### ISSUE TITLE
fwatchdog with memory leak 

### ISSUE THREAD

**Issue by mikechiuP** [openfaas/faas#1000]
fwatchdog with memory leak 

## Expected Behaviour

I run fwatchdog by docker
set up env variable with fprocess="cat /etc/hostname"
use ab to stress test
ab -n 10000 -c 100 http://localhost:8080 (port watchdog listened to) 
after stress testing, the memory cost was stable. 

## Current Behaviour

The memory cost was increased and not released normally 

## Possible Solution

ref to [issue](https://github.com/golang/go/issues/20989), use timer.AfterFunc to replace timer.NewTimer will solve this issue and it works fine of my service.

## Steps to Reproduce (for bugs)

1. run fwatchdog by docker run command: ```docker run -it --name=watchdog -p 8080:8080 --entrypoint=sh {IMAGE} ```
2. export fprocess="cat /etc/hostname"
3. fwatchdog
4. outside the docker, use ab to do benchmark ```ab -n 10000 -c 100 http://localhost:8080```
5. use ```docker stats watchdog``` could see the memory cost 

## Context

Since memory be occupied and does not be release, other containers might be crashed due to out of memory. 

Since I got the solution, I try to make a PR now. But it takes a little time to follow the guideline.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.0

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes / localhost

* Operating System and version (e.g. Linux, Windows, MacOS): Centos

* Link to your project or a code example to reproduce issue: 

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thank you very much for the PR. I'll take a look at this after the Christmas holidays.

Do you have more output data or screenshot before/after that you can share?

**Comment by mikechiuP** [comment]
@alexellis Merry Christmas!

Here is what my test steps:

original fwatchdog

![before](https://user-images.githubusercontent.com/42954621/50421016-e5bbd980-0875-11e9-8895-097a0792e1b1.png)

![after](https://user-images.githubusercontent.com/42954621/50420992-b9a05880-0875-11e9-923f-94f7cefab110.png)

## here is the dockerfile I used:
```
FROM alpine:3.8

ADD https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog /usr/bin
# uncomment to use built fwatchdog
# COPY ./fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

COPY ./fwatchdog /usr/bin/fwatchdog
# Define your binary here
ENV fprocess="/bin/cat /etc/hostname"

CMD ["fwatchdog"]
```

after docker run -p 8080:8080 watchdog:tag,
use ab command:
```
ab -n 10000 -c 100 localhost:8080/
```

Thanks for ur quickly reply!

**Comment by alexellis** [comment]
Let's see if we can reproduce the issue scientifically with taking a memory profile from `go test`?  https://dev.to/davidsbond/golang-debugging-memory-leaks-using-pprof-5di8

https://www.integralist.co.uk/posts/profiling-go/

What binary/language are you using for your DB queries? 

Alex

**Comment by mikechiuP** [comment]
> Let's see if we can reproduce the issue scientifically with taking a memory profile from `go test`? https://dev.to/davidsbond/golang-debugging-memory-leaks-using-pprof-5di8

> https://www.integralist.co.uk/posts/profiling-go/

Actually this problem seems the same as this [issue](https://github.com/golang/go/issues/20989)
The reproduced steps I posted are the same mentioned in the above issue.
 
And I totally agree about memory profile testing should be included in! 👍 
 
> What binary/language are you using for your DB queries?
We use nodejs to query neo4j via a lib.
But I think we could reproduced follow the example listed  [issue](https://github.com/golang/go/issues/20989)

Many thanks for ur help and I would see if I could do something for this, too.

**Comment by alexellis** [comment]
Derek close: merged
