### ISSUE TITLE
cant deploy functions:no such host

### ISSUE THREAD

**Issue by SequinYF** [openfaas/faas#1002]
I was trying to deploy some sample functions 

it seems that someting wrong with gateway (I am not sure), please help me.
## Expected Behaviour

`faas-cli deploy -f https://raw.githubusercontent.com/openfaas/faas/master/stack.yml`
## Current Behaviour

`Parsed: https://raw.githubusercontent.com/openfaas/faas/master/stack.yml
Deploying: hubstats.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://openfaas.endpoint.com:8080/system/functions: dial tcp: lookup openfaas.endpoint.com on 10.0.1.1:53: no such host
`
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: ` version: 0.8.1` ):
 version: 0.8.1
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm 
* Operating System and version (e.g. Linux, Windows, MacOS):
macOs
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by rgee0** [comment]
Can you help us by providing the steps to reproduce, please?  Are you running OpenFaaS locally? Do you have an OPENFAAS_URL environment variable set?

**Comment by SequinYF** [comment]
@rgee0 I was installing  openfass according to the lab2. trying to deploy function by fass-cli. how can i check my OPENFAAS_URL environment? I just do what doc said.

**Comment by rgee0** [comment]
Thanks.

Try `unset OPENFAAS_URL` or `export OPENFAAS_URL=http://127.0.0.1:8080` and then run the deploy command again.

**Comment by SequinYF** [comment]
I init docker swarm again, and it worked. I deployed functions successful. when I set alternative location by `export OPENFAAS_URL=http://openfaas.endpoint.com:8080` 
the error appears again.
`$ faas-cli list`
`Cannot connect to OpenFaaS on URL: http://openfaas.endpoint.com:8080`

**Comment by SequinYF** [comment]
> Thanks.
> 
> Try `unset OPENFAAS_URL` or `export OPENFAAS_URL=http://127.0.0.1:8080` and then run the deploy command again.
@rgee0 
It worked! thank you so so so much!!!

**Comment by rgee0** [comment]
I thought this was the case.  The command provided is meant as an example such that `openfaas.endpoint.com` should be removed and replaced with your specific endpoint.  In This instance it isn't at all necessary as you're running with the defaults.

**Comment by alexellis** [comment]
Just curious, but what file / doc page says to put `openfaas.endpoint.com` ?

**Comment by rgee0** [comment]
https://github.com/openfaas/workshop/blob/master/lab2.md#learn-about-the-cli
