### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by SequinYF** [openfaas/faas#1003]
I am trying to invoke the function. 
There has no requests lib .
`import requests
import random

def handle(req):
    r = requests.get("http://api.open-notify.org/astros.json")
    result = r.json()
    index = random.randint(0, len(result["people"])-1)
    name = result["people"][index]["name"]

    return "%s is in space" % (name)

    return req`
## Expected Behaviour

`$ echo | faas-cli invoke astronaut-finder
Anton Shkaplerov is in space`
## Current Behaviour

`Server returned unexpected status code: 500 - exit status 1
Traceback (most recent call last):
  File "index.py", line 6, in <module>
    from function import handler
  File "/home/app/function/handler.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  5b36c50280d961d3aa248bd17f901f4ef2774447
 version: 0.8.1

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.9.11
 sha:     78a4584019a2a5d86b606a00b4fba979930cc2a7
 commit:  Add sha256 hashgen for watchdog to ci config

Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.5.0
 sha:           4269ab15673ad883bfdce4df47c055588e8e86b2

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Mac
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by SequinYF** [comment]
![image](https://user-images.githubusercontent.com/19517164/50479437-8f839d80-0a11-11e9-8806-fa65f26bfbc8.png)

**Comment by alexellis** [comment]
I suspect you may have missed a step i.e. creating the requirements.txt file?

This also seems like the wrong place for an issue about this sample. Where did you find that code?

Alex

**Comment by alexellis** [comment]
I'm guessing you may be following the workshop in which case please read all the instructions under this location and if you still believe there are problems with the workshop then raise an issue on that repo.

https://github.com/openfaas/workshop/blob/master/lab3.md#example-function-astronaut-finder

Alex

**Comment by alexellis** [comment]
Btw you may also want to ask questions on Slack? https://docs.openfaas.com/community

**Comment by SequinYF** [comment]
@alexellis  Thank you.Its my mistake.
I just copy the code from the page. I dont konw how to code python at all.
![image](https://user-images.githubusercontent.com/19517164/50479786-3fa5d600-0a13-11e9-9197-577d46b6457c.png)
