### ISSUE TITLE
python - unwanted output

### ISSUE THREAD

**Issue by FlorianKuckelkorn** [openfaas/faas#1004]
Hi,

openfaas does work well :) But i have an issue when creating a python function. The moment i use external packages like for example minio python client, jaegertracing etc., these packages do print and log stuff, which later then appear in the function response => my response is getting polluted!
Any idea how to solve this?

## Expected Behaviour
function response should only include the return of my handlers function

## Current Behaviour
the function response does contain logging and printings of sub modules/packages etc.

## Possible Solution
i tried the followwing but it doesnt work:
````
import sys
from function import handler

from contextlib import contextmanager
import logging
import sys, os

@contextmanager
def suppress_stdout():
    with open(os.devnull, "w") as devnull:
        old_stdout = sys.stdout
        sys.stdout = devnull
        try:
            yield
        finally:
            sys.stdout = old_stdout

def get_stdin():
    buf = ""
    while(True):
        line = sys.stdin.readline()
        buf += line
        if line == "":
            break
    return buf

if __name__ == "__main__":
    st = get_stdin()
    with suppress_stdout():
        logger = logging.getLogger()
        logger.disabled = True
        ret = handler.handle(st)
    if ret != None:
        print(ret)
````

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.9.11

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker Swarm 18.09.0 Single Node

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi @FlorianKuckelkorn there are a couple of ways to approach this.

The first is to play with the `combine_ouput` flag which is documented in the [workshop](https://github.com/openfaas/workshop).

The second is to try the python2/3-flask template which is part of the template store:

(Update your CLI then:)

```
faas-cli template store list
```

I'll close this issue, but feel free to keep commenting.

**Comment by alexellis** [comment]
Also - if you have specific modules or examples you would like help with them please give full worked examples and we can try to address them on a case-by-case basis.

**Comment by FlorianKuckelkorn** [comment]
Hi Thanks for your reply. I decided to use the combine_output flask.
Flask seems to be interessting, but i think the latency is to high to start flask for each request

**Comment by alexellis** [comment]
Flask is not started per request. You can read about how it works with the of-watchdog in the docs.

Alex

**Comment by FlorianKuckelkorn** [comment]
Hi, i switched to flask, this also helped me to solve this issue: https://github.com/jaegertracing/jaeger-client-python/issues/229

**Comment by alexellis** [comment]
I'm glad you could switch to the of-watchdog.

Are you using the official template? Do you have it online anywhere?

Alex

**Comment by FlorianKuckelkorn** [comment]
Hi, 
i modified the official template. 

In general the template approach helps get started with openfaas in a very easy way, 
but in a production development it was literally useless: 

**Why:**
This probably goes further than this actual issue, but i would like to describe the steps i take and the obstacles i had to overcome:

1. I am building serverless functions, which do have a lot more dependencies than pip packages, so changing the Dockerfile is always needed 

=> maybe a dockerhub base image with of-watchdog etc. included would be more helpful? 

2. The idea of separating request middleware with index.py and the actual function in the handler.py is good, but also creates some side issues. 
I think in the end the concept originally was that you only need to implement the handler.py the keep the implementation as simple and straightforward as possible. 
But i always needed to change the index.py. 
I have included in the index.py so far: 

- serialization (i use a Event object which is represented as a json currently)
- i am inter-connecting each function via kafka topics so through your implementation of a kafka connection this is already a good sidecar somehow (btw: can a faas-function listen to more than one topic i didnt found that option?), but whats missing is a event publisher (i did that with a serverless function), but triggering of this function is done inside the index.py, this is a feature which should also be available by default
- distributed tracing init
- a config manager (own implementation)
- minio s3 connection handling for object access (saving results etc.)
- database connection handling, but this usually differs for each function, so maybe here a more better solution is required.

=> I think in the end its interesting to implement everything in the way that you only have to implement the handler function but this wasnt possible due my requirements

If you want to get more insight in the project and how i implemented it with openfaas, we can have a video conference if you like

**Comment by alexellis** [comment]
Many of our users would disagree including the fact that the template closely resembles the AWS Lambda signature. 

Feel free to give constructive feedback over on the python-flask repo. 

The AWS Lambda format for a Python function clearly is not useless in production given its broad usage and adoption. 

Alex
