### ISSUE TITLE
Handling request in C++ function

### ISSUE THREAD

**Issue by alishir** [openfaas/faas#1015]
I read the docs and find that for python and go languages I can implement `fun handler(byte[])` to process request data, but in the C/C++ example I couldn't find any example.

How can I process request data in C/C++ function? and does faas-cli supports C/C++ function templates?

**Comment by ivanayov** [comment]
Hi @alishir,

We don't have C/C++ template in the official templates repo, but may ask if someone from the community created such. Or raise a `help wanted` issue for making one.

There is an example of how to write a template in the [templates](
https://github.com/openfaas/templates/tree/master/template/go) repo, but I think C/C++ is more tricky as it needs options to support different compilers.

**Comment by burtonr** [comment]
@alishir I was able to create a C++ function in the past. It's absolutely possible!

The function handler recieves `stdin` as the input, and output is returned through `stdout` using the classic watchdog (the default at the moment).

I could try to put together another example for you if you'd like, or like Ivana suggested, raise an issue in the templates repo asking for a C++ template be created

**Comment by alishir** [comment]
Hi @ivanayov and @burtonr and thanks for your comments.
I created an issue for C/C++ template in templates repository: https://github.com/openfaas/templates/issues/114

**Comment by alexellis** [comment]
Hi I've commented on the issue and will close this issue since it's probably on the wrong repo here.

Alex
