### ISSUE TITLE
Remove & shutdown incorrect order (for Docker Swarm)

### ISSUE THREAD

**Issue by sribe-pearson** [openfaas/faas#1023]
Added functions & services may depend on the `func` stack such that it cannot be shut down without first removing those functions.

## Expected Behaviour

Following along the docs for setting up in Docker Swarm, then installing the demo funcs, the instructions at https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md#stop-and-remove-openfaas should work.

## Current Behaviour

Instead, `docker stack rm func` fails with an error about a dependency.

## Possible Solution

Reverse the order of the steps. Remove services first, then remove the func stack.

**Comment by alexellis** [comment]
Please feel free to submit a PR to the documentation site openfaas/docs. I'll remove the text in this file you linked to and think make it redirect to the docs site.

Alex

**Comment by alexellis** [comment]
Turns out this is already fixed in the docs. https://docs.openfaas.com/deployment/troubleshooting/

Thanks for letting us know.

Alex
