### ISSUE TITLE
Function Invocation overhead

### ISSUE THREAD

**Issue by Vad1mo** [openfaas/faas#1029]
I am experimenting with OpenFaas on local Minikube.  

The example [golang-http](https://github.com/openfaas-incubator/golang-http-template/tree/master/template/golang-http)
and my own similar function have a constant (>5s) execution overhead.

Is +-4000ms a common invocation overhead that one has to expect when triggering functions? 
Is there room for improvement in the current state of the project?

I was expecting the total time to be 5-15% more. Something around 600-1000ms. 
Direct service invocation without OpenFaas is around 400-600ms.

Btw. There is no scale to zero so the function is constantly deployed. 

```sh
OSS time http http://kube.local:31112/function/openfaas-sample
HTTP/1.1 200 OK
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Date: Mon, 14 Jan 2019 02:42:18 GMT
X-Call-Id: 7126ba7a-364a-4114-a7ff-8e588fa09824
X-Duration-Seconds: 0.000491
X-Start-Time: 1547433738152440913

Hello world, input was:

http http://kube.local:31112/function/openfaas-sample  0,36s user 0,11s system 8% cpu 5,596 total
```

I don't have a slow computer per se, it is an i7 MacBook Pro, Mid 2014

**Comment by Vad1mo** [comment]
ok, removed docker, minikube, and virtualbox:
Tried now with minikube on virtualbox and kind on docker for mac.
In both cases I get the expected results of `0,044s`

Next will try again with minikube on hyperkit, to see if anything changes.

**Comment by alexellis** [comment]
Hi @Vad1mo, I'm glad we could help with suggestions given on Slack and thanks for using OpenFaaS.

I'll close this issue now. Let us know if we can help again and welcome to the community 

Alex
