### ISSUE TITLE
Proposal: Jupyter Notebook as function template  

### ISSUE THREAD

**Issue by cmrfrd** [openfaas/faas#1030]
Currently there are several [template language](https://github.com/openfaas/templates) implementations and several amazing functions (such as [inception](https://github.com/faas-and-furious/inception-function)) for openfaas. These are amazing implementations however there is alot of overhead to rewrite some functions (such as inception) which were [originally developed](https://github.com/Hvass-Labs/TensorFlow-Tutorials) in Jupyter Notebooks (sometimes, not always). 

Exporting, rewriting, and packaging code from notebooks is a costly effort and can be avoided by using newer tools (such as [papermill](https://github.com/nteract/papermill) ) to execute and extract desired outputs (images, html, json, etc...) . 

Therefore it would be worthwhile to make a base template for executing Jupyter Notebooks. This can be done by providing a POST requests' json payload as paramaters to a Jupyter Notebook, executing that notebook in your [desired language kernel](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) , and parsing the [`Http_Accept`](https://github.com/openfaas/faas/tree/master/watchdog#working-with-http-headers) mime-type as the return [Jupyter Notebook output mime-type](https://nbformat.readthedocs.io/en/latest/format_description.html#code-cell-outputs) and return it as stdout. 
 
With this, OpenFaas can expand it's serverless capabilities by using Jupyter Notebooks as serverless functions.

This is already [being done by awslabs](https://github.com/awslabs/aws-iot-analytics-notebook-containers) but only works tightly with ECR and geared towards integrating with SageMaker

## Possible Solution

I have hacked together an [example implentation](https://github.com/cmrfrd/serverless_notebooks) of this idea as a repo before creating a PR. Let me know if this is worthwhile!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi @cmrfrd if you'd like to create your own template then please do and submit it to the template store when you're done 👍 

Alex

**Comment by alexellis** [comment]
Derek close: resolved

**Comment by alexellis** [comment]
https://www.openfaas.com/blog/template-store/

**Comment by LucasRoesler** [comment]
This could work well as an async function, but a synchronous function is going to frequently run up to timeout issues.  But creating a template that accepts a requirements file and an ipynb file.  The function could call nbconvert on the provided ipynb.  

https://github.com/takluyver/nbparameterise can also be used to pass values to the notebook
