### ISSUE TITLE
Proposal: fine-tuning of reverse proxy http.Client

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1033]
## Expected Behaviour

For performance-tuning we should be able to toggle the behavior of the http.Client used as a reverse proxy for functions. This may include:

- keep alive on/off
- keep alive duration
- max conns per host
- max idle con time

## Current Behaviour

Manual changes would be needed to the gateway to adjust these numbers.

## Possible Solution

* Read env-vars and when they are not present, use the defaults.

**Comment by LucasRoesler** [comment]
I like the idea of allowing tuning of these values at deploy time.  This will definitely require a documentation update to give a thorough overview of what the values are and situations where they should change.

Is it possible that someone would want to control these values per function?

**Comment by bartsmykla** [comment]
I also think that it's a very good idea

**Comment by pcsx22** [comment]
Hi Alex,

Changing the fields such as DisableKeepAlive, KeeplAlive, MaxIdleConnsPerHost, IdleConnTimeOut of http.Transport{} in proxy_client.go should achieve the expected behaviour. I have some extra time these days so, let me know if I should submit a PR.

**Comment by alexellis** [comment]
Done via #1039
