### ISSUE TITLE
Update docker-compose.yml to version `0.10.1` of the gateway

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/faas#1051]
We want to update docker-compose.yml file to take into account the newest version of the gateway (`0.10.1`)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by rdimitrov** [comment]
This can be considered as done, right?

**Comment by rdimitrov** [comment]
@alexellis This can be considered as done, right?

**Comment by alexellis** [comment]
Can you check and confirm please @rdimitrov ?

**Comment by rdimitrov** [comment]
Currently, all three docker-compose files are using `openfaas/gateway:0.10.2` 👍

**Comment by alexellis** [comment]
👍
