### ISSUE TITLE
Proposal: allow to add request headers as additional labels to metrics

### ISSUE THREAD

**Issue by swachter** [openfaas/faas#1052]
We would like to record the user that invoked a function. For that means we would like to add an HTTP header to the request and use the header name and its value as an additional label for Prometheus metrics.

The names of HTTP headers that are used to label metrics should be configurable either globally or for each function separately.

**Comment by alexellis** [comment]
Hi @swachter,

This is not a common pattern for Prometheus metrics - they usually only record PATH, STATUS, METHOD and the latency observed.

What is the concrete use-case behind wanting to record all HTTP headers? If you can elaborate on this we may be able to make some suggestions for you.

I don't believe this is a common use-case for OpenFaaS users so I am yet to see the value in this being part of the main project. In OpenFaaS Cloud we wrote a small proxy which sits in front of the gateway for additional routing for users, you could perhaps do something similar and create your audit trail that way?

Alex

**Comment by swachter** [comment]
In our particular use case we want to give a user the history of her calls. If measurements where labeled with a user, then the call history for a user could directly be retrieved from Prometheus.

Another use case is to label a measurement with a "callId" that is used to trace distributed processing.

In general there might be uses cases where not only runtime information about the function that is called might be of interested but also information about by whom the function was called. Sure, additional information could be accessed from other sources (e.g. ingress logs). But then one would at least need a correlation id.

**Comment by swachter** [comment]
I think my proposal is - in general - not a great idea. From the Prometheus docs (https://prometheus.io/docs/practices/naming/):

CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

Is there another possibility to get a call history for a user containing timing and status?

**Comment by alexellis** [comment]
> In our particular use case we want to give a user the history of her calls.

If the endpoint is accessible by anyone. How do you know that the specific user made those calls?

**Comment by swachter** [comment]
The plan was to extract the user info from the authorization header containing either basic authorization or a bearer identity token. The user info would be copied into the a custom header inside Ambassador using an external Ambassador authorization service. However, that plan is not feasable because Prometheus labels should not be used in this way. (I have experiences with InfluxDB where tags can be used to attach meta data to measurements. I erroneously assumed that Prometheus labels can be used similarly.)

From my point of view this ticket can be closed.

The question however remains, how a call history can be implemented. As of now I only see the  possibility of implementing a custom ingress in front of the OpenFaaS gateway. That ingress could write a "call log". In addition, it could intercept callbacks of asynchronous function calls in order to asynchronous results too.

**Comment by alexellis** [comment]
Derek close
