### ISSUE TITLE
Proposal: Identity and Access Management

### ISSUE THREAD

**Issue by 7hibault** [openfaas/faas#1058]
Hey, thanks for OpenFaaS :-)

## Summary

I'm trying to get away from AWS Lambdas, but I find that identity and access management is missing from OpenFaaS when calling the functions. [From the doc:](https://docs.openfaas.com/reference/authentication/)

> Functions exposed on OpenFaaS often do not need to have authentication enabled, this is because they may be responding to webhooks from an external system such as GitHub or Patreon. Neither GitHub, nor Patreon will support authenticating with OAuth or basic authentication strategies, but rely on HMAC.

Ok for GitHub or Patreon. But I can think of several use cases where it would be useful to have identity and access management, such as:

* My functions exposed by OpenFaaS make up a public API used by a web app where users are authenticated. 
* For monitoring purposes, I want to know which user called which function.
* Some functions can only be executed by users who have a certain role.

In an AWS architecture, we could be using Cognito for that purpose. In a microservice architecture, we could use something like [keycloak](https://www.keycloak.org/) or handle it manually.

## Expected behaviour

We should be able to authenticate users and control their access to functions, similarly to what can be done using AWS Cognito.

## Context

I personally want to use this feature to control access to a serverless API.

**Comment by alexellis** [comment]
Hi,

Thanks for your suggestion.

The way I read this sounds like you are asking for "identity and access management". I don't know what you mean by this since it's not a concrete feature, but an entire ecosystem.

What specific parts experience or use-cases are missing for you? If we work backwards from there with specifics I may be able to make some suggestions for you.

Some of our users use oauth2proxy, some use Kong in front of the API Gateway and in our [OpenFaaS Cloud](https://github.com/openfaas/openfaas-cloud) project we use OAuth for authz.

Alex

**Comment by alexellis** [comment]
Hi @7hibault please see the comment above.

I'll close this issue having not heard back from you on specific use-cases and requirements.

Please feel free to keep commenting and to join Slack to talk more.

Alex

**Comment by Jarzamendia** [comment]
I am studying an implementation for production. I think your case could be solved by using Kong as the frontend, and Keycloak to provide JWT tokens. I already saw a similar implementation for REST API's where Kong allowed access only when a token was generated for a particular consumer.
If I remember correctly, the environment used the JWT and ACL plugins.

**Comment by alexellis** [comment]
Thank you for reaching out. You can access this functionality in alpha now https://docs.openfaas.com/reference/authentication/
