### ISSUE TITLE
Swagger documentation for labels, annotations incorrect, read-only element is missing

### ISSUE THREAD

**Issue by noppen** [openfaas/faas#1059]
The Swagger documentation for labels, annotations is currently incorrect as they are listed as arrays, while the API expects them as dictionaries. Also the read-only element and description is missing in the Swagger doc.

I am happy to update these.

**Comment by alexellis** [comment]
Thank you for reporting this Joost. I would like to see this fixed up.

**Comment by acornies** [comment]
@alexellis @noppen Please check #1061
