### ISSUE TITLE
Upgrade Prometheus to v2.6.1

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1062]
## Expected Behaviour

We need to upgrade Prometheus to v2.6.1 as per https://github.com/openfaas/faas-netes/pull/363 for consistency between Swarm and Kubernetes.

## Current Behaviour

We are still on an older version

## Possible Solution

PRs will be needed for:

* docker-compose.yml

* docker-compose.armhf.yml

* docker-compose.arm64.yml

A new Dockerfile will be needed in the ./contrib/ folder for the ARM versions.

**Comment by alexellis** [comment]
Please wait for go ahead from @stefanprodan before working on this, we may switch to 2.7.0 which was just released on the Prometheus project.

**Comment by rdimitrov** [comment]
With the latest changes, this one probably can be considered as done, right?

**Comment by alexellis** [comment]
Got the all clear from @stefanprodan on Prometheus 2.7.0 so I think we can close since you sent PRs for those images 👍

**Comment by alexellis** [comment]
Thanks 👍 

Did we update docker-compose.yml already too?

**Comment by rdimitrov** [comment]
All three docker compose files use `2.6.1` at the time of writing and the PR for 2.7.0 was only to add it as build folders without any further changes to the compose files.

**Comment by alexellis** [comment]
The images for 2.7.0 are published now, so we can do PRs to move across.

Alex

**Comment by rdimitrov** [comment]
That's great :+1: Here it is then - https://github.com/openfaas/faas/pull/1077
