### ISSUE TITLE
OpenFaas Nodejs Cronjob?

### ISSUE THREAD

**Issue by JohnOllhorn** [openfaas/faas#1073]
Hi, guys,
I have more of a question than a problem, but I don't know where to ask it.

I need a way to get an asynchronous Nodejs in OpenFaas which is started by a cronjob and not by a request?! @_@

It would be also best if there would be a possibility to start these services automatically (cronjob) and to delete them after completion...

Is there still the possibility to run several OpenFaas services parallel?

Is this possible with OpenFaas?

**Comment by alexellis** [comment]
Hi @JohnOllhorn please see the docs page on this: https://docs.openfaas.com/reference/cron/#scheduling-function-runs

@zeerorg also has a project he's working on https://github.com/zeerorg/cron-connector

Alex

**Comment by alexellis** [comment]
Derek close: question answered
