### ISSUE TITLE
Introduce Kubernetes healthz endpoint

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#108]
Kubernetes has a convention of a healthz endpoint on port 10254.

* Introduce this for the watchdog / gateway etc.

**Comment by e-beach** [comment]
I'm interested in working on this. Under what circumstances should the watchdog and gateway return a failing status?

**Comment by alexellis** [comment]
So for the watchdog let's start by returning everything is OK once the lock
file is in place - then go from there. You'll also need to update
faas-netes to programmatically add the healthcheck and readiness probe to
new functions.

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by e-beach** [comment]
I wasn't working on this for a while while I figured things out, going to come back to this now.

**Comment by e-beach** [comment]
@alexellis 
I'm having trouble understanding what this has to do with the watchdog.
If we configure a request in the Probe section of the container, kubernetes will periodically ping the container, but the proxy only involves POST requests, so when does the watchdog code need to be changed?
Healthcheck:
https://github.com/e-beach/faas-netes/blob/b1fde54e1e62f0a108a017f31a2307346a6db698/handlers/deploy.go#L139-L144

**Comment by alexellis** [comment]
Ping the watchdog how? We do not want to invoke the function to check it for readiness. This is what I'd expect would be needed:

* A new healthz route for the watchdog.
* A Kubernetes configuration to add readiness probe to the deployment / pod spec

**Comment by InTheCloudDan** [comment]
@elliott-beach are you still working on this PR? If not I'd like to take a shot at seeing if I can figure it out.

**Comment by elliott-beach** [comment]
@InTheCloudDan mostly addressed in https://github.com/openfaas/faas-netes/pull/33, there is  still a dangling thread of the readiness probe as mentioned in https://github.com/openfaas/faas-netes/pull/33#issuecomment-335032333.

**Comment by BurtonR** [comment]
@alexellis Is this still needing work? It's been a while, and the [faas-netes PR](https://github.com/openfaas/faas-netes/pull/33) has been merged.

Not sure if either @InTheCloudDan or @elliott-beach  are still interested in getting this over the line (assuming there's still something left to do). If they're not, I could dive in and try to close this out

**Comment by alexellis** [comment]
I've added a health endpoint but it's currently Judy returning OK which is slightly better than not having one. I'll close the issue since I think it has been resolved now

**Comment by stefanprodan** [comment]
The gateway needs a `healthz` endpoint so we can avoid hacks like this one https://github.com/stefanprodan/openfaas-gke/blob/master/openfaas-tls/caddy-cfg.yaml#L12

Without this endpoint there is not possible to expose the gateway via a K8S Ingress controller.

**Comment by alexellis** [comment]
@stefanprodan we have this now at the provider level.. but do we need to add it to the gateway still? If so would you mind opening an issue?

**Comment by alexellis** [comment]
@InTheCloudDan if you fancy working on this let us know. It should be relatively straight-forward to add.
