### ISSUE TITLE
Proposal: move /metrics to a separate HTTP port

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1081]
## Task

We should move the /metrics/ path scraped by Prometheus for internal use to a separate HTTP port. This separates concerns.

## Possible Solution

* Figure out the port we want to use (not 8081, since that clashes with the provider)
* Add another HTTP server
* Bind the handler from Prometheus
* Update helm chart, YAML and docker-compose for all platforms.
* Test end to end

**Comment by viveksyngh** [comment]
I would like to work on this one.

**Comment by alexellis** [comment]
You can assign it with Derek

**Comment by viveksyngh** [comment]
Derek assign: me
