### ISSUE TITLE
runc processes for functions constantly spawning

### ISSUE THREAD

**Issue by nyasara** [openfaas/faas#1086]
When adding and scaling functions to an OpenFaas deployment running on Docker Swarm, runc processes are constantly exeucting for each instance of each function, and containerd-shim is consistently using 0.7% CPU per container

## Expected Behaviour
Idle functions doing no work should use little to no CPU

## Current Behaviour
Extensive CPU is being used, even when functions are idle, about 1% of the processor per instance deployed

## Steps to Reproduce (for bugs)
1. Deploy OpenFaas via Docker Swarm
2. Deploy one or more functions to OpenFaas
3. Scale functions above 1

## Context
This issue is causing extreme performance degradation as half or more of CPU resources on each Swarm node is being consumed.by containerd-shim and runc.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Not using FaaS-CLI

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.09.01

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

Nothing in the troubleshooting guide references this problem.  The functions are executing, just with reduced speed because other resources are being consumed.  Below are example lines from an auditd log, note that runc is running on the same docker container over and over, but `docker ps` shows the container continuously running (not like it is exiting and restarting).
```
type=EXECVE msg=audit(1550080419.553:16698): argc=9 a0="runc" a1="--root" a2="/var/run/docker/runtime-runc/moby" a3="--log" a4="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e/log.json" a5="--log-format" a6="json" a7="state" a8="d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=CWD msg=audit(1550080419.553:16698):  cwd="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=EXECVE msg=audit(1550080420.089:16735): argc=9 a0="runc" a1="--root" a2="/var/run/docker/runtime-runc/moby" a3="--log" a4="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e/log.json" a5="--log-format" a6="json" a7="state" a8="d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=CWD msg=audit(1550080420.089:16735):  cwd="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=EXECVE msg=audit(1550080420.389:16771): argc=9 a0="runc" a1="--root" a2="/var/run/docker/runtime-runc/moby" a3="--log" a4="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e/log.json" a5="--log-format" a6="json" a7="state" a8="d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=CWD msg=audit(1550080420.389:16771):  cwd="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=EXECVE msg=audit(1550080422.541:16934): argc=9 a0="runc" a1="--root" a2="/var/run/docker/runtime-runc/moby" a3="--log" a4="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e/log.json" a5="--log-format" a6="json" a7="state" a8="d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
type=CWD msg=audit(1550080422.541:16934):  cwd="/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d648526189b7116c6c11a8b28d450eba4acff121a6a502c84e45a4c0b26aaf9e"
```

This runs continuously until the service are scaled down to 0.

**Comment by nyasara** [comment]
I may have figured out at least part of the issue.  I removed the HEALTHCHECK from the Dockerfile that bulds these functions (it was based on the python3 template Dockerfile), and rebuilt, and there is no longer a containerd-shim issue.  This might be my environment, apparently our rack has I/O issues, and since the healthcheck is looking for a file it may have simply been stalling too much time on I/O. The runc executions I'm guessing are how the healthchecks are run by the underlying Docker engine.  This can probably be closed.

**Comment by viveksyngh** [comment]
Derek close
