### ISSUE TITLE
Typo in faas-examples readme

### ISSUE THREAD

**Issue by kayh-de** [openfaas/faas#1088]
The readme tells about a `git-maker` instead of a `gif-maker`. Hence I added a tiny MR. See #1087.
## Expected Behaviour

gif instead of git

## Current Behaviour

git
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Derek close: fixed
