### ISSUE TITLE
Proposal: Add graceful shutdown for gateway

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas#1090]
Add graceful shutdown for gateway HTTP Server

## Expected Behaviour

When gateway HTTP server shut down, it should finish all in progress requests and shut down gracefully. 

## Current Behaviour

It does not shutdown gracefully.

## Possible Solution

Look at watchdog code, it is already implemented there.

**Comment by saurabh-ku** [comment]
I would like to work on this issue. I think I have found the place where we do graceful shutdown in [watchdogs](https://github.com/openfaas/faas/blob/master/watchdog/main.go#L83).However I am unable to find where i have to make the change in the gateway. 

Can you please help me with that?

**Comment by alexellis** [comment]
Hi @saurabh-ku, this is one that I believe Vivek is taking, but we can find you something else just as interesting. Please join us in #contributors on Slack.

https://openfaas.o6s.io/slack/

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Where are we on this?

**Comment by viveksyngh** [comment]
I will start working on this.
