### ISSUE TITLE
Ability to specify the port in the deploy script as an argument

### ISSUE THREAD

**Issue by linuxjuggler** [openfaas/faas#1091]
The `docker-compose.yml` file has the port for the UI hardcoded, so a small change to the `deploy_stack` file and `docker-compose.yml` will allow to dynamically change it without editing any file directly.

## Expected Behaviour
An example for the suggested changes:

```
./deploy_stack.sh --port 80
```
This will allow the UI to run on port 80 instead of 8080.

Also the same would be for `deploy_stack.armhf.sh`

## Current Behaviour
Right now `deploy_stack.armhf.sh` does not accept any argument, mean while `deploy_stack.sh` accept only accepts `--no-auth` and `--help`.

## Possible Solution

1. Edit the `deploy_stack.sh` to export the environment variable 
```
export DEFAULT_PORT="8080"

while [ ! $# -eq 0 ]
do
  case "$1" in
    --port | -p)
      if [ ! -z "$2" ];
      then
        export DEFAULT_PORT=$2
      fi
      ;;    
    --no-auth | -n)
      export BASIC_AUTH="false"
      ;;
    --help | -h)
      echo "Usage: \n [default]\tdeploy the OpenFaaS core services\n --no-auth [-n]\tdisable basic authentication.\n --port [-p]\tdefine a new exposed port for the UI.\n --help\tdisplays this screen"
      exit
      ;;
  esac
  shift
done
```

2. Edit the `docker-compose` files to use the environment variable 
```
version: "3.3"
services:
    gateway:
        ports:
            - ${DEFAULT_PORT}:8080
```

3. Edit `deploy_stack.armhf.sh` and pass the arguments 
```
sh ./deploy_stack.sh $1 $2
```

## Context
This will help to change the port for the UI without any manually edit to the files, not sure if this is something people may find useful or not.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ): 
0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux/Mac

* Link to your project or a code example to reproduce issue:
https://github.com/linuxjuggler/faas/commit/b9fc73a1e370051f1528c127be9138373e3c0ce8

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by LucasRoesler** [comment]
Hi @linuxjuggler, I am not sure this is something we want to do.  It might suggest that the gateway is ready to be exposed on a secure port like 443 when it isn't.  In a production deployment, it is recommended that the gateway be exposed via a load balancer like nginx, which can then change the public port to be 80 as well as supporting ssl and other features required to securely expose the gateway.

Is there a specific use-case that you are trying to solve by changing the port?  

Especially for swarm, I think we would be better served by providing a walk through on customizing the deployment in the docs and making special notes about security concerns that need to be considered when making certain changes.

**Comment by LucasRoesler** [comment]
Derek add label: wontfix
Derek add label: revist
Derek close

**Comment by LucasRoesler** [comment]
Derek remove label: wontfix Derek add label: revist Derek close

**Comment by linuxjuggler** [comment]
hey @LucasRoesler , thanks for the feedback

> Is there a specific use-case that you are trying to solve by changing the port?

There is no special cause I am trying to solve here, except than manually editing the yaml files.

> it is recommended that the gateway be exposed via a load balancer like nginx

This is what I just did, thanks for the note.

> Especially for swarm, I think we would be better served by providing a walk through on customizing the deployment in the docs and making special notes about security concerns that need to be considered when making certain changes.

Totally agree with you about that, for example, the docs do not explain where the CLI should installed, which is something am still trying to figure out.

Either way, thank you very much again for the feedback 👍

**Comment by alexellis** [comment]
Derek add label: wontfix
