### ISSUE TITLE
Support question: how to use tensorflow-serving with OpenFaaS

### ISSUE THREAD

**Issue by spaghettifunk** [openfaas/faas#1093]
I am facing a problem where I'd like to use OpenFaaS to serve my Tensorflow models in production. The whole idea is that the user is able to deploy Tensorflow Serving and calling the model with invoke. I am still a newbie in OpenFaaS and after seeing the example of [python flask](https://github.com/openfaas-incubator/python-flask-template) I thought I could replicate the same sort of idea to tensorflow serving. I also opened a question on [stackoverflow](https://stackoverflow.com/questions/54750562/openfaas-serve-model-using-tensorflow-serving) in case.

## Problem

OpenFaaS is running correctly on Kubernetes and I am able to invoke functions via `curl` or from the `UI`. 

I used the `python-flask` as example, but I keep receiving `502 Bad Gateway` all the time.

The project looks like the following (very simple)

```
serve/
  - Dockerfile
stack.yaml
```

The inner `Dockerfile` is the following

```dockerfile
FROM tensorflow/serving

RUN mkdir -p /home/app

RUN apt-get update \
    && apt-get install curl -yy

RUN echo "Pulling watchdog binary from Github." \
    && curl -sSLf https://github.com/openfaas-incubator/of-watchdog/releases/download/0.4.6/of-watchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog

WORKDIR /root/

# remove unecessery logs from S3
ENV TF_CPP_MIN_LOG_LEVEL=3

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}
ENV S3_ENDPOINT=${S3_ENDPOINT} 

ENV fprocess="tensorflow_model_server --rest_api_port=8501 \
    --model_name=${MODEL_NAME} \
    --model_base_path=${MODEL_BASE_PATH}"

# Set to true to see request in function logs
ENV write_debug="true"
ENV cgi_headers="true"
ENV mode="http"
ENV upstream_url="http://127.0.0.1:8501"

# gRPC tensorflow serving
# EXPOSE 8500

# REST tensorflow serving
# EXPOSE 8501

RUN touch /tmp/.lock
HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1

CMD [ "fwatchdog" ]
```

the `stack.yaml` file looks like the following

```yaml
provider:
  name: faas
  gateway: https://gateway-url:8080

functions:
  serve:
    lang: dockerfile
    handler: ./serve
    image: repo/serve-model:latest
    imagePullPolicy: always
```

I build the image with `faas-cli build -f stack.yaml` and then I push it to my docker registry with `faas-cli push -f stack.yaml`.

When I execute `faas-cli deploy -f stack.yaml -e AWS_ACCESS_KEY_ID=... -e MODEL_NAME=serve ...` I get ` Accepted 202` and it appears correctly among my functions. Now, I want to invoke the `tensorflow serving` on the model I specified in my `ENV`.

The way I try to make it work is to use `curl` in this way

```shell
curl -d '{"inputs": ["1.0", "2.0", "5.0"]}' -X POST https://gateway-url:8080/function/deploy-model/v1/models/mnist:predict
```
but I always obtain `502 Bad Gateway`.

Does anybody have experience with OpenFaaS and Tensorflow Serving? Thanks in advance

**P.S.** 

If I run `tensorflow serving` without `of-watchdog` (basically without the openfaas stuff), the model is served correctly.

**Comment by alexellis** [comment]
Hi, @spaghettifunk 

I see you've removed the template we need you to use, please could you fix that? FYI the template is not optional and does include a link to a troubleshooting guide that instructs you how to find the logs for a function and why it may be failing.

If you try my suggestions and still can't figure it out on your own then upload the model somewhere and I'll see if there is anyone in the community who can volunteer to spend time looking into your problem.

Alex

```
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behaviour
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behaviour
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
```

**Comment by spaghettifunk** [comment]
Hi @alexellis. I will rewrite my question using the template. Sorry for the trouble :)

**Comment by alexellis** [comment]
I don't have your model, but took some time out to write up a full guide for you here:

https://github.com/alexellis/tensorflow-serving-openfaas

Let us know how you get on.

Alex

**Comment by spaghettifunk** [comment]
wow thanks!! I will go through it and let you know. Thanks once again!
