### ISSUE TITLE
Update AlertManager & Prometheus to match faas-netes

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1095]
## Expected Behaviour

Update AlertManager & Prometheus for Swarm to match faas-netes

## Current Behaviour

We found some behavioural changes in faas-netes after upgrading to the latest version of both tools. @LucasRoesler made some fixes to the helm chart / YAML for Kubernetes, which we need to bring across to this version of OpenFaaS.

## Possible Solution

Follow example given by Lucas in his PR here -> https://github.com/openfaas/faas-netes/pull/373

cc @LucasRoesler

**Comment by LucasRoesler** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek lock
