### ISSUE TITLE
How to keep functions warm?

### ISSUE THREAD

**Issue by steveyangrh** [openfaas/faas#1097]
How to enable warm start for openfaas (just like AWS lambda) ?

## Expected Behaviour

I expect variables initialized above the actual handler function are cached when users make consecutive calls, only the first call executes the initialization step and the following calls can simply call the actual handler function without initializing variables again. AWS Lambda has this feature, any code above the function lambda_handler is only called once, after the first invocation, only code in function lambda_handler gets executed. 

`    

    from keras.models import load_model

    import time

    model = load_model("some/where/model")

    time.sleep(5)

    def handle(req):   
        features = model.predict(imgs,
                                verbose = 0,
                                batch_size=1)    
        return req
`

For this piece of code, I except `model = load_model("./function/model/vgg16.h5")` and `time.sleep(5)` only get executed once in the first call.

An overview of AWS Lambda warm start is [here](https://blog.octo.com/en/cold-start-warm-start-with-aws-lambda/)
    
## Current Behaviour

For the current version of openfaas, when a function is triggered, every line of code is executed again, without using any of the previous initializations.

## Possible Solution

1. Afterburn, not sure if this is what i need
2. A separate initialization step?

## Context

I am running a tensorflow function on openfaas, the initialization step takes a relatively long time (1-1.5s compared to 0.5s(actual function code that does the thing)),  

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.06.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 14.04

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by steveyangrh** [comment]
By the way, if Afterburn is what I need, may I know where I can find the template for Python

**Comment by alexellis** [comment]
The functions are warm, what you are seeing is your process being forked once per request. If you want to have stateful memory then you need to us the of-watchdog templates. FYI Afterburn is deprecated, I don't know where you found recent documentation about that to suggest otherwise?

Use this template which will allow you to load your model once and re-use it:

```
faas-cli template store list
faas-cli template store pull python3-flask
```

Alex
