### ISSUE TITLE
Proposal: Add platform field to the OpenFaaS store

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1099]
## Expected Behaviour

All components should be ready to parse differentiate a platform field for the OpenFaaS store.

* faas-cli in openfaas/faas-cli
* OpenFaaS UI in openfaas/faas

We'd introduce a platform field like we currently use in the template store to categorise.

As a related change the UI/FaaS-CLI should determine architecture in some way at build or runtime and then use that to filter automatically. For the CLI this should be overridable, but by default act to do the least surprising thing.

## Current Behaviour

* The UI has a hard-coded URL
* The faas-cli defaults to x86_64 which is confusing and needs a long git-raw/CDN URL as an override. This is less than obvious and lead to: https://github.com/openfaas/docs/pull/130 and  https://github.com/openfaas/faas-cli/issues/467

For a list of convention / naming on architectures/platforms see the templates.json file in the openfaas/store repo.

## Possible Solution

We can't introduce a breaking change so I would suggest adding a new file called openfaas/store/functions.json rather than making those changes to store.json.

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
I moved all the functions in single `functions.json` file and appended `"platform": "..."` to all the existing functions, depending on the file from which they were taken 👍

**Comment by alexellis** [comment]
Where are we with this @martindekov  ?

**Comment by martindekov** [comment]
I took the part of the creation of the json file. I believe @viveksyngh took the part of the cli and @burtonr took the UI part? Otherwise the comment 
>I moved all the functions in single functions.json file and appended "platform": "..." to all the existing functions, depending on the file from which they were taken 👍 

was amended to the the [merged](https://github.com/openfaas/store/pull/63) PR

**Comment by alexellis** [comment]
@burtonr @viveksyngh do you have updates please?

**Comment by viveksyngh** [comment]
I have this PR .. I need to address some of the review comments. Also It has some conflicts, So I will rebase it.

https://github.com/openfaas/faas-cli/pull/620

**Comment by burtonr** [comment]
I don't have an update for this as there are comments on #1145  from @zeerorg indicating he would be working on it. Although there hasn't been an update in a while...

**Comment by alexellis** [comment]
I think @zeerorg may be away, @burtonr could you run with this?

**Comment by burtonr** [comment]
Sure thing!

**Comment by zeerorg** [comment]
The UI part was done in PR https://github.com/openfaas/faas/pull/1153 which was merged a while back
