### ISSUE TITLE
http_requests_total metric does not have synchronous function invocations

### ISSUE THREAD

**Issue by mosaic141688** [openfaas/faas#1104]
## Expected Behaviour

After making synchronous requests to `/function/{functionName}` the `http_requests_total` metric should have data for `path="/function/{functionName}"`

## Current Behaviour

After making synchronous requests to `/function/{functionName}` the `http_requests_total` metric does not  have data for `path="/function/{functionName}"`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
This is correct, this data is already documented and recorded in a separate metric since the project began in 2016.

https://docs.openfaas.com/architecture/metrics/#monitoring-functions
