### ISSUE TITLE
Question: long-running async jobs

### ISSUE THREAD

**Issue by cabrerabywaters** [openfaas/faas#1108]
## Expected Behaviour
When scaling the queue-worker all messages should be processed only one time.

## Current Behaviour
I have a long-running task (around 1 minute) that generates a PDF. If I use the queue worker as it comes it processes (1 node) everything works as expected. But as soon as I scale the queue-worker some of the messages get duplicated (randomly, and not all of them)

I tried scaling the queue-workers and leaving the function with only 1 replica and also with multiple replicas and in both scenarios got the same issue

I triggered the function 8 times
 https://www.dropbox.com/s/pth6fnzurato1e3/Screenshot%202019-02-28%2017.22.42.png?dl=0

and got 17 callbacks
https://www.dropbox.com/s/pljs24mqlsobeh0/Screenshot%202019-02-28%2017.23.44.png?dl=0

## Possible Solution
Maybe the messages are not being properly removed after processed or locked during the execution?

## Steps to Reproduce (for bugs)
1. Scale to 2 queue-workers
2. Execute many async functions with X-Callback-Url
3. Check on https://pipedream.com or other endpoint the callback calls

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
faas-cli: 0.8.3
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes FaaS-netes
queue-worker:0.7.0
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by alexellis** [comment]
Hi thanks for using OpenFaaS and for your interest.

I'm guessing that this may be due to the job being not ack'd in time and then being retried.

Please checkout the troubleshooting guide to find out more about how to configure the timeouts and see if this helps. https://docs.openfaas.com/

Alex

**Comment by cabrerabywaters** [comment]
Thank you @alexellis, 

Maybe the docs are not so clear in this sense as I only found this:

"You can tune the values for the number of tasks each queue worker may run in parallel as well as the maximum duration of any asynchronous task that worker processes. Edit the Kubernetes helm chart, YAML or Swarm docker-compose.yml files."

Maybe is a good idea to include the part of the helm chart that we are supposed to edit and instructions on how to change the config again?
"
queueWorker:
  image: openfaas/queue-worker:0.7.0
  ackWait : "60s"
  replicas: 1
"
It's a little bit tricky to find the right place for configs (im just getting started with FaaS [wonderful job btw!!]). It feels that the queue part is still somehow separated from FaaS, maybe this config could be done using the FaaS-cli for better user experience?
Will change the config and let you know how it goes!
Thank you

**Comment by cabrerabywaters** [comment]
Ok, made the change and it works perfectly, 8 messages 8 posts.

Thank you once again @alexellis

**Comment by alexellis** [comment]
Thanks for your suggestions, I'll pass them on to the community.

If you have further questions, please don't hesitate to read the docs, search past issues or join the Slack community to ask there.

Alex
