### ISSUE TITLE
Node Hmac validation

### ISSUE THREAD

**Issue by cabrerabywaters** [openfaas/faas#1110]
Hey everyone!

I just wrote a tiny library to do the Hmac checking for the functions using Node.JS (The examples that I found use Python) and included some (hopefully) useful documentation for future reference

Feel free to use it and change it as you want!
https://github.com/cabrerabywaters/faas-node-gatekeeper

**Comment by alexellis** [comment]
That's really cool. Could you submit it to the community.md file in the projects section?

Are you connected on Slack yet too? https://docs.openfaas.com/community

Thanks,

Alex

**Comment by cabrerabywaters** [comment]
@alexellis 
Sure will do it right away
Not yet on slack, will go do it now ;) Thanks
