### ISSUE TITLE
Proposal: slack slash command function template(s)

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#1115]
The OpenFaaS Lab walks through creating a Github webhook.  This is a great walkthrough especially because Github is so popular.  Slack slash commands are conceptually similar and the service is similarly popular.  

We should research slack frameworks in the popular languages and provide OpenFaaS templates for creating slack slash commands.  For example, in Go https://github.com/shomali11/slacker or Google Cloud provides a walk through using node or python https://cloud.google.com/functions/docs/tutorials/slack

Slack describes how to create a slash command here: https://api.slack.com/slash-commands

One important thing to note about slash commands is the requirements on the request url

> Request URL - the URL we'll send the data payload to, when the command is invoked by a user. You'll want to use a URL that you can setup to receive these payloads as we'll describe later in this doc. If public distribution is active for your app, this needs to be an HTTPS URL (and self-signed certificates are not allowed). If you're just building an internal integration solely for your own workspace, it can be plain HTTP.

It is possible to use HTTP, but should never be recommended.

Ultimately, the goal is to have a template with a short walkthrough in the README that handles standard boilerplate for the user, most importantly:
* Confirming receipt of the payload https://api.slack.com/slash-commands#responding_basic_receipt
* Verifying the request signature: https://api.slack.com/docs/verifying-requests-from-slack

**Comment by alexellis** [comment]
SGTM

**Comment by alexellis** [comment]
@LucasRoesler I've added this to Trello, please move the card to "In progress" when you start work on it.

**Comment by alexellis** [comment]
Hi Lucas,

Who is going to work on this? It's been open since March without any progress, so should I close it?

Alex

**Comment by LucasRoesler** [comment]
I am not going to be able to work on this any time soon
