### ISSUE TITLE
AlartManager always pending but not fire

### ISSUE THREAD

**Issue by johnhill-xu** [openfaas/faas#1120]
Hello. im just deploy a new OpenFaaS with yaml to my kubernetes cluster, and I created a function using go template from Templates named go-fn.  I deploy it with followed command:
![image](https://user-images.githubusercontent.com/39589657/54064232-6b341080-424d-11e9-8d5b-22261131477d.png)

Then I tested it with the command followed to test auto-scaling:
![image](https://user-images.githubusercontent.com/39589657/54064248-89017580-424d-11e9-9c8a-4369ac9dc84a.png)

From Promethus, I can observed Alerts, but its states stayed pending but not fired:
![image](https://user-images.githubusercontent.com/39589657/54064222-5ce5f480-424d-11e9-9dc4-fda042b03697.png)

From Grafana.
![image](https://user-images.githubusercontent.com/39589657/54064305-00370980-424e-11e9-8ca4-77c3a66f9145.png)

Is anything I made a mistake? thank you

## Expected Behaviour

Fire alert from Promethus, and go-fn replicas auto-scaling to more than 1.

## Current Behaviour

alert  statys pending and no auto-scaling.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

Gateway
 uri:     http://127.0.0.1:31112
 version: 0.11.1
 sha:     c394b09ae65177b3c6948b2c22b890068a8e6283
 commit:  Bump to nats-queue-worker 0.7.0

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.7.0 
 sha:           ab9b56c0760eadba05762fa53dbe99d890bc9e19

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
  k8s

* Operating System and version (e.g. Linux, Windows, MacOS):
  CentOS

**Comment by johnhill-xu** [comment]
It seems loop 10000 is too short, when I change it to 100k it works.

**Comment by johnhill-xu** [comment]
But the auto-scaling strategy looks there is sth wrong with it.  The QPS stays more than 100. but the replicas of the go-fn. change from 10 to 1 to 3. 

![image](https://user-images.githubusercontent.com/39589657/54065270-49d92180-4259-11e9-8709-12c13001a9e3.png)

**Comment by alexellis** [comment]
Thanks for your interest. Glad you could work this out on your own too.

--
Join Slack:
https://docs.openfaas.com/community
