### ISSUE TITLE
scale up policy error

### ISSUE THREAD

**Issue by johnhill-xu** [openfaas/faas#1124]
Hello, I made some tests these days and I found scale up policy seems not worked very well. 
For example:It is a template function with golang
![image](https://user-images.githubusercontent.com/39589657/54183722-c9782200-44df-11e9-8704-83078ee4afa1.png)

when function runing, grafana shows that:
![image](https://user-images.githubusercontent.com/39589657/54184039-9c783f00-44e0-11e9-884c-029f3ba2c315.png)

you can find scale down invoked even if qps stays at a high level.
I also checked the logs from container gateway, it shows replicas scale down from 5 to 1
![image](https://user-images.githubusercontent.com/39589657/54184586-f9c0c000-44e1-11e9-9d53-1e03ef81c8ab.png)

from code:
![image](https://user-images.githubusercontent.com/39589657/54184849-92efd680-44e2-11e9-8808-ceb51171bb2b.png)

Im not sure the reason of the issue, I will try to print the status value to find out if it is a bug.

## Expected Behaviour

scale down not invoked 
## Current Behaviour

func replicas  scale down from 5 to 1.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
FaaS-CLI version ( Full output from: faas-cli version ):
CLI:
commit: a141dedf94ffeed84412365fd591bdc8999c5a1b
version: 0.8.3
Gateway
uri: http://127.0.0.1:31112
version: 0.11.1
sha: c394b09
commit: Bump to nats-queue-worker 0.7.0

Provider
name: faas-netes
orchestration: kubernetes
version: 0.7.0
sha: ab9b56c0760eadba05762fa53dbe99d890bc9e19

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Server:
Engine:
Version: 18.06.3-ce
API version: 1.38 (minimum version 1.12)
Go version: go1.10.3
Git commit: d7080c1
Built: Wed Feb 20 02:28:17 2019
OS/Arch: linux/amd64
Experimental: false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
k8s

* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS 7.4

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by johnhill-xu** [comment]
I add the print and log shows:
![image](https://user-images.githubusercontent.com/39589657/54187487-9ede9700-44e8-11e9-9c9c-0ab414c84bc0.png)

Does it caused by the default alert rule "APIHighInvocationRate" ?

**Comment by johnhill-xu** [comment]
I change the default alert rule as followed:
![image](https://user-images.githubusercontent.com/39589657/54262682-c6496880-45a9-11e9-8c58-d67c7b63d699.png)

It will send alert continusly after invoke function once.

Part of the gateway logs, it seems AlertManager continues send resolved and fire notification to gateway:
> 2019/03/13 07:45:08 Alert received.
2019/03/13 07:45:08 {"receiver":"scale-up","status":"firing","alerts":[{"status":"resolved","labels":{"alertname":"APIHighInvocationRate","function_name":"go-fn","monitor":"faas-monitor","service":"gateway","severity":"major","value":"111.00328868199985"},"annotations":{"description":"High invocation total on ","summary":"High invocation total on "},"startsAt":"2019-03-13T07:40:53.324404523Z","endsAt":"2019-03-13T07:43:53.324404523Z","generatorURL":"http://prometheus-66b6685ffd-tzww4:9090/graph?g0.expr=sum+by%28function_name%29+%28gateway_functions_seconds_sum%29+%3E+0\u0026g0.tab=1"},{"status":"firing","labels":{"alertname":"APIHighInvocationRate","function_name":"go-fn","monitor":"faas-monitor","service":"gateway","severity":"major","value":"111.09178184899983"},"annotations":{"description":"High invocation total on ","summary":"High invocation total on "},"startsAt":"2019-03-13T07:41:53.324404523Z","endsAt":"2019-03-13T07:47:23.324404523Z","generatorURL":"http://prometheus-66b6685ffd-tzww4:9090/graph?g0.expr=sum+by%28function_name%29+%28gateway_functions_seconds_sum%29+%3E+0\u0026g0.tab=1"}],"groupLabels":{"alertname":"APIHighInvocationRate","service":"gateway"},"commonLabels":{"alertname":"APIHighInvocationRate","function_name":"go-fn","monitor":"faas-monitor","service":"gateway","severity":"major"},"commonAnnotations":{"description":"High invocation total on ","summary":"High invocation total on "},"externalURL":"http://alertmanager-6b69d64c7c-2jwpq:9093","version":"4","groupKey":"{}:{alertname=\"APIHighInvocationRate\", service=\"gateway\"}"}
2019/03/13 07:45:08 [handleAlerts] Alert is &{firing scale-up [{resolved {APIHighInvocationRate go-fn}} {firing {APIHighInvocationRate go-fn}}]}:
2019/03/13 07:45:08 GetReplicas took: 0.004406s
2019/03/13 07:45:08 status=resolved, step=1
2019/03/13 07:45:08 [Scale] function=go-fn 3 => 1.
2019/03/13 07:45:08 GetReplicas took: 0.002665s
2019/03/13 07:45:08 status=firing, step=1
2019/03/13 07:45:08 [Scale] function=go-fn 1 => 2.
2019/03/13 07:45:08 error scaling HTTP code 500, http://127.0.0.1:8081/system/scale-function/go-fn
2019/03/13 07:45:08 [error scaling HTTP code 500, http://127.0.0.1:8081/system/scale-function/go-fn]
2019/03/13 07:45:08 Forwarded [POST] to /system/alert - [500] - 0.022379 seconds


>

**Comment by alexellis** [comment]
Hi thank you for your interest in the project.

We've done a lot of testing on the auto scaling and continue to review it over time. We don't consider a bash loop appropriate for performance testing so this was outlined in our documentation around 2 years ago so that anyone in the community had a good reference on how to set up an environment and what tools to use. Hope you find this information below useful. 

More here in the docs:

https://docs.openfaas.com/architecture/performance/

Example with proper tool - hey:

https://github.com/openfaas/workshop/blob/master/lab9.md


Alex

**Comment by johnhill-xu** [comment]
Hi, alex. Thank you for your reply.
In fact it is not a performance testing. 

I followed the steps what described in Lab 9:
https://github.com/openfaas/workshop/blob/master/lab9.md

In Monitor for alerts session,

> Now stop the bash script and you will see the replica count return to 1 replica after a few seconds.

But in my occasion, the replica return to 1 replica when curl sending continuesly. you can find at the grafana pic before.

**Comment by alexellis** [comment]
Please treat this as a performance testing exercise and follow my recommendations.

You need to use `hey`, not a curl loop, I'm very very clear about this in the lab.

Alex

**Comment by alexellis** [comment]
https://github.com/openfaas/workshop/blob/master/lab9.md#trigger-scaling-of-a-go-function

**Comment by johnhill-xu** [comment]
Hello Alex, Thanks for your help.
I just tested with hey. Yes, you are right. During the test there is no scale down invoked. 
![image](https://user-images.githubusercontent.com/39589657/54323659-3f41d200-4635-11e9-812b-2a60df63ff27.png)

But have you ever tested with bash loop? do you know the reason why the "resolved" notification sended by the AlertManager during the bash loop testing? 

Thank you.
