### ISSUE TITLE
Username and password for Web UI never stated

### ISSUE THREAD

**Issue by Truemedia** [openfaas/faas#1126]
I followed along with this article on installing docker swarm and faas https://blog.alexellis.io/your-serverless-raspberry-pi-cluster/

Got up to the logging step of the first pi and don’t have any reference to credentials to use.

## Expected Behaviour

Either no password prompted or step detailing where to extract default/generated password.

## Current Behaviour

Locked out

## Possible Solution

Provide

## Steps to Reproduce (for bugs)

Follow tutorial in article

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.09

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Raspian (Linux)
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi,

Thanks for using OpenFaaS. Can you say how you deployed the code and what steps you took exactly?

In general people are never locked out. The issue template says the following:

> Please also follow the troubleshooting guide and paste in any other diagnostic information you have:

Follow the link and and the instructions on finding the password.

Alex

**Comment by rgee0** [comment]
I’ll look into the armhf files behaviour. In the meantime you can now use `deploy_stack.sh` on all the supported hardware architectures.

The blog has been updated accordingly.

**Comment by rgee0** [comment]
I've tried to reproduce and so far failed:
```
pi@pi3:~/go/src/github.com/openfaas/faas $ docker secret ls
ID                          NAME                  DRIVER              CREATED             UPDATED

pi@pi3:~/go/src/github.com/openfaas/faas $ ./deploy_stack.armhf.sh 
Attempting to create credentials for gateway..
pjumluwjl5q48m7w3n32ive75
q5j1khtufiylbqs1izfmqvrki
[Credentials]
 username: admin 
 password: 6725f82cc9b52404c2575d17cee685121128ec96c4ba6ee2225eb844c95b6593
 echo -n 6725f82cc9b52404c2575d17cee685121128ec96c4ba6ee2225eb844c95b6593 | faas-cli login --username=admin --password-stdin

Enabling basic authentication for gateway..

Deploying OpenFaaS core services for ARM
...

pi@pi3:~/go/src/github.com/openfaas/faas $ cat ./deploy_stack.armhf.sh 
#!/bin/sh

sh ./deploy_stack.sh

pi@pi3:~/go/src/github.com/openfaas/faas $ docker secret ls
ID                          NAME                  DRIVER              CREATED             UPDATED
q5j1khtufiylbqs1izfmqvrki   basic-auth-password                       26 seconds ago      26 seconds ago
pjumluwjl5q48m7w3n32ive75   basic-auth-user                           27 seconds ago      27 seconds ago
```

Happy to continue investigations if further details of how to reproduce can be provided.

**Comment by Truemedia** [comment]
Thanks will try these instructions tonight and let you know how it goes. Extra info: I’m using a Rpi3 B+ as master and zero W as slave.

**Comment by rgee0** [comment]
This may be worth a read: https://github.com/openfaas/faas/issues/501

**Comment by alexellis** [comment]
#501 states Raspberry Pi Zero is no longer supported for OpenFaaS.

**Comment by Truemedia** [comment]
Fair enough thanks for being active with this ticket everyone. I’m gunna keep looking into docker swarm and openfaas as I feel I need to learn more anyway to get up and running with a real use case scenario

**Comment by alexellis** [comment]
I would recommend looking at Kubernetes or following through the Workshop on your laptop. Using a Raspberry Pi is fun, but there's much more to it.

https://github.com/openfaas/workshop

Join Slack to connect with the community
https://docs.openfaas.com

Alex
