### ISSUE TITLE
Watchdog: content-length environment variable not consistent naming

### ISSUE THREAD

**Issue by ewilde** [openfaas/faas#1127]
## Expected Behaviour
Content-Length header value should be exported as an environment variable `Http_Content_Length`

## Current Behaviour
Content-Length header value should be exported as an environment variable `Http_ContentLength`. This is not consistent with other http headers, where the convention is to use the header name with `-` replaced with `_`. See:

```
Http_Accept=application/json, text/plain, */*
Http_Cookie=arp_scroll_position=287
Http_Referer=http://localhost:8080/ui/
Http_Accept_Language=en-GB,en;q=0.9
Http_Content_Type=text/plain
Http_Origin=http://localhost:8080
Http_X_Forwarded_Host=localhost:8080
Http_Connection=keep-alive
Http_User_Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
Http_Accept_Encoding=gzip, deflate, br
Http_X_Call_Id=21a000bd-8c96-4925-bb4d-038469ab253c
Http_X_Forwarded_For=10.255.0.2:56402
Http_X_Start_Time=1552672677370023500
Http_Method=POST
Http_ContentLength=-1
Http_Path=/
Http_Host=env:8080
```

## Possible Solution
To enable backwards compatibility keep the existing `Http_ContentLength` environment variable.

Add new `Http_Content_Length` environment variable

## Todo

Decide how to depreciate `Http_ContentLength` ?

**Comment by alexellis** [comment]
SGTM.

Do you have bandwidth for this and if not could you find someone? 

* https://github.com/openfaas/faas/tree/master/watchdog
* https://github.com/openfaas-incubator/of-watchdog

Alex

**Comment by ewilde** [comment]
@alexellis it's on my list

**Comment by matipan** [comment]
@alexellis @ewilde of-watchdog already has `Http_Content_Length`: https://github.com/matipan/of-watchdog/blob/master/main.go#L270-L273 
So we don't need to change anything there. I validated deploying a new function that prints the contents of `Http_Content_Length` and it does have the correct value.
