### ISSUE TITLE
auto-scale doesn't work

### ISSUE THREAD

**Issue by EDGsheryl** [openfaas/faas#1131]
## Expected Behaviour

I open the switch of scale from zero, and install and deploy faas-idler.

When I use 
```
    curl -X POST http://domain.com:port/async-function/nodeinfo -d ''
```
my k8s will start a pod, so that the function will work.

## Current Behaviour

When I use 
```
    curl -X POST http://domain.com:port/async-function/nodeinfo -d ''
```
The pod doesn't scale, and the queue worker get a i/o timeout.

but when I use
```
    curl -X POST http://domain.com:port/function/nodeinfo -d ''
```
The pod scale to 1. 

## Possible Solution

I think this is a bug....(sorry...)

I can use any function before check their available replica. But 

## Steps to Reproduce (for bugs)

1. open scale from zero.deploy openfaas-idler 
2. deploy sample function nodeinfo ( output CPU hostname information )
3. 
```
    curl -X POST http://domain.com:port/async-function/nodeinfo -d ''
```

## Context

async-invoke:
when pod was ` pod>1 `, the auto-scale works. but when `pod=0` auto-scale doesn't work.
sync-invoker is OK

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by zeerorg** [comment]
I'll look into this issue

**Comment by alexellis** [comment]
Scale from zero is not supported for asynchronous invocations of functions at present and issues exist to track that already.

This feature was logged 8 months ago but nobody has committed to working on it. See below:

https://github.com/openfaas/nats-queue-worker/issues/32

If you expect to invoke functions asynchronously then I would suggest that you do not mark them as valid for scaling to zero.

Feel free to +1 the issue linked. 

Alex
