### ISSUE TITLE
Non-helm deployment unable to load /etc/openfaas/basic-auth-user

### ISSUE THREAD

**Issue by altoning** [openfaas/faas#1132]
## Expected Behaviour

Attempting to enable basic_auth on API gateway using kubectl

## Current Behaviour

Gateway pod is in state of CrashLoopBackOff

## Possible Solution

Dunno

## Steps to Reproduce (for bugs)

1.Set namespaces ...
```
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
```

2. Create secrets ...
```
kubectl -n openfaas create secret generic basic-auth \
--from-literal=basic-auth-user=myusername \
--from-literal=basic-auth-password=mypassword
```

3. Set basic_auth to true
```
git diff yaml/gateway-dep.yml
diff --git a/yaml/gateway-dep.yml b/yaml/gateway-dep.yml
index d0dac48..cbcddf4 100644
--- a/yaml/gateway-dep.yml
+++ b/yaml/gateway-dep.yml
@@ -44,7 +44,7 @@ spec:
         - name: upstream_timeout  # Must be smaller than read/write_timeout
           value: "60s"
         - name: basic_auth
-          value: "false"
+          value: "true"
         - name: secret_mount_path
           value: "/etc/openfaas"
         - name: scale_from_zero
```

4. Apply yaml ...
```
kubectl apply -f ./yaml
```

5. Check pods ...
```
kubectl get pods -n openfaas
NAME                            READY   STATUS             RESTARTS   AGE
alertmanager-5df696f54d-zcjvf   1/1     Running            0          104s
gateway-5f6b6b5f6c-l42h2        1/2     CrashLoopBackOff   4          102s
nats-765f98bd59-gtxsl           1/1     Running            0          103s
prometheus-776597d547-xwrt6     1/1     Running            0          103s
queue-worker-554f887d87-pcp5d   1/1     Running            1          102s
```

6. Check logs ...
```
kubectl logs gateway-5f6b6b5f6c-l42h2 -c gateway -n openfaas
2019/03/20 03:09:58 HTTP Read Timeout: 1m5s
2019/03/20 03:09:58 HTTP Write Timeout: 1m5s
2019/03/20 03:09:58 Binding to external function provider: http://127.0.0.1:8081/
2019/03/20 03:09:58 unable to load /etc/openfaas/basic-auth-user
panic: unable to load /etc/openfaas/basic-auth-user

goroutine 1 [running]:
log.Panicf(0xc420022780, 0x2c, 0x0, 0x0, 0x0)
        /usr/local/go/src/log/log.go:333 +0xda
main.main()
        /go/src/github.com/openfaas/faas/gateway/server.go:47 +0x25cf
```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 commit:  bcff3a6bc8d066ba26233a0b5b0e2338476988e1
 version: 0.8.5

* Docker version `docker version` (e.g. Docker 17.0.05 ):
n/a
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes cluster v1.13.2 on DigitalOcean

* Operating System and version (e.g. Linux, Windows, MacOS):
Kubernetes nodes:
Debian GNU/Linux 9 (stretch)   4.19.0-0.bpo.1-amd64

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by rgee0** [comment]
Derek set title: Can I change the secrets location on Kubernetes?

**Comment by rgee0** [comment]
Derek set title: Non-helm deployment unable to load /etc/openfaas/basic-auth-user

**Comment by rgee0** [comment]
Can you try the steps detailed here:

https://github.com/openfaas/faas-netes/tree/master/yaml#10-enable-basic-auth-on-gateway

**Comment by altoning** [comment]
It works! Many thanks

-Alton

**Comment by altoning** [comment]
it was in the [README.md](https://github.com/openfaas/faas-netes/tree/master/yaml#10-enable-basic-auth-on-gateway) all this time.

maybe this link should be added to the docs at https://docs.openfaas.com/reference/authentication/ ... for non-helm users like me

many thanks for all your help

**Comment by martindekov** [comment]
Derek close

**Comment by martindekov** [comment]
Happy to help @altoning 👍

**Comment by rgee0** [comment]
> it was in the [README.md](https://github.com/openfaas/faas-netes/tree/master/yaml#10-enable-basic-auth-on-gateway) all this time.
> 
> maybe this link should be added to the docs at https://docs.openfaas.com/reference/authentication/ ... for non-helm users like me
> 
> many thanks for all your help

@altoning propose it on the docs repo, please.

**Comment by alexellis** [comment]
@altoning what's the reason that you couldn't use helm? If you are concerned about tiller, you can use helm to template YAML files with the things you want turned on and then apply that:

https://docs.openfaas.com/deployment/kubernetes/#tiller-less-helm-install

This is the supported way of enabling basic auth rather than hacking on the YAML files. What do you think?

Alex

**Comment by altoning** [comment]
i'm 2 months new to kubernetes and have been avoiding helm charts because
some people have been warning me about security issues with tiller.

last friday i finally caved in and started using helm for cert-manager. i'm
kinda liking it now.

i'll look into tiller-less helm. sounds interesting
