### ISSUE TITLE
How can I add gcc when building a Python function?

### ISSUE THREAD

**Issue by prabkumar** [openfaas/faas#1133]
## Expected Behaviour
I am trying to install [google-cloud pubsub library](https://pypi.org/project/google-cloud-pubsub/#files) by adding the required line in requirements.txt.

My requirements.txt looks like this:
`google-cloud-pubsub`

## Current Behaviour
I am attaching the console log in a file.

## Steps to Reproduce (for bugs)

1. add google-cloud-pubsub to requirements.txt
2. faas-cli up -f function_name.yml

## Context
In the library description, it is asked to use the library in a virtual env. Is it possible to setup a virtual environment in the function container? 

An alternate approach would be to download the wheel, or archive file and set the path to the file in requirements.txt. 

If I keep the wheel file for google-pub-sub in the same heirarchy level as handler.py and add google_cloud_pubsub-0.40.0-py2.py3-none-any.whl to my requirements.txt, I get the following message on the console:

`Requirement 'google_cloud_pubsub-0.40.0-py2.py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./google_cloud_pubsub-0.40.0-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/app/function/google_cloud_pubsub-0.40.0-py2.py3-none-any.whl'

The command '/bin/sh -c pip install --user -r requirements.txt\' returned a non-zero code: 1
2019/03/20 19:04:07 ERROR - Could not execute command: [docker build -t prabkumar/gmail-trigger:latest .]
`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Mac OS

[console.txt](https://github.com/openfaas/faas/files/2990419/console.txt)

**Comment by rgee0** [comment]
These are pointers:
```
Failed building wheel for grpcio

...

unable to execute 'gcc': No such file or directory
```

Can you try:
```
$ faas-cli up -f gmail-trigger.yml  --build-option dev 
```

More here:

https://docs.openfaas.com/cli/build/#10-apply-build-options

Some output from my test:
```
Building wheels for collected packages: grpc-google-iam-v1, googleapis-common-protos, grpcio
  Building wheel for grpc-google-iam-v1 (setup.py): started
  Building wheel for grpc-google-iam-v1 (setup.py): finished with status 'done'
  Stored in directory: /home/app/.cache/pip/wheels/b6/c6/31/c20321a5a3fde456fc375b7c2814135e6e98bc0d74c40239d9
  Building wheel for googleapis-common-protos (setup.py): started
  Building wheel for googleapis-common-protos (setup.py): finished with status 'done'
  Stored in directory: /home/app/.cache/pip/wheels/51/ef/76/6ca53de13cc85eea40c641d75bb01355d97181ed64eb67bc8e
  Building wheel for grpcio (setup.py): started
  Building wheel for grpcio (setup.py): still running...
  Building wheel for grpcio (setup.py): still running...
  Building wheel for grpcio (setup.py): still running...
```

**Comment by rgee0** [comment]
Derek set title: How can I add gcc when building a Python function?

**Comment by prabkumar** [comment]
Yep, this works, thanks!

**Comment by rgee0** [comment]
Great news.  We'll close this off.  Please consider [joining us on slack](https://docs.openfaas.com/community/#slack-workspace)

**Comment by rgee0** [comment]
Derek close: resolved
