### ISSUE TITLE
Defining UI Site Root

### ISSUE THREAD

**Issue by jarvisuser90** [openfaas/faas#1134]
I would like to use ingress-nginx to serve the OpenFaaS UI from `http://localhost/faas`. Is there a way for me to set the "site root" so that all the resources and link paths start from `http://localhost/faas/etc...`? Currently I am able to route to the OpenFaaS UI but the page doesn't load correctly since all the resource paths are incorrect.

**Comment by alexellis** [comment]
Changing the URL is not supported for the API or UI. It's also not on the roadmap.

Pretty URLs for functions can be done with OpenFaaS Cloud or through Nginx-rewrite rules. For your use-case why don't you set up two sets of routes - one for your pretty URL and one for the UI?

Alex
