### ISSUE TITLE
Amend issue template to advise how to search previous issues

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#1137]
## Expected Behaviour
The project now has sufficient previous back-issues that it would be worthwhile people searching these before opening a new issue.

## Current Behaviour
Some GH users may be searching first, others may not. 

## Possible Solution
Add a section to the template to describe how a user could search across the org in both open and closed issues.  Also add an item to the checklist for users to confirm they've searched prior to raising a new issue.

## Context
Trying to mitigate potential for repetition of explanations

**Comment by alexellis** [comment]
There's a couple of points like this ->

1) I've read the troubleshooting guide
2) I've searched for previous issues

👍 good idea Richard.

**Comment by alexellis** [comment]
@rgee0 are you going to work on this?

**Comment by alexellis** [comment]
[test](/issues)
