### ISSUE TITLE
Open FaaS for Actions on Google Client Library Node.js or Alexa Alexa Skills Kit SDK for Node.js 

### ISSUE THREAD

**Issue by jordisalvado** [openfaas/faas#1142]
Open FaaS for Actions on Google Client Library Node.js or Alexa Skills Kit SDK for Node.js

I am trying to use Google Action libraries (Node.js) - https://github.com/actions-on-google/actions-on-google-nodejs and Alexa Skills kit SDK for (Node.js) -https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs-  to develop my actions to Google Assistant and Skills for Alexa in Open FaaS. But Google's documentation only shows how to do it for Google Functions, AWS lambda or Node.js Express.

My code inn OpenFaaS is:

handler.js
-------------------
"use strict"

const bodyParser = require('body-parser');
const {
    dialogflow,
    Image,
    Table,
    Carousel,
    List,
    DeepLink,
    BasicCard,
    Button,
    LinkOutSuggestion,
    Suggestions,
    actionssdk
   } = require('actions-on-google');
  
const assistant = dialogflow({debug: true});

module.exports = (assistant, callback) => {
  
console.error("assistant-------------",assistant)  

assistant.intent('Default Welcome Intent', (conv, input , option) => {

conv.ask("Hi");

})

    callback(undefined, assistant);
}

Error:
--------------------
TypeError: assistant.intent is not a function
at module.exports (/home/app/function/handler.js:32:11)
at getStdin.then.val (/home/app/index.js:12:5)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
 --------------------------

Has someone tried the libraries with OpenFaas?

Thank you.

**Comment by alexellis** [comment]
Hi thanks for your interest. You can access professional support from myself (email me) or community support on Slack.  

GitHub is for issues with the project or for tracking features. 

Regards,

Alex
