### ISSUE TITLE
Documentation issue: password file is wrong

### ISSUE THREAD

**Issue by ravikalla** [openfaas/faas#1143]
Password file name mentioned in the Swarm documentation is wrong

## Expected Behaviour
Password file name should be correct
Password file name to be used is "~/.openfaas/config.yml" and not "~/.openfaas/config.yaml"

## Current Behavior
Config file name should be "~/.openfaas/config.yml"
Change the file name to "~/.openfaas/config.yml" instead of "~/.openfaas/config.yaml" in the document 
https://docs.openfaas.com/deployment/docker-swarm/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi Ravi thanks for your interest. The password file location is correct in the documentation as:

~/.openfaas/config.yaml

Can you explain why you think this is different?

Alex

**Comment by rgee0** [comment]
Ref: https://github.com/openfaas/docs/pull/142
