### ISSUE TITLE
FaaS is not accessible on Mac

### ISSUE THREAD

**Issue by ravikalla** [openfaas/faas#1144]
## Expected Behaviour

I am following this document - https://docs.openfaas.com/deployment/docker-swarm/
When I try to deploy a function on my mac, its not able to detect FaaS in my local.
`$ faas-cli store deploy figlet`

Below is the error:
```
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Is FaaS deployed? Do you need to specify the --gateway flag?
Post http://127.0.0.1:8080/system/functions: EOF

Function 'figlet' failed to deploy with status code: 500
```
I am able to access the application from the browser at "http://127.0.0.1:8080". I provided the credentials from "~/.openfaas/config.yml"

## Steps to Reproduce (for bugs)

1. Followed the document "https://docs.openfaas.com/deployment/docker-swarm/"
2. Got error while running the command `faas-cli store deploy figlet`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  96f159fc3e85a6782461c9dde77cbf88308aa21d
 version: 0.8.6

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.11.1
 sha:     c394b09ae65177b3c6948b2c22b890068a8e6283
 commit:  Bump to nats-queue-worker 0.7.0


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.6.1 
 sha:           3cac0ccc2e8bb7f567739a33f7d414cdb58440aa
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
OpenFaaS most certainly works on Docker for Mac. 

I'm going to close this issue but please feel free to keep commenting. in the issue template there is a link to the troubleshooting guide and you should go through that before raising an issue. 

Alex

**Comment by alexellis** [comment]
Derek close
