### ISSUE TITLE
Proposal: remove WriteTimeout from Go HTTP Server in gateway

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1147]
Proposal: remove WriteTimeout from Go HTTP Server in gateway

## Expected Behaviour

In order to enable logs and prevent the use of low-level connection Hijacking @LucasRoesler suggested that the WriteTimeout value from the gateway be removed permanently.

Removing the value would mean that there is no limit and a connection could potentially remain open indefinitely.

https://github.com/openfaas/faas/blob/master/gateway/server.go#L221

From the [Golang docs](https://golang.org/pkg/net/http/#Server):

```
        // WriteTimeout is the maximum duration before timing out
        // writes of the response. It is reset whenever a new
        // request's header is read. Like ReadTimeout, it does not
        // let Handlers make decisions on a per-request basis.
        WriteTimeout time.Duration
```

A warning from Cloudflare on the importance of setting server timeout values:

https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/

```
About streaming
Very annoyingly, there is no way of accessing the underlying net.Conn from ServeHTTP so a server that intends to stream a response is forced to unset the WriteTimeout (which is also possibly why they are 0 by default). This is because without net.Conn access, there is no way of calling SetWriteDeadline before each Write to implement a proper idle (not absolute) timeout.
Also, there's no way to cancel a blocked ResponseWriter.Write since ResponseWriter.Close (which you can access via an interface upgrade) is not documented to unblock a concurrent Write. So there's no way to build a timeout manually with a Timer, either.
Sadly, this means that streaming servers can't really defend themselves from a slow-reading client.
```

This change would be to enable the logs API in PR #1130 

## Current Behaviour

There is an explicit timeout set which can be cleared, only if the connection is Hijacked on the server. The downsides to this is that we then have to write very low-level networking code instead of leveraging the higher-level HTTP package.

My concerns about low-level hacks and primitives is the maintenance cost and potential unforeseen bugs.

## Possible Solution

Consider removing the global timeout and refer to current best practice / convention.

**Comment by alexellis** [comment]
Request for comment: @stefanprodan @LucasRoesler

**Comment by alexellis** [comment]
The two log streaming implementations:

With WriteTimeout removed:

https://github.com/openfaas/faas-provider/pull/15/files#diff-46a528fd5d295f6ca4aaf93db323005eR30

With WriteTimeout in place:

https://github.com/openfaas/faas/pull/1130/files#diff-7e6ccba176e6621b094f4213aae98d52R19

**Comment by stefanprodan** [comment]
I'm for disabling the write timeout, if an OF user needs it, it can be set at the LB/ingress level.

**Comment by alexellis** [comment]
I prefer the code which depends on an empty WriteTimeout but I have concerns about removing it given Cloudflare's warning.

**Comment by alexellis** [comment]
Stefan: another alternative is to use a third TCP port and HTTP server for the gateway and serve logs from there.

**Comment by alexellis** [comment]
I think go with this:

> With WriteTimeout removed: https://github.com/openfaas/faas-provider/pull/15/files#diff-46a528fd5d295f6ca4aaf93db323005eR30

**Comment by alexellis** [comment]
Derek set milestone: 0.13.0

**Comment by matipan** [comment]
I agree with @stefanprodan. @alexellis would using a third tcp port and server bring benefits other than leaving the write timeout as is?

**Comment by LucasRoesler** [comment]
Using another port, is possible, but makes it more awkward for clients that use that API. It is nicer to have the entire public API on a single port. It also introduces cors issues

**Comment by alexellis** [comment]
I agree with Lucas

**Comment by LucasRoesler** [comment]
I have checked several of the projects with servers in the CNCF and have not yet found one that sets the `WriteTimeout`
