### ISSUE TITLE
Proposal: Add "arch" to /system/info endpoint

### ISSUE THREAD

**Issue by zeerorg** [openfaas/faas#1148]
## Summary

The current `/system/info` endpoint doesn't give any information about the architecture it is running on. Since openfaas can run on different architectures (arm64, armhf, amd64) the information about the underlying hardware can be useful.

## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
An "arch" key with value either of "armhf/arm64/x86_64" is returned. Example:
```json
{
  "provider": {
    "provider": "faas-swarm",
    "orchestration": "swarm",
    "version": {
      "commit_message": "Sample Message",
      "sha": "7108418d9dd6b329ddff40e7393b3166f8160a88",
      "release": "0.2.6"
    }
  },
  "version": {
    "commit_message": "Sample Message",
    "sha": "7108418d9dd6b329ddff40e7393b3166f8160a88",
    "release": "0.8.9"
  },
  "arch": "x86_64"
}
```

## Current Behaviour
No information about architecture is returned.

## Possible Solution
1. Inject architecture with the gateway binary at compile time and return the value when `/system/info` endpoint is queried.

## Context
This will help with issue #1145 since there is no way for the dashboard to query for architecture.

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Re: #1145 I am OK with not querying the server to detect architecture type. We already have a mechanism to solve that problem.

If you want to work on this issue I am fine with it, but I think you need to take the same approach as #1145 - build the architecture type into the gateway binary at build-time using an LDARGS flag, just like we do with the git commit and version.

Alex

**Comment by alexellis** [comment]
Please go ahead and work on this when you have time @zeerorg

**Comment by alexellis** [comment]
@zeerorg where are we on this? If you're stalled, please send this issue into the contributors channel, perhaps someone else could take it?

**Comment by alexellis** [comment]
@zeerorg what's the status of this? Can you have something ready by Friday or should we find another volunteer?

**Comment by ivanayov** [comment]
I can work on this

**Comment by alexellis** [comment]
Thank you :tada:

**Comment by alexellis** [comment]
Do you have any questions?

How long do you think it will take and what would be a good date to circle back and review your PR?

**Comment by ivanayov** [comment]
I will take a look this afternoon and write back if there're any blockers and give estimates. Seems pretty straightforward from first sight.

**Comment by alexellis** [comment]
Thank you @ivanayov
