### ISSUE TITLE
Autoscaling question about scaling to zero

### ISSUE THREAD

**Issue by olyazajj** [openfaas/faas#1159]
## My actions before raising this issue 
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) 
- [x] Read/searched [the docs](https://docs.openfaas.com/) 
- [x] Searched [past issues](/issues) 

I want to try some caching approaches for scaling on the openfaas platform. For example, LRU, LFU and Popularity-Driven Content Caching with restrictions on the number of functions in a warm start. 

https://docs.openfaas.com/architecture/autoscaling/#scaling-down-to-zero here you suggest using your faas-idler algorithm or using the OpenFaaS REST API. Could you give some examples of using the second option or explain how this can be done? 

This would help me a lot in my term paper. 

## Your Environment 
* FaaS-CLI version ( Full output from: `faas-cli version` ): 

CLI:
commit: 5b36c50280d961d3aa248bd17f901f4ef2774447
version: 0.8.1

Gateway
uri: http://127.0.0.1:8080
version: 0.9.5
sha: 3598da2e513a09a6b8ce6e17c6baa3558a4c8d11
commit: Enable basic auth for service query / scaling on provider

Provider
name: faas-swarm
orchestration: swarm
version: 0.4.3 
sha: 85782ed1330ed931d794049f45ae75682b53356a

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.06.1-ce

* I am using Docker Swarm. 

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 16.04.5 LTS

**Comment by alexellis** [comment]
Derek set title: Autoscaling question about scaling to zero

**Comment by alexellis** [comment]
Derek add label: question

**Comment by zeerorg** [comment]
The OpenFaas API has a `/system/scale-function/{functionName}` endpoint that can be called to scale functions as required (even scale them to zero). 
You can check the API docs using instructions [here](https://github.com/openfaas/faas/tree/master/api-docs)

**Comment by alexellis** [comment]
Derek close: all, feel free to keep commenting. This question has been answered

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com
