### ISSUE TITLE
I Need spesifik explanation about Request header `GET` openfaas.

### ISSUE THREAD

**Issue by juandisay** [openfaas/faas#1164]
I've read
https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables,

about python code type like os.env() have a rules in Openfaas, like os.env('Http_Query') or etc?

My goals,
http://gateway:8080/function/some-of-function?query=some-of-value

THanks,

**Comment by alexellis** [comment]
Hi, please consult the workshop.

https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by juandisay** [comment]
> Hi, please consult the workshop.
> 
> https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables
> 
> --
> Join Slack to connect with the community
> https://docs.openfaas.com

after inject config like Http_Query , everything about /some/path  ,
like:
http://gateway:8080/function/env/some-path return Code 200
Can I limit it to env, if I don't have some/path, 
if i dont have /some/path return to code 404 or etc.

**Comment by alexellis** [comment]
Derek lock

**Comment by alexellis** [comment]
For further support please join Slack

**Comment by alexellis** [comment]
Derek add label: support
