### ISSUE TITLE
Question about a python function for running dhcp server as a function

### ISSUE THREAD

**Issue by saboor97** [openfaas/faas#1166]
Hii, i am trying to make dhcp serverless by running dhcp function over openfaas platform.
i'm using dhcp code from this repository, https://github.com/marceleng/py-DHCP-server i've executed this code in linux environment it works fine. But, when i created the openfaas function and imported these files in repository by replacing dhcp-server.py file which is main execution file with handler.py
when i executed the function in cli and UI both environment. I came up with following error :(

Traceback (most recent call last):
  File "index.py", line 6, in <module>
    from function import handler
  File "/home/app/function/handler.py", line 114, in <module>
    server=DHCP_server(config.SERVER_IP,config.SERVER_PORT,config.IP_POOL,DHCP_handler)
  File "/home/app/function/handler.py", line 14, in __init__
    SocketServer.UDPServer.__init__(self, ("",port), RequestHandlerClass)
  File "/usr/local/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied

**Comment by saboor97** [comment]
please help me

**Comment by alexellis** [comment]
Hi, I'm not sure that this is going to be supported.

You would be better off running it as a plain Kubernetes deployment. You'll also probably need elevated permissions on the pod spec.

Alex

**Comment by saboor97** [comment]
Mr. Alex, i'll be grateful to you if you let me know that can i build a function consisting of more than one file?
let's say handler.py is my main file can i import other files which are part of the code in handler.py?
@alexellis

**Comment by saboor97** [comment]
i have got a code of 2 files file1.py, file2.py. file1.py is main file which imports file2.py in it, file1.py code i think i'll be adding it to handler.py file  and in case of file2.py what should i do?
