### ISSUE TITLE
Incorrect request body description for /system/alert in swagger.yml

### ISSUE THREAD

**Issue by J12934** [openfaas/faas#1168]
https://github.com/openfaas/faas/blob/e903f0ef73db1533ccb2b489c450bbb2723d4842/api-docs/swagger.yml#L93-L104

Request Body Description is labeled the same for `POST /status/alert` as for `DELETE /system/functions`

## My actions before raising this issue
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
Request Body Description is labeled with a fitting description.

**Comment by alexellis** [comment]
Thanks for the catch. Please can you send a PR to amend?

Note the contribution guide and how to sign off commits (note this is not GPG signing)
