### ISSUE TITLE
Proposal: update template image to use alpine:3.9 and Go 1.12

### ISSUE THREAD

**Issue by cpanato** [openfaas/faas#1182]
Update https://github.com/openfaas/templates/blob/master/template/go/Dockerfile for example to use GO 1.12 and alpine 3.9

## My actions before raising this issue
- [x] Searched [past issues](/issues)

**Comment by alexellis** [comment]
Happy to use `alpine:3.9`, but please don't update Go right now unless it's upgrading to `1.10`.

Alex
