### ISSUE TITLE
Gvisor Discussion

### ISSUE THREAD

**Issue by pavanagrawal123** [openfaas/faas#1194]
I was having a discussion with @burtonr on Slack about implementing Gvisor with OpenFaas. Could be interesting as it would allow for privileged containers while still being semi-secure. Does anyone have specific thoughts on this idea?

**Comment by alexellis** [comment]
To my knowledge, you can add gVisor to your Kubernetes deployment transparently. Go ahead and let us know how you get on.

In terms of the other thing you said:

> it would allow for privileged containers while still being semi-secure. Does anyone have specific thoughts on this idea?

Can you tell me more about how you think that would work and what problem it would solve for you?

**Comment by alexellis** [comment]
Derek close: due to inactivity. @pavanagrawal123 feel free to discuss further on Slack
