### ISSUE TITLE
Template request: Kotlin with Gradle

### ISSUE THREAD

**Issue by i-walker** [openfaas/faas#1195]
My workflow so far is to have a docker file which builds the gradle project and exposes the binaries to the watchdog.

What are the nessary steps, that faas-cli supports kotlin with gradle?

**Comment by affix** [comment]
You can use Faas-cli to generate a new dockerfile template and build your function using Docker, Kotlin and Gradle.

Alternatively you can create a template yourself and submit it to the template store.

You can also extend this third party template https://github.com/napperley/openfaas-kotlin-templates/ from @napperly

**Comment by alexellis** [comment]
Yes, creating a template would be ideal for this.

Is this Kotlin on JVM or "native"?

See also:

https://docs.openfaas.com/cli/templates/#get-started

https://github.com/openfaas/templates/

**Comment by i-walker** [comment]
Kotlin JVM. Ok, I'll look into it. I. get back to you, if I have something working

**Comment by alexellis** [comment]
@i-walker I don't have anything for you right now, but you can use the Java template since it's geared-up for the JVM and then adapt it for Kotlin:

https://github.com/openfaas/templates/tree/master/template/java8

Alex

**Comment by Gopinathp** [comment]
I would love to contribute for this. Is there some work already done which I can help improve/maintain and release?

**Comment by alexellis** [comment]
Please take a look at how the Java template works in the openfaas/templates repo, fork it and translate to Kotlin. That's how I'd approach it.

**Comment by Gopinathp** [comment]
Sure.

**Comment by alexellis** [comment]
Thanks, it would be great to see what you can come up with.

**Comment by dkul108** [comment]
I also will be happy to help with project in any way I can. I have a decade
of Java experience, etc. Regards, Dmitro Kulinich
