### ISSUE TITLE
Enable multiple users for basic-auth plugin

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1215]
The new basic-auth plugin works from a single secret and single shared account. It could have a flag or option to read a htpasswd or a set of key/values for various users.

Pros:
* remove or revoke a single account
* give out additional access and potentially audit it

## Expected Behaviour

We should have a way to define a number of basic auth credentials.

## Current Behaviour

One shared user is possible for the REST API with the current plugin. 

## Possible Solution

Update the plugin: https://github.com/openfaas/faas/tree/master/auth

**Comment by affix** [comment]
Derek assign: me

**Comment by affix** [comment]
Derek Assign me

**Comment by affix** [comment]
Derek assign: affix

**Comment by affix** [comment]
Derek assign me

**Comment by affix** [comment]
Derek Assign me

**Comment by affix** [comment]
Derek assign: me

**Comment by affix** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I'll note it that you're working on this, but FYI assign usually only works for org members.
