### ISSUE TITLE
[Feature request] Add Bcrypt to basic auth plugin for logging in

### ISSUE THREAD

**Issue by affix** [openfaas/faas#1216]
The new basic auth plugin stores secrets as Kubernetes secrets. After implementing #1215 support for BCrypt should be enabled.

Pros:
* BCrypt is secure by design
* Its easy to implement with https://godoc.org/golang.org/x/crypto/bcrypt

Expected Behaviour

We should use bcrypt to encypt user passwords

Current Behaviour

The admin password depends on cluster configuration for encryption. 

Update the plugin: https://github.com/openfaas/faas/tree/master/auth
Update the faas provider : https://github.com/openfaas/faas-provider/tree/master/auth

**Comment by affix** [comment]
Derek add label: proposal

**Comment by affix** [comment]
Derek add label: blocked

**Comment by alexellis** [comment]
I thought it would be wise to link to how Kubernetes enables encryption at rest for Secrets, this isn't a default and needs to be enabled by the administrator. 

https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Comment by alexellis** [comment]
/set title: [Feature request] Add Bcrypt to basic auth plugin for logging in
