### ISSUE TITLE
Feature request: SDK for OpenFaaS Gateway

### ISSUE THREAD

**Issue by amlee** [openfaas/faas#1218]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

OpenFaaS has support of CLI to invoke functions and interact with OpenFaaS gateway. But there is use case that the functions need to be invoke from a Java service application. It would be great to have an officially supported OpenFaaS Java client and API interface that can be 

## Expected Behaviour

This is a feature request. The OpenFaaS Java client would support the same functionalities of the OpenFaaS CLI. 

## Current Behaviour

Currently only CLI is supported in OpenFaaS. 

## Possible Solution

There is a third-party Java client implementation that appears to be [generated from OpenFaaS http gateway via swagger.io](https://github.com/cloudatio/openfaas-client-java), but a better defined Java interface that is supported officially by OpenFaaS would be nice.

## Context

We have Java application that needs to invoke OpenFaaS functions, query Function Store, etc.. similar to what openfaas-cli does that would benefit from an official OpenFaaS Java client.

**Comment by alexellis** [comment]
Related to: https://github.com/openfaas/faas/issues/1246
