### ISSUE TITLE
Question: How to enable "Scaling up from zero replicas" on Kubernetes

### ISSUE THREAD

**Issue by hotjunfeng** [openfaas/faas#1222]
## Context

I have implemented OpenFaaS on Kubernetes and tried to enable "Scaling up from zero replicas" feature. According to the [document](https://docs.openfaas.com/architecture/autoscaling/) , I should set zero_scale to true for the gateway deployment using the docker-compose.yml. But the docker-compose.yml file is used for Docker Swarm and not works for Kubernetes. So how can I enable "Scaling up from zero replicas" of OpenFaaS on Kubernetes? Thank you.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.8.14

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes v1.13.3 with FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

Thank you for your help, and please let me know if any additional information would be useful.

**Comment by alexellis** [comment]
Hi there,

It's enabled by default. 

Given that you've not filled out the issue, I'm going to take the issue as a question rather than a bug report or unexpected issue.

Alex

**Comment by alexellis** [comment]
For technical support, please join Slack. 

--
Join Slack to connect with the community
https://docs.openfaas.com
