### ISSUE TITLE
Proposal - Add existing Kubernetes support for secrets on private repositories

### ISSUE THREAD

**Issue by madmagi** [openfaas/faas#1224]
## the Problem
The documentation listed at 
(https://github.com/openfaas/faas-netes/blob/master/SECRETS.md)
as a way to pull images from a private repository is overly complex for basic usage.  There is a time where a custom image may make sense, but Kubernetes has the capability to use custom repositories already, it just needs to be exposed to OpenFaas.  (https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

## Expected Behaviour
The proposal is to add a key in the Config.yml for a specific registry, use a specific imagepullsecret.  When an image that meets that specification, during the creation of the spec record; output the imagepullsecret.

## Current Behaviour
Current Behaviour does not support the ImagePullSecret tag in the spec section of a Pod declaration.

## Possible Solution
In the Config.yml, add a ImagePullSecret: section.  The section would be a collection of secrets and the hosting uri that they apply to.

imagepullsecret:
  secret1:
     name: mydomain.com:5000
     secret: regcredit
  secret2:
    name: otherdomain.com:3030
    secret: regcredit2

and so forth

Then simply output in the spec section as defined in (https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) if the image is from a matched registry.

## Context
We use only private-self hosted registries for our containers, I presume many businesses do the same.

Kubernetes on Iron, Kubernetes on EKS
Linux OS

**Comment by alexellis** [comment]
Hi,

Thank you for your interest in the project.

I'm confused about this statement. Perhaps you could write more objectively about what exactly it is you find complex about Kubernetes secret management?

> as a way to pull images from a private repository is overly complex for basic usage

The community team have documented how to use private registries (there are two ways supported)

1) Create a registry secret per registry and attach it to the function
2) Create a registry secret and bind it to a ServiceAccount (one-off)

As a rule I've only ever needed option 2.

Please can you give me more some details and explain what didn't work about option 2?

[Option 2 - link an image pull secret to the namespace's serviceaccount](https://docs.openfaas.com/deployment/kubernetes/#option-2-link-an-image-pull-secret-to-the-namespaces-serviceaccount)

**Comment by madmagi** [comment]
Alex,

I see how option 2 can work, however, if I have a team of developers wouldn't it be better to set this as an option once and forget about it rather than having to remember to include it every time I created a new function?   I am a fan of the KISS principle, and anytime I have developers needing to constantly remember, go do x, y, and z so it works the chances of problems goes way up.

But your point is valid as a way to do it.

**Comment by alexellis** [comment]
> I see how option 2 can work, however, if I have a team of developers wouldn't it be better to set this as an option once and forget about it rather than having to remember to include it every time I created a new function? 

I feel like I must be mis-communicating somehow.

Option 2 is exactly what you've asked for.

It sets up a pull secret in the cluster and means developers need to do nothing. Can you at least try it before dismissing it?

Alex

**Comment by alexellis** [comment]
Pinging @stefanprodan  @LucasRoesler

**Comment by madmagi** [comment]
I am testing as we type :) .  Thanks for your quick response.

**Comment by madmagi** [comment]
yup as you expected, I was the obtuse one.  Works like a charm.

**Comment by madmagi** [comment]
Just a side note, IF running docker for windows, it installs an old kubectl which causes an issue with this process.  Once I upgraded kubectl it worked.

Thanks.

**Comment by alexellis** [comment]
Thank you for the feedback. There is a note on this in the openfaas/workshop project, which I would encourage you to try out.

If you need technical support again, please join Slack.

Have a great weekend.

--
Join Slack to connect with the community
https://docs.openfaas.com
