### ISSUE TITLE
Cant't deploy function from private repository via API

### ISSUE THREAD

**Issue by strahe** [openfaas/faas#1225]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

When I deploy a function via the API(`/system/functions`), I am using a private registry, but I have provided the `registryAuth` field. I am sure registryAuth is right. But the function is always not ready, when I searched for logs from K8s, I found:

Failed to pull image "{my.com}/5cea6ca2371530dac565780b/python3-t1:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for {my.com}/5cea6ca2371530dac565780b/python3-t1, repository does not exist or may require 'docker login'

It looks like a permission issue,  Is there something I missed??

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
Gateway
 uri:     
 version: 0.13.7
 sha:     e3b77514d085987d320fef883f7a950bca97f166
 commit:  Add error handling to basic auth injector


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.7.8 
 sha:           ded145c5f6edad96785465d5910a0f40b9f6e1e7
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi @strahe, thanks for your interest in the project.

I'm unaware of any issues with our code for using private registries so I'm going to close this issue.

> [x] Read/searched the docs

Here are the instructions for deploying from a private repository on Kubernetes - https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes

Feel free to continue commenting, after you have shown that you have A) followed the docs and B) given detailed instructions for reproducing the issue you are encountering.

Good luck 👍 

Alex

--
Join Slack to connect with the community
https://docs.openfaas.com
