### ISSUE TITLE
FaaS -> OpenFaaS

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#123]
The name of the FaaS project will transition to OpenFaaS. This issue is going to track the progress and list areas needing to change.

Areas to cover:

* [x] Repo names may stay the same and move to an organization.
* [x] New website www.openfaas.com - live with HTTPS, but without content.
* [x] additional pages to be added for features etc.
* [x] Utility download script cli.openfaas.com
* [x] Twitter handle -> @open_faas
* [x] GitHub repo -> https://github.com/openfaas
* [x] Import paths for GitHub
* [x] Add logo to README / GitHub pages site.
* [x] Change FaaS Gateway to "OpenFaaS Gateway" in UI

Anything else?

**Comment by alexellis** [comment]
I've been able to register the open-faas organization on GitHub, but openfaas is taken by an account which appears to be "account sitting". They do have private activity and a message has been passed on to see if we can have the name.

**Comment by glyif** [comment]
@alexellis do you need help with the frontend of the site?

**Comment by alexellis** [comment]
There might be some opportunities to help with that, or more likely the Angular Material UI built into the API Gateway. I'd like to set the response body to use a mono-spaced font.

**Comment by rgee0** [comment]
@glyif there is part of the gateway ui impacted by the rebrand. Theres reference to FaaS In the top left corner that should become OpenFaaS

**Comment by alexellis** [comment]
Derek add label: priority/high

**Comment by alexellis** [comment]
All repos moved to https://github.com/openfaas

**Comment by johnmccabe** [comment]
@alexellis can you change the description to a checklist, nicer way of letting people see what is/isn't done

**Comment by alexellis** [comment]
Welcome to the OpenFaaS community 👍 💯
