### ISSUE TITLE
Automatic builds for auth-module and for arm

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1231]
## Task

Automatic builds for auth-module on x86_64 (via Travis) and on-demand on-device for arm via `publish.sh`

The basic-auth module is not built or pushed upon 'tag' / 'release' of the faas repo, but it should be:

https://github.com/openfaas/faas/tree/master/auth

We also don't create on-device images for this, but should do for both armhf and arm64.

https://github.com/openfaas/faas/blob/master/contrib/publish-arm.sh

**Comment by rgee0** [comment]
Derek assign: me

**Comment by alexellis** [comment]
For the x86_64 piece in https://github.com/openfaas/faas/blob/master/build.sh

I would expect something like:

```
(cd auth-etc && ./build.sh)
```

Then an extra `docker push` in the travis file.

**Comment by alexellis** [comment]
The arm parts work through specific Makefile instructions that call the same sort of build scripts: 

https://github.com/openfaas/faas/blob/master/Makefile#L16

So perhaps this:

```
.PHONY: ci-armhf-build
ci-armhf-build:
	(cd gateway; ./build.sh $(TAG))
```

would look more like:

```
.PHONY: ci-armhf-build
ci-armhf-build:
	(cd gateway; ./build.sh $(TAG) ; cd ../auth-etc/ ; ./build.sh $(TAG))
```
