### ISSUE TITLE
Add mount nfs server support to function container

### ISSUE THREAD

**Issue by feiniao0308** [openfaas/faas#1232]
We have a lot of utilities and libraries stored in an internal NFS server which is maintained by other teams. To write a function, we need to call some libraries from the NFS server. But looks like current function container does not support to mount external NFS server to the container.

I'd like to request this feature support since I'm only blocked by this feature to use OpenFaaS in my project. Thanks a lot.

**Comment by feiniao0308** [comment]
@alexellis could you please help it? Any way i can workaround it?

**Comment by alexellis** [comment]
Please can you fill out the whole issue template? We'll need all the information to make a decision.

**Comment by alexellis** [comment]
```
<!-- Due dilligence -->

## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

<!--- Provide a general summary of the issue in the Title above -->


## Expected Behaviour
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->


## Current Behaviour
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->


## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->


## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->


## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

```

**Comment by feiniao0308** [comment]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)


We have a lot of utilities and libraries stored in an internal NFS server which is maintained by other teams. To write a function, we need to call some libraries from the NFS server. But looks like current function container does not support to mount external NFS server to the container.

## Expected Behaviour
Able to support external NFS server to function container. The function can call some libraries/binaries from the NFS server since the function relies on the libraries/binaries.


## Current Behaviour
Unable to mount external NFS server. The libraries in the NFS server is maintained by different team which does not use OpenFaaS framework, so the function cannot call it directly unless mounting the NFS server to the container


## Possible Solution
No workaround solution. I'm fully blocked by it to use OpenFaaS in my project.


## Context
Without the feature, I'm unable to write some functions which depends on other libraries which is stored in NFS server and maintained by other teams.

**Comment by feiniao0308** [comment]
Thanks @alexellis for the quick response. Just update the issue template. Thanks a lot.

**Comment by alexellis** [comment]
You must fill in everything. Looks like you missed the last section.

**Comment by feiniao0308** [comment]
Updated @alexellis :-)

**Comment by alexellis** [comment]
> Code example or link to GitHub repo or gist to reproduce problem:

Can you give a sample and the error you received?

**Comment by stefanprodan** [comment]
You could put those libraries in a container image and use that as the base image for your functions. This approach would allow you to version the libraries and migrate you functions independently between versions.

**Comment by alexellis** [comment]
I'd like to see the error. Does this involve mounting a filesystem for instance?

**Comment by feiniao0308** [comment]
@stefanprodan Since the libraries are stored in external NFS server, and they linked to different libraries in the same NFS server. I cannot just extract part of libraries from the NFS server and move them into base image. Also the utitlie libraries are maintained by other teams, the libraries are updated frequently. To keep to use the latest stable libraries, we need to mount the NFS server as a volume in the container. Then access the libraries in the function.

**Comment by feiniao0308** [comment]
@alexellis there's no way to mount external NFS server as a volume to function container, so no any error. I'm blocked by how I can access the libraries stored in the NFS server. To implement the function, I need call the libraries to access internal resources.

**Comment by alexellis** [comment]
At this time we have no plans to add volume mounts for function containers.

Please see the following related issue: https://github.com/openfaas/faas/issues/320

That said, I think we could still help you.

The storage story for functions is normally to utilise SQL, no-sql or s3 (for instance AWS, Ceph, or Minio). I would suggest that you set up a Minio server and have it mirror the NFS server.

This way your function can pull in whatever it requires from S3 using the API when it starts up or on demand.

Here's an example blog post and tutorial for you: https://blog.alexellis.io/openfaas-storage-for-your-functions/

You may also find that functions are not appropriate for your use-case, in which case you may want to look into:

- [Kubernetes Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/)

- [JaaS (Jobs for for Swarm)](https://github.com/alexellis/jaas)

I'll close the issue now, but feel free to comment.

Alex

**Comment by feiniao0308** [comment]
Thanks @alexellis . Does jaas suppor to run against kubernetes?
