### ISSUE TITLE
Move to multi-arch images for prometheus and alertmanager

### ISSUE THREAD

**Issue by zeerorg** [openfaas/faas#1235]
Prometheus and alertmanager have published Multi arch images, Move armv7 images from arm tag to multi arch tags.

## Checklist:
- [x] x86_64(https://github.com/openfaas/faas/commit/9690987319a9906d2863c93eee8634f78e6aa0b6)
- [x] armhf (https://github.com/openfaas/faas/commit/9690987319a9906d2863c93eee8634f78e6aa0b6)
- [x] arm64 (https://github.com/openfaas/faas/commit/9690987319a9906d2863c93eee8634f78e6aa0b6)

## Possible Solution
Edit `docker-compose.armhf.yml` and edit the tags.

**Comment by alexellis** [comment]
Hi @zeerorg you'll need to cover .arm64 too and also the regular docker-compose.yml so that we are on the same version on all YAML files.

**Comment by rgee0** [comment]
Is there anything further required here?  Seems all three compose variants were moved to multi arch under (https://github.com/openfaas/faas/commit/9690987319a9906d2863c93eee8634f78e6aa0b6)

I'll close it and reopen if the answer comes back as yes.
