### ISSUE TITLE
Go modules support for templates

### ISSUE THREAD

**Issue by ewilde** [openfaas/faas#1241]
## Summary
Add support for Go modules that preserves backwards compatibility

## Proposal
In order to preserve backwards compatibility

- Go module support would be `off` by default

Support for Go modules would be accessed using a [build arguments](https://docs.openfaas.com/cli/build/#30-pass-custom-build-arguments) i.e. `--build-arg gomodule=on`

## Reference

https://github.com/matipan/openfaas-go111-template/blob/master/template/go-http/Dockerfile

https://github.com/retgits/of-templates

**Comment by alexellis** [comment]
Having met with Lucas, Stefan, yourself and Bruno from your team, we decided to go ahead with this change.

It should cover the docs, go template and the two HTTP-golang templates.

Alex

**Comment by bmcstdio** [comment]
Linking https://github.com/openfaas-incubator/golang-http-template/pull/24.

**Comment by alexellis** [comment]
@bmcstdio do you have an update on your progress?
