### ISSUE TITLE
[Question] how to add a host device to the deployed container?

### ISSUE THREAD

**Issue by leesera** [openfaas/faas#1244]
## Expected Behaviour

There is a '--device' option at "docker run" command for passing a host device to a container
Specific command I want to execute is 
`docker run -it --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket image_name`

I am sorry that I can't find that option when I try to deploy my image with `faas-cli`

thank you

**Comment by alexellis** [comment]
Hi @leesera 

Thank you for your interest in the project. Mounting devices and volumes is not in scope for the OpenFaaS roadmap at present.

I would recommend that you either use a Kubernetes Job, or build a microservice which binds the devices you require, then invoke that via a function. This would effectively become a `DaemonSet` on each node and a function could invoke it that way.

I'm going to close the issue, but feel free to discuss.

Alex
