### ISSUE TITLE
Document goleak usage for contributors

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#1248]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

The contribution guide should document the usage of this third party library in unit tests

## Current Behaviour

There are no docs

## Possible Solution

Add a paragraph to the section on unit testing

## Context

This is a followup to #1130

**Comment by alexellis** [comment]
Thanks Lucas
