### ISSUE TITLE
Broken link in swagger documentation

### ISSUE THREAD

**Issue by gabrielsson** [openfaas/faas#1250]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

The swagger documentation for /async-function/{functionName} 
links to deprecated documentation faas/guide

## Expected Behaviour

It should point to 

https://docs.openfaas.com/reference/async/

## Current Behaviour

It points to https://github.com/openfaas/faas/blob/master/guide/asynchronous.md.
which is deprecated

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Thank you for fixing this!
