### ISSUE TITLE
Append a task id (uuid) for each function request in the container log

### ISSUE THREAD

**Issue by lihaiswu** [openfaas/faas#1262]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

In our project, we send all k8s pod logs to log aggregator (such as vRealize Log Insight ). With the unique task id added into container log, we can query the function log by same session request. Currently, it's difficult to distinguish logs by different sessions in the function.
Adding a task id (uuid) for each function request in the container log, so that user can query logs which belong to the same session.

## Expected Behaviour

Add a uuid for function container log like:
2018/04/03 08:35:24 5898682c-edb8-4f71-9e45-992bd1cf4fca stderr: This should be an error message.

## Current Behaviour

The log in the function container is like:
2018/04/03 08:35:24 stderr: This should be an error message.

## Possible Solution

Generate a unique id for the function logger after timestamp

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Without the unique id info, it's difficult to check the error log belongs to which session. All requests have similar output.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  5fcdc692e4adf04977775ea78f79b3534a44fb36
 version: 0.8.21

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Request for comment - @stefanprodan @LucasRoesler

**Comment by LucasRoesler** [comment]
The ideal solution, imo, would be to support and document additional headers in the gateway (and watchdog) and then allow the ingress to set this ID value as a header.  The function would then be responsible to extract this information and to put it in their logs (or to set traces, etc). But this would allow integration with various tracing services and this kind of request id behavior. I don't think it is a good idea to have the gateway or the watchdog generate this id, since there are so many ways to generate and integrate with external services that will ultimately provide more value. 

It is also important to note that the content and structure of the function logs are going to be determined by the function template and your handler implementation.  Both the [default watchdog](https://github.com/openfaas/faas/tree/master/watchdog)  and the [of-watchdog](https://github.com/openfaas-incubator/of-watchdog) implementations support a `write_debug`  ENV variable that will "Write all output, error messages, and additional information to the logs. Default is false".  This will allow you to produce logs in your function handler and have them printed to the container.

**Comment by lihaiswu** [comment]
Yes, `write_debug` ENV variable will write the output to container log, but all requests will have same output. No way to filter logs with same context.

After adding `sys.stderr.write("This should be an error message.\n")` to the function, current log will have `2018/04/03 08:35:24 stderr: This should be an error message.`. Is there any way to just change the timestamp string `2018/04/03 08:35:24` or log type `stderr` to append a uuid ?

**Comment by Waterdrips** [comment]
Can this not already be done with `Http_` headers as shown in the workshop? https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables 

The inclusion of the "unique task id" into the log string format within the function can be controlled by using a Python logger within the code?

**Comment by LucasRoesler** [comment]
@lihaiswu my original point is that this is currently possible and I think it is the something the function or template author will need to implement. As @Waterdrips says, it should be supported via the Http headers. Not forcing a particular convention allows maximum flexibility to use your preferred tools.

In your example, the `sys.stderr.write` call should include the id:

```py
# get id from the env variables or generated one as a backup incase we can't find it
request_id = os.environ.get("Http_X_Request_Id", generate_id())
sys.stderr.write("request: {} This should be an error message.\n".format(request_id))
```

of course, you probably want to create a utility method for that or alternatively use Python log adapters to add this information via the logger https://docs.python.org/3/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information  This would ultimately look something like 

```py
logger = logging.getLogger(__name__)

def handler(...):
    request_id = os.environ.get("Http_X_Request_Id", generate_id())
    log = CustomAdapter(logger, {'request_id': request_id})

    ...

    log.error("This should be an error message")
    
    ...
```

You can then choose how to populate that header in a way that best fits your needs. For example, if you are using kubernetes with the  Nginx Ingress, then there is a helm variable to ensure all requests get a unique id and this is populated in the `Http_X_Requst_Id` header https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#generate-request-id .   If you are using a different load balancer the configuration will be different, but, most support this functionality.

At my work we use Jaeger, and by having this flexibility, we are able to add tracing between various service calls, including our functions without needing to fight any convention in OpenFaaS.  If OpenFaaS was creating and passing ids around, these would be completely useless bits for our configuration and noise in our logs.

**Comment by lihaiswu** [comment]
Thanks very much @LucasRoesler and @Waterdrips for detail explanation. I think the above solution should solve my questions.
