### ISSUE TITLE
Proposal: Support directly pushing Docker images

### ISSUE THREAD

**Issue by ad-si** [openfaas/faas#1264]
I wanted to use OpenFaas because of it's ease of use in comparison to other solutions (one click installation on DitigalOcean), but I'll have to abandon this experiment, as it's way too complicated to set up access to a private container registry (Check out https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry. It's insane…).

## Expected Behaviour

`faas up` should push my docker image directly to my OpenFaas installation

## Current Behaviour

A intermediate registry is needed, which is very complicated to set up.

## Possible Solution

Provide a `gateway.org/registry` endpoint where the `faas` cli tool pushes the images

## Your Environment

https://marketplace.digitalocean.com/apps/openfaas

**Comment by Waterdrips** [comment]
Have you seen this in the docs? https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes 

I managed to get my OpenFaaS K8s cluster to pull from a private dockerhub registry quite easily using this as reference.

**Comment by ad-si** [comment]
My workaround for the time being is a `faas-deploy` makefile target:

```makefile
.PHONY: faas-build
faas-build:
	# Build images
	faas --yaml openfaas.yaml build


.PHONY: faas-upload
faas-upload: faas-build
	# Upload Docker image to OpenFaaS server
	docker save -o scan.tar qthority/scan
	scp -i ~/.ssh/long_rsa ./scan.tar root@$(openfaas-gateway):/


.PHONY: faas-load
faas-load: faas-upload
	# Load image on sever
	ssh \
		-i ~/.ssh/long_rsa \
		root@$(openfaas-gateway) \
		docker load -i /scan.tar


.PHONY: faas-deploy
faas-deploy: faas-load
	faas --yaml ./openfaas.yaml deploy
```

**Comment by ad-si** [comment]
Another solution could be to co-deploy the [official registry](https://hub.docker.com/_/registry) on the OpenFaaS image from the Docker Marketplace.

**Comment by Waterdrips** [comment]
I'm a little unsure of the motivation behind this proposal still - you can use any private docker repository you want (dockerhub, ECR, GCR ....) by using the link 
--> https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes
Follow the steps of creating the secret, then mounting the secret by putting this in your stack.yaml for that function 
```
secrets:
      - dockerhub (or whatever you called the secret when you created it)
```

which is just a section from your link
--> https://kubernetes.io/docs/concepts/containers/images/#creating-a-secret-with-a-docker-config

You will need to be authenticated with that repository on the shell where you run the `faas up` command to push the image to that repository. 

Let me know if you want a hand with this - happy to help.

**Comment by ad-si** [comment]
That's waaaay too complicated, for what's basically a file upload. Sure, a registry makes sense If I want to share the image with several people (e.g. DockerHub), but I'm not sharing anything here, I'm just uploading it to my OpenFaaS installation.

**Comment by Waterdrips** [comment]
The problem with your approach is it will only work with single node clusters - plus it relies on having root ssh access to the node. 

I really don't agree that this is `waaaay too complicated` - its 2 lines in the stack.yaml and 1 kubernetes secret. Then authenticating with your container registry - 2 minutes work at most.

Correct me if I'm wrong @alexellis but bundling a container registry with openfaas installations would be beyond the scope of this project.

**Comment by burtonr** [comment]
@Waterdrips you're right in saying that bundling a container registry is outside the scope of this project. 

@ad-si what you're asking for is a special scenario that is outside the normal development process for most. Using a private registry (like DockerHub, ECR, GCR, etc) are common uses for uploading private images. This process is well documented and tested with OpenFaaS and is the suggested solution.

Although you're not sharing the image "with several people", you're sharing it with you (your local machine), potentially the build server(s), and the cluster of machines that are running the image. Doing a direct file upload would not be feasible with this dynamic environment.

**Comment by burtonr** [comment]
I'm going to close this issue as out of scope, but feel free to continue to comment

**Comment by burtonr** [comment]
Derek close: out of scope

**Comment by alexellis** [comment]
> but I'll have to abandon this experiment, as it's way too complicated to set up access to a private container registry

Like @burtonr mentioned, there are several registry-as-a-service offerings out there which are very strong and reasonably priced.

If you deploy GitLab (also one-click), it comes with a container registry.

If you need help setting up a private container registry, please feel free to ask us on Slack.

Alex

**Comment by alexellis** [comment]
@Waterdrips I think you are right, this is beyond the scope of OpenFaaS and not very modular.

I would be open to deploying an optional registry with OpenFaaS Cloud via ofc-bootstrap: https://github.com/openfaas-incubator/ofc-bootstrap - this is a distribution, and if someone wanted to opt-into it, I think that would be a useful feature request.

As for the core platform, would be helpful to add some links in the OpenFaaS documentation for people who are new to containers and cloud-native? We already have a guide for adding SSL via cert-manager on Kubernetes.

**Comment by ad-si** [comment]
Thanks for your thoughts on this. I guess the limitation that it would only work on single node clusters is good point.

@alexellis I like the idea of including an option for it in the OpenFaaS Cloud. That would certianly be a good combination!
