### ISSUE TITLE
Feature Request UI: View functions annotations/labels

### ISSUE THREAD

**Issue by kwojcicki** [openfaas/faas#1273]
From what I have seen here https://github.com/openfaas/faas/pull/871 the UI is under a code freeze/not being touched much. 

Once the transition to a new JS library has been done. It would be nice to see a functions annotations + labels in the UI without resorting to the CLI :)

**Comment by burtonr** [comment]
How would you expect to be able to view the annotations, labels, etc?

I worry that the UI would become over crowded with all of that information. Do you have an example from somewhere else to inspire a design? Or, even better if you could mock it up. 

The issue you linked shows that we recently added those additional fields when creating a function in the UI. I do agree that those should also be visible when viewing the function.It's a good suggestion, just need to think about a good design.

**Comment by alexellis** [comment]
I would like to see a mock-up of this.

Contributions to the angular UI are welcome. Burton is putting some tweaks and changes together.

**Comment by kwojcicki** [comment]
I quite like it how k8s dashboard does it:
![image](https://user-images.githubusercontent.com/2487946/62642522-e7717380-b913-11e9-9f38-22917ab9b6a5.png)

May get slightly congested if someone has 10s of annotations. Could add some drawer type expansion to minimize the clutter.

![image](https://user-images.githubusercontent.com/2487946/62642501-dcb6de80-b913-11e9-8355-cd7a0d51f731.png)

Quick editing in the browser of what it could look like. 

I like the idea of having each key/value pair in a pill makes the key/value pair obvious and clear where it ends/finishes.

Let me know what you guys think :smile:

**Comment by burtonr** [comment]
I think that looks pretty good! 

Perhaps, for the implementation, we could use a drawer to hold all the metadata that could slide out if the user chose. That would keep the current UI relatively unchanged, but with the option to show additional information.

That way, we could include showing the annotations, labels, secrets, and env vars. I think all that would be too much to stick in there constantly. I could be wrong. I think we'd need to test it out a bit.

@kwojcicki would you be willing to put together a sample and upload a gif, or short video of the functionality? If not, I could do it, but it would need to wait until the UI tutorial panel is completed (hopefully over this coming weekend)

Let me know here, or on Slack, if you need any help!

**Comment by kwojcicki** [comment]
@burtonr I think the drawer holding the metadata is a good approach.

I will happily work on this feature :smile: probably wont be able to work on it till next week however.

**Comment by burtonr** [comment]
Great to hear! No hurry, but do keep us informed of the progress. If you aren't able to work on it, we can get someone else to jump in. No worries. Thanks for helping out! 

Let me know if you need anything!
