### ISSUE TITLE
the fuction will be pended when it trys to scale

### ISSUE THREAD

**Issue by ChaosCodes** [openfaas/faas#1274]
## My actions before raising this issue

- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](https://github.com/issues)

## Expected Behaviour
The output of the script will be shown one by one and will not stop until it comes to 1000.

## Current Behaviour
The output was stop at a certain number when the function try to scale maked as Not Ready for several second and then continued to run.

## Possible Solution
Because the problem is that I only use one node to build up OpenFass, but when I add another nodes in the swarm, it seems that the master doesn't distribute the task to the other work nodes.

## Steps to Reproduce (for bugs)
1. Deploy a function 
my code of function
```python
import json
import random

def handle(req):
    r = req
    with open('./function/idioms_dict.json', 'r') as f:
        words = json.load(f)

    return r

```
2. run the script
```shell
for i in {0..1000};
do
  echo -n "$i" | faas-cli invoke idoim-follow && echo;
done;
```
3. It will be bended when it comes to around 340.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

CLI:
 commit:  b42d0703b6136cac7b0d06fa2b212c468b0cff92
 version: 0.8.11
* Docker version `docker version` (e.g. Docker 17.0.05 ):

 Docker  18.09.2
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS 10.14.5

**Comment by alexellis** [comment]
Hi I'm going to close this issue because load testing is explained in the documentation.

https://docs.openfaas.com/architecture/performance/

Alex
