### ISSUE TITLE
Support request: architecture for triggering functions based upon time

### ISSUE THREAD

**Issue by Flavsditz** [openfaas/faas#1276]
## Expected Behaviour

Triggering functions in a scheduled manner should allow a granularity smaller than a Minute, i.e. at least having seconds as the possible interval (1 - 59 secs), no need to go to the milliseconds' realm here.

## Current Behaviour

Currently, we are dependant on Cron which allows 1 minute as the smallest possible interval. Although it works for a lot of cases it does not cover cases such as ours: a polling mechanism that should check, for example, every 10 seconds for new data on a DB table (and pass it along down the line).

## Possible Solution

I haven't found a good alternative, hence why I am posting here. I've read/tried some hacks and workarounds including:
- Using Cron --> Multiple CronJobs with Sleep before calling the task (too "hacky")
- Using some Framework (like Quartz for Java) --> Have a scheduler call the HTTP Endpoint for the poller function

These might work, but they are hacks and can fail if a pod is restarted or have some sort of race conditions due to the sleep. 

## Context

We need to write a poller that does a SELECT to DB every 5 seconds. Because there are other cases here, where we would have 10, 20, 30 or other values in seconds we need something that can work with seconds. For cases higher than seconds we can use CronJob.
We are trying to find an alternative with Functions, but we are also trying to avoid the misuse of functions through having a long-lived function to do the polling.

If someone has had the use-case and could provide a nice pattern used to solve this I would appreciate.
If someone can brainstorm together for a possible solution I believe everyone can profit.

**Comment by doowb** [comment]
I didn't try this with OpenFaaS yet, but I have on AWS using this pattern:

- SQS (the "db" I was polling)
- CloudWatch (Scheduled Rule every 1 minute)
- Lambda (function to poll SQS every X seconds for 1 minute)

My use case was different and I wouldn't have used this setup if SQS could trigger Lambda directly, but I think it works better for your use case:

- database to poll
- cron job scheduled every 1 minute
- function triggered by cron job that runs for 1 minute to trigger another (async?) function every 5 seconds
- function to poll database

I'm suggesting 2 functions in case the database query takes longer than 5 seconds. You can call the second function async if running the query before it finishes is okay, or sync if you need to wait on the previous function.

**Comment by alexellis** [comment]
/set title: Support request: architecture for triggering functions based upon time

**Comment by alexellis** [comment]
Hi @Flavsditz 

I was initially confused with this issue because it is worded like a bug report.

Please correct me if I'm wrong here, but it looks like you want some commercial support with your architecture? This would probably be best achieved through Slack.

You may also be interested in the [cron-connector](https://github.com/zeerorg/cron-connector) which is a third-party component. It may support triggering sub-minute, and if it doesn't then the maintainer (@zeerorg) may be interested in adding it.

If you do need commercial support, please don't hesitate to reach out.

Alex

**Comment by alexellis** [comment]
Other triggers from the project / community - https://docs.openfaas.com/reference/triggers/
