### ISSUE TITLE
 no ~/.openfaas dir nor faas_pass.txt - gateway access errs with code 500 

### ISSUE THREAD

**Issue by marxenegls** [openfaas/faas#1280]
I cloned and moved the faas dir to an external partition , it runs but when having to cat password i cant find the .openfaas dir anywhere , I have ~/template + functions 
faas-cli made use of /tmp and installed at /usr/local/bin

faas linked to >/usr/local/bin/faas-cli 
 faas stack deploys but i get an error on gateway; Get : unsupported protocol scheme ""

I also tried changing the url/ip on the stack_arm.yml to point to a node but that didn't work , instead after failing to launch the gateway container three times it pointed towards another node 
I changed back to xdefault 127.0.0.1 :8080 
afterall it would be accessible on any node 
Swarm mode is already up and running so it isnt launched by faas .. 

$ faas-cli secret list
WARNING! Using --password is insecure, consider using: cat ~/faas_pass.txt | faas-cli login -u user --password-stdin
Calling the OpenFaaS server to validate the credentials...

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Server returned unexpected status code: 500 - Get : unsupported protocol scheme "" 

I have a local regisrty-arm and i'm also logged into Dockerhub acc /repo
wondering if that has something to do with the need for SSL

 
## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
version: 0.9.0
* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.0.3
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm x4 on /HypriotOs + /Portainer
* Operating System and version (e.g. Linux, Windows, MacOS):
raspbian  4.19.57-v7+
pi3B x4
Portainer 
I had tried installing Openfaas via its own App template store but failed 
auth issues among others

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
logs gateway :

2019/08/09 04:24:53 HTTP Read Timeout: 5m5s
2019/08/09 04:24:53 HTTP Write Timeout: 5m5s
2019/08/09 04:24:53 Binding to external function provider: http://faas-swarm:8080/  <? 
set in docker-compose.armhf.yml - docs never mentioned editing it , just stack_arm.yml
2019/08/09 04:24:53 Async enabled: Using NATS Streaming.
2019/08/09 04:24:53 Opening connection to nats://nats:4222
2019/08/09 04:24:53 Connect: nats://nats:4222
2019/08/09 04:24:53 nats: no servers available for connection

I deleted the images and will be starting fresh but still i can't find ~/.openfaas nor password/secret 
not even in the $pwd/faas /mnt/extstorage  point 
--no-auth flag ?

**Comment by rgee0** [comment]
Can you complete the issue as per the issue template and link to any guide you might be following, please?

**Comment by marxenegls** [comment]
hi thankx for quick reply
https://docs.openfaas.com/deployment/docker-swarm/
https://docs.openfaas.com/deployment/troubleshooting/#i-forgot-my-gateway-password 
https://blog.alexellis.io/quickstart-openfaas-cli/

i'm wondering if the fact that the external drive is in ntfs ,rather than ext4 might have something to do with it. i have had no issue running tones on images from it before though ...

**Comment by marxenegls** [comment]
I moved fass dir to ~/faas 
removed the previous images and redeployed anew ,seems like the creds are still seen by the install script and still no ~/.openfass dir or faas_pass.txt 

$ ./deploy_stack.sh
Attempting to create credentials for gateway..
Error response from daemon: rpc error: code = AlreadyExists desc = secret basic-auth-user already exists
Error response from daemon: rpc error: code = AlreadyExists desc = secret basic-auth-password already exists
[Credentials]
 already exist, not creating

Enabling basic authentication for gateway..

Deploying OpenFaaS core services for ARM
Creating service func_gateway
Creating service func_basic-auth-plugin
Creating service func_faas-swarm
Creating service func_nats
Creating service func_queue-worker
Creating service func_prometheus
Creating service func_alertmanager

maybe had to remove the secret first too from secrets, duuh!

**Comment by marxenegls** [comment]
it worked 

i moved faas dir to home created ~/.openfaas , removed the secret from portainer's secrets list 
redeployed and am now logged in ui 
 - i used --no-auth flag but it still wet ahead and created the creds

**Comment by alexellis** [comment]
Hi 👋 thanks for using OpenFaaS.

I would recommend redeploying with the authentication turned on

Use these instructions to find your password - https://docs.openfaas.com/deployment/troubleshooting/#i-forgot-my-gateway-password

The issue template has a link to this guide, and one of the checkboxes states "I have read the troubleshooting guide" 😄 I guess you may have missed that.

Have fun

Alex

**Comment by spiazzi** [comment]
Hi all,

I installed OpenFass on a raspberry docker swarm
I followed this
$ git clone https://github.com/alexellis/faas/
$ cd faas
$ ./deploy_stack.sh


Attempting to create credentials for gateway..
x5s3cii94b5h1rwhjabva4hjr
cwpyvwvof553mix7gt8gcbhiq
[Credentials]
 username: admin 
 password: xxxx
 echo -n xxxx | faas-cli login --username=admin --password-stdin

Enabling basic authentication for gateway..

Deploying OpenFaaS core services for ARM
Creating network func_functions
Creating config func_prometheus_rules
Creating config func_alertmanager_config
Creating config func_prometheus_config
Creating service func_prometheus
Creating service func_alertmanager
Creating service func_gateway
Creating service func_basic-auth-plugin
Creating service func_faas-swarm
Creating service func_nats
Creating service func_queue-worker


When I try to use the web console I get:
Get : unsupported protocol scheme ""

from fans-cli
 $ faas-cli secret list
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Server returned unexpected status code: 500 - Get : unsupported protocol scheme ""

I tried also to create folder  ~/.openfaas  but it don't work.
Please what I can do to fix?

**Comment by rgee0** [comment]
Please create a new issue completing all the template fields. This is to provide use with the minimum amount of info needs for us to be able to help. Thanks.

**Comment by rgee0** [comment]
Derek lock
