### ISSUE TITLE
Update Travis to the latest Go releases

### ISSUE THREAD

**Issue by cristaloleg** [openfaas/faas#1281]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

OpenFaaS should be built with the latest Go release. 

## Current Behaviour

Currently on Travis old Go 1.9 version is used.

## Possible Solution

Bump a version.

**Comment by alexellis** [comment]
Hi, thank you for your interest in contributing to the project.

Fortunately we don't use go from the Travis runtime to build the code comma we use Docker. 

For that reason this pull request is not needed. Going forward I would encourage you to raise any issue and wait for approval before working on any future patches. 

Alex

**Comment by alexellis** [comment]
I would encourage you to read our project and community contribution guide. There is also a page with helpful resources in the docs.

I'm sure that if you join slack and ask if you can help in the #contributors channel, then somebody will find you something to contribute.
