### ISSUE TITLE
Unable to build a python sample using docker

### ISSUE THREAD

**Issue by joaompinto** [openfaas/faas#1289]
## My actions before raising this issue
- [X ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ X] Read/searched [the docs](https://docs.openfaas.com/)
- [ X] Searched [past issues](/issues)

Trying to build a python based sampled on Fedora 30 failes with an error:
$  faas-cli new callme --lang python # Ran without errors
```
$ faas-cli build -f callme.yml 
[0] > Building callme.
Clearing temporary build folder: ./build/callme/
Preparing ./callme/ ./build/callme//function
Building: callme:latest with python template. Please wait..
Sending build context to Docker daemon 8.192 kB
Step 1/29 : FROM openfaas/classic-watchdog:0.15.4 as watchdog
Error parsing reference: "openfaas/classic-watchdog:0.15.4 as watchdog" is not a valid repository/tag: invalid reference format
2019/08/21 15:57:27 ERROR - Could not execute command: [docker build -t callme:latest .]

```
## Expected Behaviour

I would expect a docker image to be build.

It would be nice to have a debug/verbose flag to understack what is the exact docker command being invoked.

## Steps to Reproduce (for bugs)

1.faas-cli new callme --lang python # Ran without errors
2.faas-cli build -f callme.yml 
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  893972afffa5ea6672faa6e11743ae46322ec58c
 version: 0.9.2

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-67.git1185cfd.fc30.x86_64
 Go version:      go1.12.2
 Git commit:      1185cfd/1.13.1
 Built:           Mon Apr 22 17:46:35 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-67.git1185cfd.fc30.x86_64
 Go version:      go1.12.2
 Git commit:      1185cfd/1.13.1
 Built:           Mon Apr 22 17:46:35 2019
 OS/Arch:         linux/amd64
 Experimental:    false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by joaompinto** [comment]
This seems to be related to the docker version (based in the similar issue https://github.com/spotify/docker-maven-plugin/issues/264 ). 
This faas-cli should check and report if docker version does not meet the minimum required version.

**Comment by alexellis** [comment]
@joaompinto feel free to log your feature request on the faas-cli issue.

@haru01 I'm going to close this issue since you are not using the minimum specified version of Docker. Your version doesn't support multi-stage builds.

Please update Docker, and let us know if you need any other technical support by joining Slack.

Alex
