### ISSUE TITLE
User support request: scale from zero on VMware cluster

### ISSUE THREAD

**Issue by lihaiswu** [openfaas/faas#1290]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

The request will be stuck when invoking 0 replica function until invoking function again

## Expected Behaviour

The cache request should receive response after auto acaling replica from 0 to 1

## Current Behaviour
The cache request get stuck until another requst is sent to invoke the function

## Possible Solution

Not sure when the cache request will be sent to function after the pod is ready. I tried to deploy with LoadBalancer or Ingress. Both are same result. I also try to deploy it to other k8s cluster env, all are same results.

## Steps to Reproduce (for bugs)

1. kubectl scale deployment/figlet --replicas=0
2. echo 'test' | faas-cli invoke figlet
3. pod is creating, then change to running
4. the request in step2 gets stuck
5. invoke another request: echo 'test' | faas-cli invoke figlet
6. the request in step2 receives response

## Context

I cannot use Zero-scale feature in openfaas. Need to alway keep at least 1 replica for each function.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  750add9e2a6d1d1f1bfb788a6a85341b4b4140e8
 version: 0.8.22

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Code example or link to GitHub repo or gist to reproduce problem:
My k8s namespace has multiple nodes.

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.
Already discussed the issue in slack. And i have tried to switch to different namespace, but hit the same problem.

**Comment by alexellis** [comment]
/set title: support request for scale from zero

**Comment by lihaiswu** [comment]
Following is the logs from gateway

```
2019/08/21 21:37:50 Forwarded [GET] to /healthz - [200] - 0.000657 seconds
2019/08/21 21:37:52 GetReplicas took: 0.003782s
2019/08/21 21:37:52 GetReplicas took: 0.003007s
2019/08/21 21:37:52 [Scale 0] function=figlet 0 => 1 requested                    **===> first invoke**
2019/08/21 21:37:52 GetReplicas took: 0.003186s
2019/08/21 21:37:52 GetReplicas took: 0.003102s
2019/08/21 21:37:52 GetReplicas took: 0.003616s
2019/08/21 21:37:52 GetReplicas took: 0.003265s
2019/08/21 21:37:52 GetReplicas took: 0.004599s
2019/08/21 21:37:52 GetReplicas took: 0.003554s
2019/08/21 21:37:52 GetReplicas took: 0.003029s
2019/08/21 21:37:52 GetReplicas took: 0.004005s
2019/08/21 21:37:52 GetReplicas took: 0.005906s
2019/08/21 21:37:52 GetReplicas took: 0.003589s
2019/08/21 21:37:52 GetReplicas took: 0.003547s
2019/08/21 21:37:52 GetReplicas took: 0.129502s
2019/08/21 21:37:53 GetReplicas took: 0.154732s
2019/08/21 21:37:53 GetReplicas took: 0.146946s
2019/08/21 21:37:53 GetReplicas took: 0.155716s
2019/08/21 21:37:53 GetReplicas took: 0.142921s
2019/08/21 21:37:53 GetReplicas took: 0.152525s
2019/08/21 21:37:54 GetReplicas took: 0.151823s
2019/08/21 21:37:54 GetReplicas took: 0.144519s
2019/08/21 21:37:54 GetReplicas took: 0.154899s
2019/08/21 21:37:54 GetReplicas took: 0.149625s
2019/08/21 21:37:54 GetReplicas took: 0.144879s
2019/08/21 21:37:54 Forwarded [GET] to /healthz - [200] - 0.000382 seconds
2019/08/21 21:37:55 GetReplicas took: 0.151535s
2019/08/21 21:37:55 GetReplicas took: 0.350686s
2019/08/21 21:37:55 GetReplicas took: 0.150979s
2019/08/21 21:37:55 GetReplicas took: 0.146037s
2019/08/21 21:37:56 GetReplicas took: 0.151319s
2019/08/21 21:37:56 GetReplicas took: 0.148973s
2019/08/21 21:37:56 GetReplicas took: 0.148711s
2019/08/21 21:37:56 GetReplicas took: 0.150353s
2019/08/21 21:37:56 GetReplicas took: 0.149931s
2019/08/21 21:37:57 GetReplicas took: 0.149328s
2019/08/21 21:37:57 GetReplicas took: 0.154756s
2019/08/21 21:37:57 GetReplicas took: 0.149627s
2019/08/21 21:37:57 GetReplicas took: 0.145383s
2019/08/21 21:37:57 GetReplicas took: 0.152617s
2019/08/21 21:37:58 GetReplicas took: 0.149927s
2019/08/21 21:37:58 GetReplicas took: 0.149263s
2019/08/21 21:37:58 GetReplicas took: 0.151981s
2019/08/21 21:37:58 GetReplicas took: 0.147610s
2019/08/21 21:37:58 GetReplicas took: 0.152151s
2019/08/21 21:37:59 GetReplicas took: 0.144577s
2019/08/21 21:37:59 GetReplicas took: 0.149870s
2019/08/21 21:37:59 GetReplicas took: 0.155089s
2019/08/21 21:37:59 GetReplicas took: 0.149484s
2019/08/21 21:37:59 GetReplicas took: 0.148827s
2019/08/21 21:38:00 GetReplicas took: 0.150742s
2019/08/21 21:38:00 GetReplicas took: 0.344933s
2019/08/21 21:38:00 GetReplicas took: 0.149647s
2019/08/21 21:38:00 Forwarded [GET] to /healthz - [200] - 0.000482 seconds
2019/08/21 21:38:00 GetReplicas took: 0.149852s
2019/08/21 21:38:01 GetReplicas took: 0.149977s
2019/08/21 21:38:01 GetReplicas took: 0.148961s
2019/08/21 21:38:01 GetReplicas took: 0.149739s
2019/08/21 21:38:01 GetReplicas took: 0.150261s
2019/08/21 21:38:01 GetReplicas took: 0.149213s
2019/08/21 21:38:02 GetReplicas took: 0.149826s
2019/08/21 21:38:02 GetReplicas took: 0.154772s
2019/08/21 21:38:02 GetReplicas took: 0.145720s
2019/08/21 21:38:02 GetReplicas took: 0.149614s
2019/08/21 21:38:02 GetReplicas took: 0.149346s
2019/08/21 21:38:03 GetReplicas took: 0.153400s
2019/08/21 21:38:03 GetReplicas took: 0.153557s
2019/08/21 21:38:03 [Scale] function=figlet 0 => 1 successful - 11.153421 seconds                 **===> pod ready, but first invoke get stuck**
2019/08/21 21:38:04 Forwarded [GET] to /healthz - [200] - 0.000439 seconds
2019/08/21 21:38:10 Forwarded [GET] to /healthz - [200] - 0.000431 seconds
2019/08/21 21:38:14 Forwarded [GET] to /healthz - [200] - 0.000487 seconds
2019/08/21 21:38:20 Forwarded [GET] to /healthz - [200] - 0.000508 seconds
2019/08/21 21:38:24 Forwarded [GET] to /healthz - [200] - 0.000472 seconds
2019/08/21 21:38:30 Forwarded [GET] to /healthz - [200] - 0.000552 seconds
2019/08/21 21:38:34 Forwarded [GET] to /healthz - [200] - 0.000795 seconds
2019/08/21 21:38:34 GetReplicas took: 0.004120s                                **===> second invoke**
2019/08/21 21:38:35 Forwarded [POST] to /function/figlet - [200] - 0.015670 seconds      **===> second invoke receive response**
2019/08/21 21:38:35 Forwarded [POST] to /function/figlet - [200] - 31.689608 seconds.   **===> first invoke receive reponse now**
2019/08/21 21:38:40 Forwarded [GET] to /healthz - [200] - 0.000499 seconds
2019/08/21 21:38:44 Forwarded [GET] to /healthz - [200] - 0.000492 seconds
```

**Comment by alexellis** [comment]
We discussed this at length on Slack today and were not able to reproduce the issue with either k3s or DigitalOcean Kubernetes across 5 nodes using Cilium for networking.

This may be specific to the Kubernetes networking or distribution you are using at VMware.

**Comment by alexellis** [comment]
I don't think we will be able to reproduce your environment, but we can keep trying to reproduce the error behaviour on publicly available systems.

**Comment by lihaiswu** [comment]
Thanks @alexellis . Let's keep it opened and see if anyone hit the similar issue or not.

**Comment by alexellis** [comment]
Could you perhaps try to reproduce it using Minikube, kind, or k3s? Are there specific steps or networking drivers that cause it?

**Comment by lihaiswu** [comment]
Sometime, the first request just receives 502 as folloing log:

```
2019/08/21 21:51:19 [Scale] function=figlet 0 => 1 successful - 12.356267 seconds
2019/08/21 21:51:20 Forwarded [GET] to /healthz - [200] - 0.000705 seconds
2019/08/21 21:51:20 error with upstream request to: , Post http://figlet.scdc1-staging-openfaas-fn.svc.cluster.local:8080: dial tcp 172.21.234.251:8080: connect: connection refused
2019/08/21 21:51:20 Forwarded [POST] to /function/figlet - [502] - 1.028161 seconds
```

After that, all incoming requests work fine.

**Comment by lihaiswu** [comment]
Based on the error log `error with upstream request to: , Post http://figlet.scdc1-staging-openfaas-fn.svc.cluster.local:8080: dial tcp 172.21.234.251:8080: connect: connection refused`, I found  `requestURL` is  '' .  From source code https://github.com/openfaas/faas/blob/master/gateway/handlers/forwarding_proxy.go#L65 , what might cause this problem? @alexellis @stefanprodan 

Or could you please suggest what debug code i can add to make a local to print more infomation why the request is rejected.

**Comment by alexellis** [comment]
What Kubernetes distribution are you using?

What networking driver does it use?

**Comment by lihaiswu** [comment]
@alexellis we're using Upstream kubernetes 1.14.3 with flannel overlay network.

**Comment by alexellis** [comment]
Thanks for the info. The more, the better chance we have to reproduce it for you.

What infrastructure is it running on? Hypervisor etc

What tooling was used to initialize/join nodes?

**Comment by lihaiswu** [comment]
@alexellis we're using vSphere + Ansible

**Comment by lihaiswu** [comment]
@alexellis The scale from zero will work after adding "sleep 3 seconds" before calling `res, resErr := proxyClient.Do(upstreamReq.WithContext(ctx))`(https://github.com/openfaas/faas/blob/master/gateway/handlers/forwarding_proxy.go#L128):

```
	if requestURL == "" {
		log.Printf("%s: sleeping 3 second", baseURL)
		time.Sleep(3 * time.Second)
	}
	res, resErr := proxyClient.Do(upstreamReq.WithContext(ctx))
```

So the problem looks like the Golang webserver is not fully ready before forwarding the request.  I did try sleep 1 and 2 seconds will not work. I tested it with figlet function. Any other configuraiton i missed for health check or it's potential issue in the code?

Following is the sucessful log from gateway:
```
2019/08/23 00:10:28 [Scale] function=figlet 0 => 1 successful - 11.611145 seconds
2019/08/23 00:10:28 http://figlet.scdc1-staging-openfaas-fn.svc.cluster.local:8080: sleeping 3 second
2019/08/23 00:10:31 Forwarded [POST] to /function/figlet - [200] - 3.011097 seconds
2019/08/23 00:10:35 Forwarded [GET] to /healthz - [200] - 0.000566 seconds
2019/08/23 00:10:36 Forwarded [GET] to /healthz - [200] - 0.000637 seconds
2019/08/23 00:10:45 Forwarded [GET] to /healthz - [200] - 0.000900 seconds
2019/08/23 00:10:46 Forwarded [GET] to /healthz - [200] - 0.000608 seconds
2019/08/23 00:10:55 Forwarded [GET] to /healthz - [200] - 0.000565 seconds
2019/08/23 00:10:56 Forwarded [GET] to /healthz - [200] - 0.000514 seconds
2019/08/23 00:11:05 Forwarded [GET] to /healthz - [200] - 0.000478 seconds
2019/08/23 00:11:06 Forwarded [GET] to /healthz - [200] - 0.000599 seconds
2019/08/23 00:11:15 Forwarded [GET] to /healthz - [200] - 0.000628 seconds
2019/08/23 00:11:16 Forwarded [GET] to /healthz - [200] - 0.000646 seconds
2019/08/23 00:11:20 Forwarded [GET] to /system/functions - [200] - 0.006275 seconds
2019/08/23 00:11:25 Forwarded [GET] to /healthz - [200] - 0.000507 seconds
2019/08/23 00:11:26 Forwarded [GET] to /healthz - [200] - 0.000612 seconds
2019/08/23 00:11:35 Forwarded [GET] to /healthz - [200] - 0.000519 seconds
2019/08/23 00:11:36 Forwarded [GET] to /healthz - [200] - 0.000632 seconds
2019/08/23 00:11:45 Forwarded [GET] to /healthz - [200] - 0.000676 seconds
2019/08/23 00:11:46 Forwarded [GET] to /healthz - [200] - 0.000603 seconds
2019/08/23 00:11:55 Forwarded [GET] to /healthz - [200] - 0.000543 seconds
2019/08/23 00:11:56 Forwarded [GET] to /healthz - [200] - 0.000762 seconds
2019/08/23 00:12:05 Forwarded [GET] to /healthz - [200] - 0.000592 seconds
2019/08/23 00:12:06 Forwarded [GET] to /healthz - [200] - 0.000560 seconds
2019/08/23 00:12:15 Forwarded [GET] to /healthz - [200] - 0.000730 seconds
2019/08/23 00:12:16 Forwarded [GET] to /healthz - [200] - 0.000651 seconds
```

**Comment by lihaiswu** [comment]
Now, i'm adding sleep 5 seconds after `if queryResponse.AvailableReplicas > 0` (https://github.com/openfaas/faas/blob/master/gateway/scaling/function_scaler.go#L118) to bypass the issue. 

```
				log.Printf("%s: sleeping 5 seconds", functionName)
				time.Sleep(5 * time.Second)
```

Any other way i can add a check if the Golang server is ready, instead of just waiting. @alexellis @LucasRoesler @stefanprodan

**Comment by alexellis** [comment]
Sorry we weren't able to help you more with this, it was not possible due to the custom setup you have at work and the lack of access to your environment.
