### ISSUE TITLE
Update gateway build to go 1.11.13

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#1291]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Per the security announcement https://groups.google.com/forum/#!topic/golang-announce/65QixT3tcmg we should update to the Gateway Go version to at least Go 1.11.13

## Possible Solution

The builder layer in the Dockerfile should use `golang:1.11`

### Update Dockerfile and rebuild/release
https://github.com/openfaas/faas/issues/1291
https://github.com/openfaas/templates/issues/170
https://github.com/openfaas/faas-netes/issues/494
https://github.com/openfaas/nats-queue-worker/issues/66
https://github.com/openfaas-incubator/of-watchdog/issues/78
https://github.com/openfaas-incubator/faas-idler/issues/32
https://github.com/openfaas-incubator/golang-http-template/issues/28
https://github.com/openfaas-incubator/faas-federation/issues/4
https://github.com/openfaas-incubator/vcenter-connector/issues/27
https://github.com/openfaas-incubator/faas-memory/issues/3
https://github.com/openfaas-incubator/faas-rancher/issues/8

### Only Rebuild
https://github.com/openfaas/faas-swarm/issues/56
https://github.com/openfaas-incubator/ingress-operator/issues/10
https://github.com/openfaas-incubator/openfaas-operator/issues/87

**Comment by alexellis** [comment]
:+1: 

Anything which states `golang:1.11` should be re-built, since we don't know which "patch/revision" version it may have been built on already.

**Comment by LucasRoesler** [comment]
This actually applies to all of the Dockerfiles in this repo (basic-auth, gateway, and watchdog)

**Comment by alexellis** [comment]
Also [openfaas/templates](https://github.com/openfaas/templates)

Whilst there, if anyone sees `alpine:` lower than `3.10` please update that tag at the same time.

**Comment by alexellis** [comment]
https://github.com/openfaas/templates/commit/56f1b9d833c8fae8549f6234046cdcf0096f22bb

**Comment by alexellis** [comment]
Release: https://github.com/openfaas/faas/releases/tag/0.17.0

**Comment by alexellis** [comment]
Update required to: https://github.com/openfaas/faas/blob/master/docker-compose.yml
