### ISSUE TITLE
Proposal - Update Go to 1.12.8+ - recent CVE mitigations and Go 1.10 no longer receiving security point releases

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas#1293]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Moving to a new Go release has been raised in the past but I think its worth considering again for the following reasons.

- 1.10 no longer receives security point releases per the Go projects [Release Cycle policy](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance)
- Recent CVEs impacting HTTP/2 and Parse have warranted a K8s re-release - its not clear whether we're actually impacted here yet, but staying on 1.10 without the option of an easy upstream fix is not ideal.

The earlier discussion seemed to hang on concerns around [compatibility problems with Alpine](https://github.com/openfaas/faas/issues/875#issuecomment-425626634) with net/http requiring CGO - is this still a concern? (as an aside - would distroless be an option here?).

If we do consider a jump, I would suggest going straight to 1.12.8+, with 1.13rc1 out we'd be hit with the same problem with 1.11 in a few months.

**Comment by johnmccabe** [comment]
Happy to help out as needed.

**Comment by alexellis** [comment]
I believe that we have covered this by upgrading Go 1.11 and re-publishing new releases.

@LucasRoesler to confirm

**Comment by alexellis** [comment]
See also: https://github.com/openfaas/faas/issues/1291

**Comment by johnmccabe** [comment]
Happy enough with the pending EOL (effective, no security point releases) of 1.11?

> If we do consider a jump, I would suggest going straight to 1.12.8+, with 1.13rc1 out we'd be hit with the same problem with 1.11 in a few months

Per the [Go Release Cycle](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance)

**Comment by alexellis** [comment]
Thank you for raising this John, we have updated AFAIK all components to a patched version of Go 1.11
