### ISSUE TITLE
Support request for kubeadm-dind-cluster

### ISSUE THREAD

**Issue by lyuxiaosu** [openfaas/faas#1305]
## Expected Behavior
faas-cli can login the serverless platform deployed on kubeadm-dind-cluster.

## Current Behavior
Connection is refused and login failed. kubeadm-dind-cluster is a docker-in-docker kubernetes cluster, but it shouldn't be such connection refused problem. The service type is NodePort, its port 31112 should be accessible outside of the cluster, however, it's not. 
```
xiaosuGW@node-0:~$ echo -n $PASSWORD | faas-cli login -g $OPENFAAS_URL -u admin --password-stdin
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: http://127.0.0.1:31112. Get http://127.0.0.1:31112/system/functions: dial tcp 127.0.0.1:                                                         31112: connect: connection refused
```
## Steps to Reproduce (for bugs)
1. Deployed a multi-node kubernetes cluster with [kubeadm-dind-cluster](https://github.com/kubernetes-retired/kubeadm-dind-cluster).
2. Generate a random password
```
PASSWORD=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)

kubectl -n openfaas create secret generic basic-auth \
--from-literal=basic-auth-user=admin \
--from-literal=basic-auth-password="$PASSWORD"
```
3. Use NodePorts (default) pass no additional flags to deploy OpenFaaS
```
helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn
````
4. Display the namespace:
```
xiaosuGW@node-0:~$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   40m
kube-node-lease   Active   40m
kube-public       Active   40m
kube-system       Active   40m
openfaas          Active   33m
openfaas-fn       Active   33m
xiaosuGW@node-0:~$
```
Display pods under openfaas and openfaas-fn:
```
xiaosuGW@node-0:~$ kubectl get pods -n openfaas
NAME                                 READY   STATUS    RESTARTS   AGE
alertmanager-8566d97cb5-j54x5        1/1     Running   0          32m
basic-auth-plugin-6679c4d87d-l54pz   1/1     Running   0          32m
faas-idler-6568bb4c9b-l9k9w          1/1     Running   2          32m
gateway-95b8f788c-llmzq              2/2     Running   1          32m
nats-d4c9d8d95-gjxzp                 1/1     Running   0          32m
prometheus-765f54bc8-5kw2b           1/1     Running   0          32m
queue-worker-56b64d6848-jldp5        1/1     Running   0          32m
```
```
xiaosuGW@node-0:~$ kubectl get pods -n openfaas-fn
No resources found.
```
```
xiaosuGW@node-0:~$ kubectl get svc -n openfaas gateway-external -o wide
NAME               TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE    SELECTOR
gateway-external   NodePort   10.98.170.146   <none>        8080:31112/TCP   2m9s   app=gateway
```
5.
```
export OPENFAAS_URL=http://127.0.0.1:31112
```
6. Login this platform but failed
```
xiaosuGW@node-0:~$ echo -n $PASSWORD | faas-cli login -g $OPENFAAS_URL -u admin --password-stdin
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: http://127.0.0.1:31112. Get http://127.0.0.1:31112/system/functions: dial tcp 127.0.0.1:31112: connect: connection refused

```
## Context
I want to do some test comparison with OpenFaaS and Openwhisk but Openwhisk can be successfully deployed on kubeadm-dind-cluster.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
```xiaosuGW@node-0:~$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  893972afffa5ea6672faa6e11743ae46322ec58c
 version: 0.9.2
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
xiaosuGW@node-0:~$ sudo docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Thu Aug 15 15:12:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
```
Kubernetes
```

* Operating System and version (e.g. Linux, Windows, MacOS):
```
xiaosuGW@node-0:~$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
```
* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi

You'll need to fill out the whole template if you want us to help. https://github.com/openfaas/faas/blob/master/.github/ISSUE_TEMPLATE.md

It has key fields we need you to provide. 

Specifically with `kubeadm-dind-cluster` you'll need to use a kubectl port-forward command. See the Lab 1b for how to do that in https://github.com/openfaas/workshop.

Alex

**Comment by lyuxiaosu** [comment]
> Hi
> 
> You'll need to fill out the whole template if you want us to help. https://github.com/openfaas/faas/blob/master/.github/ISSUE_TEMPLATE.md
> 
> It has key fields we need you to provide.
> 
> Specifically with `kubeadm-dind-cluster` you'll need to use a kubectl port-forward command. See the Lab 1b for how to do that in https://github.com/openfaas/workshop.
> 
> Alex

Thank you for your help. I am sorry I didn't show my question clearly. I used the NodePort service and local kubernetes cluster. It's not a LoadBalancer services. It seems  kubectl port-forward only works for remote cluster or LoadBalancer services, which is not my case. Am I right?

**Comment by lyuxiaosu** [comment]
I think port 31112 is accessible for the outer of the kubeadm-dind-cluster because the service type of gateway-external is NodePort. It should work for ```echo -n $PASSWORD | faas-cli login -g http://127.0.0.1:31112 -u admin --password-stdin ```, but I cannot access it.

**Comment by alexellis** [comment]
You are missing the `port-forward` command. I can't see you running that?

https://github.com/openfaas/workshop/blob/master/lab1b.md#loadbalancer-remote-kubernetes-or-kind

Alex

**Comment by alexellis** [comment]
I'm going to close this issue as I'm 99% certain that you're missing the port-forward and that this is an issue with how you're using your dind-cluster rather than anything in OpenFaaS.

Let me know how you get on with the command I gave, and if you need further technical support for this, please seek it out on Slack.

**Comment by lyuxiaosu** [comment]
@alexellis Your 99% certain is wrong, your recommendation cannot help resolve this problem at all, moreover,  you somehow mislead people. I am not sure if you read my question carefully or not, or if you know what's the difference between Loadbalancer Service type and NodePorts service type. I already stated that I used NodePorts service type for my local cluster, it's not Loadbalancer service type or remote cluster, but you seems didn't understand what I was saying. Do you really understand what is ```port-forward``` command for? It does two ports map, to forward your local machine's port to a pod's port, but I used the NodePorts service type, which means my local machine's port has already mapped to the pod's port. That's the reason why I repeat my confusion multiple times why you mention ```port-forward```, but I am pretty sure you are wrong, I didn't try it.

However, your 99% certain lets me guess this is not a problem of openfaas but mine's since you might have met such wrong messages too many times, this makes me to find my wrong, the TRUE solution. Finally, I found the problem. Because I used a dind-cluster which creates two kubernetes nodes in my machine, the openfaas gateway was installed in one of these two nodes and the gateway service  was created on that node with a NodePorts service type.  The port 31112 is visible/accessible outside of the cluster, but the node ip is not 127.0.0.1. You should find the node name on which the gateway is installed, in my cluster, the node name is ```kube-node-1```, then you should get its internal IP with 
```
xiaosuGW@node-0:~$ kubectl get node kube-node-1 -o wide
NAME          STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
kube-node-1   Ready    <none>   72m   v1.14.1   10.192.0.3    <none>        Debian GNU/Linux 9 (stretch)   4.4.0-154-generic   docker://18.9.0
```
So the real IP for gateway is  10.192.0.3, not 127.0.0.1.  Re-export URL
```export OPENFAAS_URL=http://10.192.0.3:31112```
Then login again
```
xiaosuGW@node-0:~$ echo -n $PASSWORD | faas-cli login --username admin --password-stdin
Calling the OpenFaaS server to validate the credentials...
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
credentials saved for admin http://10.192.0.3:31112
```
Problem solved.

**Comment by burtonr** [comment]
Hey @lyuxiaosu sorry for the confusion! Glad you were able to resolve it though! And thanks for taking the time to write out the solution you've found as well

Please do join us on Slack, and let us know if you have any other troubles

**Comment by alexellis** [comment]
The workshop covers both NodePort and port-forwarding, including how to find the correct IP address.

We're giving you our own time to provide you with technical support and help, please try to be respectful and use an appropriate tone. 

If you're new to Kubernetes and struggling with the networking, I would suggest working through the workshop methodically or trying a Kubernetes 101 training online such as https://kubernetes.academy/

**Comment by alexellis** [comment]
/lock: resolved, please seek out any addition support on Slack
