### ISSUE TITLE
[Feature request] Template for Javalin framework 

### ISSUE THREAD

**Issue by koturwaraditi** [openfaas/faas#1306]
Hi I am  aditi 
I am a fresher and I am new  in openfaas and am trying to create a server using javalin framework inside openfaas function. so for that I have provided the same port for javalin which is available in docker file i.e upstream url.
after that i am deploying the openfaas function it is showing 500 internal server error
so can you please help me how to work javalin inside openfaas

**Comment by alexellis** [comment]
Hi @koturwaraditi 

We are using this issue tracker primarily for tracking issue, please can you seek out support in the #templates channel on Slack?

Alex

**Comment by alexellis** [comment]
We'll also need a complete GitHub repo to take a look and help you. Please provide that when you contact us on Slack 👍

**Comment by koturwaraditi** [comment]
Hi Alexellis,

I have registered with my details to your google form ..Please approve it and help us.

Aditi
