### ISSUE TITLE
[Proposal] Separate and Unroll Callback URLs // Allow Multiple Callback URLS

### ISSUE THREAD

**Issue by Miserlou** [openfaas/faas#1323]
Suppose I am building a OpenFaaS functionalized ETL to modify very large images. I have functions `load`, `flip`, `rotate`, `emboss` and `print`.

As it stands (as far as I can tell), I'll only be able to use the first three functions in my pipeline if I'm being asynchronous without using another function for overseeing everything, which defeats the whole purpose of this. From `load`, I'll invoke `flip`, with a callback to `rotate`. `rotate` has no knowledge of what to do next, so it'll end there.

I'd like to have `X-Callback-Url` allow commas, such that the header gets unrolled at every step of the pipeline, ex:

`X-Callback-Url: http://mycluster:8080/async-function/rotate,http://mycluster:8080/async-function/emboss,http://mycluster:8080/async-function/print` - which then gets unrolled to `X-Callback-Url: http://mycluster:8080/async-function/emboss,http://mycluster:8080/async-function/print`, and so on until it hits my printer.

Even better would be if this was a graph approach, so that I could send the output to multiple callbacks at once, though I'm not sure what the syntax for that should be, maybe something like `X-Callback-Url: {http://mycluster:8080/async-function/rotate,http://mycluster:8080/async-function/emboss},http://mycluster:8080/async-function/print`, which would give me two prints, one rotated and one embossed (this would still be useful). 

This approach also gives functions the ability to modify their downstream paths based on their own results, which is also useful and necessary.

**Comment by Miserlou** [comment]
An alternative syntax to consider,

```X-Callback-Url: http://mycluster:8080/async-function/rotate
X-Callback-Url-1: http://mycluster:8080/async-function/emboss
X-Callback-Url-2: http://mycluster:8080/async-function/print
```

unrolling to:

```X-Callback-Url: http://mycluster:8080/async-function/emboss
X-Callback-Url-1: http://mycluster:8080/async-function/print
```

or 

```X-Callback-Url: http://mycluster:8080/async-function/rotate, http://mycluster:8080/async-function/emboss
X-Callback-Url-2: http://mycluster:8080/async-function/print
```

If I want two different prints

**Comment by alexellis** [comment]
Thanks for your suggestion Rich.

> ETL to modify very large images

I would not recommend using the asynchronous pipeline to pass around very large binary data, it has a soft limit of a few MB, so in these cases we generally recommend using Minio or S3 to store each stage. You'll find similar limits with Cloud Functions.

One of the most similar things we've done so far is this -> https://blog.alexellis.io/openfaas-colorisebot-comes-to-kubecon/

I would think it is possible to chain a number of functions together where each passes on to another in the chain. The director pattern is also useful, especially if you don't want to add code to each of your functions to access S3, the director function can do that instead.

>  without using another function for overseeing everything, which defeats the whole purpose of this

Can you elaborate on how it defeats the whole purpose of the pipeline?

I would suggest taking a look at faas-flow from @s8sg, he's done a significant amount of work on this use-case. https://github.com/s8sg/faas-flow/ - workflows are written in Go, which are fairly simple, but if you ask him, he may be willing to add Python support or something else.

I also put together a rudimentary example here -> https://github.com/alexellis/workflow-yaml-template

**Comment by ehengao** [comment]
> I would not recommend using the asynchronous pipeline to pass around very large binary data.

I understand this is a limitaion from NAS streaming. May I ask following questsions:

1. Is it safe to pass large binary data via the invoke API via the gateway? I am not sure if i understand the logic correctly, based on the code written here: https://github.com/openfaas/faas/blob/master/gateway/handlers/forwarding_proxy.go#L145. It looks like the gateway is forwarding the requests towards the function endpoints. Do you think there is any risks passing large binary data this way via the gateway?
2. Some business critical use cases/functions might need the queuing to be persistent to recover the processing after a system failure. It make more sense to me that openfaas can provide some interfaces for users to implement their own messaging brokers like kafka or rabbitmq. Could you please share some of your plans in this area? From the gateway perspective, the interfaces seems to be [this](https://github.com/openfaas/faas/blob/master/gateway/queue/types.go#L22), but the consumer: watchdog gonna needs a new implementaion "kafka-watchdog", for example.  The kafaka connector seems to be a good fit in this case, however, the message still go through the API gateway. If the system failure happens during the message transmission towards the function. Any thoughts?

**Comment by ehengao** [comment]
Looks like Knative has similar concept of KafkaChannel as well as NAT streaming.
https://knative.dev/docs/eventing/channels/channels-crds/

**Comment by alexellis** [comment]
I'm going to lock this issue due to going off topic.

Happy for the topic to be explored further on Slack - perhaps we can condense this discussion down into some clear problem statements / use-cases and then explore whether there is a suitable solution that fits well with the project roadmap.
