### ISSUE TITLE
[Feature Request] Parallel processing of multiple asynchronous functions

### ISSUE THREAD

**Issue by valdyjunior** [openfaas/faas#1330]
## Summary
Hey, everybody,

I'm facing some problems using the asynchronous functions of OpenFaas, especially when it comes to parallelism of execution with two or more functions. I've already read the issue [#1177](https://github.com/openfaas/faas/issues/1177) and I'm opening this one for a better explanation of the problem.
If it is better to merge the two discussions please let me know

## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

## Expected Behaviour
- Requisitions sent to different OpenFaas functions are executed in parallel.
- Using the already suggested in issue #1177 one of the alternatives would be when invoke async function, use x-queue-topic: faas-request-high to route this async function into nats with faas-request-high topic

## Current Behaviour
- Currently only one topic faas-request is supported.

## Possible Solution
- Use multiple topics to divide messages forwarded to different functions, with queue-workers listening on multiple topics.

## Context
My environment is as follows:
- Two asynchronous functions F1 and F2 with five replicas each
- Five queue-workers

I send 342 execution requests, being 324 for function F1 and 18 for function F2. In this scenario, what happens is that as long as the requisitions of function F1 are not all processed and queued out, no F2 requisition is processed. Even if this function is in idle.

I understand that this behavior is not appropriate, because in this way you do not have the rational use of the entire pipeline.

In the following figure it is possible to notice the described behavior, the counter of function F2 only starts to increase when function F1 has already executed all the requests.

![F1-F2-behavior](https://user-images.githubusercontent.com/7912704/65990760-8d4be500-e462-11e9-92ac-3db9ec4d819c.png)

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  893972afffa5ea6672faa6e11743ae46322ec58c
 version: 0.9.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.17.0
 sha:     c8e033f77afc8460c025d0161ca60d8f4b2d1c30
 commit:  Update stage name in Dockerfile


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.7.2 
 sha:           ef7d9132e29edc8ff3962685ba772ad6e3f01bda
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       74b1e89e8a
  Built:            Sat Jul 27 21:08:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

`Docker Swarm`

* Operating System and version (e.g. Linux, Windows, MacOS):

`Manjaro 18.0.4`

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Related Issues
#1177

**Comment by alexellis** [comment]
The asynchronous invocation model acts like a FIFO queue - first in, first out. This behaviour is as designed.

Can you confirm that you are sending all the requests for F1, then those for F2?

**Comment by valdyjunior** [comment]
Yes, @alexellis , I first send all requests to F1 and then all to F2. 

I understand that the behavior of the system is as designed, but do you think it would be plausible to modify the behavior? I'm studying the openfaas code to contribute to this modification.

**Comment by nikhilkhanna** [comment]
Any update on this? I have the same issue where I am queueing up many long running async requests (more than there are queue workers) to a function F1 and then queueing up more requests for a different function F2. The result of this is my deployment that is running F2 is staying idle (with at least 1 minimum deployment) while all the queue workers spend time running and waiting on the F1 calls.

**Comment by alexellis** [comment]
@nikhilkhanna: the update is that this is still on the roadmap. You're welcome to contribute, also we do offer paid consulting/development via OpenFaaS Ltd if that's outside of your skillset/experience.

**Comment by alexellis** [comment]
@valdyjunior @nikhilkhanna @andeplane please see #1513

**Comment by alexellis** [comment]
This is now supported, see the docs for how to access it.
