### ISSUE TITLE
[Feature Request] [UI] Set Callback Url via Web Interface

### ISSUE THREAD

**Issue by Miserlou** [openfaas/faas#1332]
As far as I can see, there is no way to set `X-Callback-Url` from the UI. This makes applications a lot harder to debug. It would be great if there was a field to set this and other headers.

![Screen Shot 2019-10-02 at 8 24 30 PM](https://user-images.githubusercontent.com/139987/66090753-b3e94900-e552-11e9-84d3-5d36b1d8c271.png)

**Comment by jonatasbaldin** [comment]
@alexellis @LucasRoesler we would need to return this information in the REST API, right? Is it possible today?

**Comment by alexellis** [comment]
Thanks for the suggestion @Miserlou, may I ask you to please use the issue template for any issues that you raise against OpenFaaS? This request is effective a "proposal" and much more detailed case is required for those than provided above.

It may also be beneficial to ask some of the questions on Slack before raising an issue here to cut down on work for the maintainers. 

> This makes applications a lot harder to debug

Please could you elaborate on why you think that?

New features are not being accepted for the OpenFaaS UI at this time, the UI is not an exhaustive admin page, but for testing and exploring OpenFaaS.

We encourage all users to use the API or CLI for anything not covered in the UI.

The following will give the async URL for any function:

```
faas-cli describe FUNCTION
```

And `faas-cli invoke --async` will allow asynchronous invocation easily.

Find out more with the workshop - https://github.com/openfaas/workshop/blob/master/lab7.md
