### ISSUE TITLE
[Feature Request] Expose Requested Content-Type In /system/functions

### ISSUE THREAD

**Issue by Miserlou** [openfaas/faas#1333]
Different functions in the OpenFaaS function store behave differently when receiving content with different `Content-Type` headers. Some expect `text/plain` and return null otherwise, some expect `application/json` and return null otherwise, and some return the same thing no matter what.

There is no way to know apriori which the function expects, making it difficult to build complex pipelines without manually knowing and preparing requests based on what each function expects.

It would be much better if I could use the `/system/functions` endpoint to see which it expects so that pipelines could be built programatically.

Even better would be if we could could just not have to worry about this at all, and simply mandate that all functions speak `application/json` in and out.

**Comment by jonatasbaldin** [comment]
My thoughts:

- What if a function accepts different `Content-Type`s depending on the user input? Maybe a very edge case tho
- I think this is more related to the function documentation than the infrastructure, which should not care about which `Content-Type` is being sent or which one the function accepts
- Forcing `application/json` also disables other use cases, like sending binary data

What do you think?

**Comment by Miserlou** [comment]
I agree about not wanting to limit the use cases (ex, for binary data), so I think that would be an argument to have this exposed in a manifest (maybe with `application/json` or `text/plain` as an assumed default by convention).

**Comment by alexellis** [comment]
Duplicate of https://github.com/openfaas/faas/issues/1337

**Comment by alexellis** [comment]
@Miserlou thank you for your suggestion, it was already being tracked on Trello, but I've created an issue for it too.
