### ISSUE TITLE
[Support] Can invocations be retried?

### ISSUE THREAD

**Issue by ontehfritz** [openfaas/faas#1335]
This is more specific to functions that have been triggered from events (e.g. kafka events), it would be great to specify retries and back-off strategies, and to further the feature, be able to retry functions with the payload that failed; after retries have been exhausted, manually.  

This is important in situations where you received the event, but processing failed inside of the function being executed because a resource it was posting to was unavailable for multiple reasons, rate limited, intermittent down time etc etc ..., it gets really tricky to resubmit the event itself, because the amount of actors on the event can be N, and would re-trigger, even if you do your best to make event processing idempotent, it makes things complicated. 

It would be best to just retry the function with the payload it received from the event. This would also be cool, if there was a bug or change of logic in the same function and needed to redeploy and run again.

**Comment by Miserlou** [comment]
Big +1, this would be a great feature. Would this be a new header? `X-Retry-Strategy: Exponential`, `X-Num-Retries: 5`, etc?

**Comment by alexellis** [comment]
/set title: [Support] Can invocations be retried?

**Comment by alexellis** [comment]
Thanks for logging your suggestion.

Retries for invocations can be achieved through a "retry budget" with Linkerd, or through your choice of ingress controller such as Heptio Contour.

As regards the event-connector pattern, let's move the discussion over to the conenctor-sdk repo: https://github.com/openfaas-incubator/connector-sdk/issues/28

Thanks again and feel free to search past issues or to ask on Slack before logging additional issues, we find this helps keep the signal to noise ratio lower.

Alex

**Comment by alexellis** [comment]
Please also make use of the issue template for any further issues 👍
