### ISSUE TITLE
Support request for Prometheus

### ISSUE THREAD

**Issue by ziggekatten** [openfaas/faas#1340]
## My actions before raising this issue
- [X ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X ] Searched [past issues](/issues)

I have a Docker Swarm cluster with an existing Prometheus/Alert Manager/Grafana, and would like to use this. Howerver, there is no way to specify a sub URL, as my Prometheus has its API on a different path (reasons beeing som Reverse Proxy stuff).

The gateway have only two things defined related to Prometheus, host and port

How do i get the Gateway to use endpoint: http://prometheus:9090/monitoring/prometheus/api/v1"?

## Current Behaviour

Gateway get an 404 calling API on Prometheus.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 

* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Can you explain the use-case? I've personally never had this need and don't fully understand the request.

**Comment by ziggekatten** [comment]
The use case is quite simple. We would like to use existing Prometheus/AlrtManager, and since we have everything behind a Traefik reverse proxy and uses URI's instead of domains(everything under paths except TCP proxies) we have to run Prometheus with an "--web.external-url" that matches the path prefix in Traefik, thus causing the /api/v1 to be at path /monitoring/prometheus/apiv1

**Comment by alexellis** [comment]
Would you be willing to do all the work and testing for this feature and then to maintain it on an ongoing basis?

**Comment by ziggekatten** [comment]
Dang it, I was hopin' that I just haved missed some existing parameter:-)

**Comment by alexellis** [comment]
I wonder if you could access Prometheus the same way we do?

What if you deployed it a second time?

**Comment by ziggekatten** [comment]
I’m so stupid...all I really need is a small nginx service that proxy from / on port 9090 to my existing prometheus.... I’ll give that a try tomorrow.

**Comment by ziggekatten** [comment]
Allright, added a nginx, and now the gateway can communicate as it should with Prometheus. Attach the nginx below if someone else end up in this scenario
`daemon off;
worker_processes 1;

error_log /dev/stdout;


events {
    worker_connections 1024;
}

http {
    include              /etc/nginx/mime.types;
    default_type         application/octet-stream;
    sendfile             on;
    tcp_nopush           on;
    keepalive_timeout    65;
    gzip                 on;
    server_tokens        off;
    client_max_body_size 10M;

    server {
        listen      9090;
        access_log  on;
        access_log /dev/stdout;
        location / {
            proxy_pass http://monitoring_prometheus:9090/monitoring/prometheus/;
            access_log /dev/stdout;
        }
    }
}
`
Now I have one issue left, but that will be  a separate topic

**Comment by ziggekatten** [comment]
This can be closed. Works like a charm

**Comment by rgee0** [comment]
Derek close
