### ISSUE TITLE
Update basic-auth plugin to use latest faas-provider

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1355]
##  Expected Behaviour

Update the gateway and basic-auth plugin to use latest faas-provider version

### For `/gateway/`

* Edit `Gopkg.toml`

* Use the latest release from faas-provider - https://github.com/openfaas/faas-provider/releases

* Run `dev ensure`

### For `/gateway/`

* Edit `Gopkg.toml`

* Use the latest release from faas-provider - https://github.com/openfaas/faas-provider/releases

* Run `dev ensure`

### For [`auth/basic-auth`](https://github.com/openfaas/faas/tree/master/auth/basic-auth)

* Edit `Gopkg.toml`

* Use the latest release from faas-provider - https://github.com/openfaas/faas-provider/releases

* Run `dev ensure`

## Merging criteria

* Sign off the commits with `git commit -s`

* Run a local build with `make` (you'll need Docker installed for this)

* Create a Pull Request and fill out the paper-work quoting this issue

**Comment by mistikel** [comment]
I would like to take this

**Comment by alexellis** [comment]
Sure, how long do you think it will take you?

**Comment by alexellis** [comment]
More on dep -> https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#i-need-to-add-a-dependency

**Comment by Karthik-13** [comment]
@alexellis Could you please review and provide feedback on PR?
