### ISSUE TITLE
Multi-arch image script is incorrectly detecting images on Docker Hub

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1360]
Multi-arch image script is incorrectly detecting images on Docker Hub

## Expected Behaviour

The script on this line, should determine whether an image exists on the Docker Hub before attempting to build.

https://github.com/openfaas/faas/blob/master/contrib/publish-arm.sh#L51

## Current Behaviour

It returns "true" as in the image exists even for those which do not.

## Possible Solution

See if the API changed, try the line in isolation, fix and then send a PR.

**Comment by Waterdrips** [comment]
I can take a look at this

**Comment by alexellis** [comment]
Testing the script needs to be done on Linux or RPi, perhaps `docker run -ti ubuntu` would be suitable for debugging?

Perhaps the issue is that `Not found` is now lowercase in the Docker HUB API? They recently pushed changes to enable robot accounts.

For a tag that doesn't exist: 0.19.0

```
export TAG=0.19.0
export ARM_VERSION=armhf
TAG_PRESENT=$(curl -s "https://hub.docker.com/v2/repositories/${IMAGE}/tags/${TAG}-${ARM_VERSION}/" | grep -Po '"detail": *"[^"]*"' | grep -o 'Not found')
echo $TAG_PRESENT


export TAG=0.19.0
export ARM_VERSION=armhf
TAG_PRESENT=$(curl -s "https://hub.docker.com/v2/repositories/${IMAGE}/tags/${TAG}-${ARM_VERSION}/" | grep -o 'not found')
echo $TAG_PRESENT
not found
```

For a tag that does from: https://hub.docker.com/r/openfaas/gateway/tags

I am also seeing 2x `//` symbols, which seems to be causing an issue

```
export TAG=0.17.0
export ARM_VERSION=armhf
TAG_PRESENT=$(curl -s "https://hub.docker.com/v2/repositories/${IMAGE}/tags/${TAG}-${ARM_VERSION}/" | grep -o 'not found')
echo $TAG_PRESENT
not found
echo "https://hub.docker.com/v2/repositories/${IMAGE}tags/${TAG}-${ARM_VERSION}/" 
https://hub.docker.com/v2/repositories//tags/0.17.0-armhf/
```

Removing that slash:

```
TAG_PRESENT=$(curl -s "https://hub.docker.com/v2/repositories/${IMAGE}tags/${TAG}-${ARM_VERSION}/" | grep -o 'not found')
echo $TAG_PRESENT
not found
echo "https://hub.docker.com/v2/repositories/${IMAGE}tags/${TAG}-${ARM_VERSION}/" 
https://hub.docker.com/v2/repositories/tags/0.17.0-armhf/

```

**Comment by alexellis** [comment]
Thanks @Waterdrips, I'll leave it with you.

**Comment by alexellis** [comment]
In the future, please add to your commit message or PR the text "Closes: #X"
