### ISSUE TITLE
Question: How to auto-trigger rebuilding a function

### ISSUE THREAD

**Issue by ozburo** [openfaas/faas#1388]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

How can I trigger a function to be rebuilt (i.e. pulling all updated dependencies/requirements) periodically or by some trigger?

## Expected Behaviour

I've read about about the function's health check and the `/tmp/.lock` file. If I were to delete this file would this trigger Openfaas to rebuild the function completely or just spin up another instance? Is there some environment variable available that will dictate the behavior on function failure?

Imagine having a Python function with a `requirements.txt` and those dependencies are outdated and need to be repulled, how can we do this without having to redeploy the function yourself?

**Comment by alexellis** [comment]
Hi, that would be via your CI/CD process. 

Feel free to seek out free community support on Slack, or to get in touch with sales@openfaas.com if you need more hands-on commercial help.

https://docs.openfaas.com/reference/cicd/intro/

Alex

**Comment by ozburo** [comment]
Ah thanks, that's how the cool kids do it 👍
