### ISSUE TITLE
Open Faas using google container registry

### ISSUE THREAD

**Issue by mingsterism** [openfaas/faas#1390]
Hi, 
are we able to use Google Container Registry instead of Docker Hub for the registry? 

Regards, 
Ming

**Comment by LucasRoesler** [comment]
yes, we do this regularly at my work. 

If your registry is public, then it will work without any additional configuration.  

If your registry is not public, then if you are using kubernetes, you need to add a ImagePullSecret to your cluster and use that with your functions _or_ add it to the ServiceAccount used by OpenFaaS.  You can find some documentation about this process in the docs here https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes

**Comment by mingsterism** [comment]
thanks for the quick response. 
Alright, will give that a try and see if there's any issues.

**Comment by alexellis** [comment]
Please use Slack for technical support going forward. Thank you for your interest in the project.
