### ISSUE TITLE
Shouldn't I run openfass on Windows?

### ISSUE THREAD

**Issue by YeoHoonYun** [openfaas/faas#1396]
PS C:\Users\cjswo> .\faas-cli.exe build -f .\uptime.yml
[0] > Building uptime.
Clearing temporary build folder: ./build/uptime/
Preparing ./uptime/ ./build/uptime//function
Building: uptime:latest with python3 template. Please wait..
Sending build context to Docker daemon 9.216 kB
Step 1/29 : FROM openfaas/classic-watchdog:0.18.1 as watchdog
Error parsing reference: "openfaas/classic-watchdog:0.18.1 as watchdog" is not a valid repository/tag: invalid reference format

Hi, I am a programmer interested in serverless in Korea. Can I check the error "openfaas / classic-watchdog: 0.18.1 as watchdog" while installing with Docker on Windows 10 Pro?

Thank you.

**Comment by martindekov** [comment]
Hello @YeoHoonYun , thank you for using the project

This error is strange as the tag exists https://hub.docker.com/r/openfaas/classic-watchdog/tags can you provide more detailed steps to reproduce?

**Comment by YeoHoonYun** [comment]
@martindekov Thank you for your reply. The version didn't build on my computer, so I had a problem. Other versions are available. It won't be a cli.

**Comment by YeoHoonYun** [comment]
> Hello @YeoHoonYun , thank you for using the project
> 
> This error is strange as the tag exists https://hub.docker.com/r/openfaas/classic-watchdog/tags can you provide more detailed steps to reproduce?

Found deprecated go-style flags in command, translating to new format:
  C:\windows\system32\faas-cli.exe version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  0ab4012784510381e2b90c031ede3d77197b10b1
 version: 0.11.0
PS C:\Users\cjswo\openfaas_test> docker -v
Docker version 17.03.1-ce-rc1, build 3476dbf

![1](https://user-images.githubusercontent.com/45550361/70384039-d7e66200-19bb-11ea-9f13-c66092383bdf.PNG)

![2](https://user-images.githubusercontent.com/45550361/70384043-de74d980-19bb-11ea-9610-89ee6d8172d3.PNG)

Step 1/24 : FROM openfaas/classic-watchdog:0.18.1 as watchdog
Error parsing reference: "openfaas/classic-watchdog:0.18.1 as watchdog" is not a valid repository/tag: invalid reference format
2019/12/08 13:11:57 ERROR - Could not execute command: [docker build -t callme:latest .]
PS C:\Users\cjswo\openfaas_test>

Do you have any errors in Docker syntax?

**Comment by alexellis** [comment]
Hi, thank you for your interest.

You should be using Git Bash for `faas-cli` as directed in the workshop and documentation.

https://github.com/openfaas/workshop

I am going to ask you not to delete the issue template, because in doing so you've made it harder for us to help you, one of the key pieces of information given in the template is the version of Docker.

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

I would suggest you fill out the whole template with all the information asked for, but in this instance there is no issue with OpenFaaS so please use Slack instead.

Alex
