### ISSUE TITLE
Support using a custom NATS Streaming channel and queue group.

### ISSUE THREAD

**Issue by bmcstdio** [openfaas/faas#1399]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

OpenFaaS should allow for customising the NATS Streaming channel and queue group used for asynchronous invocations instead of using the hardcoded `faas-request` channel and `faas` queue group. This would allow, for example, to have different deployments of OpenFaaS (in the same or in separate Kubernetes clusters) being serviced by the same NATS Streaming cluster.

## Current Behaviour

OpenFaaS and the NATS queue worker use the hardcoded `faas-request` channel and `faas` queue group.

## Possible Solution

Allow for overriding the name of the channel via a `faas_nats_topic` environment variable.

## Steps to Reproduce (for bugs)

1. N/A
2. N/A
3. N/A
4. N/A

## Context

We will be using a single NATS Streaming cluster to service three different OpenFaaS deployments (across three different Kubernetes clusters), and we need to make sure that invocations of functions in cluster _K1_ do not end up being processed by queue workers in cluster _K2_ or _K3_.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

N/A

* Docker version `docker version` (e.g. Docker 17.0.05 ):

N/A

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):

N/A

* Code example or link to GitHub repo or gist to reproduce problem:

N/A

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

N/A

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
> We will be using a single NATS Streaming cluster to service three different OpenFaaS deployments (across three different Kubernetes clusters), and we need to make sure that invocations of functions in cluster K1 do not end up being processed by queue workers in cluster K2 or K3.

Thank you for giving this context, getting feedback from end-users is hard, so this helps a lot. Please keep the habit.
