### ISSUE TITLE
simple "hello world" project: "exec format error" - Node + PHP [armhf]

### ISSUE THREAD

**Issue by lippoliv** [openfaas/faas#1404]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

It should be possible to deploy custom functions to an OpenFaas running on an armhf like Raspberry PI 4.

## Current Behaviour

OpenFaas is running. Public functions (e.g. certinfo) do work.
Deploying custom functions with `php7` or `node-armhf` doesnt work.

    pi@openfaas-01:~ $ sudo kubectl logs deploy/hello-node-world -n openfaas-fn
    standard_init_linux.go:211: exec user process caused "exec format error"

## Steps to Reproduce (for bugs)

1. Setup standard OpenFaas on RPI4
2. Create a custom function
3. Build + Push to private registry
4. Add registry credentials to `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl`
5. Add the registry as "unsafe" (http endpoint) to `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` (not sure if relevant)
6. Deploy the function to your OpenFaas

## Context

I'am not  new to Docker. But I'am new to OpenFaas / Faas at all.

First I tried build + deploy from my WIN10 laptop, but now I do build on GitLab CI directly so the container is created in Linux. Thought that may help, but it didn't.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  0ab4012784510381e2b90c031ede3d77197b10b1
 version: 0.11.0

Gateway
 uri:     http://openfaas-01:31112
 version: dev
 sha:     672b7c48b7fcefbc974c69abab06555ab21e9db5
 commit:  Add tiers


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       dev
 sha:           b4b112e1342979590eadd2d4471530f45734a46e
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Kubernetes, setup through `k3sup`.

* Operating System and version (e.g. Linux, Windows, MacOS):

Laptop: WIN10  
GitLab: Debian Linux  
Raspberry: Debian 10

* Code example or link to GitHub repo or gist to reproduce problem:

Just run `faas-cli new my-function --lang php7` or `faas-cli new my-function --lang node-armhf`

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

```
pi@openfaas-01:~ $ echo test this | faas invoke hello-node-world -g 127.0.0.1:31112

Post http://127.0.0.1:31112/function/hello-node-world: EOF
Cannot connect to OpenFaaS on URL: http://127.0.0.1:31112
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi the PHP7 image is not designed for armhf and the node-armhf template must be used to build on the device. I'd suggest making yourself familiar with the documentation and feel free to ask for technical support on Slack. 

Thanks for your interest.

**Comment by alexellis** [comment]
You may also find this note useful https://www.openfaas.com/deployment/kubernetes/

**Comment by lippoliv** [comment]
Thanks @alexellis. With your Information I figured out how to update my CI to build on armhf (I had a spare RPI 3 which now acts as as GitLab runner) and now I am able to deploy custom functions. Very nice. Thanks for your work.

I really thought PHP7 should work on armhf for this PR https://github.com/openfaas/templates/pull/148

Thanks for the fast reply, you helped a lot. If I am stable with OpenFaas, maybe I will commit some templates. <3

**Comment by alexellis** [comment]
You're welcome.

Please consider sponsoring my time to support the project through GitHub. 

https://insiders.openfaas.io/

You can also join slack and discuss arm further in the dedicated channel.
