### ISSUE TITLE
Namespace selector does not update the function list 

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#1408]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

If I  deploy functions to the default namespace and to an additional namespace, the namespace selector in the gateway UI does not appear to work.  The API returns the expected result with a new function list, but he UI does not update to reflect this

In this screenshot you can see the latest API response but with the wrong function list rendered
![image](https://user-images.githubusercontent.com/891889/70988190-a65b4e00-20c1-11ea-95e4-ce984b3c887d.png)

## Expected Behaviour

The function list should change to show the functions from the selected namespace

## Current Behaviour

Found while walking through a demo of multinamespace support

## Steps to Reproduce (for bugs)

1. Deploy on kubernetes with the latest helm chart `openfaas-5.3.8`, make sure to set `clusterRole` to true
2. Create an annotate an extra namespace
    ```sh
    kubectl create ns dev-fn
    kubectl annotate ns dev-fn openfaas="true"
   ```
2. use the cli to deploy left pad to an extra namespace, `faas-cli store deploy Left-Pad -n dev-fn`
3. also deploy a function to the default namespace `faas-cli store deploy NodeInfo`
3. Open the gateway ui
5. use the namespace selector to change to `dev-fn`
6. observer that the function list does not change, it should still just show `NodeInfo`

## Context

Relates to #1379

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
faas-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
osx

**Comment by alexellis** [comment]
I also ran into this issue.

**Comment by alexellis** [comment]
Ref: https://github.com/openfaas/faas-netes/issues/511
