### ISSUE TITLE
Functions scaled to zero during execution

### ISSUE THREAD

**Issue by Dread1982** [openfaas/faas#1410]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

If scaling-to-zero is enabled and a function is invoked after being scaled to zero for some time, it can happen that during execution of the function, it is scaled back down again, resulting in a 502 (bad gateway) error.

## Expected Behaviour

Scaling to zero should never happen while a function is currently running.

## Current Behaviour

The faasIdler checks in a defined interval if it can scale functions to zero. As far as I understand, it uses metrics from prometheus to check for the latest invocation of a function and scales it down if the defined inactivity duration is exceeded. However, it seems as if the metrics are only updated **after** an execution, which can lead to a downscaling if during the function execution the faasIdler does its regular check. See following example with logs.

Current default values for faasIdler are:
inactivityDuration: 15m
reconcileInterval: 1m

So each minute faasIdler will check if it can scale a function down to zero which was inactive for at least 15m. 

Let's say some function was indeed inactive for a period longer than these 15m, so it is was correctly scaled down to zero some time in the past. At 14:22:18 (see following gateway logs) the function is invoked again so a scaling up to one replica is triggered. After 5 sec the scale up was successful and the function is executed (it needs about 30sec to finish). However, at 14:22:36 the faasIdler does its every minute check and as the last invocation (before the currently running one) was far in the past, it triggers again a scale to zero. As a result the running function fails seconds later with a 502 error.

```bash
2019/12/18 14:22:18 [Scale 0] function=mandant1-print-3 0 => 1 requested

...

2019/12/18 14:22:23 [Scale] function=mandant1-print-3 0 => 1 successful - 5.503548 seconds

...

2019/12/18 14:22:36 Forwarded [POST] to /system/scale-function/mandant1-print-3 - [202] - 0.010112 seconds

...

2019/12/18 14:22:39 error with upstream request to: , Post http://mandant1-print-3.openfaas-fn.svc.cluster.local:8080: dial tcp 10.100.135.123:8080: connect: connection refused
2019/12/18 14:22:39 Forwarded [POST] to /function/mandant1-print-3 - [502] - 15.500122 seconds
```

## Possible Solution

Without knowing enough about the concrete implementation possible solutions could be:
1) invocation information should be stored in prometheus at the start of a function, so faasIdler does not scale it down while it is still running
2) faasIdler or gateway should check if a function is currently running before scaling it down

## Steps to Reproduce (for bugs)

1. Install Openfaas, e.g. in local Minikube and enable faasIdler (`dryRun: false`)
2. Create a function (which should have a reasonable execution time, e.g. use a `sleep(20s)`) with scale-to-zero enabled (set label `com.openfaas.scale.zero: true`) and wait till the faasIdler has scaled it down to zero
3. Check the faasIdler logs to find out when the every minute check roughly happens (e.g. always at xx:xx:36)
4. Trigger the function shortly before the next faasIdler check, so it should still be running when the check happens
5. Function will be scaled down and fail

## Context

Scaling to zero is a great feature and one we really would like to use in production, especially as some of our functions are only invoked a few times a day. However, with the current behaviour we experience regularly failing functions. 

## Your Environment

For reproduction we used the following env, but the bug originally appeared with slightly older versions of Openfaas running in GKE.
- Minikube v1.5.2 with Kubernetes v1.15.4 on Windows10 (hyperv)
	- docker (in minikube vm) 18.09.9
- Openfaas installed via Helm chart version 5.3.10
	- openfaas/gateway:0.18.6
	- openfaas/faas-netes:0.9.15
	- openfaas/faas-idler:0.2.1

**Comment by alexellis** [comment]
Please can you move this to https://github.com/openfaas-incubator/faas-idler ?

Thanks for your interest and report.

**Comment by stefanprodan** [comment]
@alexellis GitHub allows you to move an issue to a different repo

**Comment by alexellis** [comment]
@stefanprodan I'm well aware of that, but what you may have missed is that the faas-idler is in a different organisation, something that's not supported yet. 🤔  The only option for org to org transfers is what I've asked for.
