### ISSUE TITLE
Openfaas inside docker container

### ISSUE THREAD

**Issue by kndrvt** [openfaas/faas#1414]
I need to deploy distributed serverless computing system using containernet. I want to use openfaas inside docker container, but have read that docker-in-docker is wrong approach. So I'm attempting to launch ```docker run -v /var/run/docker.sock:/var/run/docker.sock```([as is written here](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci)) with different ubuntu images trying to deploy openfaas. But it doesn't work. 
It seems that I can't deploy such system on laptop. So  I need your help. Do you have ideas how it may be done?

**Comment by alexellis** [comment]
Thanks for your interest in the project. Unfortunately you haven't provided any of the information we request and this doesn't look like an issue with OpenFaaS, but a technical support request.

Please feel free to ask for technical support on Slack but bear in mind that most people are away for the holidays.

In future please give the use-case you're trying to solve for context and fill out the entire issue  template.

**Comment by alexellis** [comment]
See also: https://docs.openfaas.com/deployment/kubernetes/
