### ISSUE TITLE
Http_Content_Length can't be negative

### ISSUE THREAD

**Issue by themoah** [openfaas/faas#1422]
Whenever there is a body in request env variable shows `Http_Content_Length=-1` (if empty shows 0).

## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
I was expecting to see the length of body, especially for text (not binary)

## Current Behaviour
Always shows -1

## Possible Solution

Probably change https://github.com/openfaas/faas/blob/master/watchdog/handler.go#L238
to `%s` (though it's int64 type). I guess, I can submit bug fix bit later.

## Steps to Reproduce (for bugs)
1. `faas-cli deploy --name env --fprocess="env" --image="functions/alpine:latest"`
2. (if needed) port-forward your cli
3. `curl 'http://127.0.0.1:31112/function/env/' -X POST -d "" | grep -I length`  And see 0 (or `echo "" | faas-cli invoke env` 
4.  `curl 'http://127.0.0.1:31112/function/env/' -X POST -d "Alice " | grep -I length ` And see -1

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  0ab4012784510381e2b90c031ede3d77197b10b1
 version: 0.11.0

Gateway
 uri:     http://127.0.0.1:31112
 version: 0.18.7
 sha:     59b7839236098820e73ed25301258b722c3d33e4
 commit:  Change how and when we fetch and parse namespace info


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.9.15
 sha:           41c33f9f7c29e8276bd01387f78d6f0cff847890
Your faas-cli version (0.11.0) may be out of date. Version: 0.11.3 is now available on GitHub.
```
* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? k8s on DO.

* Operating System and version (e.g. Linux, Windows, MacOS): Mac

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide]

it's in classic-watchdog. Afaik everything goes toward of-watchdog and thus issue should be fixed there. 

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi this is as expected, it's set to -1 whenever the content is being sent by the client in chunked mode.

What is the actual issue you appear to be having? This appears to be rather abstract.

**Comment by themoah** [comment]
@alexellis so it’s a misleading, I’d be rather expecting for it to have a real value. 
Thus, a developer can rely on that. Anyway, for a developer watchdog is a ‘black box’.

**Comment by alexellis** [comment]
I asked before, but I'll ask again.

What are you trying to do? What's the problem you're trying to solve?

**Comment by alexellis** [comment]
I would like to help you solve whatever issue you are facing, rather than getting into the details of the watchdog. You're seeing correct behaviour. The gateway doesn't buffer requests in memory, but passes them on setting the header "Content-Type: chunked", if you see Content-Type -1 then you need to ignore the content length, since it is unknown.

To help disambiguate I've updated the README for the watchdog and added a new env `Http_Transfer_Encoding`, if it's set then you can be sure you should ignore the content length.

If you let me know what you're specifically trying to do, then maybe I can help you?
