### ISSUE TITLE
Unable to login after successful install

### ISSUE THREAD

**Issue by flaviobarros** [openfaas/faas#1427]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I'm starting with openfaas. Installed docker on my machine and successfully installed openfaas in my machine. Unfortunately I am unable to login with the credentials from my terminal.

## Expected Behaviour

I would like to login with my credentials.

## Current Behaviour

Unable to login.

## Steps to Reproduce (for bugs)

1. install docker
2. initialize docker swarm
3. run openfaas install script
4. try login

## Context

Just trying openfaas

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.11.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 0.18.0

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Linux Mint Tina

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by flaviobarros** [comment]
For some reason it just worked after some time! I thought that was automatic, but took some time.

**Comment by alexellis** [comment]
No worries, please join Slack for technical support. We just use GitHub for issues in the code and for planning features.
