### ISSUE TITLE
Secret mounted file - stricter permissions 

### ISSUE THREAD

**Issue by arthurlogilab** [openfaas/faas#1429]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

A library that we use expects configuration files with secrets in them to have permissions '600' or '400'. 

It would be nice for the default permissions for secrets exposed to be that, or make them configurable. 

## Current Behaviour

The secrets exposed by faas have '640' on a readonly filesystem, so we can't even chmod them before using the in the handler. 

The workaround is to copy them and chmod them at the beginning of the handler. Which is not the right way to do it. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```
CLI:
 commit:  25cada08609e00bed526790a6bdd19e49ca9aa63
 version: 0.8.14
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu

**Comment by alexellis** [comment]
Hi 👋 thanks for your interest in the project. Does "a library" constitute ssh? Can you give concrete examples please, we should have repro instructions.

Alex

cc @LucasRoesler

**Comment by arthurlogilab** [comment]
We're using https://pypi.org/project/cwclientlib/ 

For a extract let me try, in handler : 

```python
import os
from cwclientlib import cwproxy_for
    
def handle(req):
    os.environ['CWCLCONF'] = '/var/openfaas/secrets/cwclient-conf'
    client = cwproxy_for('example')
```

I know that psql from postgresql has similar restrictions when reading `.pgpass`

**Comment by LucasRoesler** [comment]
Changing this behavior will need to be implemented in each provider, e.g. in faas-netes, we would to update this line of code https://github.com/openfaas/faas-netes/blob/0fe88f3a672c45335e644854f44811a1db287d69/k8s/secrets.go#L226, setting the `DefaultMode` property
> // Mode bits to use on created files by default. Must be a value between 0 and 0777

It seems reasonable that secrets are read only, in general

**Comment by alexellis** [comment]
Seems reasonable. We haven't had any other users report this as of yet.

Thanks for documenting the work-around and let's gauge the interest-level?

**Comment by alexellis** [comment]
No further interest has been expressed. Locking
