### ISSUE TITLE
Healthcheck of customized built-in function (Inception) when deploying to kubernetes

### ISSUE THREAD

**Issue by johnsusek** [openfaas/faas#1438]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

When customizing the Dockerfile of a built-in function like Inception, then deploying to kubernetes, it should pass health checks.

## Current Behaviour

When customizing a Dockerfile of a built-in function, health checks stop working because it can't find the /_/health endpoint.

## Possible Solution

This is what I've tried so far:

Add `HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1` to my Dockerfile

Add 
```
    annotations:
      com.openfaas.health.http.path: "/healthz"
      com.openfaas.health.http.initialDelay: "30s"
```

to my stack.yml

In the former case, I receive the original error. In the latter case, the healthcheck fails because it cannot find the /healthz endpoint

## Steps to Reproduce (for bugs)

Deploy a dockerfile function with these settings to kubernetes:

stack.yml
```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  inception:
    lang: dockerfile
    handler: ./function
    image: mydockername/inception
```

Dockerfile
```
FROM tensorflow/tensorflow:latest

RUN apt-get update -qy \
 && apt-get install -qy \
       python3-pip time
RUN curl -sSL https://github.com/openfaas/faas/releases/download/0.7.0/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog

WORKDIR /root/

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

ENV TF_CPP_MIN_LOG_LEVEL=3
COPY *.py ./

RUN python3 ./pre_download.py

COPY *.txt ./


ENV write_debug="true"
ENV fprocess="/usr/bin/time -v python3 index.py"

CMD ["fwatchdog"]
```

## Context

I'm trying to deploy a version of "Inception" that adds resource usage stats to the response (see how I've added `/usr/bin/time -v ` to the beginning of fprocess. In my code that parses the response I use this to e.g. determine to amount of memory used by the function.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  49d9f888a6e06b4e2cfdf542cfbf6dde2ebed7d7
 version: 0.11.6

Gateway
 uri:     http://138.197.55.18:8080
 version: 0.18.7
 sha:     59b7839236098820e73ed25301258b722c3d33e4
 commit:  Change how and when we fetch and parse namespace info


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.9.15 
 sha:           41c33f9f7c29e8276bd01387f78d6f0cff847890
Your faas-cli version (0.11.6) may be out of date. Version: 0.11.7 is now available on GitHub.
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 

* Code example or link to GitHub repo or gist to reproduce problem:
See above

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

Readiness probe failed: Get http://10.244.1.74:8080/_/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by johnsusek** [comment]
Log output from `faas-cli logs inception`:

```
2020-01-28T17:10:41Z 2020/01/28 17:10:41 Forking fprocess.
2020-01-28T17:10:41Z 2020/01/28 17:10:41 Query
2020-01-28T17:10:41Z 2020/01/28 17:10:41 Path  /_/health
```

**Comment by alexellis** [comment]
I am not sure why you are seeing that error as the watchdog provides the endpoint, not the underlying code.

Have you got sufficient resources in the cluster?

What watchdog version is being used?

**Comment by alexellis** [comment]
I can confirm that using a recent version (the one you mentioned is months old), the endpoint is available:

```
curl localhost:8888/_/health -I

HTTP/1.1 200 OK
Date: Tue, 07 Jul 2020 08:33:49 GMT
Content-Length: 2
Content-Type: text/plain; charset=utf-8
```

I've updated the main image in the store and so I'll close this out for you.

Alex

**Comment by alexellis** [comment]
/set title: Support issue for old inception image
