### ISSUE TITLE
Research item: container security features

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#144]
## Expected Behaviour

Containers offer more security features to the end-user

Here are some ideas (please add below)

* [read-only](https://www.projectatomic.io/blog/2015/12/making-docker-images-write-only-in-production/) root FS
* drop all capabilities
* sec comp / se-linux profiles

How much of this is supported by Swarm / K8s?
What is built into the image definition vs a runtime parameter?

**Comment by LucasRoesler** [comment]
Couple of questions about how this is used:

1. What the practical use case where a developer explicitly opts into a read-only fs or would it be opt-out to a non-root fs?
2. With the above question in mind, do we see the openfaas cluster admin having an option to enforce read-only root functions?
3. If the cluster admin can control this, does it simply override the setting and return a warning if the function is not labelled as supporting a root-only fs?  In this case, the function would just break as soon as it tries to write to the fs.  Or, would it just outright reject it until it is labeled correctly?
4. Do we want to set a specific convention about having a writable folder, say `/opt/sandbox`?  Perhaps it is an ENV var that openfaas can pass in, `FAAS_WRITE_DIR`?

I will think a little more and come up with some more questions.

**Comment by alexellis** [comment]
Please comment on #590

**Comment by alexellis** [comment]
We implemented read-only FS. AWS Lambda also has this feature now.
