### ISSUE TITLE
Move all builds to use license-check's docker image instead of curl to download it

### ISSUE THREAD

**Issue by hasheddan** [openfaas/faas#1440]
This is a meta tracking issue to implement usage of the `teamserverless/license-check` Docker image across all repositories in `openfaas` and openfass-incubator` as demonstrated [here](https://github.com/openfaas/faas-netes/pull/591/files#diff-3254677a7917c6c01f55212f86c57fbf). Links to PR's in each repository will be added below as they are opened.

## openfaas repos

- [x] [faas-netes](https://github.com/openfaas/faas-netes): https://github.com/openfaas/faas-netes/pull/591
- [x] [faas](https://github.com/openfaas/faas): #1441 
- [x] [faas-swarm](https://github.com/openfaas/faas-swarm): https://github.com/openfaas/faas-swarm/pull/68

## openfaas-incubator repos

- [x] [ingress-operator](https://github.com/openfaas-incubator/ingress-operator): https://github.com/openfaas-incubator/ingress-operator/pull/22
- [x] [ofc-bootstrap](https://github.com/openfaas-incubator/ofc-bootstrap): https://github.com/openfaas-incubator/ofc-bootstrap/pull/186
- [x] [faas-memory](https://github.com/openfaas-incubator/faas-memory): https://github.com/openfaas-incubator/faas-memory/pull/8
- [x] [faas-federation](https://github.com/openfaas-incubator/faas-federation): https://github.com/openfaas-incubator/faas-federation/pull/9

**Comment by hasheddan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
How are we going with this one? Are there only 7 repos that use the license check at present?

**Comment by hasheddan** [comment]
@alexellis I could only identify the 7 listed above as using license-check. I have PR's linked for each, and I believe [ofc-bootstrap](https://github.com/openfaas-incubator/ofc-bootstrap/pull/186) and [faas-memory](https://github.com/openfaas-incubator/faas-memory/pull/8) are still awaiting merge :)

**Comment by alexellis** [comment]
Thank you for your contribution, you'll find a place on https://kenfdev.o6s.io/github-stats-page#/ and the openfaas.com homepage :)
