### ISSUE TITLE
Update projects in this repository to use Go 1.13

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1442]
## Task

Update projects in this repository to use Go 1.13

i.e. https://github.com/openfaas/faas/search?l=Dockerfile&q=%22%3A1.12%22

https://github.com/openfaas/faas/blob/master/.travis.yml#L5

https://github.com/openfaas/faas/search?l=Dockerfile&q=%22%3A1.11%22

Note: do not search and replace blindly, there are instances of `alpine:3.11` which are completely unrelated. This task requires due care and attention.

**Comment by hasheddan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Please don't:

* switch to Go modules
* delete the vendor directory

Thank you :-)
