### ISSUE TITLE
Clarify that async only works with POST in documentation

### ISSUE THREAD

**Issue by markus-seidl** [openfaas/faas#1444]
The documentation https://docs.openfaas.com/reference/async/ states

> Any function can be invoked asynchronously by changing the route on the gateway from /function/<name> to /async-function/<name>. A 202 Accepted message will be issued in response to asynchronous calls.

Which is not exactly true, as the request *must* be a post. Otherwise openfaas will quit with 405. Also the example hides the fact

```
$ curl http://127.0.0.1:8080/async-function/figlet \
  --data "Hi" \
  --header "X-Callback-Url: http://<your-ip>:8888"
```

As `--data` silently inserts a `-X POST`. I think this should be at least mentioned in the documentation.

**Comment by alexellis** [comment]
Hi Marcus, can you explain what problem you were running into?

**Comment by markus-seidl** [comment]
For sure: I've read

> Any function can be invoked asynchronously by changing the route on the gateway from /function/ to /async-function/. A 202 Accepted message will be issued in response to asynchronous calls.

Transformed my get requests by url-replacement and wondered why nothing worked. After investigation I found the 405 and then I experimented with a few methods. Then I found out that it needs "POST".
I think that should somehow in the documentation.

**Comment by alexellis** [comment]
Thanks, I've taken a look and updated the docs.
