### ISSUE TITLE
Padding broken in the UI for the store pop-up

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1450]
## Description 

The padding is broken in the UI for the store pop-up. It would be good to have this more balanced, see the below example:

<img width="720" alt="75097546-d92f3000-55a3-11ea-9780-1bbe80a57370" src="https://user-images.githubusercontent.com/6358735/75097679-86567800-55a5-11ea-8d78-83572cbbf236.png">

**Comment by Waterdrips** [comment]
Is this just the heading padding you are looking to shift

**Comment by alexellis** [comment]
Updated the diagram, but input is welcome if we can tune up anything else.
