### ISSUE TITLE
Question: OpenFaas deploy with gitops Argo integration

### ISSUE THREAD

**Issue by odelucca** [openfaas/faas#1470]
Hey guys, I'm considering move from my current FaaS tool to `OpenSaas` but I have a quick question regarding the deployment pipeline.

Our company has a Gitops infrastructure, using Drone and Argo. Basically Drone handles the deploy pipeline, we have a plugin which deploys a CRD in a git repository and them Argo syncs it with our Kubernetes cluster.

Can I deploy OpenFaas functions by creating the CRD directly? Or the only way to deploy it is by using the `faas-cli`?

If I can deploy creating the CRD, how can I do so? There are any examples?

Thanks :)

**Comment by shyamammu123** [comment]
Are you talking about ArgoCD? If yes, then you can use customconfigManagementPlugins with Openfaas to support it.  You need to follow this link to setup :- https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/

**Comment by alexellis** [comment]
Hi, we don't use GitHub for technical support, professional services or Q&A. Please could you use Slack? I believe there are some customers using ArgoCD and others using FluxCD. @shyamammu123 thanks for commenting.
