### ISSUE TITLE
Ability to detect the Kubernetes namespace in which a function in running

### ISSUE THREAD

**Issue by steve-perkins** [openfaas/faas#1477]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

I am writing a Docker-based OpenFaaS function, which in turn needs to make outbound REST calls to other functions.  I am using the target function name, and namespace, to construct the URI.  I.e.:

`http://[MY-FUNCTION].[OPENFAAS-FN-NAMESPACE].svc.cluster.local:8080`

If the target function were always in the default `openfaas-fn` namespace, then this could effectively be a static hardcoded value.  Unfortunately though, this Kubernetes cluster has multiple OpenFaaS installations, in different namespaces (e.g. `dev-openfaas-fn`, `qa-openfaas-fn`, etc).  So the initial function needs to know its namespace, in order to dynamically construct a URI for other functions in that namespace.

As far as I know, the standard way for code inside of a Kubernetes pod to detect its namespace is to read the `/var/run/secrets/kubernetes.io/serviceaccount/namespace` file on the container's filesystem.  However, this file does not seem to be present in a pod built by `faas-cli up`.

## Expected Behaviour

When an OpenFaaS function of `lang` type `dockerfile` is built using `faas-cli up`, the filesystem of its Docker container should include a file named `/var/run/secrets/kubernetes.io/serviceaccount/namespace`.  This file contains the Kubernetes namespace in which OpenFaaS functions are deployed (e.g. `openfaas-fn`).

## Current Behaviour

This file is NOT present at all in Docker containers build via `faas-cli up`.

## Possible Solution

Either populate this file if possible, or suggest some other workaround for providing a function with knowledge of its Kubernetes namespace (hopefully short of a manual approach, like creating a secret).

## Steps to Reproduce (for bugs)

1. Create an OpenFaaS function of `lang` type `dockerfile`.
2. Include code, which logs the contents of file `/var/run/secrets/kubernetes.io/serviceaccount/namespace`.
3. Deploy the function with `faas-cli up`.
4. Examine logs for the pod, and see that this file does not exist.

## Context

Covered in the overview at top.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):  19.03.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?  Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):  Windows (locally), Linux (remote)

* Code example or link to GitHub repo or gist to reproduce problem:  N/A

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting):  N/A

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi Steve you really need to call functions via the gateway, even internally. Direct invocation is not a supported usecase.

When we use multiple namespaces, we configure them via env-vars at deployment time.

I'm still trying to understand the usecase though. It sounds like you have a solution you'd like to see however can you explain the problem you're trying to solve?

**Comment by steve-perkins** [comment]
By "via the gateway", do you simply mean the external URL?  The address that you would use to call the function from curl, Postman, or whatever?

**Comment by alexellis** [comment]
https://github.com/openfaas/workshop/blob/master/lab4.md#create-workflows

**Comment by steve-perkins** [comment]
Thank you, @alexellis.  If you have multiple OpenFaaS installations on the same Kubernetes cluster (in different namespaces), then will `gateway.openfaas:8080` always resolve to the one used by the caller?

**Comment by alexellis** [comment]
Is there any chance you can answer my question? https://github.com/openfaas/faas/issues/1477#issuecomment-598375753

**Comment by steve-perkins** [comment]
I'm... not sure how to explain the use case any more clearly than the detailed issue description above.

1. I have one OpenFaaS function, which internally calls another one (i.e. the "Call one function from another" subsection of your "Create Workflows" link above.)

2. Using `http://gateway.openfaas:8080/function/my-second-function`, as suggested by that document, does indeed work fine.  Thank you!

3. However, my Kubernetes cluster has multiple OpenFaaS installations.  Each in a separate Kubernetes namespace, representing separate virtual environments (e.g. "dev", "qa", etc).

4. Therefore, I am asking whether `gateway.openfaas:8080/function/my-second-function` will always resolve to the the instance of the function that's in the caller's namespace.

**Comment by alexellis** [comment]
The way we solve this problem is by having an environment variable at deployment time. Would you be willing to try that? I.e. `NAMESPACE` - this can be set in YAML or via faas-cli deploy.

**Comment by steve-perkins** [comment]
I can do that.  However, it raises two questions:

1. For the URL `http://gateway.openfaas:8080/function/my-second-function`. does the `openfaas` part represent the namespace in which the Gateway is running?  If you have multiple OpenFaaS installations, in namespaces `dev-openfaas`, `qa-openfaas`, etc... would this URL be (for example) `http://gateway.dev-openfaas:8080/function/my-second-function` instead?

2. I don't think setting an environment variable in the YAML file would do much good, as that would be little more than hardcoding.  I think you would have to pass it at build time, e.g. `faas-cli up -e NAMESPACE=dev`.  However, do those environment variables get baked into your function's Docker container, in the container registry?  Or does the Gateway or Kubernetes pass them when pods instances are scaled up?  

I'm not clear on whether you would need separate builds, with separate Docker containers pushed to the container registry... or whether you have a single Docker container for your function, and truly make this value dynamic at deploy time.

**Comment by alexellis** [comment]
You can read about how environment variables configured in stack.yml behave in the documentation at https://docs.openfaas.com/

I'm going to close this issue now as it seems to be more of a technical support request than an issue with OpenFaaS and the namespace (which is known at deployment time) can be injected via the function deployment request.

**Comment by alexellis** [comment]
If you need further support or help with your openfaas project, feel free to use Slack.

**Comment by alexellis** [comment]
/set title: Technical support on referencing functions across multiple namespaces
