### ISSUE TITLE
Queue-Driven Jobs

### ISSUE THREAD

**Issue by RichiCoder1** [openfaas/faas#1479]
## My actions before raising this issue
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

The ability create functions that aren't necessarily invoked, but instead constantly reading off some queue or queue-like structure. These functions would scale up and down automatically based on queue length or other factors.

## Current Behaviour

It looks like currently (from what I've read) functions must be invoked in some way. You can accomplish this through Triggers & Connectors, but it'd be nice to be able to have a pull-based model vs pushed based.

## Possible Solution

Some prior art here would be [Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=csharp) as well as [Dapr](https://dapr.io/) when combined with [Keda](keda.sh). Since Keda is now in the CNCF, it could even potentially used to complement OpenFaas's own scaling component.

## Context

The motivation is the typical case of wanting to put work on a queue, and then distribute it.

**Comment by burtonr** [comment]
@RichiCoder1 have you seen the docs on [event source triggers](https://docs.openfaas.com/reference/triggers/#add-your-own-event-source)

We have NATS, Kafka, RabbitMQ, AWS SQS, and others available.

The link you shared to Azure functions is posting an event to a message queue from their storage service. You could do similar things by posting an event to a Kafka stream, or NATS topic and OpenFaaS can trigger a function invocation from that message.

There is also the [cron connector](https://github.com/openfaas-incubator/cron-connector) if you're looking for delayed invocation of a function. If you wanted to, you could have the cron connector periodically call a function that could read from a data source, and in turn, execute a function as designated in that data source.

Serverless functions are by nature a push invocation as they are only active when needed. It's just a matter of how you decide to trigger the function. With OpenFaaS there are a lot of options

**Comment by RichiCoder1** [comment]
> @RichiCoder1 have you seen the docs on event source triggers

>We have NATS, Kafka, RabbitMQ, AWS SQS, and others available.

Just, I edited a bit late, but I did mention that in the Current Behavior. 

> Serverless functions are by nature a push invocation as they are only active when needed. It's just a matter of how you decide to trigger the function. With OpenFaaS there are a lot of options

I guess my request/question is that is there a way that they could

**Comment by burtonr** [comment]
> Going though the full invocation seems a little wasteful.

I'm not sure what you mean by "wasteful". I'd counter that with saying that having a function running continuously scanning for changes seems wasteful. Rather, the function to do the work should only be ran when it's needed.

I think, for your case, the best bet would be using the cron connector run on a tight schedule to watch a directory, or other data source.

Generally speaking though, using the [NATS connector](https://github.com/openfaas-incubator/nats-connector) or [Kafka connector](https://github.com/openfaas-incubator/kafka-connector) would be more efficient as the functions would be listening and only become active when a message appears in the queue

**Comment by RichiCoder1** [comment]
> Generally speaking though, using the NATS connector or Kafka connector would be more efficient as the functions would be listening and only become active when a message appears in the queue

Apologies, this is what I meant. OpenFaas scales the function up based on queue length (and down to zero if queue length is zero). When spun up, the function's host uses the target's native queue consumption to pull in items and invoke the function locally, ala something like watchdog. Rather than going through the gateway invocation.

**Comment by LucasRoesler** [comment]
@RichiCoder1 you are very concretely right that functions must be invoked, but the way we have handled this via the queue-worker, see https://docs.openfaas.com/reference/async/  and https://github.com/openfaas/nats-queue-worker, the worker watches the queues and then invokes the functions. 

This allows the functions to be implemented and scaled completely agnostic to the source of the payload.  It also allows significant flexibility to different use cases and queue patterns that direct reading of the queue would either prevent or make significantly complex.

A typcial deployment usually looks like this:

![queue-worker-flow](https://user-images.githubusercontent.com/6358735/32060206-047eb75c-ba66-11e7-94d3-1343ea1811db.png)

The queue can be fed in two ways, in the flow shown above:
1. Using the async endpoint, you can queue payloads into the queue
2. The queue can be filled via any other external method

Aside from a general concern for efficiency, is there a specific metric or measurement you have made in this type of deployment that will cause this architecture to not work in your use case?

**Comment by RichiCoder1** [comment]
@LucasRoesler Not at the moment. That makes sense to me. Thanks for the explanation! Will reopen/new issue if I run into a specific issue or unmet use case

**Comment by LucasRoesler** [comment]
@RichiCoder1 I am going to mark this as closed.  Thanks for feedback and if you run into any issues or have questions about how to adapt the Queue Worker pattern for your specific queuing needs, feel free to reach out in any of the Slack channels.

**Comment by alexellis** [comment]
Thank you @LucasRoesler and @burtonr for the detailed explanations.
