### ISSUE TITLE
Deploying Keras models using TensorFlow

### ISSUE THREAD

**Issue by Guoyoyo** [openfaas/faas#1486]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

I am trying to deploy a model by using keras. The needed packages (Keras, python-opencv, etc.) installed successful except tensorflow. The error message is in the following:

``` ERROR: Could not find a version that satisfies the requirement tensorflow (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow (from -r requirements.txt (line 1))
The command '/bin/sh -c pip install -r requirements.txt --target=/home/app/python' returned a non-zero code: 1

[0] < Building demo done in 4.75s.
[0] Worker done.
Total build time: 4.75

Errors received during build:
- [demo] received non-zero exit code from build, error: The command '/bin/sh -c pip install -r requirements.txt --target=/home/app/python' returned a non-zero code: 1
```

## Expected Behaviour

Install tensorflow library successful.

## Steps to Reproduce (for bugs)

1. faas-cli new --lang python-debian tf-faas
2. cd tf-faas
3. vim requirements.txt add tensorflow
4. faas build -f tf-faas.yml

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):0.11.3

* Docker version `docker version` (e.g. Docker 17.0.05 ):18.09.6

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes 

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Code example or link to GitHub repo or gist to reproduce problem:N/A

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting) :N/A

## Next steps
Keep trying to find out the cause of the bug. If I have a new discovery, I will describe it here

**Comment by alexellis** [comment]
Hi, sorry but we don't do technical support over GitHub issues. I believe we are already helping you on Slack. Feel free to create a github issue with all the code and send a link into the thread where we are already helping you.
