### ISSUE TITLE
Invalid queue-worker image referenced in docker swarm deployment

### ISSUE THREAD

**Issue by ragingpastry** [openfaas/faas#1487]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Master is currently broken due to this: https://github.com/openfaas/faas/commit/690da5ed5ff505428508a19bd31d379be74d7e1e#diff-4e5e90c6228fd48698d074241c2ba760R125

The image openfaas/queue-worker:0.8.5 does not exist.

## Expected Behaviour

master to not be broken. I should be able to deploy a docker swarm stack and use async functions

## Current Behaviour

master is broken. I cannot deploy a docker swarm stack and use async functions

## Possible Solution

Don't bump the version to one that does not exist. Currently the queue worker version is referencing a version which does not exist.

## Steps to Reproduce (for bugs)

1. Deploy docker swarm stack according to instructions
2.
3.
4. Receive broken async functions

## Context

I was trying to use the docker swarm stack with async functions.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
@Waterdrips @freshrap6 how was this tested?

**Comment by alexellis** [comment]
Thanks for raising the issue.

Remember that you do not need to strictly use master, you can at any time checkout a release using its tag in `git`.
