### ISSUE TITLE
Integration: Hyper.sh provider

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#149]
Research item - help wanted from Hyper.sh or community.

Hyper functions can access each other via DNS so this may be a viable option for folks who are into what Hyper offers.

**Comment by Gnep** [comment]
Cool, will check.

Also, https://github.com/hyperhq/hyper-connector-k8s, a quick change on the aci-k8s-connector. Maybe a unified API interface for swappable backend drivers?

**Comment by alexellis** [comment]
I think that cloud be a very interested integration

**Comment by Gnep** [comment]
Hi Alex,

Let me discuss with our engineering team. I'm the CEO of Hyper, therefore I'm more of a talking head, instead of actual developer :)

**Comment by alexellis** [comment]
@Gnep I had an email from Song on your team about about starting work on this. Let me know if I can help in any way.

**Comment by johnmccabe** [comment]
Derek add label: skill/advanced

**Comment by alexellis** [comment]
@Gnep - I think this will be of use to your team, it makes implementing the code easier:

https://github.com/alexellis/faas-provider

**Comment by Gnep** [comment]
Thanks. Song is working on the integration right now. I'll ask him to follow up with you guys here.

**Comment by imeoer** [comment]
@alexellis Thanks for the working, we will take a look and apply to our provider.

**Comment by alexellis** [comment]
If anyone would like to try out the Hyper.sh integration it's available here:

Sign up with my referral code:

https://console.hyper.sh/register/invite/oAx1am6b7eFa2L40ary7TBYWE6eDxWFN

Then follow the detailed instructions here:

https://github.com/hyperhq/faas-hyper

Here are a couple of working screenshots 🍾 👍 

![s2](https://user-images.githubusercontent.com/6358735/30161708-a8b1e74a-93c9-11e7-8550-46e5da33aef9.png)
![s1](https://user-images.githubusercontent.com/6358735/30161709-a8e06822-93c9-11e7-9170-7ddbdd9d8aac.png)

**Comment by vivekjuneja** [comment]
I deployed the following functions 

1. functions/alpine:latest
2. functions/nodeinfo:latest

The deployment works great, and I was able to test the functions. 

The invocation count however on the OpenFaaS portal does not seem to work.

![openfaas_hyper](https://user-images.githubusercontent.com/122003/30177494-4ecfac8e-9406-11e7-8ad4-f632ba1a641a.gif)

[Link to screencapture](http://g.recordit.co/Qcs5y8hv5a.gif)

**Comment by alexellis** [comment]
Thank you for testing @vivekjuneja ! Here's what it looks like with metrics working: https://github.com/hyperhq/faas-hyper/issues/2

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by iampeterbanjo** [comment]
What else is needed to close this issue?

**Comment by alexellis** [comment]
Hey @iampeterbanjo are you thinking of helping out for Hacktoberfest? I think you'd need to compare notes with @Gnep and Song Yong over on their repo - http://github.com/hyperhq/faas-hyper

Testing would be good as a starting point 👍

**Comment by iampeterbanjo** [comment]
hi @alexellis yes I'm thinking of contributing as part of Hacktoberfest. Looking at Hyper's repo what's left seems to be adding new features so I think I might be getting in over my head :-)

**Comment by alexellis** [comment]
We have other areas that might be easier for you to get involved with. Please browse issues here and on the openfaas/cli project.

**Comment by iampeterbanjo** [comment]
Ok thanks, I'll do that.

**Comment by alias1** [comment]
Commented on https://github.com/hyperhq/faas-hyper/issues/1 as well, but is there a canonical `faas-cli` example with this?

**Comment by alexellis** [comment]
Have not heard from Hyper in a few months. No feedback on open issue so assuming inactive. Will close issue. cc/ @Gnep
