### ISSUE TITLE
Question about using private Docker registry

### ISSUE THREAD

**Issue by DylanFayant** [openfaas/faas#1491]
Hello the community !

I'm contacting you because I'd like using a private Docker registry for all my OpenFaas functions but I don't understand the documentation well. 

Documentation : [link here](https://ericstoekl.github.io/faas/operations/managing-images/) 

My first question is about the content of the request to send to configure the registry : 
```
curl -XPOST /system/functions -d {
    "service": "functionName",
    "image": "privateregistry.domain.com/user/function",
    "envProcess": "/usr/bin/myprocess",
    "network": "func_functions",
    "registryAuth": "dXNlcjpwYXNzd29yZA=="
}
```
I don't understand well what are these three body contents : "service", "envProcess" and "network". 

Image is the registry URL and registryAuth is the base64 name:password. 

My second question is about the use of this request. We put a functionName in the request so the use of this private Docker registry is only for one function (the functionName) ? Because I'd like to use my private Docker registry by default in my OpenFaas installation. 

Thank you ! I wish you a nice day :smile:

**Comment by alexellis** [comment]
Please use Slack for technical support.
