### ISSUE TITLE
Question: How to develop & deploy a function in a local Kubernetes cluster?

### ISSUE THREAD

**Issue by prokopsimek** [openfaas/faas#1493]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Is it possible to deploy a function to OpenFaaS running in Kubernetes Cluster (Docker for MacOS) on the localhost without building a Docker image?

## Expected Behaviour

I would like to develop a function and test in local OpenFaaS without the need for internet connection.

## Current Behaviour

The documentation says that I have to deploy an image with a function to Docker Registry.

## Possible Solution

1) I can deploy my own Docker Registry on the localhost but there is a build time of Docker image which I'd like to skip too.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  ea687659ecf14931a29be46c4d2866899d36c282
 version: 0.11.8
Your faas-cli version (0.11.8) may be out of date. Version: 0.12.2 is now available on GitHub.
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
```Kubernetes```
* Operating System and version (e.g. Linux, Windows, MacOS):
```MacOS Catalina v10.15```

## Next steps

If I could mount a volume to deploy a function locally or there is any other solution so I can add a new guide to the documentation.

**Comment by alexellis** [comment]
Hi @prokopsimek thanks for your interest in the project. There are a number of ways to achieve this however we do not use github for technical support requests.

Feel free to join Slack and ask there. 

Alex
