### ISSUE TITLE
Proposal: /tmp  directory read-only or optional

### ISSUE THREAD

**Issue by eplazaso** [openfaas/faas#1506]
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Possibility to make the /tmp folder optional or read-only when http health-check is set. 

## Expected Behaviour

Since /tmp is not strictly needed when having http health-check, It would be interesting to have an option to set it to read-only when readonly_root_filesystem is set to true. This will prevent the execution of malicious content in the lambda. Therefore adding extra security hardening, if needed.

## Current Behaviour

/tmp has writing and execution permission, and is not possible to make it optional.

## Possible Solution

Introduce a new flag to make the tmp folder optional, either not mounting it at all or simply mounting as read only. The later option could be based on the value of readonly_root_filesystem.

## Context

Given I have a lambda that does not need to write/read anything to disk, the tmp folder opens up an attack vector. Defeating the purpose of setting  the read only root filesystem to true. As you can still put files into tmp and also execute it. Although restricted by the potential user the container runs with.

**Comment by alexellis** [comment]
> Given I have a lambda that does not need to write/read anything to disk, the tmp folder opens up an attack vector. Defeating the purpose of setting the read only root filesystem to true. 

I don't agree with you.

The point of a read-only filesystem is to prevent the following:

* base system libraries and user space from being overwritten by a bad actor
* prevent the function code being overwritten

Having a small writable area under `/tmp` mirrors AWS Lambda and whilst you could fill this area up with 00s and 11s, I'm not sure what attack vector you're concerned about?

Read more at https://www.openfaas.com/blog/read-only-functions/

**Comment by eplazaso** [comment]
Thanks @alexellis for your quick response.  I have a doubt,  where is the difference of writing malicious code to tmp vs writing it to user repository?
