### ISSUE TITLE
'failed to update config func_alertmanager_config' during install on Docker for Windows

### ISSUE THREAD

**Issue by korggy** [openfaas/faas#1508]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I also tried running PowerShell as Administrator but that didn't help.

## Expected Behaviour
The installation script should complete without errors.

## Current Behaviour
In PowerShell I receive the following:
```
PS D:\temp\faas> .\deploy_stack.ps1
Attempting to create credentials for gateway..
basic-auth-user secret exists
basic-auth-password secret exists

Enabling basic authentication for gateway..

Deploying OpenFaaS core services
failed to update config func_alertmanager_config: Error response from daemon: rpc error: code = InvalidArgument desc = only updates to Labels are allowed
```

In Git Bash I receive the following:
```
$ ./deploy_stack.sh
Attempting to create credentials for gateway..
Error response from daemon: rpc error: code = AlreadyExists desc = secret basic-auth-user already exists
Error response from daemon: rpc error: code = AlreadyExists desc = secret basic-auth-password already exists
[Credentials]
 already exist, not creating
Enabling basic authentication for gateway..

Deploying OpenFaaS core services
failed to update config func_prometheus_config: Error response from daemon: rpc error: code = InvalidArgument desc = only updates to Labels are allowed
```

## Possible Solution
Perhaps there is something about my local Docker installation that is breaking this? I'm not experienced enough to know what to check.

## Steps to Reproduce (for bugs)
1. Open PowerShell
2. .\deploy_stack.ps1

or

1. Open Git Bash
2. .\deploy_stack.sh

## Context
I'm unable to install OpenFaaS.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
  commit 2d183c713b32385831dc7f69c073e57c06e3b76c
  version 0.12.2
* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.8, build afacb8b
* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
* Other diagnostic information / logs from [troubleshooting guide]

**Comment by alexellis** [comment]
Hi, this is not a first-time installation, it looks like you're installing a second time over an older version. Unfortunately Docker Swarm doesn't support upgrading configs and we recommend you use Kubernetes / k3s.

Feel free to seek out technical support on Slack, we only use GitHub for issues with the code.

Alex
