### ISSUE TITLE
Register external service as function (custom deployment)

### ISSUE THREAD

**Issue by andrevtg** [openfaas/faas#1516]
The current developer workflow is optimal and simple:

- new
- build
- push
- deploy
- remove

Some use cases (like the recurring "[mounted volume](https://github.com/openfaas/faas/issues/1178)" issue) could be solved in a more generic way if we could deploy the function by other means and "register" it later on in OpenFaaS. So an alternative workflow for "external" services could be:

- new
- build
- push
- deploy externally (using helm, kubectl, docker stack, whatever)
- register
- remove (just unregister in this case)

Registering an external service would create the pŕoper routes in the gateway (this is still a faas-cli generated container, so that should be simple enough).

This could be a very easy way to generically address custom deployment needs but still preserving simplicity on the rest of the workflow. Doesn't sound like it would have a great impact on code and it could also be a particular case for the operator too.

What do you think?

**Comment by alexellis** [comment]
Hi thanks for the suggestion. I need to know - is this just a dressed up request for volumes? I would like to know what specific usecase you have any where the current solution is falling short for you. It can be tempting to just present a technical solution, but we need to make sure the problem is understood well enough before going there. Alex

**Comment by andrevtg** [comment]
I have 2 use cases in here:

- Yes, volumes. My function is a Pipelinewise adaptation to FaaS and even tough each job is stateless in itself, scaling to more than a single instance demands a shared folder (like NFS);
- Additional k8s yaml for each function. In my case I am "surrounding" each function with a few custom resources that uniquely affect it on the ingress controller (Kong).

**Comment by alexellis** [comment]
Do you want this for Swarm or for Kubernetes? It's unclear which, since this repo is mainly for Swarm.

**Comment by alexellis** [comment]
Closing as inactive.
