### ISSUE TITLE
[Deploy]Use YML to deploy gateway components for help

### ISSUE THREAD

**Issue by promission** [openfaas/faas#1522]
Sorry, I found a lot of information that did not solve this problem, so I can only come here for help
---
kubectl version is 1.12

I refer to the official website yml installation method for deployment【**C. Deploy using kubectl and plain YAML (for development-only)**】。Finally executed kubectl apply -f ./yaml

After the deployment is complete, check the gateway deployment log and find that the error is as follows: 【**Error from server (BadRequest): a container name must be specified for pod gateway-68fc5f67c-krrk4, choose one of: [gateway faas-netes]**】，But I do n’t know how to choose one to deploy

I hope everyone can help，thanks！

**Comment by tardigrde** [comment]
@promission were you able to resolve this?

**Comment by alexellis** [comment]
Resolve what? It's a bizarre issue on an ancient version of Kubernetes 1.12?

@tardigrde can I ask you to please raise your own issue, but only after reading the docs.
