### ISSUE TITLE
Using Pull Dog

### ISSUE THREAD

**Issue by ffMathy** [openfaas/faas#1530]
I recently launched a service that I believe could be helpful in this repository. It's free to use (from a demo-cluster pool of free servers), and I need feedback. I think it could really be a win-win for us both.

https://dogger.io

It automatically spawns up a Docker-based test environment for each of your pull requests, based on a docker-compose.yml file that you choose.

I think it could be helpful in general, to test things out in production before they are merged.

What do you think? It is already used by the [Portainer project](https://github.com/portainer/portainer), and they have been very happy with it so far.

**Comment by alexellis** [comment]
Hi @ffMathy,

Just some general feedback for you on your style and brand here.

Some folks make call this the equivalent of "cold calling" - when someone phones you up with no context, and doesn't even know your name, firing off as many leads as you can, to see which stick (you know that feeling when a LinkedIn recruiter contacts you?):

<img width="837" alt="Screenshot 2020-05-17 at 15 19 50" src="https://user-images.githubusercontent.com/6358735/82150955-ddd94c80-9851-11ea-9345-0505e38190c5.png">

Other folks might be more understanding, and see past that.

I'm not sure that dogger is going to solve a problem for us right now, but will bear it in mind for the future if something comes up.

Alex

**Comment by ffMathy** [comment]
Hi @alexellis - thank you for your reply.

I carefully looked those projects up, and I can assure you that it's not just intended as spam, but I can see how it may be viewed that way. I'm not interested in non-relevant users either. They all have a `docker-compose.yml` file and are Docker Compose based.

Portainer was happy that I contacted them this way, and it actually solved a problem for them. That way, I don't see how it's necessarily bad.

That being said, I respect your view on this, and I'll see if I can find a way to target this in a more relevant manner.

**Comment by alexellis** [comment]
Best of luck with the product. It's likely that you'll need more than one method and channel to get to critical mass.
