### ISSUE TITLE
gateway/queworker and faas-idler won't start

### ISSUE THREAD

**Issue by pixeldrew** [openfaas/faas#1532]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Installed k3os 0.10.1 onto VirtualVox VM from liveCD
Used https://bit.ly/2WYRmqo as starting configuration (k3os by default uses traefik as ingress lb)
Used Arkade to install openfaas

## Expected Behaviour

Gateway/Queue and FAAS-idler should start

## Current Behaviour

Gateway/Queue and FAAS-idler does not start

## Steps to Reproduce (for bugs)

1. Run k3os live CD from 
2. Install k3os to virtual disk
3. Copy kubeconfig to host:
```sh
scp rancher@10.137.0.183:/etc/rancher/k3s/k3s.yaml ./k3s-vm-config.yaml
export KUBECONFIG=`pwd`/k3s-vm-config.yaml
```
3. Use arkade to install openfaas

## Context

Trying to test out single node cluster with openfaas installed locally, i'm trying to determine if this is a viable alternative to azure-functions

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 version: 0.12.4
* Docker version `docker version` (e.g. Docker 17.0.05 ):
containerd
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
```
NAME        STATUS   ROLES    AGE   VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION     CONTAINER-RUNTIME
k3os-6139   Ready    master   22m   v1.17.5+k3s1   10.137.0.183   <none>        k3OS v0.10.1   5.0.0-43-generic   containerd://1.3.3-k3s2
```
* Operating System and version (e.g. Linux, Windows, MacOS):
k3os 0.10.1
* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
```
kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
nats                1/1     1            1           25m
basic-auth-plugin   1/1     1            1           25m
alertmanager        1/1     1            1           25m
prometheus          1/1     1            1           25m
queue-worker        0/1     1            0           25m
gateway             0/1     1            0           25m
faas-idler          0/1     1            0           25m
```

```
kubectl logs queue-worker-54cfc7d5bc-xpvq4 -n openfaas         
Loading basic authentication credentials
Connect: nats://nats.openfaas.svc.cluster.local:4222
can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection
panic: can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection

goroutine 1 [running]:
log.Panic(0xc0000f1da8, 0x1, 0x1)
	/usr/local/go/src/log/log.go:338 +0xac
main.main()
	/go/src/github.com/openfaas/nats-queue-worker/main.go:208 +0x5ac
```

```
kubectl logs faas-idler-d4dd46745-8xmtq -n openfaas                  
panic: Get http://gateway.openfaas:8080/system/info: dial tcp 10.43.223.78:8080: connect: connection refused

goroutine 1 [running]:
main.main()
	/go/src/github.com/openfaas-incubator/faas-idler/main.go:72 +0x847
```

```
kubectl logs -n openfaas gateway-5cffc9c5bd-zw87k gateway
2020/05/24 16:25:35 HTTP Read Timeout: 1m5s
2020/05/24 16:25:35 HTTP Write Timeout: 1m5s
2020/05/24 16:25:35 Binding to external function provider: http://127.0.0.1:8081/
2020/05/24 16:25:35 Async enabled: Using NATS Streaming.
2020/05/24 16:25:35 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
2020/05/24 16:25:35 Connect: nats://nats.openfaas.svc.cluster.local:4222
&{0xc00000dd00}
2020/05/24 16:25:35 nats: no servers available for connection
```
```
kubectl logs -n openfaas gateway-5cffc9c5bd-zw87k faas-netes          
W0524 16:04:29.406415       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020/05/24 16:04:29 HTTP Read Timeout: 1m0s
2020/05/24 16:04:29 HTTP Write Timeout: 1m0s
2020/05/24 16:04:29 HTTPProbe: true
2020/05/24 16:04:29 SetNonRootUser: false
2020/05/24 16:04:29 Starting operator. Version: 0.10.5	commit: 9be50543b372381a505e9e54a1356bb076c8f01f
```
## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi, I'm going to close this issue as technical support since OpenFaaS is working as expected in our end to end tests.

For technical support and more esoteric combinations, you should definitely join OpenFaaS Slack and maybe Rancher Slack too. Check that your networking in Kubernetes is configured properly. 

Alex
