### ISSUE TITLE
why functions are automatically public ?

### ISSUE THREAD

**Issue by yvz5** [openfaas/faas#1536]
Making every function public is not the best idea. I would prefer making all functions private by default and make certain functions only public. Is there a way to change this behaviour ? Is there a way that I can change the kubernetes ressources created by the cli ? Maybe then I can remove the ingress rule for the function ?

**Comment by alexellis** [comment]
Hi thank you for your interest in the project. I just wanted to let you know that we don't handle miscellaneous questions through GitHub issues, but through Slack.

Feel free to join and fire away using threads.
