### ISSUE TITLE
Swarm images for ARM64 would benefit from being updated

### ISSUE THREAD

**Issue by TinyAngryKitten** [openfaas/faas#1537]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Current Behaviour
On arm64, queue-worker does not start when running deploy_stack.sh, it is stuck as pending saying there are no supported nodes. This is because the queue-worker image it uses is built for amd64, not arm64 as it should be.

## Possible Solution
A quick fix would be to change the queue-worker tag from 0.9.0-arm64 to just 0.9.0, however, all queue-worker images with a platform tag is built for [amd64](https://hub.docker.com/r/openfaas/queue-worker/tags?page=2) and that should probably be fixed to avoid problems later.

## Steps to Reproduce (for bugs)
1. run deploy_stack.sh
2. docker stack ps func
3. queue-worker will be pending with Error: no suitable node
## Your Environment
Raspberry pi 4
Ubuntu 18.04 LTS

**Comment by alexellis** [comment]
It would be more or less safe to update the file to match the contents of the main docker-compose.yml file - retaining the arm64 suffix for everything apart from the queue-worker, which is now multi-arch.

I hear that @aidun is looking to contribute again. Markus, can you take this on?

https://github.com/openfaas/faas/blob/master/docker-compose.yml

https://github.com/openfaas/faas/blob/master/docker-compose.arm64.yml

Whilst there, you could probably update armhf if required

https://github.com/openfaas/faas/blob/master/docker-compose.armhf.yml

**Comment by alexellis** [comment]
This issue should not be closed until the PR is completed. @aidun how are you doing with that patch?

**Comment by aidun** [comment]
I planned to do it tomorrow evening

**Comment by BobTheDestroyer** [comment]
#1525 was closed assuming it was because the arm64 image for queue was not patched.
I had already looked at the modification done and did it myself, so it is not the queue worker.
