### ISSUE TITLE
Errors you may encounter when upgrading the library

### ISSUE THREAD

**Issue by KateGo520** [openfaas/faas#1545]
### github.com/prometheus/client_golang  
-Latest Version: v1.6.0   (Latest commit 6edbbd9 on 28 Apr)
-Where did you use it: 
https://github.com/search?q=prometheus%2Fclient_golang++repo%3Aopenfaas%2Ffaas+path%3A%2Fwatchdog+path%3A%2Fgateway+path%3A%2Fauth%2Fbasic-auth&type=Code&ref=advsearch&l=&l= 
-Detail: 
>[github.com/prometheus/client_golang/go.mod](https://github.com/prometheus/client_golang/blob/v1.6.0/go.mod#L5)
```
module github.com/prometheus/client_golang
go 1.11
require (
	github.com/beorn7/perks v1.0.1
	github.com/cespare/xxhash/v2 v2.1.1
	…
)
```
>[github.com/prometheus/client_golang/prometheus/registry.go](https://github.com/prometheus/client_golang/blob/v1.6.0/prometheus/registry.go#L28)
```
package prometheus
import (
	"github.com/cespare/xxhash/v2"
	"github.com/golang/protobuf/proto"
	…
)
```
This problem was introduced since **_prometheus/client_golang v1.2.0_** .Now you used version [v1.1.0](https://github.com/openfaas/faas/blob/master/gateway/Gopkg.toml#L19). If you try to upgrade  **prometheus/client_golang** to version **v1.2.0** and **above**, you will get an error--- **_no package exists at "github.com/cespare/xxhash/v2"_**

## I investigated the libraries  (**prometheus/client_golang >= v1.2.0**)  release information and found the root casue of this issue is that---- 
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the recent versions.

2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has migrated to Go Modules _must_ include the major version in the import path to reference any v2+ modules. For example,  Repo github.com/my/module migrated to Modules on version v3.x.y.  Then this repo should declare its module path with MAJOR version suffix "/v3"  (e.g., module `github.com/my/module/v3`), and its downstream project should use `"github.com/my/module/v3/mypkg"` to import this repo’s package.

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### 1. Migrate to Go Modules.
Go Modules is the general trend of ecosystem, If you want a better upgrade package experience, migrating to Go Modules is a good choice.

### 2. Keep using the dependency manage tool (like dep, glide, govendor, etc).

Because the import paths have different meanings between the projects adopting module mechanism and the non-module mechanism. 

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

If you prefer to use the dependencies manage tool (like dep, glide, govendor, etc), a textbook example provided by repo `github.com/moby/moby` can prevent this type of issues.
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf
In the vendor directory, `github.com/moby/moby` adds the **/vN** subdirectory in the corresponding dependencies.
**This will help more downstream modules to work well with your package, otherwise they will be stuck in github.com/cespare/xxhash v1.1.0.**

**By the way**, have you ever encountered such errors when upgading the libraries? Do you plan to upgrade the libraries in near future?
Hope this issue report can help you ^_^
Thank you very much for your attention.

Best regards,
Kate

**Comment by KateGo520** [comment]
@alexellis  @Waterdrips  Could you help me review this issue? Thx :p

**Comment by alexellis** [comment]
Hi,

I saw that your account appears to be automating GitHub issues, perhaps as a bot.

We haven't updated this dependency yet so are unaware of any issues, but will look into them at the time. What kind of outcome are you hoping for?

Alex

**Comment by alexellis** [comment]
Even the comments seem automated -> https://github.com/googlecloudrobotics/core/issues/51

<img width="1113" alt="Screenshot 2020-07-07 at 09 36 33" src="https://user-images.githubusercontent.com/6358735/86749712-5c25c400-c035-11ea-9d78-d19f47875e2d.png">

**Comment by KateGo520** [comment]
@alexellis  I am a Ph.D. student and my research topic is developing an effective technique to help open-source developers manage their Golang dependencies. I just provided the detection results of my detection tool and try to find a better way to help Go projects to adapt to module management mechanism. This is a non-trivial task. Guaranteeing the quality of our open-source community is our common goal. Thank for your support and understanding.
 
 
Best regards,
Kate
