### ISSUE TITLE
Question: Invoke function depending on HTTP method

### ISSUE THREAD

**Issue by dennisMKI** [openfaas/faas#1546]
I wanna split a Microservice into smaller functions using OpenFaaS. 
Currently my Microservice has several REST endpoints supporting get, post, update and delete e.g.: /users
- get: get all users
- post: create new user
- ...

Is it possible to replace my microservice without changing the REST endpoint structure? For example via configuration of the API-Gateway/faas-provider to route the calls depending on the http method/verb in the YAML stack file e.g.: /users
- get: invoke "get-users" function
- post: invoke "add-user"_ function 
- ...

Thanks in advance!

Dennis

**Comment by alexellis** [comment]
Hi @dennisMKI please could you join Slack for technical support?

Thanks :-)

Also, if you Google "openfaas crud" you'll see several articles that I've written on this.

Alex
