### ISSUE TITLE
Question on how to scale the queue-worker

### ISSUE THREAD

**Issue by hwuerz** [openfaas/faas#1550]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Hi,

I have many requests to an async function, more than can be processed in real time. As a result, the queue fills up. Now I want the function and especially the queue-workers to scale with the size of the queue.

As background: My function has a fixed `max_inflight` value and is only called asynchronously (`/async-function/my-function`). By scaling queue-worker and the function together I can avoid unnecessary HTTP 429 errors. If a combined scaling does not work, an independent scaling of the queue-worker based on the queue length would help me too.

Is this possible with OpenFaaS on Kubernetes?

What I found so far:
https://github.com/openfaas/faas/issues/671 A combination of function scaling and queue-worker scaling was mentioned but not elaborated on. 
https://github.com/openfaas/faas/issues/1479 The result was that the queue-worker should be used for many requests, their scaling was not discussed.
https://github.com/openfaas/workshop/blob/master/lab7.md Lab 7 in the workshop only deals with the queue-worker logs, but not with their scaling.
https://docs.openfaas.com/reference/async/ The docs say that the queue workers should be scaled for higher concurrency, but not how.

Thanks for OpenFaaS, it' s a great framework!

## Expected Behaviour

OpenFaaS scales the queue workers for async function calls based on the queue size. Ideally, the function is scaled accordingly.

## Current Behaviour

The queue workers are not scaled. Neither automatically, nor based on the queue size.

## Steps to Reproduce (for bugs)

1. Create a function that takes a few seconds to finish.
2. Call the function via `/async-function/my-function` more often than the requests can be processed.
3. The NATS queue fills.
4. The queue workers and the function do not scale as a result of the increasing queue size.

## Context

I have many function calls that take some time in total, but should be finished as soon as possible. Therefore OpenFaaS should scale the queue worker and the function based on the queue size.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  2d183c713b32385831dc7f69c073e57c06e3b76c
 version: 0.12.2
Your faas-cli version (0.12.2) may be out of date. Version: 0.12.8 is now available on GitHub.

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Kubuntu 18.04

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi, are you part of the Cognite team as this sounds very familiar to what I've been helping @andeplane set up?

Alex

**Comment by alexellis** [comment]
/set title: Question on how to scale the queue-worker

**Comment by hwuerz** [comment]
Hi Alex, thanks for your prompt response! 

No, unfortunately I have nothing to do with Cognite. Is there any way I can find the results of your project?

Thanks, Hendrik

**Comment by alexellis** [comment]
So there are a few ways this has been solved before, or that it could be approached:

1) Add an autoscaling rule on the 429 HTTP code - this is easy to do, just update the Prometheus / Alertmanager config - Cognite did this - https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/prometheus-cfg.yaml#L65
2) Add a HPAv2 rule for the queue-worker - base it upon CPU or memory, it's up to you which - then it will autoscale (see the example we provide for functions, you can copy it)
3) Update the parallelism of the queue-worker, you will see that it can be set to a massive number for a single process, there is no longer any need to scale the queue-worker. https://docs.openfaas.com/reference/async/#parallelism
4) If you have slow functions that block a queue - you can use multiple named queues - https://docs.openfaas.com/reference/async/#multiple-queues

Re: "scaling functions" - this is automatic and built-in, so there is no need to request this. If however you are finding the scaling rule is not working for your use-case, you can:

1) Use HPAv2 instead with memory or CPU and we provide a tutorial for that - https://docs.openfaas.com/tutorials/kubernetes-hpa/
2) Use HPAv2 with custom metrics that you emit - https://docs.openfaas.com/tutorials/kubernetes-hpa-custom-metrics/

If you feel you need to see retries, then you could do this by using Linkerd - it can configure a retry budget for services - https://github.com/openfaas-incubator/openfaas-linkerd2 - https://linkerd.io/2/tasks/configuring-retries/

**Comment by hwuerz** [comment]
The function scaling based on the 429 HTTP errors sounds like a good idea. I'll do that. 
And if the queue-workers can handle so many concurrent connections, then I won't scale them either. I will simply set their parallelism to `max_inflight of the function * max scaling of the function`. That way, with maximum scaling of the function, no more unnecessary 429 should come back.

Linkerd sounds exciting. I will have a look at it

Thanks again, you' re great!

**Comment by alexellis** [comment]
Glad to help.

You can get insights like this regularly from my Insiders Updates emails which includes updates on OpenFaaS, Kubernetes and cloud computing. https://insiders.openfaas.io - some tiers include the complete set of back issues that covers the queue-worker in more detail. 

You may also want to join Slack to chat with the community. Link in the docs.
