### ISSUE TITLE
Question about how GetReplicas works with function invocation

### ISSUE THREAD

**Issue by MSchabel** [openfaas/faas#1556]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Summary
While browsing Kibana Logs I noticed that some [GetReplicas()](https://github.com/openfaas/faas/blob/11ff356ccea32b89b9da556c18305cd7c5ea9ba5/gateway/plugin/external.go#L56) calls take longer than 3 seconds. (see screenshot) 
![image](https://user-images.githubusercontent.com/17764789/88034745-6968a580-cb41-11ea-8a94-7fcad4342e01.png)
Previously during high load situations, those values could go up more significant.
The question would be now if it is intended and wanted behavior, that the gateway waits forever for a response from the function provider. I saw that there is a timeout for the [connection creation](https://github.com/openfaas/faas/blob/11ff356ccea32b89b9da556c18305cd7c5ea9ba5/gateway/plugin/external.go#L32), but no total timeout
## Expected Behaviour

GetReplicas() calls should have a meaningful timeout so the execution can not be halted.
## Current Behaviour
GetReplicas() calls can take way longer than the expected 3 seconds, therefore, blocking/halting an invocation.
## Possible Solution
Setting the timeout property `http.Client` with a meaningful value to avoid endless waiting. 
## Steps to Reproduce (for bugs)
```go
package main
import (
    "log"
    "net"
    "net/http"
    "net/http/httptest"
    "time"
)
// Taken directly from Gateway Code
func getClient() http.Client {
    proxyClient := http.Client{
        Transport: &http.Transport{
            Proxy: http.ProxyFromEnvironment,
            DialContext: (&net.Dialer{
                Timeout:   3 * time.Second,
                KeepAlive: 0,
            }).DialContext,
            MaxIdleConns:          1,
            DisableKeepAlives:     true,
            IdleConnTimeout:       120 * time.Millisecond,
            ExpectContinueTimeout: 1500 * time.Millisecond,
        },
    }
    return proxyClient
}
func main() {
    // Faulty Server taking long to respond
    svr := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        time.Sleep(50 * time.Second)
    }))
    defer svr.Close()
    // Client Code
    log.Println("Making request")
    start := time.Now()
    client := getClient()
    _, err := client.Get(svr.URL)
    if err != nil {
        log.Printf("Request Failed with %s", err.Error())
    } else {
        log.Printf("Request Success")
    }
    log.Printf("Request took %fs", time.Since(start).Seconds())
    log.Println("Finished request")
}
```

**Comment by alexellis** [comment]
Hi @MSchabel thank you for your interest in the project.

I've got to say that the way this issue is worded comes across rather odd. I'm going to update it if that's OK with you?

Can you trace the code that you think is calling `GetReplicas()` and copy the line in here? We also need to be mindful of what knock-on effect they may be if we do not wait for the `GetReplicas()` call to complete before trying to invoke and endpoint. The code is there for a reason - to check readiness before invocation when scaling from zero, it's also cached for a period of time.

Regards,

Alex

**Comment by alexellis** [comment]
/set title: Question about how GetReplicas works with function invocation

**Comment by alexellis** [comment]
Can you confirm how many deployment objects you have in the openfaas-fn namespace, and whether you're using the controller (default) or operator (CRD) for OpenFaaS?

**Comment by alexellis** [comment]
@templum, this looks like LivePerson? Can you fill in any context and details?

**Comment by Templum** [comment]
Using the controller and we know it is related to the auto-scaling. This makes your point valid, but I would say a meaningful default makes sense to avoid that it waits for minutes/hours. Given that, for some reason, the response takes so long.

**Comment by MSchabel** [comment]
Hey @alexellis 
> I've got to say that the way this issue is worded comes across rather odd. I'm going to update it if that's OK with you?

sure 👍 

> Can you trace the code that you think is calling `GetReplicas()` and copy the line in here? 

See [here](https://github.com/openfaas/faas/blob/11ff356ccea32b89b9da556c18305cd7c5ea9ba5/gateway/scaling/function_scaler.go#L47)

Regards,
Martin

**Comment by alexellis** [comment]
Locking as inactive with no repro given.
