### ISSUE TITLE
/system/functions endpoint never update the number of availableReplicas

### ISSUE THREAD

**Issue by Willena** [openfaas/faas#1557]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
- The json returned when calling http://gateway:8080/system/functions should return the correct number of availableReplicas for each deployed functions
- The json returned when calling http://gateway:8080/system/function/<funcName> should return the correct number of availableReplicas for the <funcName> functions

## Current Behaviour
- For now, http://gateway:8080/system/functions always return 0 availableReplicas for each function in the returned array, whereas http://gateway:8080/system/function/<funcName> gives the correct number of availableReplicas

## Possible Solution
- Fix the http://gateway:8080/system/functions so that the availableReplicas property get updated.

## Steps to Reproduce (for bugs)
1. Create a new swarm
2. Deploy OpenFaas
3. Build and deploy a simple function (for example named: example-func
4. Wait for the function to deploy
5. Call http://gateway:8080/system/function/example-func
6. Observe the number of availableReplicas
7. Call http://gateway:8080/system/functions
8. Look at the array item that corresponds to example-func
9. The availableReplicas value in the object corresponding to example-func is 0 and does not get updated

## Context
- Build a simple script that call the API of the gateway to wait for all my app function to be deployed and running on the cluster, in order to start a CI job

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.4

* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Code example or link to GitHub repo or gist to reproduce problem: X

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting): X

**Comment by alexellis** [comment]
This is as designed, for the replica count you need to use the status URL

```
/system/function/NAME
```

**Comment by alexellis** [comment]
/set title: Question about where to find availableReplicas

**Comment by Willena** [comment]
Then why the availableReplicas property is also present in the returned objects of `/system/functions` if it is useless ?
