### ISSUE TITLE
Question: CLI and Web Console login problem on k8s

### ISSUE THREAD

**Issue by asatarov** [openfaas/faas#1563]
## My actions before raising this issue
- I have a fresh installation of OpenFaas on K8s by helm chart. It is up and running.
- Basic-auth is enabled

## Expected Behaviour

I want to login to gateway either by CLI or by WebUI. But can't.

## Current Behaviour

I can't login to gateway either by CLI or by WebUI.

```
> kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode
fPy0KUMyvZxu
> kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-user}" | base64 --decode
admin
> kubectl port-forward -n openfaas svc/gateway 31112:8080 &
Forwarding from 127.0.0.1:31112 -> 8080
Forwarding from [::1]:31112 -> 8080
> faas-cli login -g http://127.0.0.1:31112 -u admin --password fPy0KUMyvZxu
WARNING! Using --password is insecure, consider using: cat ~/faas_pass.txt | faas-cli login -u user --password-stdin
Calling the OpenFaaS server to validate the credentials...
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Unable to login, either username or password is incorrect
```
When trying to open https://gateway.some.domain in browser it ask login and password and can't login also.

In Pod basic-auth-plugin-XXX log there is only :
2020-08-19T14:10:06.655330332Z 2020/08/19 14:10:06 Validated request 401.

## Possible Solution

How can I further investigate the issue and find a couse of the problem ?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by snsie** [comment]
I'm also having this issue
