### ISSUE TITLE
Invoke function in the UI is not working when direct_function is set to false

### ISSUE THREAD

**Issue by phgache** [openfaas/faas#1565]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

The "invoke" button should call the function and the UI shoud show the function return.

## Current Behaviour

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/2770972/91423817-54c2b000-e859-11ea-9aef-45a08f6c53ff.png">

As you can the see the call is failing because when the operator try to lookup for the function service, the name used is concatenated with the namespace.
This is working with direct_function set to true because in this case the operator is not involved.
 
Given that, imho there is two options : 

1. Removing the namespace when the UI is calling the function because it is working in both mode (direct_function) 
2. Make the gateway and operator being able to work with the namespace added to the function name.

I have seen new feature about using multiple namespaces so the option 2 is maybe the best one as it will probably have less impacts.

## Possible Solution

I’m not 100% sure that this is the best option, but as OpenFaaS does not support multiple namespace when direct_function is set to false, removing it in the « trimURLTransformer » could be an option :

[main.go](https://github.com/openfaas/faas/blob/master/gateway/main.go#L96)

```
	nilURLTransformer := handlers.TransparentURLPathTransformer{}
	trimURLTransformer := handlers.FunctionPrefixTrimmingURLPathTransformer{}

	if config.DirectFunctions {
		functionURLResolver = handlers.FunctionAsHostBaseURLResolver{
			FunctionSuffix:    config.DirectFunctionsSuffix,
			FunctionNamespace: config.Namespace,
		}
		functionURLTransformer = trimURLTransformer
	} else {
		functionURLResolver = urlResolver
		functionURLTransformer = nilURLTransformer
	}
```

[forwarding_proxy.go](https://github.com/openfaas/faas/blob/master/gateway/handlers/forwarding_proxy.go#L214)

```
// Transform returns the URL path unchanged.
func (f TransparentURLPathTransformer) Transform(r *http.Request) string {
	return r.URL.Path // remove the namespace at the end
}

```
## Steps to Reproduce (for bugs)

1. Deploy the openfaas with direct_functions set to false
2. Deploy nodeinfo function sample
3. Hit the invoke button

## Context

This issue seems to only occurs in the UI which is has a minimal impact on our project. I raise this issue also to be sure that there is no further impact that I was not able to see.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
0.12.4

* Docker version `docker version` (e.g. Docker 17.0.05 ): 
19.03.13-beta2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? 
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOs 10.15.4

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by LucasRoesler** [comment]
We are getting really close with multiple namespace support in the operator, i would rather fix this bug in the operator instead of hacking the gateway here. I will definitely take a look this weekend

**Comment by LucasRoesler** [comment]
@phgache I have created a potential fix in faas-netes, if you checkout https://github.com/openfaas/faas-netes/pull/683 you can see the testing instructions and if you are feeling adventurous, give it a try and help us verify the fix

**Comment by alexellis** [comment]
Fixed in: https://github.com/openfaas/faas-netes/releases/tag/0.12.3

@phgache please could you try it out?

**Comment by phgache** [comment]
Hi,

I have deployed the new version and the bug is fixed.

Thanks @LucasRoesler & @alexellis
