### ISSUE TITLE
Support for registries other than docker hub.

### ISSUE THREAD

**Issue by senthilnathan** [openfaas/faas#1566]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

The default docker images used to build the functions are from docker hub.
  e.g. openfaas/classic-watchdog
And docker hub has recently introduced rate limit: https://docs.docker.com/docker-hub/download-rate-limit/        
It will be very useful if this registry is made configurable to use pull through caches/mirror in place of docker hub.

## Expected Behaviour

We should be mirror these images from any other private registry and use that while building the functions.

## Current Behaviour

To the best of my knowledge, this registry is not configurable to any registry other than docker hub.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.9.5
* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.1
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

Please let me know if I should raise this issue in the faas-cli repository instead.

**Comment by alexellis** [comment]
Hi senthilnathan who do you work for and how are you using the project?

All images can be mirrored and pointed at another registry.

In short, you should pay Docker. It's not practical to avoid their fees, and the time you'll spend fighting it is going to far outweigh the 7 USD per month you'd be paying them.

Closing this as a support request. No features are needed to support your suggestion.

Alex
