### ISSUE TITLE
Function deployment finish but Not Ready on UI and  liveness probe failed warning in pod

### ISSUE THREAD

**Issue by JasonPad19** [openfaas/faas#1569]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I have initially installed openfaas and work fine in the newly created kubernetes cluster (v 1.18).
And then i try to install kuberflow v.1.1 on the same cluster. 
If i try to deploy an new function, I will encounter liveness probe failed in the pod, and see Not Ready on UI.
However, the status of the pod and service are in running status.  Also, all other previous deployed openfaas functions are still working.

## Expected Behaviour

I am expecting the deployed function to be in Ready status on UI.

## Current Behaviour

 I will encounter liveness probe failed in the pod, and see Not Ready on UI.

## Possible Solution

I wonder if it is caused by kuberflow installation. They are using istio as well. 
Would you please suggest how to debug and fix/workaround it ?

## Steps to Reproduce (for bugs)

1. Install OpenFaas 
2. Deploy functions, and everything works
3. Install Kubeflow v.1.1
4. Deploy functions, and function shows Not Ready on UI.

## Context

I am trying to deploy a function to openfaas.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  f7c29ea19b5df9d7aa87e9c70aacf4d9315da2cd
 version: 0.12.4
Your faas-cli version (0.12.4) may be out of date. Version: 0.12.9 is now available on GitHub.

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
Function pod log, not sure why it is refering to gcr.io for istio-proxy.
![image](https://user-images.githubusercontent.com/52347372/93152224-37934a00-f752-11ea-98ac-7d26e348ddc7.png)

Function service log comparison. Previous deployed function is working. Newly deployed function is not working.
![image](https://user-images.githubusercontent.com/52347372/93149321-1cbcd780-f74a-11ea-8516-187d6d7c9a2c.png)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by JasonPad19** [comment]
I managed to make it work by uninstalling kubeflow.

Also, need to follow this step if istio is running on the same cluster.
https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/

Before you start
Configuring your installation with kfctl_k8s_istio.v1.1.0.yaml has an option you should consider:

Disabling istio installation - If your Kubernetes cluster has an existing Istio installation you may choose to not install Istio by removing the applications istio-crds and istio-install in the configuration file kfctl_k8s_istio.v1.1.0.yaml

**Comment by alexellis** [comment]
Glad you were able to solve your own issue. There are some community resources for Istio, which may be of help.

https://docs.openfaas.com/tutorials/featured/#service-mesh
