### ISSUE TITLE
[Question] Function timeouts and relationship to gateway timeouts

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas#1574]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

So I've been looking at documentation as well as existing issues and the labs related to timeouts, and I'm not sure on the wording of this what is actually expected to happen.

Per [lab 8](https://github.com/openfaas/workshop/blob/master/lab8.md)
> API Gateway
> There is also a maximum timeout duration set at the gateway and it will override the function timeout. At the time of writing the maximum timeout is configured at "20s", but can be configured to a longer or shorter value.

The implication here is that this _overrides_ the function timeout, rather than is a separate maximum timeout across all functions.

### Case 1
1. timeout on function is set to `10s`
2. timeout on gateway is set to `20s`
3. runtime timeout is `10s`

### Case 2
1. timeout on function is set to `2m`
2. timeout on gateway is set to `1m`
3. runtime timeout is `1m`

## Current Behaviour

Unknown; based on current wording it appears that the gateway _overrides_ the function, rather than acting as a _global maximum_.

If that wording is correct, then it would imply that setting timeouts on functions has no effect, outside of `exec_timeout`.

## Possible Solution

* Improve documentation on this. I would prefer not to see the labs have detailed information that can't be found in the official documentation.
* Rename parameters to be more self-explanatory.

## Context

I'm trying to have small-ish functions autoscale based on requests, and things are being re-queued due to what seems like a bunch of interplay between a bunch of timeouts that I'm unsure of what they actually do, despite searching the docs, the helm chart, and the labs.

**Comment by alexellis** [comment]
I believe this was due to an issue in the operator, which was fixed recently. It supported timeouts i.e. `10` (meaning 10s), but only as an integer. It can now parse Golang durations i.e. `10s`
