### ISSUE TITLE
Typo in Swagger YAML (OpenAPI definition)

### ISSUE THREAD

**Issue by noam09** [openfaas/faas#1578]
There is a typo in the [Swagger YAML file](https://github.com/openfaas/faas/blob/master/api-docs/swagger.yml).
`FunctionDefintion` should be `FunctionDefinition`

**Comment by alexellis** [comment]
@viveksyngh could you send us a PR to fix this please?

**Comment by alexellis** [comment]
Thanks @noam09

**Comment by alexellis** [comment]
Yankee can you take this?

**Comment by yankeexe** [comment]
Yeah sure @alexellis

**Comment by alexellis** [comment]
Thank you both!
