### ISSUE TITLE
How to see Metrix Traffic Outbound/Inbound

### ISSUE THREAD

**Issue by derit** [openfaas/faas#1582]
I have a question, i want to see traffic outbound/Inbound data how to make sure it with metrix? 
for example :
i want to create upload download file and i want to see, how much (Bytes) data outbound/Inbound  

thanks

**Comment by alexellis** [comment]
[kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) or your CNI network plugin should be able to do this.

**Comment by derit** [comment]
i only using flannel, and i don't know flannel can do it
