### ISSUE TITLE
Sentiment Analysis missing arm64 build

### ISSUE THREAD

**Issue by mihaigalos** [openfaas/faas#1587]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I wanted to deploy SentimentAnalysis on an arm64 RPi4. No such build was provided. I can help here.

## Expected Behaviour
I would like to deploy SentimentAnalysis on an arm64 device using faas-cli.

## Current Behaviour
Currently not possible, as no arm64 docker.

## Possible Solution
Implement the arm64 docker and build the container.

## Steps to Reproduce (for bugs)
Inspect the [store](https://github.com/openfaas/store/blob/master/store-arm64.json).
Inspect the [SentimentAnalysis](https://github.com/openfaas/faas/tree/master/sample-functions/SentimentAnalysis): no arm64 docker file.

## Context
None.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
We will add this via CI in the project, it's not a priority so it may take a while, but it's important to have official images.

**Comment by alexellis** [comment]
This has been completed in: https://github.com/openfaas/store-functions/ along with a bunch of other functions. Enjoy.
