### ISSUE TITLE
Save the date 🎂 - OpenFaaS 4th birthday!

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1592]
Join us for the OpenFaaS 4th birthday celebration on our online stream!

![71088225-de33c580-2195-11ea-802d-0b1268bca410](https://user-images.githubusercontent.com/6358735/99195912-b1f73f00-2780-11eb-8800-c81527080b33.png)

*Where:* [Sign up here for your invite](https://forms.gle/hZBSpfXHxSoEEFbz5)
*Date:* 18th December 2020 1700 GMT

What else can you do to help OpenFaaS? [Become a GitHub Sponsor for the project](http://github.com/sponsors/openfaas/) or the [project lead](http://github.com/sponsors/alexellis)

Get your SWAG ready for the call 🎅

* ["Gift of Serverless" Christmas Jumper & t-shirt](https://store.openfaas.com/collections/best-sellers-2020/products/gift-of-serverless-christmas-jumper)
* [OpenFaaS 4th Birthday Mug](https://store.openfaas.com/collections/best-sellers-2020/products/openfaas-4th-birthday-celebration-mug)

We'll also be doing a prize draw!

**Comment by alexellis** [comment]
Hi everyone, please sign up for your place at the birthday event here -> https://forms.gle/hZBSpfXHxSoEEFbz5

Places will be limited, so make sure you can attend!

**Comment by Crispy-rw** [comment]
Is the zoom call going to be released after the celebration?

**Comment by alexellis** [comment]
Everyone who signed up has now been sent the invite link and entered into the prize draw.

The YouTube live will be at 1700-1800GMT today (Friday 18th)

Subscribe for the event here: 

https://youtu.be/eDDtlcAa6-U

**Comment by alexellis** [comment]
Thank you to everyone who made it. Use the link above for the replay of the live stream.
