### ISSUE TITLE
Setting up to point to both a local and remote instance

### ISSUE THREAD

**Issue by adityamookerjee** [openfaas/faas#1597]
## My actions before raising this issue
- [X ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X ] Read/searched [the docs](https://docs.openfaas.com/)
- [X ] Searched [past issues](/issues)

## Expected Behaviour
I would like to connect to both a local and remote instance at the same time and have parity between them.
So when I run `fans-cli` up, my code is deployed to both

## Current Behaviour
I am able to set a `OPENFAAS_URL` to my remote and local instances individually such that `faas-cli` login works with **one** at a time

## Possible Solution
- `OPENFAAS_URL` points to a list of instances?

## Context
I think it would be useful to have remote/local (i.e. `dev` / `prod`) parity

## Your Environment
Remote instance is a DigitalOcean 1-click OpenFaas droplet (which uses swarm, I believe)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
So when it comes to "deploying to production" which is what I think you're saying here. I would suggest you use something like Github Actions.

Then in your action simply have two URLs and run `faas-cli deploy -g URL1` followed by `faas-cli deploy -g URL2`

I would never recommend that you deploy your local development images to production without testing them. I don't quite get that workflow.

Closing as resolved. If you want to chat with the community, feel free to join Slack.
