### ISSUE TITLE
I've installed OpenFaas for my project and its working great but is there a workaround to change the authorization password for the Web UI which will really be a great help from the authors. Thanks in advance

### ISSUE THREAD

**Issue by premb98** [openfaas/faas#1602]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
/set title: Question - how do I change the password

**Comment by alexellis** [comment]
This is explained in the docs. https://docs.openfaas.com/deployment/troubleshooting/

Please don't raise issues to ask simple questions that are already clearly explained - it just detracts from the limited time we have to maintain this project.

If you like, join Slack to chat with the community.
