### ISSUE TITLE
How to go with the CRUD operation in OpenFaas? How many handlers do we need for each service or their CRUD operations?

### ISSUE THREAD

**Issue by rward27** [openfaas/faas#1604]
I am sorry that I have to write this as an issue but I didn't find more resources for openfaas anywhere and there are not many tutorials doing something more than just pulling pre-built templates and running them.

I was wondering if anyone here could guide me in figuring out how to go with Openfaas (on kubernetes) in performing CRUD operations. Basically I was searching a way to do this in Java but I get lost when it comes to Handler. Do I need to write multiple handlers for each CRUD operation and write specific operation inside each handler?

In case I have 20 Services in my project, each having CRUD operations, do I need to have 20x4=80 handlers for the those services and their CRUD operations? 
**Like suppose I have a function that does User Registration and another function for User Login, will this need 2 handlers?**

**Comment by alexellis** [comment]
Hi @rward27 we don't do technical support over GitHub, this is just for issues with the code.

That said, you may enjoy these resources:

https://www.openfaas.com/blog/serverless-single-page-app/
https://levelup.gitconnected.com/building-a-todo-api-in-golang-with-kubernetes-1ec593f85029
https://github.com/alexellis/crud-postgresql-nodejs-openfaas
https://github.com/alexellis/comment-vibes

And I'd suggest checking out the community page for how to get support and to chat with other users.

https://docs.openfaas.com/community/

Enjoy the holidays

**Comment by alexellis** [comment]
/set title: Support request: designing CRUD applications

**Comment by alexellis** [comment]
We also offer paid consulting that may save you some time and give you the direction you need to keep going on your own. You can book time from January. https://www.openfaas.com/support/
