### ISSUE TITLE
Missing documentation on how to deploy OpenFaaS on K8s with using the statically generated YAML files

### ISSUE THREAD

**Issue by tardigrde** [openfaas/faas#1609]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I followed the [docs](https://docs.openfaas.com/deployment/kubernetes/#install-the-openfaas-chart-using-arkade-or-helm) to deploy OpenFaaS in K8s. Here I only see options for `Helm` and `arcade` to install OpenFaaS. 
I want to install OpenFaaS without these tools, but there is no documentation on how can I install it `using the statically generated YAML files (not recommended)` (this line is listed as an option [in the docs](https://docs.openfaas.com/deployment/#kubernetes-recommended-for-production-and-for-work)). 

## Expected Behaviour

A line or chapter of documentation for deploying OpenFaaS without arkade or Helm.

## Current Behaviour

No docs like this.

## Context

I want to start using OpenFaaS on K8s without using arkade or Helm.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.12.21
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version:           20.10.1

* Are you using Kubernetes or faasd?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux, Debian 10 (Buster)

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

If asking questions regarding the docs should not go here, feel free to close/delete this issue, then I'd join the Slack channel if that is a more appropiate place to ask questions like this.

**Comment by Waterdrips** [comment]
Hey, thanks for looking into OpenFaaS and opening this issue. 

Out of interest, whats your use case for not using arkade/helm? 

If you want a set of static manifests to deploy using your CI platform then helm template can be used to generate the manifest based on the options provided. 

The faas-netes repo would be the place to look for the static yaml: https://github.com/openfaas/faas-netes/tree/master/yaml#yaml-development-only-instructions seems to give instructions.

**Comment by tardigrde** [comment]
Yes, thank you for your answer. 

I want to avoid using them, just because I'd rather leave out new tools from my setup as long as it is possible.
