### ISSUE TITLE
Openfass digitalocean error

### ISSUE THREAD

**Issue by markdessain** [openfaas/faas#1610]
Hey, I just tried to launch the OpenFaaS onto DigitalOcean from the [marketplace](https://marketplace.digitalocean.com/apps/openfaas). The droplet launches and shows the interactive prompt but fails after checking out this repository.

It is also mentioned in the docker swamp docs - https://docs.openfaas.com/deployment/docker-swarm/#20-deploy-the-stack

<img width="1095" alt="Screenshot 2020-12-26 at 08 53 24" src="https://user-images.githubusercontent.com/230477/103147663-da972f00-4757-11eb-9d90-16151c1c5e66.png">

It looks like the master branch is significantly different that the tagged branches such as 0.20.5. The `/deploy_stack.sh` file has been removed so one solution could be for the server to launch and checkout a tagged version rather than using the master branch?

-----

Workaround:

```
cd /home/openfaas-user/faas/
git checkout 0.20.5
./deploy_stack.sh
```

or use:

https://www.openfaas.com/blog/faasd-tls-terraform/

**Comment by alexellis** [comment]
We are no longer supporting Docker Swarm so I would suggest using faasd instead. We have tutorials for bash or terraform installation on DigitalOcean.

https://github.com/openfaas/faasd

Alex

**Comment by markdessain** [comment]
Is it worth removing it from the marketplace though? Just to avoid confusion if people try and use it.

**Comment by alexellis** [comment]
I think it would make more sense to update it to faasd to be honest. I'm trying to have a Christmas vacation, so just to let you know every reply here is sending me an alert and email. 

I'm sure this can wait until the new year. 

Thanks again for making us aware of the DO marketplace issue. It's not one of our official installation methods and our docs don't mention Swarm. For help getting started see: https://docs.openfaas.com/

**Comment by alexellis** [comment]
![marketplace](https://user-images.githubusercontent.com/6358735/103156899-6daa8600-47a5-11eb-95b1-3bfb69051298.png)

Submitted to DigitalOcean for review.

**Comment by TrikkStar** [comment]
> We are no longer supporting Docker Swarm so I would suggest using faasd instead. We have tutorials for bash or terraform installation on DigitalOcean.
> 
> https://github.com/openfaas/faasd
> 
> Alex

If that's the case you may also want to update your documentation to reflect this. As it currently stands the docs read like Swarm isn't recommended vs isn't supported anymore. (The docker guide is also broken as `deploy_stack.sh` no longer exists)
![image](https://user-images.githubusercontent.com/10501544/103367523-52849280-4a93-11eb-9704-cdcd287ff611.png)

**Comment by alexellis** [comment]
We are actually way ahead of you there we changed and merged this 15 days ago when the decision was made.

https://github.com/openfaas/docs/pull/249

I'll look into why GitHub or Netlify isn't updating the live site however.

**Comment by alexellis** [comment]
FYI: https://github.com/openfaas/docs/commit/7cb055abc2d2c3f419cb0b958bc86e9138d9e8c5

**Comment by alexellis** [comment]
We are now waiting on the DigitalOcean team (who I suspect, like many are enjoying their holidays) to come in and release the new version of the OpenFaaS Marketplace app.

I'm sorry that you saw an older copy of the docs, the publishing issue is now resolved.
