### ISSUE TITLE
openfaas cli install seems broken

### ISSUE THREAD

**Issue by antoine-em** [openfaas/faas#1613]
## My actions before raising this issue
- [ x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ x] Read/searched [the docs](https://docs.openfaas.com/)
- [ x] Searched [past issues](/issues)

The installation of openfaas cli `faas-cli` fails.

## Expected Behaviour

After running the command from the documentation the cli should be installed properly.

## Current Behaviour

On docker alpine
```
/ # curl -sSL https://cli.openfaas.com | sh
Finding latest version from GitHub
0.12.21socket-worker-5029ae85.js
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.21socket-worker-5029ae85.js/faas-cli as /tmp/faas-cli
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
```

On github action
```
Finding latest version from GitHub
0.12.21socket-worker-5029ae85.js
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.21socket-worker-5029ae85.js/faas-cli as /home/runner/work/emi_ops/emi_ops/etl_functions/faas-cli
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
Binary checksum didn't match. Exiting
Error: Process completed with exit code 1.
```

## Possible Solution
No idea.

## Context
Tested within docker containers both locally and on github action step.

## Your Environment

* Docker, Github action

**Comment by antoine-em** [comment]
Reported already in faas-cli repository
- https://github.com/openfaas/faas-cli/issues/856
- https://github.com/openfaas/cli.openfaas.com/pull/6

**Comment by alexellis** [comment]
Thanks for your report. We already have a fix up for this in a PR.
