### ISSUE TITLE
[Feature Request] Any plans to support deno?

### ISSUE THREAD

**Issue by betterRunner** [openfaas/faas#1621]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I don't know if is a suitable suggestion: can Deno.js be supported in OpenFaaS? Seems like Deno have a few advantages as a FaaS runtime environment such as TS support, url import, security and etc. whiling comparing to Node.js.

**Comment by LucasRoesler** [comment]
Deno is just an alternative node runtime, right? Support would simply require creating a new function template. Unfortunately, we aren't Deno experts, but if someone in the community created a template, we could promote it here

**Comment by betterRunner** [comment]
@LucasRoesler Got it, thanks for the reply. Let's see if anyone else is also interested in this feature.
