### ISSUE TITLE
list of openfaas blog posts are not updated for 2020 and 2021

### ISSUE THREAD

**Issue by nitishkumar71** [openfaas/faas#1622]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

List of blog posts are not updated in https://github.com/openfaas/faas/blob/master/community.md

## Expected Behaviour

List of blog posts should be updated till january 2021

## Current Behaviour

List of blog posts are not updated till 2021
## Possible Solution

Updated list of blog posts in https://github.com/openfaas/faas/blob/master/community.md

**Comment by alexellis** [comment]
Thank you - I don't think we needed an issue for this, but it's appreciated that you are being consistent.

**Comment by alexellis** [comment]
Came in today:

https://goncalo-a-oliveira.medium.com/serverless-with-openfaas-and-net-6a66b5c30a5f

We have some on the blog at openfaas.com/blog

In the "mentions/podcasts/videos" section we could add the book and its publishing date - I don't mind that being put down as 15th Jan. https://gumroad.com/l/serverless-for-everyone-else

**Comment by alexellis** [comment]
Two new videos

https://www.youtube.com/watch?v=mzuXVuccaqI

https://www.youtube.com/watch?v=nGOZLOjg5Zs

**Comment by nitishkumar71** [comment]
> Came in today:
> 
> https://goncalo-a-oliveira.medium.com/serverless-with-openfaas-and-net-6a66b5c30a5f
> 
> We have some on the blog at openfaas.com/blog
> 
> In the "mentions/podcasts/videos" section we could add the book and its publishing date - I don't mind that being put down as 15th Jan. https://gumroad.com/l/serverless-for-everyone-else

Are there any more links which are not included from openfaas.com/blog?
