### ISSUE TITLE
Integration testing files missing for gateway

### ISSUE THREAD

**Issue by Space-Banana-42** [openfaas/faas#1625]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

When we try to run test for PR of this issue: https://github.com/openfaas/faas/issues/1624,  we followed instructions here: https://github.com/openfaas/faas/blob/master/gateway/tests/integration/README.md.
However, we noticed that required file "deploy_stack.sh" and "docker-compose.yml" has been removed since this PR https://github.com/openfaas/faas/pull/1608/files

## Expected Behaviour
Proper guideline for Integration test. 

## Current Behaviour
Current [guideline for Integration testing of gateway](https://github.com/openfaas/faas/blob/master/gateway/tests/integration/README.md) is wrong due to removal of "deploy_stack.sh" and "docker-compose.yml" since this PR https://github.com/openfaas/faas/pull/1608/files

## Possible Solution
Can we create new image from our side on do the integration test with our system? And we are happy to contribute to new guideline.

## Context
When we try to run test for PR of this issue: https://github.com/openfaas/faas/issues/1624, we notice that.

**Comment by alexellis** [comment]
The integration tests are run through the certifier project, which is a full end to end suite. The commit notes that removed the integration tests from the gateway mention that they moved there.

https://github.com/openfaas/certifier
