### ISSUE TITLE
Using custom template in openfaas cloud

### ISSUE THREAD

**Issue by mbuczkowski-gm** [openfaas/faas#1631]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Current Behaviour

I am using on-prem openfaas cloud deployment and I want to modify a Dockerfile in python3-http template. I'm not sure how to achieve this goal. All the tutorials focused on deploying using faas-cli (e.g `faas-cli up`). I would like to use custom Dockerfile with GitHub webhook, which works just fine for basic python3-http template. I either get:
```
missing language template: Not supported language: python3-http-test for function: query
```
or 
```
unsupported custom "templates" folder
```
when I tried to include my custom template alongside the handler files.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker 19.03.15

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? OpenFaas Cloud on prem installed with ofc-bootstrap

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi, the openfaas-cloud project is archived. Feel free to see the #openfaas-cloud channel on Slack for more.

Alex

**Comment by alexellis** [comment]
https://slack.openfaas.io/
