### ISSUE TITLE
Deploy OpenFaaS to minikube

### ISSUE THREAD

**Issue by zhangwinning** [openfaas/faas#1632]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Using https://medium.com/faun/getting-started-with-openfaas-on-minikube-634502c7acdf to Deploy OpenFaaS to minikube

when invoke step 11
![image](https://user-images.githubusercontent.com/23034399/107976032-e7b3fa00-6ff3-11eb-9322-b3ea6e67503d.png)

## Expected Behaviour

Connect correctly

## Current Behaviour

```
➜  faas echo -n $PASSWORD | faas-cli login -g http://$OPENFAAS_URL -u admin --password-stdin
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: http://192.168.49.2:31112. Get "http://192.168.49.2:31112/system/functions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

 Deploy OpenFaaS to minikube

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
➜  faas faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  3cfd4a0fad765349f758a5ee42b12412bce0be2e
 version: 0.13.4
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
➜  faas docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

using OpenFaaS on Kubernetes 
* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Thanks for your interest in OpenFaaS. It would appear that you have a networking issue with your computer, or that OpenFaaS is not correctly deployed.

I would recommend you look at our docs for deploying OpenFaaS to Kubernetes and perhaps try something like KinD instead or Multipass.

https://docs.openfaas.com/deployment/

Feel free to join Slack if you need technical support.
