### ISSUE TITLE
Per #1052 how can I provide a correlation id for async function calls?

### ISSUE THREAD

**Issue by klmcwhirter** [openfaas/faas#1634]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

When making asynchronous API calls it is important to be able to specify a Correlation ID so when the response comes it is determinant which API call to which is being referred.

## Expected Behaviour
Either something like an X-Correlation-Id header, or payload pass thru should be allowed for so that a response can be related to a request.

## Current Behaviour
Per [Async](https://docs.openfaas.com/reference/async/) only the following headers are provided:
[LINK](https://docs.openfaas.com/reference/async/#callback-request-headers)

## Possible Solution
I do not want to get in the way of the creativity of your contributors. You guys are working some magic.

But it seems the header approach would make more sense. _Which part of the request payload should pass thru?_ Seems like the payload pass thru approach might be a can of worms.

Please accept some header containing the correlation id that would pass thru _as-is_ to the response.

Since a correlation id is an opaque value, any amount of needed data could be included (e.g., the basic Authorization header). But the caller could just include a client-side generated UUID as well. _This is what I usually do._

**Comment by klmcwhirter** [comment]
See the last sentence of this [comment](https://github.com/openfaas/faas/issues/1052#issuecomment-457519577) in 1052.

**Comment by alexellis** [comment]
I'm not sure I understand the usecase here. Can you be more explicit about the problem you're trying to solve? I appreciate you are trying to be vague and generic, but I'm missing context.

Why is it that your cannot use X-Call-Id to correlate your requests and responses?

**Comment by klmcwhirter** [comment]
X-Call-Id is NOT generated by the caller - a HUGE difference.

Think about your consumers case for a moment ...


A number of calls (say 100 is typical) how would the caller of these async operations know how to process them?

Typically we would persist the correlation-id along with other items pertinent to the call (for example the other data relationships that have some business meaning, but are not related to the API call - in one of our cases, account-manager relationships where trades are reportable to the EU regulatory body). In a case like this we need to know which trade for which relationship is being processed.

It is quite common in a messaging / API scenario to rely on a correlation-id to tie things together. The use case does not really matter. This is a long held, trusted design pattern. To be honest, i am surprised you are not familiar with this need.

[Enterprise Integration Patterns and Correlation iD](https://www.enterpriseintegrationpatterns.com/ramblings/09_correlation.html)

This is a deal breaker in most enterprises where async operations is the norm.

**Comment by alexellis** [comment]
I still don't understand why the X-Call-Id, that you receive upon submission isn't working out for you?

What's the pain it's causing? What's the weakness?

I'm not sure if you're aware, but you can pass your own body and headers into any function call. Is that what you're asking for?

**Comment by klmcwhirter** [comment]
Again I cite the Enterprise Integration best practices,

Alex, you are certainly a smart guy.

But if you do not follow the proven best practices in the industry you will have a hard sell ahead of you.

What you do with your product is certainly up to you.

But if you are trying to sell a reference implementation for companies like Amazon to follow, then I think you probably should adhere to industry best practices.

I have 40+ years experience. Yep, a gray beard. So maybe my time has come and gone. But i encourage you to listen to someone who has spent a number of years as a salmon swimming upstream.

Again, love what you are doing here,

**Comment by alexellis** [comment]
I'm just trying to understand what is missing here.

You can pass in your own IDs via headers, that can be used for your preexisting "correlation ID", you also have access to the HTTP path, querystring and body.

The X-Call-Id gives a further element of traceability. 

It seems like you are tell us that what you're asking for cannot be done, but I would like to know what you've tried, and why it didn't work? From what I can see we have answered the question and what you've asked for is possible. Feel free to re-open if you feel otherwise, or need further assistance.

**Comment by klmcwhirter** [comment]
I am open to a private conversation.  But let's stop this here.

**Comment by alexellis** [comment]
> Either something like an X-Correlation-Id header, or payload pass thru should be allowed for so that a response can be related to a request.

You can do this today, so I am not sure how to read your responses, but it seems like you may feel like you are being argued with? That's not the case.

What you've asked for is available and possible. Feel free to try it out - if in doubt, [feel free to get in touch](https://openfaas.com/support/).
