### ISSUE TITLE
faas-cli deployment with tunneling successfully but not done

### ISSUE THREAD

**Issue by krotofil** [openfaas/faas#1635]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

## Expected Behaviour
We will deploy an test function for our new openfaas 
kubenetes environment

## Current Behaviour
1. First of all, 
we have an Kubernetes environment, which we tunneling the
for example: 
`kubectl port-forward -n openfaas svc/gateway 8080:8080`
openfass gui to following adress -> http://127.0.0.1:8083/ui/ -> we successfully login into UI
2. Now we do the steps by using the go templates from  example to deploy the function.
```
faas-cli new --lang go gohash
faas-cli build -f gohash.yml
```
We editing these file gohash.yml for our env:
```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  gohash:
    lang: go
    handler: ./gohash
    imagePullSecrets: acr-pull-secret
    image: xxxxxxxxx.azurecr.io/gohash:latest
    imagePullPolicy: IfNotPresent
```
3. Now we running the build comand and it works fine
```
Successfully built 352903fe2348
Successfully tagged ecedevweubscapacr.azurecr.io/gohas:latest
Image: ecedevweubscapacr.azurecr.io/gohash:latest built.
```

4. then we push the Image into Repo - works fine
   we see the Image located by our container registry

5. Deploying function
```

 faas-cli deploy -f gohash.yml
Deploying: gohash.
Function gohash already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://127.0.0.1:8083/function/gohash.openfaas-fn
```

we are very surprised at the statement that the deployment is already available,
but we don´t found any containers running or find the function in our openfaas Gui.

## Context
We installing for testing an locally openfaas with locally container registry, but
ther Error or Issue not happends there. The gateway are localhost too, on both
env.

## Your Environment
CLI:
 commit:  ec002af3c1ef848c507080a83a4e5c6ec6dab308
 version: 0.13.5
Your faas-cli version (0.13.5) may be out of date. Version: 0.13.6 is now available on GitHub.

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
yes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux ubuntu

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Thanks for using openfaas.

I'm going to close this because it looks like you didn't run `push`, which is a required part of the workflow.

For technical support, we would recommend first reading the [docs](https://docs.openfaas.com/) (perhaps you have missed something on private registries) and second joining Slack and asking the community to help you.

**Comment by alexellis** [comment]
You ticked to say you've followed the troubleshooting guide, but didn't provide any console output, so I'm not sure if you followed the same one as we have made available.

You will probably find the answer to your issue by following this:

https://docs.openfaas.com/deployment/troubleshooting/#troubleshoot-kubernetes

**Comment by krotofil** [comment]
sorry but i worte, that our Image are available in our Azure Container registry, if the image are not available, we getting another output. 
i worte you same Outputs and we make following example four your site.
example -> https://blog.alexellis.io/serverless-golang-with-openfaas/

i getting the yml File and outputs from only steps into the Issue?

**Comment by alexellis** [comment]
It seems like you missed the advice I gave you in the previous message.

Your output shows that you skipped the `$ faas-cli push -f gohash.yml` step. You need that, you cannot skip it.

If you are using a private registry, you need to read the docs on how to configure that. https://docs.openfaas.com/deployment/kubernetes/#use-a-private-registry-with-kubernetes

Follow the troubleshooting guide:

https://docs.openfaas.com/deployment/troubleshooting/#troubleshoot-kubernetes

We don't mind pointing people in the right direction, but users need to be willing to help themselves and use the materials we have already provided.

**Comment by krotofil** [comment]
here are my output:

```
cp@ncp-virtual-machine:/mnt/hgfs/SCAP/services/faas$ faas-cli build -f hello.yml
[0] > Building hello.
Clearing temporary build folder: ./build/hello/
Preparing: ./hello/ build/hello/function
Building: ecedevweubscapacr.azurecr.io/hello:latest with java11 template. Please wait..
Sending build context to Docker daemon  142.3kB
Step 1/30 : FROM openjdk:11-jdk-slim as builder
 ---> e0236d4937b0
Step 2/30 : ENV GRADLE_VER=6.1.1
 ---> Using cache
 ---> 3eabbfa27f86
Step 3/30 : RUN apt-get update -qqy   && apt-get install -qqy    --no-install-recommends    curl    ca-certificates    unzip
 ---> Using cache
 ---> e926317752c9
Step 4/30 : RUN mkdir -p /opt/ && cd /opt/     && echo "Downloading gradle.."     && curl -sSfL "https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip" -o gradle-$GRADLE_VER-bin.zip     && unzip gradle-$GRADLE_VER-bin.zip -d /opt/     && rm gradle-$GRADLE_VER-bin.zip
 ---> Using cache
 ---> f690cf81996f
Step 5/30 : ENV GRADLE_HOME=/opt/gradle-$GRADLE_VER/
 ---> Using cache
 ---> ddb87b1f312f
Step 6/30 : ENV PATH=$PATH:$GRADLE_HOME/bin
 ---> Using cache
 ---> 0ff55b37fd9e
Step 7/30 : RUN mkdir -p /home/app/libs
 ---> Using cache
 ---> 27cbdf168a56
Step 8/30 : ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"
 ---> Using cache
 ---> ccf7f87fe6d7
Step 9/30 : WORKDIR /home/app
 ---> Using cache
 ---> 2cdc96bc8c03
Step 10/30 : COPY . /home/app/
 ---> Using cache
 ---> e47c71d67316
Step 11/30 : RUN gradle build
 ---> Using cache
 ---> 248dc7b2a9d9
Step 12/30 : RUN find .
 ---> Using cache
 ---> c87005027c20
Step 13/30 : FROM openfaas/of-watchdog:0.7.6 as watchdog
 ---> 7580c7c70fce
Step 14/30 : FROM openjdk:11-jre-slim as ship
 ---> 33964aae8141
Step 15/30 : RUN apt-get update -qqy   && apt-get install -qqy    --no-install-recommends    unzip
 ---> Using cache
 ---> 93d5f920baca
Step 16/30 : RUN addgroup --system app     && adduser --system --ingroup app app
 ---> Using cache
 ---> 9dcb2c05e754
Step 17/30 : COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
 ---> Using cache
 ---> d539c79f1fc0
Step 18/30 : RUN chmod +x /usr/bin/fwatchdog
 ---> Using cache
 ---> 54335e845b83
Step 19/30 : WORKDIR /home/app
 ---> Using cache
 ---> 02fab28cce19
Step 20/30 : COPY --from=builder /home/app/function/build/distributions/function-1.0.zip ./function-1.0.zip
 ---> Using cache
 ---> 62d62da68003
Step 21/30 : user app
 ---> Using cache
 ---> 31b38cded21f
Step 22/30 : RUN unzip ./function-1.0.zip
 ---> Using cache
 ---> 01332025a6dc
Step 23/30 : WORKDIR /home/app/
 ---> Using cache
 ---> a6550cc32afe
Step 24/30 : ENV upstream_url="http://127.0.0.1:8082"
 ---> Using cache
 ---> a8514278f96e
Step 25/30 : ENV mode="http"
 ---> Using cache
 ---> a00c9f2f3b43
Step 26/30 : ENV CLASSPATH="/home/app/function-1.0/function-1.0.jar:/home/app/function-1.0/lib/*"
 ---> Using cache
 ---> 0bb8d139e45d
Step 27/30 : ENV fprocess="java -XX:+UseContainerSupport com.openfaas.entrypoint.App"
 ---> Using cache
 ---> dbc4aaca63f4
Step 28/30 : EXPOSE 8080
 ---> Using cache
 ---> 4f714f9af173
Step 29/30 : HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1
 ---> Using cache
 ---> 63abd0fab711
Step 30/30 : CMD ["fwatchdog"]
 ---> Using cache
 ---> 352903fe2348
Successfully built 352903fe2348
Successfully tagged ecedevweubscapacr.azurecr.io/hello:latest
Image: ecedevweubscapacr.azurecr.io/hello:latest built.
[0] < Building hello done in 0.38s.
[0] Worker done.

Total build time: 0.38s
ncp@ncp-virtual-machine:/mnt/hgfs/SCAP/services/faas$ faas-cli push -f hello.yml
[0] > Pushing hello [ecedevweubscapacr.azurecr.io/hello:latest].
The push refers to repository [ecedevweubscapacr.azurecr.io/hello]
197c5b365e6e: Layer already exists 
59d017535721: Layer already exists 
c8e21fe2bc00: Layer already exists 
1d84988ad82c: Layer already exists 
dbb4b7b846a3: Layer already exists 
027810cd859b: Layer already exists 
513adf10febc: Layer already exists 
08664b16f94c: Layer already exists 
9eb82f04c782: Layer already exists 
latest: digest: sha256:3fbc83b1ae3d3c22699c1d7d1df887e406a7f7692174e5a74d494043f69957ad size: 2423
[0] < Pushing hello [ecedevweubscapacr.azurecr.io/hello:latest] done.
[0] Worker done.
ncp@ncp-virtual-machine:/mnt/hgfs/SCAP/services/faas$ faas-cli deploy -f hello.yml
Deploying: hello.
Function hello already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://127.0.0.1:8083/function/hello.openfaas-fn

ncp@ncp-virtual-machine:/mnt/hgfs/SCAP/services/faas$ 
```

No Containers or functinos found into openfaas gui

**Comment by alexellis** [comment]
You've now confirmed that you did a push, thank you.

Now it's the third time I've said it, but please follow the troubleshooting guide:

https://docs.openfaas.com/deployment/troubleshooting/#troubleshoot-kubernetes

And set up your private registry auth.

I haven't seen any evidence that you've done either.

https://docs.openfaas.com/deployment/troubleshooting/#troubleshoot-kubernetes

**Comment by krotofil** [comment]
you see the pushing are successfully Deplyoment,tooo 
-> see

ncp@ncp-virtual-machine:/mnt/hgfs/SCAP/services/faas$ faas-cli deploy -f hello.yml
Deploying: hello.
Function hello already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://127.0.0.1:8083/function/hello.openfaas-fn

ncp@ncp-virtual-machine:/mnt/hgfs/SCAP/services/faas$ 

but we don´t habe any container which are existing -> 
the URL http://127.0.0.1:8083/function/hello.openfaas-fn gets an 404 NOT an 200 ??

**Comment by krotofil** [comment]
thx a lot, but the troubleshooting guide can help me, if the deployment says 200 but we have any containers deployed on our openfaas-fn

**Comment by alexellis** [comment]
You need to run every command in that section. If you ask for help, then you need to follow what you've been told.

**Comment by alexellis** [comment]
Have you set up your private authentication yet as per the docs?

I'm going to close this issue. You have everything you need, you just need to follow the instructions given.

Private registries need auth. That's not a bug and it's documented. If your function isn't running for any other reason, the commands that I linked you to for namespace events, to describe the deployment and to find any logs will give you any answers you require.
