### ISSUE TITLE
[FEATURE REQUEST] hot reload functions

### ISSUE THREAD

**Issue by mstrYoda** [openfaas/faas#1636]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

## Expected Behaviour

What about supporting hot-reload functionality for local test purposes? So this allows faster execution cycle for test purposes.

I would like to test my function without rebuilding&pushing an image on every change something like below:

```
faas-cli up-test my-function -f function.yaml 
```

I am imagining a behavior like skaffold does.

## Current Behaviour

Currently we need to run faas-cli up and it builds & pushes docker image to registry.

## Possible Solution

When we run `faas-cli up-test -f function.yml` it can do the following steps:

- spawn a pod with a test image like golang:alpine-x
- watch the current directory
- push changes to test image
- run new codes

I am not aware of internals of openfaas so the solution I describe above may sound meaningless. But I believe that functionality can supported.

## Context

Testing etc.

**Comment by alexellis** [comment]
A summary of the discussion on Slack:

There is a WIP but abandoned PR (no changes in 1 year) in the faas-cli for this, to rebuild upon save. Some users also use tilt for the same purpose. https://github.com/openfaas/faas-cli/pull/763

A live-reload feature is beyond the scope of the current roadmap so I'll close this issue out and point you at something like Okteto - they have a few guides for "hot reload" where they do relatively insecure tricks that you won't want in production, but can make development faster. They also have a good debug story.

For the fastest development you may want to build / run the container locally without deploying it to openfaas. Here's an example with the node12 template: https://simonemms.com/blog/2020/08/12/live-reload-for-openfaas/

You should also consider using unit tests to verify your code before doing a build. That's one of the fastest options available.
