### ISSUE TITLE
Enable Namespace dropdown by default

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/faas#1640]
## Expected Behaviour

The gateway should always show the namespace dropdown even when only one exists.

We also should add a link (possibly on a ? icon) to point to the multiple namespaces docs. 

## Current Behaviour

NS dropdown only shows on > 1 namespace

**Comment by Waterdrips** [comment]
https://github.com/openfaas/faas/blob/master/gateway/assets/index.html#L57-L64

We should set the `ng-show="allNamespaces.length > 1"` ng-show to true (or remove it totally?? ) and always show the namespace dropdown.

**Comment by Waterdrips** [comment]
Then create a link below ?? (as a new item in the sidebar) that was `multiple-namespace` docs

**Comment by alexellis** [comment]
We'll focus energy on the new dashboard now and close this issue.
