### ISSUE TITLE
Openfaas tutorial for full stack deploy

### ISSUE THREAD

**Issue by GiannisStasinakis82** [openfaas/faas#1642]
Good evening.
I have to build a full stack using openFaas and swarm for my class project. Since I need to create a chain of functions, is there any tutorial to study in order to deploy this chain of functions using openfaas and docker swarm ?

**Comment by alexellis** [comment]
Hi @GiannisStasinakis82,

Your best materials are already outlined in the documentation in the workshop and LF course "Introduction to Serverless"

GitHub issues are only for problems with the codebase, not for questions that are already answered in materials we have made clearly available. Please do some of your own research and feel free to join Slack if you want to chat to other users.

Alex
