### ISSUE TITLE
Make GH Actions consistent and easier to test for contributors

### ISSUE THREAD

**Issue by cpanato** [openfaas/faas#1643]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
Some GitHub actions are not following the pattern that was defined like https://github.com/openfaas/faas/tree/master/.github/workflows

Especially in the `publish` workflow that has the hard-coded registry. which makes it a bit harder for community contributors to test the container build/push because they will not have access to the Openfaas registry.
So the idea is to make the publish workflow similar to others in the org

I've review all the repositories in the org and the following repositories we need to change:

@cpanato will take:
 - [ ] https://github.com/openfaas/ingress-operator - https://github.com/openfaas/ingress-operator/pull/44
 - [ ] https://github.com/openfaas/faas-netes - https://github.com/openfaas/faas-netes/pull/785
 - [ ] https://github.com/openfaas/faas-cli - need to make it similar to the others - https://github.com/openfaas/faas-cli/pull/881
 
@developer-guy can take:
 - [ ] https://github.com/openfaas/nats-connector - https://github.com/openfaas/nats-connector/pull/23
 - [ ] https://github.com/openfaas/cron-connector - https://github.com/openfaas/cron-connector/pull/16
 - [ ] https://github.com/openfaas/mqtt-connector - https://github.com/openfaas/mqtt-connector/pull/6

@developer-guy show interest to help as well and we will split the work

**Comment by developer-guy** [comment]
thank you @cpanato, really appreciate for analysis.

**Comment by Xorima** [comment]
Hey, I'm a follower of these projects but not a contributor, were you aware of: https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/ which may help with the standardisation and consistency of your actions?

**Comment by alexellis** [comment]
Thanks for the input @Xorima 

I think this is mostly done now, if anything is remaining, feel free to ping me on that Issue / PR.
