### ISSUE TITLE
How to build for different architecture, if using M1

### ISSUE THREAD

**Issue by Tarang** [openfaas/faas#1645]
I've searched around and tried `faas-cli` with lots of build arguments. This is a related issue but different: https://github.com/openfaas/faas-netes/issues/232

## My actions before raising this issue
- [X ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ X] Read/searched [the docs](https://docs.openfaas.com/)
- [ X] Searched [past issues](/issues)

I have a python project with OpenFaaS. I am trying to deploy it and it works, but so long as I use an x86 based cpu to run the `faas-cli up` command. If I run the same command on an M1 Apple CPU, it also deploys fine but it will be in an infinite Crash Loop (CrashLoopBackOff) where the error in the logs is ```standard_init_linux.go:N: exec user process caused "exec format error"```

The issue here is Docker just came out for M1 Macs and if you're using certain python imports such as `import json`, Docker builds the python parts using an `arm64` build instead of an `amd64`/`x64` based build.

## Expected Behaviour
- The expected behaviour is after deploying the function should start up and run without crashing.
- The ideal change is a build flag lets you use the new docker `buildx` system to build for a different architecture.

## Current Behaviour
- `faas-cli up -f xxx.xaml` on an m1 based machine using the latest M1 Docker.
- The resulting container will be in a `CrashLoopBackOff`
- faas-cli uses the traditional docker build engine

## Are you a GitHub Sponsor (Yes/No?)
I tell people to use OpenFaas alot

Check at: https://github.com/sponsors/openfaas
- [X ] Yes
- [ ] No

## List All Possible Solutions and Workarounds
- Build on an x86 machine

## Which Solution Do You Recommend?
- Use `docker buildx` instead of `docker build` under the hood and allow passing in flags to target a different architecture

## Steps to Reproduce (for bugs)

1.  ` faas-cli template store pull python3-debian`
2.  `faas-cli new test --lang  python3-debian`
3.  Add `import json` to the `handler.py` file
4.  (Configure test.yaml file for your gateway)
5. `faas-cli up -f test.yaml` on a M1 based Mac
6. Check status of pods with `kubectl get pods`

## Context
Not able to use openfaas on an Apple Silicon Based Mac to deploy images

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```faas-cli version                                        14:49:28
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2cec97955a254358de5443987bedf8ceee272cf8
 version: 0.13.9
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
With Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Mac OS

**Comment by alexellis** [comment]
Hi,

Thanks for your interest in the project.

if you are building on an ARM64 computer (Docker for Mac on M1, is actually a Linux ARM64 VM), then you need to use `faas-cli publish` and `faas-cli deploy` after that. You do the same thing on a Raspberry Pi targeting a PC or a PC targeting a Raspberry Pi.

Please see `faas-cli publish --help` messages for more details.

For more details:

https://docs.openfaas.com/cli/build/

https://www.openfaas.com/blog/openfaas-flask/

Glad that we could help, and do see the note about becoming a sponsor so we can continue to serve the community and help users like yourself.

Alex
