### ISSUE TITLE
NATS Streaming server deprecation

### ISSUE THREAD

**Issue by rtisma** [openfaas/faas#1663]
As shown in https://github.com/nats-io/nats-streaming-server, the nats-stream-server is being deprecated, and will receive updates until 2023. 

Is there a plan to accommodate this change? Possibly integrate JetStream?

**Comment by alexellis** [comment]
Hi @rtisma we will deal with this in due course. OpenFaaS Pro customers will get JetStream support first, but we still have two years before it's fully deprecated.

Alex

**Comment by bmarick** [comment]
@alexellis 

Any update on this?
NATS Steaming is now fully deprecated.

**Comment by alexellis** [comment]
We have provided a fully tested NATS JetStream implementation, our OpenFaaS Standard customers are already using it in production.

Docs: https://docs.openfaas.com/openfaas-pro/jetstream/

Comparison: https://openfaas.com/pricing/

Happy to talk or give you a free trial, just reach out to us.
