### ISSUE TITLE
after deploying openfaas image to opensift getting Error: Cannot find module 'aws-sdk'

### ISSUE THREAD

**Issue by dhan1978** [openfaas/faas#1666]
Hi,
i have made image of lambda function by using openfaas and deploy on openshift getting below error

exit status 1
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'aws-sdk'
Require stack:
- /home/app/function/node_modules/aws-param-store/lib/ssm.js
- /home/app/function/node_modules/aws-param-store/lib/param_query.js
- /home/app/function/node_modules/aws-param-store/lib/index.js
- /home/app/function/system_parameter_readers.js
- /home/app/function/constants.js
- /home/app/function/handler.js
- /home/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/app/function/node_modules/aws-param-store/lib/ssm.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/app/function/node_modules/aws-param-store/lib/ssm.js',
    '/home/app/function/node_modules/aws-param-store/lib/param_query.js',
    '/home/app/function/node_modules/aws-param-store/lib/index.js',
    '/home/app/function/system_parameter_readers.js',
    '/home/app/function/constants.js',
    '/home/app/function/handler.js',
    '/home/app/index.js'
  ]
}

Dockerfile is given below

FROM --platform=${TARGETPLATFORM:-linux/amd64} ghcr.io/openfaas/classic-watchdog:0.1.5 as watchdog
FROM --platform=${TARGETPLATFORM:-linux/amd64} node:12-alpine as ship

ARG TARGETPLATFORM
ARG BUILDPLATFORM

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

RUN addgroup -S app && adduser app -S -G app

WORKDIR /root/

# Turn down the verbosity to default level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN mkdir -p /home/app

# Wrapper/boot-strapper
WORKDIR /home/app
COPY package.json ./
#RUN npm install
#RUN npm install aws-sdk
# This ordering means the npm installation is cached for the outer function handler.
RUN npm i --production

# Copy outer function handler
COPY index.js ./

# COPY function node packages and install, adding this as a separate
# entry allows caching of npm install runtime dependencies
WORKDIR /home/app/function
COPY function/*.json ./

RUN npm install aws-sdk
RUN npm install

RUN npm i --production || :

# Copy in additional function files and folders
COPY --chown=app:app function/ .
WORKDIR /home/app/

RUN chmod -R 777 ./function/node_modules

# chmod for tmp is for a buildkit issue (@alexellis)
RUN chmod +rx -R ./function \
    && chown app:app -R /home/app \
    && chmod 777 /tmp

USER app

ENV cgi_headers="true"
ENV fprocess="node index.js"
EXPOSE 8080

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"] 

package.json is given below

{
  "name": "function",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "scripts": {
	"start": "node ./bin/www",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
  "dependencies": {
	"aws-sdk": "2.990.0",
    "jsonwebtoken": "^8.5.0",
    "aws-param-store": "^2.1.0",
    "hashmap": "^2.3.0"
  }
}
calling file is like given code
const awsParamStore = require('aws-param-store');
var HashMap = require('hashmap');

	        let parameters = awsParamStore.getParametersByPathSync(resourcePath, { WithDecryption: true, region: resourceRegion });
       let results = awsParamStore.getParameterSync(resourcePath, { WithDecryption: true, region: resourceRegion });
let parameters = awsParamStore.getParametersSync(resourcePath, { WithDecryption: true, region: resourceRegion });

may i know resolution .
---------------------------------------------------------------------------------------------------
#

## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by dhan1978** [comment]
Steps to Reproduce (for bugs)
1) deploy image mourya1978/mourya:iatm-core-of-lambda on openshift
2) open router url and get issue.
3) username and password of Dockerhub willbe provided over mail mr.mourya1978@gmail.com 
4) please check all library present inside function

**Comment by alexellis** [comment]
Hi there,

Thanks for your interest in OpenFaaS.

Whilst we cannot support individuals directly with their use of openfaas, I would suggest you try my eBook on OpenFaaS which has examples with Node.js including how to add npm modules.

Once you have a copy, let me know how you get on. I can also send you a working example with the AWS SDK.

Alex
