### ISSUE TITLE
Long Time running function infinite loop when call in asynchronous mode 

### ISSUE THREAD

**Issue by seb-835** [openfaas/faas#1673]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
long time running function should be only run once when async called and not run in infinite loop  ! 

## Current Behaviour
I got a long time running function, when i call it  through  \async-function\  ,  when the function is completed, it restart, redo the job, then restart again, and again .... only way to stop it is to  delete the function. 

## Are you a GitHub Sponsor (Yes/No?)
Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)
1.  Build /Deploy function
```
 > cat faas-fct/fn_test.yml 
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080  

functions:
  echoit:
    lang: dockerfile
    image: alpine:latest
    fprocess: "tee"
    skip_build: true
  sleep:
    lang: dockerfile
    image: alpine:latest
    fprocess: sleep 300
    skip_build: true

> faas-cli deploy -f  fn_test.yml 
```

2.  call function in async mode with a  callback
```
> curl http://127.0.0.1:8080/async-function/sleep -d {""} -H "X-Callback-Url: http://gateway.openfaas.svc.cluster.local:8080/function/echoit"
```
3. watch log of pod echoit or sleep  ..and see it looping...

ECHOIT :
```
2021/10/29 13:18:03 Forking fprocess.
2021/10/29 13:18:03 Wrote 32 Bytes - Duration: 0.000897 seconds
2021/10/29 13:23:03 Forking fprocess.
2021/10/29 13:23:03 Wrote 32 Bytes - Duration: 0.000924 seconds
2021/10/29 13:28:03 Forking fprocess.
2021/10/29 13:28:03 Wrote 32 Bytes - Duration: 0.000833 seconds
```
SLEEP:
```
021/10/29 13:10:36 Metrics listening on port: 8081
2021/10/29 13:13:03 Forking fprocess.
2021/10/29 13:18:03 Wrote 0 Bytes - Duration: 300.001868 seconds
2021/10/29 13:18:03 Forking fprocess.
2021/10/29 13:23:03 Wrote 0 Bytes - Duration: 300.001025 seconds
2021/10/29 13:23:03 Forking fprocess.
2021/10/29 13:28:03 Wrote 0 Bytes - Duration: 300.001049 seconds
2021/10/29 13:28:03 Forking fprocess.
```

4. The only way to stop it : 
 ```
> faas-cli delete sleep
```
and see callbacks of failed retry in echoit:
```
2021/10/29 13:32:09 Forking fprocess.
2021/10/29 13:32:09 Wrote 103 Bytes - Duration: 0.000770 seconds
2021/10/29 13:32:09 Forking fprocess.
2021/10/29 13:32:09 Wrote 103 Bytes - Duration: 0.000676 seconds
```

## Notes:
when run in normal mode (with function/gateway timeout correctly set ), 
``` 
> curl http://127.0.0.1:8080/function/sleep -d {""} 
```
the function run only once.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  77ad215bcc6291dbf72c73caffe4d76aa2bb6fb1
 version: 0.13.11
Handling connection for 8080

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.21.1
 sha:     a9a77f0ecaa8d5a242606ceaf6deed5d8703249b

Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.13.8 
 sha:           c0a8c3cba4156fac9847953a83cea03bf54e42ef
```

* Are you using OpenFaaS on Kubernetes : YES

* Operating System and version : LINUX

**Comment by alexellis** [comment]
Hi, thanks for your interest in openfaas.

This is working as designed, you must extend or limit the timeouts for your installation.

https://docs.openfaas.com/tutorials/expanded-timeouts/

If you need any further support with configuring openfaas, don't hesitate to reach out https://openfaas.com/support/

**Comment by alexellis** [comment]
/set title: Asynchronous task was retried when not ack'd within the ack window
