### ISSUE TITLE
Unable to determine how functions or subsystems can be configured.

### ISSUE THREAD

**Issue by MichaelHindley** [openfaas/faas#1678]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
Configuring faas, I want to see what options are available, so that I can configure my faas correctly and see which type of workloads I could run.

Extended expectation is to see what schemas I can interact with when implementing openfaas as a platform to run code on. 

## Current Behaviour
Assumptions:
Documentation for faas yml own config schema does not exist.
Documentation for openfaas own http api's does not exist.
Documentation for how to configure NATS does not exist.

Documentation of faas-cli is _superb_ and a stark contrast to the other schemas a user can interact with.

Understanding how these buildings blocks can be configured is fundamental in an architects technical evaluation when comparing openfaas to other tools that are feasible for the project. Are they available in a readable manner somewhere apart from source? :)

## Are you a GitHub Sponsor (Yes/No?)
*Given this request for help, how are you supporting the project?*
No

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds
Read openfaas/faas golang sourcecode to find out what you can configure in the different parts of the openfaas stack.

## Which Solution Do You Recommend?
N/A

## Steps to Reproduce (for bugs)
Kind of n/a or I'm just missing it completely :)
(you can follow this list for almost any building block of openfaas that relies on users inputting values to a schema I think?)

1. Do Workshop at https://github.com/openfaas/workshop
2. Try to read the docs about the things being done in the workshop, realise docs don't exist for function config
4. Example: https://github.com/openfaas/workshop/blob/master/lab8.md#extend-timeouts-with-read_timeout
5. Above example references several timeout related config parameters that can be passed to the function.
6. Try to look for `exec_timeout` at https://docs.openfaas.com/ and find nothing
7. Find PR for the feature at https://github.com/openfaas/faas/pull/540.
8. See PR mentions explicitly that "docs do not need to be updated".
9. Wonder if docs exist somewhere?

## Context
I'm evaluating the feasibility of the platform to serve features in high-performance high-security environments where stability, security and compliance is mission critical. 

As an example, here is k-natives schema for the eventing-api: https://knative.dev/docs/reference/api/eventing-api/
Notice the schema lists all available options, descriptions and all references are linked allowing for easy navigation and simplifying the due diligence process greatly. See also faas-cli self-documenting output.

## Your Environment
N/A

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.
Filled out form

**Comment by alexellis** [comment]
Hi, I'm not really sure how to help on this issue, the things you've asked for are so broad.

In this instance, the comment you made doesn't make sense. The schema is documented

> Documentation for faas yml own config schema does not exist.
> Try to read the docs about the things being done in the workshop, realise docs don't exist for function config

https://docs.openfaas.com/reference/yaml/

> Try to look for exec_timeout at https://docs.openfaas.com/ and find nothing

Again this is listed in the docs with a full example: https://docs.openfaas.com/tutorials/expanded-timeouts/

What's the best way that I can help you @MichaelHindley? Are you looking for training?

Alex

**Comment by alexellis** [comment]
If you want a detailed reference guide, then you have the docs, but better than that (for specific use-cases) would be the manual: https://store.openfaas.com/l/serverless-for-everyone-else

There's also a course we wrote for the LinuxFoundation on Serverless on Kubernetes that you might benefit from working through: https://www.openfaas.com/blog/introduction-to-serverless-linuxfoundation/

**Comment by alexellis** [comment]
/set title: Question about function configuration and timeouts
