### ISSUE TITLE
Multitenant - works ok but cannot connect after 14 hours.

### ISSUE THREAD

**Issue by datngoNFQ** [openfaas/faas#1679]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Me and my team are able to deploy openfaas multitenant by following this link: https://docs.openfaas.com/reference/namespaces/

We check with /ui and dropdown box for multiple namespaces are shown. Deploy many functions to various namespaces work.

Then, we take snapshot of our AWS lightSail to ensure that we have a backup that ready to work.

Then, 14 hours later. We are not able to connect to openfaas gateway.

Even when we create a new instance from the snapshot, We are still not able to connect to openfaas gateway.

## Expected Behaviour

We expect to connect to openfaas as normal

## Current Behaviour
After 14 hours (or some timeout duration) openfaas is not able to connect to.

Me and my team are able to deploy openfaas multitenant by following this link: https://docs.openfaas.com/reference/namespaces/

We check with /ui and dropdown box for multiple namespaces are shown. Deploy many functions to various namespaces work.

Then, we take snapshot of our AWS lightSail to ensure that we have a backup that ready to work.

Then, 14 hours later. We are not able to connect to openfaas gateway.

Even when we create a new instance from the snapshot, We are still not able to connect to openfaas gateway.

Below is the output when we run command: kubectl port-forward -n openfaas svc/gateway 8080:8080
```
ubuntu@ip-172-26-5-242:~$ kubectl port-forward -n openfaas svc/gateway 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
E1117 03:07:20.670682   16860 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 9b3e0d8298012cb8b59b9d80e17f3752e405ca8d616caa36672d2ddf2746eb0f, uid : failed to execute portforward in network namespace "/var/run/netns/cni-4ac309e8-6b98-83a0-ed53-8b1124979701": failed to connect to localhost:8080 inside namespace "9b3e0d8298012cb8b59b9d80e17f3752e405ca8d616caa36672d2ddf2746eb0f", IPv4: dial tcp4 127.0.0.1:8080: connect: connection refused IPv6 dial tcp6 [::1]:8080: connect: connection refused 

```

We are in a tight deadline that we could not investigate deeper into the issue. But the same issue happens on my MacOS laptop lastweek. 

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## List All Possible Solutions and Workarounds

For now, we have to remove the kind cluster (https://kind.sigs.k8s.io/)
Then, re-create kind cluster, then reinstall openfaas for multi tenant.
And we know that, after many hours , the system would be failed again, and we need to reinstall like that.

## Steps to Reproduce (for bugs)

1. Delete the kind cluster
2. Re-create a kind cluster that support openfaas multi tenant 
3. Reinstall openfaas multi tenant

## Context

We are trying to deploy functions into multiple tenant, each tenant is 1 namespace, each function belongs to 1 tenant only.

Please refer to above detailed description

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.13.15

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.10, build b48563620.10.10, build b485636

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04 LTS (Focal Fossa) And also Macos 11.6

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by datngoNFQ** [comment]
We are using openfaas on kubernets

**Comment by alexellis** [comment]
Hi @datngoNFQ it seems like your gateway pod restarted due to some event within your cluster. Nothing here seems related to multi-tenancy. Multiple namespace support is tested regularly and I'm unaware of any problems. That said, Kubernetes is complex and we're very experienced with it.

I'd suggest booking a call with myself to explore how we can help your company here through professional services/consultiung.

https://calendly.com/alexellis/explore

Regards,

Alex

**Comment by datngoNFQ** [comment]
@alexellis Thank you for your feedback. Do you know why event after restart docker, the pod for gateway still not able to function properly.

**Comment by alexellis** [comment]
I run openfaas locally and don't run into any issues doing this. You haven't provided any logs or evidence that you've followed the troubleshooting guide. I really can't help you without any context.

To clarify, there are no known issues with openfaas, docker or restarting systems, but you have not provided any context about how or where you're running openfaas.

If you'd like to have me look at your environment 1:1, then OpenFaaS Ltd offers that service: https://calendly.com/alexellis/
