### ISSUE TITLE
[QUESTION] Connecting to WebUI

### ISSUE THREAD

**Issue by Butzenmummel** [openfaas/faas#1680]
I got a (stupid) question, but I just dont know how to solve it.
I deployed openfaas on my k3s raspberry pi cluster and I am stuck at accessing the WebUI.
My current step is;
`arkade info openfaas
#Forward the gateway to your machine`

What exactly do I need to type as gateway? I am just learning this stuff.
`kubectl rolloput status -n openfaas deploy/gateway`

Thanks in advance

**Comment by alexellis** [comment]
Feel free to ask for technical support on Slack.

Alex

**Comment by alexellis** [comment]
/set title: How do I connect to my Raspberry Pi?
