### ISSUE TITLE
Timeout configs in Helm values.yml doesn't override function timeouts

### ISSUE THREAD

**Issue by ctwkongmu** [openfaas/faas#1681]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

The timeout settings in helm values.yml(`readTimeout`, `writeTimeout`) seems not to override function timeouts as stated in [workshop](https://github.com/openfaas/workshop/blob/master/lab8.md):

> There is also a maximum timeout duration set at the gateway and it will override the function timeout. At the time of writing the maximum timeout is configured at "20s", but can be configured to a longer or shorter value.

## Expected Behaviour

After update the timeout settings in helm values.yml(`readTimeout`, `writeTimeout`) and run helm upgrade, the function timeouts should be changed accordingly.

## Current Behaviour

After change helm values.yml(`readTimeout`, `writeTimeout`) and run helm upgrade, the values changed in gateway (verified by `env` in gateway container).
But the timeout in function seems to be the unchanged.
This is verified by restart the function pod in `openfaas-fn` namespace and check the logs
```
2021/11/25 09:07:23 Version: 0.2.0	SHA: 56bf6aac54deb3863a690f5fc03a2a38e7d9e6ef
2021/11/25 09:07:23 Timeouts: read: 5s write: 5s hard: 0s health: 5s.
2021/11/25 09:07:23 Listening on port: 8080
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds

Workaround:
Add the function timeout under the environment in `function.yml` file.

## Which Solution Do You Recommend?

Not a solution, but, maybe instead of letting the settings in values.yml to override function settings, shouldn't it the the other way around?
(Cluster setting defines the default behavior while each function defines the specific behavior.)

## Steps to Reproduce (for bugs)

1. change helm values.yml(`readTimeout`, `writeTimeout`) 
2. run helm upgrade
3. restart function pod
4. check the log and timeout stays the same.

## Context
I was encountering 503 on a long running function.
After I changed the timeout config the timeout still happens.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.15

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.8

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Using faas-cli on macos and cluster is on EKS.

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi @ctwkongmu thanks for your interest in openfaas.

The timeout values in values.yaml do not affect function timeouts, I'm not sure what led you to believe that, but if you have a link to the URL, we may be able to update it.

Here's a tutorial on how to set timeouts.

https://docs.openfaas.com/tutorials/expanded-timeouts/

Regards,

Alex

**Comment by alexellis** [comment]
/set title: How do I set expanded timeouts?
