### ISSUE TITLE
run openfaas 'manualy' on docker only?

### ISSUE THREAD

**Issue by mvdhoning** [openfaas/faas#1687]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

It seems that openfaas needs kubernetes to function. 
This is way overkill for my usecase. Only a few functions for a single application.
The alternative faasd seems to use an alternative containerd then docker so i dont dare to install that in my single machines that has already working docker containers running.
So what other options are there if any? Is there a way to start some needed container by hand on docker?

## Expected Behaviour

Make instructions on how to setup openfaas on a single machine using docker command line only.

## Current Behaviour

faas needs kubernetes or similar, faasd uses an alternative to docker. Both do not suit my usecase run openfaas on a sinle machine using docker containers. So i cannot use/try it.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X ] No

## Which Solution Do You Recommend?

if possible manual instructions or docker compose file

## Context

Not able to use openfaas on my server as it is only a single machine running docker containers, wanted to add openfaas to the existing infrastructure but that is not possible and faasd does not seem to be an useable alternative on the same machine

## Your Environment

* Docker version 20.10.7 Community

**Comment by Shikachuu** [comment]
I shouldn't run `faas-netes` without Lubernetes, since it is heavily depends on the Kubernetes API.

In a virtual machine (lima,  multipass, vagrant etc.) you can run the `faasd` project which roughly has the same fetaures, but fits your described use case really well, I mean, its is literally built for that.

https://github.com/openfaas/faasd

**Comment by mvdhoning** [comment]
does that mean one can run faasd inside a docker container? If yes it could be a solition, if no it is not a solution as all i want my server to do is serving docker containers.

**Comment by alexellis** [comment]
@mvdhoning faasd requires its own VM or host, this is [documented in the manual](https://gumroad.com/l/serverless-for-everyone-else)

May I suggest that you would benefit from buying a copy?
