### ISSUE TITLE
Upstream HTTP request error when function takes more than 7 seconds

### ISSUE THREAD

**Issue by pmarsi** [openfaas/faas#1688]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues] (https://github.com/openfaas/faas/issues/1559)

## Expected Behaviour
FaaS function crash the execution much earlier than configured timeouts. When a client make a FaaS function request, it receives a 502 Bad Gateway response (HTTP/1.1 502 Bad Gateway)

## Current Behaviour
I've implemented the same FaaS function than the lab8 of the Workshop (https://github.com/openfaas/workshop/blob/master/lab8.md).
I've deployed Openfaas via Helm over a k3s cluster. We create two namespaces, one for internal faas components and other one for FaaS functions.

Before deploying our function, we configured the timeouts with the following values:
   *  ```exec_timeout: 15s```
   *  ```read_timeout: 15s```
   *  ``` write_timeout: 15s```

My function sleeps for a time configured by environment variable, and the print some messages. The behaviour of the function depends of the time that I configure:

       * sleep time: 3s --> OK
       * sleep time: 5s --> OK
       * sleep time: 8s --> FAIL (context deadline exceeded (Client.Timeout exceeded while awaiting headers))
    
I can't understand  what is happening...The function crash much earlier that the timeouts that I've configured

## Steps to Reproduce (for bugs)

1. Create a k3s cluster
2. Deploy OpenFaaS via Helm
3. Create a sleep FaaS function described in the workshop lab 8 (https://github.com/openfaas/workshop/blob/master/lab8.md)
    I deploy FaaS function directly with kubectl, I didn't use faas-cli command line.
4. Configure the timeouts and the sleep timing
5. Launch several HTTP request with CURL

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.20

* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.13

* Are you using OpenFaaS on Kubernetes? yes

* Operating System and version (e.g. Linux, Windows, MacOS): Linux Mint 20.2

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi, I would suggest that you follow the tutorial named Expanded timeouts.

It covers everything you need including a full working example in Go and Node.js

https://docs.openfaas.com/tutorials/expanded-timeouts/

If you need additional support from us, I'd suggest becoming a sponsor via GitHub

https://github.com/sponsors/openfaas

Alex

**Comment by pmarsi** [comment]
Thank you @alexellis. Regarding to this issue, I've seen this morning a similar bug reported in the following web: https://issueexplorer.com/issue/openfaas/faas-netes/743

As you said here https://issueexplorer.com/issue/openfaas/faas-netes/729#5166257, you found a fix for the bug, so I updated the helm package of faas-netes in order to solve the problem.
