### ISSUE TITLE
Deploy Functions in Openfaas on paused containers to reduce cold starts

### ISSUE THREAD

**Issue by iamnst19** [openfaas/faas#1689]
1.	Create a paused container that allows to create network configurations in advance
2.	Create a snapshot of the function using CRIU(https://criu.org/Main_Page)
3.	Now in the case of function chaining when you have to create a new function then it will use the preexisting paused container and apply snapshot on top of it
4.	To prove the success of our experiments we will have to record time it took to create the container with function.

** I would like to know if the above is even possible doing in openfaas

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? yes on kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Code example or link to GitHub repo or gist to reproduce the problem: 

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi @iamnst19 

1) As far as I know Kubernetes doesn't broadly support the concept of paused containers, so I'll have to close this issue. Happy to revisit when it's a stable, GA API.

2) For faasd, we already support pausing containers and it works really well as the default for any container scaled to zero replicas:

I have already sent you a video when you reached out to me directly :slightly_smiling_face: 

https://www.youtube.com/watch?v=ZnZJXI377ak

https://twitter.com/alexellisuk/status/1366335183939633158

How else can I help?

Alex
