### ISSUE TITLE
Proposal: Secrets Integration for OpenFaas with Vault

### ISSUE THREAD

**Issue by nicholasjackson** [openfaas/faas#169]
HashiCorp Vault is an open source tool for managing and controlling access to tokens, passwords, certificates.  Integrating OpenFaas with Vault would allow a generic backend which would enable the injection of secrets into OpenFaas.  In addition to secrets Vault could be used to generate and and manage x.509 certificates for jobs again enabling transparant cross platform TLS.

## Expected Behaviour
**Secrets:**
When a user creates a new function in OpenFaaS they should be able to provide key/value pairs which would be encrypted and stored in Vault.  When a job executes this data would be retrieved from Vault and injected into the job for it to use.

**TLS:**
When a job is created it would contact vault to obtain a x.509 certificate securing it with TLS.  The gateway would then communicate with the service using TLS rather than plain HTTP.  In addition to this the proxy could use mutual TLS with a client side certificate to ensure that the job it is talking to is intact the correct job to mitigate man in the middle attacks.

## Possible Solution
The internals from consul template [https://github.com/hashicorp/consul-template](https://github.com/hashicorp/consul-template) could be embedded into the gateway to ensure that when a secret expires (all secrets have a TTL) or if the secret is updated it would be able to update the function.  This would reduce the load on the Vault server and making a call every-time a function executes.  Nomad and Kubernetes both have this capability when you integrate Vault and start a Job or Pod however by placing this integration into the proxy it gives agnosticism to the underlying scheduler and allows seamless integration with Swarm, Rancher, Mesos, etc.

## Context
Having a central capability for secrets management and encryption functions allows functions to remain light and the author to concentrate on functionality not security.  Enterprises already trust Vault and implementing it would allow them to leverage existing infrastructure.  TLS can be complicated to set up and get right however leveraging Vaults CA capability allows easy creation and management for x.509 certificates.

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek add label: priority/middle

**Comment by nicholasjackson** [comment]
This is potentially superseded with the following proposal which would allow implementation outside of OpenFaaS.
[https://github.com/openfaas/faas/issues/262](https://github.com/openfaas/faas/issues/262)

**Comment by alexellis** [comment]
It would be nice to see this in the faas-nomad implementation. See also: #807

**Comment by alexellis** [comment]
Derek close: inactivity

**Comment by Preisschild** [comment]
I'd be interested in Vault Integration.

Would be cool if this would be supported sometime.

**Comment by alexellis** [comment]
There are users of openfaas that also use Vault. If you join Slack now you'll see the thread and are welcome to ask questions.
