### ISSUE TITLE
One node per function invocation

### ISSUE THREAD

**Issue by rvarkonyi** [openfaas/faas#1693]
## Expected Behaviour

What I'd like to achieve is that whenever my function gets invoked, a new node in my Kubernetes cluster is created to handle the process - my function is highly CPU / Memory intensive so it definitely requires its own node to run on every time it gets invoked.

## Current Behaviour

I was able to define resource _requests_ and _limits_ in my function definition and also configure _Cluster Autoscaling_ in DigitalOcean and now have multiple nodes running and I would expect my function to get deployed to a new node every time it's invoked. Instead, what I'm seeing is that the original replicaset gets recreated on the first node.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

Not sure about workarounds, it's why I'm asking for support / guidance.

## Which Solution Do You Recommend?

Not sure.

## Steps to Reproduce (for bugs)

1. Enable CA on DigitalOcean, disable Autoscaling in OpenFaaS
2. Configure resource requests and limits in your function in a way that a single node is unable to handle multiple invocations
3. Invoke your function multiple times
4. Your function will run on a single node instead of multiple nodes

## Context

Functions that utilise high amount of CPU / Memory (such as an image processing pipeline in my case) would benefit from the expected behaviour described above.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.13.15

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.8

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? OpenFaaS on Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Code example or link to GitHub repo or gist to reproduce problem:  N/A

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting) -  N/A
* 

## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I'm fairly new to OpenFaaS and Kubernetes and would like to ask for a bit of a guidance here. I've successfully deployed my nodeJS function to OpenFaas that's running in a Kubernetes cluster on DigitalOcean. The actual process that's being executed is an image processing pipeline that's highly CPU / memory intensive so what I'd like to achieve is that whenever my function is invoked in OpenFaas, a new Kubernetes node spins up and executes the function. I did some research in autoscaling and I think I understand the concepts but it would be really great if someone could explain how to achieve the desired result in OpenFaaS context.

Any help would be greatly appreciated.

Thanks

**Comment by alexellis** [comment]
@rvarkonyi please can you fill out the whole issue template?

https://github.com/openfaas/faas/blob/master/.github/ISSUE_TEMPLATE.md

Thanks, then we'll take a look at this.

**Comment by alexellis** [comment]
Hi, just click "edit", copy and paste in the issue template and fill it out.

That'd be really appreciated.

You should be able to see plenty of other examples such as: #1676

**Comment by rvarkonyi** [comment]
## Expected Behaviour


What I'd like to achieve is that whenever my function gets invoked, a new node in my Kubernetes cluster is created to handle the process - my function is highly CPU / Memory intensive so it definitely requires its own node to run on every time it gets invoked.


## Current Behaviour


I was able to define resource _requests_ and _limits_ in my function definition and also configure _Cluster Autoscaling_ in DigitalOcean and now have multiple nodes running and I would expect my function to get deployed to a new node every time it's invoked. Instead, what I'm seeing is that the original replicaset gets recreated on the first node.

## Are you a GitHub Sponsor (Yes/No?)


Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds



Not sure about workarounds, it's why I'm asking for support / guidance.

## Which Solution Do You Recommend?

Not sure.

## Steps to Reproduce (for bugs)


1. Enable CA on DigitalOcean, disable Autoscaling in OpenFaaS
2. Configure resource requests and limits in your function in a way that a single node is unable to handle multiple invocations
3. Invoke your function multiple times
4. Your function will run on a single node instead of multiple nodes

## Context


Functions that utilise high amount of CPU / Memory (such as an image processing pipeline in my case) would benefit from the expected behaviour described above.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.13.15

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.8

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? OpenFaaS on Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Code example or link to GitHub repo or gist to reproduce problem:  N/A

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting) -  N/A

**Comment by alexellis** [comment]
@rvarkonyi this can be addressed through OpenFaaS' pro scaler which can use either CPU or in-flight requests for auto-scaling.

Thanks,

Alex
