### ISSUE TITLE
How to link a customized service account to the function

### ISSUE THREAD

**Issue by liililil** [openfaas/faas#1699]
## My actions before raising this issue
- Followed the [Private Registries](https://docs.openfaas.com/reference/private-registries/#option-1-link-an-image-pull-secret-to-the-namespaces-serviceaccount)
- kubectl edit serviceaccount default -n openfaas-fn.
- Add imagePullSecrets to default serviceaccount.

## Expected Behaviour
The default serviceaccount has permanent change.

## Current Behaviour
Using a managed cluster, the change will be covered immediately.

## List All Possible Solutions and Workarounds
1. Create another service account, and then link it to the pod.
2. Link the imagePullSecret to the pod.

## Which Solution Do You Recommend?
I would like if I can use faas-cli or some related configuration files to change the function pod's imagePullSecret or serviceAccount.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.14.1
* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.12
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by alexellis** [comment]
Hi @liililil 

Thanks for your interest.

It's not clear what issue you are having here or what you want to do?

Do you want a custom Kubernetes service account for your function? I.e. to access logs etc? That's supported by OpenFaaS Pro only.

Details are available here: https://docs.openfaas.com/reference/workloads/#custom-service-account

To get in touch for a call with us, feel free to reach out https://openfaas.com/support

Alex
