### ISSUE TITLE
How do I run docker inside a function?

### ISSUE THREAD

**Issue by mrunmayi** [openfaas/faas#1706]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) verified issue not mentioned in troubleshooting guide 
- [ ] Read/searched [the docs](https://docs.openfaas.com/) already read the docs
- [ ] Searched [past issues](/issues) : yes I searched past issues and could not find similar issue.

## Expected Behaviour

There are currently 3 ways to run docker inside docker (https://devopscube.com/run-docker-in-docker/)
- By mounting docker.sock: As faas does container management we are unable to mount the docker in the existing containers that faas-deploy created. we could not find any such option to mount a socket
- By using dind which needs `privileged` mode to containers. I saw in few of the issues (https://github.com/openfaas/faas/issues/1238) its mentioned that openfaas do not plan to support privileged mode to containers
- By Sysbox : I coud not find any documentation around it ini openfaas.
- 

we should be allowed to docker command like docker build inside the docker container 

## Current Behaviour

currently we do not have any way or much documentation around how to run docker commands inside faas manages containers

## Are you a GitHub Sponsor (Yes/No?) : no

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1. build an image 
2. use faas-cli deploy to deploy the image
3. login into the container / try to run docker command 
4. it fails 
5. 
## Context

We have a cli micro-service which is running using openfaas. This service try to build docker images and deploy the images for other product components 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Closing since we didn't hear back from you.

Feel free to send another comment here if you want to continue the discussion.
