### ISSUE TITLE
Handler file updated but not reflecting after deploying again

### ISSUE THREAD

**Issue by CryptoMeena** [openfaas/faas#1707]
I have made changes to a handler file and re-deployed again but it is taking the older version. The modifications are not coming up.
I have done the following
1. Removed all the functions using faas-cli rm -f  myfile.yaml
2. Removed all the docker images by calling docker rmi  <imagename>
3. faas-cli build -f  myfile.yaml
4. faas-cli push -f  myfile.yaml
5.  faas-cli deploy -f  myfile.yaml

**Comment by alexellis** [comment]
Hi @CryptoMeena you'll need to use the issue template if you'd like us to give you a hand here.

You've removed all the useful information we could use to help you, but I suspect the answer you need is in the troubleshooting guide.

The issue template is not optional.

Alex
