### ISSUE TITLE
Timeout issue on /system/functions

### ISSUE THREAD

**Issue by JayBraker** [openfaas/faas#1711]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
- I would like to get started learning faasd

## Expected Behaviour
- Login successfully

## Current Behaviour
- After running ./hack/install.sh I can open localhost:8080/ui/ and login with admin/#password
- Trying to call localhost:8080/system/functions results in loading basic login and then loading forever
- Trying to login first time via faas-cli -> client aborts after timeout (not server side but the client times out)

## Steps to Reproduce (for bugs)

1. Setup vhost Ubuntu 20.04
2. Clone repo
3. run `cd faasd && sudo ./hack/install.sh`
4. `$ export OPENFAAS_URL=http://localhost:8080
     $ cat faasd.txt | faas-cli login --username admin --password-stdin`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
   commit:  b1c09c0243f69990b6c81a17d7337f0fd23e7542
   version: 0.14.2
* Docker version `docker version` (e.g. Docker 17.0.05 ):
  Not installed
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
  faasd
* Operating System and version (e.g. Linux, Windows, MacOS):
  Ubuntu 20.04 (4 cores 8GB RAM vHost)

**Comment by JayBraker** [comment]
Maybe I got sth wrong with not installing docker?
From what I read in the docs, installing docker on the same host as faasd might cause trouble bc of both depending on containerd

Also: Is there a smooth way to get the logs from non-kubernetes faasd?
I checked systemctl status faasd but that only gives info on successfull startup I guess:
`Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Resolver: "faasd-provider"="10.62.0.1"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Resolver: "basic-auth-plugin"="10.62.0.7"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Resolver: "nats"="10.62.0.8"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Resolver: "prometheus"="10.62.0.9"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Resolver: "gateway"="10.62.0.10"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Resolver: "queue-worker"="10.62.0.11"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Looking up IP for: "prometheus"
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Proxy from: 127.0.0.1:9090, to: prometheus:9090 (10.62.0.9)
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 faasd: waiting for SIGTERM or SIGINT
Apr 24 19:02:56 HOSTNAME faasd[178395]: 2022/04/24 19:02:56 Proxy from: 0.0.0.0:8080, to: gateway:8080 (10.62.0.10)
`

**Comment by JayBraker** [comment]
Apparently faasd only listens for proto tcp6.
Port 8080 is not in use and I have not seen any errors during installation.
But still after restarting faasd or the machine, faasd won't bind to port 8080 for ipv4 traffic

Any ideas how to mitigate this behavior?

**Comment by alexellis** [comment]
Hi @JayBraker perhaps you should use `127.0.0.1` as per the eBook? It forces ipv4.

We also have detailed troubleshooting instructions that may be of help over there.

> edit: Cannot reproduce the issue on a local kvm running Ubuntu 22.04.. sigh

So what's different? Do you know?

Alex

**Comment by JayBraker** [comment]
> 

Ah yes thanks for getting back on this anyway.
Figured it out:
My firewall defaults to deny, this blocks any communication to the openfaas0 network interface.
After allowing traffic from localhost to that interface and vice versa everything worked as expected
