### ISSUE TITLE
POST /system/scale-function/{functionName} yields "service  not found"

### ISSUE THREAD

**Issue by rozpuszczalny** [openfaas/faas#1713]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?

I'd like to play around with manual function scaling

## Expected Behaviour

Sending `POST /system/scale-function/{functionName}` scales replicas to the desired number.

## Current Behaviour

`POST /system/scale-function/{functionName}` returns 404 error with `service  not found` body.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1. Start fresh instance of faasd
2. Create nodeinfo function
3. Run query below:

```
http -v -a admin:`sudo cat /var/lib/faasd/secrets/basic-auth-password` POST http://localhost:8080/system/scale-function/nodeinfo replicas:=10 service=nodeinfo
```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  b1c09c0243f69990b6c81a17d7337f0fd23e7542
 version: 0.14.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.21.3
 sha:     cdb6badddaede0f69ef8ce9cb4b7e25e876b75fa


Provider
 name:          faasd
 orchestration: containerd
 version:       0.16.0 
 sha:           e668beef139ee094ad7364a5534b15d84b1b1f6d
```

* ~~Docker version `docker version` (e.g. Docker 17.0.05 )~~ Containerd version:
```
$ sudo ctr version
Client:
  Version:  v1.6.2
  Revision: de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
  Go version: go1.17.2

Server:
  Version:  v1.6.2
  Revision: de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
  UUID: aa082e02-38f0-4b18-a46e-6dfcd55d39d0
```

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

faasd

* Operating System and version (e.g. Linux, Windows, MacOS):

arm64 linux (Raspberry Pi 4)

* Code example or link to GitHub repo or gist to reproduce problem:

N/A

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

The only relevant log from faasd-provider:
```
Apr 29 09:09:14 pi-cloud-1 faasd[7012]: 2022/04/29 09:09:14 [Scale] request: {"replicas": 2, "service": "nodeinfo"}
Apr 29 09:09:14 pi-cloud-1 faasd[7012]: 2022/04/29 09:09:14 [Scale] service  not found
```

Full request - response from httpie:

```
$ http -v -a admin:`sudo cat /var/lib/faasd/secrets/basic-auth-password` POST http://localhost:8080/system/scale-function/nodeinfo replicas:=2 service=nodeinfo
POST /system/scale-function/nodeinfo HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Basic [redacted]
Connection: keep-alive
Content-Length: 38
Content-Type: application/json
Host: localhost:8080
User-Agent: HTTPie/2.2.0

{
    "replicas": 2,
    "service": "nodeinfo"
}

HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Fri, 29 Apr 2022 08:07:12 GMT
X-Content-Type-Options: nosniff

service  not found

$ http -v -a admin:`sudo cat /var/lib/faasd/secrets/basic-auth-password` http://localhost:8080/system/function/nodeinfo
GET /system/function/nodeinfo HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic [redacted]
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/2.2.0



HTTP/1.1 200 OK
Content-Length: 608
Content-Type: application/json
Date: Fri, 29 Apr 2022 08:09:21 GMT

{
    "annotations": {},
    "availableReplicas": 1,
    "createdAt": "2022-04-29T07:23:52.449646462Z",
    "envProcess": "node index.js",
    "envVars": {
        "NODE_VERSION": "14.19.0",
        "NPM_CONFIG_LOGLEVEL": "warn",
        "YARN_VERSION": "1.22.17",
        "cgi_headers": "true",
        "exec_timeout": "10s",
        "mode": "http",
        "prefix_logs": "false",
        "read_timeout": "15s",
        "upstream_url": "http://127.0.0.1:3000",
        "write_timeout": "15s"
    },
    "image": "ghcr.io/openfaas/nodeinfo:latest",
    "labels": {},
    "name": "nodeinfo",
    "namespace": "openfaas-fn",
    "replicas": 1
}
```

**Comment by alexellis** [comment]
Hi @rozpuszczalny

Thanks for your interest.

I can see that you're using faasd, however faasd doesn't support scaling beyond 1 replica.

I'll close this issue for you, but feel free to keep the conversation going.

Can you tell us a bit more about what you're trying to achieve?

Alex
