### ISSUE TITLE
Support request for KinD / arkade

### ISSUE THREAD

**Issue by JdKock** [openfaas/faas#1714]
I'm using:
macOs Monterey 12.3.1
faas-cli 0.14.2
Kind 1.23.4

I have installed Kind and now want to install OpenFaas on it with arkade.
I created a new cluster: 
❯ kind create cluster --name openfaas

And after this I run: 
❯ arkade install openfaas

I see no error messages.

Check openfaas is running:
❯ kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"

All the deployments (alertmanager, basic-auth-plugin, gateway,.....) shows 0/1. This means nothing is ready I think.

And than check the pods:
❯ kubectl get pods -n openfaas

All the pods are 0/1 and with status ImagePullBackOff

Can anybody help me what is wrong with my openfaas installation?

**Comment by alexellis** [comment]
Hi @JdKock 

Thanks for the interest.

In order to help you, we'll need you to edit this and fill out the issue template, in addition to what you've given.

You also deleted or ignored the statement "I've read and tried the troubleshooting guide" which probably would have given you what you need to fix this or get a meaningful error.

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

Alex

**Comment by alexellis** [comment]
/set title: Support request for KinD / arkade

**Comment by welteki** [comment]
Hi @JdKock

Have you tried the troubleshooting steps?
https://docs.openfaas.com/deployment/troubleshooting/#openfaas-on-kubernetes

Especially the output of `kubectl get events -n openfaas --sort-by=.metadata.creationTimestamp`
should be helpful to figure out why the installation fails.

**Comment by JdKock** [comment]
@welteki Thanks! I will try that first to see if that is helpful why its failing.

**Comment by alexellis** [comment]
@JdKock sounds like you have a networking issue.

Given that you deleted the issue template we have very little information on how to help you.

There's no issues with OpenFaaS, we've checked so we need to close this out.

I'd suggest that you explore why Kubernetes isn't able to pull images on your network.

Alex

**Comment by JdKock** [comment]
@alexellis Thanks for all the help!
