### ISSUE TITLE
Questions about parallelism for concurrent function request.

### ISSUE THREAD

**Issue by FTWH** [openfaas/faas#1718]
The following is from official doc:
> Parallelism(https://docs.openfaas.com/reference/async/#parallelism)
By default there is one queue-worker replica deployed which is set up to run a single task of up to 30 seconds in duration.
You can increase the parallelism by scaling the queue-worker up - i.e. 5 replicas for 5 parallel tasks.
Alternatively you can increase the parallelism by setting the queue worker's "max_inflight" option to a value greater than one. This will cause the queue-worker to concurrently receive up to max_inflight many messages and simultaneously invoke their corresponding functions. Should you wish to restrict concurrency for certain functions, please make use of [multiple queues](https://docs.openfaas.com/reference/async/#Multiple-queues) and separate these functions accordingly. When scaling up a queue worker, please be aware that you will get up to 'n * max_inflight' parallel function invocations.

Q1: If I scale the queue-worker to 5 replicas, is it means all the function that I have deployed on OpenFaaS can run in parallel at 5 concurrency? (all the function will be same)

Q2: If it is true, if some functions requires more resources, what if their CPU or memory resources run out at the degree of parallelism? Will OpenFaaS function pod crash?

Q3: Is it means that the total concurrency = num_of_queue-worker * max_inflight? Is it means each function can have this num of concurrency or the sum of total function's concurrency?

Thank you for your noticing!
Best regards.

## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
Really confused about the concurrent mechanism of openfaas.

## Expected Behaviour

None

## Current Behaviour

None

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Which Solution Do You Recommend?

Describe more details about intra pod concurrency and the relationship between max_inflight and number of queue worker in documentation.

## Steps to Reproduce (for bugs)

None.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.14.2
* Docker version `docker version` (e.g. Docker 17.0.05 ):
21.04
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Code example or link to GitHub repo or gist to reproduce problem:
None
* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by welteki** [comment]
Hi @FTWH

Thanks for your interest, could you please take some time to fill out the issue template.

This youtube video about the queue-worker might be useful to help you understand it better.
https://www.youtube.com/watch?v=VdggUjexbuI&t=183s

Regards,
Han

**Comment by FTWH** [comment]
> Hi @FTWH
> 
> Thanks for your interest, could you please take some time to fill out the issue template.
> 
> This youtube video about the queue-worker might be useful to help you understand it better. https://www.youtube.com/watch?v=VdggUjexbuI
> 
> Regards, Han

Thanks for your help! But I still have some confusion.
1. Is the queue workers only related to async invocations? Do queue workers influence the sync invocations?
2. Dose OpenFaas support in-pod concurrency? Can function requests be handled simultaneously in each replica?
3. What if the resource consumption in a pod exceeds the limitation? In a pod, the function processes run in parallel, which shares the resources in the pod. Will the OpenFaaS automatic determine the intra-pod concurrency for preventing run out of memory?

**Comment by alexellis** [comment]
Hi @FTWH

What we are missing from you, is what is in the issue template:

What are you trying to do?

Why?

What have you tried already?

If you answer these, you'll probably get the answers you are looking for from us.

For question 1 - read this page: https://docs.openfaas.com/reference/async/

You may also benefit from reading: https://www.openfaas.com/blog/limits-and-backpressure/

For 2 - yes of course, OpenFaaS containers are normal Kubernetes Pods serving traffic over HTTP, you can serve as many requests as the pod can handle.

3 - "What if the pod runs out of resources" - then you [should set appropriate requests / limits values](https://docs.openfaas.com/reference/yaml/#function-memorycpu-limits), just like in Kubernetes, it's no different. [OpenFaaS auto-scaling](https://docs.openfaas.com/architecture/autoscaling/) combined with the `max_inflight` setting handle this particularly well.

I'll leave this link here again as it explains it in a bit more detail:

https://www.openfaas.com/blog/limits-and-backpressure/

If you need additional support, feel free to reach out to us about our commercial services or join a weekly community call.

> Our office hours at 1630 GMT+1 / BST each Wednesday will be open to the community.
>
> https://us02web.zoom.us/j/83845933347?pwd=RzhVeWVHVXJQY2RBM1FMMzd3blhpUT09
>
> Introduce yourself, feel free to bring questions, comments and suggestions for openfaas, arkade, k3sup and derek.

More importantly, context is key, so if you spend a few moments to tell us what you're trying to build or achieve, that will help you get what you want.

Regards,

Alex

**Comment by alexellis** [comment]
I've added a bit more detail over at: https://github.com/openfaas/docs/pull/290/files
