### ISSUE TITLE
OpenFaaS on Kubernetes getting started guides for DigitalOcean, Packet & AWS

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas#172]
## Expected Behaviour

Guides should be provided to allow a user to easily set up an OpenFaaS platform on Kubernetes across a range of cloud providers. The initial target list includes:

- [ ] DigitalOcean
- [ ] Packet
- [ ] AWS

**Comment by johnmccabe** [comment]
Derek add label: enhancement

**Comment by johnmccabe** [comment]
I've picked this up.

**Comment by alexellis** [comment]
Thanks John. Should we prioritise K8s and kubeadm?

**Comment by johnmccabe** [comment]
Probably a good idea, I'll have a look at that now.

**Comment by alexellis** [comment]
You can direct people to https://blog.alexellis.io/tag/learn-k8s/

**Comment by amitkumarj441** [comment]
@johnmccabe @alexellis I'm willing to take up this task by setting up OpenFaas on AWS.

Please let me know if it's still pending.

**Comment by johnmccabe** [comment]
@amitkumarj441 picking up AWS would be cool, please do

**Comment by amitkumarj441** [comment]
Thanks a lot @johnmccabe for your prompt response.

Any suggestion before starting OpenFaas on AWS?

**Comment by johnmccabe** [comment]
@amitkumarj441 have you used OpenFaaS/AWS before?

**Comment by amitkumarj441** [comment]
@johnmccabe Yes, I'm using AWS extensively for my research projects since an year and I have used OpenWhisk before and OpenFaaS is new to me, but I'm going to deploy it on AWS and open to suggestions.

**Comment by amitkumarj441** [comment]
@johnmccabe I'm a Docker and Kubernetes intermediate hacker and would like to give a try on Rancher as well. Please add Rancher in the above list and I'll try to get OpenFaas up on both of these cloud providers.

**Comment by alexellis** [comment]
I'm ok with a Rancher guide - in fact we can link to Ken's blog post. However we need to focus in on Kubernetes and then Swarm for this issue.

John could you update the title to set the scope?

**Comment by takotuesday** [comment]
This would be really helpful. I just recently discovered OpenFaaS and have spent a decent amount of time trying to get it going in my VPS with not much luck.

**Comment by alexellis** [comment]
Email me at alex@openfaas.com and I'll invite you to slack so we can try to help you

**Comment by takotuesday** [comment]
@alexellis thanks! Email sent

**Comment by alexellis** [comment]
Hey what is your actual name so I know who to look out for?

**Comment by markboost** [comment]
@johnmccabe As discussed, it would be great to add a Civo to this list.

The guide below would also in theory would with any Openstack provider, as it's using the Openstack API. Feel free to use it.

https://www.civo.com/learn/kubernetes-and-openfaas-using-terraform

**Comment by alexellis** [comment]
We've merged the link into the community guide :+1:

**Comment by alexellis** [comment]
@ericstoekl can you put together a short guide for AWS when you have time? Create an issue to track it if you need to.

**Comment by alexellis** [comment]
@vielmetti do you think you'd have time or someone on the Packet team to write up a short guide for OpenFaaS on Packet? I think you could set up the hosts then point to our standard Kubernetes guide.

**Comment by alexellis** [comment]
Closing issue in favor of opening new ones.
