### ISSUE TITLE
Cant reach service for : [function name] when trying to make a sync call parallelly (in stepfunction using lambda)

### ISSUE THREAD

**Issue by deepanshu-zluri** [openfaas/faas#1727]
## My actions before raising this issue
- [1] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [1] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi @deepanshu-zluri what was happening here?

You left very little for us in the issue template, so it's hard to know how to help you

Alex
