### ISSUE TITLE
Cant reach service for : [function name] when trying to make a sync call parallelly (in stepfunction using lambda)

### ISSUE THREAD

**Issue by deepanshu-zluri** [openfaas/faas#1728]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

Trying to orchestrate the openfaas functions using stepfunctions and lambda . i am trying to run lambda in map state and calling the same openfaas function in those map state

When a sync call is made to the function using http request it returns successfully for the first invocation but fails for the other parallel calls giving and error "Cant reach service for : [function name]" . the label com.openfaas.scale.max for the function is set to 10  but the replicas never increase.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1. pull any function from store or create one
2. try invoking it using http post request in parallel concurrent manner

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
 Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi @deepanshu-zluri 

I'm confused with this issue, due to the lack of examples or steps to reproduce the problem. I am also unsure about the terms you're using, in OpenFaaS, we only have functions and we also don't have step-functions in the official project.

Are you asking for technical support for AWS Lambda? Or is this about OpenFaaS?

If you need help, you will need to provide a code example and steps to reproduce the problem, along with filling out the whole issue template.

Alex

**Comment by alexellis** [comment]
From the email I received from your team, it seems like you are overwhelming a single function. 

The best pattern for your kind of use-case would be the following:

Thanks for your interest

https://www.openfaas.com/blog/limits-and-backpressure/

If you'd like to discuss further, you are welcome to attend the weekly community call.

Alex
