### ISSUE TITLE
gateway UI and faas-cli not listing  the functions

### ISSUE THREAD

**Issue by anannaya** [openfaas/faas#1732]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
faas-cli list  --tls-no-verify -g https://openfaas.xxxxxx.texxxxxxxst.thuxxxxxnderhead.io
Cannot parse result from OpenFaaS on URL: https://openfaas.anand.test.thunderhead.io/system/functions
unexpected end of JSON input

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
`
CLI:
 commit:  b1c09c0243f69990b6c81a17d7337f0fd23e7542
 version: 0.14.2
`
* Docker version `docker version` (e.g. Docker 17.0.05 ):
`
Client:
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 31 19:20:32 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 31 19:21:13 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13
  GitCommit:        9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc:
  Version:          1.0.3
  GitCommit:        f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  `
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
yes.

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu and faas-cli ran on MAc laptop

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by anannaya** [comment]
There is tight coupling with a prometheus and alertmanager . Trying to figure out how to specify existing prometheus and alertmanager link.

**Comment by anannaya** [comment]
Basically these are part of prometheus metrics, I got it. Closing the issue, I will customise the chart to support prometheus-operator using servicemonitor CRD.

**Comment by welteki** [comment]
Hi, @anannaya

With the limited information you have provided us it is hard to understand what issue you are experiencing exactly.

I have verified that the functions are correctly listed in the gateway UI and using the faas-cli.

Han

**Comment by anannaya** [comment]
@welteki  I did not enable the promtheus and alert-manager .  So UI did not display the functions.
