### ISSUE TITLE
Invoke the function from faas-cli i am getting "Server returned unexpected status code: 405" .  

### ISSUE THREAD

**Issue by srinu49** [openfaas/faas#1733]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

## Expected Behaviour
 Function should be deployed.

## Current Behaviour
Deploying: hello-openfaas.
Unexpected status: 405, message: 
Function 'hello-openfaas' failed to deploy with status code: 405

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1. Login into openfaas gateway.
2. deploy hello-openfass function.
3.  
4.
5.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version Ubuntu, ):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by srinu49** [comment]
Invoke the function from faas-cli I am getting "Server returned unexpected status code: 405" But I can able to invoke the function from openfaas web UI. When I am trying to deploy other functions from faas-cli, getting unexpected status code 405.

**Comment by Shallow-Sea** [comment]
Is the port started?

srinu49 ***@***.***>于2022年6月14日 周二13:46写道：

**Comment by rgee0** [comment]
Since HTTP/405 is Method Not Allowed it would be really helpful to understand what _exactly_ you were attempting to do.  Usually this involves little more than filling in the fields issue template. You should be able to edit this one, rather than starting afresh.

**Comment by alexellis** [comment]
You'll need to fill out the whole issue template and provide an example so that we can try to reproduce it and advise you.

**Comment by srinu49** [comment]
Thank you all for your support, I resolved the issue. The problem is in my hello-openfass.yaml file
 gateway: http://localhost:8080/ui. But my ~/.bashrc openfass gateway URL is set with export OPENFAAS_URL=http://localhost:8080   there is a mismatch. After modifying .yaml file gateway URL to http://localhost:8080 problem solved.
