### ISSUE TITLE
when deploy the function in openfass getting " FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'. "

### ISSUE THREAD

**Issue by srinu49** [openfaas/faas#1735]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

## Why do you need this?
I want to compress a video file.

## Expected Behaviour
Video file should to compressed.

## Current Behaviour
Internal Server Error
exit status 1
Traceback (most recent call last):
  File "/home/app/index.py", line 18, in <module>
    ret = handler.handle(st)
  File "/home/app/function/handler.py", line 17, in handle
    ffmpeg.run(stream)
  File "/home/app/python/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/home/app/python/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)
handler.py
................................
import ffmpeg
import sys
def handle(req):
	stream = ffmpeg.input(r'/home/app/function/los_angeles.mp4') # video location
	stream = stream.filter('fps', fps=5, round='up').filter('scale', w=720, h=720)
	stream = ffmpeg.output(stream, r'/home/app/function/losoutput2.mp4')

	ffmpeg.run(stream)
	return req

requirements.txt
...................................
ffmpeg-python

## Context
I checked inside the container directory I found these files.
In  /home/app
function  index.py python requirements.txt files 

In /home/app/function
__init__.py  handler.py  los_angeles.mp4  requirements.txt

In  /home/app/python
bin	ffmpeg_python-0.2.0.dist-info  future-0.18.2.dist-info	libpasteurize     ffmpeg     future     libfuturize   past

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  b1c09c0243f69990b6c81a17d7337f0fd23e7542
 version: 0.14.2

Gateway
 uri:     http://localhost:8080
 version: 0.22.0
 sha:     cc2f38938e5081e617eab8e63156b194d6543bb1

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.15.0 
 sha:           e50e5c4e34335bf7dfad02497da456f88b18c57f

* Docker version `docker version'
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~18.04.3
 Built:             Mon Nov  1 01:04:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~18.04.3
  Built:            Fri Oct 22 00:57:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~18.04.2
  GitCommit:        
 runc:
  Version:          1.0.1-0ubuntu2~18.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

* using OpenFaaS on Kubernetes 

* Operating System and version Ubuntu

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi there, we cannot debug errors in your function for unless you provide the source code. 

The issue you raised doesn't appear to be a problem with OpenFaaS itself. 

Please provide a GitHub repository or let us know if you want to close your issue. 

Alex

**Comment by srinu49** [comment]
I fixed the issue.

**Comment by alexellis** [comment]
The issue would have been in your code, and we didn't have a code sample from you, so couldn't provide any real form of support.

I'll close this now.

Alex

**Comment by alexellis** [comment]
/set title: Support request for executing ffmpeg from Python
