### ISSUE TITLE
Spring WebFlux and RSocket Support.

### ISSUE THREAD

**Issue by iAbhinavKarn** [openfaas/faas#1736]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
I am trying to implement rsocket application using WebFlux.

## Expected Behaviour
Support of New Messaging Models like Request Stream, Fire & Forget and to make an api which supports Reactive Programming.

## Current Behaviour

Currently if we create an application we can only get the data in one go or we can enable async but this will only let the endpoint take multiple input but block any new I/O operation but by implementing WebFlux and RSocket we can also use Non Blocking I/O Operations and the connection from a TCP protocol will be working till all the response using Request Response Model is not completed and all other operations can also work.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):  0.14.2

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.15

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
* Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu(20.04)

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Thanks for your interest in OpenFaaS.

We have no plans to support the specific application frameworks that you mentioned at this time.

However, they may work, if you try them. Feel free to spend some of your own time on that.

> Support of New Messaging Models like Request Stream, Fire & Forget and to make an api which supports Reactive Programming.

Our model for this is async:

https://docs.openfaas.com/reference/async/

You can also take self-paced training to experiment with the model and see how it works for you:

https://docs.openfaas.com/tutorials/training/

Thanks,

Alex
