### ISSUE TITLE
Question - Build "AWS Lambda" using openfaas

### ISSUE THREAD

**Issue by shawnngtq** [openfaas/faas#1740]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
Same reason as open-source projects

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Context
 
After installing and trying it. I will categorize this is FAAS "engine" 🚂.

What is missing from this as compared to AWS lambda is:

- code editor 📝
- layers
- etc

Any idea how we can build "AWS Lambda" using openfaas and integrate it with other tools?

If anyone has done it, please share, you can also DM me directly if you prefer to 😁

**Comment by alexellis** [comment]
Hi @shawnngtq 

Thanks for your interest here, but there's so much lacking in this issue that I don't know how to help you.

If you're curious how to build functions, the best option would be for you to do some self-paced learning:

I wrote Serverless For Everyone Else as a complete guide to using the API, building functions with Node, and deploying them to the cloud.

https://docs.openfaas.com/tutorials/training/

You're also welcome to join the weekly community call, see the pinned issue.

I'm going to close this now as I don't think we can help with such a vague request, and the issue tracker isn't really for giving out technical support.

You should find all you need in the training materials, and the docs, we have pretty comprehensive examples. Then, if you need anything else, feel free to pop into a weekly call.

Alex
