### ISSUE TITLE
Documentation for golang outdated

### ISSUE THREAD

**Issue by RichardoC** [openfaas/faas#1741]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
While reading https://github.com/openfaas/faas/blob/master/README.md I realised that the golang library mentioned <github.com/openfaas-incubator/go-function-sdk>  has been archived, and thus there must be a new/better way of doing this.

## Expected Behaviour
The project readme should document the current way of getting started with golang FaaS functions.

## Current Behaviour
Documentation describes a library that got archived ~ 2 years ago.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Thanks for your interest. The canonical examples for Go and OpenFaaS are in Everyday Go which you will find available at store.openfaas.com

We also have up to date documents for Go at docs.openfaas.com, if you see a specific issue there, then raise an issue on openfaas/docs. 

We don't maintain archived repositories and all links that I'm aware of point to the new locations. 

Happy to look at specific URLs you can find in blog posts or official docs. 

@welteki can you take a look please?
