### ISSUE TITLE
using Playwright with OpenFaaS?

### ISSUE THREAD

**Issue by osmenia** [openfaas/faas#1744]
## My actions before raising this issue
- [x ] Read/searched [the docs](https://docs.openfaas.com/)
- [x ] Searched [past issues](/issues)

Here is blog about Puppeteer: https://www.openfaas.com/blog/puppeteer-scraping/

Is it possible to use FAAS with Playwright?  https://playwright.dev/

AWS Lambda works fine with Chrome, Firefox/Edge not.

Puppeteer Team is now working on Playwright.

tnx a lot!

**Comment by alexellis** [comment]
Hi @osmenia 

Feel free to try and find out.

If it works with AWS Lambda, then it should work in a container (which is what OpenFaaS uses)

In the future, if you'd like help please fill out the whole issue template.

Alex
