### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by unnimona** [openfaas/faas#1752]
i want to use openfaas

which is better to use?

faas-netes or faasd or k3s with faas or k8s with faas?

I will try it on my laptop and i want to deploy to AWS EC2. is AWS EKS or google GKE recommended?

**Comment by alexellis** [comment]
Hi @unnimona we can only help people who fill out the whole issue template.

Thanks for your interest in OpenFaaS.

We also don't provide support via issues, so feel free to read the docs or come to the weekly community meeting.

https://docs.openfaas.com/deployment/

https://docs.openfaas.com/tutorials/training/

https://docs.openfaas.com/community/

Alex
