### ISSUE TITLE
how to upload file to faas function?

### ISSUE THREAD

**Issue by unnimona** [openfaas/faas#1754]
#this works fine
curl -X POST http://10.46.239.201:8080/function/name -d "text"

#this does not sends a file to function 
curl -X POST http://10.46.239.201:8080/function/name --form file=@hello.txt

function dockerfile
ENV fprocess="xargs script.sh"

how to make the docker file receive the file input and send to bash script? any guide or tutorial to follow?

**Comment by alexellis** [comment]
Sorry, it seems like you've misunderstood how we use the issue tracker. I get it, some projects
give away free support via their issue tracker. We only use it track bugs and our own work.

For community support, you can check out our free training or come along to a weekly community call
and ask your questions there

https://docs.openfaas.com/community/
