### ISSUE TITLE
Is it possible to support multithreading in pyhton template function

### ISSUE THREAD

**Issue by m199369309** [openfaas/faas#1755]
I want to use multithreading in python functions to improve the processing power of the program, how do I need to modify the python template

**Comment by alexellis** [comment]
Hi 

Thanks for your interest 

Unfortunately we can't answer any issues where people delete the issue template. 

I'll get this closed, feel free to open another one when you have the time to explain what you're doing properly including which template and what kind of code you're trying to run. 

Alex
