### ISSUE TITLE
How to get an image as a http response in openfaas?

### ISSUE THREAD

**Issue by srinu49** [openfaas/faas#1757]
How to get an image as a http response in openfaas?

## Expected Behaviour
Image file should be expected as a function response.

## Current Behaviour
Response status: 200
Response body: 2275 byte(s) received
And a file downloaded with information like this is below:

ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --disable-debug
libavutil 56. 70.100 / 56. 70.100
libavcodec 58.134.100 / 58.134.100
libavformat 58. 76.100 / 58. 76.100
libavdevice 58. 13.100 / 58. 13.100
libavfilter 7.110.100 / 7.110.100
libavresample 4. 0. 0 / 4. 0. 0
libswscale 5. 9.100 / 5. 9.100
libswresample 3. 9.100 / 3. 9.100
libpostproc 55. 9.100 / 55. 9.100
Input #0, image2, from '/tmp/4f4359b646fb4d5785a8586297727630_ele.JPG':
Duration: 00:00:00.04, start: 0.000000, bitrate: 3541048 kb/s
Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 6000x4000, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
Stream #0:0 (mjpeg) -> fps
scale -> Stream #0:0 (mjpeg)
Press [q] to stop, [?] for help
[swscaler @ 0x7f12208d8080] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/tmp/4f4359b646fb4d5785a8586297727630_compressed_ele.JPG':
Metadata:
encoder : Lavf58.76.100
Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown, progressive), 720x720, q=2-31, 200 kb/s, 5 fps, 5 tbn
Metadata:
encoder : Lavc58.134.100 mjpeg
Side data:
cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame= 1 fps=0.0 q=5.9 size=N/A time=00:00:00.20 bitrate=N/A speed=0.894x
frame= 1 fps=0.0 q=5.9 Lsize=N/A time=00:00:00.20 bitrate=N/A speed=0.875x
video:75kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
{'file_name': 'ele.JPG'}
<HttpResponse status_code=200, "image/jpg">

## Steps to Reproduce (for bugs)
Steps to invoking the vid-compress function
1. upload an image ele.JPG into minio bucket.
2. Request body should be {"file_name":"ele.JPG"} select download option and then click Invoke. 
Code available at https://github.com/srinu49/Image-compression

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu

* Code example or link to GitHub repo or gist to reproduce problem:
* https://github.com/srinu49/Image-compression

File: handler.py
.........................................
import json
import os
import uuid
from PIL import Image  
import PIL  
import requests
#from django.http import HttpResponse

from minio import Minio
import ffmpeg

def handle(st):
   
    req = json.loads(st)
    print(req)

    mc = Minio(os.environ['minio_hostname'],
                  access_key=os.environ['minio_access_key'],
                  secret_key=os.environ['minio_secret_key'],
                  secure=False)

    source_bucket = os.environ['source_bucket']
    dest_bucket = os.environ['dest_bucket']

    file_name = req['file_name']
    my_uuid = gen_uuid()

    file_path = f"/tmp/{my_uuid}_{file_name}"
    mc.fget_object(source_bucket, file_name, f"/tmp/{my_uuid}_{file_name}")
  
    (
        ffmpeg
        .input(file_path)
        # .hflip()
        .filter('fps', fps=5, round='up')
        .filter('scale', w=720, h=720)
        .output(f"/tmp/{my_uuid}_compressed_{file_name}")
        .run()
    )

    mc.fput_object(dest_bucket, file_name, f"/tmp/{my_uuid }_compressed_{file_name}")
    
 
    f = Image.open(f"/tmp/{my_uuid }_compressed_{file_name}")  
   
    f.save("datacompressed.jpg")

    with open(f'/tmp/{my_uuid }_compressed_{file_name}','rb') as rf:
        with open('./datacompressed.jpg','wb') as wf:
            for line in rf: 
                wf.write(line)
            # shutil.copyfileobj(rf.write().decode('utf-8'), wf)
            return print('Image sucessfully Downloaded: ',file_name)
  
def gen_uuid():
    return str(uuid.uuid4().hex)

File: vid-compress.yml
............................................................
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  vid-compress:
    lang: dockerfile
    handler: ./vid-compress
    image: srinivasuoh/vid-compress:latest
    environment:
      write_debug: true
      minio_hostname: "my-minio-fs.default.svc.cluster.local:9000"
      minio_access_key: "minio"
      minio_secret_key: "minio123"
      source_bucket: "source-videos"
      dest_bucket: "compressed-videos"
      content_type: "image/jpg"
       
    

File: requirements.txt
.........................................................
ffmpeg-python
minio
requests
Pillow
Django

**Comment by alexellis** [comment]
Hi, thanks for your interest in OpenFaaS

We cover this topic in a free training course:

https://docs.openfaas.com/tutorials/training/#introduction-to-serverless-on-kubernetes

I'll get your issue closed, but please bear in mind that we do not provide free support via GitHub

We hold a weekly call where you can attend and ask questions: 

https://docs.openfaas.com/community/

Or if you'd like to explore a commercial relationship, you can do so via https://openfaas.com/support

Alex
