### ISSUE TITLE
regarding serverless for everyone ebook and jetstream + faasd

### ISSUE THREAD

**Issue by unnimona** [openfaas/faas#1758]
i am a school student
i want to test jetstream async with faasd.
is this jetstream? https://github.com/openfaas/nats-queue-worker
is it possible? is there a guide to do that?
should i buy your ebook for that or sponsor you on github? which to choose

need help

**Comment by alexellis** [comment]
Hi @unnimona JetStream works with faasd but is for OpenFaaS Pro customers.

Feel free to reach out to us with some more information at: https://openfaas.com/support/

Regards,

Alex

**Comment by alexellis** [comment]
/set title: How can I get access to JetStream for faasd
