### ISSUE TITLE
Technical support request for timeouts

### ISSUE THREAD

**Issue by JesseStutler** [openfaas/faas#1766]
Hi, I use stress testing tools like jmeter or hey to stress some functions, but I find that there are many error requests, the HTTP status code is 502 bad gateway, and the delay is always about 10 seconds. I find that in gateway, there are many error records like:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/38534065/201343820-77f9cf02-b9cb-432b-9715-739f0c7ceda7.png"> I didn't set timeout in client-side or directly cancel the HTTP request, I don't know why gateway is always reporting context canceled.

And I thought that it's because watchdog sets the timeout, and I configure the exec-timeout to 60 seconds, but the request is still error and will be canceled within 10 seconds. I don't know why....Any ideas?
![image](https://user-images.githubusercontent.com/38534065/201344338-61e7f5d7-1f62-495b-b55a-59ee8b4cc2a4.png)

**Comment by rgee0** [comment]
Did you consult the following prior to your testing?

https://docs.openfaas.com/architecture/performance/

**Comment by alexellis** [comment]
Hi there, you'll need to fill out the whole issue template. We don't have enough information to help you here

Alex

**Comment by alexellis** [comment]
And for extending timeouts please see:

https://docs.openfaas.com/tutorials/expanded-timeouts/

**Comment by alexellis** [comment]
/set title: Technical support request for timeouts.

**Comment by JesseStutler** [comment]
@rgee0 @alexellis  Hi, thanks for replying. Sorry to open an issue because I didn't find openfaas slack channel or discord...I have figured out that it's because jmeter's problem, I will try to find out where jmeter sets the default 10 seconds timeout. I will close this issue. But before that, is there any way like slack or discord something to share my simple questions...? Thanks.

**Comment by rgee0** [comment]
Derek close
