### ISSUE TITLE
WSL + OpenFaas: can't connect to nats

### ISSUE THREAD

**Issue by PierrickI3** [openfaas/faas#1771]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?

Install OpenFaas on my K8S cluster

## Who is this for?

Me

When I try to install OpenFaaS using faas-netes in k8s using WSL under Windows, I get the following in both the `gateway` and `queueworker` pods:

```console
OpenFaaS Gateway - Community Edition (CE)

Version: 0.25.2 Commit: bc2eeff4678407583faec982c1c7d1da915dd60c
Timeouts: read=5m2s	write=5m2s	upstream=5m0s
Function provider: http://127.0.0.1:8081/

2022/12/05 15:58:31 Async enabled: Using NATS Streaming.
2022/12/05 15:58:31 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
2022/12/05 15:58:31 Connect: nats://nats.openfaas.svc.cluster.local:4222
2022/12/05 15:58:33 dial tcp 10.101.241.144:4222: i/o timeout
```

I have opened the following [issue](https://github.com/openfaas/faas-netes/issues/1045) on the `faas-netes` repository but I don't think this is related to helm since I have tried `arkade` also to deploy it and I get the same issue.

## Expected Behaviour

Both the `gateway` and the `queueworker` pods should be able to connect to nats

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)
1. Deploy a K8S cluster using Docker Desktop in WSL (Ubuntu 22.04)
2. Use helm to deploy OpenFaaS
3. Gateway and Queue Worker never manage to connect using nats

## Context

Using WSL in Windows (Ubuntu 22.04)

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```console
CLI:
 commit:  0074051aeb837f5f160ee8736341460468b5c190
 version: 0.15.4
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:44 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):

Ubuntu 22.04 in WSL (Windows)

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

I have been on it for more than a week. I tried setting `NO_PROXY` using `export no_proxy=".svc,.svc.cluster.local"` but no changes.

I also checked this section on your website:
```
The gateway must be able to talk to nats and prometheus. If these are crashing, you probably have networking issues preventing containers from talking to each over or looking up each other over DNS.
```

The DNS does not seem to be the issue here as it resolved the address. Is there a command I can use to test the connection between the gateway and the nats pod?

Any help would be greatly appreciated.

**Comment by alexellis** [comment]
Hi, I was certain I had hit send on my message 2 days ago.

We cannot debug your environment for you, but I can point you in the right direction.

This error happens due to a misconfiguration of networking or DNS.

Try deploying an Nginx pod in one namespace and a curl pod in the second, if they fail to reach each other, that's effectively the same thing as is going on for you here with OpenFaaS Community Edition.

You may want to contact Microsoft or Docker for support for the WSL product, since we have no issue with OpenFaaS in correctly configured environments we'll get this issue closed now.

Alex

**Comment by PierrickI3** [comment]
Thanks. It ended up working all of a sudden after I restarted Docker Desktop. No idea why. However, in the meantime, I have move on to another topic. I will definitely remember this if this happens again.
