### ISSUE TITLE
Feature Request: Support for mounting volumes

### ISSUE THREAD

**Issue by ResistanceIsUseless** [openfaas/faas#1773]
I know this topic has come up previously but the issue was closed. I saw a lot of excellent reasons why this feature was needed. Even some users moving to other frameworks to be able to have that feature. @alexellis  has your position on this changed at all? It would be really nice to have this as an option for testing. I'm working on some automation and it would be really helpful to have the option to mount a persistent volume to a storage account. I'm using Azure Kubernetes with OpenFaaS and NodeRed to automate different CLI commands. So being able to mount a storage account would be a huge help at this point. If you still don't think it's a feature you would add. Do you think you could do a blog post on using kubectl to deploy some functions with volume options?

**Comment by alexellis** [comment]
Hi @ResistanceIsUseless 

We would need you to fill out the whole issue template.

Feel free to open another issue and fill out the context of:

Why this is needed.

Who this is for.

Why the alternatives can't work - a normal Kubernetes deployment, Minio/S3.

Regards,

Alex
