### ISSUE TITLE
Openfaas + Istio -> gateway can't call functions

### ISSUE THREAD

**Issue by CC007** [openfaas/faas#1780]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues) (found #1721, but it didn't provide a solution)

## Why do you need this?
I'm trying to invoke OpenFaaS functions in a cluster that uses Istio. 

## Expected Behaviour
Invoking a function (like `env`) either by using a URL or through faas-cli should work.

## Current Behaviour
Trying to invoke the `env` function gives a 503 error with the message `upstream connect error or disconnect/reset before headers. reset reason: connection termination`

## Steps to Reproduce (for bugs)
1. install istio helm chart
2. enable istio on `default` and `openfaas` namespace
3. install openfaas helm chart with: 
    - `istio.mtls: true`
    - `gateway.directFunctions: true`
    - `gateway.probeFunctions: true`
    - `functionNamespace: default`
4. deploy `env` function
5. call `http://<gateway domain name>/system/function/env?namespace=default` (which works)
6. call `http://<gateway domain name>/function/env?namespace=default` (this gives a 503 with the message `upstream connect error or disconnect/reset before headers. reset reason: connection termination`

## Context
 - Setting up an istio gateway and virtual service directly does allow me to call the function, so the service and pod are up and running.
 - using `faas-cli invoke env` I get the same error
 - I tried with both the `gateway` and `gateway-external` service
 - Kiali shows me the following graph:
 
![afbeelding](https://user-images.githubusercontent.com/5381337/219220239-025a0f50-ead4-4775-a2d4-4ca8048401e3.png)
The red line to `PassthroughCluster` shows that the host that the traffic is trying to reach IS the `env` service, but 100% of the traffic is giving a 5xx status

## Your Environment

* FaaS-CLI version: 
```
CLI:
 commit:  45c1d906b77709adde47c35bed868026266389e8
 version: 0.15.9

Gateway
 uri:     https://<gateway domain name>
 version: 0.26.3
 sha:     a128df471f406690b1021a32317340b29689c315


Provider
 name:          faas-netes-ce
 orchestration: kubernetes
 version:       0.16.4
 sha:           caf1eb0a25153082f1305fba7656db9a5d8a6676
```

* Docker version : 20.10.17

* Are you using OpenFaaS on Kubernetes or faasd? on Kubernetes

* Operating System and version: client on WSL Ubuntu (windows 10 host), k8s server on Ubuntu VM (harvester + rancher setup)

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

Env logs when calling function through the working route (Istio gateway -> env):
```
2023/02/15 23:55:21 Forking fprocess.
2023/02/15 23:55:21 Wrote 2974 Bytes - Duration: 0.000646s
```
No logs in env when calling through the gateway (Istio gateway -> OpenFaaS gateway -> env)
gateway shows these logs:
```
2023/02/15 23:58:41 Forwarded [GET] to /function/env?namespace=default - [503] - 0.0015s 
```

**Comment by alexellis** [comment]
Hi thanks for your interest in OpenFaaS.

For Istio support (a commercial feature) you'd need OpenFaaS Pro, learn more at https://openfaas.com/pricing

If you'd like a free trial or to discuss options, you'll find a link to contact us there.

Regards,

Alex
