### ISSUE TITLE
How does autoscaling work

### ISSUE THREAD

**Issue by QWQyyy** [openfaas/faas#1781]
hello，I am a serverless student，we deploy some python3 runtime function in the OpenFaaS，and use apachebench send large POST request to test it auto extend performance. But, we still not see Replicas extend，we deploy function code is：
```bash
faas-cli deploy -f rc-r.yml --label com.openfaas.scale.max=10 --label com.openfaas.scale.target=3 --label com.openfaas.scale.min=1 --label com.openfaas.scale.target-proportion=0.6
```
and we also try set com.openfaas.scale.target=1 and com.openfaas.scale.target-proportion=0.1，but it can not extend？

we python3 function code is：
```python
from rediscluster import RedisCluster
import json
import time
def handle(req):
  json_req = json.loads(req)
  key = str(json_req["key"])

  nodes = [
        {'host': '192.168.0.113', 'port': '6001'},
        {'host': '192.168.0.124', 'port': '6001'},
        {'host': '192.168.0.232', 'port': '6001'},
  ]

  start = time.time()
  src = RedisCluster(startup_nodes=nodes, decode_responses=True)
  res = src.get(key)
  t = float(time.time() - start) * 1000

  result = {"res": str(res), "time": str(t)}
  return json.dumps(result)
```
we apachebench test script code is:
```bash
ab -n 100000000 -c 20 -t 60 -p ./data -T "application/json"  -v 4 "http://192.168.0.113:31112/function/rc-r"
```
and we also try very much args in -n or -c 、-t，but it can not work.
it is apachebench test result：
![image](https://user-images.githubusercontent.com/54056797/223386479-8b09ef59-40c4-42c6-a00e-3bdae8403d38.png)
it is my `faas-cli ls` display Replicas result：
![image](https://user-images.githubusercontent.com/54056797/223386672-137ea5af-643b-4d44-8f7c-9ceaad44fdaa.png)
this result born in we all test.

my hardware：3 * 2vCPU 4GB public cloud server.

I hope OpenFaaS group give me some suggestion，such as setup、hardware or software，and ask me why it Replicas  could not extend？
thank you！
give you best wish！

**Comment by alexellis** [comment]
Hi @QWQyyy it looks like you've got confused and are trying to apply OpenFaaS Pro auto-scaling to OpenFaaS CE

For OpenFaaS CE see: https://github.com/openfaas/workshop

Thanks for your interest, I'll get this closed now.

Alex
