### ISSUE TITLE
Can't find openfaas/queue-worker:0.11.2 and openfaas/basic-auth-plugin:0.20.1	

### ISSUE THREAD

**Issue by tshah010** [openfaas/faas#1789]
Why are they not available in https://hub.docker.com/u/openfaas?

## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
our jobs are failing because these images are unavailable

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
OpenFaaS on Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi

OpenFaaS is hosted on ghcr.io [not on the Docker Hub](https://www.openfaas.com/blog/how-does-docker-hub-affect-openfaas/) and it's been that way for ~ 2 years.

It sounds like you need to update your Helm chart... why are you using such ancient versions of things?

Alex
