### ISSUE TITLE
Proposal: Make the side nav toggleable on FaaS UI

### ISSUE THREAD

**Issue by kenfdev** [openfaas/faas#180]
## Expected Behaviour

When the screen is smaller than a certain width (probably 960px?), the side nav should be hidden and toggleable.

## Current Behaviour

When the screen is smaller than a certain width (probably 960px?), the side nav is hidden but not toggleable. Therefore, people who don't know this behavior get lost in how to create function, find functions, etc.

## Possible Solution

Add a toggleable icon on the top left (perhaps?).  And let people see the side nav even though the screen width small.

## Steps to Reproduce (for bugs)

1. Open the gateway UI
2. Make the browser window width small.
(Tested it on Chrome and Firefox but all the browsers should have the same problem)

## Context

If the side nav gets hidden, it's pretty much impossible to do anything with the UI.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:
Screenshot
![2017-09-11 10 06 37](https://user-images.githubusercontent.com/3941889/30254850-f26c3d92-96d8-11e7-994b-19b93f81134a.png)

**Comment by kenfdev** [comment]
I'll take a look at this this week if there's no problem on that.

**Comment by alexellis** [comment]
Please do

**Comment by kenfdev** [comment]
@alexellis how about something like this? Just added a few lines for a toggle button and added a svg in `assets/img/icons/menu.svg` from the [material design icons](https://materialdesignicons.com/).

![toggle_sidenav](https://user-images.githubusercontent.com/3941889/30281827-73644866-974e-11e7-8086-80967b710237.gif)

I'll create a PR if it's ok or edit it more if there is more to do.
The `bootstrap.js` is getting cumbersome so maybe we should componetize it in some point.

**Comment by johnmccabe** [comment]
@kenfdev looks good 👍

**Comment by johnmccabe** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
Very nice 💯

**Comment by alexellis** [comment]
Derek add label: priority/middle
