### ISSUE TITLE
Problem  on  deploying a new function with faas-cli deploy

### ISSUE THREAD

**Issue by CriZ-sd** [openfaas/faas#1800]
## My actions before raising this issue
- [ x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ x] Read/searched [the docs](https://docs.openfaas.com/)
- [ x] Searched [past issues](/issues)

## Expected Behaviour
 Hello, i am creating and deploying a new function using faas-cli new and faas-cli up (or faas-cli build + faas-cli push + faas-cli deploy) but the function doesn't appear at the available functions on openfaas.  The expected behaviour was that after deploying the new function this should appear by running the faas-cli list command.  

## Current Behaviour
After succesfully (without any error) running the faas-cli new and faas-cli up commands the new function doesn't appear by running the faas-cli list command. Also, i can't invoke the function, it actually, doesn't exist. 

## Steps to Reproduce (for bugs)

1. docker swarm init
2. git clone https://github.com/openfaas/faas
3. cd faas
4. git checkout 0.6.5
5. ./deploy_stack.sh
6. faas-cli new --lang=python3-debian hello
7. docker login (with my username and paasword from dockerhub)
8. nano hello.yaml (to add my dockerhub username on the image path )
9. faas-cli build -f ./hello.yml
10. faas-cli push -f hello.yml
11. faas-cli deploy -f hello.yml
12. faas-cli list 
And after the 12 step the new function (hello) doesn't appear and i also can't invoke it .
Am i missing any set up step or is there anything else that i need to do ?

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
faas-cli version 0.16.4
* Docker version `docker version` (e.g. Docker 17.0.05 ):
docker version 20.10.21
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
I am using docker swarm with open-faas
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 22.04.2 LTS

**Comment by alexellis** [comment]
Docker Swarm was deprecated several years ago. 

Use faasd or K3s instead. Both are written about in the docs. 

Let me know if I can help further.
