### ISSUE TITLE
Cannot connect to OpenFaaS on URL: http://xx.xxxx:31112

### ISSUE THREAD

**Issue by wiluen** [openfaas/faas#1802]
I rewrite source code in faas-nete in Openfaas CE.  when I build the new faas-netes image and re-deploy. I can't use faas-cli , and can't open ui. then I deploy the old version, it still don't work. but the faas functions can still work!

**Comment by alexellis** [comment]
Sorry we can't support you if you fork the project. I'd suggest using. CE as it is if you'd like our help or check out our commercial offerings at openfaas.com

Bear in mind that we need everyone to use the issue template, if you'd take the time to do that we may have been able to give you a pointer
