### ISSUE TITLE
Request for CUDA access

### ISSUE THREAD

**Issue by Abhishekghosh1998** [openfaas/faas#1805]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

## Expected Behaviour

I have a use case that requires a container to interact with the base operating system for interprocess communication. I can achieve that using the `--ipc=host` option in the `docker run` command. 

For example:
`docker run -it --ipc=host my_custom_image:latest`

I have packaged the required code in a Dockerfile (for OpenFaas, using the Dockerfile template). The code works fine for basic functionality, but it fails when I need to communicate with the host os. 

On a Kubernetes cluster, I tried to achieve the same functionality of using the `hostIPC` namespace as follows:

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  hostIPC: true
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: my_custom_image:latest
...
```

I am not sure, but since OpenFaaS uses Dockerfile to build the image of the function to run, and then pushes it to the registry and then deploys it, I guess during the deployment or function triggering, it executes a command like `docker run` or Kubernetes pod creation.

I want to add that `--ipc=host` to this `docker run` command which spawns the container for the function. Or something equivalent to `spec: hostIPC: true` as in the pod description .yml file.

Can you help me with how this functionality can be achieved? Any specific field in the `stack.yml` file to deploy the function?

For example, I have the following stack yml file for a function named `print-1`:
![image](https://github.com/openfaas/faas/assets/43134757/9b1b8798-7156-4b8b-9749-492d3b480990)

What field to add in the above yml file so that the deployment for pod in kubernetes shows `spec: hostIPC: true`:
![image](https://github.com/openfaas/faas/assets/43134757/70766419-53de-4f0b-b4ba-ef2eeb84cbe7)

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ X] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.16.10

* Docker version `docker version` (e.g. Docker 17.0.05 ): 24.0.2

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? I am using OpenFaaS on a Kubernetes cluster created by `kind` utility

* Operating System and version (e.g. Linux, Windows, MacOS): Linux 5.15.0-76-generic

* Code example or link to GitHub repo or gist to reproduce problem: 

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Is host IPC actually needed to use a GPU?

Most people have used node scheduling constraints and that has worked for them?

**Comment by alexellis** [comment]
https://docs.openfaas.com/reference/profiles/#use-tolerations-and-affinity-to-separate-workloads

**Comment by Abhishekghosh1998** [comment]
@alexellis Yes, I was trying to use the GPU with OpenFaaS. I tried to use the `Kubernetes Webhook` idea you gave me. I am not sure whether `host IPC` is required or not. However, the pointers which you gave, I shall look into it. Thanks for the same.

**Comment by alexellis** [comment]
If you want to use a GPU, I don't believe you need host IPC. I've never had someone say they needed it, and a number of people have used GPUs before.

Make sure docker-nvidia or containerd-nvidia is properly configured then use a scheduling constraint.
