### ISSUE TITLE
Can multiple functions be run on a single runtime？

### ISSUE THREAD

**Issue by SilenceShine** [openfaas/faas#1808]
Can multiple functions be run on a single runtime？

**Comment by alexellis** [comment]
Hi @SilenceShine 

We'd like to help but don't know how. I'll close this issue as you haven't taken the time to fill out the issue template, or give us sufficient context / info to help you.[

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

Alex
