### ISSUE TITLE
requests schedule policy in openfaas

### ISSUE THREAD

**Issue by wiluen** [openfaas/faas#1813]
hi, I am a serverless student,  it seems openfaas request schdule policy is based on FCFS (first come first serve) , and I want to design a request schedule policy , e.g., to let import request have a bigger priority, and it can be schedule earlier. how can I do this ?   

my enviroment is based on K8S with 8 nodes, each node have 8cores and 16G memory.

**Comment by alexellis** [comment]
Hi @wiluen you will need to fill out the whole issue template if you want us to be able to help.

We have no context about what you've tried, why you've assumed that "FCFS" applies, or how you've proven that to be the case.

Try to think through what you are asking for - and give as much detail as possible before raising an issue.

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

I'm going to get this closed, but will re-open if you do the above.

Alex
