### ISSUE TITLE
Is there a workflow tool for OpenFaaS?

### ISSUE THREAD

**Issue by Abhishekghosh1998** [openfaas/faas#1814]
This is not exactly an issue, but request to know whether a feature is available in OpenFaaS or not.
I was thinking of [function composition in OpenFaaS](https://ericstoekl.github.io/faas/developer/chaining_functions/). Apache OpenWhisk provides action sequences and `composer`, which helps fancy `parallel` execution of functions. In OpenFaaS, do we have some equivalent of `composer`?

## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

## Why do you need this?
To accomplish Amazon States Language (ASL) like feature in OpenFaaS. 
Especially Apache OpenWhisk provides it. I was wondering, how is it made available in OpenFaaS. (If at all)

## Who is this for?
Anyone, who wants to use `function composer` like feature available in Apache OpenWhisk.

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?
No.

## Expected Behaviour
Instead of just simple function chaining, I want to have the facility to reach a stage in the chain, where, function invocation shall branch out in parallel, and then they shall join to the next function in the chain. Kind of:

```	
			   f1
			    |
			    |
			   f2
			    |
			    |
			   f3
			   /|\
			  / | \
			 f4 f5 f6     <-------- f4, f5, f6 executes in parallel.
			  \ | /
			   \|/
			    f7
```

## Current Behaviour
I could not find any such behavior.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
/set title: Is there a workflow tool for OpenFaaS?

**Comment by alexellis** [comment]
There is no workflow automation tool, however many people use asynchronous functions with an X-Callback-Url instead to build in orchestration.

See the examples from OpenFaaS Standard for how we've shown how to do this at scale, including fan-in and fan-out.

https://docs.openfaas.com/openfaas-pro/jetstream/

**Comment by Abhishekghosh1998** [comment]
@alexellis What are your thoughts on the following: [Faas-flow - Function Composition for ](https://github.com/s8sg/faas-flow#faas-flow---function-composition-for-openfaas)[OpenFaaS](https://github.com/openfaas/faas)
