### ISSUE TITLE
Permanent Port Forwarding 

### ISSUE THREAD

**Issue by shenferhat** [openfaas/faas#1817]
when we type "kubectl port-forward -n openfaas svc/gateway 8080:8080" or with '&' its not permanent, i have to put this command each system startup, i think i have to edit "yml" file but i don't know where to edit, can you tell how we can make this forwarding permanent?

regards.

**Comment by alexellis** [comment]
Hi @shenferhat we need all users to fill out the proper issue template, so we have the full context.

I'd recommend you read my two articles covering this to learn your options, including how inlets can give your "permanent forwarding"

* https://inlets.dev/blog/2022/06/24/fixing-kubectl-port-forward.html
* https://blog.alexellis.io/primer-accessing-kubernetes-services/

Alex
