### ISSUE TITLE
[Bug] OpenFaas CE Unexpected status: 400, message: unable to create function, maximum: 30

### ISSUE THREAD

**Issue by pgmgb** [openfaas/faas#1818]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

## Expected Behaviour
We see the following error after upgrading the OpenFaas CE Helm chart from `14.1.10` to `14.1.14` :
```bash
faas-cli deploy -f .\functions\dummy.yml --gateway $OPENFAAS_GATEWAY
Deploying: dummy-function.

Unexpected status: 400, message: unable to create function, maximum: 30
```

It is not possible to deploy new functions. Editing (redeploy) existing ones works.

## Current Behaviour

We would expect to be able to deploy new functions without an error.

## Steps to Reproduce (for bugs)

1. Deploy OpenFaas CE Helm chart `14.1.14`.
2. Try to deploy a new (not existing) function with `faas-cli deploy -f` command
3. See the error

## Context
 
We did not see any limits in the documentations or the Helm chart parameters. Therefore, I'm not sure, if that's a bug?

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.16.16

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? Yes

* OpenFaas Helm chart version: 14.1.14

**EDIT:**
Issue can be closed

**Comment by alexellis** [comment]
Thanks for using OpenFaaS.

The Community Edition has been described as "Run functions for non-production or experimental use" for a couple of years at least now.

I hope that if you are running it at scale in production, you bear this in mind.

Alex
