### ISSUE TITLE
AfterBurn for Node.js Implementation

### ISSUE THREAD

**Issue by genexp** [openfaas/faas#182]
## Expected Behaviour
I'd like to help create or test an AfterBurn example for NodeJS.

## Current Behaviour
Examples exist for Java and Python.  Let's make more!

## Context
We use NodeJS as our main execution environment for small JS based functions.  Because we use them mostly for data processing, we'd like them to be as fast as possible and not incur the overhead of starting up Node each time.

## Your Environment
Kubernetes (FaaS-netes)

**Comment by alexellis** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek add label: skill/intermediate

**Comment by alexellis** [comment]
Derek add label: priority/medium

**Comment by alexellis** [comment]
Initial work at - https://github.com/alexellis/nodejs-afterburn

**Comment by alexellis** [comment]
Ping @genexp

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by austinfrey** [comment]
@alexellis you mentioned the initial parser needed some improvements? if you could elaborate a bit, I could try and make some headway

**Comment by alexellis** [comment]
Hi - they are using a buffer that assumes each "data" element received is a whole payload. Instead it needs to buffer until "done" using some kind of "peaking".

https://github.com/alexellis/nodejs-afterburn

**Comment by Marak** [comment]
@alexellis -

I took a look at the afterburn node.js example as well as some of the other afterburn code.

I'm curious, will using afterburn allow for state to be acquired in the process? At first glance it looks like https://github.com/alexellis/nodejs-afterburn can acquire state based on custom `handler.js` files. If so, this could lead to unexpected behavior of function.

**Comment by alexellis** [comment]
Derek close: n/a
