### ISSUE TITLE
RPC and openfaas

### ISSUE THREAD

**Issue by noura2030** [openfaas/faas#1821]
Hi, 
I am doing college project I went to say if I can use Remote Procedure Call<<RPC>> . IF yes, how can I implement that ? Is there any tutorial for that. 
The second question is about the chain function, how I can do that in openfaas . I get some old links but It seems doesnot work with me.

**Comment by alexellis** [comment]
Hi @noura2030 

The GitHub issue tracker is not the right place to get support and ask questions.

Please attend the weekly call instead: https://docs.openfaas.com/community/

Alex
