### ISSUE TITLE
Openfaas install gateway Crash

### ISSUE THREAD

**Issue by a48446** [openfaas/faas#1833]
When encountering a crash scenario with the OpenFaaS gateway during installation, you need to change the serviceType in the values.yaml file to LoadBalancer. This is because OpenFaaS defaults to using NodePort for deployment, and as a result, there won't be an External-IP assigned after installation for IP distribution. Therefore, you must modify the faas-netes configuration file to change the External-IP to be obtained using the LoadBalancer approach.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):  0.16.23

* Docker version `docker version` (e.g. Docker 17.0.05 ): 23.0.1

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? Yes

* Operating System and version (e.g. Linux, Windows, MacOS): ubuntu

* Code example or link to GitHub repo or gist to reproduce problem: https://github.com/a48446/ML-openfaas/tree/main

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Hi, you will need to provide us with much more detail than this.

There is no reason that a NodePort would cause the container to crash, so look at the troubleshooting guide and work through it line by line. You should find the problem.

Alex

**Comment by alexellis** [comment]
Here is a confirmation that the NodePort configuration works as expected, no crashes.

<img width="1470" alt="Screenshot 2024-02-02 at 08 33 27" src="https://github.com/openfaas/faas/assets/6358735/96efdbd7-ccfc-41cf-9410-0c6fb086651f">

Please fill out the whole issue template in future, and give us as much specifics as you can including K8s version, hosting platform, versions, etc
