### ISSUE TITLE
Unable to find the http_request_duration_seconds metric on my deployed images

### ISSUE THREAD

**Issue by camilovietnam** [openfaas/faas#1839]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
Hello! I have deployed a Go function with a container, and I would like to be able to display a dashboard in Grafana to show how many requests are returning 200, 404, 500, etc. I am deploying three copies of the same container build with faas-cli, with the host names `echo-go1`, `echo-go2` and `echo-go3`.

## Who is this for?
This is just for a research project for university. 

## Expected Behaviour
The endpoint `http://echo-go1:8081/metrics` should show the `http_request_duration_seconds` metric. However, it is not available there. The page https://docs.openfaas.com/architecture/metrics/ mentions that `The http_request* metrics record the latency and statistics of /system/* routes` so I'm not sure if this is actually the expected behaviour, or if I should be looking somewhere else for this. 

## Are you a GitHub Sponsor (Yes/No?)
No

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
* CLI:
 commit:  6e26edd4f9ae0d0fac9d6916a1b831f4f41d8096
 version: 0.16.27

* Docker version `docker version` (e.g. Docker 17.0.05 ):
  Version:           25.0.3

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
No, just running the container  built via faas-cli build, using docker-compose

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOs Sonoma 14.4.1

This is the first time I use Open-Faas, so please let me know if you need any additional information. Thanks!

**Comment by rgee0** [comment]
Someone better informed might input later, but I think your answer is in the documentation that you link to:

![image](https://github.com/openfaas/faas/assets/16418793/5ee48a15-2fc8-407c-b4e2-167bd2bd8c65)


![image](https://github.com/openfaas/faas/assets/16418793/3280895b-f206-42af-a74e-e17930a2490c)

I expect that you're not using Pro, and so would only see the basic metrics.  As you only state what you don't see at `http://echo-go1:8081/metrics` its not possible to say for certain that what you are seeing is the basic set.  This should be easy for you to determine though.

**Comment by camilovietnam** [comment]
> Someone better informed might input later, but I think your answer is in the documentation that you link to:
> 
> ![image](https://private-user-images.githubusercontent.com/16418793/329855198-5ee48a15-2fc8-407c-b4e2-167bd2bd8c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjMxODUsIm5iZiI6MTcxNTUyMjg4NSwicGF0aCI6Ii8xNjQxODc5My8zMjk4NTUxOTgtNWVlNDhhMTUtMmZjOC00MDdjLWI0ZTItMTY3YmQyYmQ4YzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZjhhYWM5N2RlYmQ4YmQ3YTIzZTU4MjkwNTE2N2YyOGJiOGQ5NWEzZWM0MDljNzFkNTcxNjg5M2RiZTRhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sfjk5bxLxOhEs6BBTkNo6kBPZ8hsOVhPbV-aTm26Bu8)
> 
> ![image](https://private-user-images.githubusercontent.com/16418793/329855252-3280895b-f206-42af-a74e-e17930a2490c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjMxODUsIm5iZiI6MTcxNTUyMjg4NSwicGF0aCI6Ii8xNjQxODc5My8zMjk4NTUyNTItMzI4MDg5NWItZjIwNi00MmFmLWE3NGUtZTE3OTMwYTI0OTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ODkxNTdhMTZiNDY2OGU1YmNjMzUwNzMxNDg2ZDU4MjU0NDNmYzg5OWQzYjMzYjQ4NzE3YmQ5MTZhMzI3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Wnre40rW8fIuR9Tm5j4lA4yBAyxvHINGnluikBfIzE)
> 
> I expect that you're not using Pro, and so would only see the basic metrics. As you only state what you don't see at `http://echo-go1:8081/metrics` its not possible to say for certain that what you are seeing is the basic set. This should be easy for you to determine though.

Ah, that was an easy question to answer. Indeed, I just missed that header mentioning the "Pro" edition. Thanks, I will close the ticket.

**Comment by alexellis** [comment]
Thanks for the interest and thanks @rgee0 for answering.

If you'd like to try out OpenFaaS Standard, [feel free to reach out](https://openfaas.com/pricing).
