### ISSUE TITLE
[Question] Pricing options for freelance/solo developers?

### ISSUE THREAD

**Issue by Noonlord** [openfaas/faas#1841]
Hello,

Sorry if this doesn't belong here, I tried to find another means of communication but this is all I could find. 

Do you have any other unlisted pricing options for solo developers/freelancers/small start-up companies? 15 functions and public repository limitations are a bit tough on Community Edition. And 1000$/mo is a bit much for me. Is there any other option that I am not aware of? Thanks for the help!

**Comment by alexellis** [comment]
Hi there is a form you can contact us through on the website, this is very clearly marked at the bottom of this page:

https://www.openfaas.com/purchase/

Looking forward to hearing from you.

Alex
