### ISSUE TITLE
 [Question] How to Deploy OpenFaaS on Docker Compose in Non-Swarm Mode

### ISSUE THREAD

**Issue by 876192453** [openfaas/faas#1844]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [√ ] Read/searched [the docs](https://docs.openfaas.com/)
- [√ ] Searched [past issues](/issues)

Why do you need this?
We are seeking guidance on deploying OpenFaaS in a Docker Compose environment that is not managed by Swarm, specifically for custom projects tailored to the needs of smaller clients.

Expected Behaviour
A feasible method to deploy OpenFaaS components using Docker Compose in Standalone Mode, allowing us to publish functions as we would in a Swarm environment.

Current Behaviour
Currently, we are unable to find documentation or examples that illustrate deploying OpenFaaS in a non-Swarm Docker Compose setup.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [√ ] Yes
- [ ] No

## List All Possible Solutions and Workarounds

Utilizing faasd as a potential solution for deploying OpenFaaS functions via Docker Compose.
Seeking alternative methods or configurations that are not explicitly documented.

## Which Solution Do You Recommend?

We are open to suggestions from the community and maintainers. If faasd is a viable option, we are willing to consider it.

## Context
We are a company that has successfully integrated OpenFaaS into our SaaS project and are now looking to extend this to smaller, custom projects. We believe that using Docker Compose in Standalone Mode will help us conserve resources while still providing a robust solution for our clients.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
   26.1.1
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
   no
* Operating System and version (e.g. Linux, Windows, MacOS):
   Linux 5.14.0-362.8.1.el9_3.x86_64

**Comment by alexellis** [comment]
Since we haven't heard back from you, I'll get this issue completed.

You can always contact us via the [links on the pricing page](https://openfaas.com/pricing)
