### ISSUE TITLE
Proposal: Add Kubernetes YAML Cheat Sheet to OpenFaaS Documentation

### ISSUE THREAD

**Issue by Sammieblz** [openfaas/faas#1845]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
The Kubernetes YAML Cheat Sheet aims to simplify the onboarding process for developers who want to deploy OpenFaaS on Kubernetes. Many developers, especially beginners, struggle to create or customize YAML files for their Kubernetes deployments. Having ready-made templates and examples for deploying OpenFaaS components such as the gateway, functions, networking, and autoscaling configurations will accelerate the setup process and ensure best practices are followed.

## Who is this for?
This is for developers and DevOps engineers who are deploying OpenFaaS on Kubernetes clusters, especially beginners or anyone unfamiliar with Kubernetes YAML configurations.

### What company is this for?
This contribution is on an individual basis and not tied to any company.

## Expected Behaviour

The Kubernetes YAML Cheat Sheet should provide:
1. Examples of common OpenFaaS deployments, including:
   - Gateway deployment.
   - Configuring secrets.
   - Setting up ingress and networking.
   - Horizontal pod autoscaling.

2. Well-commented YAML examples that:
   - Explain each section for clarity.
   - Follow best practices for configuring Kubernetes resources.

## Current Behaviour

Currently, OpenFaaS documentation covers some details about deploying on Kubernetes but lacks a consolidated section with easily accessible YAML templates. This makes it harder for newcomers to quickly understand and deploy OpenFaaS components in Kubernetes clusters.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

- The solution involves adding a new page in the documentation specifically titled "Kubernetes YAML Cheat Sheet." 
- Add the following types of configurations:
  - Gateway deployment.
  - Ingress for exposing OpenFaaS.
  - Horizontal pod autoscaling examples.
  - Networking configurations.

## Which Solution Do You Recommend?

I recommend creating a new Markdown page within the `/docs/` folder to contain all Kubernetes YAML configurations, each with a detailed explanation for every field. This would provide a one-stop guide for anyone looking to deploy OpenFaaS in Kubernetes.

## Steps to Reproduce (for bugs)

N/A (This is a new addition request.)

## Context

The Kubernetes YAML Cheat Sheet will:
- Improve onboarding for new users.
- Reduce time spent on setting up and troubleshooting Kubernetes configurations.
- Act as a ready reference for configuring OpenFaaS on Kubernetes, especially useful for beginners.

## Your Environment

FaaS-CLI version:
Full output from: ```faas-cli version```

Docker version:
Example: ```Docker 20.10.7```

OpenFaaS Deployment:
Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

Operating System and Version:
Example: ```Ubuntu 20.04 LTS```, ```Windows 11```, ```macOS Big Sur```

Code Example or Link to Reproduce Problem:
``N/A (new feature request)``

Other Diagnostic Information / Logs:
``N/A``

**Comment by alexellis** [comment]
Hi,

Thanks for the suggestion.

We have a guide for troubleshooting which may be what you're looking for: https://docs.openfaas.com/deployment/troubleshooting/

And for ingress, there is detailed documentation: https://docs.openfaas.com/reference/tls-openfaas/

If there are any topics missing in the documentation, feel free to propose them and we can take a look in our next weekly community call on [Wednesday](https://docs.openfaas.com/community/).

Of course, you don't need our permission to create a cheat sheet if that would help you with your usage of OpenFaaS. Host it on your blog, or GitHub account and we'd be happy to link back to it from the community resources file.

I'll close this issue, but send us a message when you've got something ready in your repo or in a Gist for us to check out.

Alex
