### ISSUE TITLE
faasd not starting in fresh install

### ISSUE THREAD

**Issue by RafaelPasCz** [openfaas/faas#1846]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
I am currently doing IoT research for the university I study at (Universidade Estadual do Oeste do Paraná) and one of the topics of this research is function as a service, I have been using faasd for that
## Who is this for?
This is for educational and research purposes only

I have been using faasd in a raspberry pi 3 B for a while, however I had to reinstall the raspberry pi OS due to unrelated issues and, consequently had to reinstall faasd, I used the guide in this link: https://blog.alexellis.io/faasd-for-lightweight-serverless/, that has previously worked fine for me. however, after this fresh install, faasd refuses to start

## Current Behaviour
Faasd installs normally, with no problems in the installation script logs, however when i check journalctl using the "sudo journalctl -u faasd -f --lines 100" command, this appears:

Nov 21 10:57:15 raspberrypi faasd[2469]: faasd Community Edition (CE) version: 0.19.2        commit: 2adc1350d4af241166dcc2d86c137fd2e4764921
Nov 21 10:57:15 raspberrypi faasd[2469]: 2024/11/21 10:57:15 File exists: "/var/lib/faasd/secrets/basic-auth-password"
Nov 21 10:57:15 raspberrypi faasd[2469]: 2024/11/21 10:57:15 File exists: "/var/lib/faasd/secrets/basic-auth-user"
Nov 21 10:57:15 raspberrypi faasd[2469]: 2024/11/21 10:57:15 Writing network config...
Nov 21 10:57:15 raspberrypi faasd[2469]: 2024/11/21 10:57:15 Supervisor created in: Less than a second
Nov 21 10:57:15 raspberrypi faasd[2469]: Preparing prometheus with image: docker.io/prom/prometheus:v2.49.1
Nov 21 10:57:15 raspberrypi faasd[2469]: Prepare done for: docker.io/prom/prometheus:v2.49.1, 93.97MB
Nov 21 10:57:15 raspberrypi faasd[2469]: Preparing gateway with image: ghcr.io/openfaas/gateway:0.27.9
Nov 21 10:57:16 raspberrypi faasd[2469]: time="2024-11-21T10:57:16-03:00" level=info msg="trying next host - response was http.StatusNotFound" host=ghcr.io
Nov 21 10:57:16 raspberrypi faasd[2469]: Error: cannot pull: failed to resolve reference "ghcr.io/openfaas/gateway:0.27.9": ghcr.io/openfaas/gateway:0.27.9: not found
Nov 21 10:57:16 raspberrypi systemd[1]: faasd.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 10:57:16 raspberrypi systemd[1]: faasd.service: Failed with result 'exit-code'.
Nov 21 10:57:26 raspberrypi systemd[1]: faasd.service: Scheduled restart job, restart counter is at 77.
Nov 21 10:57:26 raspberrypi systemd[1]: Stopped faasd.service - faasd.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
apparently it is trying to pull a container from the github registry, but it is not finding it, maybe double checking if the container is still up would shed some light

## Which Solution Do You Recommend?
checking if the container registry link is still functional

## Steps to Reproduce (for bugs)
1. clone the faasd repository with: git clone https://github.com/openfaas/faasd
2. access the faasd folder with: cd faasd
3. execute the installation script with: ./hack/install.sh
4. after the installation is done, check logs with: sudo journalctl -u faasd -f --lines 100

## Context
I have tried this on two different networks, so I don't think it's a networking issue on my end, the raspeberry pi is a fresh OS install, using the standard 64 bit installation with desktop enviroment. I have also tried on several fresh installs of the raspberry pi OS and fresh installs of  faasd

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  41605396955e6b13488755852106bd9bf315219a
 version: 0.16.37

* Docker version `docker version` (e.g. Docker 17.0.05 ):
I am using faasd, so docker is not installed in the raspberry pi
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
I am using faasd
* Operating System and version (e.g. Linux, Windows, MacOS):
    Operating System: Debian GNU/Linux 12 (bookworm)  
         Kernel: Linux 6.6.51+rpt-rpi-v8
         Architecture: arm64

* Code example or link to GitHub repo or gist to reproduce problem:
I have not had the opportunity to write any code in this install yet
* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
Output from "sudo systemctl status faasd":
● faasd.service - faasd
     Loaded: loaded (/lib/systemd/system/faasd.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2024-11-21 12:14:42 -03; 6s ago
    Process: 2768 ExecStart=/usr/local/bin/faasd up (code=exited, status=1/FAILURE)
   Main PID: 2768 (code=exited, status=1/FAILURE)
        CPU: 554ms

Output from "sudo systemctl status faasd-provider":
● faasd-provider.service - faasd-provider
     Loaded: loaded (/lib/systemd/system/faasd-provider.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-11-21 11:49:55 -03; 25min ago
   Main PID: 970 (faasd)
      Tasks: 7 (limit: 755)
        CPU: 828ms
     CGroup: /system.slice/faasd-provider.service
             └─970 /usr/local/bin/faasd provider

Nov 21 11:49:55 raspberrypi systemd[1]: Started faasd-provider.service - faasd-provider.
Nov 21 11:49:57 raspberrypi faasd[970]: 2024/11/21 11:49:57 faasd-provider starting..        Service Timeout: 1m0s
Nov 21 11:49:57 raspberrypi faasd[970]: faasd Community Edition (CE) version: 0.19.2        commit: 2adc1350d4af241166dcc2d86c137fd2e4764921
Nov 21 11:49:57 raspberrypi faasd[970]: 2024/11/21 11:49:57 Writing network config...
Nov 21 11:49:57 raspberrypi faasd[970]: 2024/11/21 11:49:57 Listening on: 0.0.0.0:8081

**Comment by alexellis** [comment]
Hi sorry about this, we purge some of the older openfaas-ce images over time, and we didn't update the docker-compose.yaml file.

I'll get that done now, or as Richard says, update your gateway to the latest image.

https://github.com/openfaas/faas/pkgs/container/gateway

Alex
