### ISSUE TITLE
Backlog: rolling updates

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#185]
We should be able to provide a seamless rolling update.

## Expected Behaviour

We have i.e. Derek version 0.2 in "production" and want to transition to version 0.3.

## Current Behaviour

Right now we can use the Swarm or Kubernetes CLI to do this.

## Possible Solution

* Enable the deployment endpoint to take an update flag

Suggestion via @gabrtv

A longer version of this story includes:

* canary deployments
* versioning (currently possible via Docker image tags)

**Comment by alexellis** [comment]
Derek add label: priority/high

**Comment by alexellis** [comment]
This needs additional testing on K8s/Swarm then we can close out the issue. @johnmccabe @ericstoekl @rgee0

**Comment by BurtonR** [comment]
@alexellis, @johnmccabe, @rgee0, and @ericstoekl The update feature has been in the wild for a couple of months now. Do you think this still needs "testing"? 

If so, what sorts of additional testing needs done?

**Comment by alexellis** [comment]
Can be closed now. This is live.
