### ISSUE TITLE
Return a HTTP error response when 'MakeNewFunctionHandler' logs an error

### ISSUE THREAD

**Issue by alias1** [openfaas/faas#195]
## Expected Behaviour

When an error is encountered while deploying a function to a non-existent network, the gateway should return a corresponding error response so that `faas-cli` can properly pick it up.

## Current Behaviour

An error is logged in the gateway logs, but `faas-cli` receives a `200` response, indicating success. Not sure if this happens in other places. May be worth a quick check through all relevant code to ensure it returns proper 'error' codes.

## Steps to Reproduce (for bugs)
1. `faas-cli deploy --network foo_nonexistent -f someFuncs.yml`
2. Receive a `200` successfully deployed
3. Check the logs for the gateway
4. There should be an error line similar to `openfaas_gateway.1.1w7br0vud8mj@moby    | 2017/09/18 21:44:16 Error response from daemon: network func_functions not found`

## Context

See https://github.com/alexellis/faas-cli/issues/96#issuecomment-330367366

@alexellis linked to https://github.com/alexellis/faas/blob/master/gateway/handlers/createhandler.go#L57

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): `17.06.2-ce`

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? `Swarm`

* Operating System and version (e.g. Linux, Windows, MacOS): `macOS 10.12.6`

**Comment by alias1** [comment]
ping @ems5311 RE: https://github.com/ems5311/faas/blob/fbe19240a67f7b24c2862f1e1ad6a024d9455125/gateway/handlers/createhandler.go#L57

**Comment by alexellis** [comment]
The code is fixed in the server, but I think we're working on UI enhancements too. @ericstoekl @nullseed ?

**Comment by nullseed** [comment]
@alexellis Yep, i'll be commiting the UI enhancements tonight

**Comment by johnmccabe** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
@alias1 - fixed in #195. Can you test?

**Comment by nullseed** [comment]
@alexellis - I think think you mean fixed in #199 rather than #195

**Comment by alias1** [comment]
Looks good to me!

```
services:
    gateway:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - 8080:8080
        image: functions/gateway:0.6.6-beta2
```
```
⇒  brew info faas-cli
faas-cli: stable 0.4.17 (bottled)

⇒  faas-cli deploy --network foo_nonexistent -f functions.yml
Deploying: gobuster.
No existing service to remove
Unexpected status: 400, message: Deployment error: Error response from daemon: network foo_nonexistent not found
400 Bad Request
```

**Comment by alexellis** [comment]
Good news! How about testing via the UI now with the updated Docker image?

**Comment by alias1** [comment]
UI seems to work as well.

![image](https://user-images.githubusercontent.com/753891/31208630-0de42754-a9d2-11e7-83f1-62e0cbaf4af3.png)

**Comment by alexellis** [comment]
Brilliant - thank you for testing.
