### ISSUE TITLE
Add favicon to UI

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas#221]
## Expected Behaviour

The UI currently doesn't include an OpenFaaS favicon, it should have a favicon.

## Current Behaviour

Accessing the UI from a browser/phone/tablet should result in a platform appropriate favicon being presented to the user.

## Possible Solution

Generate a favicon with https://realfavicongenerator.net/ and add to index.html.

## Steps to Reproduce (for bugs)

n/a

## Context

We have a lovely logo, it deserves to be an icon.

## Your Environment

n/s

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Merged. Looking forwarding to seeing it in the next release.
