### ISSUE TITLE
Document: Traefik integration for Docker Swarm

### ISSUE THREAD

**Issue by austinfrey** [openfaas/faas#229]
## Expected Behaviour

Add documentation to add Traefik as an API gateway providing Basic Authentication to the Gateway and SSL

## Current Behaviour
Without and Basic Authentication, OpenFaaS is open the the public internet

## Possible Solution
Provide documentation similar to Kong to add another option for Basic Auth and SSL

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

Pros:
* All setup is done via docker-compose.yml file, no additional services are needed other than Traefik
* Adds flexibility, another option

Cons:
Might not be as configurable as Kong

**Comment by alexellis** [comment]
How would this differ to the Kong guide?

Do you have pros/cons of using either?

**Comment by austinfrey** [comment]
I updated with Pros and Cons

**Comment by austinfrey** [comment]
i have a write up for the Basic Auth piece here: [traefik integration](https://github.com/austinfrey/faas/blob/traefik_integration/guide/traefik_integration.md)

Tried to follow the same style as other guides. I'll write up the SSL piece later today.

**Comment by austinfrey** [comment]
closing since this was merged in #231
