### ISSUE TITLE
Proposal: Standardized OpenFaaS Github Badges for related repositories

### ISSUE THREAD

**Issue by austinfrey** [openfaas/faas#232]
The idea would be to create standardized GitHub badges for related projects on GitHub. Something like this:
![OpenFaaS](https://img.shields.io/badge/openfaas-v0.6.5-blue.svg)

We could have different ones to label projects as OpenFaaS compatible `functions` or a project that's in an `incubator` phase of development, or even certified `provider` badges. I wanted to open up the discussion for additional ideas and determine what badges would be useful/needed.

**Comment by alexellis** [comment]
Let's do it. The version number would be hard to maintain/keep up. What other text could we use?

[ openfaas | node/Docker/mixed ] ?

**Comment by austinfrey** [comment]
Just to get a list going and see what sticks

`openfaas | <runtime> ` for functions like you mentioned
`openfaas | provider` for things like swarm, k8's, cattle, hyper.sh etc
`openfaas | <certification level>` - meet certain testing criteria

definitely open to suggestions

**Comment by kenneyhe** [comment]
Since we are talking about badges, is there a code coverage badge for the python component? unittest coverage will be great.  I am using coverall.io my other projects.. nosetests/pytest with circleci /codeship might be nice..

**Comment by austinfrey** [comment]
@kenneyhe are you asking if there is code coverage for python functions generated using the OpenFaaS templates? some more clarity there might be helpful?

also, if no one else has suggestions, I think moving forward with some preliminary badges for OpenFaaS functions and OpenFaaS providers would be a good start. That way on landing on a repo page, users can immediately identify if it's a function that can be run on OpenFaaS or if it's a Provider/Backend for OpenFaaS. 

@alexellis if that sounds good to you, where would the best place be to include instructions for badging projects?

**Comment by alexellis** [comment]
How about::

![OpenFaaS](https://img.shields.io/badge/openfaas-<3-blue.svg)

![OpenFaaS](https://img.shields.io/badge/openfaas-serverless-blue.svg)

**Comment by austinfrey** [comment]
Which badge would go with what?
<3 = affiliated project?
serverless = provider?

**Comment by alexellis** [comment]
People could put either on their repos which contain OpenFaaS functions

**Comment by kenneyhe** [comment]
@austinfrey any code coverage badge (I am code agnostic) to show coverage % for the template code will be appreciated.   I usually have a tests directory for unittests with python coverage tool to show current code quality.  Since it is a rest-api, all we need is curl commands to make sure template is sound..  here is one example.. 

[![Coverage Status](https://coveralls.io/repos/github/kenneyhe/BingRewards/badge.svg?branch=master)](https://coveralls.io/github/kenneyhe/BingRewards?branch=master)

**Comment by alexellis** [comment]
I think we have a badge now like in the faas-cli repo .. @austinfrey would you like to add a brief sentence to the community.md file about using it?

**Comment by alexellis** [comment]
Closing as resolved.

**Comment by austinfrey** [comment]
sure thing!
