### ISSUE TITLE
Proposal: ECS OpenFaaS provider

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#233]
In the same vein as a Kubernetes, Nomad and Docker Swarm integration I'm hearing from folks at JeffConf that an ECS provider would be useful for them to bypass some of the Lambda limitations without having to learn K8s or Swarm. @stack360 has started some initial work as his 20% project at Huawei.

https://github.com/stack360/faas-ecs

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by alias1** [comment]
Funny how my research leads me in circles to things that are already half started. In a similar vein (lambda restrictions), OpenFaaS support for ECS would be extremely beneficial. I'm not sure if it will directly map for me though, as i'm interested in scaling out a function invocation to X instances, with varied params. (eg. function based 'threading as a service')

**Comment by alexellis** [comment]
What is the use-case? Maybe it will work?

**Comment by alias1** [comment]
The basic thing i'm currently working on is a static compiled go binary that will process through a large wordlist (could be 20k lines or more) and check if files exist on a website (dirbusting).

So I will probably include the wordlist in the docker image (or have the image know how to pull it down), then provide the domain and 'slice' (start/end line) of the wordlist to use. Ideally I would then want each 'function invocation' to run on a separate EC2 micro instance or similar.

Ultimate goal is to scale the workload out beyond what a single machine would be capable of.

**Comment by alexellis** [comment]
Derek close: Implemented by @ewilde - https://github.com/ewilde/faas-fargate
