### ISSUE TITLE
Hacktoberfast - provide guide for self-hosted registry

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#242]
For Hacktoberfast

We could do with a guide for running the open-source self-hosted registry with OpenFaaS and Docker Swarm. Also Kubernetes via https://github.com/openfaas/faas-netes/issues/32

**Comment by alexellis** [comment]
Related via @johnmccabe  - https://gist.github.com/johnmccabe/55baab605c0fb82df9c1cbf8c3dde407

**Comment by johnmccabe** [comment]
Note there are is also some existing material here - https://github.com/openfaas/faas/blob/master/docs/managing-images.md#deploy-your-own-private-docker-registry

**Comment by jonocodes** [comment]
I have started working on this.

**Comment by BurtonR** [comment]
Derek close
