### ISSUE TITLE
functions/gateway:armhf-0.6.5 exits/fails on PiZero

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#247]
## Expected Behaviour
Gateway UI on ARM should be consistent with that of X86-64.

## Current Behaviour
The UI is dated on ARM such that the OpenFaaS branding is not yet reflected.
`docker-compose.armhf.yml` needs amending to pull in a later gateway image.  However, upon trying this `functions/gateway:armhf-0.6.5` was found to be failing on ARMv6 with the following error:
```
standard_init_linux.go:178: exec user process caused "exec format error"
```
Further investigations - with attempts to build the gateway locally - found that `Dockerfile.armhf` is also missing the queue components which conflicts with the `vendor` info and causes the build to fail.

## Possible Solution
Change gateway/Dockerfile.armhf
Change gateway/build.armhf.sh
Build new gateway image and push to `functions/gateway:armhf-n.n.n`
Amend `docker-compose.armhf.yml` to reflect new gateway image

## Steps to Reproduce (for bugs)
1. Run ./deploy_stack.armhf.sh
2. Check the interface to find older look and feel
3. Tear the stack down
4. Change the gateway image in `docker-compose.armhf.yml` to `functions/gateway:armhf-0.6.5`
5. Run ./deploy_stack.armhf.sh
6. Try to access the gateway, check `docker service ls` for replica count, check `docker ps -a` to see exiting/failing gateway containers

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux (Raspbian Jessie)

**Comment by rgee0** [comment]
Derek add label: bug

**Comment by alexellis** [comment]
I think this still works on RPi2/3 but is only built on manual best-effort basis. We may have to deprecate Pi Zero to enable CI to keep in sync with main releases. 

Were you able to rebuild from scratch? Did it all work as expected?

**Comment by rgee0** [comment]
Yes, I got it going, seems OK - certainly looks nicer.
