### ISSUE TITLE
Consolidate arm build/deploy scripts

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#249]
## Expected Behaviour

`./build.sh` should work for ARM/x86_64 etc
`./deploy.sh` should work for ARM/x86_64 etc

## Current Behaviour

`./build.armhf.sh` is needed along with `./build.sh` for x86_64.

A separate deployment script is also needed - this should be consolidated. See #248 for an example of a technique for this work.

**Comment by alexellis** [comment]
Assigned to Richard.

**Comment by rgee0** [comment]
Should we adopt the arm32v7 notation to replace armhf as part of this?

**Comment by alexellis** [comment]
My feeling is maybe but not yet. Armhf arm64

**Comment by alexellis** [comment]
Derek close
