### ISSUE TITLE
Hacktoberfast: Make read_/write_debug false in watchdog 

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#251]
## Expected Behaviour

Functions should not write their input/output (request/response values) to the console by default.

If this change is put in place, then we should at least print something to show a request was handled, but on a single line and not N lines. Imagine if your function returned 5k lines of text.

## Current Behaviour

The watchdog has `read_` and `write_debug` on by default and this means output is printed to the console - for some functions that causes a small latency penalty. With a larger response body that will incur a larger penalty - i.e. returning 10k lines of JSON would return 10k lines of text in the logs.

## Possible Solution

See also: [Golang basics - writing unit tests](https://blog.alexellis.io/golang-writing-unit-tests/)

The changes will concentrate around the read_config tests:

* Update watchdog Golang unit tests to generate failing tests
* Add breaking tests if necessary
* Change underlying behaviour in Golang code and see tests pass

## Steps to Reproduce (for bugs)

Deploy the sample stack.

```
echo 'each
> line
> is
> another
> line
> in
> the
> logs' | faas-cli invoke --name func_markdown
```

Here is an example:

```
$ docker service logs func_markdown
func_markdown.1.k7mhyqfykgpu@moby    | <p>test</p>
func_markdown.1.k7mhyqfykgpu@moby    | 
func_markdown.1.k7mhyqfykgpu@moby    | <p>each
func_markdown.1.k7mhyqfykgpu@moby    | line
func_markdown.1.k7mhyqfykgpu@moby    | is
func_markdown.1.k7mhyqfykgpu@moby    | another
func_markdown.1.k7mhyqfykgpu@moby    | line
func_markdown.1.k7mhyqfykgpu@moby    | in
func_markdown.1.k7mhyqfykgpu@moby    | the
func_markdown.1.k7mhyqfykgpu@moby    | logs</p>
func_markdown.1.k7mhyqfykgpu@moby    | 
```

Feel free to ask questions in the thread.

**Comment by BurtonR** [comment]
I'd like to try my hand at this one. Sounds easy enough to reproduce and just enough to get my feet wet in the code base to get me up to speed for future contributions.

To be clear, the default behavior will be changed from printing all lines, to a single line in the log. The `read_` and `write_debug` will retain the option to be turned on.

**Comment by alexellis** [comment]
Yes that's right. The single line would maybe say how many bytes were read or written if that's easy to do.
