### ISSUE TITLE
Client-side validation for "New Function"

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#252]
## Expected Behaviour

On the API gateway, you should not be able to click "Create/New" if the image field is invalid (red). There is some work to do server validation underway in #199 - but the UI should also stop this.

I think the button / click needs to look at the "state" of the model to see if it's valid before allowing the click. The red colouring in the UI indicates the validation is working.

Notes: UI uses angular 1.x + material

**Comment by rozuur** [comment]
Can I work on this?

**Comment by alexellis** [comment]
Please do 👍

**Comment by alexellis** [comment]
@rozuur this is still outstanding if you'd like to work on it.

Referenced PR only covers part of the work, but not the required field validation on the client-side.
