### ISSUE TITLE
Hacktoberfest: generated documentation site

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#253]
We need a separate documentation site to be generated by

* or Jekyll Github pages
* Hugo in CI
* Something else

This is an example from NATS.io: https://github.com/nats-io/nats-site

This should have the OpenFaaS branding and colour-scheme similar to www.openfaas.com

We have content building up on blog posts and in the ./guide folder.

**Comment by johnmccabe** [comment]
I'd started looking into this last week going the Jekyll/Github route that K8s followed (avoids having to deal with the site building in a pipeline)

**Comment by alexellis** [comment]
Updated title/body to match up with this.

**Comment by genexp** [comment]
Humble suggestion: Gitbook is open source and very easy to use.  We moved a bunch of our documentation to it over the last six months and we've been really happy with the ease of updates.   

A nice example:
https://frontendmasters.com/books/front-end-handbook/2017/

(It's all just markdown with optional theming)

**Comment by johnmccabe** [comment]
assign to: johnmccabe

**Comment by johnmccabe** [comment]
Derek assign: johnmccabe

**Comment by alexellis** [comment]
See updated comment: https://github.com/openfaas/faas/pull/464#issuecomment-371971680

**Comment by alexellis** [comment]
Cheers @genexp

**Comment by alexellis** [comment]
Derek close: thanks @johnmccabe
