### ISSUE TITLE
Security - External Function Delegation

### ISSUE THREAD

**Issue by nicholasjackson** [openfaas/faas#262]
## Expected Behaviour
The watchdog should be able to delegate responsibility to external functions for various security related features such as:
1. Obtaining TLS certificates
2. Obtaining Secrets
3. Checking Authorisation

## Current Behaviour
This is currently not implemented behaviour

## Possible Solution
Defining an interface for the three external functions would allow the watchdog to delegate security related functionality to a downstream function.  This would allow various backends to be implemented without the need for detailed knowledge of the backend such as Vault or AWS Cognito, AWS KMS, etc.

Startup configuration would be provided to a function which lets its watchdog know which function call it would need to execute in order to perform the action.  The security functions themselves would be grouped into two different kinds:
1. Startup functions (called once)
2. Per request (called with every request)

![extensions](https://user-images.githubusercontent.com/773533/31306540-35e55eca-ab4a-11e7-98aa-a884c37486a0.png)

### 1. Startup Flow

When the watchdog starts if there is a TLS and / or Secrets function registered it would call that function to request and configure a TLS certificate or to request secrets.  The implementation of the backend function would only need to satisfy a standard interface allowing extensibility for a wide range of platforms.

![1_startup_flow](https://user-images.githubusercontent.com/773533/31306542-43d96134-ab4a-11e7-9bdf-c8487c32df7f.png)

### 2. Per Request Authz
If Authz is configured then the payload passed to the watchdog would be handed of to a Authz function for validation.  The Author function would return a list of claims which could be then passed to the handler.  Delegating only Authz to the function would allow the Authorization part to be handled external to the request.  The Authorization flow would authenticate against the chosen backend and create a secure validatable token (something like JWT) which could then be passed with each request to a function.

The externally registered function would be responsible for validating the token, in the instance of a JWT this would be checking the signature is valid by using the public key.  It would return a list of claims which corresponded to a OpenFaaS interface which could then be passed to the function call.  If the token is not valid the watchdog would return a NOT AUTHORIZED message and would not call the handler.

It would still be up to the individual function to check the passed claims have the correct entries to perform the requested action however it can trust the claims it has been passed as they would have been validated by the Watchdog.

![2_request_flow](https://user-images.githubusercontent.com/773533/31306573-e47a07e2-ab4a-11e7-9682-836c2899e0e5.png)

## Context
External security is an important part of a system however security beyond the firewall is equally important.  If an attacker breaches the firewall they could call functions with any permissions.  In addition to this network traffic beyond the firewall should be secured with TLS (preferably MTLS) to reduce the attack vector.  The concepts of Zero Trust are fast becoming a standard with modern systems and OpenFaaS should attempt to follow this.

## Your Environment
The above proposal would work in any environment as it is an extension of the watchdog not the provider.  It also allows users to leverage existing security processes and infrastructure.

**Comment by alexellis** [comment]
Hi Nick, thanks for your proposal. This looks like a significant change that touches every service. We'll look into this in detail and get some feedback.

**Comment by nicholasjackson** [comment]
Yes it is significant, however the external functions could be disabled by default giving backwards compatibility.  Before even thinking about this there would probably pre work needed such as the ability to pass parameters to functions for startup such as those outlined in the Paramus to specify memory and cpu allocation.

**Comment by nicholasjackson** [comment]
This is the issue I was relating to in the previous comment. https://github.com/openfaas/faas/issues/239

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Update - we have secure secret support in place/under-way through Swarm and Kubernetes secrets. Nic also wants to revisit his proposal.

**Comment by ivanayov** [comment]
@nicholasjackson there is now support for signing functions with HMAC (for reference: [docs](https://docs.openfaas.com/reference/authentication/#for-functions) / [workshop](https://github.com/openfaas/workshop/blob/master/lab11.md)).
We also have sealed secrets.

Do you have any input on your proposal? Is it now outdated or may be we should revisit it?

**Comment by alexellis** [comment]
Derek close: inactivity
