### ISSUE TITLE
Rename sample function names to lowercase

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#265]
The current set of function names in the samples.yml file are invalid, so need to be lowercase to be deployable on Swarm/K8s. Also replace `_` for `-` for DNS validation.

Testing:

This should yield no errors:

```
faas-cli build -f samples.yml
faas-cli deploy -f samples.yml
```

https://github.com/openfaas/faas/blob/master/sample-functions/samples.yml

**Comment by alexellis** [comment]
Derek add label: helpwanted

**Comment by riktimmondal** [comment]
i am taking it

**Comment by VijayGomathi** [comment]
don't know how to run these commands

faas-cli build -f samples.yml
faas-cli deploy -f samples.yml

**Comment by rgee0** [comment]
@VijayGomathi Can you give us a bit more info?  How have you tried so far? What message do you get when trying to run them?

**Comment by VijayGomathi** [comment]
@rgee0 I tried installing faas-cli via npm. but i could not run the command. I am getting the following error message.
"'faas-cli' is not recognized as an internal or external command,
operable program or batch file."

I also tried installing faas-cli package globally in npm. Still getting the same error

**Comment by rgee0** [comment]
@VijayGomathi please try `$ curl -sSL https://cli.openfaas.com | sudo sh`

**Comment by VijayGomathi** [comment]
@rgee0 I am using windows operating system

**Comment by VijayGomathi** [comment]
@rgee0 now I'm getting this error. Please help.
![faas-cli](https://user-images.githubusercontent.com/31568585/31316053-e60c882a-ac42-11e7-8c2a-d00987609f80.PNG)

**Comment by alexellis** [comment]
You can't use Windows containers for this script.. switch to Linux containers.

**Comment by GrantSheehan** [comment]
I'm not sure what was meant by `Also replace _ for - for DNS validation.`, maybe those replacements were made in an earlier merged PR?

**Comment by alexellis** [comment]
Fixed by @GrantSheehan - thank you. @VijayGomathi thank you for taking a shot at this.
