### ISSUE TITLE
testing for demo

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#267]

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
Derek assign issue to: johnmccabe

**Comment by alexellis** [comment]
Derek assign to: johnmccabe

**Comment by alexellis** [comment]
Derek assign: johnmccabe

**Comment by alexellis** [comment]
Derek add label: demo

**Comment by alexellis** [comment]
Derek add label: demo

**Comment by rgee0** [comment]
Derek add label: conor

**Comment by rgee0** [comment]
Derek remove label: conor

**Comment by alexellis** [comment]
Derek set title: testing for demo

**Comment by alexellis** [comment]
Derek reopen

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
@rgee0 looks good.
