### ISSUE TITLE
PUT /system/functions endpoint returns 404

### ISSUE THREAD

**Issue by schickling** [openfaas/faas#268]
When trying to re-deploy a function using the `HTTP PUT` method the server returns a 404 like here: 

![image](https://user-images.githubusercontent.com/1567498/31321145-62c3aaea-ac81-11e7-9b45-12502a1841c7.png)

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

![image](https://user-images.githubusercontent.com/1567498/31321149-74f606ae-ac81-11e7-9510-203ed5b4f8a6.png)

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS

**Comment by johnmccabe** [comment]
@schickling can you retry your curls adding the scheme to the urls:
```
curl -X http://localhost:8080/system/functions ...
```

**Comment by johnmccabe** [comment]
Derek add label: question

**Comment by johnmccabe** [comment]
Is it just the update that fails, can you hit any other endpoint successfully?

And does it also fail with the `faas-cli`

**Comment by alexellis** [comment]
Our recommended approach for interacting with OpenFaaS is via the `faas-cli`.

https://blog.alexellis.io/quickstart-openfaas-cli/

`PUT` for updates is available in the latest release and Docker image (functions/gateway:0.6.6-beta2)

**Comment by schickling** [comment]
`faas-cli` works, `HTTP POST` and `HTTP GET` works.

**Comment by alexellis** [comment]
Just gave the latest release a test on my "lab" - appears to take the update as expected. Can you move to a newer gateway image please @schickling ? Also getting Chromeless working on OpenFaaS is very interesting if you have any ideas about that.

If you'd like to join our community on Slack just email alex@openfaas.com for an invite.

**Comment by schickling** [comment]
I've installed the CLI via `brew install faas-cli` - any instructions how to upgrade the versions?

Re Chromeless: Yes, that would definitely be interesting, however, I won't be able to look into that before November. Maybe someone can [open an issue](https://github.com/graphcool/chromeless/issues/new)?

**Comment by alexellis** [comment]
For the gateway edit your docker-compose.yml file and change image: functions/gateway:... to the above then run `./deploy_stack.sh` again. It's late in the UK so will catch up with you in the morning. Unless you want to join Slack where we may have folks in your timezone.

**Comment by schickling** [comment]
Thanks @alexellis - this works with the `functions/gateway:0.6.6-beta2` image. 

Is there a way to make the `PUT`/`POST` call blocking until the function has been deployed and is ready to be used without running into `Can't reach service:` errors?

**Comment by austinfrey** [comment]
@schickling not currently. is there a particular situation where you would not want that feedback?

**Comment by austinfrey** [comment]
@schickling closing for now, but if you have further input or want to re-open, please feel free!

**Comment by austinfrey** [comment]
Derek close

**Comment by alexellis** [comment]
@schickling Austin is correct - but @ericstoekl is doing some work which will help your scenario by giving data over the RESTful endpoints and CLI as to when a function has a replica ready. Are you on our Slack channel? Maybe we could chat more there.
