### ISSUE TITLE
Question on watchdog and environmental variables (Kubernetes)

### ISSUE THREAD

**Issue by psyhomb** [openfaas/faas#270]
It looks like function watchdog environment variables are not exported, not available to the forked process (function).

## Expected Behaviour

According to this [doc](https://github.com/openfaas/faas/tree/master/watchdog) if I execute function via API with `fprocess=env` I should see `Http_Query="reverse=true"` as well as other environment variables exported from request headers
```
# curl -sSL -X POST 'http://localhost:8080/function/test?reverse=true' | egrep 'fprocess|Http_'
fprocess=env
Http_User_Agent=curl/7.54.0
Http_Accept=*/*
Http_Method=POST
Http_Query=reverse=true
```

## Current Behaviour

Instead none of the `Http_` environment vars are available
```
# curl -sSL -X POST 'http://localhost:8080/function/test?reverse=true' | egrep 'fprocess|Http_'
fprocess=env
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I'm trying to change function behavior by using `querystring` boolean parameter

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
```
Kubernetes v1.6
```
* Operating System and version (e.g. Linux, Windows, MacOS):
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
You need to enable cgi_headers as per Readme for the watchdog.

**Comment by psyhomb** [comment]
Ok but according to [README.md](https://github.com/openfaas/faas/tree/master/watchdog) `cgi_headers` option should be enabled by default?

Option | Usage
-- | --
`cgi_headers` | HTTP headers from request are made available through environmental variables - Http_X_Served_By etc. See section: Handling headers for more detail. Enabled by default.

and that reflect what I see in the source code IINW
https://github.com/openfaas/faas/blob/master/watchdog/readconfig.go#L45-L48

Nevertheless after explicitly enabling it all env vars seems to be available except for `Http_Query=reverse=true`
```
# curl -sSL -X POST 'http://localhost:8080/function/test?reverse=true' | egrep 'fprocess|Http_'
fprocess=env
Http_Accept=*/*
Http_Accept_Encoding=gzip
Http_X_Forwarded_For=10.244.7.1
Http_Connection=close
Http_User_Agent=curl/7.54.0
Http_Content_Length=0
Http_Method=POST
```

Just to mention that I'm using watchdog from release [v0.6.5](https://github.com/openfaas/faas/releases/download/0.6.5/fwatchdog)

**Comment by alexellis** [comment]
Interesting - this unit test is showing that it defaults to true:

```
func TestRead_CgiHeaders_DefaultIsTrueConfig(t *testing.T) {
	defaults := NewEnvBucket()
	readConfig := ReadConfig{}

	config := readConfig.Read(defaults)

	if config.cgiHeaders != true {
		t.Logf("cgiHeaders should have been true (unspecified)")
		t.Fail()
	}
}
```

You can prove out the default by entering the watchdog directory and doing:

```
$ go build && fprocess=env ./watchdog &
$ curl localhost:8080
...
Http_User_Agent=curl/7.43.0
Http_Accept=*/*
Http_Method=GET
Http_Query=/
```

If you still have issues we'll publish a new release of the binary later today.

**Comment by psyhomb** [comment]
Ok I just made some tests with proposed version (0.6.6b) and `Http_Query` environment variable is available now but it's always empty (`Http_Query=/`) despite the fact that `querystring` is present in the http request
```
# curl -sSL -X POST 'http://localhost:8080/function/test?reverse=true' | egrep 'fprocess|Http_|cgi_headers'

fprocess=env
cgi_headers=true
Http_User_Agent=curl/7.54.0
Http_Content_Length=0
Http_Accept=*/*
Http_Accept_Encoding=gzip
Http_X_Forwarded_For=10.244.7.1
Http_Connection=close
Http_Method=POST
Http_Query=/
```

**Comment by psyhomb** [comment]
Strange, when I try same thing directly, not via Kubernetes, everything seems to be OK.
Any clue what this could be?

```
# fprocess=env ./fwatchdog &
# curl -s -X POST localhost:8080?reverse=true | egrep 'Http_|fprocess'
fprocess=env
Http_User_Agent=curl/7.35.0
Http_Accept=*/*
Http_Method=POST
Http_Query=/?reverse=true
```

**Comment by psyhomb** [comment]
It turns out like Kubernetes is altering or doing something with the querystring, because if I run same commend inside pod (container) querystring is available...

From inside container
```
# k exec -it test-2210613549-w90n2 -- /bin/sh
# curl -X POST localhost:8080?reverse=true
...
Http_Query=/?reverse=true
```

From outside container (service)
```
# curl -sSL -X POST 'http://k8s-node:31112/function/test?reverse=true'
...
Http_Query=/
```

**Comment by alexellis** [comment]
Hi, I have a change pending in #276 which will help with getting Query value through to the watchdog. I think you are right in identifying the gateway (proxy) as where the data is being stripped. The watchdog component is ready to work with the Query/Path already as you saw with `kubectl exec`.

**Comment by johnmccabe** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Fixed and released in latest version of watchdog. @psyhomb if you'd like to do a PR for the Dockerfiles in this repo I can merge that.

**Comment by alexellis** [comment]
@psyhomb closing as fixed, but if you want to submit PR to upgrade watchdog we can merge that.

**Comment by austinfrey** [comment]
Derek close
