### ISSUE TITLE
Research: Report function replica status by querying Docker Swarm API

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas#273]
From Alex:
> Do we have a way in the Docker Swarm API to query whether any of the 1/1 replicas are “ready” i.e. healthcheck passed? This could help us in making our error messages better.. or if there’s another state like “pending” that we can return as “node pulling image” etc

We need a way to report to the user whether their function is ready-to-go, without making them examine the output of `docker service ls` (and probably `| grep <functionname>`), which is currently what's required to find out whether your container is replicated or not.

Each of the different backends (Swarm, K8, etc) will need their own implementation of this feature, because each backend manages the health of their containers in a different way. We will first get this working with Docker Swarm.

## Expected Behaviour

When using `proxy.ListFunctions()` in the `faas-cli` code, it will return info about what functions are available, and whether or not they are ready to use.

## Current Behaviour

The CLI tool is unable to report whether or not a function is ready to use.

## Possible Solution

We will add this feature to the `gateway/handlers/` section. Need to read through the Docker Swarm API to figure out exactly how to do this.

## Steps to Reproduce (for bugs)

1. Deploy a new function with `faas-cli deploy -f <YAML>`
2. In `faas-cli list`, you will see the function name appear, even before it is active. However, there is no indication of whether the function is ready to use or not.
3. Need to query `docker service ls` to see if the function has any active replicas or not (wait until replicas status is `1/1`)
4.

## Context

This is an issue that we have been talking about for some time. The contention is that separate functionality will be needed for each backend. However, we would like to start with Docker Swarm.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Targeting all OSes

* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
Derek assign issue to: ericstoekl

**Comment by ericstoekl** [comment]
Derek assign: ericstoekl

**Comment by johnmccabe** [comment]
Docker add label: proposal

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
Update: https://asciinema.org/a/M7OS28J4tvza0oe7ZVXLusfqa

Will be making a pull request soon, if this looks good.

**Comment by ericstoekl** [comment]
`faas`: https://github.com/ericstoekl/faas/tree/replicaStatus
`faas-cli`: https://github.com/ericstoekl/faas-cli/tree/replicaStatus

```
$ faas-cli list
Function                      	Invocations    	Replicas
func_nodeinfo                 	0              	1/1
youtube-dl                    	0              	0/1
func_webhookstash             	0              	1/1
func_hubstats                 	0              	1/1
func_decodebase64             	0              	1/1
func_echoit                   	0              	1/1
ct_1                          	0              	0/1
func_wordcount                	0              	1/1
func_markdown                 	0              	1/1
func_base64                   	0              	1/1

```

Without this change, the time to run `faas-cli list` is around `real	0m0.014s`. With the update, it is about `real	0m0.026s`. @alexellis suggested having this as `--verbose` option.

**Comment by ericstoekl** [comment]
Updated with verbose as an option. Check it out:

https://asciinema.org/a/cwClkFoAWUg1VTCns8FwXrMNP

**Comment by developius** [comment]
This is great, looking forward to not have to login to my swarm master any more 😀

**Comment by ericstoekl** [comment]
@alexellis Has mentioned that we should have this functionality on K8 as well.

@developius Good call about that, I'll need to test it.

**Comment by imikushin** [comment]
Looking forward to see this resolved!

**Comment by alexellis** [comment]
Derek close: fixed
