### ISSUE TITLE
Proposal: Use Swarm Configs for Prometheus and AlertManager

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#282]
## Expected Behaviour

We should be able to use the pinned official Prometheus images with no changes - by using "Docker Swarm Configs"

https://docs.docker.com/engine/swarm/configs/

## Current Behaviour

We have to bake config into our own images and push to the Hub which is hard to maintain and confusing for newcomers. With Kubernetes we use config-maps.

## Possible Solution

The solution should use the same pinned versions we have now, but add configs to the docker-compose files - including the extended and arm stack.

Notes: please report on the minimum Docker version for Configs - we don't want to necessarily raise the bar for people like Azure Container Service etc who are on "older" versions of Docker.

**Comment by fntlnz** [comment]
This impacts also faas-netes which uses the `latest-k8s` tag, there we could use a `ConfigMap`.
The first supported version for configs is `17.06` that would pull out a large amount of users as you said though.

**Comment by weikinhuang** [comment]
I'm planning on making this change to the faas-netes yaml files, when I made the helm charts, they've already been migrated to use the library images and mount `ConfigMaps`.

**Comment by alexellis** [comment]
Derek close: fixed
