### ISSUE TITLE
Proposal: Migrate to Prometheus 2.x

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#283]
Migrate to the latest Prometheus 2.x version including latest AlertManager.

## Context

We should do this due to memory and disk usage improvements and to keep current.

I have tried this and there appears to be breaking changes in the config for AlertManager and Prometheus. The person taking this task on will need to work through any issues and ensure auto-scaling and metrics are unaffected.

I don't expect this to cover the client library used in the Gateway/faas code.

**Comment by johnmccabe** [comment]
I'll pick this up, been meaning to get hacking on the main platform again.

**Comment by austinfrey** [comment]
here's another one @viveksyngh

**Comment by alexellis** [comment]
Derek close: completed migration.
