### ISSUE TITLE
Proposal: Secure secret management

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#285]
This proposal is inspired by the Docker Swarm secret management but should be generalizable to Kubernetes Secrets and possibly other 3rd party secret management systems.

## Summary 
It is common that a function may need to connect to a database or a secure API. The username and password values used to connect to these data sources should be kept secret and secured.  Currently these values are either hardcoded into functions or provided as environment variable. This means that these values are not encrypted at rest and even more specifically it leads to the highly likely situation where these secret values are checked into git repositories. This puts these sensitive values at risk.

Both [Docker Swarm](https://docs.docker.com/engine/swarm/secrets/) and [Kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/) have built in secret management systems.  In particular, both provide an API for management of secrets and support mounting those secrets in services as files.  Kubernetes is the most flexible in allowing you to specify the exact path of where these files are mounted.  Docker Swarm on the other hand strictly mounts the secrets to `/run/secrets` inside the containers.

## Expected behavior
OpenFaaS should support defining services that access secret values from and encrypted storage. 

## Current Behavior
Secrets can be provided via the Environment variables, but these values are not encrypted at rest.

## Possible solution
The end user should be able to provide secrets to the orchestration layer (docker swarm or kubernetes) and then reference those same secrets in the function. The creator of a function would simply provide a list of secrets that are required for the function during the function creation (or in the stack yaml for the cli) and the orchestration layer would be responsible for mounting those secrets as files in a standard location.

Specifically, 

1. We should standardize functions to expect secret files mounted in `/run/secrets`.
2. Secret values will be created and managed independently from functions via the orchestration tool
3. When creating a new function service, the API accepts a list of secret names as strings. The gateway then passes this forward to the orchestration layer when defining the new function service/pod.

```go
// CreateFunctionRequest create a function in the swarm.
type CreateFunctionRequest struct {
    // Service corresponds to a Docker Service
    Service string `json:"service"`

    // Image corresponds to a Docker image
    Image string `json:"image"`

    // Network is specific to Docker Swarm - default overlay network is: func_functions
    Network string `json:"network"`

    // EnvProcess corresponds to the fprocess variable for your container watchdog.
    EnvProcess string `json:"envProcess"`

    // EnvVars provides overrides for functions.
    EnvVars map[string]string `json:"envVars"`

    // Secrets is a list of secrets required for the orchestration layer to provide
    Secrets []string `json:"secrets"`

    // RegistryAuth is the registry authentication (optional)
    // in the same encoded format as Docker native credentials
    // (see ~/.docker/config.json)
    RegistryAuth string `json:"registryAuth,omitempty"`

    // Constraints are specific to back-end orchestration platform
    Constraints []string `json:"constraints"`
}
```

## Context

I want to use this functionality specifically to securely store database and api access credentials.

**Comment by alexellis** [comment]
Which do you need first? We have a PR for Kubernetes and the faas-cli has been released with support already. https://github.com/openfaas/faas-netes/pull/54

**Comment by LucasRoesler** [comment]
I was going to submit the PR for faas gateway today (hopefully).  Almost all of my local development is in Docker Swarm, so I always start there.

**Comment by austinfrey** [comment]
Derek add label: proposal
