### ISSUE TITLE
Documentation issue on the testdrive

### ISSUE THREAD

**Issue by psoares** [openfaas/faas#286]
The README example on the testdrive says to type the following command:
`echo "# Test *Drive*"| faas-cli --invoke --name func_markdown`

The --name parameter needs to be removed for this to work, otherwise the following message displays: "Please provide a name for the function".

The correct syntax seems to be: 
`echo "# Test *Drive*"| faas-cli --invoke func_markdown`

**Comment by alexellis** [comment]
Thanks or mentioning this. We've recently made the change and the docs are catching up. Check back now. 

Alex
