### ISSUE TITLE
Async function call duration is not exported

### ISSUE THREAD

**Issue by developius** [openfaas/faas#291]
Async function calls don't export the execution duration of the call, unlike non-async calls.
They do, however, track the status code.

## Expected Behaviour
Execution duration should be exported to prometheus

## Current Behaviour
Async function calls do not record execution duration

## Steps to Reproduce (for bugs)
1. Call an async function
2. Observe tracked status code, but not duration

## Context
Was wondering why there were no execution duration graph points in my Grafana dashboard

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 17.09.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by elliott-beach** [comment]
I can get started on this and learn something about Prometheus. H

**Comment by elliott-beach** [comment]
Still figuring this out - I think this will involve calling trackTime at some point during handling of request to `"system/async-report"` 

Calling trackTime:
https://github.com/openfaas/faas/blob/6dc9ffbfce2abd58a3cdde518fcd1fabd33e196e/gateway/handlers/proxy.go#L198-L205

Around here:
https://github.com/openfaas/faas/blob/6dc9ffbfce2abd58a3cdde518fcd1fabd33e196e/gateway/handlers/asyncreport.go#L15-L24

Correct?

**Comment by ericstoekl** [comment]
Derek assign: elliott-beach

**Comment by alexellis** [comment]
Sounds about right to me. Do you want to try it out? Technically you can test this work during development by using `curl` or postman to hit the gateway.

**Comment by alexellis** [comment]
Derek assign: elliott-beach

**Comment by alexellis** [comment]
Fixed in #338
