### ISSUE TITLE
Document Environment Variables

### ISSUE THREAD

**Issue by elliott-beach** [openfaas/faas#298]
There are several undocumented environment variables :

Watchdog (read into WatchdogConfig):
`fprocess`, `read_timeout`, `writeTimeout`, `write_debug`, `cgi_headers`,
`marshal_request`, `debug_headers`, `suppress_lock`, `content_type`

Gateway (read into GatewayConfig):
`read_timeout`, `write_timeout`, `functions_provider_url`, `faas_nats_address`,
`faas_nats_port`, `faas_prometheus_port`, `faas_prometheus_host`

Faas-netes:
 `read_timeout`, `write_timeout`,`enable_function_readiness_probe`

## Possible Solution
I feel the readme for both faas and faas-netes is sprawling and I would prefer to add an `env_vars.md` in each provider (faas-netes and faas) documenting possible environment variables.

Minikube uses an  [env_vars.md](https://github.com/kubernetes/minikube/blob/master/docs/env_vars.md), which makes me think we should do it in this way.

## Context 
https://github.com/openfaas/faas-netes/pull/33#issuecomment-335726964

**Comment by elliott-beach** [comment]
Does anyone know why the openfaas gateway and watchdog both have environment variables configuring http timeouts? What's the use case for configuring the watchdog differently than the gateway?

**Comment by johnmccabe** [comment]
Wouldn't going with a single gateway defined timeout result in you always using the longest timeout for all watchdog processes regardless of whether it made any sense in the context of that specific function?

**Comment by elliott-beach** [comment]
yeah, makes sense.

**Comment by rgee0** [comment]
The watchdog variables are described here:

https://github.com/openfaas/faas/tree/master/watchdog

What would you like to see beyond this detail?

**Comment by elliott-beach** [comment]
@rgee0 Thanks, didn't see that! I'll try and imitate that style into documentation for faas-netes or the gateway if a similar table doesn't exist.

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by johnmccabe** [comment]
Derek add label: skill/beginner

**Comment by alexellis** [comment]
+100 points for this issue. A readme in the Gateway directory would be good 👍 and the same table for faas-netes.

**Comment by InTheCloudDan** [comment]
If the table is just being copied wouldn't it be cleaner to just point a link for faas-netes to the table here? That way there is a single source of truth for the information.

**Comment by alexellis** [comment]
Gateway needs separate config from faasnetesd and visa versa because they are deployed as separate processes or containers. I don't mind some repetition over no documentation.

**Comment by alexellis** [comment]
I think this is complete now. thanks @elliott-beach - :1st_place_medal:
