### ISSUE TITLE
Proposal: Set an env var to make container aware if started in faas context

### ISSUE THREAD

**Issue by udondan** [openfaas/faas#304]
I'm looking into creating an image that can run a program adhoc when started by hand _or_ with the faas watchdog in front of it when deployed through faas.

If faas could just set an env var (e.g. `IS_FAAS`) that can be checked this should do it. Inside the entrypoint script then one can do something like this:

```bash
if [ -z "$IS_FAAS" ]; then
  echo "running adhoc..."
else
  fwatchdog
fi
```

## Expected Behaviour
When container is deployed, an env var should be set.

## Current Behaviour
The only env var that is always set by faas is `fprocess`. But since that can/should be part of the Dockerfile it would also be set if not deployed through faas.

## Possible Solution
I believe this can easily be added in [handlers.buildEnv](https://github.com/openfaas/faas/blob/master/gateway/handlers/createhandler.go#L112-L121).

Happy to make this my first contribution, if proposal is accepted.

## Context
I'm evaluating OpenFaaS for [Ansible Silo](https://groupon.github.io/ansible-silo/). With Silo you can also build standardized Ansible bundles (=Docker image). I would like to add OpenFaaS support right out of the box for said bundles.

**Comment by alexellis** [comment]
I don't fully understand the motivation. Can you give a full example please?

**Comment by udondan** [comment]
I created a Docker image to show the goal: [udondan/awesome](https://github.com/udondan/faas-awesome)

You can run this adhoc:

```
$ docker run -it udondan/awesome
yay
```

Or deploy it as a function to OpenFaaS:

```
$ faas-cli deploy --image=udondan/awesome --name=awesome --fprocess="awesome" -e "IS_FAAS=1"
Removing old service.
Deployed.
URL: http://localhost:8080/function/awesome

200 OK
```

And then invoke it.

```
$ true | faas-cli invoke awesome
yay
```

The entrypoint of the image decides, based on the existence of the env var `IS_FAAS` if the watchdog should be started or the _awesome_ application should be triggered directly.

Right now you need to set `IS_FAAS` manually during deployment. I would like to see this happening automatically.

**Comment by udondan** [comment]
Does the example make sense? Also, can we tag this correctly as proposal?

**Comment by alexellis** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
I'm sorry I don't understand what this is trying to achieve.

**Comment by udondan** [comment]
I'm honestly puzzled how this can still not be clear. Trying one last time to put this into other words:

The goal of this proposal is, to make the software running inside the container aware if it is been executed as a function in faas - or not. With the awareness of this fact, images can be built with **optional** faas support and applications don't need to be re-packaged just for faas. 

If that still doesn't make any sense, please close it. I am not able to describe it any better.

**Comment by alexellis** [comment]
I'm just asking for a use-case. Give me a practical example explained clearly.

How about @rgee0 @JockDaRock ?

**Comment by udondan** [comment]
In the ticket description I already mentioned our Ansible use case. Let me elaborate a bit on how that is related.

Ansible needs to run in a very controlled environment, especially the Ansible version itself [should never be changed](https://www.reddit.com/r/ansible/comments/739zdr/is_it_just_me_or_does_working_with_ansible_kind/) if you don't want to break your old playbooks, roles, modules and plugins. That Ansible is written in a scripting language (Python) and its module dependencies could appear in any version just makes it worse. That's why we decided to bundle our playbooks including all dependencies together with Ansible into an Docker image. [Ansible Silo](https://groupon.github.io/ansible-silo/) is a tool to easily create such bundles.

The reason how that is related to OpenFaaS is the way how we use Ansible. Or better, in which dimensions. In my company we have about 25k remote systems to manage. This is not (only) about deployment of applications. This is primarily about updating DNS configuration, Splunk forwarding rules, monitoring rules and such - on a daily basis.

The original idea was to run these images directly on an k8s cluster. Then I accidentally found OpenFaaS and thought it's a perfect match. Bundles can be set up as functions and triggered asynchronously with differing payload (e.g. Splunk forwarding rules). Still, the same bundle can be executed locally by any developer without involving k8s, OpenFaaS. Of course this does not require any predefined env var. The one deploying the function could take care of it. For us, this would anyway be an automated process, an image that gets uploaded to our private registry can automatically be deployed as a function. Though Silo is open source and if we add the FaaS watchdog to Silo it would be great if any user could just load that Silo bundle as a function in FaaS w/o having to take care of details like forwarding env vars to trigger some behavior.

I don't have any other example, but I'm sure there are many Docker images that run some kind of job and could benefit from OpenFaaS support. Everyone can set their own env var to start the watchdog or we can define a standard in OpenFaaS itself.
