### ISSUE TITLE
Question - how do I run on ARMHF or ARM64?

### ISSUE THREAD

**Issue by DQvsRA** [openfaas/faas#306]
I'm experimenting with OpenFAAS from "Morning coffee with the OpenFaaS CLI"

## Expected Behaviour
I should have a built docker image, isn't it?

## Current Behaviour
En error 

## Steps to Reproduce (for bugs)
Following the description
Here is a picture
![image](https://user-images.githubusercontent.com/442111/31630469-f82c37a6-b2b6-11e7-9ac1-8fd56a522e1f.png)

## Your Environment
Docker version 17.09.0-ce, build afdb6d4

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux odroid64 3.14.79-116 #1 SMP PREEMPT Tue Sep 26 01:19:06 BRT 2017 aarch64 aarch64 aarch64 GNU/Linux

Help me, please!

**Comment by rgee0** [comment]
Although not explicitly stated, the tutorial is really intended for readers using linux/mac. You appear to be trying to build from an x86_64 Dockerfile on an aarch64 system.

**Comment by DQvsRA** [comment]
Same thing happened for armv7, orangepi plus 2e
![image](https://user-images.githubusercontent.com/442111/31631819-3cf7de54-b2bb-11e7-9e94-bb5d0e477f97.png)

**Comment by DQvsRA** [comment]
@rgee0 Yes it's true. I thought that "Serverless functions on any platform" ([link](https://blog.alexellis.io/quickstart-openfaas-cli/)) includes arm processors. Isn't it?

**Comment by rgee0** [comment]
You've swapped aarch64 for armv7l, so this is to be expected.  You'll need to swap the template to accommodate the architecture you are running on

You could try copying the Dockerfile from `./template/node-armhf/` into `./template/node` before running `faas-cli build`?

**Comment by DQvsRA** [comment]
@rgee0 Now it's built. And I probably should use --lang node-armX, next time?

Successfully built ded0d9c3f714
Successfully tagged callme:latest
Image: callme built.
[0] < Builder done.

**Comment by rgee0** [comment]
Currently its a manual task to patch the Dockerfile according to your chosen architecture.

Glad we got you moving.

**Comment by rgee0** [comment]
Derek add label : question

**Comment by alexellis** [comment]
Changing title to "Question - how do I run on ARMHF or ARM64?"

Answer - ARM64 support is in-progress, we can walk you through it but ARMHF is easier.

@DQvsRA details for ARMHF are explicitly stated in this tutorial: (requires patching the Dockerfiles for ARM)

https://blog.alexellis.io/serverless-golang-with-openfaas/

**Comment by alexellis** [comment]
Closing due to label "resolved" - @DQvsRA please checkout the PRs we raised above. Feel free to keep commenting.
