### ISSUE TITLE
Proposal: Quick guide for ARMHF / ARM64

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#307]
This will be a quick guide showing:

* Deploying on ARMHF on Swarm
* Getting the CLI
* How to patch the templates

For ARM64 we'd show:

* How to deploy on Swarm
* How to patch the templates (includes Nodejs)

I suggest this is written by a maintainer or contributor.

**Comment by rgee0** [comment]
Readme.md, or blog? If .md would this be placed in faas-cli?

**Comment by alexellis** [comment]
Guide in the guides folder so that this is documented re: #306

**Comment by rgee0** [comment]
Is the latest armv8 branch [arm64_part1](https://github.com/openfaas/faas/tree/arm64_part1)?

Is there a possibility to add a deploy_stack.arm64.sh to this branch to simplify the guide?

**Comment by alexellis** [comment]
I think if ARM64 is still WIP we can say that and mention what is available.

I would like a single deploy_stack file which checks the uname and then picks the right compose file..

**Comment by alexellis** [comment]
>Is the latest armv8 branch arm64_part1?

yes
