### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by DQvsRA** [openfaas/faas#308]
I'm trying to run an example project callme on nodejs but armv7

## Expected Behaviour
Running on localhost:8080

## Current Behaviour
"... cannot connect to OpenFaaS on URL: http://localhost:8080"

## Steps to Reproduce (for bugs)
Same as in topic "Morning coffee with the OpenFaaS CLI"
faas-cli deploy -f callme.yml (with or without --gateway "http://localhost:8080" )

## Context
![image](https://user-images.githubusercontent.com/442111/31634104-a18af5ac-b2c2-11e7-8416-20bf6dac94cb.png)

**Comment by DQvsRA** [comment]
And the same thing on armv8. Is this a general problem of a network setup?

root@odroid64:~/openfaas#  faas-cli deploy -f callme.yml
Deploying: callme.
Error removing existing function: Delete http://localhost:8080/system/functions: dial tcp [::1]:8080: getsockopt: connection refused, gateway=http://localhost:8080, functionName=callme
Is FaaS deployed? Do you need to specify the --gateway flag?
Post http://localhost:8080/system/functions: dial tcp [::1]:8080: getsockopt: connection refused

**Comment by rgee0** [comment]
::1 suggests it’s trying to dial ipv6.

Either try 127.0.0.1 instead of localhost or if possible comment out the ipv6 entry in your hosts file.

**Comment by rgee0** [comment]
Derek add label: question

**Comment by DQvsRA** [comment]
Hosts are clean now but still same problem

![image](https://user-images.githubusercontent.com/442111/31636057-600be1ca-b2c9-11e7-8700-2caf432d7a51.png)

**Comment by rgee0** [comment]
Is 8090 as the port a typo?

**Comment by DQvsRA** [comment]
It does not matter the same thing happened on every port number. Or what do you mean?

**Comment by rgee0** [comment]
The gateway normally runs on port 8080, rather than 8090.

You were trying 8080 earlier, why have you changed to 8090 since resolving the IPv6 issue?

**Comment by DQvsRA** [comment]
@rgee0 I tried different ports but every time have the same output

**Comment by rgee0** [comment]
Are you running OpenFaaS Swarm or Kubernetes - which pre-requisite did you follow from the guide?

**Comment by DQvsRA** [comment]
It's a Swarm

**Comment by rgee0** [comment]
Please provide output of `docker service ls`

**Comment by DQvsRA** [comment]
It's clean

![image](https://user-images.githubusercontent.com/442111/31651282-524d6520-b31b-11e7-86d6-1652fad84de7.png)

**Comment by rgee0** [comment]
Indicates that OpenFaaS isn't deployed. And the same on the arm7 machine?

I suggest that on the arm7 machine you following the instructions in the swarm deployment guide:

https://github.com/openfaas/faas/blob/master/guide/deployment_swarm.md

With one change to the deploy command run the following:

```
$ git clone https://github.com/openfaas/faas && \
  cd faas && \
  git checkout 0.6.5 && \
  ./deploy_stack.armhf.sh
```

This aims to deploy the arm stack. 

As @alexellis mentioned in #306 arm64 support in work in progress so suggest getting to grips with OpenFaaS on arm7 in the shorter term.

**Comment by DQvsRA** [comment]
Seams like that problem about GOPATH. I checked everything again and rebound PATH. 
After rebuild "callme" nodejs example for arm64 (Odroid C2) the result is next:
![image](https://user-images.githubusercontent.com/442111/31661556-7bbdc4d4-b33b-11e7-8927-7ebe286817b5.png)

![image](https://user-images.githubusercontent.com/442111/31661581-8b0dc7a4-b33b-11e7-9f32-df650384d497.png)

For armv7 deploy become frozen:
root@orangeP2E:~/openfaas# faas-cli deploy -f callme.yml
Deploying: callme.

**Comment by DQvsRA** [comment]
It's WORKING!
root@odroid64:~/openfaas# date | faas-cli invoke callme
{"status":"done"}

Thanks for help!

**Comment by rgee0** [comment]
Derek add label: Resolved

**Comment by rgee0** [comment]
Derek add label: resolved

**Comment by alexellis** [comment]
Closed since this appears to be resolved. Feel free to keep commenting.

**Comment by alexellis** [comment]
@rgee0 Derek can also close issues.

**Comment by rgee0** [comment]
@alexellis can he?  I couldn't see provision in the code for closing / re-opening.

```
	commands := map[string]string{
		"Derek add label: ":    "AddLabel",
		"Derek remove label: ": "RemoveLabel",
		"Derek assign: ":       "Assign",
		"Derek unassign: ":     "Unassign",
	}
```

**Comment by alexellis** [comment]
I might be wrong then.. I think maybe we at least have an issue around for it. Do you want to work on it?
