### ISSUE TITLE
Function return Content-Type not honored by Gateway

### ISSUE THREAD

**Issue by mcgoober** [openfaas/faas#312]
## Expected Behaviour
The watchdog has a setting 'content_type' which when set forces the return content-type of a function. This content-type that is returned by the watchdog should be also be returned by the gateway.

## Current Behaviour
The gateway returns the same content-type as the request. i.e if you POST with content-type 'application/json' in the request, then 'application/json' is in the response, no matter what the function actually returns.

## Possible Solution
https://github.com/openfaas/faas/blob/master/gateway/handlers/proxy.go#L173
At the time of writing...
https://github.com/openfaas/faas/blob/dde98eb582c381d07d4b7c6842b815c455179b57/gateway/handlers/proxy.go#L173

This line of code forces response content-type to the request and overwrites the function return content-type. The comment above the line suggests that this may been thought about.

Removal of this line prevents the content-type from being overwritten and allows the gateway to return the correct content-type for the function.

## Steps to Reproduce (for bugs)
1. Create a function with env var 'content_type' set to 'text/html'
2. POST to the function with request content-type say.. 'application/json'
3. Function will return 'application/json', this is true for any content-type

## Context
Found this issue whilst attempting to make a function that returned HTML for a browser and thus develop a web application as a function or set of functions. The browser won't display the returned HTML  unless the content-type is 'text/html'.  
This solution also requires the ability to call a function with a GET, but I've accomplished this in another way.

## Your Environment
* Gateway 0.6.6d
* Watchdog 0.6.6d
* Docker Swarm 17.06.1-ce

**Comment by alexellis** [comment]
Thanks for using OpenFaaS @mcgoober 

I am sure I have this working correctly in my recent Alexa skills - but it may be as you say because of the caller. I'll look into this over the next few days. We can also take a PR if you want to move quicker than that.

You can also checkout the new code branch I pushed on for enabling "GET" routes. We published some info about it in the Slack channel #general I believe.

**Comment by alexellis** [comment]
Thank you for picking this up @ericstoekl

**Comment by alexellis** [comment]
@ericstoekl I had some time to work on this on the flight.

**Comment by alexellis** [comment]
I've implemented the new behaviour with a fall-back to old behaviour when the variable is not defined with a value.

**Comment by mcgoober** [comment]
Thanks @alexellis for the fix. However the behavior hasn't changed in 0.6.7. 
The pull request from this ticket would have worked as far as I can see...
https://github.com/openfaas/faas/commit/6d5ae1af5bf5b2f8f365438b3eac845000c4fb46#diff-a7739e9c4834f2d0769169a1c27e7774
However in a further commit this code was modified and the original functionality re-introduced due to an argument ordering error.
https://github.com/openfaas/faas/commit/520a6b05a18cf8add215ecca1d66dfead82b15ea#diff-a7739e9c4834f2d0769169a1c27e7774

Checkout the code on line 173 of proxy.go...
https://github.com/openfaas/faas/blob/ec60d975188ecd843d82a640471388e9ee3c149f/gateway/handlers/proxy.go#L173

This shows the order of parameters given to GetContentType as ResponseHeader then RequestHeader
However the order of the declaration of GetContentType is RequestHeader then ResponseHeader.

https://github.com/openfaas/faas/blob/ec60d975188ecd843d82a640471388e9ee3c149f/gateway/handlers/proxy.go#L180

**Comment by alexellis** [comment]
Can you give a concrete test-case that we can use to reproduce the issue?

**Comment by mcgoober** [comment]
I understand your need for a repro, and if I have to go to the trouble I will, but please check your code first.

Your tests for the new code in tests/proxy_tests.go are great, and work, because they call GetContentType with the correct parameter order (Request, Response, DefaultHeader). Your code in gateway proxy.go does not. 

The fix for this is to change the call to GetContentType in proxy.go to from...
`w.Header().Set("Content-Type", GetContentType(response.Header, r.Header, defaultHeader))`
to this...
`w.Header().Set("Content-Type", GetContentType(r.Header, response.Header, defaultHeader))`

**Comment by alexellis** [comment]
We have a lot of work on right now and a very small team. The issue template asks for a repro scenario so if this is important to you I'd ask you to help us help you.

**Comment by mcgoober** [comment]
Repro Steps...
1. Deploy gateway version 0.6.13 and create a function though the gateway UI as follows...
Image: functions/alpine:latest
Name: Putty
fprocess: wget -q -O - http://www.putty.org/

2. Execute this command to add content_type env param to service. This line should force the response to always return 'text/html'. I'm using Docker, but I'm sure an equivalent command for Kubernetes exists.
sudo docker service update --env-add content_type=text/html Putty

3. With a web browser, browse to /function/Putty and inspect the gateway logs...

[1513077542] Forwarding request [] to: http://?.?.?.?:8080/function/Putty

This is correct, no content type was given in the GET hence the [] and we got a page rendered which means the content-type came back as 'text/html' as the function is supposed to.
This can also be checked with the following...
curl -v http://gateway:8080/function/Putty

4. Now execute the following POST to /function/Putty and inspect the gateway logs...
curl -v -X POST -H "Content-Type: text/plain" http://gateway:8080/function/Putty

[1513077575] Forwarding request [text/plain] to: http://?.?.?.?:8080/function/Putty

The logs show that the content type was passed through to the function correctly. But the final response from the gateway has content type set to 'text/plain', not 'text/html' as the function should force it to.
Any content-type can be specified in the POST and the function will always mirror the content-type on the response no matter what the environment variable 'content_type' is set to in the service.

**Comment by alexellis** [comment]
Thanks for taking time to write this up.

So with step 2 you can just add the environment in the YAML when you deploy.

If you hard-code a request content-type then the proxy will match that for the return value. This behaviour can probably be removed now (subject to testing).

Historically the time when this was most useful was when writing an Alexa skill for instance which queries in JSON and was getting a text/plain response (the default). We can now override this at deployment time with 

```
  environment: 
    content_type: application/json
```

@austinfrey, @rgee0, @ericstoekl do either of you want to remove the code that matches request content-type to response content-type? 

Alex

**Comment by ericstoekl** [comment]
Can confirm that fixing the ordering of the function call parameters in `GetContentType()` fixes the issue for @mcgoober 's specific case.

@alexellis , do you want to remove the `headerContentType = requestHeader` assignment entirely, as taking `requestHeader` is not something we should ever do?

**Comment by mcgoober** [comment]
Many thanks for your help guys. I was wondering if it would be possible to allow a function to set the content type based on some logic. Headers from the request are transferred via environment vars to the function but could the function set content_type env var during execution such that its value is used as the response content type? 

Happy to raise another ticket to cover this as a feature request.

**Comment by alexellis** [comment]
This is not a simple request, it's hard to accomplish what you're asking for since you cannot extract data from the forked process other than stdout, stderr and the exit code. I.e. environment on a child process is not observable from the parent. We do have an alternative way of accomplishing this with the new afterburn mode. https://github.com/openfaas-incubator/of-watchdog

**Comment by alexellis** [comment]
Out of curiosity are you on Slack yet? Email alex@openfaas.com if you'd like to join.

**Comment by mcgoober** [comment]
Ohh, nice tip on afterburn mode. This will do the trick nicely. Yep, already on Slack, thanks for adding me.
