### ISSUE TITLE
Watchdog review: fprocess variable

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#316]
I'd like to discuss the experience of using the watchdog especially the `fprocess` variable which some of us understand to mean `fork_process`.

Can we improve on the name of the variable?

This issue is open for discussion - please do not create a PR.

**Comment by udondan** [comment]
I thought it meant `faas_process`.

In general I think it is important to namespace environment variables to avoid conflicts with other software.

I also prefer uppercase for environment variables.

Therefore my choice would be: `FAAS_PROCESS`

**Comment by rgee0** [comment]
Taking a semantic approach`process` implies a running state.  Within a container the Watchdog is running and upon function invocation the Watchdog issues a command to satisfy the function request.  

If the nomenclature is to change then I'd suggest involvement of `command` rather than `process`.

**Comment by alexellis** [comment]
`command` will conflict with `CMD` - the container directive. All OpenFaaS env-vars are currently lower_case @udondan 

faas_command - might work better but is pretty long

Maybe `faas_cmd`?

**Comment by alexellis** [comment]
@trusch I know you've been looking at the watchdog. Any thoughts from your side?

**Comment by LucasRoesler** [comment]
I like the idea of name spacing `faas_cmd` seems reasonable and clear. Although would it be more correct to say `watchdog_cmd`?

**Comment by trusch** [comment]
I think prefixing with the project name is quiet common to prevent collisions with other variables. So the only question is, what is the project name ;) From my point of view the current `fprocess` variable is specific to the openfaas/faas/watchdog implementation so either `watchdog_cmd` or `fwatchdog_cmd` would come to my mind.

**Comment by Lewiscowles1986** [comment]
`fwatch_cmd` for brevity and clarity? :thinking:

**Comment by stealthybox** [comment]
I always thought it meant `function-process` because it's used by the [Function Watchdog](https://github.com/openfaas/faas#function-watchdog).

I like `faas_cmd` or `watchdog_cmd`.

**Comment by alexellis** [comment]
Thanks for the suggestions.

`function_process` and `fprocess` are now both supported in the new of-watchdog project.
