### ISSUE TITLE
Kubernetes using rkt

### ISSUE THREAD

**Issue by shawnhwei** [openfaas/faas#317]
Does it work?

**Comment by austinfrey** [comment]
hi @shawnhwei, not sure if anyone has tried. i have not used rkt so maybe someone else can chime in here.

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by alexellis** [comment]
I suspect it would work exactly the same as using runc. We even have people using cri-containerd and runV. I'll close this issue because I'm not sure there is any useful context here. Feel free to keep commenting.

**Comment by shawnhwei** [comment]
Thanks for your replies. I was just curious if anyone had any experience using rkt before I invest time into it. I'll give it a shot and get back to you.
