### ISSUE TITLE
Add NATS Streaming stack for ARM

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#322]
## Expected Behaviour
Create ARM equivalents of `docker-compose.extended.yml`

## Current Behaviour
Currently `docker-compose.extended.yml` is aimed at x86_64.  

## Possible Solution
Create armhf and arm64 equivalents of `docker-compose.extended.yml`.
n.b. Full arm64 support is currently WIP so depending upon timings it may make sense to create the armhf equivalent initially.

Once #321 is merged the consolidated deployment script will need amending to enable deployment of extended on arm.

## Context
Addressing inconsistencies across hw platforms to simplify deployment and provide a more uniform user experience.

**Comment by rgee0** [comment]
Derek add label: Proposal

**Comment by alexellis** [comment]
Thanks.

Did you find the multi-arch images from nats.io for testing on ARM/RPi?

I can see "NATS" is multi-arch but not NATS-Streaming which is what we need.

https://hub.docker.com/r/library/nats/
https://hub.docker.com/r/library/nats-streaming/

**Comment by petemiron** [comment]
Sample Docker image is available at: docker pull `petemiron/nats-streaming-server-arm64`

Full multi-platform support will be available once this is merged: https://github.com/nats-io/nats-streaming-docker/pull/8 waiting on nats-streaming-server 0.6.0 release, which should be out end of this week (10/27/2017).

cc @kozlovic

**Comment by alexellis** [comment]
Hey Peter, thank you. This will be very helpful for a Hyper armv demo and for Packet. I need the 32-bit version for Raspberry Pi for the demo we talked about. I'll also have a look at the Dockerfile for this.

**Comment by kozlovic** [comment]
@alexellis We have this [PR](https://github.com/docker-library/official-images/pull/3622) submitted to the official-images repo. We do include an arm32v7 docker image. Hope this is what you were looking for. The PR has not been merged yet, but they usually have a pretty good turn around, so I would not be surprised if this was merged today and available on Docker Hub by EOD.

**Comment by kozlovic** [comment]
@alexellis If you need to build your own docker image, it is pretty simple. If you don't need to recompile the server with Go 1.9.2, then simply go on an ARM machine where docker is installed, then either clone repo https://github.com/nats-io/nats-streaming-docker/ and cd into directory `arm32v7` or copy the content of this directory locally and then build the image:
```
docker build -t <image name> .
```
You should now have an ARM32v7 docker image of NATS Streaming v0.6.0 server.

If you need to recompile, generate the executable with the appropriate Go version this way. Note that this is using cross-compile, so you can build from any platform, say macOS:
```
env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -v -a -tags netgo -installsuffix netgo -ldflags "-s -w -X github.com/nats-io/nats-streaming-server/version.GITCOMMIT=`git rev-parse --short HEAD`" -o nats-streaming-server
```
Copy the generated executable to the directory I mentioned above and build the docker image as described before.

**Comment by kozlovic** [comment]
@alexellis It seems that they have merged the PR and there is a tag for arm32v7. However, it seems that there is a problem and the linux/amd64 seem to be unavailable. Not sure what's going on there.

**Comment by alexellis** [comment]
@kozlovic I think it's all good now for ARMHF - not sure about ARM64?

**Comment by alexellis** [comment]
This is now available for armhf in our repo.

**Comment by kozlovic** [comment]
@alexellis we do have an ARM64 image too.

**Comment by alexellis** [comment]
Perfect.. 👍
