### ISSUE TITLE
Suggestions for watchdog

### ISSUE THREAD

**Issue by trusch** [openfaas/faas#334]
I see some problems regarding the openfaas watchdog.

Problem 1: The watchdog does a `ioutil.ReadAll(r.Body)` before calling the function. This could be fatal if a function can take huge amount of data as input (think about hashing a movie or something).

Problem 2: The watchdog itself is not very carefully written from my perspective. The `pipeRequest()` function is ultra long and not very maintainable. Given the fact that the only supported way for a user to supply its own code to openfaas is to wrap it with the watchdog, should animate us to write the watchdog very carefully. I know how this project was started, and that the watchdog is not the hardest part in openfaas. Therefore I understand why this is the status quo.

Problem 3: Because the watchdog is the only supported way of supplying code, even functions written in go would walk through a full fork/exec style execution. I know there are discussions about "afterburn" but I think this will only try to fix this someway and not solve it completely.

I tried to tackle these problems with this project: [trusch/frunner](https://github.com/trusch/frunner)

It is meant to be a drop-in replacement (I think it is not ready for that at the moment, we would need to review that) for the openfaas/faas/watchdog. It solves problems 1 and 2 and provides an abstraction layer for callables which enables us to create a native go template (in the sense of the `cli`) which then wouldn't be forced to fork/exec for every function call.

Please let me know if there is interest in `frunner` I would love to see this landing in openfaas/faas as a replacement or the current watchdog program.

**Comment by trusch** [comment]
Things that are definetly missing:

* writing the lock-file
* interpret the `cgi_headers` environment variable (currently on by default)
* The whole "json / not json" handling

**Comment by alexellis** [comment]
My sense is that there are more effective ways to introduce oneself to a community and better ways of delivering feedback and criticism, especially when aiming to influence.

On your feedback

Note 1 - "reads all data before invoking function"

Happy for you to prototype an alternative in a PR for review. A `read_limit` may be sensible and the watchdog could read incrementally into a buffer and reject the request if the data incoming exceeds agreed contract.

Note 2 - The watchdog can be refactored into smaller pieces.

If you have time to refactor the functions into smaller parts which are coherent then have a go at it and we'll review the PR. Please note that this should still be procedural and read top to bottom.

Note 3 - Fork/exec is not the only supported method. See #224

**Comment by trusch** [comment]
I'm sorry if I was too direct and hurt your feelings. I already stated my understanding of why the current form of the watchdog is as it is. I really like this project and when reading over the codebase I simply found the watchdog implementation.

My only concern is that such a basic component, which is used in every function call, should be written very carefully. Once again, I did not want to blame you for that or say that you didn't take care when writing it. I think you simply have other, more important, things to implement and so the watchdog is on a lower priority.

As you can see I already proposed an prototype. I could prepare a PR, but I think there are some points to be clarified before adding more work into this.

What would be a more effective way than finding a problem, describing it and proposing software which tries to solve them?

**Comment by trusch** [comment]
I added `read_limit` to [trusch/frunner](https://github.com/trusch/frunner) as suggested by @alexellis

**Comment by rorpage** [comment]
I agree with Alex that there are better ways to jump in. If you think changes are needed for the watchdog, then it would help to document that in constructive language with test cases to demonstrate the point you are trying to make.

As far as swapping out the watchdog with your own code, that's not typically how things are done in, really, any open source project I've seen. It’s much better to get to know the team and maintainers, raise your concerns, and open a two-way discussion. Please also review the guidelines in the `CONTRIBUTING.md` document as well.

We appreciate your ideas very much, but I think there are better ways to participate.

**Comment by trusch** [comment]
I got your point but do not want to swap out the watchdog. This is not a PR. It just happened that this prototype exists and I just referenced it here to have a basis to discuss on.

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
I think issues have been opened or points addressed in openfaas-incubator/of-watchdog. Closing, please feel free to keep commenting.
