### ISSUE TITLE
Proposal: Refactor custom limits for maximum auto-scaling limits

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#339]
We currently have a max number of replicas for any function, but in Swarm we also support overriding that. This issue is about providing a label that can be passed at deploy-time to specify the minimum number of replicas and maximum number too.

* If the min=max this disables auto-scaling on a per-function basis
* This should be agnostic to Kubernetes, Swarm or any other back-end
* We may have to expose labels through the GET /system/functions endpoint which currently lists off deployed functions.

**Comment by austinfrey** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
In progress via #414
