### ISSUE TITLE
Proposal: gateway: pass request body to service without buffering

### ISSUE THREAD

**Issue by trusch** [openfaas/faas#341]
The request body is currently buffered completely in the gateway. There is no need for that as discussed in #337

## Expected Behaviour
There should be no full buffering of incoming requests in the gateway

## Current Behaviour
The requests is buffered completely just to be wrapped in an bytes.Reader a few lines later.

## Possible Solution
Required change is in #340

## Context
I want to be able to process big input data (movies, big archives, etc.)

**Comment by austinfrey** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Believe we have implemented and released this now. Closing.
