### ISSUE TITLE
Proposal: watchdog: pass request body to process without buffering

### ISSUE THREAD

**Issue by trusch** [openfaas/faas#342]
The request body is currently buffered completely in the watchdog. There is no need for that as discussed in #337

## Expected Behaviour
There should be no full buffering of incoming requests in the watchdog

## Current Behaviour
The requests is buffered completely.

## Possible Solution
use io.Reader rather than a byte slice

## Context
I want to be able to process big input data (movies, big archives, etc.)

**Comment by austinfrey** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
This is available in of-watchdog https://github.com/openfaas-incubator/of-watchdog
