### ISSUE TITLE
Make stderr output from the function available to clients (e.g. for logging)

### ISSUE THREAD

**Issue by imikushin** [openfaas/faas#347]
## Expected Behaviour
As a FaaS function developer, I'd like to be able to use standard POSIX streams in a familiar way: stdin to read input, stdout to write output, stderr - to print/log messages and errors.

The proposal is to capture both stdout **and** stderr and return the content of both, appropriately separated, so that the API clients could make use of both.

An example CLI usage would look like:
```sh
$ cat ./source.svg  |  faas-cli -q invoke my-svg-render  >./out.png  2>./log.txt
```

## Current Behaviour
Currently, stderr is not captured by OpenFaaS. 

## Possible Solution
A possible API implementation could be using a custom header that would contain base64 encoded stderr content.

## Context
I'd like to write my function logging messages to stderr, following a familiar convention: e.g. in logrus (a Go logging library) the default logger writes to stderr. On the client side I'd like to be able to see these messages or discard them as I see fit.

**Comment by austinfrey** [comment]
Derek add label: proposal

**Comment by imikushin** [comment]
Related to #337

**Comment by alexellis** [comment]
Getting stderr is important, but the HTTP transport is raw binary, so you would have to do special encoding or serialisation which I don't think is a good idea.

What behaviour have you observed currently? Do you have a function which prints to stderr and stdout?

We need to take some proposals on the implementation detail and design.

**Comment by alexellis** [comment]
Current function side-car/watchdog implementation:

https://github.com/openfaas/faas/tree/master/watchdog

Proposed re-write:

https://github.com/openfaas-incubator/of-watchdog/blob/master/README.md

Perhaps this would fit into the "Serialising model"?

**Comment by alexellis** [comment]
<img width="1212" alt="screen shot 2017-10-31 at 08 29 23" src="https://user-images.githubusercontent.com/6358735/32214099-9fd9cf54-be15-11e7-9697-732968aa51cc.png">

@imikushin also checkout this example.. If your caller knows how to deserialise your custom format, you are able to write back some sort of custom payload.

**Comment by imikushin** [comment]
The problem that we want to solve is being able to look at the logs, errors and stack traces, that the function prints. In order to do that, we want to record all the information about the function invocation: 
- arguments (input), 
- results (output) and 
- logs (errors/messages).

As of now, we can only record the first two. The last one is the problem, because stderr content is not being captured and sent to clients. 

Design options:

1.  Reply with stderr content in a custom header. Works for situations where the output is sent all at once - when the invocation has ended (either normally or with errors). The older clients will just ignore the header.

2.  Multiplex out/err streams. The client needs to specifically request this mode (perhaps via Expect or a custom header).

3. Reply with redirect (Location) to output and Link to error stream. The client needs to specifically request this mode (perhaps via Expect or a custom header).

**Comment by alexellis** [comment]
Derek close: fixed with watchdog via `combine_output` flag
