### ISSUE TITLE
Proposal: Golang Kafka connector for OpenFaaS functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#361]
The University of Calgary put together a Kafka connector for their OpenFaaS deployments. 

https://github.com/ucalgary/ftrigger

We have had several requests for the ability to trigger a function (via the gateway) from a message published to a Kafka topic. Let's think about how to provide a connector written in Go. At the same time it's worth thinking about how this pattern could be applied to other event sources such as:

* AWS events #263 
* MSFT Azure's EventGrid

@kinghuang does this by matching up labels on functions to topic subscriptions and it seems to work very well and maintains simplicity too.

**Comment by alexellis** [comment]
Initial alpha version of the Kakfa Connector in Golang - https://github.com/openfaas-incubator/kafka-connector

**Comment by austinfrey** [comment]
cc @viveksyngh this could probably use some attention if you're interested

**Comment by alexellis** [comment]
I would like input from @kinghuang and maybe @kars7e too on whether a single topic is suitable for triggering functions. Can we use a wildcard for a consumer with this Go library?

**Comment by viveksyngh** [comment]
I was looking for issues to work on. @austinfrey was helping me out by pointing to some issues on which I can work on.

**Comment by alexellis** [comment]
Derek close: https://github.com/openfaas-incubator/kafka-connector
