### ISSUE TITLE
Proposal: Capture stdout from the watchdog when running Afterburn mode

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#362]
## Expected Behaviour
stderr from the process could be piped to stdout so that errors can be made available within logs

## Current Behaviour
Function errors are not easily observable

## Possible Solution
Similar work took place under #313

## Steps to Reproduce (for bugs)
Not a bug

## Context
Errors occurring within Afterburn functions are not easily observable

## Your Environment
Not a bug

**Comment by rgee0** [comment]
Derek add label: Proposal

**Comment by alexellis** [comment]
I have this pushed up for testing. also #313 https://github.com/openfaas-incubator/of-watchdog

**Comment by alexellis** [comment]
This is present in https://github.com/openfaas-incubator/of-watchdog @rgee0 can you test?

**Comment by alexellis** [comment]
Derek close: n/a
