### ISSUE TITLE
Question: Extreme memory requirements - Pod needs 13GB

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas#364]
I have a image processing function that need to use 13G memory. I create a Cluster
have 16G memory with 3 nodes. But I can not find a way to configure my function's 
Pod memory size or swap memory size. And if several request at same time, How to 
set configure to make my each function call can have enough memory to complete the job?

## Expected Behaviour
The image processing job can finish and upload the result.

## Current Behaviour
The image processing job will return memory not enough error.

## Possible Solution
Does faas-cli have command that can set the deploy function's memory/swap memory size? 
or I can manual set the function's pod's memory? But how can I ensure each job can have
13G free memory to use??

## Context

I can run my image processing function on local docker with large swap memory. I try to enlarge 
my cluster's memory but I found the root cause is that the function's pod only can use 40M memory and 0.419 cores cpu for one job request. I try to check the pod's yaml: it shows resources->requests->cpu:100m. I guess this is create by faas-cli deploy command. Can I use faas-cli to
increase my function's pod memory? and ensure each request can have at least 13G memory?

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes (FaaS-netes)
* Operating System and version (e.g. Linux, Windows, MacOS):
Local: MacOS 10.12.5, remote: GCP k8s
* Link to your project or a code example to reproduce issue:

**Comment by rayhero** [comment]
And I also notice that I can not change the function's pod memory. If I want to increase the pod's memory I need to create a new pods. But the create flow is control by faas-cli. How can I manual recreate the pod with large memory?

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by rayhero** [comment]
It seem like I can hard code modify the createhandler.go locate at gateway/handlers/ and redeploy the faas to make faas set my resource limit & request during deploying function?

**Comment by alexellis** [comment]
Hi @rayhero we're working on something which I think will help with dealing with more memory than is available in the pod. Are you dealing with a 16GB image file?\

What is the specific use-case and function? Is it available online for us to test?

**Comment by alexellis** [comment]
@trusch @rgee0 can we reproduce this issue simply?

**Comment by trusch** [comment]
@alexellis as you said we need more information about the specific nature of the usecase. Perhaps the function really needs that much memory than even io-streaming wouldn't help.

**Comment by rayhero** [comment]
@alexellis I using Open CV image processing library to do the image feature detection. Since I need to processing 4K image one one thread. Open CV need to use large memory to build the Gaussian Pyramid model for feature detection. I think I need to set the pod's memory limit to make sure each pod can have enough memory to finish it's job

**Comment by rayhero** [comment]
@alexellis if you want the docker image to test, I can provide the sample image for you to test the limitation setting is work or not.

**Comment by alexellis** [comment]
Please do that.. @rayhero

**Comment by alexellis** [comment]
Related to #379. Closing as resolved.
