### ISSUE TITLE
Doc Proposal: get started with the source code

### ISSUE THREAD

**Issue by wonderxboy** [openfaas/faas#366]
I am new to this awesome project. So when I browse the docs, I did not find a doc for "get started with the source code" or the like. I think it would be great if there is such a doc for someone new to this project, especially when he wants to contribute on the source code level. In the meanwhile, where should I get started if I want understand the source code?

**Comment by alexellis** [comment]
Hi Sean, the best way to get started if you would like to contribute is with the contribution guide and then one of the open issues. We'd also encourage you to join the Slack community so you can get connected and support for your first contributions. Email alex@openfaas.com to get started.

**Comment by alexellis** [comment]
I'll mark this issue as revisit and close, please feel free to keep commenting.

**Comment by alexellis** [comment]
Derek add label revisit

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Derek add label: revisit
