### ISSUE TITLE
Serverside callback when any function has been uploaded?

### ISSUE THREAD

**Issue by maxbry** [openfaas/faas#367]
Is it possible to determine a function/callback/script that should be triggered whenever a new function has been uploaded?

**Comment by alexellis** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Can you give the scenario please?

**Comment by alexellis** [comment]
@maxbry what's the use-case?

**Comment by alexellis** [comment]
Closing due to lack of information / activity.
