### ISSUE TITLE
Limit on how many functions can be deployed in a single server?

### ISSUE THREAD

**Issue by abdelhadi24** [openfaas/faas#368]
Is there a limit on how many _unique_ functions can be deployed in an openfaas instance?

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Hey @abdelhadi24 I think we'd need a bit more information to be able to help you. This depends on the size of your server and how much memory your functions require.
