### ISSUE TITLE
Question: Multi-tenancy

### ISSUE THREAD

**Issue by maxbry** [openfaas/faas#371]
I'm interested in using OpenFaaS for a team of developers. Each developer should work on dedicated problems and upload his solution. The functions should then being called by a backend system.
* When a function is used in a productive system, can it be prevented from being overridden?
* Can I limit access to that OpenFaaS server with something like accounts?

**Comment by alexellis** [comment]
Hi we have no multi-user support at this point however we'd recommend you deploy to your production servers via a CI/CD process which will void the problem above. If you need support for OpenFaaS we can invite you to the Slack community to talk about your use case more. Just drop an email to alex@openfaas.com

**Comment by alexellis** [comment]
We have provided an answer, so closing the issue. Please feel free to keep commenting.
