### ISSUE TITLE
Question: Is there a way to restrict to which nodes a function can be deployed?

### ISSUE THREAD

**Issue by Templum** [openfaas/faas#373]
Hello,

I have the following question regarding the OpenFaaS project. Is it possible to manipulate or restrict on which nodes a function gets deployed? Both kubernetes and swarm allow deploying services to nodes based on requirements. 

The use case I have in mind is, that I like some of the functions to be deployed in special regions to avoid issue regarding data laws. As for example, germany has more restrictive data laws in comparison to us.

Best regards
Simon

**Comment by austinfrey** [comment]
Hi @templum yes, you can apply constraints just like you would for regular swarm services. here is an example from the OpenFaaS docker-compose.yml https://github.com/openfaas/faas/blob/b92b0926fa11a1fae61925ec8fad066c159c486a/docker-compose.yml#L73

And here is a link to the Docker Swarm instructions: https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint

Perhaps someone could chime in regarding k8's as well.

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Hi @Templum are you using Docker swarm or Kubernetes?

Specify a constraint in the YAML file. More info here - https://github.com/openfaas/faas-cli#constraints

**Comment by Templum** [comment]
@alexellis I'm using Kubernetes

**Comment by alexellis** [comment]
@Templum what kind of constraints do you need? Label-based constraints?

**Comment by Templum** [comment]
@alexellis Normal label constraints should do the job. So will the "constraints" field within the yaml translate to nodeSelector for a kubernetes cluster? If so thanks for the help, and sorry for the caused inconvenience. I should have read the documentation more strictly then.

**Comment by alexellis** [comment]
I have nodeSelectors ready in https://github.com/openfaas/faas-netes/pull/77

I've done some initial testing on it by swapping the faas-netesd tag to "constraints". Would you like to take it for a test-drive and report back before we merge/release?

**Comment by alexellis** [comment]
This is merged now @Templum - let us know if you need any help with it.

**Comment by alexellis** [comment]
Docker image will be updatable now to:

https://github.com/openfaas/faas-netes/releases/tag/0.3.4
