### ISSUE TITLE
Question about localhost time-out

### ISSUE THREAD

**Issue by wonderxboy** [openfaas/faas#374]
1. run deploy_stack.sh
2. http://localhost:8080 shows up and functions work as expected
3. run deploy_extended.sh
4. http://localhost:8080 times out

## Expected Behaviour
Per the description on https://github.com/openfaas/faas/pull/131 , the functions can be invoked async after deploy_extended

## Current Behaviour
http://localhost:8080 times out
invoking functions also times out
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
 17.09.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS 10.12.6
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Have you checked the docs about localhost and ipv6? Perhaps try using 127.0.0.1 instead to force ipv4?

**Comment by alexellis** [comment]
Derek assign: rgee0

**Comment by wonderxboy** [comment]
The issue went away when I restart my docker...and it did not repo after that

**Comment by alexellis** [comment]
Great to hear that
