### ISSUE TITLE
Async route doesn't support GET

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas#376]
## Expected Behaviour

I should be able to invoke an async function via GET.

## Current Behaviour

Invoking an async function via GET is currently not possible as the route isn't configured (you get a `404`).

The nats-queue-worker also doesn't honour the request method set in the request object.

The introduction of support for GET invocations appears to have missed this out.

## Possible Solution

We should handle a GET and the nats-queue-worker should honour the method.

## Steps to Reproduce (for bugs)

1. Deploy an async gateway
2. Attempt to invoke an async function via GET
3. 404 returned

## Context

Trying to invoke an async function via GET.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.09.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
OSX

* Link to your project or a code example to reproduce issue:
n/a

**Comment by johnmccabe** [comment]
Derek add label: bug

**Comment by alexellis** [comment]
Derek remove label: bug

**Comment by alexellis** [comment]
Design constraint is that asynchronous functions are invoked with a post. Could raise a PR to document that.

**Comment by alexellis** [comment]
Derek add label: enhancement

**Comment by johnmccabe** [comment]
Derek remove label: bug

**Comment by johnmccabe** [comment]
Closing as docs have been updated

**Comment by johnmccabe** [comment]
Closing as docs have been updated
