### ISSUE TITLE
Upgrade NodeJS sample functions to latest LTS version

### ISSUE THREAD

**Issue by burtonr** [openfaas/faas#383]
The sample functions reference the previous version of NodeJS. 8.9.1 is now the current LTS

## Context
This change doesn't really affect this project directly, however, having the sample functions match the latest LTS version will (may) eliminate confusion that OpenFaaS doesn't support the latest version of NodeJS.

Update to the templates over on the cli project: [faas-cli PR](https://github.com/openfaas/faas-cli/pull/222)

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek close: done
