### ISSUE TITLE
Question: on scaling with high memory usage Pods

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas#389]
I using faas to do the image processing job. It cost 4cores,8GB memory/request and 20mins 
processing time. My environment is GCP kubernetes. I create a Cluster with 10core, 25GB memory.
I set the pod resource limit to 4core and 8GB memeoy. And I using 

`kubectl autoscale deployment auto-hotspot --cpu-percent=20 --min=1 --max=100 --namespace=openfaas-fn`

to do the pod's autoscaling.

When I try to send 2 request at same times, I receive unexpected status code: 500 - Can't reach service error or cannot connect to OpenFaaS on URL error

## Expected Behaviour
the pod should execute first job for first request. And the second request should wait for autoscaling. After second pod created, the second pod should execute second job for second request.

## Current Behaviour
the second request will receive two kinds of error:
    1. unexpected status code: 500 - Can't reach service
    2. cannot connect to OpenFaaS on URL
## Possible Solution
If I want to make sure the pod can process all the request. I need to pre-create enough pods to handle the incoming request. But it will spend more money to maintain lots of pods. If the request can wait for pod creation. We can make sure every job can be done.

Another approach is to check the gateway proxy server. modify the judgement from the request
to pod process. To make sure the pod have enough resource to process the request.

Moreover, maybe the readinessprobe is the correct way to avoid busy pod's get more job.

## Steps to Reproduce (for bugs)
1. Create cluster on GCP kubernetes. and set the cluster's resource with 10core, 25GB memory
2. Enable the cluster's autoscaling. min nodes=1, max nodes=100
3. Modify the pods spec to 4core, 8GB memory in faas-netes's /handler/deploy.go to:
```
                                Spec: apiv1.PodSpec{
					Containers: []apiv1.Container{
						{
							Name:  request.Service,
							Image: request.Image,
							Ports: []apiv1.ContainerPort{
								{ContainerPort: int32(8080), Protocol: v1.ProtocolTCP},
							},
							Env: envVars,
							Resources: apiv1.ResourceRequirements{
								Limits: apiv1.ResourceList{
								v1.ResourceCPU:    resource.MustParse("4000m"),
								v1.ResourceMemory: resource.MustParse("8192Mi"),
								},
							},
							ImagePullPolicy: v1.PullAlways,
							LivenessProbe:   probe},
					},
					RestartPolicy: v1.RestartPolicyAlways,
					DNSPolicy:     v1.DNSClusterFirst,
				},
```
## Context
I have check the auto scaling example @alexellis provide in ReadMe.md. It process 5 request/secs
use case. But my use case is each request will use all the pod's resource. But before autoscaling finish, the gateway will try to execute the job in same pod's and cause the terminate result. How to let gateway to keep the request until the autoscaling is finish?

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
Version: 17.09.0-ce
API version: 1.32
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:40:09 2017
OS/Arch: darwin/amd64
Server:
Version: 17.09.0-ce
API version: 1.32 (minimum version 1.12)
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:45:38 2017
OS/Arch: linux/amd64
Experimental: true
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes (FaaS-netes)
* Operating System and version (e.g. Linux, Windows, MacOS):
Local: MacOS 10.12.5, remote: GCP k8s
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Derek add label: question

**Comment by rayhero** [comment]
maybe the readinessprobe is the correct way to avoid busy pod's get more job?

**Comment by rayhero** [comment]
I finish this job by using the readinessprobe. The kubectl autoscaling can not work since the resource usage will be hide if the pod becom un available.

**Comment by rayhero** [comment]
@alexellis does openfaas support setting readinessprobe on each function?

**Comment by alexellis** [comment]
Hi @rayhero what is the difference between this issue and #379? Do you need two issues?

**Comment by alexellis** [comment]
@rayhero

**Comment by alexellis** [comment]
Derek close: inactive
