### ISSUE TITLE
Question: asynchronous & synchronous on same cluster possible?

### ISSUE THREAD

**Issue by stormwalkerec** [openfaas/faas#392]
As I'm new to this (OpenFaas & Kubernetes), under deployment_k8s.md you specify to choose with stack you want to install. If I recall correctly, in your demo video you mentioned to get async you just changed the url request. How did you achive both asynchronous & synchronous in your video ?

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by johnmccabe** [comment]
@stormwalkerec when you deploy with async support you can still invoke functions synchronously.

All that changes is the endpoint by which you invoke the function. For example, say you have a function called `mycoolfunction` you could invoke it as follows via these endpoints:

| Mode         | Method | URL                                            | Body | Headers  | Query string
| -------------|--------|------------------------------------------------|------|--------- |------------------- |
| Synchronous  | POST   | http://gateway/function/{function_name}        | Yes  | Yes      | Yes |
| Synchronous  | GET    | http://gateway/function/{function_name}        | Yes  | Yes      | Yes |
| Asynchronous | POST   | http://gateway/async-function/{function_name}  | Yes  | Yes      | Yes [#369](https://github.com/openfaas/faas/issues/369) |
| Asynchronous | GET    | Not supported                                  | -    | -        | - |

**Comment by alexellis** [comment]
Thanks for commenting @johnmccabe. @stormwalkerec I'm going to close the Issue since it's been answered now, but please feel free to keep asking questions here.
