### ISSUE TITLE
Can not set readinessprobe on each function

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas#396]
it's related to https://github.com/openfaas/faas/issues/389. I can set the readinessprobe on 
faas-netes/handlers/deploy.go. But it will let every function need to follow the readinessprobe check

## Expected Behaviour
Just like @alexellis enhance the function resource limit (https://github.com/openfaas/faas-cli/pull/225), Can we also put the readinessprobe setting on each function?

## Current Behaviour
If I add readinessprobe in faas-netes/handlers/deploy.go, I can let function check by readinessprobe. But other function which I don't want to check by readinessprobe is also need to
add the readinessprobe check.

## Possible Solution
Like @alexellis enhance the function resource limit (https://github.com/openfaas/faas-cli/pull/225), 
put the readinessprobe settings on each functions.

## Steps to Reproduce (for bugs)
1. add readinessprobe in deploy.go like below:
```
        readinessPath := "/root/.readinessprobe"
	readinessProbe := &apiv1.Probe{
		Handler: apiv1.Handler{
			Exec: &apiv1.ExecAction{
				Command: []string{"cat", readinessPath},
			},
		},
		InitialDelaySeconds: 1,
		TimeoutSeconds:      1,
		PeriodSeconds:       1,
		SuccessThreshold:    1,
		FailureThreshold:    1,
	}
```
and add this probe in PodSpec:
```
                                  Spec: apiv1.PodSpec{
					Containers: []apiv1.Container{
						{
							Name:  request.Service,
							Image: request.Image,
							Ports: []apiv1.ContainerPort{
								{ContainerPort: int32(8080), Protocol: v1.ProtocolTCP},
							},
							Env: envVars,
							Resources: apiv1.ResourceRequirements{
								Limits: apiv1.ResourceList{
								v1.ResourceCPU:    resource.MustParse("4000m"),
								v1.ResourceMemory: resource.MustParse("8192Mi"),
								},
							},
							ImagePullPolicy: v1.PullAlways,
							LivenessProbe:   probe,
							ReadinessProbe: readinessProbe},
					},
					RestartPolicy: v1.RestartPolicyAlways,
					DNSPolicy:     v1.DNSClusterFirst,
				},
```
2. add sample function by faas-cli
3. the function will not available since it don't have readiness check file

## Context
When processing large resource used pod autoscaling. you need to use readinessprobe to avoid too many job apply to same pods. But it we have another light weight function not need the readinessprobe. All of they need to add the readinessprobe check and it's not make sense

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
Version: 17.09.0-ce
API version: 1.32
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:40:09 2017
OS/Arch: darwin/amd64
Server:
Version: 17.09.0-ce
API version: 1.32 (minimum version 1.12)
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:45:38 2017
OS/Arch: linux/amd64
Experimental: true
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes (FaaS-netes)
* Operating System and version (e.g. Linux, Windows, MacOS):
Local: MacOS 10.12.5, remote: GCP k8s
* Link to your project or a code example to reproduce issue:

**Comment by austinfrey** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
This suggestion configures the readiness check on a per function basis. I'm not sure what the point of that is?

**Comment by alexellis** [comment]
Derek close: inactive
