### ISSUE TITLE
the function  can not be reached  from the OpenFaaS gateway when the function is scaling 

### ISSUE THREAD

**Issue by chaim1986** [openfaas/faas#405]
When I did a stress test to my function "whoami" from the  OpenFaaS gateway  , I got some errors  like "Can't reach service:  whoami " which  responsed from the JMeter.  

I find that all these errors happened when the function is auto-scaling,  and at the same time the function will disappear from the OpenFaaS Portal  UI and go back again when the scaling finish . 

I  think maybe  there are something to do to improve this situation...

## Expected Behaviour

The function  can be reached by function gateway when  the function is scaling(auto or by hand).

## Current Behaviour

The function  can not be reached  from the OpenFaaS gateway when the function is scaling (auto or by hand).

## Possible Solution

keep the function data until the scaling finish

## Steps to Reproduce (for bugs)

1. set up a Open-faas environment in the Play with Docker (or use local VM servers)
2.  Use JMere do a stress test or  some CMD url tools trigger a function into auto-scaling (or scaling the function by hand) 
3.  Check  the error responses from the tools  when the function is scaling
4.  Look at the OpenFaaS Portal  UI , you will see the function up and down in the function list at the same time.

## Context

This issue affects  the performance of Open-faas system.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

[rancher@rancher-T2 ~]$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

  I try on Docker Swarm and Rancher Cattle  

* Operating System and version (e.g. Linux, Windows, MacOS):

server : Linux : rancher OS

client : MAC OS

* Link to your project or a code example to reproduce issue:

use a sample function   ---  emilevauge/whoamI

https://hub.docker.com/r/emilevauge/whoami/

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Please attach your test plan from jMeter. Do you have a healthcheck built into your function when running on Swarm?

**Comment by alexellis** [comment]
@chaim1986

**Comment by alexellis** [comment]
Derek close: I believe this to be resolved - a health check is always needed in Swarm
