### ISSUE TITLE
Document: fine-tuning async with NATS Streaming

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#408]
The asynchronous guide needs updating to cover new configuration flags for NATS Streamining:

There are two important environmental variables:

```
max_inflight: 1
ack_timeout: 30s
```

Due to the way NATS Streamining does re-deliveries all messages must be acknowledged (completed) within a certain timeframe which means each message must complete in ack_timeout / max_inflight seconds.

If you have a long running function that takes over 30s you must extend the value for ack_timeout.

If you want to multi-process then scale the queue_worker service.

Example of when we see redelivery:

You have a function that sleeps for 5 seconds https://github.com/alexellis/sleepy/blob/master/stack.yml then send 10 requests. They must all (5 x 10 = 50 seconds) complete within the window of ack_timeout /  work_inflight  which is (30 / 10 = 3 seconds) - this will result in the last few requests being acked outside the window and therefore will get redelivered. 

Pinging @ericstoekl @stefanprodan

**Comment by developius** [comment]
Awesome to finally know why this was happening - good job @alexellis!

**Comment by alexellis** [comment]
Yes it's great to have this documented. It does mean we have to know what our max time / duration is for a piece of work. We should also probably swallow / ack any task that gets redelivered so we don't get into a loop. Here's the scenario:

* Max ack time is 30 secs
* Max in-flight is 1
* User creates task that takes 40 seconds
* Results in redelivery message until it takes less than 30 seconds thus causing a loop.. we can break that with an exit condition of if redelivered then ignore it.

Btw I could use help with putting that change in and testing it.

cc/ @petemiron

**Comment by ericstoekl** [comment]
@alexellis I would like to work on this item. To clarify, we need the following:

1. Timeout instead of redeliver if `ack_wait` expired.
2. Tests to validate
3. Detailed guide on these env variables and their usage.

Let me know if this is OK.

Thanks,
Eric

**Comment by alexellis** [comment]
Not sure. I think this is ready now and I'll move the issue description into the docs.

Speaking of docs.. John's PR for docs is looking abandoned. Could you try it out and find out how long the docs build takes? Maybe we can launch it next week if it looks good.

**Comment by ericstoekl** [comment]
Regarding the docs PR -- sure, I'll take a look at that.

**Comment by alexellis** [comment]
Derek close
