### ISSUE TITLE
K8S Deployment Guide References Missing Sample Functions

### ISSUE THREAD

**Issue by blachniet** [openfaas/faas#410]
## Expected Behaviour

I'd like to be able to easily set up a sample openfaas deployment by following the walkthroughs.

## Current Behaviour

The [Use OpenFaaS](https://github.com/openfaas/faas/blob/master/guide/deployment_k8s.md#30-use-openfaas) section in the [Deployment guide for Kubernetes](https://github.com/openfaas/faas/blob/master/guide/deployment_k8s.md) references functions that do not appear in the sample it instructs the user to use.

It instructs the user to use the samples in [faas-cli/samples.yml](https://github.com/openfaas/faas-cli/blob/master/samples.yml), and instructs the user to invoke the `stronghash` function. However, that samples file does not define a `stronghash` function.

## Possible Solution

Update [Deployment guide for Kubernetes](https://github.com/openfaas/faas/blob/master/guide/deployment_k8s.md) to reference functions in the sample that it instructs the user to use.

## Steps to Reproduce (for bugs)

n/a

## Context

n/a

## Your Environment

* minikube v0.23.0
* faas-cli v0.5.0

**Comment by alexellis** [comment]
Hi @blachniet thanks for trying OpenFaaS - it looks like we changed the samples. I've added that one back in: https://github.com/openfaas/faas-cli/commit/44c51d4ecaae25cb22bf3fca978c78b03382d714

You might prefer to make use of the new Function Store too (available if you update to 0.6.13). https://blog.alexellis.io/announcing-function-store/

**Comment by alexellis** [comment]
Derek close
