### ISSUE TITLE
Help wanted: Implement basic regression test through DIND

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#42]
DIND Docker in Docker can be used to deploy FaaS, run some basic tests and get a confidence level RE: PRs/changes.

Initial version of this would deploy built-in stack and test echo function for example.

Help wanted on this (re: time)

**Comment by ems5311** [comment]
Instead of using DIND, would it be feasible to mount the docker socket as a volume in a docker container, so that instead of deploying FaaS inside of docker, we deploy it on our host, but controlled by a single docker container? I ran into this section of the [`docker run` documentation](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only):

> `$ docker run -t -i -v /var/run/docker.sock:/var/run/docker.sock -v /path/to/static-docker-binary:/usr/bin/docker busybox sh`
> 
> By bind-mounting the docker unix socket and statically linked docker binary (refer to get the linux binary), you give the container the full access to create and manipulate the host’s Docker daemon.

**Comment by alexellis** [comment]
A core use-case is multi-node clustering which is not possible by mounting a container.

**Comment by alexellis** [comment]
Closing due to lack of interest.

**Comment by scher200** [comment]
If just only we wanted this, still I thought it would be worth posting:
[https://github.com/scher200/dosd](https://github.com/scher200/dosd)
It gives you openfaas in a dind container, please try it:
```
docker run -d --name swarm -p 8080:8080 --privileged scher200/dosd
```

**Comment by alexellis** [comment]
Looks interesting. Have you run the tests from certify-incubator repo inside? Could be a good thing to try next

**Comment by scher200** [comment]
```
# make test                                             
gateway_url=http://0.0.0.0:8081/ go test ./tests -v
=== RUN   Test_Deploy_Stronghash
--- PASS: Test_Deploy_Stronghash (0.01s)
=== RUN   Test_InvokeNotFound
--- PASS: Test_InvokeNotFound (0.00s)
	deploy_test.go:106: [1/30] Correct response: 404
=== RUN   Test_Deploy_PassingCustomEnvVars
--- PASS: Test_Deploy_PassingCustomEnvVars (10.16s)
	deploy_test.go:97: [1/30] Bad response want: [200], got: 500
	deploy_test.go:98: http://0.0.0.0:8081/function/env-test
	deploy_test.go:97: [2/30] Bad response want: [200], got: 500
	deploy_test.go:98: http://0.0.0.0:8081/function/env-test
	deploy_test.go:97: [3/30] Bad response want: [200], got: 500
	deploy_test.go:98: http://0.0.0.0:8081/function/env-test
	deploy_test.go:97: [4/30] Bad response want: [200], got: 500
	deploy_test.go:98: http://0.0.0.0:8081/function/env-test
	deploy_test.go:97: [5/30] Bad response want: [200], got: 500
	deploy_test.go:98: http://0.0.0.0:8081/function/env-test
	deploy_test.go:106: [6/30] Correct response: 200
PASS
ok  	_/home/administrator/Git/openfaas/certify-incubator/tests	10.177s
```

**Comment by scher200** [comment]
do you mabe have a certify-incubator container, that i can use to setup a dockerized test?
