### ISSUE TITLE
nginx sample file not working

### ISSUE THREAD

**Issue by tkiraly** [openfaas/faas#421]
hi

in https://github.com/openfaas/faas/blob/master/contrib/nginx/gateway.conf the proxy_pass values are end with a slash. Because of this nginx appends the location string. if no slash there, then no append happens.

## Expected Behaviour

no append happen

## Current Behaviour

append happen and behind nginx /ui is not working aka not finds any function (system/functions endpoint is 404 not found)

## Possible Solution

remove the slashes from the end
## Steps to Reproduce (for bugs)

1. start docker swarm with nginx in front of the api gateway 
2. when http://<ip>/ui loads in the browser console en error throws every second: /system/functions not found

## Context

i tried to provide basic auth for api gateway (:8080) and prometheus (:9090) endpoints
## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
no
* Operating System and version (e.g. Linux, Windows, MacOS):
linux
* Link to your project or a code example to reproduce issue:
now it is broken, the fix is to remove slashes and the intended behavior is come into play

**Comment by alexellis** [comment]
What isn't working? Lots of us are using this config including me

**Comment by tkiraly** [comment]
i'm sorry, it was something on my side!

**Comment by alexellis** [comment]
No worries. Let us know if you need help with anything
