### ISSUE TITLE
How to set circuit breaker mechanism 

### ISSUE THREAD

**Issue by mjafarpour** [openfaas/faas#425]
Hi,
How can use circuit breaker mechanism? For example set the rate limit for fuction links to call.

**Comment by austinfrey** [comment]
hey @mjafarpour, at the moment, rate limiting would be done using an api gateway layer on top of OpenFaaS. Something like Kong or Nginx can be placed in front of OpenFaaS to provide those features.

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by alexellis** [comment]
If you follow our guide for Kong you can set up everything you need there. Thank you for using OpenFaaS. I'll close the issue and feel free to keep commenting. https://github.com/openfaas/faas/blob/master/guide/kong_integration.md

**Comment by mjafarpour** [comment]
Thanks for your attention. I checked the nginx samples. I don't have any experience with kong. but if you recommend the kong, i'll use it.
