### ISSUE TITLE
Suggestion: Allow functions to use multiple networks [Swarm]

### ISSUE THREAD

**Issue by diddledan** [openfaas/faas#428]
Faas-cli can only deploy a function into a single Docker network. The default for this is `func_functions`. I am proposing allowing multiple networks to be specified on the command-line when deploying a function to enable a function to access services which are logically separated such as for policy reasons.

## Expected Behaviour
When deploying a function I should be able to specify multiple networks for the function to have access to, which is propagated to the containers holding the function in Docker Swarm.

## Current Behaviour
Currently I can only specify a single network when deploying my function with faas-cli and, as I'm using traefik, I am required to use a shared network to allow traefik to route to the function but placing es, traefik, and my function in the same network will allow traefik and potentially external users direct access the es system.

## Possible Solution
Either modify the faas-cli `--network` option to allow multiple networks to be specified, or add an additional flag to specify additional networks.

## Context
I currently have an Elasticsearch service deployed within a network called `elasticsearch`. This isolates it logically allowing for restriction of which containers can access it. I would like the ability to deploy a function which resides in the `elasticsearch` network, but also in the `func_functions` network. The reason I still need it in `func_functions` is because my `traefik` service cannot route to the function without being in the same network or the function has ports exposed on it's host. I do not want to expose the Elasticsearch service and network to traefik, and I don't want to publish ports for this specific function as that will allow direct access bypassing the traefik system.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```plain
Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   02c1d87
 Built:        Thu Oct 26 06:34:46 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu Linux 16.04

**Comment by alexellis** [comment]
Derek add label: swarm

**Comment by alexellis** [comment]
Derek close: lack of interest

**Comment by flyhigh-hifi** [comment]
Should be implemented, for swarm mode it's critical feature.

**Comment by alexellis** [comment]
Hi thanks for your interest in the project. Given that we are now two and a half years in with dozens of production users so I'm not sure how this is a critical feature. Having said that I would still be interested in hearing more from you if you want to raise our own issue and show us how this is critical for your own business.

**Comment by alexellis** [comment]
Derek lock
