### ISSUE TITLE
Proposal: Add support for ARM images in function store

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#429]
## Expected Behaviour
When a user uses the UI their experience should be the same on all supported platforms.

## Current Behaviour
User is presented with a store on x86_64.  The gateway on `arm` does not yet include the store functionality.

## Possible Solution
To avoid duplication in the JSON where functions are available across multiple HW architectures, add an additional attribute to the function definition in the store.  Suggest this can be `images` with the current `image` being deprecated once sufficient time has passed.

```
    "images" : {
                "x86_64": "functions/nodeinfo",
                "armhf": "rgee0/nodeinfo:latest-armhf"
    },
```

At the gateway build time either push `uname -m` into an angular variable, or since each hw platform has its own `Dockerfile` apply a known string such as `x86_64`, `armhf` & `arm64` which will enable the front end code to filter the incoming Store JSON to functions appropriate to the hw the gateway is running on.

## Context
Attempting to achieve consistency across the supported hardware architectures.

**Comment by alexellis** [comment]
@kenfdev @ericstoekl can we get your thoughts on this proposal?

**Comment by kfukuyama** [comment]
Sorry if this is a noob question but isn't a cluster able to have both architectures and deploy to a specific architecture using constrains? Was thinking if the UI should show architectures as an option  .
If we don't need to think about that situation, I think @rgee0 's proposal is good 👍

**Comment by rgee0** [comment]
Is that how the function store currently works?

If I have a gateway running on x86 backed by arm worker nodes what happens when I try to deploy from the function store?

**Comment by kenfdev** [comment]
@rgee0 The function store is only calling a ajax which is the same as the one used by "manually deploy". So it has to know which image to use if there are multiple definitions like your proposal above. 

> At the gateway build time either push uname -m into an angular variable, or since each hw platform has its own Dockerfile apply a known string such as x86_64, armhf & arm64 which will enable the front end code to filter the incoming Store JSON to functions appropriate to the hw the gateway is running on.

So applying ^this part is going to do the trick. The JS could read the variable at runtime. 

What I was concerned was if we need to be able to deploy to both architectures if there _are_ both in the cluster. The gateway is only hitting the orchestrator's API so I thought there would be a possibility that both `arm` and `x86_64` nodes would be inside the cluster. I'm not sure and think this is a edge case for now, so would like to here opinions about it.

**Comment by rgee0** [comment]
I understand your concern.  It’s how that concern has been addressed in the initial implementation that I’m interested in. Sounds like it hasn’t? So it’s already a potential problem.

We should probably place this on hold and raise an issue against the current implementation in mixed architecture deployments.

It’s a shame as I’ve a working prototype that filters based on gateway architecture, which may be of little use once this new issue is resolved.

**Comment by alexellis** [comment]
Looks like we need more design / discussion around this. Please can you guys summarise where you are now?

**Comment by alexellis** [comment]
@rgee0 why is the proposal closed?

**Comment by rgee0** [comment]
I closed it because the right course of action would seem to be re-evaluate once the function store implementation has had more thought / design as per @kenfdev's concern.

**Comment by alexellis** [comment]
That should be done on this issue.

**Comment by rgee0** [comment]
On the basis that the initial implementation had no supporting issue, nor a design / discussion so this is the only place for it?

**Comment by dvdmuckle** [comment]
Now that the function store has been merged, I believe this issue should be reopened.
