### ISSUE TITLE
Functions deployed from store are not getting environment set

### ISSUE THREAD

**Issue by ChrisCGH** [openfaas/faas#431]
When I deploy a function from the function store which has environment values specified in store.json, the container that is run does not have the environment values set.

## Expected Behaviour
For example, the inception function should have read_timeout and write_timeout set

## Current Behaviour
After deploying inception from the function store:
$ docker ps | grep inception
9643e58ecd3d        alexellis/inception:latest         "fwatchdog"              About a minute ago   Up 20 seconds           6006/tcp, 8888/tcp   inception.1.o3mtinvjtoiaatj3wvcm8ijil
$ docker exec -it 9643e58ecd3d sh
# env
HOSTNAME=9643e58ecd3d
fprocess=python3 index.py
HOME=/root
TF_CPP_MIN_LOG_LEVEL=3
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/root
# 

## Steps to Reproduce (for bugs)
As above

## Context
I want to be able to set environment values in store.json

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
docker-ce-17.09.0.ce-1.fc26.x86_64

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Fedora 26

* Link to your project or a code example to reproduce issue:

**Comment by ChrisCGH** [comment]
Maybe this bit of bootstrap.js needs to be updated to send the environment values (func.environment?):
`            $scope.onFuncSelected = function(func) {
                $scope.item.image = func.image;
                $scope.item.service = func.name;
                $scope.item.envProcess = func.fprocess;
                $scope.item.network = func.network;
                $scope.selectedFunc = func;
            }
`

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
Hi @ChrisCGH , thanks for your suggestion. Last I heard we are still deciding what to do with environmental variables with regards to the function store. The reason that this is slightly more complicated is because the `read_timeout` and `write_timeout` will need to be set at the gateway level as well for the function to work with increased timeouts. @alexellis, correct me if I'm wrong here.

**Comment by ChrisCGH** [comment]
Hi Eric, it's true that the gateway timeouts need to be increased too, but at least that's something that I can control when I deploy faas. How about making the gateway timeout dynamic, by allowing them to be specified in the create function request, and adding some protection by specifying hard limits when deploying the gateway?

**Comment by alexellis** [comment]
As I suspected the code is not merged yet, but the store is ready i.e. the timeouts are set in the definitions. Please re-test after we merge the changes here: https://github.com/openfaas/faas/pull/424

**Comment by ChrisCGH** [comment]
Thanks Alex, will do

**Comment by alexellis** [comment]
Closed as this feature is not released.
