### ISSUE TITLE
Question: can I skip pushing images when using minikube?

### ISSUE THREAD

**Issue by kylos101** [openfaas/faas#436]
Hi, OpenFaaS looks awesome (I've watched a couple videos and read a few blog posts)! I apologize in advance if I've missed something...

## Expected Behaviour
Have the ability to deploy functions' images in Minikube w/o publishing to a remote docker registry and running "docker login". 

## Current Behaviour
Images built with faas-cli cannot be pulled from my local docker registry (the desired image is listed in the output of "docker images").

Is it required to publish an image to a docker registry and "docker login" prior to running "faas-cli deploy" when developing on Minikube? [This hints that publishing and logging in are required.](https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf)

The order of operations I took was:
1. faas-cli build
2. faas-cli deploy

I plan to try pushing to a remote registry and "docker login" later today, but wanted to get a head start. 

## Possible Solution
Modify faas-cli so that Kubernetes doesn't ignore my local docker registry. I'm not sure why my local docker registry is being ignored, otherwise I would get more detailed here. :-)

## Steps to Reproduce (for bugs)
1. From a Minikube cluster with OpenFaaS installed
2. Scaffold a new function with faas-cli
3. Use faas-cli to build the function
4. Use faas-cli to deploy the function (w/o pushing the image to a docker registry or running "docker login")
5. The deployment, pod, and replica set should fail saying they cannot pull the image due to access or it doesn't exist

## Context
I'm unable to author my first function; I install sample functions, though.

## Your Environment
- [ ] I will add my docker version when I get home.
I am using Minikube 0.24.1.
I am using Windows 10.
My code is not online, but I can post a sample later, if it is needed.

**Comment by alexellis** [comment]
Derek add label: question

**Comment by alexellis** [comment]
If you use Docker Swarm then your library is shared between OpenFaaS automatically and you have no need to push. When using `minikube` you need to push to an intermediary registry or build directly into the Docker version running in minikube.

* Running a local registry on minikube:

https://github.com/kubernetes/minikube/blob/master/docs/addons.md

Or Google it

* Use minikube's Docker version and library

```
minikube docker-env
```

The issue with building directly into minikube is that they use a super-old Docker version so old it doesn't even do multi-stage builds. So you need to run a registry container (blisteringly fast anyway), wait until minikube upgrade their Docker version or push to a public registry.
```

**Comment by alexellis** [comment]
@kylos101 please feel free to keep commenting on this issue.

**Comment by kylos101** [comment]
@alexellis will do, thank you very much for the detailed response, and rephrasing this issue (I was struggling with phrasing).

I am currently building my images into minikube, but I'm not running a registry container, so I'm going to try that first. More updates to follow - probably in a few hours.

**Comment by alexellis** [comment]
Docker for Mac/Windows + Kubernetes will be even more interesting too since I think it will give both a recent version of Docker and a local Kubernetes environment.

**Comment by kylos101** [comment]
Hi there, I got the registry running following [this](https://github.com/kubernetes/minikube/blob/master/docs/addons.md) and [this](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry), and just need to figure out how to build and publish to it. 

More updates later tonight (hopefully). Thanks again!

**Comment by kylos101** [comment]
Setup the registry today in a k8s pod, just need to figure out how to
publish to it.

Some homework for tonight.

**Comment by kylos101** [comment]
Hi @alexellis, I'm such a doofus. I should have provided more context in my initial post.

To recap, I was trying to figure out why my minikube kubernetes instance was having trouble pulling images for OpenFaaS.

What I failed to mention, is that I have no problems using images in kubernetes that are local to my machine:
kubectl create -f some/deployment.yaml

I just found that this is ideal when working with Minikube:
"imagePullPolicy": "IfNotPresent" 

When deployments are created for OpenFaaS, they have this set in the deployment
"imagePullPolicy": "Always"

I changed it to "IfNotPresent" and everything works like a champ now - no private registry required, I can build right into Minikube.

Thanks a lot for your guidance! Onto OpenFaaS!!!

**Comment by hypnoglow** [comment]
Upvote for this. Since "ImagePullPolicy" defaults to "Always" and cannot be changed (without `kubectl edit`), the registry cannot be eliminated from the workflow. But for minikube it is much more convenient to push your images directly to its docker and not to use a redundant registry.

**Comment by alexellis** [comment]
PullAlways is needed for rolling updates. 

You should be able to build directly to the minikube library by using minikube environmental variables.

**Comment by hypnoglow** [comment]
> PullAlways is needed for rolling updates.

What do you mean? Rolling update is provided by updating image tag, isn't it?

> You should be able to build directly to the minikube library by using minikube environmental variables.

Again, what do you mean? Are you talking about registry plugin?

**Comment by alexellis** [comment]
https://kubernetes.io/docs/getting-started-guides/minikube/#reusing-the-docker-daemon

I'll try to update the documentation to make it clearer how to use a registry for local development or Minikube's library directly. Thanks for commenting.

**Comment by alexellis** [comment]
Derek lock: not an issue
