### ISSUE TITLE
Support metrics servers other than Prometheus

### ISSUE THREAD

**Issue by nicholasjackson** [openfaas/faas#441]
OpenFaaS should support other metrics collection and aggregation services other than Prometheus.  For example DataDog or NewRelic or Circonius are excellent SaaS based metrics platforms.

## Expected Behaviour
Prometheus metrics should be enabled by default however it should be possible to override with another provider.

## Current Behaviour
All metrics are passed to Prometheus

## Possible Solution
Implement pluggable metrics and refactor the code to depend on an interface.

## Context
Many companies do not use Prometheus for logging metrics and only having this capability limits real-world deployability.

**Comment by alexellis** [comment]
Please see comment: https://github.com/openfaas/faas/pull/442#issuecomment-374289765
