### ISSUE TITLE
Question about Traefik setup error on AWS

### ISSUE THREAD

**Issue by akeshavan** [openfaas/faas#449]
Thanks for this awesome software! I was able to deploy this on AWS very easily, except for getting SSL set up. 

## Expected Behaviour

I'm following the Traefik integration instructions to deploy faas on my EC2 micro instance on AWS, and I'm not able to get SSL to work. 

## Current Behaviour

The `docker service logs func_traefik` output shows the error 

`"Error creating TLS config: Unknown entrypoint  for ACME configuration" `

and 

`"Error preparing server: Unknown entrypoint  for ACME configuration" `

The full output is on a gist here: https://gist.github.com/akeshavan/aa62d195ce36630e07f77aae86599be7#file-docker_service_logs_traefik

## Steps to Reproduce (for bugs)

1. Create a t2.micro AWS ubuntu instance
2. Follow the instructions to deploy faas
3. Follow the [traefik instructions](https://github.com/openfaas/faas/blob/master/guide/traefik_integration.md), or use my `docker-compose.yml` file here https://gist.github.com/akeshavan/aa62d195ce36630e07f77aae86599be7#file-docker-compose-yml (replacing the password, domain, and email according to the instructions)
4. `./deploy_stack.sh`
5. `docker service logs func_traefik` will show the errors

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```$ docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04 xenial
* Link to your project or a code example to reproduce issue:

Here is a gist with my docker-compose.yml file and the output for `docker service logs func_traefik` https://gist.github.com/akeshavan/aa62d195ce36630e07f77aae86599be7

Thanks!

**Comment by alexellis** [comment]
Thank you for using OpenFaaS. This is probably not going to be an issue with our project itself - I can ping the author of this guide but you may need to seek help with the Traefik community. @austinfrey 

The guide does need customisations - so please make sure you've done that too. I don't think it's just a case of copy/paste.

**Comment by akeshavan** [comment]
Thanks! I did the customizations, but removed them from my gist to keep things private. I'll continue hacking away at it.

**Comment by alexellis** [comment]
Let's see how you get on. Kong and Nginx also work really well.

**Comment by akeshavan** [comment]
Ha! Even though Kong's directions were longer, it was very simple. This is great!

**Comment by akeshavan** [comment]
Ok, I think Traefik isn't working because LetsEncrypt doesn't work for an EC2 domain. The error message must be buried somewhere. Since the Kong SSL directions are for a self-signed certificate, it works. If using Traefik w/ EC2, make sure you have a domain name first.

**Comment by alexellis** [comment]
Really glad you got to the bottom of this. It'd be great if you could submit a brief PR to the guide along these lines?

I also wanted to invite you to join our Slack community. It'd be great to speak to you more. Just email alex@openfaas.com - hope to speak soon. 

Alex
