### ISSUE TITLE
Help wanted: Blog post about using OpenFaaS with AKS

### ISSUE THREAD

**Issue by rorpage** [openfaas/faas#450]
Write a blog post about Azure Container Services with Kubernetes (https://docs.microsoft.com/en-us/azure/aks/)

**Comment by rorpage** [comment]
Derek add label proposal

**Comment by rorpage** [comment]
Derek add label: proposal

**Comment by rorpage** [comment]
Derek assign: me

**Comment by squillace** [comment]
Hey, speaking for Azure I'd love to help out here. Let me follow up. FWIW, anyone can submit a document at https://github.com/MicrosoftDocs/azure-docs, but as the repo is GIANT I'll be glad to do the lifting here.

**Comment by rorpage** [comment]
Awesome, thanks @squillace!

**Comment by alexellis** [comment]
@squillace would be so awesome to get your help with this ⭐️

**Comment by squillace** [comment]
I'm starting to have a look at this. I'll post a doc in draft in my repo for comments over the next week.

**Comment by alexellis** [comment]
Derek close: released by @ericstoekl + @squillace
