### ISSUE TITLE
Backlog: Move Swarm code into its own provider faas-swarm

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#454]
I'm moving Docker Swarm out of the API Gateway into faas-swarm.

The reason is so that each provider follows the same model, we will end up with this for every provider:

```
API Gateway -> Provider -> Orchestrator
API Gateway -> Provider -> Function
```

Currently we have the above for providers but swarm is orthogonal:

```
API Gateway -> Orchestrator
API Gateway -> Function
```

https://github.com/openfaas/faas-swarm

It will also mean that anyone who needs to vendor the gateway gets a much leaner dependency. Most people vendor the gateway now so they can make use of the "requests" package that contains the object model for interacting with the gateway.

Another plus point here is the ability to create a Golang client package / SDK for the OpenFaaS gateway

As part of this work I'll also consider moving the "requests" models into the faas-provider library, but I don't know if this is the right thing to do yet. 

## Considerations

* Migration for existing users
* Need for new YAML files / new Docker image for faas-provider
* Stability/regression/performance testing
* We have to avoid circular dependencies which may mean breaking `master` for a time

## Todo:

- [x] Move integration tests from faas to faas-swarm

**Comment by JockDaRock** [comment]
Tested this on Mac and Play-With-Docker last night.  Seems to be working fine so far.

Would like to test out several more functions.  But this seems to be working great so far.

**Comment by alexellis** [comment]
Derek close
