### ISSUE TITLE
Use #!/bin/sh rather than #!/bin/bash for compatibility with other shell environments

### ISSUE THREAD

**Issue by willhallonline** [openfaas/faas#455]
We should use #!/bin/sh rather than #!/bin/bash for greater compatibility with other shell environments. Generally speaking #!/bin/sh will be more operable within different environments.

## Possible Solution
Replace #!/bin/bash with #!/bin/sh except in situations where bash is **required**. Which I can't see in the current *.sh files.

## Context
Generally, I have been running a whole bunch of the codebase through various linters and my general expecations when accepting code is that is is #!/bin/sh is that it uses that rather than bash. I have seen mixed versions throughout the codebase.

**Comment by alexellis** [comment]
Thanks Will.
