### ISSUE TITLE
Watchdog docs: marshal_requests should be marshal_request

### ISSUE THREAD

**Issue by nozzlegear** [openfaas/faas#461]
Bumped into this just now trying to get the watchdog to marshal my requests to JSON. The watchdog docs tell you to use `marshal_requests` env var, [but the `Read` function is looking for `marshal_request`](https://github.com/openfaas/faas/blob/6199c61178bc34a09d99a2c9a23b631c703deacc/watchdog/readconfig.go#L78). I was going to submit a pull request but since this is just a typo the contribution guide said to file an issue instead.

**Comment by BurtonR** [comment]
@nozzlegear we request that issues be opened so that we can track problems/changes easier and prevent a bunch of unsolicited PRs from popping up without warning.

Please do open a PR so we can get this corrected. Don't forget to sign your commit :)

**Comment by alexellis** [comment]
Can I ask why you want to marshal the requests? As far as I know nobody is using this and headers are already available through environment.

**Comment by nozzlegear** [comment]
@alexellis Sure! I'm using watchdog for a couple F# functions, I was marshalling the requests to see if there were some common properties that would always be passed to the function that I could then turn into a real F# type for deserializing. I'm not opposed to using the environment variables, it's just something that I would consider "weird" in a dotnet application and would rather have it passed more directly to the function. 

It looks like the watchdog doesn't pass the querystring through that marshalling though, so I'll end up using environment variables anyway.

**Comment by alexellis** [comment]
That's because it was an experimental feature which has not kept up with the default way of doing things. It can adapt and change but this type you're mentioning would be better populated by the entry point then sent into the F# handler. Look at through OpenFaaS/templates repo for inspiration. If you could join our Slack Community we can discuss more in the contributors channel. 

To join email alex@openfaas.com

**Comment by alexellis** [comment]
By all means also PR the docs / README for the typo.

**Comment by nozzlegear** [comment]
Thanks! I've already switched over to environment variables in the couple functions I've built, but I'll send a PR soon since this was confusing for me when reading the current docs.

**Comment by BurtonR** [comment]
Derek add label: documentation

**Comment by alexellis** [comment]
Changes made in README file for watchdog. Thanks for pointing out.
