### ISSUE TITLE
Proposal: Migrate all OpenFaaS projects to dep vendoring 

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas#462]
Use [dep](https://github.com/golang/dep) project wide.

## Projects

- [x] openfaas/faas
- [x] openfaas/faas-swarm
- [ ] openfaas/faas-netes
- [x] openfaas/faas-cli
- [x] openfaas/faas-provider
- [x] openfaas/nats-queue-worker
- [x] openfaas-incubator/faas-o6s

**Comment by alexellis** [comment]
We'll do the `faas` gateway with the changes in #460.

I don't think the watchdog vendors packages yet or of-watchdog.  (so we could take them off the list)

**Comment by alexellis** [comment]
@BurtonR want to test out derek here to add the label of `proposal`?

**Comment by BurtonR** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
Can we get brief instructions on how to convert the projects to use `dep` for vendoring? Something like, delete the `vendor/` directory, run `dep init`, then run `dep add` on each package that is still missing? Or is there more to it?

**Comment by stefanprodan** [comment]
@ericstoekl `dep init` should be enough but in same cases the package doesn't have a sem ver release or the release is very old. In these cases you can override the revision git sha to the Gopkg.toml, here is an [example](https://github.com/stefanprodan/faas-o6s/blob/master/Gopkg.toml#L15).

**Comment by stefanprodan** [comment]
One more thing, the `Gopkg.toml` should contain only the imported packages from your code, `dep` will add the inner dependencies to `Gopkg.lock` when you run `dep ensure`.

**Comment by alexellis** [comment]
So it's just like `vndr` - we do an `init` up front then later on do an `ensure -add` or `ensure -update` to add/maintain dependencies. I've just updated the contribution guide with a link to the dep homepage.

https://github.com/golang/dep

**Comment by dungeonmaster18** [comment]
If anyone is not working on migrating faas-cli I would like to take that.

**Comment by alexellis** [comment]
Please feel free @dungeonmaster18 - just raise the PR without the vendor folder 👍

**Comment by dungeonmaster18** [comment]
Hey @stefanprodan migration of faas-cli to dep has been merged. Please mark it done in the description of this issue.

**Comment by stefanprodan** [comment]
Done. Thanks @dungeonmaster18

**Comment by stefanprodan** [comment]
@dungeonmaster18 do you want to go for nats-queue-worker next?

**Comment by dungeonmaster18** [comment]
Yes, I will create the pr by today. Also I was going through faas-netes it also seems easy but I am not sure due to it's large dependency on k8s. Has anybody tried migrating faas-netes? @stefanprodan

**Comment by stefanprodan** [comment]
I think we will do faas-netes when porting the code for faas-o6s. I would also wait for the gateway to be merged with the new faas-swarm.

**Comment by alexellis** [comment]
Hey it doesn't hurt to do this migrating to `dep` now, but we will have to re-vendor again when #460 is complete and the gateway shrinks down to a much smaller since. #460 removes Docker swarm from the gateway.

**Comment by dungeonmaster18** [comment]
Okay I will only work on nats-queue-worker.

**Comment by dungeonmaster18** [comment]
Hey @stefanprodan mark nats-queue-worker done. Also I seen certify-incubator which also needs to move to dep. But I was thinking of keeping it for good-first-issue.

**Comment by alexellis** [comment]
Derek close: thanks to everyone who worked on this.
