### ISSUE TITLE
Help wanted with Raspberry Pi and Prometheus

### ISSUE THREAD

**Issue by mysmartbus** [openfaas/faas#465]
## Expected Behaviour
When running `docker service ps --no-trunc func_prometheus` and `docker service ps --no-trunc func_alertmanager`, the desired state is supposed to be `running`.

## Current Behaviour
Running `docker service ps --no-trunc func_prometheus` and `docker service ps --no-trunc func_alertmanager` lists both of them as `Shutdown`.

Error message given is `invalid mount config for type "bind": bind source path does not exist`.

The volumes in `docker-compose.armhf.yml` are correct and the files do exist on the host.

## Possible Solution
None identified yet.

## Steps to Reproduce (for bugs)
1. Deployed stack via `./deploy_stack.armhf.sh`.
2. Ran `docker service ls`
3. Noted that `func_alertmanager` and `func_prometheus` always showed 0/1 in the Replicas column.

## Context
Unable to tell how the faas stack is performing.

## Your Environment

My docker swarm consists of 1 Raspberry Pi 2 and 4 Raspberry Pi 3's. The Pi 2 is a manager (availability=drained), 2 of the Pi 3's are managers and the other Pi 3's are workers.

All of the Pi's are running Raspbian Jessie 8.0.

```
$ docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:53:02 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:14 2017
 OS/Arch:      linux/arm
 Experimental: false
```

```
$ faas-cli version
Commit: d1d38e9b2d5600a3485442b75641bf73b566313b
Version: 0.5.1
```

**Comment by alexellis** [comment]
Derek set title: Help wanted with Raspberry Pi and Prometheus

**Comment by alexellis** [comment]
That's a lot of managers for a cluster of 2 nodes. Try with one manager or clone the code to the same place on each manager to satisfy the mount. OpenFaaS doesn't currently use bind mounting for the regular PC version.

**Comment by mysmartbus** [comment]
> ...clone the code to the same place on each manager to satisfy the mount...

Solved the problem.

**Comment by alexellis** [comment]
Great to hear that 👍 We're making some changes to make this better for ARM too. Please get in touch if you'd like more support or to join our Slack Community.
