### ISSUE TITLE
Spelling error in faas/watchdog/README.MD

### ISSUE THREAD

**Issue by gaberger** [openfaas/faas#466]
Spelling error:  s/appliaction/application

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Thank you for this 👍
