### ISSUE TITLE
Document: use of Kubernetes secrets

### ISSUE THREAD

**Issue by rimusz** [openfaas/faas#469]
Document how to use Kubernetes secrets in functions and add it to https://github.com/openfaas/faas/blob/master/guide/README.md

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
This would be a great addition to the auto-generated documentation site.

**Comment by alexellis** [comment]
As the generated site is WIP I'd suggest adding this as a footnote to the Kubernetes deployment guide in the faas/guide folder.

**Comment by ivanayov** [comment]
This is addressed in docs: [#define-a-secret-in-kubernetes](https://docs.openfaas.com/reference/secrets/#define-a-secret-in-kubernetes)

**Comment by ivanayov** [comment]
Derek close
