### ISSUE TITLE
UI: setting environment variables in manual deployments

### ISSUE THREAD

**Issue by jrevillas** [openfaas/faas#471]
I want to add support for environment variables while deploying new functions through the UI. This operation is currently supported by API Gateway and `faas-cli`, but the UI needs to be updated in order to handle these dynamic inputs. And since this is a common task, here you have some different approaches for the same "UX challenge".

## Heroku

* Blankslate with a link to documentation and the form to add new variables. ([view](https://user-images.githubusercontent.com/6373771/34656151-f28f9298-f415-11e7-9a5c-7d33cb516204.png))
* Every change performs an AJAX call (not needed for us, but good for handling changes).
* Existing variables will be shown as read-only fields. ([view](https://user-images.githubusercontent.com/6373771/34656144-dc5fd410-f415-11e7-8391-f6f38be90b17.png))
* Edition is made through a modal where the key can't be edited.
* Deleting variables requires additional confirmation.

Note that we are currently working in a modal, so let's try to avoid new ones. You can find another approach from the new AWS Lambda console [here](https://user-images.githubusercontent.com/6373771/34656268-7823a42a-f417-11e7-848c-5d0c758a4151.png). Also, check out [this one](https://user-images.githubusercontent.com/6373771/34656269-783aeee6-f417-11e7-9295-c222ac8cdc13.png) from Portainer.

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
@alexellis I think this is a reasonable suggestion. Maybe someone like @kenfdev would like to look into it? :)

**Comment by alexellis** [comment]
Yes I agree. Javier I think is starting to mock one of the options up for us.

**Comment by alexellis** [comment]
@ovation22 @kenfdev as #TeamServerlessUI what do you think?

**Comment by Waterdrips** [comment]
/close
This is possible in the UI
