### ISSUE TITLE
Proposal: Docs for watchdog streaming mode

### ISSUE THREAD

**Issue by lzfxxx** [openfaas/faas#473]
The description of the streaming mode is only available in [https://github.com/openfaas-incubator/of-watchdog](url), but docs for how to use it with the main repo and examples are not available.

## Expected Behaviour
Expected the docs for using the watchdog in streaming mode and example code for doing the streaming with FaaS. 

Code written in python is personally preferred :P

**Comment by itscaro** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Hi @lzfxxx, please can you raise this issue in the openfaas/of-watchdog repository? The mode you are referring to is part of an incubator project which can be used in OpenFaaS but is not currently part of the main project - the main project is still using openfaas/faas/watchdog. That is the reason the documentation only exists within the of-watchdog README file.

When you open the issue please state which specific questions and queries you have over and above what is documented in the README. Thanks.

**Comment by lzfxxx** [comment]
@alexellis After reading the new documentation in openfaas/of-watchdog and some testing, i think i have no more problems about the modes of the watchdog. Thank you!

**Comment by alexellis** [comment]
Just curious - what brought you to the of-watchdog over the existing watchdog that we are using in the project now? watchdog in openfaas/faas?

**Comment by lzfxxx** [comment]
Yes, I found it in the README of watchdog in openfaas/faas. I was trying to find out the solution of openfaas on data exceed the memory.
