### ISSUE TITLE
Use cleaner image in guide/backends.md

### ISSUE THREAD

**Issue by amiryal** [openfaas/faas#475]
Suggestion: in `guide/backends.md`, use the following image instead of the one below it:
![](https://imgur.com/download/RXG4N1b)

![](https://camo.githubusercontent.com/c250e0dc975e50b6fae3fc84ba5cdc0274bc305c/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f44466837692d5a586b41415a6b77342e6a70673a6c61726765)

**Comment by alexellis** [comment]
Looks good to me. Thank you Amir.
