### ISSUE TITLE
Proposal: Form a consistent approach to common attributes for constraints and limits

### ISSUE THREAD

**Issue by nicholasjackson** [openfaas/faas#479]
The ability to restrict the placement of a function based upon attributes such as "name" or cpu architecture is a very useful feature in OpenFaaS allowing it to take advantage of multi-architecture scheduler clusters.

However all of the schedulers implement a custom naming convention for describing these  features and while they are generally based on a key/value  convention the differences between the names and values does not allow for a consistent approach for describing constraints in an OpenFaaS stack file.

This proposal sets out a normalized base set of constraints which would be interpreted by the provider and interpreted into a scheduler specific format.

## Expected Behaviour
Ability to defined constraints and limits in a manner that makes the stack file portable across all provider implementations

## Current Behaviour
Limits and Constraints are represented as a string and are dependent upon the underlying providers interpretation.

### Limits
Limits are somewhat easier with a standard unit being used across all schedulers, the main difference is the way that the unit is represented, for example k8s uses the following representation:

```yaml
  limits:
      memory: 10Mi
      cpu: 100m
```

I propose that this is changed to an integer representation in OpenFaaS with the conversation to provider specific implementation handled on a provider by provider basis.

* memory -  integer representing a number of Megabytes e.g. 1024 = 1024MB
* cpu - integer representing number of Megahertz where 1024MHz = 1 CPU

### Constraints
The initial proposed constraints are:
	• node.name [string]
	• node.os [string] (windows, linux, darwin)
	• node.arch [string] (amd64, arm7, arm6)

It would be possible to add custom constraints specific to each scheduler based on label meta data using the following syntax:
	• node.label.[name] [string] (i.e node.label.beta.kubernetes.io/instance_type)

These custom labels would not allow portability of stack files but would allow the user a common method of describing constraints.

#### Comparators:
	• = equality
	• != not equal
	• >= greater than equals
	• <= less than equals
	• < less than
	• > greater than
	• in
	• notin

Where the 

#### Examples:

```yaml
constraints:
  - "node.os = windows"
  - "node.os in [windows,linux]"
  - "node.arch != arm"
  - "node.label.beta.kubernetes.io/instance_type = t2.medium"
```

#### Implementation:
To ease the implementation of this proposal a common tokenizer would be created which would convert the constraints into the following go structs:

```go
type Constraint struct {
	Name	string
	Comparator	ConstraintComparator (enum)
	Value	ConstraintValue
}

type Value struct {
	Type	ValueType (list, string)
	List	[]string
}

// implementation of Golang Stringer interface
// lists would be converted to array notation "[a,b,c]"
func (v *Values) String() {}
```

##### Example usage:
In most instances the user would be able to use the value like so:

```go
myconstraint.Value.String() // return value from constraint 
```

However in the instance that a list is passed the following method could be applied
```go
for _,v := range myconstraint.Value.List {
	// v is a string
}
```

## Context
Create standard interface for limits and constraints with the interpretation delegated to a provider implementation

**Comment by alexellis** [comment]
Thanks for writing this up Nic. Having a consistent experience is going to be beneficial in the long run - we just need to check what the "cost" of that would be. (For instance the Kubernetes parsing code is huge.)

I'd like to make sure we have limits and constraints fully working, finished and tested in Swarm and Kubernetes before working on this.

**Comment by nicholasjackson** [comment]
Currently there is no implementation for Nomad which I need to build so I can filter functions for CPU arch. I am happy to make a first pass on this and create an example tokenizer, using this example for a test bed.  If the implementation looks good and once existing Swarm and K8s is settled I am happy to help out with the other schedulers.  

Also happy to use the Nomad implementation a working prototype, even if this means complete code rework on my part.

**Comment by alexellis** [comment]
> I propose that this is changed to an integer representation in OpenFaaS with the conversation to provider specific implementation handled on a provider by provider basis.

What if we could support both?

**Comment by rgee0** [comment]
Derek set title: Proposal: Form a consistent approach to common attributes for constraints and limits

**Comment by rgee0** [comment]
Derek add label: Proposal

**Comment by nicholasjackson** [comment]
I am not against the k8s format, however if it is adopted I would suggest it is the only format, I think specific attributes per scheduler is a little confusing.  The adaption for native format could be dealt with by the provider.

For example, Swarm uses Nano cpus, Nomad and K8s use mili cpu however in k8s you can also specify decimal instances of a CPU.  I think the later example even confuses many K8s users and I think it is clearer and simpler to just choose one option.

My personal preference would just be to use whatever the most common case would be and gives the best user experience with simplest implementation.  I am also not convinced the notation used in the K8s units is the clearest.  Representing 100MB which is a commonly understood format as 100Mi representing (MiB or Mebibyte) is not the clearest representation in my humble opinion.

That said I don't really mind as long as it is a consistent approach

**Comment by alexellis** [comment]
+1

This is a good idea. If it can be done with a minimal package it would be great.

**Comment by 486** [comment]
Hey there, I am currently looking at OpenFaaS and stumbled over this during my evaluation.

- Are there any updates on this topic?
- Is there any ongoing work on the broader topic of provider abstraction? E.g. I saw that I cannot create secrets via OpenFaaS, I need to use the underlying orchestrator.
- On the topic of common vs provider-specific configuration, maybe it makes sense to pass through larger provider-specific configs to the provider. E.g. with k8s there‘s a bazillion options in a deployment / container spec, and the provider will always be behind on that. Instead, a `kubernetes.deployment.spec` field could be handled by the provider to add any k8s parameters possible.

**Comment by alexellis** [comment]
Hi @486,

> Are there any updates on this topic?

You will need to be much more specific. What is your own usecase? What are your needs? Are you using Kubernetes?

> Is there any ongoing work on the broader topic of provider abstraction? E.g. I saw that I cannot create secrets via OpenFaaS, I need to use the underlying orchestrator.

You are wrong about this, you can create secrets using the API and CLI.

> On the topic of common vs provider-specific configuration, maybe it makes sense to pass through larger provider-specific configs

Thank you for your suggestion. There is an issue in the CLI which you may want to check out. 

Alex

**Comment by 486** [comment]
@alexellis Thanks for the quick response!

> What is your own usecase? What are your needs? Are you using Kubernetes?

I am studying how provider-agnostic OpenFaaS is currently. So I am looking out for places where the underlying Swarm / k8s leaks through. Yes, we are mostly using Kubernetes now but that might change, that‘s why we are looking for something portable. Common attributes working with the same units is relevant for that.

> You are wrong about this, you can create secrets using the API and CLI.

Thanks for pointing it out, I guess I read some outdated documentation.

> There is an issue in the CLI which you may want to check out.

You mean this one https://github.com/openfaas/faas-cli/issues/623 ? It is somehow related, but only about a specific topic (tolerations). I would go further and add a feature to arbitrarily change the provider-specific deployment config before it is applied, so that it could cover anything from affinity to security policies etc.

**Comment by alexellis** [comment]
Whilst I would like to see this implemented, there has been no community interest in developing this feature for well over a year so I'm going to close it.

**Comment by alexellis** [comment]
OpenFaaS is agnostic and has a faas-provider interface that anyone can implement in a short period of time. 

The interface covers crud for functions/services, secrets, scaling and logs.

**Comment by alexellis** [comment]
@486 I would encourage you to engage with the community via Slack, rather than doing detective/guess-work. I'd rather you got correct answers and help with your usecase.
