### ISSUE TITLE
Function Store - bubble up errors.

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#481]
## Expected Behaviour

If an error occurs while trying to deploy a function from the Function Store, the manual page should be focused upon detection/display of the error.

<img width="1121" alt="screen shot 2018-01-13 at 17 23 47" src="https://user-images.githubusercontent.com/6358735/34908382-af9b9f8e-f886-11e7-8c8e-cb99ca91f018.png">

## Current Behaviour

You get no feedback and have to work out to click on the "manual" tab

<img width="1122" alt="screen shot 2018-01-13 at 17 23 54" src="https://user-images.githubusercontent.com/6358735/34908383-b3e7fc90-f886-11e7-94b8-54c8b20bf7b6.png">

## Possible Solution

Possible solution is to ask @kenfdev or @LucasRoesler very nicely to help 🥇 

## Steps to Reproduce (for bugs)

1. Deploy a function from the store
2. Deploy the same function from the store after

## Your Environment

Tested on faas-swarm - same difference on other orchestrators.

**Comment by dungeonmaster18** [comment]
I would like to add another suggestion to this i.e why don't we just disable the function if it's already deployed. By disable I mean either it shouldn't be there in store once deployed or deploy button should be disabled(non clickable). Please your thoughts on this.

cc / @alexellis @kenfdev @LucasRoesler

**Comment by alexellis** [comment]
We have to switch if there is an error deploying so that is going to be needed whatever we do. The current experience leaves the user confused.

**Comment by dungeonmaster18** [comment]
True. But I was thinking of adding a filter inside a store that filters already imported function from the store functions. if we add this then we no longer worry about user trying to deploy same function twice. then too we have to refactor error msg to make it more user friendly in the manual tab.

**Comment by LucasRoesler** [comment]
@dungeonmaster18  Is there no option to customize a function from the store, e.g. env variables? what about versions in the store? Not sure we want to actually prevent duplicate deploys unless they are exactly the same function with the same config.

**Comment by alexellis** [comment]
Would either of you be able to do the UI work to focus the error message if it's produced by the UI pop-up?

**Comment by kenfdev** [comment]
Switching to the manual tab on deployment error?
With an error toastr (or was there already a toastr)
I agree with Lucas that we should be able to deploy multiple functions with different names and versions.
Let me see if I could quickly prototype it.

**Comment by ericstoekl** [comment]
Derek add label: skill/beginner

**Comment by kenfdev** [comment]
![store_deploy_error](https://user-images.githubusercontent.com/3941889/35483615-cef66f64-0487-11e8-947c-62bfc11a2b7d.gif)

Here's a quick fix. Added "Error" toastr and made it switch to the manual tab.
Personal thoughts is that showing 2 effects (toastr and moving the tab) sort of blurs whats happening. Perhaps just showing a toastr like "Error. Check the manual tab for any errors." may be better. (But may also be obscure for people who don't understand the manual tab is actually being filled in the background)

**Comment by dungeonmaster18** [comment]
Nice @kenfdev +1

**Comment by alexellis** [comment]
I like the version you have in the gif @kenfdev - I think it's better than current but agree for the future we could revisit the UX and tune it even more.

Let's go ahead with the version as per the gif if you have time in the next week or two?

**Comment by alexellis** [comment]
Derek add label: area/ux

**Comment by alexellis** [comment]
@kenfdev I would like to see this implemented as the current experience is super confusing without being able to see the error. Do you think you can push the PR for this change?

**Comment by kenfdev** [comment]
Sorry for the delay. I've applied the improvement.

**Comment by kenfdev** [comment]
Derek close
