### ISSUE TITLE
Idea: Browse Function Store outside of OpenFaaS UI

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#484]
Someone on Twitter suggested browsing the functions in the store while outside of OpenFaaS.

Possible solution:

Generate something for GitHub pages from our JSON file.

**Comment by rorpage** [comment]
See also [#13](https://github.com/openfaas/store/issues/13) in the `store` repo

**Comment by Jeff-Lowrey** [comment]
I realize this is pretty stale, but I might like to work on it.

Was there a reason that either of the solutions mentioned in https://github.com/openfaas/store/issues/13 (from @itscaro and @hkd987 ) weren't adopted?

They both look pretty good.

Is this enhancement looking to generate static MD (rebuilt/refreshed on demand), or a dynamic solution?
