### ISSUE TITLE
Proposal: Add try with PWD button in the readme.

### ISSUE THREAD

**Issue by dungeonmaster18** [openfaas/faas#485]
**Description** :

So the idea behind this is making the testing of openfaas by new users simple, so that we can draw more people to openfaas and make their first step simple.

Also if things goes well we can also have this on the openfaas website and docs site(WIP) in the near future.

I would love to have a discussion on this.

Cc / @alexellis

**Comment by alexellis** [comment]
Derek add label: proposal
