### ISSUE TITLE
Question: can functions be updated by deploying again?

### ISSUE THREAD

**Issue by dayuoba** [openfaas/faas#488]
when i change the handler.js, then build, push, deploy. invoke it, the previous func was invoked.i don't know if miss something
## Expected Behaviour
i think when i modify codes,rebuild and deploy it, it should be updated by faas-server

**Comment by itscaro** [comment]
what do you choose for `image:` in `stack.yml`?

**Comment by alexellis** [comment]
@dayuoba yes your function will be updated when you deploy a second time providing you have re-built it and re-pushed it and re-deployed it.

Please can you fill out the whole issue template which we provide for your benefit and ours.

**Comment by itscaro** [comment]
@dayuoba Could you try the following command?
````
faas-cli deploy --replace --update=false -f stack.yml
```

@alexellis I have issue with rolling-update, since the spec is the same, image name is plain without hash, `docker service update` does not update.

**Comment by alexellis** [comment]
What is strange is that I can't reproduce this. Is there a specific language template this happens with? What's the docker version? What's the CLI version?

The poster doesn't specify Swarm or K8s.

**Comment by dayuoba** [comment]
@alexellis 
i tried the official bolg https://blog.alexellis.io/quickstart-openfaas-cli/,
 and use node.js template.
docker version is 17.09
swarm
cli :
faas-cli version
Commit: 6ec90d8ed086dddb26fe3a0775975fba3a71e5a5
Version: dev



@itscaro  > faas-cli deploy --replace --update=false -f stack.yml
this works！
but i think it should be same when without --repace --update=false

**Comment by dayuoba** [comment]
@itscaro image field i filled  with <private-registry/iamge:tag>

**Comment by itscaro** [comment]
@dayuoba You do in this sequence `build, push, deploy`?

**Comment by itscaro** [comment]
Derek add label: question

**Comment by dayuoba** [comment]
> You do in this sequence build, push, deploy?
yes. 
modify handler.js -> build -> push -> deploy -> invoke

**Comment by itscaro** [comment]
@dayuoba Can you retry

```
1 step:
modify handler.js -> build -> push -> deploy without --update & --replace flags -> invoke
2 step:
modify handler.js -> build -> push -> deploy without --update & --replace flags -> invoke
```

Does it work in this sequence?

**Comment by dayuoba** [comment]
@itscaro yes，i used to do this, that's why i post this issue. 
i try your sequence again . don't work

**Comment by alexellis** [comment]
There are two update modes, by default a rolling update is done, but if you've previously pushed an image to the Docker hub or a registry you'll have to push it after every build. The flag is implicit: `--replace=false --update=true`

Mode two deletes and recreates the function and should not be used. `--replace=true --update=false`

Please can you give the environment details we requested so that we can help you resolve the issue? 

Both modes have been tested with Docker Swarm and Kubernetes.

**Comment by dayuoba** [comment]
@alexellis 
docker version is 17.09, swarm
faas-cli version:
Commit: 6ec90d8ed086dddb26fe3a0775975fba3a71e5a5
Version: dev
macOS 10.13.1 


any env i missed?

**Comment by alexellis** [comment]
This may be normal for the few seconds your function is updating. Try `docker service ps functionnamehere`

**Comment by alexellis** [comment]
Derek close: inactive

**Comment by scher200** [comment]
Hi @alexellis I experience the same thing as @dayuoba has but then with faas-netes:
```
faas-cli build -f functions.yml && faas-cli push -f function.yml
faas-cli deploy --replace --update=false -f function.yml
```
or 
```
faas-cli build -f functions.yml && faas-cli push -f function.yml
faas-cli deploy -f function.yml
```
both result in an old image being launched. While deleting the function first and then deploying, is not helping either.
I am using a private repository but this is well configured and pulled the image the first time.
It just does not seem to re-pull and upgrade to the new version of the equally named image.
Good to mention is that I am using names like:  repo.dockerimages.com/username/function:1.1-alpha

**Comment by ivanayov** [comment]
@scher200 I've experienced the same when pushing images to registry, but didn't investigate the issue yet. Might be with Docker Hub.
It seems that there is some caching.

What helps is repeating build/push/deploy.

**Comment by alexellis** [comment]
Why don't you try using a new tag with each version? It's not a good practice to keep reusing the same tag.

You can also use --tag=sha between git commits passed to build, push and deploy. Please open your own issue if you have any other issues with full instructions on how to reproduce

**Comment by alexellis** [comment]
Derek lock
