### ISSUE TITLE
How to view the log and local debug

### ISSUE THREAD

**Issue by ijustyce** [openfaas/faas#492]
I use aws lambda in the past  and I can view the content of console.log in cloudwatch, by use serverless-offline plugin I can run aws lambda locally and can debug it in vscode.

Now I want to self host my code so I try to use openfaas but I can't find useful docs of how to debug locally or view the output of console.log, forgive me for my poor English please, I already search the result by google and stackoverflow but no luck, if anyone know how to do it please let me known thks in advance.

**Comment by itscaro** [comment]
Derek add label: question

**Comment by dvdmuckle** [comment]
You can use `docker logs containername` to view the logs from a given container. This command includes tab complete, which is nice as container names are typically appended with some hash, so your command to view logs may look like `docker logs func_markdown.1.8xickg0qnzjm3j6vqpysgjcas`.

**Comment by alexellis** [comment]
Hey @ijustyce we link to the guides from the main readme, there's also a search bar at the top of GitHub which should help you find what you need.

[Guides index](https://github.com/openfaas/faas/tree/master/guide)

Listed on that page is the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and some notes on debugging too.

`console log` is returned directly as the result of your function.

**Comment by ijustyce** [comment]
Ok, Thanks, I will try it when go home, but I still can't find something like [apigateway custom authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html) Is faas support authorizer function now or how can I add a login interceptor just like spring mvc ?

**Comment by alexellis** [comment]
@ijustyce the easiest way to add authentication/authorisation would be to use our guide for adding Kong. This is a specialist tool for adding that layer. Please refer to the [guides](https://github.com/openfaas/faas/tree/master/guide) for that. I'll close this issue as I think we've answered the question, but please feel free to keep commenting.
