### ISSUE TITLE
Research: revise function signatures

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#494]
We need to do some research into what the best signature would be for functions moving forward.

We have two primary modes in the function watchdog:

* forking mode (existing)
* HTTP or afterburn mode (new)

## forking mode (existing)

The forking mode uses stdio so can support any Linux or Windows binary as a function - most of the time with no changes needed or knowledge of HTTP. So any "bash" utility that works with pipes can be a function - i.e. `cat` or `shasum`. This is the basis for the language templates at https://github.com/openfaas/templates/

The forking mode looks like this:

```
module.exports = function (context, callback) {
  var error;
 
  callback(error, { "apiResult": "passed" })
}
```

HTTP context and environmental variables are fetched like this:

`process.env.Http_Query` or `process.env.Http_Accepts`

The "context" object is the binary bytes representing the body - i.e. a string, or an image or a JSON object that can be parsed.

In Python with the forking mode the response is written to stdout rather than returned.

> Note: We have existing language templates for common programming languages. This mode will continue to be supported.

* Entrypoint which is hidden from user:

https://github.com/openfaas/templates/blob/master/template/node/index.js

* Handler - which is visible to user

https://github.com/openfaas/templates/blob/master/template/node/function/handler.js

Pros:

Any binary can be a function without any supporting libraries
Easy to use

Cons:

Cannot set HTTP response status / headers unless it's 200 OK or 500 program exited with non-zero exit code
Concurrency is more expensive due to forking processes

## HTTP or afterburn mode (new)

This mode requires the binary to expose port 80 over TCP and accept HTTP requests. This is what most of the other Open Source FaaS projects are doing as the only method of invocation. Note - HTTP is never visible to the user - you just write your handler and the rest is hidden by the framework. 

In the newer HTTP or afterburn mode we have a single process handling all requests so environmental variables can no-longer be used in that template for setting HTTP context.

In this mode we'd need to pass the additional HTTP meta-data through the method signature. Here are some options:

* enrich the context so that it gains a `.body` property and a `headers` `query` etc property
* add an additional parameter for headers / context etc
* adopt the style of one of the existing providers such as AWS Lambda, Azure Functions
* something completely different such as [FaaS Lang](https://github.com/faaslang/faaslang) by Keith Harwood (this appears to only cover Node.js and has no adoption beyond Keith's product) but is an interesting take on function signatures

I have put together some sample templates for people to play with the HTTP-enabled version:

* https://github.com/alexellis/python27-flask-template
* https://github.com/alexellis/node8-express-template
* https://github.com/alexellis/golang-http-template

These use the existing handler format from the "forking mode"

> Bottom line - you don't see a trace of the implementation detail in your handler, but you do benefit from it in terms of speed and concurrency. This research is about creating a more flexible signature for the new HTTP or afterburn mode.

* Entrypoint - still hidden from user

https://github.com/alexellis/node8-express-template/blob/master/template/node8-express/index.js

* Handler - visible to user:

https://github.com/alexellis/node8-express-template/blob/master/template/node8-express/function/handler.js

Pros:

High throughput in almost any language
Can set HTTP response status / headers
Concurrency is cheap
Matches technique taken by other FaaS projects

Cons:

Cannot use environmental variables
Requires a HTTP library in each language
New function signature required to support contextual HTTP information

## Considerations for HTTP mode / templates

* Dual maintenance of forking mode and the new HTTP-based mode
* Backwards compatibility
* Documentation
* Recommendations on which to use
* HTTP or rpc for communication between the watchdog and the function process
  * Use of framework-level HTTP servers such as express, flask, sinatra or stdlib level such as "net/http"

**Comment by duckinator** [comment]
@alexellis unless i'm misreading something or there's context i've missed, this seems to inherently oppose the second sentence of the README for this project.

> Any process can be packaged as a function enabling you to consume a range of web events without repetitive boiler-plate coding.

If you have to add network-related code to the program running in it, then what is the point of using the openfaas at all, instead of just a normal web server?

**Comment by alexellis** [comment]
You've misread it.

**Comment by duckinator** [comment]
This is the part I was referring to:

> HTTP or rpc for communication between the watchdog and the function process

Does that not require pulling in an HTTP or RPC library for the process to communicate with the watchdog?

**Comment by alexellis** [comment]
Hi Ellen, please could you take some time to read over the notes above detail comparing the two modes available? Also refer to the updated [README of the of-watchdog](https://github.com/openfaas-incubator/of-watchdog) which goes into the low level details.

**Comment by duckinator** [comment]
Afterburn:

> Vastly accelerated processing speed but requires a client library for each language - HTTP over stdin/stdout. Single-threaded with a mutex.

HTTP:

> Does not require new/custom client libraries like afterburn but makes use of a long-running daemon such as Express.js for Node or Flask for Python

---

This seems to confirm what I said above, not imply that I misread something?

The Afterburn description explicitly says it requires another library, and the HTTP one is literally just an HTTP server running in openfaas. I don't see how this fits the `Any process can be packaged as a function` idea if you're fundamentally changing the behavior of the process to make it work in openfaas, which is all I was saying above.

**Comment by alexellis** [comment]
No that's still not right. There are only two modes listed:

* forking - any process
* HTTP - any process that exposes a HTTP TCP port

This does not invalidate the statement on the homepage.

**Comment by duckinator** [comment]
I just noticed you edited the post and multiple comments after telling me I misread. I re-read them all and it is completely different from what it said originally, but makes far more sense now. Thanks for clarifying the original description.

FYI, GitHub doesn't give notifications about description or comment edits, so it's generally a good idea to leave a new comment saying you update something when you do so. That way people know to re-read the updated sections, which helps avoid miscommunication.

**Comment by duckinator** [comment]
I just noticed you edited the issue description and multiple comments after telling me I misread. I re-read them all and it is completely different from what it said originally, but makes far more sense now. Thanks for clarifying the original description.

FYI, GitHub doesn't give notifications about description or comment edits, so it's generally a good idea to leave a new comment saying you update something when you do so. That way people know to re-read the updated sections, which helps avoid miscommunication.

**Comment by rgee0** [comment]
To clarify, this is a research item, rather than a proposal.  What is written above, to my mind, is describing the current position/options to help elucidate the research direction and the subsequent discussion.  There isnt a suggestion that one mode should be dropped in favour of the other, nor that these options are the only way, rather the description sets out the relative strengths and weaknesses inherent in each existing mode to facilitate further discussion.  Ideally one mode would fit all - maybe this will drive us towards such a solution - but in the event that it doesn't, then we need to be clear on the relative merits of all supported modes so that users are using that most appropriate to their needs.

**Comment by duckinator** [comment]
@rgee0 yes, I understand this. The original unedited issue seemed to imply that these ideas would cause the forking mode to require an HTTP or RPC library. However, as I said in the response immediately prior to yours, Alex edited the issue description and it makes more sense now.

**Comment by alexellis** [comment]
Removing comments as we have clarified the proposal now.

**Comment by alexellis** [comment]
Moving to new issue.
