### ISSUE TITLE
Proposal: configure polling rate for UI

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas#495]
## Current Behaviour
The refresh request is set for every second, sometimes it gets the browser to high cpu usage (perhaps it depends on the machine specs).

It would be nice to have a check box to disable fresh requests and re-enable it, or a configuration to change the periodicity of the refresh request

**Comment by itscaro** [comment]
Derel add label: proposal

**Comment by alexellis** [comment]
This might be better as a configurable delay for the polling?

**Comment by itscaro** [comment]
@alexellis Yes

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
Derek add label: UI

**Comment by alexellis** [comment]
Sounds good to me.. happy for someone to build a configuration pop-up pane to configure this.

Alex

**Comment by alexellis** [comment]
Derek close: inactivity
