### ISSUE TITLE
[UI] invalidate assets cached by browser on changing version of gateway

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas#496]
## Current Behaviour
asset files are possibly cached by browser, when version changes, these files can be outdated.

## Possible Solution
add `?<sha1sum>` to URI of asset files

```
<link rel="stylesheet" href="style/bootstrap.css?7d4edfd8eb346f71f5428090330c9dcac4a7c92e">
<script src="script/funcstore.js?129982807627b4cf72024be4a11f722d3bf6ee5b"></script>
<script src="script/bootstrap.js?da26e6e8c57c16193be0629b9fbdf94d6e2a0a8a"></script>
```

**Comment by ericstoekl** [comment]
Very interesting, thanks @itscaro . Does the `shasum` solution cause duplication of cached assets? Is there a way to mark these assets to have them NOT be cached in the first place?

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by kenfdev** [comment]
@itscaro I was aware about this, too. For now, maybe a simple version number on the JavaScript files could solve the problem.
In the future we should have a pipeline which auto generates the hash with the filename. (It's pretty much baked in in the project skeletons of recent Frontend stacks)
