### ISSUE TITLE
Question:  Is Docker 17.05 still supported as per the swarm guides?

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#499]
## Expected Behaviour
The stack should deploy if the user's Docker configuration matches those described in `guide/deployment_swarm.md` & `guide/deployment_swarm_arm.md`

## Current Behaviour
```sh
$ ./deploy_stack.armhf.sh

Deploying stack
unsupported Compose file version: 3.3
```
## Possible Solution
According to [the Docker docs](https://docs.docker.com/compose/compose-file/compose-versioning/) 3.3 is supported as of 17.06.0, so may just be a case of updating the guides.

If the intention is to support 17.05 then the compose file may need downgrading.

## Steps to Reproduce (for bugs)
1. Install Docker 17.05.0
2. close the faas repo
3. run `./deploy_stack.armhf.sh`

## Context
Following the current guides does not provide users with a successful outcome.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
 $ docker version

Client:

 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:

 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian

* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
Derek add label: Question

**Comment by alexellis** [comment]
As of the change to support configs we need people to use something newer than 17.05. The docker repo has much newer available for arm.. have you tried upgrading? If the docs say 17.05 then that needs changing too.

**Comment by rgee0** [comment]
Thanks

**Comment by alexellis** [comment]
Will you be updating the reference to Docker 17.05?
