### ISSUE TITLE
Question: Is functions/queue-worker:0.4-armhf available from the hub?

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#500]
## Expected Behaviour
`$ ./deploy_stack.armhf.sh` deploys fully and successfully.  

## Current Behaviour
```
$ ./deploy_stack.armhf.sh
Deploying stack
Updating service func_nats (id: w6mlcds2yvv485vqtmj50f5et)
Updating service func_prometheus (id: wlrx0bok2yosb7ah7uzgze4t3)
Updating service func_queue-worker (id: crsf2wuzrx2gjzgafllelynyl)
image functions/queue-worker:0.4-armhf could not be accessed on a registry to record
its digest. Each node will access functions/queue-worker:0.4-armhf independently,
possibly leading to different nodes running different
versions of the image.
```

## Possible Solution
Checking the tags under [the Docker repo](https://hub.docker.com/r/functions/queue-worker/tags/) suggests the expected image may not have been pushed.

## Steps to Reproduce (for bugs)

1. `$ ./deploy_stack.armhf.sh`
2. Observe no error messages
3. Run `$ ./deploy_stack.armhf.sh` again and the message above is presented
4. Check each node in the swarm for available images and queue-worker cannot be found
5. Check [the Docker repo](https://hub.docker.com/r/functions/queue-worker/tags/) and no `0.4-armhf` is found.

## Context
Testing the latest arm stack.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
$ docker version
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:16:34 2018
 OS/Arch:	linux/arm
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:12:44 2018
  OS/Arch:	linux/arm
  Experimental:	false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian

* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
Derek add label: question

**Comment by alexellis** [comment]
@rgee0 I've pushed this up manually. Do you want to keep a single issue to track the testing you're doing on the RPi Zero?

**Comment by rgee0** [comment]
Derek close: Image now available
