### ISSUE TITLE
Proposal: Review function signatures & new option for templates

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#504]
We need to do some research into what the best signature would be for functions moving forward.

We have two primary modes in the function watchdog:

* forking mode (existing)
* HTTP mode (new)

> Note: There will be backwards compatibility for existing functions in OpenFaaS. This is not a breaking change, but a new set of options. "HTTP" mode is described below and is optional, it is not mandated that you use this. Pros and cons are discussed below. 

## forking mode (existing)

The forking mode uses stdio so can support any Linux or Windows binary as a function - most of the time with no changes needed or knowledge of HTTP. So any "bash" utility that works with pipes can be a function - i.e. `cat` or `shasum`. This is the basis for the language templates at https://github.com/openfaas/templates/

The forking mode looks like this:

```
module.exports = function (context, callback) {
  var error;
 
  callback(error, { "apiResult": "passed" })
}
```

HTTP context and environmental variables are fetched like this:

`process.env.Http_Query` or `process.env.Http_Accepts`

The "context" object is the binary bytes representing the body - i.e. a string, or an image or a JSON object that can be parsed.

In Python with the forking mode the response is written to stdout rather than returned.

> Note: We have existing language templates for common programming languages. This mode will continue to be supported.

* Entrypoint which is hidden from user:

https://github.com/openfaas/templates/blob/master/template/node/index.js

* Handler - which is visible to user

https://github.com/openfaas/templates/blob/master/template/node/function/handler.js

Pros:

Any binary can be a function without any supporting libraries
Easy to use

Cons:

Cannot set HTTP response status / headers unless it's 200 OK or 500 program exited with non-zero exit code
Concurrency is more expensive due to forking processes

## HTTP mode (new)

This mode requires the binary to expose port 80 over TCP and accept HTTP requests. This is what most of the other Open Source FaaS projects are doing as the only method of invocation. Note - HTTP is never visible to the user - you just write your handler and the rest is hidden by the framework. 

In the newer HTTP mode we have a single process handling all requests so environmental variables can no-longer be used in that template for setting HTTP context.

In this mode we'd need to pass the additional HTTP meta-data through the method signature. Here are some options:

* enrich the context so that it gains a `.body` property and a `headers` `query` etc property
* add an additional parameter for headers / context etc
* adopt the style of one of the existing providers such as AWS Lambda, Azure Functions
* something completely different such as [FaaS Lang](https://github.com/faaslang/faaslang) by Keith Harwood (this appears to only cover Node.js and has no adoption beyond Keith's product) but is an interesting take on function signatures

I have put together some sample templates for people to play with the HTTP-enabled version:

* https://github.com/alexellis/python27-flask-template
* https://github.com/alexellis/node8-express-template
* https://github.com/alexellis/golang-http-template

These use the existing handler format from the "forking mode"

> Bottom line - you don't see a trace of the implementation detail in your handler, but you do benefit from it in terms of speed and concurrency. This research is about creating a more flexible signature for the new HTTP mode.

* Entrypoint - still hidden from user

https://github.com/alexellis/node8-express-template/blob/master/template/node8-express/index.js

* Handler - visible to user:

https://github.com/alexellis/node8-express-template/blob/master/template/node8-express/function/handler.js

Pros:

High throughput in almost any language
Can set HTTP response status / headers
Concurrency is cheap
Matches technique taken by other FaaS projects

Cons:

Cannot use environmental variables
Requires a HTTP library in each language
New function signature required to support contextual HTTP information

## Considerations for HTTP mode / templates

* Dual maintenance of forking mode and the new HTTP-based mode
* Backwards compatibility
* Documentation
* Recommendations on which to use
* HTTP or rpc for communication between the watchdog and the function process
  * Use of framework-level HTTP servers such as express, flask, sinatra or stdlib level such as "net/http"

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
I'm still figuring out how this works. I think we should go with the AWS Lambda format, and we change from `(context, callback)` to `(event, context, callback)`, where the `event` object contains the request body, and `context` contains the Query and Header data. We could also have `context` contain some more interesting and useful stuff like time remaining for function execution (this is something that Lambda provides).

With regards to how this can be implemented -- currently in the Node8-Express example it looks like the `body-parser` middleware is being used, which will give you an object that only contains `event.body`. Will we need to include another middleware in order to pass a second parameter (`context`) to the handler function?

**Comment by developius** [comment]
I think splitting up the params passed to the handler into `event` and `context` might cause confusion over what `event` actually is. Is it a native javascript event, or is it something custom? I would be in favour of passing one single object to the handler along with a callback (or let it return a promise or use an async function - I have a working example of this), like you tend to with middleware.

```javascript
// example express middleware
function middleware(req, res, next) {
  // do something and call next() with a result
}
```

Having said that, the difference with our handlers vs, say, express' is that we don't currently let them mutate the response (`res.status(404)` for instance). In @alexellis's [new code](https://github.com/alexellis/node8-express-template/blob/master/template/node8-express/index.js#L16-L30) for the 'backend' of the handler (the proxy between the watchdog and the handler itself - `index.js`), the handler is actually mounted as middleware but is passed limited context (just `req.body` in this case).

It would detract from the simplicity of just calling back with a raw response for the client, but the other way to allow fine-grained control over the response would be to mount the handler as middleware directly, giving it access to all the express request/response objects. Not sure if that's a good tradeoff though, as we'd also have to maintain similar functionality for all the other language templates too (presumably?).

**Comment by michaelmerg** [comment]
Hi all,
I'm playing around with faas the last couple of days and implemented a Java runtime (https://github.com/michaelmerg/serverless-function-runtime-java). I used some ideas of the AWS implementation like the same handler signatures.

I think it would the good define some kind of specification for handlers (signature, input and output types, and so on...) and the capabilities of a `context` object that each runtime independent of the language must support.

**Comment by rosskevin** [comment]
FYI @alexellis - I've been using this is node and based on your original node8-express template, now looking at exposing my graphql-ruby endpoint (based on rails-api) in the same way.  I'm still early but I do thing this direction provides a lot of potential.

**Comment by alexellis** [comment]
Closing due to lack of interest from community.

Template store also removes need for some of this discussion. 

Alex

**Comment by alexellis** [comment]
Derek lock
