### ISSUE TITLE
Proposal: Use official Golang image as base in the gateway armhf Dockerfile

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#509]
## Expected Behaviour
Use official Golang image as base in the gateway armhf Dockerfile

## Current Behaviour
Currently the armhf Dockerfile builds from a non-official build created by @alexellis as at the time of creation there was a [bug in the official image](https://github.com/docker-library/golang/issues/184). 

## Possible Solution
Use `golang:1.9.3-alpine3.6` or to stay in line with the x86 stream `golang:1.8.6-alpine3.6`.  Both have been built from successfully and deployed onto a ARM32v7 Pi3.

Alternatively the `golang:1.9.3` & `golang:1.8.6` images show multi-platform support.  If support for ARM32v6 is dropped as per #501 then these images support what would be the supported OpenFaaS platforms meaning the builder base could be standardised across `x86`, `ARM32v7` & `ARM64`.
 
```
Manifest List: Yes
Supported platforms:
 - linux/amd64
 - linux/arm/v7
 - linux/arm64/v8
 - linux/386
 - linux/ppc64le
 - linux/s390x
 - windows/amd64:10.0.14393.2007
 - windows/amd64:10.0.16299.192
```

## Steps to Reproduce (for bugs)
Not a bug

## Context
Currently maintaining a bespoke image for ARM requires time and effort to maintain which frequently causes the armhf version to lag.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:16:34 2018
 OS/Arch:	linux/arm
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:12:44 2018
  OS/Arch:	linux/arm
  Experimental:	false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian

* Link to your project or a code example to reproduce issue:
N/A

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Let's push armhf up to golang-1.9.2. The `faas` / gateway for x86_64 can also be updated since it no-longer depends on Docker.

**Comment by alexellis** [comment]
@rgee0 will you be working on this change?

**Comment by rgee0** [comment]
Yes

**Comment by rgee0** [comment]
Closing as the gateway armhf Dockerfile was updated in 3897d1f54e0b9d9662d2d651bb83be4c96852077
