### ISSUE TITLE
Support Go durations for timeout values

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#510]
## Description

Support Golang durations such as "10s" or "1m20s" in the gateway configuration.

Current behaviour:

```
ENV read_timeout="10" # 10 seconds
```

Expected behaviour:

```
ENV read_timeout="1m" # 60 seconds aka 1 minute

ENV read_timeout="10s" # 10 seconds

ENV read_timeout="10" # 10 seconds
```

This should be backwards compatible with the old method where the configuration for timeouts was assumed to be an integer representing seconds.

See https://github.com/openfaas/faas-netes/blob/master/test/read_config_test.go#L68 for the code I've written to do this there.

## Acceptance criteria

- [ ] Tested end-to-end
- [ ] Code copied from faas-netesd
- [ ] Unit tests updated or copied from faas-netesd

**Comment by viveksyngh** [comment]
I am working on this issue.
