### ISSUE TITLE
gateway not starting while deploying in swarm.

### ISSUE THREAD

**Issue by malikkal** [openfaas/faas#517]
All services coming online except gateway.

![image](https://user-images.githubusercontent.com/16984768/36192680-95a24774-119d-11e8-9493-3d369cf144c5.png)

Any help is much appreciated. Thanks

**Comment by alexellis** [comment]
Hi @malikkal raise a new issue and fill out the whole template please. This is mandatory.

Please also consult the troubleshooting guide for information on how to check what's going wrong. https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md

In particular you should check the logs for the gateway to determine the error.

**Comment by alexellis** [comment]
Derek close: missing information
