### ISSUE TITLE
How long can a code deployed in openFaas can execute

### ISSUE THREAD

**Issue by VenkateshSrini** [openfaas/faas#518]
@alexellis ,
I have used Azure functions earlier. I also had an opportunity to play with openWhisk. One question that keeps coming to mind is does openFass also has a time restriction on the amount of time a code can execute in openFass? If so what is the max time? Can it be configured based on my need ?

**Comment by ericstoekl** [comment]
Hi @VenkateshSrini,
Thanks for checking out the project!

You can configure the time limits for function execution using the `read_timeout:` and `write_timeout:` Environment Variable options. You will make these changes in your function YAML file.

See this link for more info: https://github.com/openfaas/faas/blob/6eca86f31e1fa3fb8748198f927aff63c03d1a28/gateway/README.md#environmental-overrides

You may also be interested in running your function in [Async Mode](https://github.com/openfaas/faas/blob/master/guide/asynchronous.md#guide-on-asynchronous-processing) which will fire a webhook request upon function completion. This is useful for long running tasks.

**Comment by ericstoekl** [comment]
Derek close

**Comment by alexellis** [comment]
Thanks @ericstoekl - please see also our troubleshooting guide which goes into detail about the timeouts at the API Gateway / function level: https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md#timeouts
