### ISSUE TITLE
UI: update portal to work over `kubectl proxy`

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#519]
## Expected Behaviour

If possible the portal UI should work over kubectl proxy

## Current Behaviour

This fails with an error due to the browser trying to query the root of the domain. The kubectl proxy forces a deep relative path so the XHR request fails.

## Possible Solution

Make a non-root call to the /system/functions endpoint? Not sure what the best approach is here.

cc @kenfdev @jrevillas 

## Steps to Reproduce (for bugs)

1. Deploy kubernetes and OpenFaaS
2. `kubectl proxy`
3. Head to 127.0.0.1:8001/api/v1/proxy/namespaces/openfaas/services/gateway/

## Context

Mentioned in following issue: https://github.com/openfaas/faas-netes/issues/63

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
DfM

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Reported by @id0Sch originally

**Comment by kenfdev** [comment]
I assume we can fix this by using relative paths for the ajax calls.
I think traefik is doing it the same way looking at this [PR](https://github.com/containous/traefik/pull/492).

I can look at this in the following week.

**Comment by alexellis** [comment]
Thanks @kenfdev

**Comment by alexellis** [comment]
Merged. Let's close the issue when we have confirmed the fix in 0.7.2

**Comment by alexellis** [comment]
<img width="1045" alt="screen shot 2018-02-25 at 13 08 10" src="https://user-images.githubusercontent.com/6358735/36641741-f4c609c4-1a2c-11e8-8430-eb7085c9abdb.png">

Did I mention it yet? @kenfdev is awesome

**Comment by alexellis** [comment]
Derek close: fixed
