### ISSUE TITLE
Docker Swarm secret not available to function on remote system

### ISSUE THREAD

**Issue by lucasalexander** [openfaas/faas#521]
I have created a secret and granted my function access to it when deploying with faas-cli, and this works in my local environment (Docker 17.12-ce on Windows). When I deploy to my remote system (Docker 17.12-ce on Debian Linux 9), the secret is not available to the function.

## Expected Behaviour
The secret should be available to the function in my remote instance.

## Current Behaviour
I deploy using this command: .\faas-cli.exe deploy -f .\python3-rabbit-crm-client.yml --secret rabbitsecrets

When I inspect the python3-rabbit-crm-client service on my local instance, I see the secret in the task template:
```
"TaskTemplate": {
    "ContainerSpec": {
        "Image": "lucasalexander/python3-rabbit-crm-client:latest",
        "Labels": {
            "com.openfaas.function": "python3-rabbit-crm-client",
            "com.openfaas.uid": "173409400",
            "function": "true"
        },
        "Env": [
            "fprocess=python3 index.py"
        ],
        "StopGracePeriod": 10000000000,
        "DNSConfig": {},
        "Secrets": [
            {
                "File": {
                    "Name": "rabbitsecrets",
                    "UID": "0",
                    "GID": "0",
                    "Mode": 292
                },
                "SecretID": "gbry69xf5eu90h8asbcrp3gsz",
                "SecretName": "rabbitsecrets"
            }
        ],
        "Isolation": "default"
    },
    "Resources": {},
    "RestartPolicy": {
        "Condition": "any",
        "Delay": 5000000000,
        "MaxAttempts": 5
    },
    "Placement": {
        "Constraints": [
            "node.platform.os == linux"
        ]
    },
    "Networks": [
        {
            "Target": "vor6lx717vhtr1st3s6zr3pst"
        }
    ],
    "ForceUpdate": 0,
    "Runtime": "container"
},
```

When I inspect the service on my remote instance, the secret is not listed in the task template:
```
"TaskTemplate": {
	"ContainerSpec": {
		"Image": "lucasalexander/python3-rabbit-crm-client",
		"Labels": {
			"com.openfaas.function": "python3-rabbit-crm-client",
			"function": "true"
		},
		"Env": [
			"fprocess=python3 index.py"
		],
		"StopGracePeriod": 10000000000,
		"DNSConfig": {},
		"Isolation": "default"
	},
	"Resources": {},
	"RestartPolicy": {
		"Condition": "any",
		"Delay": 5000000000,
		"MaxAttempts": 5
	},
	"Placement": {
		"Constraints": [
			"node.platform.os == linux"
		]
	},
	"Networks": [
		{
			"Target": "15k7arichvdo2s1zc8u59p6ee"
		}
	],
	"ForceUpdate": 0,
	"Runtime": "container"
},
```
I have verified the secret exists on the remote system using "secret inspect rabbitsecrets."

## Steps to Reproduce (for bugs)

1. Create secret
2. Create function that reads secret
3. Build function
4. Push function
5. Deploy function with access to secret
6. Run function (works on localhost, throws error on remote)

## Context
I need to allow the function to access secured resources with a username and password.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): 17.12.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Debian Linux 9

* Link to your project or a code example to reproduce issue:
https://hub.docker.com/r/lucasalexander/python3-rabbit-crm-client/

```
import sys
import pika
import uuid
import datetime
import json


def get_secret(secret_name):
    try:
        with open('/run/secrets/{0}'.format(secret_name), 'r') as secret_file:
            return secret_file.read()
    except IOError:
        return None

class CrmRpcClient(object):
    def __init__(self):
        print(get_secret('rabbitsecrets'))
        #i've removed logic beyond this point where it fails to retrieve the secret

def handle(req):
    #instantiate an rpc client
    crm_rpc = CrmRpcClient()
```

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by BurtonR** [comment]
@lucasalexander have you created the secret on the remote system as well?
Secrets are managed by the Docker Swarm. So for _each_ swarm cluster, you would need to run `echo "something secret" | docker secret create rabbitsecrets -`

**Comment by lucasalexander** [comment]
Yes, "docker secret ls" shows it on the remote system.

On February 17, 2018, at 12:48 PM, Burton Rheutan <notifications@github.com> wrote:

@lucasalexander have you created the secret on the remote system as well?
Secrets are managed by the Docker Swarm. So for each swarm cluster, you would need to run echo "something secret" | docker secret create rabbitsecrets -

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openfaas/faas","title":"openfaas/faas","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/openfaas/faas">https://github.com/openfaas/faas</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BurtonR in #521: @lucasalexander have you created the secret on the remote system as well?\r\nSecrets are managed by the Docker Swarm. So for _each_ swarm cluster, you would need to run `echo \"something secret\" | docker secret create rabbitsecrets -`"}],"action":{"name":"View Issue","url":"<a href="https://github.com/openfaas/faas/issues/521#issuecomment-366462696">https://github.com/openfaas/faas/issues/521#issuecomment-366462696</a>"}}}

**Comment by alexellis** [comment]
@lucasalexander this should work. @BurtonR + I are looking into it.

cc @LucasRoesler

**Comment by alexellis** [comment]
I've just tried this with a remote host and it worked as expected.

gw: functions/gateway:0.7.0
Docker:

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:11:05 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:09:37 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

Host: Ubuntu Linux 16.04


```
provider:
  name: faas
  gateway: http://x.x.x.x:8080

functions:
  secrets:
    lang: python
    handler: ./secrets
    image: alexellis2/test-secrets
    secrets:
     - rabbitsecrets
```

Remote server:
```
echo -n "something secret" | docker secret create rabbitsecrets -
```

My laptop:
```
echo -n | faas invoke -f ./secrets.yml secrets
something secret
```

Handler:

```
def get_secret(secret_name):
    try:
        with open('/run/secrets/{0}'.format(secret_name), 'r') as secret_file:
            return secret_file.read()
    except IOError:
        return None

def handle(st):
    print(get_secret('rabbitsecrets'))
```

**Comment by lucasalexander** [comment]
Thanks for the quick responses. I deployed your function to my remote gateway and I am still not seeing the secret available to the deployed function service.

I created this file:
```
provider:
  name: faas
  gateway: https://xxxxxx

functions:
  secrets:
    lang: python
    handler: ./secrets
    image: alexellis2/test-secrets
    secrets:
     - rabbitsecrets
```
And ran this deploy command: _.\faas-cli.exe deploy -f .\test-secrets.yml_. When I run the function I get "None" as the response. I did verify that services on the swarm can access the secret by creating a new service as shown in this [blog post](https://hackernoon.com/managing-secrets-in-docker-swarm-6da766f1357d) and then running _cat /run/secrets/rabbitsecrets_ for the container. Could it be a problem with my copy of faas-cli? Is there a way I can manually deploy a function without using that tool?

**Comment by alexellis** [comment]
@lucasalexander the faas-cli is a REST client and talks over HTTP to the gateway, so Postman or curl could also create a function.

If you're a Windows user, then perhaps you could install [Fiddler](https://www.telerik.com/fiddler) and record the traffic from the faas-cli to see whether the secret list is being sent down the wire correctly?

If you sign up to Slack by emailing alex@openfaas.com we may be able to get some more insights. Right now I cannot reproduce the error on my setup whilst you can.

In the interim while we look into this could you make use of environmental variables?

Also - what version of the CLI are you using?

**Comment by alexellis** [comment]
One more thing you can do is to delete the function and create it again - then look at the logs via `docker service logs func_faas-swarm --tail 50`

**Comment by alexellis** [comment]
This is me using a Linux client against the play-with-docker.com environment.

Perhaps you could try this too?

```
provider:
  name: faas
  gateway: http://ip172-18-0-11-ba4keesa77ug00fmqr4g-8080.direct.labs.play-with-docker.com:8080

functions:
  secrets:
    lang: python
    handler: ./secrets
    image: alexellis2/test-secrets
    secrets:
     - rabbitsecrets
```

![screenshot-pwd-admin](https://user-images.githubusercontent.com/6358735/36350332-cb4f4252-148e-11e8-843d-35877c5f7ece.png)
![screenshot-success-pwd](https://user-images.githubusercontent.com/6358735/36350333-cb6f7f68-148e-11e8-8d8d-5d859aa80957.png)

I don't have easy access to Windows machines but maybe @johnmccabe or @itscaro could try to repro?

**Comment by lucasalexander** [comment]
I get the same "None" reponse in the Docker playground environment. :(
```
provider:
  name: faas
  gateway: http://ip172-18-0-31-ba4usl4a77ug00fmr660-8080.direct.labs.play-with-docker.com:8080
functions:
  secrets:
    lang: python
    handler: ./secrets
    image: alexellis2/test-secrets
    secrets:
     - rabbitsecrets
```
![chrome_2018-02-18_15-34-26](https://user-images.githubusercontent.com/95673/36357280-5fd674cc-14c1-11e8-9ddb-18e9baed4b95.png)
![powershell_2018-02-18_15-34-44](https://user-images.githubusercontent.com/95673/36357277-57e8535c-14c1-11e8-9963-a872327816e5.png)
![chrome_2018-02-18_15-34-37](https://user-images.githubusercontent.com/95673/36357282-6256ede4-14c1-11e8-9135-950c2eb6b834.png)

I am using faas-cli for Windows version 0.6.2, commit a81705b7f50e89bad580f9930436dbf34996cbec. Unfortunately I've not been able to capture a Fiddler trace of the faas-cli requests. Also, here are the logs that show me removing and re-adding the function in my remote environment:
```
func_faas-swarm.1.yi7h4r26xaf3@lucas-ubuntu-01    | 2018/02/18 13:23:25 Attempting to remove service secrets
func_faas-swarm.1.yi7h4r26xaf3@lucas-ubuntu-01    | 2018/02/18 13:23:25 1
func_faas-swarm.1.yi7h4r26xaf3@lucas-ubuntu-01    | 2018/02/18 13:23:46 Error inspecting service Error: No such service: secrets
func_faas-swarm.1.yi7h4r26xaf3@lucas-ubuntu-01    | 2018/02/18 13:23:47 q112nfps8bf9gujk94hvghuqn []
```

**Comment by alexellis** [comment]
My best guess at this time is that there's an underlying issue with Windows and secrets in the YAML file. This works fine on Linux and Mac.

Let's see what the other two guys can add on this. Have you tried running the FaaS CLI on a Linux machine too?

**Comment by johnmccabe** [comment]
Its working for me on Windows 10...

- Deployed a stack to the playground. -
- Created the secret via the playground console
- Deployed the function from powershell on my laptop
- Invoked from my laptop
![image](https://user-images.githubusercontent.com/83862/36358057-b3a82ac6-14ff-11e8-9d56-03b55867e291.png)
- Deleted the fn/secret and deployed and it continued to work.

**Comment by johnmccabe** [comment]
I did however observe swarm get itself in a mess, with the underlying container not being deleted when deleting via the cli.

![image](https://user-images.githubusercontent.com/83862/36358101-608de078-1500-11e8-9f4a-bdb421fec752.png)

OpenFaaS sees only one function, but both containers appear to be responding to requests (note the diff secrets).

![image](https://user-images.githubusercontent.com/83862/36358114-a053ef9a-1500-11e8-956e-3b43af57f2d3.png)

I suspect this is a swarm issue as I've seen something similar occur outside of OpenFaaS...

**Comment by johnmccabe** [comment]
@lucasalexander can you try deploying the example function again, but delete the language key:
```
provider:
  name: faas
  gateway: http://ip172-18-0-31-ba4usl4a77ug00fmr660-8080.direct.labs.play-with-docker.com:8080
functions:
  secrets:
    handler: ./secrets
    image: alexellis2/test-secrets
    secrets:
     - rabbitsecrets
```

**Comment by lucasalexander** [comment]
I feel like I must be doing something dumb. I can't get it to work in the Docker playground with or without the language key when using faas-cli on either my Windows 10 laptop or a Linux machine. I also tried creating the function with Postman, and the function is still not seeing the secret:
```
{
	"service":"secrets",
	"image":"alexellis2/test-secrets",
	"network":"func_functions",
	"envProcess":"python index.py",
	"envVars":{},
	"constraints":null,
	"secrets":["rabbitsecrets"],
	"labels":{},
	"limits":null,
	"requests":null
}
```

Finally I tried deploying the function directly from within the Docker playground environment, and it still doesn't work. 

Question - Do I need to do anything other than create the yml file and execute a deploy if I'm using Alex's image, or do I need to download code and build it myself to get this to work?

**Comment by LucasRoesler** [comment]
I have not been able to replicate this in the play-with-docker.com environment.  I was able to deploy faas, add a secret, and then deploy this stack

```yaml
provider:
  name: faas
  gateway: <...>
functions:
  secrets:
    handler: ./secrets
    image: alexellis2/test-secrets
    secrets:
     - rabbitsecrets
```

Having done this, the function executes and displays the secret as expected.

**Comment by alexellis** [comment]
@lucasalexander to summarize - 4 of us have tried the setup on a mix of Linux, Mac and Windows and Play-with-docker and been able to access the secret. We cannot reproduce the issue.

I can offer you a brief Zoom call this week where we could screen share and observe the issue on your computer remotely. This may give some clues as to why you are encountering difficulties.

**Comment by johnmccabe** [comment]
@alexellis is the problem not this:
```
"envProcess":"python index.py",
```
Will that not try to spawn python to handle a request which won't be there in the test-secrets image?

**Comment by lucasalexander** [comment]
I still can't access the secret even if I omit the envProcess from the JSON body when I create the function. @alexellis I will take you up on the Zoom call offer. I would definitely like to show what I'm doing to see if it's an easy fix. Thanks!

**Comment by lucasalexander** [comment]
Following up on this, I was able to get it working in Docker playground. The only thing I did different this time around was I installed version 0.7.1 instead of version 0.7.0. Would that be expected to make a difference?

**Comment by lucasalexander** [comment]
I am closing this issue as it is now reliably working on 0.7.1.

**Comment by alexellis** [comment]
Glad we could be of assistance. We have been using `functions/gateway:0.7.0`, but if `0.7.1` works please stick with it. Keep in touch and maybe you could get involved with a #FaaSFriday next week? https://twitter.com/search?f=tweets&vertical=default&q=faasfriday&src=typd
