### ISSUE TITLE
Faas-cli list returns: " 'faas' is the only valid provider for this tool - found:"

### ISSUE THREAD

**Issue by paulvanbladel** [openfaas/faas#525]
Following this guide.
https://blog.alexellis.io/quickstart-openfaas-cli/
Works like charm with docker swarm, but faas-cli list gives strange output as described above.
New to open faas (and impressed), so difficult to give more pointers.
What i see from docker service ls is that the callme service is there.
Cheers
paul.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
@iyovcheva please could you help?

**Comment by iyovcheva** [comment]
@paulvanbladel can you please share the steps to reproduce (would be very useful if you have your console history) and give some more information about your environment?
Thanks

**Comment by paulvanbladel** [comment]
hi @iyovcheva 
I think I wasn't running faas-cli list not in a directory that actually contains yaml files.
I can image that list only works under that condition?

**Comment by iyovcheva** [comment]
hi @paulvanbladel 

You don't need to run the command in the same directory.

In the `callme.yml` file there is a `provider` key:
```
provider:
  name: faas
```

The error occurs when provider does not match a valid one [1]. 
`faas-cli list` command parses the yaml files [2].

You may have a typo, missing space or missing provider line.

[1] https://github.com/openfaas/faas-cli/blob/f15e9814976c01b0ebeba3ff97edd178cd9ade86/stack/stack.go#L59
[2] https://github.com/openfaas/faas-cli/blob/cadf7dea543d149b1932f9636dc24805de8643a9/commands/list.go#L42

**Comment by paulvanbladel** [comment]
Can it be the case that faas-cli is confused by other yml files that are not at all related with open-faas?
Anyhow, don't want to loose your time with this, I will just reinstall everything and check if the problem still pops up. I'll close the issue now and come back to you when I discovered a rational/clean way to reproduce. Thanks a lot for your very kind help. Cheers.

**Comment by alexellis** [comment]
There is no need to reinstall anything Paul. Please just follow the tutorial again in a new folder and report back. Multiple YAML files are a supported usecase too.

**Comment by alexellis** [comment]
Thanks @iyovcheva for investigating this issue

**Comment by paulvanbladel** [comment]
@alexellis thx. Btw, great software !!! 
I'm basically writing functions based on the .net core template. Do you have any recommendation when I need a kind of CRON alike scheduler for these functions?
Sorry if this is a beginner question, but what would be the preferred way of actually calling the open faas function from that scheduler:
1. via faas-cli invoke ..
2. via curl and pass arguments in post method ?

Cheers
paul.
