### ISSUE TITLE
Migrate UI's AngularJS from 1.5 to 1.6

### ISSUE THREAD

**Issue by kenfdev** [openfaas/faas#530]
## Current Behaviour

The current AngularJS version of the gateway UI is 1.5. The most recent AngularJS version is 1.6 and has some bugs fixed. For example, #528 occurs because of the bug of the `$http` service. 

## Possible Solution

We should migrate from 1.5 to 1.6.
According to the [docs](https://docs.angularjs.org/guide/migration), there are some breaking changes so we need to be careful not to break existing functionalities.

**Comment by kenfdev** [comment]
Derek add label: UI

**Comment by kenfdev** [comment]
@alexellis according to [this](https://github.com/openfaas/faas/issues/528#issuecomment-367936868) comment, you're suggesting 1.6.6 but the most recent is 1.6.9.
There are some bug fixes so I'd suggest we go with 1.6.9. How do you think?

**Comment by alexellis** [comment]
Derek add label: priority/middle

**Comment by alexellis** [comment]
Fixed. What a fast turn-around @kenfdev - 💯 🥇

**Comment by alexellis** [comment]
Derek close: fixed
