### ISSUE TITLE
Instrument the Gateway API system calls

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas#532]
Provide Prometheus metrics for `/system/functions` API call as in:

* total invocations grouped by HTTP method and response status code
* invocation duration histogram

## Expected Behaviour
Be able to track the rate of system calls and alert on high latency system calls.

## Current Behaviour
API system calls are not instrumented.

## Possible Solution
Extend the current metric provider to system calls.

## Context
Mesure the latency between the Gateway and the Provider for calls such as function listing.

**Comment by alexellis** [comment]
Hey Stefan, thanks for working on this - it looks good on the whole but I have a question.

Imagine if we had an issue such as unexpected latency with one of the specific endpoints such as the one for scaling, listing or deleting a function. How would we diagnose that with the current implementation?

Should we also record the endpoint or the OpenFaaS operation taking place? We do this for individual functions (i.e. recording their names)

What do you think?

**Comment by BurtonR** [comment]
I think this would be a great addition! This would allow us/users/admins to be able to diagnose the OpenFaaS functionality rather than just a function. 

It'd be good to know if the deploy or invoke process was taking too long and be able to find any potential issues there. At least enough to alert someone that they should take a deeper look.

**Comment by alexellis** [comment]
Bump @stefanprodan - this should still happen.

**Comment by stefanprodan** [comment]
Someone else can take it, I don't have spare time to work on this right now.

**Comment by alexellis** [comment]
Derek add label: skill/advanced

**Comment by alexellis** [comment]
Can you link us to your preferred implementation/naming convention? This is to enable HPAv2-style metrics as I remember.

**Comment by alexellis** [comment]
I'll take this.
