### ISSUE TITLE
Watchdog: marshal "Cookie" header into environment

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#538]
## Description

`Http_Cookie` should contain the value passed in the `Cookie` header if it is not already present.

Area for change:

https://github.com/openfaas/faas/blob/master/watchdog/main.go#L206

This change should also cover https://github.com/openfaas-incubator/of-watchdog

Work items:

* First of all - test that the the Cookie is not already transmitted by forcing a header at the gateway

`curl -H "Cookie: some-value" etc....`

* Update the line mentioned in the watchdog and test with setting the `fprocess` env-var to `env` (you can run this on your host without a container for testing

* Next update the of-watchdog with the same change and test in the same way

**Comment by alexellis** [comment]
Suggested contributors: @johnmccabe @dungeonmaster18 @viveksyngh

**Comment by alexellis** [comment]
Derek add label: area/watchdog

**Comment by viveksyngh** [comment]
I will work on this.

**Comment by johnmccabe** [comment]
Just sanity checked this and it appears to be unnecessary. The `Cookie` header, if present, is already resulting in `Http_Cookie` being set in the function env.

https://github.com/openfaas/faas/blob/8f8e337dccb66b3e1dcdc9287e0b037a9937c332/watchdog/main.go#L208-L211

**Comment by johnmccabe** [comment]
Derek close: already implemented
