### ISSUE TITLE
Question on OpenFaaS autoscaling

### ISSUE THREAD

**Issue by white-cloud** [openfaas/faas#541]
Hello

which command i use for example to fix the number of replica depend on the CPU usage or the number of requests ??
Thank you .

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Please fill out "your environment" - thanks

**Comment by ericstoekl** [comment]
@white-cloud -- You should be able to apply min/max scaling by adding the following to your stack.yml file:

```
  labels:
    "com.openfaas.scale.min": "5"
    "com.openfaas.scale.max": "15"
```

Let us know if this works :)

**Comment by alexellis** [comment]
Ping for filling out the template - this will let us answer your question as it may depend on Swarm vs Kubernetes and which version of either. @white-cloud

**Comment by white-cloud** [comment]
Hello @alexellis  thank you for your answer.

I'm using Openfaas in kubernetes v1.9 .

My question now is how to desactivate the autoscaling of openfaas.
Thank you.

**Comment by iyovcheva** [comment]
Hi @white-cloud 

To disable auto-scaling, you should set the minimum and maximum scale to "1".

**Comment by alexellis** [comment]
Yes that will work great @iyovcheva - alternatively remove the alert from AlertManager's configuration. It's bind-mounted from faas-netes YAML / helm. 

https://github.com/openfaas/faas-netes/blob/master/yaml/prometheus_config.yml#L40

Or keep the alert and stop OpenFaaS processing it:

https://github.com/openfaas/faas-netes/blob/master/yaml/alertmanager_config.yml#L62

**Comment by alexellis** [comment]
Derek close: question resolved
