### ISSUE TITLE
Question: how do I use xargs in a function?

### ISSUE THREAD

**Issue by continuata** [openfaas/faas#542]
## Expected Behaviour
when calling a function I expect to be able to pass arguments like this
```
ENV fprocess="xargs ./myfunc"
```

## Current Behaviour
I'm able to call my function successfully explicitly without xargs:
```
ENV fprocess="./myfunc 1 0.005 0.25 0.25"
```
But if I try to use xargs I get `can't find service`

## Context
I want to be able to pass arguments into my compiled C++ function.

## Your Environment
* Docker version 17.12.0-ce-mac49
* Local test Docker instance
* MacOS

Here is my Dockerfile
```
FROM alpine:3.6 as builder
RUN apk add --no-cache curl \
    && curl -SL https://github.com/openfaas/faas/releases/download/0.6.4/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && apk --no-cache del curl

WORKDIR /root/

RUN apk add --no-cache g++ \
  musl-dev
COPY main.c     .

RUN g++ main.c -static -o /poincare \
 && chmod +x /poincare

FROM scratch

COPY --from=builder /poincare           .
COPY --from=builder /usr/bin/fwatchdog  .
COPY --from=builder /tmp /tmp

ENV fprocess="xargs ./poincare"
CMD ["./fwatchdog"]
```

**Comment by alexellis** [comment]
As far as I'm aware the `xargs` approach works.

What `curl` / `invoke` statement are you using?

Do you want to push up a container for me to try out?

**Comment by continuata** [comment]
I'm just running it with 
```
echo -n "1 0.005 0.2 0.2" | faas invoke poincare
```

Which works fine if I change the Dockerfile to be explicit i.e.
```
ENV fprocess="./poincare 1 0.005 0.2 0.2"
```

So I doubt there's anything wrong with how I'm invoking it.
I'm having the same problem with the nmap tutorial code.

**Comment by alexellis** [comment]
Can your code be timing out? Have you looked at the logs yet in the troubleshooting guide re: `write_debug: true`?

https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md

**Comment by alexellis** [comment]
I tried your example and `docker service logs` gave the error.. this should always be the first port of call when things don't look right.

I then swapped scratch for `alpine:3.6` and the program ran. I used the sample here - https://www.geeksforgeeks.org/command-line-arguments-in-c-cpp/

**Comment by continuata** [comment]
that's perfect.
Thanks so much for all the help.
