### ISSUE TITLE
Dashboard ui should indicate when function's Docker image is not yet available

### ISSUE THREAD

**Issue by mjbright** [openfaas/faas#544]
When deploying a new function via "Deploy New Function" it should be clear when a newly added function is not yet available because the Docker image has not yet been pulled.

## Expected Behaviour
I selected "colorize" in the list "From Store", then clicked on the "Deploy" button.
"colorize" is now listed in the list of functions
I should be able to select the "colorize" function, set the appropriate "Request Body" parameters
Pressing the "INVOKE" button should now invoke the function.

## Current Behaviour
When pressing INVOKE" button I get a "500 Internal Server" error.

Note: I suspected this to be the case so manually did a pull of the image.
          Once the image was pulled the function was usable.

## Possible Solution
I'd suggest that whilst the Docker image used by the function is not yet available, that the function appear in the function list but using colour to indicate that it is not yet ready, e.g. grey background, or red text.

## Steps to Reproduce (for bugs)
1.  Select a function in the store which has not already been run and has a large image, e.g. "colorize"
2.  Deploy
3.  In main UI, select the function in the list
4.  Parametrize the function (fill in "Request Body")
5. Press "INVOKE"
6. See that we get an "500 Internal Server" error.

## Context
I wanted to try an interesting FaaS example (though am unsure if "colorize" can be done from ui).
This error would occur for any "long to pull" i.e. large Docker image based function not yet pulled.

## Your Environment
docker-17.12.ce
Swarm
Fedora 27

**Comment by alexellis** [comment]
I agree with the suggestion and it's one we've been working on since last year. Unfortunately it is not a trivial change and does add some latency for Swarm due to the way Docker provide to query the status of container readiness.

If you'd like to do some early testing then please see #556.

I'll close this issue as a duplicate for now.

**Comment by alexellis** [comment]
Derek add label: duplicate
