### ISSUE TITLE
Watchdog: introduce endpoints for health and metrics

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#547]
Update the OpenFaaS Watchdog to introduce two new endpoints:

* /_/health

This should check for the lock file at `/tmp/.lock` - use the existing behavior for this.

* /_/metrics

Vendor Prometheus go library and expose:

Add a Prometheus counter:

```
function_invocation{}
```

This counter should represent the requests/second.

> Need to review Prometheus naming guidelines before approving the name `function_invocation` for the bucket. https://prometheus.io/docs/practices/naming/

Once complete - make equivalent change to the of-watchdog here:

https://github.com/openfaas-incubator/of-watchdog

## Worries / other concerns

* This may be a large chunk of work - so I would prefer two separate Pull Requests for this
* There will be a size increase of watchdog binary when adding Prometheus go library, we need to evaluate this before merging.
* This is the first time the watchdog will override any URL - normally these are marshaled directly to the underlying function

**Comment by stefanprodan** [comment]
Adding the Prometheus client will bring the watchdog binary size to 6MB

**Comment by alexellis** [comment]
Thanks for commenting. The current size is around 3.92MB - so adding instrumentation almost doubles the size of the binary.

**Comment by viveksyngh** [comment]
@alexellis for `_/health` endpoint, what if `.lock` suppressed with `suppressLock` configuration? We need to return 404 in that case.

**Comment by alexellis** [comment]
Great question.. Can you check what Kubernetes expects to fail a health-check? (liveness probe)https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request

**Comment by viveksyngh** [comment]
for Kubernetes, anything greater than `200` to less than `400` is a success. For failed, it uses 500 response.

**Comment by alexellis** [comment]
Sounds good to me

**Comment by kdubuc** [comment]
Dumb question, but what is the difference betweek HEALTHCHECK Dockerfile and the /_/health endpoint ? They returns the same information. OpenFaaS cannot read the docker service HEALTHCHECK status ?

**Comment by alexellis** [comment]
I have done this work now
