### ISSUE TITLE
Community suggestions for Swarm implementation

### ISSUE THREAD

**Issue by ulm0** [openfaas/faas#548]
# Feature(s) proposal
First of all, thanks for the work you've been doing with this project, it's really amazing. I've been playing with it for the first time in my local Swarm through **UI only**.

And I've listed a few things it can be improved on:

### 1. Network-aware functions deployments

When deploying new functions, it either shows an empty network or a default (`func_functions`) one

![image](https://user-images.githubusercontent.com/13160093/36911476-62ec225a-1e22-11e8-885e-ef38b2ea9c84.png)

![image](https://user-images.githubusercontent.com/13160093/36911624-d6de1eac-1e22-11e8-81af-fe8c555adf25.png)

**Proposal:** Since `func_functions` might not be the network used, make functions deployments network-aware by detecting the network `faas-swarm` service is attached to (if it's connected to more than one, service can be inspected and used the first network listed), or the default network can be specified with labels in the `faas-swarm` service scope (e.g. `faas.network=myfaasnetwork`) just like Traefik does (`traefik.docker.network=mytraefiknetwork`).

### 2. Functions official library:

I'm aware of [functions](https://hub.docker.com/u/functions), though some images are out-dated.

**Proposal:** Use this repo for a docker-official-like library for functions and a standard for submiting function images to this library, a curated list.

### 3. Multi-arch function images

Based on the previous proposal. Deploying functions on multi-arch clusters can be a pain (Swarm clusters composed of AMD64 and ARMvX nodes), due to specifying the right arch for the function (e.g adding and/or removing the `-armhf` suffix to the desired image)

**Proposal:** Have (as wide as possible) multi-arch image support by using the manifest-tool. The official functions library might have a pipeline for this. In addition, a new repo can be created for this purpose [github.com/openfaas/functions](https://github.com/openfaas/functions)

**That's all I got so far, if a new idea comes to my mind, i'll update this post asap.**

**Comment by alexellis** [comment]
Thank you for providing your feedback. I'll try to give some responses that represent my available time and the usefulness of these suggestions to the project vs the cost in time and effort to implement them.

* 1. Network-aware UI for Swarm

This has been mentioned before, but it's both technically very involved and something we advise against. OpenFaaS is always deployed to the same network within `deploy_stack.sh`. An override field is available in the UI and the API. The Function Store pre-populates the default network but it can be overriden.

The implementation details are complex on this one. I don't think it's even possible to determine which network the user prefers, unless it's set in environmental configuration i.e. hard-coded. Hard-coding the configuration is a really bad idea as the network name is generated by `docker stack deploy`. Picking the first network out of a list will almost always be the wrong thing to do.

If you can apply a label to the network in the compose file - that may make it possible to query the network, but there's another issue - you have to get that network label out of the faas-swarm provider up to the gateway to be displayed in the UI which means a new set of endpoints. It's a lot of work to support a non-standard configuration.

If you want to work on a solution I'll consider reviewing the detailed proposals and subsequent PRs.

* 2. Library?

What do you mean by official library? Do you mean a new user account on the Docker Hub?

Which Docker images are out-dated? I would not suggest randomly running any Docker image listed within the `functions` namespace on the Docker Hub.

We only maintain the functions in the *function store* and the images in the YAML files for Swarm/Kubernetes. You should not expect any other development images you find to be supported or up to date.

To build new functions use the faas-cli - https://github.com/openfaas/faas-cli

3. Multi-arch images

I am well aware of [multi-arch](https://blog.alexellis.io/tag/raspberry-pi/) and how it works. Individual images are required for every architecture target which then have to be cross-referenced in a virtual image containing the metadata for each image. Multi-arch images require a complex CI build infrastructure which is not available to the project and I don't have time to build or maintain this. 

ARM support is supplied on a best-effort only basis for the community. I am unaware of any business users consuming the ARM versions of OpenFaaS for enterprise/business use-cases - if that changes I'll review.

Right now my cost/benefit analysis is saying 1. is not going to provide a significant benefit and we are pointing people at Kubernetes for running in production or for enterprise where the network name has no meaning. 2. I need clarification but I am not sure there's an issue. 3. while this would be helpful for playing with OpenFaaS on RPi the cost and demand on my time outweighs the benefit to ARM hobbyists. (I say this as an ARM hobbyist)

**Comment by alexellis** [comment]
Here's an update with some good news.

cc @rgee0 

As of the latest versions of faas-swarm we can derive the network name for OpenFaaS functions - that means any stack name can be used. We will have to remove the references to the "func_functions" network from the store's JSON file but can only do that once most people have migrated up - otherwise they will see an error on the "manual" tab.

**Comment by alexellis** [comment]
@ulm0 please check out our update.

**Comment by ulm0** [comment]
I'll give it a try asap, ty!

**Comment by ivanayov** [comment]
@ulm0 do you have new input on the issue? Should we close it?

**Comment by ulm0** [comment]
I dropped off swarm for now since I've been working a lot with kubernetes latelyOn Nov 8, 2018 14:44, Ivana Yovcheva <notifications@github.com> wrote:@ulm0 do you have new input on the issue? Should we close it?

**Comment by ivanayov** [comment]
Derek close
