### ISSUE TITLE
Proposal: Amend fwatchdog documentation to reference container readiness checks

### ISSUE THREAD

**Issue by gkuchta** [openfaas/faas#551]
I realize that using openfaas without `fwatchdog` isn't a supported use case, but it might still be handy to explicitly call out the additional constraint you need to satisfy:

I propose ammending [this section of the fwatchdog README.md](https://github.com/openfaas/faas/blob/master/watchdog/README.md#i-dont-want-to-use-the-watchdog) to:

---

### I don't want to use the watchdog

This is an unsupported use-case for the OpenFaaS project however if your container exposes HTTP POST on port 8080 and satisfies the orchestration readiness checks (for example, writing out a `/tmp/.lock` for Kubernetes) then the OpenFaaS API gateway and other tooling will manage your container.

---

As is, it just mentions exposing 8080, which isn't sufficient to actually get traffic to your container.

Cheers!

**Comment by alexellis** [comment]
Thanks for catching this. Keeping docs up to date is something we care about.
