### ISSUE TITLE
Sample function: Update/extend DockerHubStats

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#561]
## Expected Behaviour

When given a username the function gives the amount of repositories for that username or org.

i.e.

```
%s has %d repositories on the Docker Hub
```

If a username and repo combo is given `username/repo`:

```
Repo: %s has been pulled %d times from the Docker Hub
```

## Current Behaviour

Only supports a username or org to count the repos available.

## Context

The API for fetching image pull statistics is here:

https://hub.docker.com/v2/repositories/functions/gateway/

Code is available here and can be built with the faas-cli

https://github.com/openfaas/faas/tree/master/sample-functions/DockerHubStats

```
cd faas/sample-functions
faas build --filter=dockerhubstats
```

**Comment by BurtonR** [comment]
I'll take this on. Looks like a useful update!

**Comment by alexellis** [comment]
Thanks @BurtonR
