### ISSUE TITLE
Architecture: move requests type from gateway to faas-provider

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#565]
We should move the requests type from the gateway to the faas-provider so that there are no dependencies on the gateway from other code.

**Comment by alexellis** [comment]
Derek add label: enhancement

**Comment by BurtonR** [comment]
I do love clean code :smiley: 

I can get started on this

**Comment by BurtonR** [comment]
@alexellis Currently, in the `faas-provider` the package `types` holds the `requests.go` file.

Changing faas to use the faas-provider would mean changing `requests.Function` (for example) to `types.Function`

Is that what you expect? Or should this change also include changing the faas-provider `types` to `requests` or maybe adding a new package to faas-provider for the requests?

Not sure how you want to handle this. I think adjusting faas to use `types` would be the most backwards compatible. We would then need to add all the request structs to the `requests.go` file in the faas-provider

Just getting started on this and want to make sure I'm headed down the right path (changing faas `requests` to faas-provider `types`)

Thanks!

**Comment by alexellis** [comment]
This is not a simple change and will require co-ordination with all the consumer projects. I would not recommend starting out on this on your own as it will probably get stuck. I have some other things that need attention first. Once we have everything lined up this change can go in without causing too much hassle.

**Comment by BurtonR** [comment]
Sounds good! I was just getting started with it when I realized how big of a change this is going to be!

Ping me again when we're ready

**Comment by alexellis** [comment]
@burtonr @ewilde what if we dual-maintained the requests package in both locations temporarily? what about spinning out a new package/repo for the requests since they're also used in the CLI?

I know @stefanprodan has an interest in this issue

**Comment by alexellis** [comment]
@stefanprodan please could you take this on?

**Comment by stefanprodan** [comment]
Yes, I'll make a v2 branch in ` faas-provider`.

**Comment by alexellis** [comment]
@stefanprodan please can you do what is effectively a 1.x branch where the only work we do is to move the types without changing them?

Then we can get to the v2 after that. :+1: 

Alex

**Comment by alexellis** [comment]
I've opened up this issue to represent the moving of packages as a 1.x refactor - https://github.com/openfaas/faas-provider/issues/22

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-swarm/pull/55
