### ISSUE TITLE
Proposal Autoscaling Increments as percentage of max replica amount

### ISSUE THREAD

**Issue by Templum** [openfaas/faas#569]
## Expected Behaviour
Currently, the auto scaling happens in static 5 increments which are limited by the settable max replicas amount. It would be a nice behaviour if that scaling increments would not be static, but instead a percentage of the max replica amount. Because this would also allow ways to define the scaling behaviour. Function with a high max replica amount will scale large that functions with a lower max replica amount.

## Current Behaviour
Currently, it will be statically 5. Which also causes a not so nice behaviour if it happens that the provided max replica amount is smaller than 5. In that case, it increases by 5 and the later reduces down to the defined max value.

## Possible Solution
In the alerthandler.go replace the constant ```step``` value, with a computed percentage based on ```maxReplicas```. 

## Steps to Reproduce (for bugs)
The described bug under 'Current Behaviour' can be reproduced by setting ```com.openfaas.scale.max``` to something smaller than 5.
When scaling occur you should see initially 5 pods created followed by a downscaling 

## Context
Based on the idea that high used function need to scale more and faster this approach would allow this. If I set an overall higher replica amount it would scale faster, where function which doesn't need to scale fast and in large amounts would scale in smaller steps.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
-

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Are you willing to work on this?

**Comment by Templum** [comment]
Hi Alex,

I gave it a try as it is a smaller change. If you're happy with the [commit](https://github.com/Templum/faas/commit/8e3d5d77672dca92778a858d32ae34adcab36ca1) I also can set up the pull request. 

Change to the handler and also updated the tests to match the percentage scaling.

Cheers,

Simon

**Comment by alexellis** [comment]
@stefanprodan ptal

**Comment by alexellis** [comment]
We'll take a look, thanks again for the proposal.

**Comment by alexellis** [comment]
Perhaps rather than scaling continually by a proportional amount it could scale to a set value? i.e.

min: 1
max: 100

As a percentage of max:

1 r/s  -> 1 replica
2 r/s -> 2 replicas

and so on..

@stefanprodan ?

**Comment by BurtonR** [comment]
Derek close: merged
