### ISSUE TITLE
Architecture: watchdog - graceful termination

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#573]
The watchdog could benefit from doing a graceful termination where by it stops accepting new HTTP requests when it gets a SIGTERM from Swarm or Kubernetes.

Example of an issue reported by Simon (@Templum) during down-scaling of replicas:

https://github.com/openfaas/faas-netes/issues/156

This can be implemented via the new HTTP server cancellation in Go 1.9 and onwards: https://golang.org/pkg/net/http/#Server.Shutdown

Note:

Windows sends SIGINT twice
Linux sends SIGINT then SIGTERM

**Comment by junneyang** [comment]
graceful shutdown not working, my pod remove immediately, not wait for shutdowntimeout, why?  
logs:

![image](https://user-images.githubusercontent.com/6802322/89444968-1a4b8300-d785-11ea-95a1-d1e5795c4e05.png)

**Comment by alexellis** [comment]
Hi @junneyang I do not believe that a 24-hour grace-period is possible in Kubernetes. You can see how the termination process works here:

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

cc @LucasRoesler @andeplane 

Alex

**Comment by junneyang** [comment]
@alexellis  thanks, i made a mistake
i should config preStop hook for kubernetes.
