### ISSUE TITLE
Can we have custom docker guide ?

### ISSUE THREAD

**Issue by serans1** [openfaas/faas#575]
## Expected Behaviour
Not really a bug but more of doc issue, All posts mention custom docker as an option while I couldnt find a guide on the matter.
Can you share some example on how this can be done ?

## Current Behaviour
Found the issue where the feature is requested , didnt find instructions how to use it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
In unclear about what you're asking for.

Can you please explain with some examples?

**Comment by BurtonR** [comment]
@serans1 We definitely want to make sure out documentation is accurate!

Can you provide a link to where the "custom docker as an option" is mentioned? 
You say All Posts. Are you referring to the `community.md` blog posts section? Is there a specific guide you were following where there was some confusion?

**Comment by BurtonR** [comment]
Derek add label: documentation

**Comment by serans1** [comment]
https://github.com/openfaas/faas-cli/issues/29

**Comment by BurtonR** [comment]
I see. You were looking at an old issue. If you take a look at the merged PR, the "custom" was changed to "dockerfile" after some discussion:

> Changed from "Custom" to "Dockerfile" after discussion on Slack / GitHub. #29

So, to get the available templates, you can run the following commands:

```bash
faas-cli template pull
faas-cli new --list
```
which will return the following output:

```bash
Languages available as templates:
- csharp
- dockerfile
- go
- go-armhf
- node
- node-arm64
- node-armhf
- python
- python-armhf
- python3
- ruby

```

This is described in the faas-cli readme: [Run the CLI](https://github.com/openfaas/faas-cli#run-the-cli)

**Comment by BurtonR** [comment]
Derek: close

**Comment by BurtonR** [comment]
Derek close

**Comment by alexellis** [comment]
Thanks Burton :100:

**Comment by serans1** [comment]
Kudos for the prompt handling, Star is on the way :)
Giving it a drive
