### ISSUE TITLE
NATS clients not reconnecting if NATS server fails over

### ISSUE THREAD

**Issue by vosmith** [openfaas/faas#579]
When a NATS Streaming server running in in-memory mode restarts, all of the clients need to reconnect to NATS according to this issue:

https://github.com/nats-io/nats-streaming-server/issues/150

While using OpenFaas it appears that the Gateway and QueueWorker are not aware of restarts from NATS, and all subsequent async function calls fail due to a publish ack timeout.

## Expected Behaviour

If a NATS server restarts, the connected clients should reconnect

## Current Behaviour

If a NATS server restarts, clients timeout while waiting for the publish ack.

## Possible Solutions

1. Test NATS connections periodically and, attempt to reconnect if the connection fails.
1. Check the connection if the a publish ack encounters a timeout.  Retry the operation after successfully reconnecting.

## Steps to Reproduce (for bugs)

1. Deploy openfaas
2. Deploy a function
3. Tail the logs for the gateway and your function deployment
3. Call the function asynchronously
4. Observe the logs for NATS submitting the job and your function forking the process
5. kubectl delete your NATS pod
6. Call the function asynchronously
7. Observe the logs for NATS after 30s with the publish ack timeout message and no further logs in the function deployment. 

## Context

AFAIK, Most container schedulers will restart pods if it deems it necessary.  For OpenFaas applications using any async function calls, this will prevent them for working properly.  We have an application that basically performs a series of ETL jobs which are all asynchronous :).
  
## Your Environment

* Docker version 1.13.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:
Please see steps above :sweat_smile: 

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

Adjustments made the the helm chart for our deployment
* Adding ingresses for the services in values.yml
* Adding resource limits on all services
* Bumping up all timeouts to 300s

**Comment by iyovcheva** [comment]
Derek add label: review
Derek add label: proposal
Derek add label: support

**Comment by iyovcheva** [comment]
Derek add label: proposal

**Comment by iyovcheva** [comment]
Derek add label: support

**Comment by iyovcheva** [comment]
Thanks for logging this @vosmith 
If you're interested in contributing a fix, we'd be happy to review/merge.

**Comment by iyovcheva** [comment]
Derek add label: help wanted

**Comment by vosmith** [comment]
Hey @iyovcheva , I would love to! Let me see what I can do :+1:

**Comment by vosmith** [comment]
Hey @iyovcheva , the work done to fix this issue is actually in the [nats-queue-worker](https://github.com/openfaas/nats-queue-worker repository).  I've submitted PR [117](https://github.com/openfaas/nats-queue-worker/pull/17) as a fix and is ready for review.  Thanks!

**Comment by astub** [comment]
Could this be the issue i'm having with async X-Callback-Url not getting a request? What logs should I look for to verify this?

**Comment by alexellis** [comment]
@astub it's unlikely unless you think your nats-streaming server restarted for some unknown reason.

You should check out the troubleshooting guide:

https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md

Check the logs for the queue-worker and raise a new issue for your problem if you can't figure it out.

**Comment by ivanayov** [comment]
Upcoming fix with [#33](https://github.com/openfaas/nats-queue-worker/pull/33)

**Comment by alexellis** [comment]
This is now resolved
