### ISSUE TITLE
Error : Manifest for function/faas-swarm:0.2.1 not found

### ISSUE THREAD

**Issue by yogeek** [openfaas/faas#580]
The "0.2.1" tag used in the default stack (docker-compose.yml) does not exist for the "function/faas-swarm" image

## Expected Behaviour
Testing openfaas stack with "Try in PWD" button must deploy the stack in PWD without error

## Current Behaviour
Testing openfaas stack with "Try in PWD" button leads to the following error :
`Error : manifest for functions/faas-swarm:0.2.1 not found`

## Possible Solution
The reason is : the tag "0.2.1" is missing for the image : https://hub.docker.com/r/functions/faas-swarm/tags/
Solutions : 
- add this tag and push the tagged image in dockerhub
or
- change the tag of functions/faas-swarm by an existing tag in docker-compose.yml

**Comment by alexellis** [comment]
Thanks for noting this. Can you checkout the tag 0.7.3 which is also in the test drive guide?

**Comment by alexellis** [comment]
Master also contains 0.2.2 which is a valid existing tag if you'd like to repull?

**Comment by alexellis** [comment]
Moved to 0.2.2 tag to fix this. Thank you for reporting.

**Comment by yogeek** [comment]
Sorry for the delay, I was not able to test the new tag before. Thank you for the fix !
