### ISSUE TITLE
[Proposal] Add title element to index.html for gateway

### ISSUE THREAD

**Issue by dvdmuckle** [openfaas/faas#597]
## Expected Behaviour

Show something like "OpenFaaS Portal" as the title element for the OpenFaaS gateway UI.

## Current Behaviour

Currently, the title shows up as whatever URL the user uses to browser to the gateway UI

## Possible Solution

Add a <title> element to the index.html file for the gateway

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
I think this makes sense. If you'd like to go ahead with that.

**Comment by dvdmuckle** [comment]
Created #600

**Comment by alexellis** [comment]
Derek close: fixed by #600
