### ISSUE TITLE
Support: Timeout troubleshooting

### ISSUE THREAD

**Issue by tarunmangukiya** [openfaas/faas#608]
## Expected Behaviour

I am writing a function to bulk transfer files to s3 from remote urls in NodeJS. Function container is responding with success and gateway must forward the same to the user.

## Current Behaviour
I have checked container logs. Function container is returning success in 26 seconds. But gateway is responding it with 502 error. I've checked that the function's the task is performed and I can see the output in s3.

The same function works when I transfer 1-2 files, but when I transfer let's say 15-20 files the function behaves like this.

I've put 100s timeout everywhere, in gateway and in function too.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version 17.12.0-ce-win47 (15139)
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

**Comment by alexellis** [comment]
Hi @tarunmangukiya it sounds like your timeout values have not been set appropriately.

You didn't say whether you followed the troubleshooting guide:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have.

Questions:

* Can you upload your docker-compose.yml and function's YAML into a Gist (not the issue) and paste the URL here?

https://gist.github.com 

* When you say "everywhere" what does that include?

* How are you invoking the function?

**Comment by tarunmangukiya** [comment]
Hi @alexellis, Yes I've followed the troubleshooting guide to resolve timeout issue, earlier it was 500 error due to `timeout`, then I changed it accordingly and it worked for small 1-2 number of files.

Gist: https://gist.github.com/tarunmangukiya/16136dacba8e8a43ce458f3e353a2aa2
Includes: `docker-compose.yaml`, `handler.js`, `package.json` and `stack.yml`
In handler.js there're 3 env variables, S3_KEY, S3_SECRET, S3_ENDPOINT.

Changed Timeouts in `docker-compose.yml` and `stack.yml` for gateway timeout and individual function timeout, I did change the value in `faas-swarm` just to verify if it's timeout issue.

I am invoking function from OpenFaaS Portal UI, tried with PostMan too, same issue.

I've attached `requests.txt` to make a sample request call in gist.

**Comment by alexellis** [comment]
With the latest gateway version this field should be a Golang duration. So I think "1000" was meant to be 1000s which is 16 minutes (probably way too high)

`            read_timeout:  1000   # set both here, and on your functions`


Your gateway is also quite old at `functions/gateway:0.7.0`
Perhaps you could update to a later version of faas-swarm and the gateway?

Look at the file in master for the compose file and please try again. 

https://github.com/openfaas/faas/blob/master/docker-compose.yml

It will be easier to replace your docker-compose.yml file with the latest and then tune the timeout values - please also use Golang durations i.e. "60s" or "300s" etc.

**Comment by tarunmangukiya** [comment]
Yeah I set it to check if there's an issue with the timeouts. Let me update the gateway and revert soon.

Thank you!

**Comment by tarunmangukiya** [comment]
@alexellis For now it feels like that was the gateway version issue itself, tried with 40+ files now and it's working perfectly. We can close the issue for now. Will inform in case of any issue in future.

Thanks for your help and OpenFaaS :)

**Comment by alexellis** [comment]
I'm glad to hear this. You should also try the async route for longer running tasks. Then the jobs can go into the background.

**Comment by tarunmangukiya** [comment]
Ya checked it, pretty useful to create large sized zip on the go for our [Iconscout.com](https://iconscout.com) 🥇 

Will surely try it.

**Comment by tarunmangukiya** [comment]
Hey @alexellis, new gateway is working great with, but there's one more issue started occurring. Now for long running functions > 20s the curl shows, `No reply from server` error. And the timing of this error is random.

Gateway logs `200 response` when it completes, and there's no timing relation between the error at calling server and Faas server.

Also, there was one more error that showing, `Empty response from server`, while gateway responds with the `200 status` and proper bytes.

Can't understand the reason behind both the cases, as those are random in timings.

**Comment by alexellis** [comment]
What are all the values you picked for the gateway?

**Comment by tarunmangukiya** [comment]
300s for each read, write and upstream, I need higher values as we're already processing the events from the jobs, the FaaS are divided in different individual dockers.

**Comment by alexellis** [comment]
Can you attach your current docker-compose.yml file as a gist?

Basically you are saying you have a 5 minute timeout which is cutting off at around 20 seconds in?

**Comment by tarunmangukiya** [comment]
Yes, 5 minute timeout and that's not exactly 20s. Each time the time is different. I measured it with stopwatch.

And even I tried to put the higher values like 1800, but still no luck.

Docker-compose.yml: https://gist.github.com/tarunmangukiya/ebfd6cfeb830629f3cabf1d4f22408b7

**Comment by alexellis** [comment]
Related issue:

`            upstream_timeout: "300s"     # Maximum duration of upstream function call - should be more than read_timeout and write_timeout
`

Please read the comment and alter this value.

**Comment by alexellis** [comment]
Let's try this function: https://github.com/alexellis/issue-608/

**Comment by alexellis** [comment]
I set the timeout_secs: value to "25000" - 25s and then ran this:

```
time curl http://192.168.0.35:8080/function/sleep-for -d test -i
HTTP/1.1 502 Bad Gateway
X-Call-Id: b3c4961f-fdd2-4c21-ac38-9e5589d3d62b
X-Start-Time: 1522227789600187415
Date: Wed, 28 Mar 2018 09:03:29 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

real	0m20.020s
```

It worked as expected breaking off the connection at the 20s mark which is the default configuration set in the gateway under `upstream_timeout`.

**Comment by tarunmangukiya** [comment]
Let me try.

**Comment by alexellis** [comment]
I extended the timeouts on the gateway to around 60s for read/write timeout and 65s for the upstream_timeout and then set my timeout_secs in the function to 35000.

```
time curl http://192.168.0.35:8080/function/sleep-for -d test -i
HTTP/1.1 200 OK
Content-Length: 32
Content-Type: application/x-www-form-urlencoded
Date: Wed, 28 Mar 2018 09:09:01 GMT
X-Call-Id: dda82122-7454-4347-89c3-afec54b44094
X-Duration-Seconds: 35.100177
X-Start-Time: 1522228106782001810

Waiting 35000
{"status":"done"}

real	0m35.120s
user	0m0.005s
sys	0m0.006s
```

Worked as expected.

**Comment by tarunmangukiya** [comment]
What's `timeout_secs`?

**Comment by tarunmangukiya** [comment]
Got it, it's there for function handler.

**Comment by tarunmangukiya** [comment]
Your function is working perfect.
While in mine.

**Output in Curl**
> POST /function/func_icons-premium HTTP/1.1
> Host: 192.168.31.35:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 18636
> Expect: 100-continue
>
> HTTP/1.1 100 Continue
> We are completely uploaded and fine
> Empty reply from server
> Connection #0 to host 192.168.31.35 left intact
curl: (52) Empty reply from server

**Gateway Log**
> 2018/03/28 09:21:46 Forwarded [POST] to /function/func_icons-premium - [200] - 95.478713 seconds

Have increased `upstream time` in  `docker-compose.yml`

**Comment by alexellis** [comment]
The handler you have exported in handler.js looks fairly different from what is generated by the template. I would not be surprised if the error is related to that.

```
export default async (event, callback) => {
}
```

**Comment by tarunmangukiya** [comment]
Actually I edited the handler to support AWS like `(event, context)`, `context.fail()` and `context.succeed()`.

Let me check & deploy the OpenFaaS into VMs if the issue is related to docker installation or OS.

**Comment by alexellis** [comment]
My time is very limited so let's try this - revert your template to the official OpenFaaS version and drop the fancy async keywords etc. They are not going to leverage significant benefits for the function at hand.

Then create a GitHub repo - public or private - push your code there and try to build/deploy/invoke your code. If you are still having issues share the repo with me and any secrets needed for S3 (temporary bucket is OK) so I can try to reproduce the issue.

Right now there are too many variables and my controlled experiment could not reproduce the issue.

**Comment by alexellis** [comment]
I think you had an update that you posted on slack. What's the status of your issue now?

**Comment by tarunmangukiya** [comment]
Hi @alex, that empty response issue was with docker installation itself. Reinstalled docker and it's working like charm. Now there're few minor issues for now. I think I'll be able to manage with it.

Thanks for your help guys!
