### ISSUE TITLE
Push docker images to Quay as well as to DockerHub

### ISSUE THREAD

**Issue by iyovcheva** [openfaas/faas#609]
We would like to have an additional option for Docker registry in case DockerHub support is dropped.
Please find here the [Quay Documentation](https://www.google.bg/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjq3tXwvYnaAhUkIJoKHc_HDZ8QFggnMAA&url=https%3A%2F%2Fdocs.quay.io%2Fsolution%2Fgetting-started.html&usg=AOvVaw32taSpoVDZnr4Ak6jjFQ1d)

## Expected Behaviour

`faas push -f func.yml` should push images to DockerHub or Quay based on the image prefix.

## Current Behaviour

`faas push -f func.yml` pushes the docker image to one's DockerHub account

## Possible Solution

Add something like `sudo docker push quay.io/namespace/repository:tag` to [pushImage](https://github.com/openfaas/faas-cli/blob/e81362363338afde4ca84a4568f728ede7406fb7/commands/push.go#L72)()
Check `imagePrefix` as well.

## Steps to Reproduce (for bugs)

Not a bug

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by iyovcheva** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
I think I didn't explain the intent of this very well.

The idea was to push the images during CI to both Docker Hub and Quay.io - it needs some PRs to the Travis YAML file for all the main repositories.
