### ISSUE TITLE
IDEA Transport Layer abstraction by introducing transport Plugin

### ISSUE THREAD

**Issue by s8sg** [openfaas/faas#611]
## Expected Behaviour
The current transport layer is based on HTTP. Having a transport level abstraction and plugin based implementation of different transport mechanism  (e.g. Kakfa, rabbitmq etc) would allow the platform user to choose best suited transport layer for their use-case. 

## Current Behaviour
Currently `HTTP protocol` is being used as the basic transport layer for all the functions. Every Function includes a watchdog that transfer the `HTTP` request to/from `STDIN/STDOUT`  
The APIGateway accepts `HTTP` requests and forwards it to the applicable functions as a `HTTP` request

## Possible Solution
**Watchdog** can be implemented to accept different types of request once it has a transport level abstraction. A plugin based implementation for different types of transport will allow user to choose from a variety of possible transport protocol. For watchdog the transport layer is only to accept request and to send reply
```bash
/usr/bin/fwatchdog --platform-transport kafka:<kafka_broker>:<topic> 
```

In the other hand for **API Gateway**; the Transport layer for forwarding request, as well as for the incoming request can be specified **separately**. So that In a user environment where the user already using a Kafka based broker doesn't need a separate Kafka connector to forward request to APIGateway. 

```bash
./gateway --incoming-transport http --platform-transport kafka:<kafka_broker>
```

The API-gateway request should be aware of each application transport details (e.g. `IP` in case of HTTP and `topic` in case of Kafka) and the details should be abstracted/handled by specific plugins

The load-balancing between service can happen in the same manners as it is working now

## Context
It is always better make a open platform highly flexible in terms of implementation. A transport layer abstraction would allow user to choose their favourite broker. 

```
 _______________________________________
| APIGateway    |   Function Watchdog   |
|---------------------------------------|
|            Transport Layer            |
|---------------------------------------|
| Prometheus   |  Swarm  |   Kubernets  |
|---------------------------------------|
|                Docker                 |
 ---------------------------------------
```

**Comment by iyovcheva** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
I am not sure that the watchdog is the appropriate place to make this change - it introduces far too many moving parts. All traffic should ingress through the API gateway.

Please see my pattern for the Kafka connector - it uses OpenFaaS as a black box and enables any event type to be subscribed to providing a small amount of code is written to subscribe.

https://github.com/openfaas-incubator/kafka-connector

You can also get a video demo in our [last community meeting via YouTube](https://www.youtube.com/watch?v=lD2zqUuLOqc&list=PLlIapFDp305BebghsydcwLYO_zyI1kBVc&index=12&t=103s).

**Comment by alexellis** [comment]
I'm going to close the issue because it's a duplicate and we already have work underway to support this (see above). Please feel free to keep commenting. See also #400 #470

**Comment by alexellis** [comment]
Derek add label: duplicate
