### ISSUE TITLE
Docs: write-up how to use a private registry with OpenFaaS on Kubernetes

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#623]
The docs site should have a new page or new paragraph added on how to use a private registry with Kubernetes.

* Link to how to deploy the registry in the K8s docs
* Show how to create an image pull secret
* Show an OpenFaaS YAML file with the secret added in the `secrets section`

Some of this has already been done in markdown in other markdown but can be condensed down. 

https://github.com/openfaas/faas-netes/blob/master/SECRETS.md

Target repo - http://github.com/openfaas/docs

**Comment by iyovcheva** [comment]
Derek assign: i yovcheva

**Comment by iyovcheva** [comment]
Derek assign: iyovcheva

**Comment by alexellis** [comment]
Please keep the docs information focused on the use of private images rather than on secrets as a generic topic. We should also add a separate page on the use of secrets.

**Comment by ericstoekl** [comment]
Shouldn't this issue be tracked in the `docs` repo?

**Comment by alexellis** [comment]
I have no problems with tracking it here since we have a lot of repositories much of the work is starting out in the faas repo which is the front-facing repo if that makes sense.

**Comment by jmo808** [comment]
If OpenFaaS is deployed on K8s there's a way to assign private registry login info to the namespace service account. I tested this by assigning the docker registry secret to the openfaas-fn namespace and then you can push the private images and k8s auto assigns the imagePullSecrets to the pod manifest. On AWS and GKE managed K8s their own private registry login info is already added to their managed node builds.  AKS it has to be manually configured as described above (which would be the same instructions for non managed K8s). I can supply those documentation bits (which is merged from a couple of articles I found that led me to that solution).

**Comment by alexellis** [comment]
The method we have documented is to create a named image pull secret and then to have that referenced at the function level in the YAML file

@jmo808 it'd be good for you to add your solution to the final page too.

Here's an updated version of Lucas' markdown for us to trim down and take over to the docs site: https://github.com/LucasRoesler/faas-netes/blob/2a2868e9000b437bd5e2baa90598e2369bafd7d7/SECRETS.md

**Comment by jmo808** [comment]
Yes, I did thanks! I'm in now.

**Comment by alexellis** [comment]
Maybe you could send your initial PR and markdown here? https://github.com/openfaas/faas-netes/blob/master/SECRETS.md Then we could take it over to the new docs site from there. 

Do you use Swarm in any of your work?

**Comment by iyovcheva** [comment]
@jmo808 Can you please send your PR on this as well - [docs/pull#6](https://github.com/openfaas/docs/pull/6) ?

**Comment by iyovcheva** [comment]
Thanks @jmo808

**Comment by alexellis** [comment]
Hi @jmo808 we're going to merge Ivana's PR then you can send one onto that.

https://github.com/openfaas/docs/pull/6

**Comment by alexellis** [comment]
Sounds good! (It's merged now)

**Comment by BurtonR** [comment]
Derek close: merged
