### ISSUE TITLE
Docs: write up on how to start out contributing

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#626]
We need a very brief high-level document on how to start contributing. It should not be a duplication of the contribution guide - think of it as an onboarding guide for new people.

* Link to Golang tutorials - https://blog.alexellis.io/tag/golang-basics/
* Explanation of the different repos (cut/paste the GitHub headline)
* How to clone the repositories (a script to clone the main ones)
* Link to how to work on the UI
* Where to download Golang (link)
* Link to contribution guide
* Link to re-writing Git history / signing-off quick commands

What else do we think should be here that would help with on-boarding new people?

**Comment by alexellis** [comment]
An initial version is up here ready for a PR / enhancement from community - https://docs.openfaas.com/contributing/get-started/

**Comment by neomatrix369** [comment]
@alexellis Take a look at what I did for https://github.com/neomatrix369/awesome-graal (see https://github.com/neomatrix369/awesome-graal/blob/master/CONTRIBUTING.md)

**Comment by alexellis** [comment]
I like that page. We have something similar here - https://github.com/openfaas/faas/blob/master/community.md

**Comment by alexellis** [comment]
Recording from recent meeting online with the community on this topic. https://youtu.be/7djgiSuoyII

**Comment by alexellis** [comment]
Given the lack of interest in this topic I put something together and [published it in the docs](https://docs.openfaas.com/contributing/get-started/) - @iyovcheva then added a section with links for Go/Docker. :+1:

**Comment by alexellis** [comment]
Derek close: completed
