### ISSUE TITLE
Update list of Derek maintainers across all repos

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#630]
The current list of active Derek users I believe is represented in the following list.

We need to create PRs (signed-off) to update this across all repos. Signing off can be done through the GitHub UI if this makes the task easier by putting a final line in the commit message.

I've also updated the list so that it has a priority of who is most active in the project.

```
maintainers:
 - alexellis
 - iyovcheva
 - BurtonR
 - rgee0
 - ericstoekl
 - stefanprodan
 - kenfdev
 - johnmccabe
 - itscaro
 - jockdarock

features:
 - dco_check
 - comments
```

@JockDaRock @itscaro do you want to remain in this list? I haven't seen you use Derek / comment on issues for several weeks.

If anyone else would like to be in this list please comment. By being in the list you can use Derek to manage PRs and Issues.

More on Derek here - https://github.com/alexellis/derek - https://blog.alexellis.io/derek/

**Comment by alexellis** [comment]
@dungeonmaster18 is welcome to stay in the list where he is already there.

**Comment by viveksyngh** [comment]
I would like to be added to this list.

**Comment by alexellis** [comment]
That’s fine by me Vivek. Feel free to raise some of the PRs to update the lists and to add yourself too.

**Comment by BurtonR** [comment]
This work is in progress and has been completed (via redirect to faas' `.DEREK.yml`)
* [faas-cli](https://github.com/openfaas/faas-cli/pull/412)
* [faas-swarm](https://github.com/openfaas/faas-swarm/commit/7f5eed999bf81b67961c670327eb942702dec5a6)
* [faas-netes](https://github.com/openfaas/faas-netes/commit/36b6c87ceff44e2be9222947ee3e36ff08b442c8)

Still needs to be done on the following:

- [ ] [openfaas-cloud](https://github.com/openfaas/openfaas-cloud)
- [ ] [docs](https://github.com/openfaas/docs) 
- [ ] [workshop](https://github.com/openfaas/workshop)
- [ ] [templates](https://github.com/openfaas/templates)
- [ ] [store](https://github.com/openfaas/store)
- [ ] [certifier](https://github.com/openfaas/certifier)
- [ ] [nats-queue-worker](https://github.com/openfaas/nats-queue-worker)
- [ ] [openfaas-serverless](https://github.com/openfaas/serverless-openfaas)

Also, the following project within the OpenFaaS organization do _not_ have a `.DEREK.yml` file and will need added:
* [faas-provider](https://github.com/openfaas/faas-provider)
* [caddy-builder](https://github.com/openfaas/caddy-builder)
* [serverless-openfaas-nodejs](https://github.com/openfaas/serverless-openfaas-nodejs)
* [backer-thankyou](https://github.com/openfaas/backer-thankyou)

@alexellis could you review the above list and make sure this is what you want? If so, I can start making the PRs to the repos that have derek enabled already.
I think you'll need to add derek to the ones that do not yet have it enabled.

**Comment by itscaro** [comment]
Hi Alex, I will be less busy in a few weeks, hopefully starting from mid
July.

Thanks
-- 
Minh-Quan TRAN

**Comment by affix** [comment]
Hey Alex, Add me :)

**Comment by alexellis** [comment]
Go for it.. send a PR to derek.yml here Keiran

**Comment by alexellis** [comment]
@itscaro welcome back, looking forward to catching up and showing you OpenFaaS Cloud
