### ISSUE TITLE
Issues with function chaining following function director pattern

### ISSUE THREAD

**Issue by satie** [openfaas/faas#633]
## Current Behaviour
I am trying out OpenFaas and having issues chaining/composing functions following the [function director pattern](https://github.com/openfaas/faas/blob/master/guide/chaining_functions.md#function-director-pattern). However, I can pipe output of one function to another using `curl`.

I am trying to accomplish the following - 
* `world` function returns the text 'world'
* `hello` function take text as input and return 'hello _text_' as output
* `helloworld` chains the two functions above by taking the output of `world` as input for `hello` and outputs 'Hello world'

Function piping works from the command line by piping the following commands - 
```bash
$ curl -s http://127.0.0.1:8080/function/world | curl -sX POST http://127.0.0.1:8080/function/hello --data @-
Hello world
```

However, chaining the functions following the [function director pattern](https://github.com/openfaas/faas/blob/master/guide/chaining_functions.md#function-director-pattern) does not seem to work. The function seems to _hang_ and CPU utilization of docker goes up drastically.

Can someone please suggest what I may be doing wrong?

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 18.03.0-ce, build 0520e24
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
macOS 10.12.6
* Link to your project or a code example to reproduce issue:
https://github.com/satie/helloworld-faas

**Comment by alexellis** [comment]
Hi I took a quick look at the code and noticed that it looked quite complicated. I wonder if you could try using the request.js npm module in your example?

I suspect that something like a missing callback or event in the example may be causing the issue.

Alex

**Comment by satie** [comment]
Replaced the http calls with request.js.

Thanks.

**Comment by alexellis** [comment]
I'm pretty sure I can see the issue now. You are referring to `localhost` from within a Docker container... that will not do what you're expecting. I think it may be calling the function recursively.

Check this line:
https://github.com/satie/helloworld-faas/blob/master/helloworld/handler.js#L6

You should use `gateway` or `gateway.openfaas` not `localhost`. Please try it again and let me know.

See also the workshop which I think may cover this - https://github.com/openfaas/workshop

**Comment by satie** [comment]
That seems to have done the trick. Thanks for pointing that out. I kind of thought that `gateway` was suggested more on general terms.

**Comment by Abhishekghosh1998** [comment]
@alexellis In OpenFaas is this the equivalent of Apache OpenWhisk Action Sequence?
