### ISSUE TITLE
Function with custom response for Twilio

### ISSUE THREAD

**Issue by chzbrgr71** [openfaas/faas#634]
I'm working on an OpenFaaS function that accepts webhook requests from Twilio based on incoming text messages. The standard Twilio response is packaged as XML, so the encoded message must be "text/xml" The current Python template just responds as text and thus creates an error in Twilio. 

In my ```handler.py``` I am using print or return, but they result in an error within Twilio. 

## Expected Behaviour
I want a way in the Python function to format the response contentType to "text/xml" 

## Current Behaviour
It looks like the response contentType is "application/x-www-form-urlencoded" The messages look like this: ```<?xml version="1.0" encoding="UTF-8"?><Response><Message>Ahoy! Thanks so much for your message.</Message></Response>```

## Steps to Reproduce (for bugs)
I created my function using the steps here: https://docs.openfaas.com/tutorials/first-python-function 

The Twilio details are here: https://www.twilio.com/docs/sms/quickstart/python 

## Your Environment
OpenFaas on AKS

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS 

* My handler.py code looks like this: 

```
import requests
import json
from log import Log
from twilio.twiml.messaging_response import MessagingResponse

def handle(req):
    log = Log()

   # Add code here to parse payload

    # Start our response
    resp = MessagingResponse()

    # Add a message
    resp.message("Ahoy! Thanks so much for your message.")
    
    log.info(str(resp))
    return str(resp)
```

**Comment by BurtonR** [comment]
Hi @chzbrgr71! It sounds like you're in need of the updated watchdog that handles function via an "http mode". This means you can set the headers, content type, response status, etc...
Check it out here: https://github.com/openfaas-incubator/of-watchdog

And for you, here's the Python/Flask template to start off with: https://github.com/openfaas-incubator/python-flask-template

**Comment by chzbrgr71** [comment]
Thank you for the help!!! I was able to try this out and it worked perfectly. I made zero changes to my code. Only changed to the above template.
