### ISSUE TITLE
Question: Can Swarm Secrets take Different Source and Target projection?

### ISSUE THREAD

**Issue by blaskovicz** [openfaas/faas#635]
## Overview
I recently updated my playground-golang function to have redis support. As such, it was necessary for that function to have a redis url, and thus a docker swarm secret defined in its [yaml](https://github.com/blaskovicz/playground-golang/commit/668d21f010b3b51f13acb713c3c40daa4d283d21#diff-90444407ac06d912d8624b4396c7d99bR11).

I usually set my secrets in the form `$app-name-prefix_$var_name_$version` and then [map them to a shorter name at runtime](https://github.com/blaskovicz/cut-me-some-slack/blob/master/docker-compose.yml#L11), via `docker-compose.yml` (since secrets are immutable, and global). Is this possible to do something like this in OpenFaaS (eg: via faas-cli)?

## Possible Workaround

I developed [go-swarmed](https://github.com/blaskovicz/go-swarmed) which maps `/var/run/<file...>` to corresponding env variables to help people transitioning from Heroku to Docker Swarm. I recently [enhanced it](https://github.com/blaskovicz/go-swarmed/commit/fe5b653281f364aeb279513cc3daffd56972d755#diff-04c6e90faac2675aa89e2176d2eec7d8R36) to strip off app name prefixes and version suffixes, if enabled.
Of course, this only works for golang.

## Other

1) It seems the "secure secret management guide" on [your apikey-secret example README.md page](https://github.com/openfaas/faas/tree/master/sample-functions/apikey-secret) is broken.
2) The page says "deploy this sample with Docker Swarm and attach the secret to it" but I had to search around for another openfaas guide showing how to do it (faas-cli guide).
3) Would you be willing to have an example golang function ([similar to this one](https://github.com/openfaas/faas/blob/master/sample-functions/apikey-secret/handler.go#L15)) using the [go-swarmed](https://github.com/blaskovicz/go-swarmed)  library?

**Comment by alexellis** [comment]
Hi @blaskovicz thanks for your suggestion.

At this time we are not looking to change the secrets projection behaviour in Swarm and Kubernetes.

What code do you have which expects the secret format you mention above? Is there any reason why it can't use the full path as specified such as `$app-name-prefix_$var_name_$version`?

Maybe you could write some code to scan /var/run/secrets to match on your `$var_name` portion and bind to that?

Alex

**Comment by alexellis** [comment]
Derek close: wontfix
