### ISSUE TITLE
UI doesn't work with JavaScript disabled

### ISSUE THREAD

**Issue by Rillian-Grant** [openfaas/faas#647]
## Expected Behaviour

You should get a message telling you to enable JS

## Current Behaviour

You get what looks like a html template

## Possible Solution

This pull request: #646 

Signed-off-by: Rillian Grant <rillian.grant@hotmail.com>

**Comment by alexellis** [comment]
Hi @Rillian-Grant thank you for your contribution. I would not expect the OpenFaaS UI to work without JavaScript, but this is an interesting PR. I'm going to ask @kenfdev to give some input.

Alex

**Comment by alexellis** [comment]
Hi @Rillian-Grant we will need some screenshots for this change. Please see the comments in the PR.

**Comment by alexellis** [comment]
PR is now in: https://github.com/openfaas/faas/pull/659

**Comment by alexellis** [comment]
@cpitkin do you want to try using Derek here to close the issue?

**Comment by cpitkin** [comment]
Derek close
