### ISSUE TITLE
CI: passwords for Docker Hub must be read from stdin

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#650]
Just like the OpenFaaS CLI the Docker CLI now mandates passwords are passed-in via STDIN.

We have to update all of our projects which publish Docker images to do this.

* faas
* faas-swarm
* nats-queue-worker

etc

The change needs to take place in .travis.yml - see faas-netes as an example of where I've already done this.

**Comment by iyovcheva** [comment]
Derek assign: iyovcheva
