### ISSUE TITLE
Question: using Selenium with OpenFaaS

### ISSUE THREAD

**Issue by ankitaggarwal-trantor** [openfaas/faas#654]
I have a python application to automate browser using splinter (selenium) library. Its is working fine through Docker or directly through module. But when I am implementing it through Openfaas, it returning Bad Gateway Error. Seems like selenium or browser automation not working with Openfaas. I have tried headless and xvfb both. It will be great if any one can share working example of openfaas with selenium headless or xvfb.

**Comment by alexellis** [comment]
@ankitaggarwal-trantor the runtime environment for an OpenFaaS function is a Docker container, but it's not privileged. Therefore you may want to look at how to run Selenium in an unprivileged mode or with something like Headless Chrome.

If you can find something that works with AWS Lambda then the chances are that you could make it work with OpenFaaS too. Here's a couple of links I found on Google:

https://medium.com/clog/running-selenium-and-headless-chrome-on-aws-lambda-fb350458e4df
https://aws.amazon.com/blogs/devops/ui-testing-at-scale-with-aws-lambda/

**Comment by alexellis** [comment]
One of the ways automation testing can scale up is by running a Selenium grid - or farm of different hosts and browsers. You can then use the remote web-driver to connect to them and this means you don't have to worry about installing or running a browser inside your function / container.

Example:

http://selenium-python.readthedocs.io/getting-started.html#using-selenium-with-remote-webdriver

Let us know how you get on.

**Comment by alexellis** [comment]
Derek set title: Question: using Selenium with OpenFaaS

**Comment by alexellis** [comment]
Derek close: this issue is now inactive after two weeks so I'm going to close it. Feel free to keep commenting.
