### ISSUE TITLE
faas-cli build failing when using 'Dockerfile' (uppercase D)

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas#655]
This is an issue that we fixed a while back, but there may be a regression. In version `0.6.5` I am seeing this issue crop up again:

## Expected Behaviour

Given a stack file that looks like this:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hellodocker:
    lang: Dockerfile
    handler: ./hellodocker
    image: hellodocker
```

I would expect the `dockerfile` language template to be used. However I get the error:

```
$ faas build -f hellodocker.yml 
[0] > Building hellodocker.
2018/04/17 08:41:38 Language template: Dockerfile not supported. Build a custom Dockerfile instead.
```

Editing the `hellodocker.yml` file and putting it back to `dockerfile` resolves this issue.

## Current Behaviour

Language must be `dockerfile` with a lowercase `d` or else it will fail with `Dockerfile not supported` error message.

## Possible Solution

`ToLower()` language value before checking it against available templates.

## Steps to Reproduce (for bugs)

1. `faas new hellodocker --lang dockerfile`
2. Edit `hellodocker.yml` to change `dockerfile` to `Dockerfile`
3. `faas cli build -f hellodocker.yml`
4.

## Context

Ran into this while attempting to build an older function I made back when `Dockerfile` was the standard.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 18.03.0-ce-rc4

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 1604

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by rgee0** [comment]
Is this on the correct repo?

**Comment by rgee0** [comment]
https://github.com/openfaas/faas-cli/blob/ae7390005a2fe13873f2cb6fcfa2d830dad4a40b/builder/build.go#L18

and 

https://github.com/openfaas/faas-cli/blob/b9e2aef1389f2027c3f55c6041e26ecfe2bab772/stack/language_template.go#L50

**Comment by viveksyngh** [comment]
I have tested this and it seems to work.

```
functions /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new hellodocker --lang=Dockerfile
Folder: hellodocker created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: hellodocker
Stack file written: hellodocker.yml

/Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli build -f hellodocker.yml
[0] > Building hellodocker.
Building: viveksyngh/hellodocker with Dockerfile. Please wait..
Sending build context to Docker daemon   2.56kB
Step 1/6 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/6 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.7.6/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Using cache
 ---> 5b493b622dce
Step 3/6 : ENV fprocess="cat"
 ---> Using cache
 ---> 08c55fdb0c8a
Step 4/6 : ENV write_debug="false"
 ---> Using cache
 ---> cccfac4d242b
Step 5/6 : HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1
 ---> Using cache
 ---> 1a4e79800627
Step 6/6 : CMD [ "fwatchdog" ]
 ---> Using cache
 ---> 746c1b8191ad
Successfully built 746c1b8191ad
Successfully tagged viveksyngh/hellodocker:latest
Image: viveksyngh/hellodocker built.
[0] < Building hellodocker done.
[0] worker done.
➜  functions /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli push -f hellodocker.yml
[0] > Pushing hellodocker.
The push refers to repository [docker.io/viveksyngh/hellodocker]
fedd7aa36668: Layer already exists
9dfa40a0da3b: Layer already exists
latest: digest: sha256:3634f4ef40f5506720ad32a585d16fcf31cd77b6864b3f3e23fd552c95a61782 size: 739
[0] < Pushing hellodocker done.
[0] worker done.
➜  functions /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli deploy -f hellodocker.yml -g http://185.136.235.75:31112
Deploying: hellodocker.
Function hellodocker already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://185.136.235.75:31112/function/hellodocker

```

**Comment by alexellis** [comment]
Good collaboration on this. Richard do you want to raise a PR?

**Comment by alexellis** [comment]
Fixed in https://github.com/openfaas/faas-cli/pull/383
