### ISSUE TITLE
Future item: remove templates from faas-cli repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#658]
The `faas-cli` used to be the home for the OpenFaaS templates, but now it's the `templates` repo instead. We should delete the template folder from the `faas-cli` repo when we're comfortable that everyone has upgraded to a version of the CLI that points to the `templates` repo

https://github.com/openfaas/templates/

We will also need to update the build/deploy scripts for the samples so they do a `faas template pull` before building - otherwise it will generate an error.

**Comment by alexellis** [comment]
@BurtonR @rgee0 FYI

**Comment by rgee0** [comment]
Is this on the correct repo?

What is meant when we refer to future?  Is it hours, days, weeks?

This is where the anonymous analytics would have really helped out.  Using `av` we could measure __an__ impact of this change to inform our comfort levels.

**Comment by alexellis** [comment]
Yes this is the best repo to surface and to track suggestions.

We are where we are, so when do we do this work?

**Comment by stantonxu** [comment]
@alexellis @rgee0 I would like to work on this issue by submitting a pull request. Before doing that, I've reviewed the code. In the current HEAD version, the `DefaultTemplateRepository` is already set to `https://github.com/openfaas/templates.git`. 

And in the build script, it already calls the `PullTemplates` method, which will pull template from default repo `https://github.com/openfaas/templates.git` if not repo is indicated. In the deploy script, it will check the `./template` folder, and ask to run `faas template pull` command, which is also valid if we delete the `template` folder.

So does that mean we just need to simply delete the `template` folder in the `faas-cli` repo, as all others are already ready?

**Comment by BurtonR** [comment]
I do believe that you are correct @stantonxu! Thanks for taking the time to dig through all the code to be sure of that though! 
Be sure to check out the [contribution guide](https://github.com/openfaas/faas-cli/blob/master/CONTRIBUTING.md) and don't forget to sign your commit :smile:

**Comment by stantonxu** [comment]
Thank you @BurtonR for your quick confirm. Working on it.

**Comment by stantonxu** [comment]
https://github.com/openfaas/faas-cli/pull/419 ready for review.

**Comment by rgee0** [comment]
Please be advised that this is potentially a breaking change for some users and so timing of any merge will be a consideration.  In light of that please provide details of affected versions and dates in the PR detail as this will help the decision process.

**Comment by stantonxu** [comment]
@rgee0 thanks, is there a template for the affected versions and dates to be included in the PR details?

By the way, it depends on when you guys decide to approve and merge the PR. I see the current released version is 0.6.10 by Alex on Jun 5th. So should I say that the affected versions are 0.6.10 and below, and dates are Jun 5th and before?

**Comment by alexellis** [comment]
If you land here via Google or searching issues, please let us know if you had an issue with this change. We recommend you update your CLI via curl, brew or the releases page.

**Comment by alexellis** [comment]
Thanks @stantonxu for your first PR 🎉

**Comment by stantonxu** [comment]
Thank you @burtonr @rgee0 @alexellis
