### ISSUE TITLE
Update Golang versions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#660]
Update faas gateway and watchdog to use Golang 1.9.6 in Dockerfiles.

No-harm testing will be necessary

Relates to #523

**Comment by alexellis** [comment]
Testing:
- Basic no-harm testing needed

**Comment by alexellis** [comment]
Nobody has worked on this issue for 2 months - Go 1.9.7 is now available so we should move straight to that.

1.10 has breaking changes so will be the next move later on.

**Comment by wwsean08** [comment]
Will be opening a PR tonight or tomorrow moving to 1.9.7.

**Comment by BurtonR** [comment]
Derek close
