### ISSUE TITLE
Document CLI and yml file available options

### ISSUE THREAD

**Issue by burtonr** [openfaas/faas#661]
## Description

The documentation of the faas-cli YAML format is currently in its README and misses several of the new features.

## Tasks

* Move text from [README.md](https://github.com/openfaas/faas-cli/blob/master/README.md#yaml-format-reference) file and moved over to the docs site at https://github.com/openfaas/docs
* Add any missing sections about the YAML format (you'll need to identify what these are by looking at the Go code and then filling in the gaps)
  * limits/requests
  * anything else
* Remove content from faas-cli README and link to the docs page

**Comment by ericstoekl** [comment]
I am trying this out on my fork, any feedback is welcome:

https://github.com/ericstoekl/docs/blob/documentYamlCli/docs/reference/yaml.md

In particular, [this section](https://github.com/ericstoekl/docs/blob/documentYamlCli/docs/reference/yaml.md#limits-and-requests) is new, and it would be good to document these things. I am quite sure that `Limits` and `Requests` do something different on Swarm vs on Kubernetes, and we should figure out exactly what they do. So far I am pretty sure what they do, except for Requests for Memory on Kubernetes.

**Comment by cpitkin** [comment]
This issue will fix this issue in the docs repo openfaas/docs#12

**Comment by alexellis** [comment]
@ericstoekl if unsure then please err on the side of caution and don't explain the concepts - just link to the relative documentation.

Have you covered everything that is available in the YAML stack in your new file? (There may be things which were not in the faas-cli README)

**Comment by alexellis** [comment]
@ericstoekl can you raise a PR if you're working on this? Thanks

**Comment by alexellis** [comment]
@ericstoekl please raise a PR, this work appears to have been dropped.

**Comment by alexellis** [comment]
Derek close: merged - I updated this and released it on the docs site today.
