### ISSUE TITLE
Support: Google Puppeteer (web-browser automation)

### ISSUE THREAD

**Issue by developer-rakeshpaul** [openfaas/faas#662]
Hi Team,

I am trying to run the google chrome puppeteer packge on faas. However, I get the following error when i try to invoke the function using a node template.  I did modify the node template to incorporate the troubleshooting suggestions provided by the puppeteer team.

```
(node:2701) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[0422/092906.458598:FATAL:zygote_host_impl_linux.cc(199)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid).
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at Interface.onClose (/home/app/function/node_modules/puppeteer/lib/Launcher.js:174:14)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
(node:2701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018/04/22 09:29:06 Duration: 0.226985 seconds

```
I have used a modified template using the node template. Please find below the corresponding git repository with the respective template and handler function.
[faas-function](https://github.com/developer-rakeshpaul/faas-functions)

## Your Environment

* Docker version `docker version` 18.03.0-ce:

* I am using Docker Swarm

* Operating System and version: MacOS(High Sierra 10.13.4):

* Link to your project or a code example to reproduce issue:
[faas-function](https://github.com/developer-rakeshpaul/faas-functions)

Any directions to resolve this will be a great help for me. Thanks a lot for this wonderful project..

Thanks and Warm Regards,
Rakesh

**Comment by alexellis** [comment]
cc @ericstoekl - have you worked with automating web-browsers/chrome with OpenFaaS?

**Comment by developer-rakeshpaul** [comment]
Hi Alex,

Could you please check  [troubleshooting document](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) by the puppeteer team. 

> One of their tips is to try running the container with docker run --cap-add=SYS_ADMIN when developing locally. Since the Dockerfile adds a pptr user as a non-privileged user, it may not have all the necessary privileges.

Is it possible to run the docker container like that using faas.

**Comment by ericstoekl** [comment]
I have run into the same issue that @developer-rakeshpaul is reporting here -- it is not specifically an issue with OF. This was why I couldn't use the node template for making a screenshotter. Elevating privilege may be possible through the Dockerfile (@alexellis  please weigh in)

**Comment by alexellis** [comment]
Functions do not run as `SYS_ADMIN` in any platform I can think of - this is really insecure, Docker Swarm won't even allow for it.

The options I linked to allow you to run Chrome without elevating privileges. Please try that first.

**Comment by developer-rakeshpaul** [comment]
Sure Alex, I did give it a try and faced some issues. Will try once again and update with my results. Thanks a lot for the feedback.

**Comment by developer-rakeshpaul** [comment]
@alexellis I am still facing some issues with the alternate methods suggested by you. I get the following error.

```
Internal Server Error
exit status 1
{"status":"done"}
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/app/headless_shell ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


```

I have pushed the latest code to [GitHub](https://github.com/developer-rakeshpaul/faas-functions). I doubt if it is caused some missing dependencies by the headless chromium.

**Comment by alexellis** [comment]
The error clearly says that `/home/app/headless_shell` does not exist. Have you checked that it is where you expect it to be in the container?

`docker run webshot ls /home/app/headless_shell`

It would also help if you could push the image up to the Docker Hub.

**Comment by developer-rakeshpaul** [comment]
Yes I did check that the file exists in the folder.. Please find below the result of ls -ltr on the /home/app folder 

```
-rwxrwxrwx    1 app      app      104854024 Mar  4 09:52 headless_shell
-rw-r--r--    1 app      app            280 Apr 26 12:33 package.json
-rw-r--r--    1 app      app            752 Apr 26 12:33 index.js
-rw-r--r--    1 app      app       43553884 Apr 26 12:35 HeadlessChrome.tar.gz
-rw-r--r--    1 app      app            304 Apr 26 12:36 package-lock.json
drwxr-sr-x    1 app      app           4096 Apr 26 12:36 node_modules
drwxr-sr-x    1 app      app           4096 Apr 26 12:40 function
```

I will work on pushing the image to docker hub and update once it is done.

**Comment by alexellis** [comment]
So I built your container and I think the problem is that you need to use Debian as a base or install libc which is probably missing in Alpine.

**Comment by alexellis** [comment]
Ping @developer-rakeshpaul - PTAL

**Comment by developer-rakeshpaul** [comment]
@alexellis finally got it working with the node:8-slim image. Pushed the changes to [GitHub](https://github.com/developer-rakeshpaul/faas-functions) Thanks a lot for the help Alex
