### ISSUE TITLE
Build images for PR's to avoid checking out code to try new features

### ISSUE THREAD

**Issue by marcosnils** [openfaas/faas#663]
It'd be nice if PR images could be built to try new features before they're meged to master without having to checkout the code and compile it locally.

Spoke briefly with @alexellis about it and we thought that it might be a good idea.

**Comment by alexellis** [comment]
Who do we do about misuse?

**Comment by marcosnils** [comment]
tag the images as snapshots so people won't use them unnecessary?

**Comment by alexellis** [comment]
I think we could do this if someone wanted to work on it. Perhaps it should use a different account name to make sure it is separate from the official builds.

**Comment by alexellis** [comment]
Derek add label: help wanted

**Comment by alexellis** [comment]
Also looks useful - https://docs.travis-ci.com/user/pull-requests/

**Comment by ericstoekl** [comment]
RE misuse -- the issue would be if people create many pull requests and cause lots of builds to be run on the openfaas travis-ci account? Isn't travis-ci free for open source?

**Comment by iyovcheva** [comment]
@ericstoekl yes, it is ([travis plans](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiQkqPr-eHaAhXCNJoKHZDaAooQFggnMAA&url=https%3A%2F%2Ftravis-ci.com%2Fplans&usg=AOvVaw1bYqatsMt6_SzAQqlWTm_1)). I think there are 5 concurrent jobs available for open source projects.

**Comment by bishwenduk029** [comment]
Hello everyone I would love to work on this one, ofcourse if no one has started yet, will be needing guidance from you all.....

**Comment by alexellis** [comment]
If someone wants to work on this and is able to test this independently then I'd support that. IMHO the images should push to a separate Docker namespace which makes it clear that these are untrusted builds from public PRs.

**Comment by alexellis** [comment]
Derek close: inactivity
