### ISSUE TITLE
Proposal: Use gRPC for communication between services

### ISSUE THREAD

**Issue by topicus** [openfaas/faas#669]
## Expected Behaviour
I would like to call lambda functions using gRPC instead of http

## Current Behaviour
Currently, only http calls are supported. 

## Possible Solution
Modify Function Watchdog to support gRPC

## Context
There are two main advantages of using gRPC over http:
- **Schema reflection:** Schema introspection open up an opportunity to compose function types into a bigger schema (GraphQL for example).
- **Performance:** using a binary protocol reduces the overhead of an http call.

**Comment by alexellis** [comment]
Derek set title: Proposal: Use gRPC for communication between services

**Comment by alexellis** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
@topicus please can you revise your proposal in accordance with the contribution guide? https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#i-have-a-great-idea

Thanks,

Alex

**Comment by alexellis** [comment]
Derek close: doesn't comply with contribution guide.

**Comment by alexellis** [comment]
Feel free to keep commenting and if you have data-points I'd be happy to consider them.

**Comment by alexellis** [comment]
Derek lock

**Comment by alexellis** [comment]
A proper use-case needs to be given for such a broad architecture change to even be considered. The contribution guide lays out exactly what is required, so if someone lands here, I'd recommend you read the contribution guide and then write-up a full proposal arguing the case for why you need this feature.
