### ISSUE TITLE
Question on tuning auto-scaling

### ISSUE THREAD

**Issue by yurifrl** [openfaas/faas#671]
Hy, I'm sorry to use an issue to ask this, but can someone point me to the docs of how to add a new scale rule? or force a scale manually. I've read about prometheus alerting but can't grasp my head around it, I've also tried to get an invite to slack with a email to alex@openfaas.com but it seams the address doesn't exist.

My problem is that I have a long time function, that runs asynchronously and the pods are not scaling to supply the demand, so the function takes twenty minutes and goes one at the time, I need to add some sort of alert rule on prometheus to scale based on demand I don't know.

**Comment by BurtonR** [comment]
The [docs site](https://docs.openfaas.com/) is a work in progress, but still a good resource for more information on OpenFaaS. Here is the link to the auto-scaling section: https://docs.openfaas.com/architecture/autoscaling/

Also, [the workshop](https://github.com/openfaas/workshop) is another great resource to understand the basics of OpenFaaS. The lab on auto scaling may provide some useful information for you here: https://github.com/openfaas/workshop/blob/master/lab8.md

**Comment by BurtonR** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Hi @yurifrl - you should scale the amount of queue-workers - each one will run a single task in parallel by default with a maximum task duration of 30 seconds. You can read about how to alter timeouts in the documentation.

You mention Pods but haven't filled out our issue template so I am going to guess you're on Kubernetes. Scale the queue worker to the degree of parallelism you want (it's a light-weight component) and let us know how you get on. 

alex@openfaas.com is valid and used every day but you need to send an email with more than 8 words to get past the spam filter. How about you share your email with us in this issue and I will invite you to the community?

**Comment by yurifrl** [comment]
Hello everyone, thanks for your answers, I did scale the queue-workers, and it worked fine, Thank you.

**Comment by yurifrl** [comment]
@alexellis If you can invite me to the slack channel that would be awesome, my email is yurifl03@gmail.com

**Comment by alexellis** [comment]
Great to hear it.
