### ISSUE TITLE
Suggestion: make UI available offline

### ISSUE THREAD

**Issue by Rillian-Grant** [openfaas/faas#675]
The web UI cannot be used offline as the angular.js file is grabbed from http://googleapis.com/

## Possible Solution

Store the angular.js file with the other js and the index.js files

## Steps to Reproduce (for bugs)

1. Visit the web UI without internet acess

**Comment by alexellis** [comment]
I think this is to be expected.

Couple of questions about this issue:

Why do you need offline access? Who else would need offline access?

How important is this to the project vs the cost of maintaining all the files from a CDN?

**Comment by Rillian-Grant** [comment]
I have a Pi that has no WIFI and I use it to play with OpenFaaS

**Comment by alexellis** [comment]
How do you build OpenFaaS functions without internet access?

**Comment by Rillian-Grant** [comment]
I pull the images over ethernet

**Comment by alexellis** [comment]
I'm not sure we should do this, so I'm going to close and mark for revisit.
