### ISSUE TITLE
Traefik guide should include the async-function endpoint

### ISSUE THREAD

**Issue by alexking** [openfaas/faas#678]
Since queuing an async function uses a different endpoint than normal (`/async-function`) it isn't possible with the [documented traefik configuration](https://github.com/openfaas/faas/blob/17a3564ca0a31c68390de2d9de6cfde44021b931/guide/traefik_integration.md#update-the-gateway-service). Adding to the PathPrefix fixes this. Adding this as an issue because pull requests for [typos are discouraged](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md). 

## Expected Behaviour

Calling an async function should return 202 Accepted.

## Current Behaviour

 
Trying to run an async function behind Traefik with this configuration will return a 404 error. 

## Possible Solution

[Documentation](https://github.com/openfaas/faas/blob/17a3564ca0a31c68390de2d9de6cfde44021b931/guide/traefik_integration.md#update-the-gateway-service) should change from 

```
- traefik.frontend.rule=PathPrefix:/ui,/system,/function
```

to 

```
- traefik.frontend.rule=PathPrefix:/ui,/system,/function,/async-function
```

## Steps to Reproduce (for bugs)

1. Setup Traefik according to guide
2. Try to run an async function

**Comment by alexellis** [comment]
Hi @alexking this isn't a typo, it was just written before async was a stable feature. If you can test your change and confirm it works along with the previous behaviour still in fact for /ui and /system then I can merge a PR for the change.

Alex

**Comment by alexellis** [comment]
Please also read the contribution guide about Git sign-off, that means not editing in the UI or if you do adding a proper signed-off line at the end of the commit message. The git CLI does this for you via `git commit -s`

**Comment by alexking** [comment]
Ah yeah I figured - was interpreting typo too broadly - I'll send in a pull request 😄

**Comment by alexellis** [comment]
Derek close: fixed / released.
