### ISSUE TITLE
Suggestion: Add Cache-Control and ETag in watchdog environments

### ISSUE THREAD

**Issue by s8sg** [openfaas/faas#679]
## Context
many website including github use aggressive cache in order to avoid excessive load. For an open-faas function providing content that is behind one of those server may not function properly till the cache is expired. 
i.e: function like [of_badge_gen](https://github.com/s8sg/of_badge_gen) might not provide the right status image till the cache is expired. 
The similar problem is described in this thread: [Aggressive image caching breaks image  #badges](https://github.com/github/markup/issues/224#issuecomment-37663375)

To override the cache many server supports `Cache-Control` header in http response. It can be done as  `Cache-Control: no-cache`.  Setting Cache control to `no-cache` asks the server to "re-validate before serving this content". Although `Cache-Control` doesn't specify what it needs to "re-validate". To do that `Etag` is used.  Use of `Cache-Control` along with variable `ETag` can allow us to make the cache revalidate and reload content when necessary

## Expected Behaviour
 
Watchdog should be able to set `Cache-Control` and `ETag` variable in the response header

## Current Behaviour

Watchdog doesn't support any way to add an extra HTTP header 

## Possible Solution

**1. Add Cache-Control and ETag in Environments lists**
`Cache-Control` and `ETag` can be used for Environmental overrides like of `Content-Type` 

**2. Provide generic way to set any response header**
As header could be various and based on used needs, a more generic approach can be taken. 
One way could be by adding Response Header from Env variables which starts with `HttpR_`. 
i.e. Env `HttpR_Cache-Control=re-validate` would end up setting a `Cache-Control: re-validate` in the response header 
or
Have a single variable `Http_Response_Headers` like http query_string: `Cache-Control=re-validate& ETag=77726beb4af9335c974dc8cabfed27fb` which will be parsed using `url` package and add response header `Cache-Control: re-validate`, `ETag: 77726beb4af9335c974dc8cabfed27fb`

**Comment by alexellis** [comment]
@s8sg do you still have interest in this issue?

We cannot return arbitrary data or headers from the classic watchdog, but `Cache-Control` could be set to a one-time value via an environmental variable if you think that helps.

In the of-watchdog you can set whatever headers you like.

**Comment by s8sg** [comment]
@alexellis  `Cache-Control` alone is not enough to get the benefits. As we can't use dynamic value for either `Expires`, `Last-Modified` or `Etag`. I guess it better to take those use-case in `of-watchdog`. 

Although we might generate dynamic `Last-Modified`/`Etag` tag from the watchdog itself for each request, but not sure it thats a good idea
