### ISSUE TITLE
is that possible to return message before function finish?

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas#680]
I use faas to do a large time cost job. Since the job need 1.5 hours to finish, I want to return a receiving message to let caller know that the job is start. After job finish, I will trigger their webhook to process the result. I use nodeStdin sample to test the response flow. I found that the echo only return after function finish. I can not response first even I echo at beginning.

## Expected Behaviour

I want my job can still running but I can echo back the receiving message in the beginning

## Current Behaviour

the response message only return after job finish

## Possible Solution

is there a way to let watchdog know I want to return before job finish?
I have not study the watchdog source code so I can not sure it can be done

## Steps to Reproduce (for bugs)

1. use nodeStdin sample 
2. add a large time const work in handle function
3. echo message at beginning of job

## Context

I want to use faas to do a image processing job. But the processing time can not be finish in short time. I need to response first and callback webhook after job finish

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 14.04
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by iyovcheva** [comment]
Hi @rayhero ,
I suggest you to chain 2 functions asynchronously. You can find an example for chaining [here](https://github.com/openfaas/workshop/blob/27245090d09b1f63e3a0e33ce64b63132d6886f9/lab6.md) and async functions [here](https://github.com/openfaas/workshop/blob/4cf063d30807e81686a7df1b279ad451491207ae/lab5.md)

The additional function can invoke the original one and then return response, informing the watchdog that your function have started.

**Comment by iyovcheva** [comment]
@rayhero Did that work for you?

**Comment by iyovcheva** [comment]
Derek add label: question

**Comment by iyovcheva** [comment]
Derek close
