### ISSUE TITLE
Question: how to set secrets via the REST API

### ISSUE THREAD

**Issue by robertrbruno** [openfaas/faas#683]
## Expected Behaviour

I am registering a new function using the REST api to a k8s deployment.

Using the POST to /system/functions  and sending json in the body with the service, image, and secrets where secrets is an array with one string "regcred" which is a secret it the openfaas namespace for the docker repo creds.

I would have expected this to set the imagePullSecret for the deployment.

## Current Behaviour
The REST api succeeds but the secret is not being used as the imagePullSecret.  When I do a get on the function description there is no mention of the secret name either.

If I edit the deployment that is created by calling the REST call and manually add the imagePullSecret everything works.

**Comment by alexellis** [comment]
@robertrbruno I'd suggest you try using the `faas-cli` for this and then compare that with the JSON you are generating in your own submission to the endpoint.

**Comment by alexellis** [comment]
cc @LucasRoesler

**Comment by robertrbruno** [comment]
The type of the secret is kubernetes.io/dockerconfigjson  it was created using kubectl create secret docker-registry regcred ..

**Comment by alexellis** [comment]
@robertrbruno please can you follow the suggestion I gave before going any further.

> @robertrbruno I'd suggest you try using the faas-cli for this and then compare that with the JSON you are generating in your own submission to the endpoint.

Please confirm that the secret works when binding via the faas-cli (this is a normal use-case for us and we have tested it). If you have an error at that point then you may be using an old version of faas-netes or you may be configuring your secret in the wrong namespace.

**Comment by robertrbruno** [comment]
@LucasRoesler the secret is in the same namespace as the openfaas deployment which I thought is where it needed to be.   We named our namespace "openfaas".  Gatway version is 0.7.3.

@alexellis I'll do my best to test with faas-cli today.  Is there any easy way to see the json it produces if it does work?  I'd very much like to be able to use the REST api if at all possible.

**Comment by alexellis** [comment]
@robertrbruno I believe you will need to set your secrets in the openfaas-fn namespace.

I'm not sure why you are using 0.7.3 of the gateway (that implies that components will also be out of date) - please update to master.

If we don't hear from you this week confirming that you've tested with the CLI (something we know that works). I'll close this issue.

Thanks,

Alex

**Comment by alexellis** [comment]
I found no issues attaching and binding to a secret on Swarm, and we can bind to secrets successfully using the CLI with Kubernetes too. This means you're probably getting something wrong in your secret creation or your REST call.

Example:


```bash

docker secret create tester -
this is secret
kvg9148mi99z084tbghhriuji

curl 127.0.0.1:8080/system/functions --data-binary '
{
"image": "functions/alpine:latest",
"service": "check",
"secrets": ["tester"],
"envProcess": "xargs find",
"network": "func_functions"
}
'

curl 127.0.0.1:8080/function/check -d "/run/"
/run/
/run/secrets
/run/secrets/tester
```

**Comment by robertrbruno** [comment]
Thanks for all the follow-up.   I'll test tomorrow.

**Comment by alexellis** [comment]
Would also be good to check `kubectl get events openfaas-fn` - I believe this data is requested when raising an issue on faas-netes repo. If this issue is about faas-netes, it may make sense for you to close this issue and raise a new one there giving all the troubleshooting info.

**Comment by BurtonR** [comment]
derek close

**Comment by BurtonR** [comment]
@robertrbruno  I closed this issue as it seems you have resolved this with the information provided. If not, please feel free to comment and re-open (or open a new issue in the faas-netes repo)

**Comment by BurtonR** [comment]
Derek close
