### ISSUE TITLE
Proposal: UI Add a page for deploying functions

### ISSUE THREAD

**Issue by kenfdev** [openfaas/faas#684]
## Expected Behaviour

1. Click on the `Deploy New Function` button
2. Show a page for deploying a new function (rather than opening a modal) inside the single page app. 
3. Select a function from the store or fill in the information manually
4. Click the `Deploy` button
5. Go back to the functions list page

## Current Behaviour

1. Click on the `Deploy New Function` button
2. Open a modal 
3. Select a function from the store or fill in the information manually
4. Click the `Deploy` button
5. Close the modal

## Possible Solution

We can add a `router` for the single page app and the default page would be the same as current `/ui` . For the new functions page, we could move to `/ui/deploy` or `/ui/functions/new` or whatever fits and show a page for deploying a new function. The content could be the same as what we have inside the modal now.

#### Pros

* It's literally a single page app. Simple to have only one page to deal with. This is a big Pro.

#### Cons

Currently, I think it's okay but thinking about the future and additional features...

- Putting too much content inside a single modal gives it too much responsibility despite its small area. For example, adding the capability of editing environment variables (with dynamic rows) inside the modal would add additional complexity both in the ui and the implementation.
- The extra layer of modal possibly breaks the styles of the material design components which weren't intended to be used inside a tab which is inside a modal.
- It's hard to add another layer of information (e.g. popups or another modal). A modal above a modal is going to be confusing.

#### Pros

* Plenty of space compared to a modal. For example, we can add a `Advanced Options` section for additional input for functions (e.g. environment variables).
* It should reduce the possibility of breaking the material design component's css designs
* Because it's a flat page now, we can open a modal within the new page for additional information.

#### Cons

* UX change for people who've already used the current Gateway UI. Could introduce confusion for people who are used to it.
* An extra `router` module is needed for the single page app

**Comment by kenfdev** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Would you like to work on this?
