### ISSUE TITLE
Question on rolling update behaviour in swarm

### ISSUE THREAD

**Issue by lapwat** [openfaas/faas#686]
When performing a rolling update, the function is not callable during 10 seconds.

## Expected Behaviour
A rolling update should be transparent to the user.
The function should always be callable during a rolling update. The function should never be in "Not ready" state.
The old version should be accessible until the updated version is Ready.

## Current Behaviour
If you try to call the function during a rolling update, you get an empty response from curl.

## Steps to Reproduce (for bugs)

1. Create a new function in the language of your choice
2. Build & deploy
3. Change `handler.lang` with a new response message
4. Build & deploy
5. Call the function with `curl url` multiple time during rolling update
=> At some point you get an empty response

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.12.1-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by iyovcheva** [comment]
Hi @lapwat, do you push the image to a Docker registry?

**Comment by rgee0** [comment]
@lapwat can you provide the output from `docker service ls | grep -E 'func_faas-swarm|func_gateway'` please?

**Comment by alexellis** [comment]
You don’t say what version of OpenFaaS you are using. I would recommend moving to master - the start first strategy does not cause 10 sec downtime.

**Comment by lapwat** [comment]
@alexellis I was in 0.7.7, I tried with master & problem resolved :)
Now the behaviour is as expected.
```sh
$ for i in {1..10}; do curl localhost:8080/function/test; sleep 1; done
Thank you
# deploying update
Thank you
Thank you
Thank you
Thank you
Very much
Thank you
Very much
Very much
Very much
```

@rgee0 FYI
```sh
$ docker service ls | grep -E 'func_faas-swarm|func_gateway'
6j7vtipbttxe        func_faas-swarm     replicated          1/1                 functions/faas-swarm:0.2.2         
8s1g4d0jmawe        func_gateway        replicated          1/1                 functions/gateway:0.7.3            *:8080->8080/tcp
```

Thank you all for your reactivity

**Comment by alexellis** [comment]
@lapwat the policy for updating changed from StopFirst to StartFirst for Docker Swarm. You can find more release notes/PRs etc over on the repo - https://github.com/openfaas/faas-swarm

Also 🎉 👍 😄
