### ISSUE TITLE
Proposal: Move Basic Auth into gateway code

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#687]
We currently secure the OpenFaaS administrative API route `/system/` by fronting it with Basic Auth through a HTTP Reverse Proxy.

If we implement basic auth within the the `/system/` route we can decouple this implementation detail.

The implementation may require the user to create a secret using `kubectl` / `docker swarm` before deploying.

We should also look at alternative options.

Do not forget faas-netesd / openfaas-operator / faas-swarm.

**Comment by alexellis** [comment]
Test

**Comment by alexellis** [comment]
Some interesting ideas on different auth strategies: https://facundoolano.wordpress.com/2013/12/23/my-take-on-restful-authentication/

**Comment by cpitkin** [comment]
@alexellis Which auth strategy in that list did you have in mind? Starting out with Basic Auth then adding more later might not be a bad idea.

**Comment by alexellis** [comment]
Would like input from the community on this. We've seen basic auth offer usefulness and simplicity, but is there more we could do?
