### ISSUE TITLE
Proposal: Change secrets to mount in a specialized subfolder

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#692]
To address various issues that we have recently seen occur with secrets (mostly in Kubernetes) and to maintain cross-compatibility between Swarm and Kubernetes, we should mount all secrets to  `/var/openfaas/secrets`.

## Expected Behaviour

When a user indicates that a secret is required, we should specify that the orchestration layer mounts that secret inside `/var/openfaas/secrets`.  For example, in Swarm, if the user has a secret `postgresuser`, then inside the function container, they secret file would be found at `/var/openfaas/secrets/postgresuser`.

Internally, the faas provider would be setting the mount point via their respective APIs:

* for Swarm, we would use the `source=%s,target=%s` notation as described here https://docs.docker.com/engine/swarm/secrets/#intermediate-example-use-secrets-with-a-nginx-service
* for Kubernetes this would require setting the `mountPath` appropriately, see https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

## Current Behaviour

This behavior mimics the current behavior of mounting the secrets at `/run/secrets` but will avoid conflicts with how other systems expect that folder to behave.  

## Context

This provides a solution to bugs like openfaas/faas-netes#188 in which the Kubernetes cluster fails to launch the function container because there is a permissions issue with the `/run/secrets` folder.

One of the goals in this proposal is to continue to preserve a consistent experience between Kubernetes and Swarm for function authors.  Currently, and continuing with this proposal, secrets will also be available in the same location and assuming that they do not use multiple files per Kubernetes secret, then the function can access the secrets in exactly the same way in both Kubernetes and Swarm.

**Comment by LucasRoesler** [comment]
Some comments on the actual implementation, I am pretty sure that for both swarm and k8s, this is a one line change.  

In swam, we would just need to update https://github.com/openfaas/faas-swarm/blob/master/handlers/deploy.go#L345 to use a formatted string with the `source=%s,target=/var/openfaas/%s` instead of the secret name, like it currently does.  Essentially we would be piggybacking on the swarm cli parsing, which we already do anyway. 

In k8s, we would simply update the `mountPath` here https://github.com/openfaas/faas-netes/blob/master/handlers/secrets.go#L98

**Comment by LucasRoesler** [comment]
While implementing this change in `faas-swarm` I noticed something that will become broken with this change.  In `faas-swarm` we implicitly supported the entire docker secrets command line configuration for secrets.  In particular, it was possible to use the `source=,target=` notation as the secret and faas would be able to handle that correctly.  I don't think we ever explicitly stated support for this behavior, but it is worth highlighting that it was possible and will break in my current implementation.

**Comment by alexellis** [comment]
Derek close: released
