### ISSUE TITLE
Proposal: Adjust Response Codes of the Rest API for Create / Update

### ISSUE THREAD

**Issue by Templum** [openfaas/faas#693]
The api routes for create and update as defined [here](https://github.com/openfaas/faas/blob/master/api-docs/swagger.yml) in the official swagger documentation do return an inappropriate HTTP Status code. 

Create and Update currently return an  [200 - OK](https://httpstatuses.com/200) which indicates that the operation was already completed. But in fact at that point we only started / created a deployment, which may even fail. So a better status code would be [202 - Accepted](https://httpstatuses.com/202). 

## Important Note
This proposal might affect users and test that check for the returned status code. But besides that it should be a rather minor modifcation.

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by Templum** [comment]
@ericstoekl I actually can confirm that behaviour for K8S it returns 202. Also the faas-cli checks for both. Guess the API implementation is overall very inconsistent, at least based on swagger.

**Comment by alexellis** [comment]
I would not quite go a strong as that Eric. I would say 202 is fine if you want to update across the board the please go ahead.

**Comment by alexellis** [comment]
@Templum do you want to update the Go code for this in faas-swarm and faas-netes?

**Comment by alexellis** [comment]
I opened an issue for faas-swarm and faas-netes for you to work on.

**Comment by Templum** [comment]
Thanks for setting up the issues, after the ready only fs I will move over to those.

**Comment by alexellis** [comment]
Derek close: fixed
