### ISSUE TITLE
Update the Swagger API Documentation

### ISSUE THREAD

**Issue by Templum** [openfaas/faas#694]
Currently, there is an swagger documentation available [here](https://github.com/openfaas/faas/blob/master/api-docs/swagger.yml), hower it is not update and also not complete. 

For example both create and update return an 400 - Bad Request in case the provided information where not in the correct format. Which is not displayed. 

Definition are only partially available and also lack the marking of required fields. 

There is also som improvements options for example the field `network` of the `CreateFunctionRequest` could show `func_functions` as defaults, as this field is even only required in an docker envrioment. 

### Note
I would be willing to work on that issue and update the documentation accordingly.

**Comment by alexellis** [comment]
Hi Simon, thank you for raising this. I'd support you working on this and I think it will help the community going forward too.

**Comment by Templum** [comment]
Based on feedback in #693 it seems that the return types are different based if the provider is K8S or Swarm.

**Comment by ivanayov** [comment]
This looks completed.
Waiting for @Templum to confirm before closing.

**Comment by Templum** [comment]
Sorry for the delay,  it is fixed. Going to close the issue now
