### ISSUE TITLE
Controlling autoscaling with Kubernetes instead of OpenFaaS

### ISSUE THREAD

**Issue by faromero** [openfaas/faas#696]
I would like to control the behavior of how each replica set scales based on criteria passed to `kubectl autoscale` instead of OpenFaaS's alert system. However, it seems that Kubernetes autoscale is conflicting with OpenFaaS's even though I believe I turned off the OpenFaaS alerts.

## Expected Behaviour
The autoscaling policy should only be managed by Kubernetes (via HPA) if the OpenFaaS alerts are turned off. Thus, if I have configured minimum and maximum replicas for a particular ReplicaSet via `kubectl autoscale`, the OpenFaaS autoscale should not attempt to terminate replicas or spawn new ones.

## Current Behaviour
Based on #541, I removed the alert from [AlertManager's configuration](https://github.com/openfaas/faas-netes/blob/master/yaml/prometheus_config.yml#L40-L50) _and_ told OpenFaaS to [stop processing it](https://github.com/openfaas/faas-netes/blob/master/yaml/alertmanager_config.yml#L27-L31). I then configure an OpenFaaS ReplicaSet to have a minimum of 2 replicas and a maximum of 5 replicas via `kubectl autoscale`. Then, every time a new replica is created, it is immediately terminated, which "infinitely" occurs because the two policies are seemingly in conflict with each other: Kubernetes wants to create a second replica but OpenFaaS for some reason only wants one alive.

## Context
Research project on FaaS

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): **Docker 1.13.1**

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? **Kubernetes (FaaS-netes)**

* Operating System and version (e.g. Linux, Windows, MacOS): **Ubuntu 16.04**

Thank you for your help, and please let me know if any additional information would be useful.

**Comment by stefanprodan** [comment]
I've tested the HPA setup for the [OpenFaaS Kubernetes Operator](https://github.com/openfaas-incubator/openfaas-operator) with Alertmanager scaled to 0 and it works as expected. Can you please try out the operator and see if that works? Here is an example https://github.com/stefanprodan/openfaas-flux#manage-openfaas-functions-and-auto-scaling-with-weave-flux

Thanks

**Comment by faromero** [comment]
Hi Stefan,
Thank you for your response, I will try to test this on the operator.
I am new to OpenFaaS and Kubernetes, but what does the operator do that is different from just running FaaS-netes with the FaaS-CLI, and is using HPA instead of the AlertManager not possible without the operator?

Thanks again for your assistance, I will see if I can get it working with the operator.

**Comment by alexellis** [comment]
@faromero Please see the notes on AlertManager - http://docs.openfaas.com/architecture/autoscaling/

You will not get scaling behavior from OpenFaaS (AlertManager) if you remove the alert or if you scale AlertManager to zero replicas. There is nothing else in the deployment which would scale your functions.

**Comment by faromero** [comment]
@alexellis Thank you for the response and the helpful link!
From the link, it states at the bottom that you can scale using the HPA instead. My desired behavior is to control the scaling myself based on custom HPAs and _not_ have OpenFaaS scale my functions (hence my efforts to disable the alerts). However, currently it seems that even if I disable the alerts (i.e. comment out the lines in the two _yml_ from my original post), and start up an HPA, OpenFaaS is still trying to manage the scaling behavior of the functions.

**Comment by stefanprodan** [comment]
@faromero have you restarted the Alertmanager pod after changing the config?

**Comment by faromero** [comment]
@stefanprodan, thanks for the suggestion. After I changed the config, I applied the changes to the pod via the following command: `kubectl apply -f ./namespaces.yml,./yaml`. Does this apply the update to the pod or do I need to run another command to restart it in order for the changes to take effect?

**Comment by stefanprodan** [comment]
The pod is not restarted since nothing changed inside the Deployment object. The Alertmanager config is stored as a ConfigMap. You can delete the running pod or call `/-/reload` see https://github.com/prometheus/alertmanager/issues/353

**Comment by faromero** [comment]
That's great to know. I did kill the pod, updated the config, and then brought the pod back up, but I am still getting the same behavior. Just to confirm: if I comment out lines 40-50 in prometheus_config.yml (highlighted [here](https://github.com/openfaas/faas-netes/blob/master/yaml/prometheus_config.yml#L40-L50)), OpenFaaS should not receive an alert to take action on scaling, correct?

**Comment by stefanprodan** [comment]
Ah sorry you need to restart the Prometheus pod not Alertmanager.

**Comment by faromero** [comment]
I deleted the entire setup (`kubectl delete -f ./namespaces.yml,./yaml`) and then redeploying after making the change (`kubectl apply -f ./namespaces.yml,./yaml`), yet I _still_ see the conflict occurring (a second function pod is deployed, and then immediately killed). The logs from the AlertManager or Prometheus pods do not seem to indicate any activity related to this behavior (not sure if they are suppose to).
Thanks again for your help and the quick responses.

**Comment by alexellis** [comment]
Please give us step by step instructions of what to type in exactly to reproduce your problem. We'll also need to know how you are generating high load.

**Comment by faromero** [comment]
@alexellis thanks for your response. I am not generating a high load (yet), what I am doing is setting a minimum (2) and maximum (doesn't matter but let's say 5) number of replicas in my autoscale configuration. Hence, HPA always wants 2 replicas of a particular pod but OpenFaaS doesn't see a need for the second replica so it kills it (despite me trying to tell it otherwise). Here are the steps to reproduce this behavior:
1) Set up a remote Kubernetes cluster by following [these](https://blog.alexellis.io/your-instant-kubernetes-cluster/) instructions (great blog by the way). In my case, there is one master and one remote worker.
2) Set up `faas-netes` per the instructions [here](https://docs.openfaas.com/deployment/kubernetes/). Before running `kubectl apply -f ./namespaces.yml,./yaml` inside of the `faas-netes` directory, I go into `./yaml` and comment out lines 40-50 in _prometheus_config.yml_ (highlighted [here](https://github.com/openfaas/faas-netes/blob/master/yaml/prometheus_config.yml#L40-L50)). I then run the _apply_ command from above.
3) I deploy the sample functions in the `faas-cli` directory (described in _stack.yml_) and use the gateway flag for my remote worker. At this point, I can invoke the functions successfully.
4) Now, I run the following command: `kubectl autoscale rs <name of desired function's ReplicaSet> ---min=2 --max=5`. I have also tried it with a `--cpu-percent` flag and deployed functions with resource limits as well as deployed a metrics server, but the behavior is the same.
5) After a couple of seconds, if I run `kubectl describe hpa -n openfaas-fn`, I can see that it increased the replica count to 2. If I check `kubectl get pods -n openfaas-fn`, I see that the new pod has a status of "Terminating". This behavior proceeds to ping-pong (i.e. if I run `kubectl describe hpa -n openfaas-fn` again after a couple of seconds, I can see it tried to deploy another replica pod to replace the one that was terminated).

Apologies for the long post; I wanted to make it as detailed as possible. Thanks again for all assistance and insight.

**Comment by alexellis** [comment]
Thanks for the instructions.. So I ran through your instructions and found I could reproduce the error.

I think the problem is the you've modified the ReplicaSet and not the Deployment.

Deployment info:

```
kubectl describe -n openfaas-fn deploy/figlet
Name:                   figlet
Namespace:              openfaas-fn
CreationTimestamp:      Thu, 24 May 2018 17:26:53 +0000
Labels:                 faas_function=figlet
Annotations:            deployment.kubernetes.io/revision=1
Selector:               faas_function=figlet
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  0 max unavailable, 1 max surge
```

RS info:

```
Name:           figlet-6f9d88968
Namespace:      openfaas-fn
Selector:       faas_function=figlet,pod-template-hash=295844524
Labels:         faas_function=figlet
                pod-template-hash=295844524
Annotations:    deployment.kubernetes.io/desired-replicas=1
                deployment.kubernetes.io/max-replicas=2
                deployment.kubernetes.io/revision=1
Controlled By:  Deployment/figlet
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 1 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       faas_function=figlet
                pod-template-hash=295844524
  Annotations:  prometheus.io.scrape=false
```

Why don't you try setting up HPA on the deployment like in Stefan's guide? https://github.com/stefanprodan/openfaas-flux#manage-openfaas-functions-and-auto-scaling-with-weave-flux

Another example working with deployments: https://stefanprodan.com/2018/kubernetes-scaleway-baremetal-arm-terraform-installer/#horizontal-pod-autoscaling

This works for me if you want to use the CLI instead of YAML:

```
kubectl autoscale deploy/figlet -n openfaas-fn --min=2 --max=5 

Every 0.5s: kubectl get pods -n openfaas-fn                                                                                                             Fri May 25 20:51:53 2018

NAME                                 READY     STATUS    RESTARTS   AGE                 
figlet-6f9d88968-49cbf               1/1       Running   0          42s                 
figlet-6f9d88968-84h5l               1/1       Running   0          1d  
```

**Comment by alexellis** [comment]
Derek close: not an issue

**Comment by faromero** [comment]
Fantastic, that did the trick! Thanks so much @alexellis and @stefanprodan!
