### ISSUE TITLE
Is there support for Cloud Events?

### ISSUE THREAD

**Issue by moshe0076** [openfaas/faas#701]
Cloud events https://cloudevents.io/ failed to trigger an OpenFaaS function. 
## Expected Behaviour
Cloud Events are handheld by the OpenFaaS function natively. 

## Current Behaviour

I was trying to trigger an OpenFaas function from an Event Gateway (https://github.com/serverless/event-gateway), but the OpenFaaS function cannot handle the event. 
## Possible Solution

Add support for Cloud Events. Make the event available to the function handler so the event context can be used inside the function.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 17.03.2-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 1.8 - rancher/k8s:v1.8.5-rancher4
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04.3 LTS (4.4.0)
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
We have support for CloudEvents, no changes are required in the function. FYI no "serverless event-gateway" is required either - Azure publishes events in this format via its EventGrid.

@johnmccabe can you share your example function please?

**Comment by johnmccabe** [comment]
I'll push it up later today when I get home.

**Comment by alexellis** [comment]
Thanks please link to it here when ready. 

Any tips for the issue poster?

**Comment by alexellis** [comment]
@johnmccabe please provide an update and link to your blog or GitHub repo for @moshe0076 

The event gateway is not required for OpenFaaS, we have an API Gateway built-in and no changes are needed to handle CloudEvents.

**Comment by johnmccabe** [comment]
https://github.com/johnmccabe/cloudevents-slack-demo - blog post isn't ready.

**Comment by alexellis** [comment]
Another example:

https://github.com/rgee0/cloudevents-interop-demo
