### ISSUE TITLE
Proposal: Add new metrics for the functions

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas#703]
Add more useful metrics for the functions like.

```
1. Number of 2XX requests per second
2. Number of Non-2XX requests per second
3. Distribution of response time for requests
```

## Expected Behaviour

 We can expose these metrics through Gateway.

## Current Behaviour

Right now we are having metrics like `replicas`, `invocationCount`  for each function. We can also expose these new metrics. 

## Possible Solution

All of these metrics are already there in Prometheus, we need to expose these metrics through the gateway. 

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Prometheus provides cloud-native instrumentation and monitoring. @ericstoekl why would you deprecate Prometheus?

**Comment by ericstoekl** [comment]
Ok, sounds like Prometheus will cease to be used for the autoscaling functionality, but we will continue to use it for monitoring. Makes sense.

**Comment by alexellis** [comment]
@burtonr @viveksyngh @stefanprodan 

What could we add in the API that would let us draw some graphs in the UI such as RED metrics for the last period i.e. 15mins?

**Comment by viveksyngh** [comment]
As per my understanding, we can call Prometheus Range queries API's to scrape these metrics based on timestamps for a specified interval (say last 15 minutes) and then we can pass that data to frontend which can we used for plotting graphs in UI. 

https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

**Comment by burtonr** [comment]
Having more metrics available through the API means that we could make debugging and monitoring function performance possible from the OpenFaaS UI directly! 

If you use the UI for development locally, you could easily tell if your function was slow, or had a memory leak, etc.
