### ISSUE TITLE
Wrong env name for ack_wait in stack definition file

### ISSUE THREAD

**Issue by klingenm** [openfaas/faas#704]
https://github.com/openfaas/faas/blob/ab2aa14c4837626ddfef406a2c9ed5903f7b4e8a/docker-compose.yml#L91

According to https://github.com/openfaas/nats-queue-worker/blob/master/queue-worker/main.go#L206 it should be `ack_wait` not `ack_timeout`.

**Comment by alexellis** [comment]
I think you're right. We updated the name and the config for Kubernetes but possibly not for swarm. https://github.com/openfaas/faas-netes/blob/master/yaml/queueworker.yml

**Comment by alexellis** [comment]
Looks like the docs need an update too http://docs.openfaas.com/deployment/troubleshooting/#timeouts-asynchronous-invocations

**Comment by alexellis** [comment]
I think everything is updated now. @klingenm can you confirm please?

**Comment by viveksyngh** [comment]
I think this one also needs an update in `openfaas-cloud` repo documentation. I have created a PR for that.  https://github.com/openfaas/openfaas-cloud/pull/66

**Comment by alexellis** [comment]
Thank you, that's merged now. Any mentions in the workshop?

**Comment by alexellis** [comment]
Derek close: resolved
