### ISSUE TITLE
RESTful URL Parameters

### ISSUE THREAD

**Issue by ray211** [openfaas/faas#710]
I am very new with OpenFaas. I created a raspberry pi cluster following Alex's [blog](https://blog.alexellis.io/your-serverless-raspberry-pi-cluster/). The cluster is working and I managed to create my first python function per the [instructions](https://blog.alexellis.io/first-faas-python-function/). 

I created the Hello Python example and got it working using the Gateway UI. However, if I invoked the method using the Gateway URL it will not return a result.

## Expected Behaviour

If I invoke the method using the Gateway URL I would expect a response. For example, if my Gateway URL was 192.168.1.100 then using
http://192.168.1.100/function/hello-python?q=test
should respond with
Hello! You said: test

## Steps to Reproduce (for bugs)

1. Follow instructions for building [RPI cluster](https://blog.alexellis.io/your-serverless-raspberry-pi-cluster/).
2. Follow instructions for building first [Python function](https://blog.alexellis.io/first-faas-python-function/).
3. Using a browser navigate to Gateway URL and type the following: http://gateway:8080/function/hello-python?q=test

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.05.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Raspbian Version 9

* Link to your project or a code example to reproduce issue:
Python Version 2.7.13

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by iyovcheva** [comment]
Derek add label: question

**Comment by iyovcheva** [comment]
Derek add label: support

**Comment by ray211** [comment]
Sorry for the typo, yes I tried both methods without any luck.

After reading the workshop documentation, specifically [lab 6](https://github.com/openfaas/workshop/blob/master/lab6.md) I found the value using the environment variable: Http_Query. However, changing the code and the URL string breaks the Gateway UI invoke.

**Comment by alexellis** [comment]
Ray what's the specific problem you're encountering? The function doesn't work at all?

**Comment by alexellis** [comment]
Derek close: inactive

**Comment by pandres95** [comment]
This issue is related #815
