### ISSUE TITLE
Help wanted: AWS SNS blog post

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#712]
Eric stated that at a recent meet-up someone asked whether AWS SNS can be deployed on OpenFaaS.

This can be done even within the function as demonstrated by @johnmccabe with his CloudEvents demo. We need to put together a short blog post / tutorial for AWS to show how easy this is and share that with our community.

I'd like someone to volunteer to write a short blog post showing how to subscribe to an SNS topic and process a message. Assume that OpenFaaS is already set up on Kubernetes with a public IP. 

Alex

**Comment by affix** [comment]
I'm on it :)

**Comment by alexellis** [comment]
Thank you 👍 let us know if you have questions or run into any issues etc.

**Comment by alexellis** [comment]
Bonus points if it can run on the new staging OpenFaaS Cloud where we have sealed secrets available too.

**Comment by affix** [comment]
had some issues with my setup through the week, will get this done by Tuesday

**Comment by affix** [comment]
got an SNS Subscribe handler working, Just does an echo at the moment

https://github.com/affix/OpenFaaS-SNS

**Comment by alexellis** [comment]
That's a good first step, thank you. Looking forward to reviewing the blog post before it goes live.

**Comment by alexellis** [comment]
Hi @affix what do you have around this now?

**Comment by affix** [comment]
So far,

- Subscribe to SNS Topic (HTTP(s))
- Handle Notifications from S3
  - Trigger another function based on the notification
    - Trigger OCR on an image in an S3 Bucket

**Comment by alexellis** [comment]
@affix what is the status of this? Thanks

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Unfortunately if this hasn't happened in 10 months I don't think it will happen at all.
