### ISSUE TITLE
Functions are accessible if we add slash (/) at the end of url

### ISSUE THREAD

**Issue by tarunmangukiya** [openfaas/faas#714]
Let's say our function name is `download`, and we access that function using GET `http://localhost:8080/function/download` then it gives proper response. But if we access it using `http://localhost:8080/function/download/` then it throws 502 server error.

## Expected Behaviour
I think both of the urls are technically same and both of them should work.

## Current Behaviour
It throws 502 server error. I've checked gateway logs and found that gateway upstreams it to container as `http://download/:8080/function/download`, there is trailing slash.

## Possible Solution

Both urls should work.

## Steps to Reproduce (for bugs)

1. Create any function which provides response in GET request, example, `download`
2. Access it from `http://localhost:8080/function/download`
3. Access it from `http://localhost:8080/function/download/`
4. Check the outputs

## Context

I was trying to keep my server env file neat. There were slash at the end in some urls, as we're using them for internal proxying and http requests. So, I created all the urls with slash at the end.

**Comment by affix** [comment]
I don't feel this is a bug, more of a proposal.

However I don't see a real benefit to supporting a trailing slash in the URL as this is something that can be handled by your load balancing software (if using any).

A trailing slash would break get params and theres no real benefit to supporting both URL schemed.

making it "neat" doesn't seem like a valid reason for this change.

**Comment by alexellis** [comment]
Can we validate this with the normal classic watchdog? And the latest gateway.

Which docker image are you using?

**Comment by alexellis** [comment]
I reproduced the problem on Kubernetes with the nodeinfo function. It used to work with a trailing slash, so it should still do that now. I think it may be a regression around the direct functions access code. I'd like help looking into this.

**Comment by LucasRoesler** [comment]
I got it

**Comment by affix** [comment]
Tested this with the latest gateway on k8s using figlet

```
➜  ~ curl -d "Hello World" https://<hidden>/function/figlet
 _   _      _ _        __        __         _     _
| | | | ___| | | ___   \ \      / /__  _ __| | __| |
| |_| |/ _ \ | |/ _ \   \ \ /\ / / _ \| '__| |/ _` |
|  _  |  __/ | | (_) |   \ V  V / (_) | |  | | (_| |
|_| |_|\___|_|_|\___/     \_/\_/ \___/|_|  |_|\__,_|

➜  ~ curl -d "Hello World" https://<hidden>/function/figlet/
 _   _      _ _        __        __         _     _
| | | | ___| | | ___   \ \      / /__  _ __| | __| |
| |_| |/ _ \ | |/ _ \   \ \ /\ / / _ \| '__| |/ _` |
|  _  |  __/ | | (_) |   \ V  V / (_) | |  | | (_| |
|_| |_|\___|_|_|\___/     \_/\_/ \___/|_|  |_|\__,_|
```

Also tested using my faas-ruby-login function

```
➜  ~ curl -d '{"username": "affixx", "password": "TestPassword"}' https://<hidden>/function/faas-ruby-login
{'username': 'affixx', 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE1MjgzMjIwOTIsImlhdCI6MTUyODMyMjA5MiwiZXhwIjoxNTI4MzM2NTAyLCJ1c2VyIjp7ImVtYWlsIjoiY2FvbnRhY3RAa2VpcmFuLnNjb3QiLCJpZCI6IjYiLCJmaXJzdF9uYW1lIjoia2VpcmFuIiwibGFzdF9uYW1lIjoic21pdGgiLCJ1c2VybmFtZSI6ImFmZml4eCJ9fQ.hUWpId_QKbPiZGQeQMFdSSoFU6V693aE6UJG7Xn9XK3e2xFHHbWLgmlHyI3eKEDx7Lb-RY1Usninxp2FhLT6kbbFwTqr-6Kqm6rY5ZqYAUBkZXZ4KR64Aon9KUBHgcQRn9EECJttovfmIN3nR5AEmkCndtWOBInNfP3r9U7Rwblv4b0I1lGR2w-LCqofJCaPvvyHcSIYwGmJ4RdMmzRp0iRs4vlkBwYaGnK395OkMK2ApQqe5ij9kETCw_OaviBLIcKOffUWA3Fzad2GdOprVC1ejo1pQPFfYFJpmespkivnwwvZyIUczbbDmpXWVVU7x-jWemKlX6D38fbDu_qCwg'}
➜  ~ curl -d '{"username": "affixx", "password": "TestPassword"}' https://<hidden>/function/faas-ruby-login/
{'username': 'affixx', 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE1MjgzMjIwOTQsImlhdCI6MTUyODMyMjA5NCwiZXhwIjoxNTI4MzM2NTA0LCJ1c2VyIjp7ImVtYWlsIjoiY2FvbnRhY3RAa2VpcmFuLnNjb3QiLCJpZCI6IjYiLCJmaXJzdF9uYW1lIjoia2VpcmFuIiwibGFzdF9uYW1lIjoic21pdGgiLCJ1c2VybmFtZSI6ImFmZml4eCJ9fQ.BGW7oaMqTzmdg_psXPn3K4NGuw-AKGBm2NAfpVhu9ptZxmVT0NGSftEXy1UwlBZZ7uH0QxQtyiqc6yIZArES3cgFCmbl0Fi8aMls2MCmwYXPRgf8UMaPvppgTRJMPQQErrF_dl0llzZ_It7kgjLlvxT1oovQ0gWEdqmCveUufRb-7W0pLIJr8fXEuxeobfB3ByYzvAuY2Xws0x-LoAQ014YihcQUN7Is0A76TLBMygWF7pQFfwCQ8QstULVdBm8wX-eg3pkjdDmZRpDgUxrNwW1ZAyuCBgz9S5YVP-1sqI4asPCCFifGEONi8P-eKH2Fg4L3WJSrDZIz7V80-xf9Iw'}
```
