### ISSUE TITLE
Proposal: Ability to add extra headers in function

### ISSUE THREAD

**Issue by tarunmangukiya** [openfaas/faas#715]
We're doing image resizing on the fly with OpenFaaS and we want to add extra headers such as cache control and last updated in the response. Thus the images will be cached in the user's browser saving time and bandwidth.

### Headers required
- `Cache-Control`
- `Expires`
- `Pragma`

**Comment by BurtonR** [comment]
@tarunmangukiya There is already a way to dynamically add HTTP headers to the request/response per function by creating and reading the environment variables as `Http_<your_header_name_here>`

Please see the example in the workshop: https://github.com/openfaas/workshop/blob/master/lab4.md#use-http-context---querystring--headers

This is also explained in the watchdog readme: https://github.com/openfaas/faas/blob/7f6295c9cff2f9f6584fd33327615e26851c31b2/watchdog/README.md#working-with-http-headers

**Comment by tarunmangukiya** [comment]
@BurtonR But here in watchdog, there's no such variables shown.
https://github.com/openfaas/faas/tree/master/watchdog

**Comment by BurtonR** [comment]
Perhaps the wording there needs updated, but here:

> Headers and other request information are injected into environmental variables in the following format:
>
> The X-Forwarded-By header becomes available as Http_X_Forwarded_By

This is saying that environment variables starting with `Http_` are interpreted to/from HTTP headers.

A better explanation can be found in the workshop though.

In your case, you can set the environment variable `Http_Cache_Control` to return the `Cache-Control` header. And so on for the others you have listed

**Comment by tarunmangukiya** [comment]
Added `Http_Cache_Control: "public, max-age=31536000"` in `stack.yml`. But it doesn't respond with the specific header.

**Comment by alexellis** [comment]
@tarunmangukiya please be clear about what you want.

To read these headers from incoming requests or

To set these headers on outgoing responses

**Comment by tarunmangukiya** [comment]
I want to set these headers in the outgoing response.

**Comment by alexellis** [comment]
So you'll need to look into the of-watchdog for that, or do it at your reverse proxy layer.

http://docs.openfaas.com/architecture/watchdog/#of-watchdog

Alex

**Comment by alexellis** [comment]
I'm going to close as resolved, but feel free to keep commenting.
