### ISSUE TITLE
Docs: write docs page on scheduled jobs with K8s

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#719]
We need to document scheduled jobs in the docs at GitHub.com/openfaas/docs

## Task

Write a docs page on scheduled jobs with K8s. Use Stefan's approach as a basis and state that this is only for Kubernetes.

https://github.com/stefanprodan/openfaas-flux#manage-openfaas-cron-jobs

Alex

**Comment by alexellis** [comment]
Stefan would be best to do this but I think he's quite busy this week. @johnmccabe you're experienced with K8s.. could you pick this up? @LucasRoesler this could also be useful reference material for your reference if you have capacity to pick up.

**Comment by LucasRoesler** [comment]
I will take a quick stab at this today, using Stefan's  page as a reference

**Comment by LucasRoesler** [comment]
I created a quick walkthrough that uses Stefan's example as its basis. See openfaas/docs#35
