### ISSUE TITLE
Request: Do you have a template for R functions?

### ISSUE THREAD

**Issue by JonathanBowker** [openfaas/faas#720]
Do you have a template for R functions?

**Comment by iyovcheva** [comment]
Hi @JonathanBowker 
There isn't a template, but [here](https://github.com/openfaas/faas/tree/master/sample-functions/BaseFunctions/R) is a sample function you could reuse.

You're also welcome, if you wish to create a custom template following these [docs](http://docs.openfaas.com/cli/templates/#40-customise-a-template)

**Comment by alexellis** [comment]
Sounds good to me @iyovcheva, @JonathanBowker if you need anything more please feel free to comment or re-open the issue.

We've given a sample R Dockerfile you can build into an OpenFaaS function and linked to the docs where you can create your own template (this will be hosted in your GitHub repo and fetched via `faas-cli template pull`.)

**Comment by psolymos** [comment]
Just a note for people looking for an R template for OpenFaaS: https://github.com/analythium/openfaas-rstats-templates
