### ISSUE TITLE
Proposal: allow slashes in function names to provide namespacing

### ISSUE THREAD

**Issue by shaunc** [openfaas/faas#730]
Currently, when you try to deploy a function with a slash in it, you get an error. It would be quite
useful to be able to use "/" to group functions into namespaces (and sub ... namespaces), so functions for a particular service could bee foo/, then for instance foo/stats/ could be monitoring functions and foo/tests/ could be testing functions, as well as foo/bar/... for functions within "foo" relating to "bar" resources, etc.

## Expected Behaviour

```
$ faas deploy --name a/b/c

Deployed. 200 Ok.
URL: http://127.0.0.1:8080/function/a/b/c
```

## Current Behaviour

```
$ fass deploy --name a/b/c

Unexpected status: 400, message: Deployment error: Error response from daemon: rpc error: code = InvalidArgument desc = name must be valid as a DNS name component
```

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

Docker for Mac: Version 18.03.1-ce-mac65 (24312)

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):

Mac

**Comment by alexellis** [comment]
I'm going to sum this up as a request for (soft or hard) multi-tenancy, please comment if that's not what you want.

## Existing solution

We already have a solution for this "namespacing" suggestion and you're quite right that a `/` is an illegal name for a Swarm or Kubernetes service. We map directly to the function name so you need to use a valid character as a separator.

We are grouping functions by namespace with a prefix of `-` plus metadata in the deployment labels.

Check out the OpenFaaS Cloud project for more - via its router it enables sub-domain access for users. Example:

https://alexellis.openfaas-cloud.com/echo-function

OpenFaaS Cloud provides other enhancements / functionality to help separate functions such as network namespace configurations for the Kubernetes CNI driver.

http://docs.openfaas.com/openfaas-cloud/intro/

If you absolutely want to type in: "domain.com/user/function" and get that mapped onto OpenFaaS you could fork the router component of OpenFaaS Cloud and create that URL scheme, just remap to a convention you're happy with like we've done.

I'm going to close the issue but please feel free to keep commenting and tell us more about why you need this so we can consider your requirements better.

Alex

**Comment by alexellis** [comment]
Derek close: existing feature

**Comment by shaunc** [comment]
Thanks for the reply. I'll have to study openfaas-cloud to see how it works. (nb the first link to "echo-function" is broken.)

We are working on a set of functions that provide (among other things) auth and a P2P distributed hashtable (loosely based on chord). We would like to support plugins that extend the functionality, and want a mechanism so that (modulo plugin name) their functions don't clash. As a first pass, we've used two dashes "--" as a namespacing separator, but it makes for ugly names, and it would be convenient to allow relative paths for function-to-function calls within a plugin.

As you say -- it may be easy to do by forking the router -- still have to look at it. Would you be interested, potentially, in a PR that mapped names with "/" to names with "--"?
