### ISSUE TITLE
Completely bock UI but allow function calls?

### ISSUE THREAD

**Issue by nelfer** [openfaas/faas#731]
So I've successfully used OpenFaaS to create integration points between internal applications. Congratulations on making such a great product!

Now my predicament is another: I want to use OpenFaaS for microservices for a software/site that will be exposed to people outside my company. Think for example AJAX calls to do some processing.

The issue is that the UI runs in the same port as the function execution (as far as I know).

Is there a way to disable the UI completely but leave the functions open for execution? I can protect the functions by validating secrets.

Using basic authentication doesn't work for this, because in order to call the function, I must pass the basic authentication credentials. Anyone that looks at the URL can grab them and enter the UI, remove functions, add functions or do some other kind of mischief.

So maybe the question is: How can I expose my functions to be used by a public site, but don't expose the UI?

Thanks for the help!

P.S. I quickly saw the compose files and saw that there's a "function provider url". Is it as simple as exposing that service instead of the gateway?

**Comment by nelfer** [comment]
Found the article that shows the endpoints to secure here: https://docs.openfaas.com/reference/authentication/

**Comment by alexellis** [comment]
Great, glad that you found it in the docs 👍
