### ISSUE TITLE
Extend health endpoint to include gateway version and commit details

### ISSUE THREAD

**Issue by ewilde** [openfaas/faas#733]
This issue proposes to extend the health endpoint and add `gateway` version information

## Current Behaviour
Currently the info endpoint shows helpful information about the configured provider:

```json
{
  "provider": "faas-swarm",
  "version": {
    "sha": "c890cba302d059de8edbef3f3de7fe15444b1ecf",
    "release": "0.3.3"
  },
  "orchestration": "swarm"
}
```

## Possible Solution
To help provide better runtime information to developers and operators, I propose to add a version block for the gateway:

```json
{
  "provider": {
    "name": "faas-swarm",
    "orchestration": "swarm",
    "version": {
      "sha": "c890cba302d059de8edbef3f3de7fe15444b1ecf",
      "release": "0.3.3"
    }
  },
  "gateway": {
    "version": {
      "sha": "c890cba302d059de8edbef3f3de7fe15444b1ecf",
      "release": "0.3.3",
      "commit_message": "Bump faas-swarm to latest"
    }
  }
}
```

## Context
When I was testing a change to OpenFaas prior to finishing off a PR I wanted to make sure I was running the correct build of the `gateway`. This proposal makes that easier

This proposal would be a breaking change for this endpoint. I think it would be cleaning to do this rather than have ambiguity with the `provider` version being a root attribute in the json body. however would be good to have feedback if making a breaking change on this endpoint is a big deal or not

**Comment by alexellis** [comment]
The endpoint isn't being used and was recently added so I think this would be fine.

Perhaps this part should remain with the provider?

```
 "orchestration": "swarm"
```

Alex

**Comment by alexellis** [comment]
Hi @ewilde, just to confirm. This is for the /system/info endpoint and not the health endpoint.. correct?

**Comment by alexellis** [comment]
When you have a PR please link here by `#PR_NUMBER`
