### ISSUE TITLE
Move all core builds from functions/* to openfaas/* on Hub

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#741]
This work involves moving all builds of all core components from functions/* to openfaas/* on the Docker Hub.

This moves to a better name for images and also gives free image-scanning. I've done the change for faas-swarm as an example for whoever works on this. @stefanprodan gave this perspective: this task also gives our users more confidence that we ship regularly and makes any vulnerabilities in components clear to us and the community early.

https://hub.docker.com/r/openfaas/faas-swarm/tags/

https://quay.io/repository/openfaas/faas-swarm?tab=tags

![screen shot 2018-07-02 at 1 41 50 pm](https://user-images.githubusercontent.com/6358735/42164359-b45aefe6-7dfd-11e8-80e3-37bb658ff7ba.png)

## Task

* Move from functions/ to openfaas/ for gateway, faas-netes, faas-swarm, queue-worker etc
* Do not move functions or do a wild-card search
* At the same time have every image push to both quay.io and the Hub - see faas-swarm as an example

Files that need changes: .travis.yml, ci.sh build.sh Makefile, etc.

Please raise the PRs and then ping me so that I can add the environmental variables to Travis to push to Quay successfully.

**Comment by alexellis** [comment]
Includes CLI repo if we haven't done this already - both pushing to Quay and rename to openfaas/*

**Comment by alexellis** [comment]
Related - #61

**Comment by ivanayov** [comment]
@alexellis ok, I can have look today

**Comment by stefanprodan** [comment]
@ivanayov I can do the operator change since I need to update the readme with the Helm installer anyway

**Comment by ivanayov** [comment]
@stefanprodan Thanks for taking this

**Comment by alexellis** [comment]
Derek close: this appears to be completed now.
