### ISSUE TITLE
Question: What should value of Http_X_Forwarded_For be in function?

### ISSUE THREAD

**Issue by info2000** [openfaas/faas#749]
The header Http_X_Forwarded_For is returning a wrong value, returning a local ip, it appears is fordwading the gateway container ip

This are the headers received:

[Http_Content_Type] => text/plain
    [Http_Origin] => http://217.182.87.71:8080
    [Http_Referer] => http://217.182.87.71:8080/ui/
    [Http_Content_Length] => 0
    [Http_Accept_Encoding] => gzip, deflate
    [Http_X_Call_Id] => d6c91228-292b-4993-9754-caa03cc4972e
    [Http_Cache_Control] => no-cache
    [Http_Connection] => keep-alive
    **[Http_X_Forwarded_For] => 10.255.0.2:65188**
    [Http_X_Start_Time] => 1531048975329479132
    [Http_Accept_Language] => en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7
    [Http_Pragma] => no-cache
    [Http_Accept] => application/json, text/plain, */*
    [Http_Cookie] => _ga=GA1.1.1709874416.1531005813; _gid=GA1.1.27171284.1531005813
    [Http_User_Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
    [Http_Method] => POST
    [PHP_SELF] => index.php
    [SCRIPT_NAME] => index.php
    [SCRIPT_FILENAME] => index.php
    [PATH_TRANSLATED] => index.php
    [DOCUMENT_ROOT] => 
    [REQUEST_TIME_FLOAT] => 1531048975.9164
    [REQUEST_TIME] => 1531048975

The expected value should be
79.156.60.104

I'm made the request from openfaas ui and from my browser, and the behavior is the same
The function is a hello world based on the php7 template

Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false

Over swarm
Linux debian 8

This is the php  code
`class Handler
{
    public function handle(string $_data): void {
        $_version = phpversion();
        echo 'PHP Version : '. $_version ."\n". 'Data : '. $_data. "\n\n".print_r($_SERVER, true);
    }
}
`

**Comment by alexellis** [comment]
Hi, thanks for logging the details for this.

We should take a look at this to confirm, but the code looks correct in the gateway package:

https://github.com/openfaas/faas/blob/6676d1b80749d94aef3e750dd38109255161be67/gateway/handlers/forwarding_proxy.go#L58

Just to confirm.. what were you expecting to see in the function under `Http_X_Forwarded_For`? The original client IP from your home network for instance? What if that was not the only hop between your client and the function?

Alex

**Comment by alexellis** [comment]
@ericstoekl I know you wanted to do some more support issues, can you take a look into this please?

**Comment by stefanprodan** [comment]
We can close this issues as it's not related to OpenFaaS. @info2000 please see https://github.com/moby/moby/issues/25526

**Comment by alexellis** [comment]
Derek close: not an issue
