### ISSUE TITLE
can I define dockerfile myself? 

### ISSUE THREAD

**Issue by Littermonkey** [openfaas/faas#757]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I need a docker image is based on ubuntu . can you help me ?

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by burtonr** [comment]
Hey @Littermonkey! You sure can use your own Dockerfile! 
Have a look at our [Dockerfile template](https://github.com/openfaas/templates/blob/master/template/dockerfile/function/Dockerfile)

Basically, all you need is to include the `watchdog` binary, set the `fprocess` to the command you want run, and set the `CMD`.

**Comment by burtonr** [comment]
Derek add label: question

**Comment by Littermonkey** [comment]
Hi @burtonr ! How do I modify the dockerfile template , so that I can customize my own docker image. can you tell me what should I do ?

**Comment by burtonr** [comment]
Sure! 
You'll need the cli installed [here](http://docs.openfaas.com/cli/install/).
Then, run the following:

`faas-cli new docker-func --lang dockerfile`

That will give you a directory `docker-func`, inside there is a Dockerfile that you can modify as you need. 

Then, of course follow the process like any other function:
```
faas-cli build -f docker-func.yml
faas-cli deploy -f docker-func.yml
```

**Comment by Littermonkey** [comment]
ok ,  will the new customize dockerfile replace the old dockerfile? or Do I need to delete the old?

**Comment by burtonr** [comment]
That generated Dockerfile is what you would change to have what you want. Alternatively, you _could_ replace it with another Dockerfile. Just be sure to include the watchdog so OpenFaas has something to call.

I'd recommend changing the one that is there though

**Comment by Littermonkey** [comment]
ok . I got it . thank you very much

**Comment by burtonr** [comment]
Great!

**Comment by burtonr** [comment]
Derek close: answered
