### ISSUE TITLE
can you tell me how to use the gateway ?  Is it like the aws api gateway ?

### ISSUE THREAD

**Issue by Littermonkey** [openfaas/faas#763]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by burtonr** [comment]
Please see the [Docs](https://docs.openfaas.com/)
Also, we have a workshop that you can go through that will allow you to try out many of the features of OpenFaaS so you may have a better understanding of how it all works.

https://github.com/openfaas/workshop

**Comment by burtonr** [comment]
Derek close

**Comment by burtonr** [comment]
@Littermonkey  I closed this issue as the question is very broad and more information can be found in the docs, or explained in the workshop.

Please feel free to open a new issue with specific questions or problems you may have. Also, please be sure to fill out the template when asking the specific questions. It will help us determine the cause of the issue much faster and easier. Thanks!
