### ISSUE TITLE
UX: can we show invocation URL in UI?

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#765]
To improve UX, can we show invocation URL in UI for invoking a function as part of the details page?

We don't know the external IP when inside Kubernetes/Swarm, but we know the "host" the browser is pointing at. Can we use this information to give the user a public URL/link for their function?

Alex

**Comment by alexellis** [comment]
Feedback/idea was from large bank evaluating OpenFaaS. 

cc @kenfdev

**Comment by kenfdev** [comment]
Let me prototype this tonight or tomorrow 👍

**Comment by alexellis** [comment]
I am thinking we can utilise this space by splitting the image area in half and placing to the right. 

<img width="1463" alt="screen shot 2018-07-13 at 08 41 56" src="https://user-images.githubusercontent.com/6358735/42679111-cb7c31ac-8678-11e8-943d-9b2d6d1fcd80.png">

**Comment by alexellis** [comment]
@kenfdev

**Comment by kenfdev** [comment]
<img width="1273" alt="link7" src="https://user-images.githubusercontent.com/3941889/42679590-79a8e056-86bd-11e8-9f72-2658b41d226f.png">

Yes, that's what I did. WDYT?

**Comment by alexellis** [comment]
I like it 🎉 ! Should it have the copy icon there too and then clicking adds it to the clipboard?

**Comment by alexellis** [comment]
Derek set milestone: 0.8.6

**Comment by alexellis** [comment]
Derek close: merged
