### ISSUE TITLE
Docs: Swarm/Kong guide should show how to add async-function route

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#766]
Via community member Omar Qureshi:

In

https://github.com/openfaas/faas/blob/master/guide/kong_integration.md

Add:

```
curl -X POST \
   --url http://kong-admin:30703/apis/ \
   --data 'name=async-function' \
   --data 'uris=/async-function' \
   --data 'upstream_url=http://gateway:31112/async-function'
```

**Comment by mrtind** [comment]
I can work on this one.

**Comment by Kashyap12** [comment]
Hi @alexellis Can I take this up?

**Comment by alexellis** [comment]
Hi @Kashyap12, we got to the point where we updated the async route but it looks like Kong may have had some changes since we wrote the original and it's now giving some errors for @martindekov around the auth section. Feel free to take a look. 

Alex

**Comment by alexellis** [comment]
Derek close: fixed
