### ISSUE TITLE
Docs: retrieve basic auth password value

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#768]
Please update the docs to give a mechanism to retrieve password from a docker secret (may involve running a container and using "cat") and for Kubernetes secret which may involve `base64 --decode`

Alex

**Comment by alexellis** [comment]
Derek add label: area/docs

**Comment by alexellis** [comment]
Derek add milestone: 0.8.6

**Comment by alexellis** [comment]
Derek set milestone: 0.8.6

**Comment by alexellis** [comment]
Work done here - https://github.com/openfaas/docs/pull/42

**Comment by mrtind** [comment]
I already found a way to retrieve content of docker secret with redis. Can i take this one ?

**Comment by alexellis** [comment]
Derek close: resolved
