### ISSUE TITLE
Minor error in lab4

### ISSUE THREAD

**Issue by jonasrosland** [openfaas/faas#771]
## Expected Behaviour
On line 186 of https://github.com/openfaas/workshop/blob/master/lab4.md, it says:
`$ echo -n "" | faas-cli invoke nodeinfo | faas-cli invoke func_markdown`
However, in the workshop there is no function with that name created.

## Current Behaviour
The invocation breaks.

## Possible Solution
Change the line to the correctly named function:
`$ echo -n "" | faas-cli invoke nodeinfo | faas-cli invoke markdown`

## Steps to Reproduce (for bugs)
See above

## Context
Lab4 doesn't work correctly.

## Your Environment
Latest Docker Edge as per setup guide

**Comment by alexellis** [comment]
Fixed 👍
