### ISSUE TITLE
Question: how can I effectively benchmark Python functions?

### ISSUE THREAD

**Issue by lioncruise** [openfaas/faas#772]
Hello, recently I'm doing some performance research on Serverless computing architecture, and use OpenFaaS as the researching entity. I wrote 2 "hello world" logic code respectively in OpenFaaS function with the built-in Python template and a Python Flask application deployment on Kubernetes. I set the number of replica all the same, and started pressure testing with wrk tool.  According to my experimental result, the QPS of Serverless function is several to 10+ times lower than Flask application with the same executing logics and same resources. So, what are the main factors that caused the poor performance of Serverless computing? And whether Serverless computing suitable for high concurrency online service scene? What are the main scenarios of Serverless computing?

**Comment by alexellis** [comment]
Hi @lioncruise please break down your method into something we can reproduce scientifically. 

You should also read up on the documentation for performance testing and be using the high-throughput version of the Python templates.

https://github.com/openfaas/faas/blob/master/guide/performance_testing.md

http://docs.openfaas.com/architecture/watchdog/

Alex

**Comment by alexellis** [comment]
Derek close: inactive

**Comment by alexellis** [comment]
For high-throughput tests, take a look at the of-watchdog Python template
