### ISSUE TITLE
Web GUI not accessible

### ISSUE THREAD

**Issue by drago87** [openfaas/faas#775]
The problem started happening last week (Around the 9 of July) dont remeber exactly the date. It worked before then.
Updating creepMiner did not help.
The GUI worked in version 
1.7.16
1.8.0
1.8.2 (Worked from when i dowloaded it around a week after release)
## Expected Behaviour
After starting creepMiner going to http://localhost:port would open the web GUI
(port is the port number i have tried)
## Current Behaviour
After going to http://localhost:port Getting the error  "Connection refused: localhost:port"
(port is the port number i have tried)

## Your Environment
Windows 10
creepMiner 1.8.2 and 1,8,3

Log File
[creepMiner_20180717_160957.566889.log](https://github.com/openfaas/faas/files/2202502/creepMiner_20180717_160957.566889.log)

Config File (Removed pass and user)
[mining - Copy.txt](https://github.com/openfaas/faas/files/2202510/mining.-.Copy.txt)

**Comment by alexellis** [comment]
Derek lock: invalid
