### ISSUE TITLE
Question: How do you get headers and query params in the function?

### ISSUE THREAD

**Issue by dtrce** [openfaas/faas#785]
Is it possible to pass in all the headers and query params that were part of the request when the function was called via Http endpoint?

## Expected Behaviour

The input of the function should use a standard format such as Json. Json data could have keys such as body, headers and queryparams.

## Current Behaviour

Currently it only passes in the body of the http request.

## Context

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.03.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Mac

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
I'm going to point you at this for the QueryString and "all" headers -> https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables

As for "params" I'm not sure if you mean URL parameters like /employee/:id/ kind of thing? 

JSON is supported as a body type / content-type already.

Hope this helps.

**Comment by alexellis** [comment]
Then I'd say it really depends on which programming language you are using too. The newer style templates do have an event and context that can be used for some of this, the classic versions access this data via environmental variables as you'll see in the link.

**Comment by alexellis** [comment]
Derek close: support question / query, not a defect.

**Comment by alexellis** [comment]
Please feel free to keep commenting.

**Comment by juandisay** [comment]
> Please feel free to keep commenting.

Hi, @alexellis 
I Need spesifik explanation about Request header GET openfaas. 
I've read 
https://github.com/openfaas/workshop/blob/master/lab4.md#inject-configuration-through-environmental-variables, 

about python code type like os.env()  have a rules in Openfaas, lik os.env('Http_Query') or etc? 

THanks,
