### ISSUE TITLE
Update contributing guide to use markdown headers

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#787]
## Expected Behaviour

Markdown headers i.e. `#` `##` `###` etc should be used to enable linking to sub-sections such as the group of core contributors or the section on commit messages.

## Current Behaviour

Only implemented partially.

## Possible Solution

Make some edits to the file (try to retain the same headings, just use `####` etc where needed)

https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

**Comment by rgee0** [comment]
Derek close: merged in #788
