### ISSUE TITLE
Update NATS Streaming to 0.11.0

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#790]
## Suggestion

It looks like nats-streaming has a new version 0.12.0 - we should test this and move to it if it is stable.

## Changes

- docker-compose.yml
- helm chart
- Kubernetes YAML files

https://hub.docker.com/_/nats-streaming/

Additional due diligence:
- check client library and re-vendor/update if needed
- "handler" package in queue-worker may need to be revendorded, which is a rebuilt of the gateway
- check queue-worker can still pull work and process it

**Comment by alexellis** [comment]
Anything else to add @stefanprodan ?

**Comment by martindekov** [comment]
I can work on this one. Can I assign myself ?

**Comment by alexellis** [comment]
(This work needs thorough regression/hands-on testing)

**Comment by martindekov** [comment]
Yeah ok I will continue with the faas-cli.

**Comment by burtonr** [comment]
Derek assign: martindekov

**Comment by burtonr** [comment]
@martindekov if you are no longer working on this you can use `Derek unassign: me` in order to remove yourself from the issue.

**Comment by martindekov** [comment]
Hey @burtonr I just saw you assigned me. I actually meant I am passing that and haven't even started working on it. If you want to work on this take it.

**Comment by martindekov** [comment]
Derek unassign: me

**Comment by LucasRoesler** [comment]
Derek assign: me

**Comment by LucasRoesler** [comment]
I just looked at the nats client library and there are no newer releases than our currently vendored package

**Comment by LucasRoesler** [comment]
It is also worth noting that the title for this ticket says version 0.12.0 but the latest tag I could find for nats-streaming is 0.11.0

**Comment by kozlovic** [comment]
Yes, latest is only 0.11.2.

**Comment by alexellis** [comment]
Derek set title: Update NATS Streaming to 0.11.0

**Comment by alexellis** [comment]
@LucasRoesler where are we with this now?

**Comment by LucasRoesler** [comment]
This is closed

**Comment by LucasRoesler** [comment]
Derek close
