### ISSUE TITLE
console.log() in javascript not working?

### ISSUE THREAD

**Issue by itibb13** [openfaas/faas#798]
Hi guys,

I am using OpenFaas with the Node.js template. While playing around with simple examples written in Javascript, I noticed that console.log() works only while invoking the functions via command-line tool faas-cli. However, when I invoke the same function (unchanged) via the browser interface then I receive a null message.  In contrast, when I remove the line with the console.log(), everything works fine.
Any ideas what I am doing wrong or missing? In fact, how can I enable logging with the Node.js template for debugging purpose?

Thank you

**Comment by alexellis** [comment]
Hi @itibb13 thanks for your interest in OpenFaaS.

Please see the OpenFaaS workshop Lab 4 for everything you need to know about this.

https://github.com/openfaas/workshop/blob/master/lab4.md

Regards,

Alex

**Comment by alexellis** [comment]
Derek close: resolved

**Comment by alexellis** [comment]
Derek add label: support

**Comment by alexellis** [comment]
Feel free to keep commenting, closing as resolved.
