### ISSUE TITLE
Question: How to reuse code across different functions

### ISSUE THREAD

**Issue by lapwat** [openfaas/faas#804]
Good morning,

Is there a best practice for reusing the same files across different functions. Let me explain myself.

I have got 2 different functions: one that will return a category given an input, the other one will return a number given an input. They share some of the same code.

The folder structure is
- functions
    - stack.yml
    - function1
        - handler1.py
        - utils.py
    - function2
        - handler2.py
        - utils.py

`handler1.py` and `handler2.py` are different. `utils.py` represent the same file and is shared by `function1` and `function2`.

At present I need to duplicate the up-to-date version of `utils.py` into `function1` and `function2` every time I want to build/deploy my functions.

Is there a way to link an unique version of `utils.py` to my functions ?

Best,

Quentin

**Comment by rgee0** [comment]
Possible duplicate. Ref: OpenFaaS/faas-cli#322

**Comment by rgee0** [comment]
Derek set title: Question: How to reuse code across different functions

**Comment by ivanayov** [comment]
Derek close
