### ISSUE TITLE
Question: How to manage/isolate environments?

### ISSUE THREAD

**Issue by wdyun** [openfaas/faas#805]
Is there any easy way to isolate prod 、dev environment？In CI/CD use Jenkins，how to define the 'provider gateway', so use one same code just different config?

```
provider:
  name: faas-dev
  gateway: http://192.168.4.95:31112
```

**Comment by alexellis** [comment]
Hi @wdyun,

The best way to isolate environments is with multiple installations of OpenFaaS on Kubernetes. Use NetworkPolicy to separate them if you need a hard link between them. 

@stefanprodan can send you a link to some examples of this.

Btw you cannot change the `provider.name` field, it must be `faas`.

Once your environments are established leave the `gateway` field out of the YAML file and use the `--gateway` field to switch between them, or the `OPENFAAS_URL` env-var.

Alex

**Comment by alexellis** [comment]
Derek close: resolved

**Comment by alexellis** [comment]
Please feel free to keep commenting. I'm closing since since this is not an Issue with the project, more of a support question. These are best asked on Slack - via https://docs.openfaas.com/community/
