### ISSUE TITLE
Proposal: Deprecate dep usage in favour of vgo

### ISSUE THREAD

**Issue by james-r-smith** [openfaas/faas#806]
As Go has been on a [mission to get dependency management nailed](https://github.com/golang/proposal/blob/master/design/24301-versioned-go.md), the decision is clear that modules are the direction that has been decided. Go 1.11 is going to be the first release that will offer basic support for dependency management into the Go toolchain.

Currently, Go modules are in a stable condition to be used over other tools like `dep`, that we are currently using. It's also [supported in Travis as well](https://dave.cheney.net/2018/07/16/using-go-modules-with-travis-ci). As [Go 1.11 is approaching](https://github.com/golang/go/milestone/62), we should now consider the approach to migrating to modules. We can do this with [vgo](https://github.com/golang/vgo).

Vgo offers a way to migrate from popular dependency management tools, such as `dep`, and also supports the vendoring option until they deprecate that approach in the future. With `vgo`, we'll be able to do the following: ensure we are using the same versions of dependencies that we are now, vendor our dependencies for the FaaS projects that use it, and maintain the integration with Travis. Outlined in the next section below are steps that we can take for migrating.

## Actions to Take

- Update Docker images using Go to a version supporting modules
- Update Go version in Travis to a version supporting modules
- Use [vgo](https://github.com/golang/vgo) or a beta version of Go 1.11 to migrate all OpenFaaS projects to modules
- Update documentation / template welcome messages to suggest `vgo` or the Go 1.11 toolchain to manage dependencies

## Current Behaviour

`dep`  tool is used to manage dependencies.

**Comment by alexellis** [comment]
Hi James, thanks for your suggestion.

My take is that deprecating `dep` will be a huge amount of work and I'm not sure what the value proposition is (yet). It may be something that should be reviewed in time once vgo is GA and we have some spare cycles or moving offers considerable value to the project and contributors.

Perhaps as an interim step you may want to help with migrating some of the projects to the latest Golang version made available by Docker?

Alex

**Comment by stefanprodan** [comment]
Most OpenFaaS projects depend on Kubernetes and Docker Moby, I would wait for these two project to make the move first.

**Comment by james-r-smith** [comment]
@alexellis, I agree that small steps should be made, and it should be done in one big sweep through the projects. That's a great start! Should we upgrade the version to Go `1.11beta3`, or go with the latest released version like `1.10.3`? Also, I would think if we do projects one at a time, it would help with the migration.

@stefanprodan, Kubernetes has seemed to go with [Bazel](https://bazel.build/), which is another great tool, but mainly used for incredibly large, monolithic repositories with (usually) several languages being used. I do agree it's good to watch other large projects adopt it. I know it's a bit obvious, but [Go](https://github.com/google/go-cloud) libraries have already begun using it if that helps. 😅

**Comment by stefanprodan** [comment]
@james-r-smith I think you are confusing a build tool such as Bazel with a dependency one such as [Godep](https://github.com/tools/godep). Kubernetes didn't made the switch to [dep](https://github.com/golang/dep) because it didn't work for them, they use [godep](https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json). Docker Moby uses [vndr](https://github.com/LK4D4/vndr). 

We've been using `vndr` in OpenFaaS and made the switch to `dep`, see #462 

My take on this is that we should wait and see if Kubernetes and Moby are moving to go modules.

**Comment by james-r-smith** [comment]
Ah, okay, @stefanprodan. Thanks for clearing things up. I can understand your side of the argument now. That sounds fine. We can definitely initiate the process by upgrading the versions of Go throughout. Would this be okay to start now, or should we pick this back up once `1.11` is released?

**Comment by thepudds** [comment]
One quick update/comment: kubernetes is now moving towards Go 1.11 modules (aka vgo). See for example here: 

https://github.com/kubernetes/kubernetes/pull/64731#issuecomment-407345841

and here:

https://github.com/kubernetes/kubernetes/pull/65683

(And in general the whole design of versioned modules / vgo allows for the ecosystem to adopt at different rates, and it is still very much at the opt-in stage, so no need to rush if not right yet for your project. I just happened to see comment above about kubernetes, and just wanted to provide a quick update on kubernetes based on statements I've seen from Russ Cox and the k8s team).

**Comment by alexellis** [comment]
Thanks for the discussion. I think we need to hold off for now, certainly we do not want to be adopting a beta or alpha version of Go.

James et al, if you're looking for ways to contribute please comment in #contributors on Slack.

**Comment by alexellis** [comment]
Derek lock: revisit

**Comment by alexellis** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek: close - revisit when impact to broader project evaluated and strategy ready for converting all projects consistently.
