### ISSUE TITLE
Enable X-Call-Id header for async-function calls

### ISSUE THREAD

**Issue by pourabolghasem** [openfaas/faas#813]
## Expected Behaviour

When an async-fucntion call is made, the only way for the caller to track the function execution is through X-Callback-Url header. This is great for event driven architectures. But if the caller wants to track (i.e., correlate) the result of individual function calls with the actual calls, it seems the only way is to embed the tracking information (uuid) within the request body of the async call or its header. This feature request is to enable including the X-Call-Id header the default behavior for async-fucntion calls as well. The X-Call-Id can then be included in the response to the async caller along with the http.StatusAccepted header. It can also be included in the call to X-Callback-Url, which then will enable correlating the function calls and their results.

## Current Behaviour

Upon an async call, the caller receives http.StatusAccepted header and no other information to be able to track this instance of the function call.

## Possible Solution

The following single line addition in faas/gateway/server.go can enable this feature:
`faasHandlers.QueuedProxy = handlers.MakeCallIDMiddleware(faasHandlers.QueuedProxy)`

## Context

Correlating the requests and responses for long running function calls (which are made through async calls) is a critical feature for enabling observability in analytics and data processing workloads. These workloads are not necessarily event-driven and are designed to follow the transformation of the data. X-Call-Id in combination with X-Callback-Url can enable such observability under these workloads.

**Comment by alexellis** [comment]
Sounds good to me.

Would you like to implement and test it?

I also wondered if you had more info on your usecase? 

Alex

**Comment by ivanayov** [comment]
Derek add label: proposal

**Comment by ivanayov** [comment]
Derek add label: help wanted

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
@ivanayov what's your ETA on this? Thanks
