### ISSUE TITLE
Support: Issue with AKS + RBAC + Helm

### ISSUE THREAD

**Issue by pharrukh** [openfaas/faas#814]
I run this command:

```
helm upgrade openfaas --install openfaas/openfaas \                                                                                                                     
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn \
    --set rbac=false
```

`Error: error validating "": error validating data: found invalid field readOnlyRootFilesystem for v1.PodSecurityContext`

## Expected Behaviour

The services of OpenFaas are deployed to Azure Kubernetes Services.
## Current Behaviour

Services are not deployed.
## Context

When I edit the file: `./faas-netes/chart/openfaas/templates/gateway-dep.yaml` and remove `readOnlyRootFilesystem: true` I get the services deployed and I can access the UI. But I cannot deploy any function I get this error:

```
deployments.extensions is forbidden: User "system:serviceaccount:openfaas:openfaas-controller" cannot create deployments.extensions in the namespace "openfaas-fn"
```

in the `Manually` tab of the popup form.

<img width="1012" alt="screen shot 2018-08-12 at 9 46 04 pm" src="https://user-images.githubusercontent.com/6096032/44005795-5c5d722c-9e79-11e8-8882-861cf61a081a.png">

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.06.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS 10.13.6
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
@stefanprodan PTAL, any relation to recent refactoring work in helm chart? AKS used to work without RBAC as per the guide written with @squillace and @ericstoekl 

I would think you can get paste this by creating your cluster with RBAC enabled (I believe you need to use the AKS CLI for that)

**Comment by affix** [comment]
by setting `--set rbac=false` you don't create the service account.

Do you have RBAC enabled on your AKS Cluster?

**Comment by alexellis** [comment]
How about trying?

```sh
kubectl get clusterroles | grep -i rbac
```

**Comment by alexellis** [comment]
Try this:

```
kubectl cluster-info dump | grep authorization-mode
```

It'll tell us whether you have RBAC on or not.

**Comment by alexellis** [comment]
So we set up an AKS cluster with 2 nodes in `eastus` using these instructions: 
https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough

Then I installed OpenFaaS with:

```
helm repo update  && helm upgrade openfaas --install openfaas/openfaas     --namespace openfaas      --set functionNamespace=openfaas-fn --set rbac=false --set serviceType=LoadBalancer
```

Before that I installed helm + tiller -> https://github.com/openfaas/faas-netes/blob/master/HELM.md

Then I got a LoadBalancer for the gateway and tried to deploy `figlet`

<img width="903" alt="screen shot 2018-08-12 at 22 04 07" src="https://user-images.githubusercontent.com/6358735/44006390-bab89a2a-9e7b-11e8-8899-301ce2cdee8b.png">

I'd refer this issue to @stefanprodan who has been working on the helm chart recently. Perhaps there's something that got nudge?

In the meantime [you can setup AKS with RBAC enabled](https://docs.microsoft.com/en-us/azure/aks/create-cluster) via `--enable-rbac`, which will get you past this error.

**Comment by alexellis** [comment]
The SA does appear to exist, but do we know why we're getting the error on a cluster which has RBAC turned off?

```
$ kubectl get sa/openfaas-controller -n openfaas -o yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2018-08-12T21:00:10Z
  labels:
    app: openfaas
    chart: openfaas-1.2.1
    component: faas-controller
    heritage: Tiller
    release: openfaas
  name: openfaas-controller
  namespace: openfaas
  resourceVersion: "1727"
  selfLink: /api/v1/namespaces/openfaas/serviceaccounts/openfaas-controller
  uid: b35d7143-9e72-11e8-9547-fa3ad5ac897e
secrets:
- name: openfaas-controller-token-brhd8
```

**Comment by alexellis** [comment]
As strange as it sounds, setting rbac to `true` resulted in the cluster fully working, despite me being able to detect RBAC in the Kubernetes cluster. Perhaps Azure are enabling RBAC silently now?

**Comment by alexellis** [comment]
I pinged @lachie83 from Azure / AKS who told me RBAC is on, on all clusters by default when created with the current CLI version of `az`. That would add up with that I saw when I installed OpenFaaS with `--set rbac=true`. @affix can you try installing with `--set rbac=true` on your test cluster?

**Comment by lachie83** [comment]
Hey @alexellis. Apologies. I've done some digging and I don't believe it is on by default in the CLI just yet. You would have to explicitly enable it. In order to confirm you can show the cluster details using the CLI. ```
az aks show -g <RESOURCE_GROUP> -n <CLUSTER_NAME>
Look for - enableRbac 
```

**Comment by pharrukh** [comment]
This is the result of `az aks show -g berlincluster-dev-rg -n berlincluster`

`{
  "aadProfile": null,
  "addonProfiles": {
    "omsagent": {
      "config": {
        "logAnalyticsWorkspaceResourceID": "/subscriptions/ef7fec7f-59c8-46f3-8fd6-b66cbd0a1205/resourcegroups/defaultresourcegroup-weu/providers/microsoft.operationalinsights/workspaces/defaultworkspace-ef7fec7f-59c8-46f3-8fd6-b66cbd0a1205-weu"
      },
      "enabled": true
    }
  },
  "agentPoolProfiles": [{
    "count": 1,
    "maxPods": 110,
    "name": "nodepool1",
    "osType": "Linux",
    "storageProfile": "ManagedDisks",
    "vmSize": "Standard_DS1_v2"
  }],
  "dnsPrefix": "berlinclus-berlincluster-de-ef7fec",
  "enableRbac": true,
  "fqdn": "berlinclus-berlincluster-de-ef7fec-ce4c305b.hcp.westeurope.azmk8s.io",
  "id": "/subscriptions/ef7fec7f-59c8-46f3-8fd6-b66cbd0a1205/resourcegroups/berlincluster-dev-rg/providers/Microsoft.ContainerService/managedClusters/berlincluster",
  "kubernetesVersion": "1.9.9",
  "linuxProfile": {
    "adminUsername": "azureuser",
    "ssh": {
      "publicKeys": [{
        "keyData": "xxx"
      }]
    }
  },
  "location": "westeurope",
  "name": "berlincluster",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "networkPlugin": "kubenet",
    "networkPolicy": null,
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "MC_berlincluster-dev-rg_berlincluster_westeurope",
  "provisioningState": "Succeeded",
  "resourceGroup": "berlincluster-dev-rg",
  "servicePrincipalProfile": {
    "clientId": "67c3cd46-567c-44e8-8c5d-ac5512901024"
  },
  "type": "Microsoft.ContainerService/ManagedClusters"
}`

As I did not set `rbac`, I was following [this](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) instruction.

**Comment by pharrukh** [comment]
I am now recreating a cluster, as I did not find a way to change `rbac`. Here is the warning message:
`az aks create --resource-group serverless-dev-rg --name serverless-cluster --enable-rbac

Argument 'enable_rbac' has been deprecated and will be removed in a future release. Use '--disable-rbac' instead.`

**Comment by alexellis** [comment]
I think it's confusing but the Azure team changed their setup to enable RBAC rather than disable it. So you should create a cluster and then install with OpenFaaS without setting `--set rbac=false`

Please do this and report back.

**Comment by farrukh-normuradov** [comment]
@alexellis I did exactly that yesterday. I got faas service installed in the cluster and I got functions deployed through UI.  But status never turned to "Available/Ready", it was not ready so the "Invoke" button was disabled. I did not yet figure out how to control deployment with `faas-cli`.

I will retry today, in 10 hours and report back.

**Comment by ivanayov** [comment]
@farrukh-normuradov what is the pod status?

**Comment by pharrukh** [comment]
I got it working by not setting `--set rbac=false`.

My request was graciously handled, I appreciate. Thanks.
