### ISSUE TITLE
Concurrent executions of the same function in a single container?

### ISSUE THREAD

**Issue by wnagchenghku** [openfaas/faas#817]
I would like to ask about the concurrency of OpenFaaS.

## Current Behaviour

According to the [SAND paper](https://www.usenix.org/system/files/conference/atc18/atc18-akkus.pdf) (Section 2.3), OpenFaaS allows parallel executions of the same function in a single container, but I didn't find any such information on OpenFaaS website. May I know does OpenFaaS support this behavior? If it supports, does OpenFaaS spawn a new process or new thread in the container to handle the concurrent requests? If OpenFaaS does not support this behavior, why not?

Many thanks for your time.

**Comment by alexellis** [comment]
Hi @wnagchenghku, this is documented but perhaps not in the language you were looking for.

Concurrent execution is supported with both function execution models. We use a watchdog shim component in the container to manage this.

https://docs.openfaas.com/architecture/watchdog/

Alex

**Comment by alexellis** [comment]
If you'd like to ask more questions please join the Slack community https://docs.openfaas.com/community

**Comment by FTWH** [comment]
> https://docs.openfaas.com/community

Hello, could you please tell me about how to set up the limitation for this concurrency like "Container Concurrency" in Knative? Thanks!

**Comment by alexellis** [comment]
Hi @FTWH you can learn about concurrency limitation in this blog post:

https://www.openfaas.com/blog/limits-and-backpressure/

Alternatively, we do offer paid support, or if you prefer, feel free to attend our weekly community call.

> Our office hours at 1630 GMT+1 / BST each Wednesday will be open to the community.
> https://us02web.zoom.us/j/83845933347?pwd=RzhVeWVHVXJQY2RBM1FMMzd3blhpUT09
> Introduce yourself, feel free to bring questions, comments and suggestions for openfaas, arkade, k3sup and derek.


Regards,

Alex
