### ISSUE TITLE
Question: Is it possible to redo the basic authentication process, or find out what the credentials for the gateway are?

### ISSUE THREAD

**Issue by SlopezP** [openfaas/faas#823]
I am very inexperienced with all of this so any help at all would be appreciated.

I deployed openfaas via Docker swarm, and got to the point where the credentials for the gateway were created. However, I was greeted with a few permission errors, and ran the process again as a super user. What I didn't realize before I closed the terminal was that the credentials were printed within the terminal that I closed. And now I do not know either the username or password to the openfaas UI.

I would like to know of either a way to access the username and password for the gateway, or to redo the entire openfaas deployment process entirely. Thank you.

## Expected Behaviour
I used the basic guide to deploy openfaas via Docker Swarm here: https://docs.openfaas.com/deployment/docker-swarm/

Everything worked as intended.

## Context
Without removing authentication, I cannot access the openfaas site that I created. 
I tried using the code below to reset the password, assuming admin was the username, but that has not worked either.
```
$ docker service rm print-password \
 ; docker service create --detach --secret basic-auth-password --restart-condition=none --name=print-password alpine:3.7 cat /run/secrets/basic-auth-password

$ docker service logs print-password
21f596c9cd75a0fe5e335fb743995d18399e83418a37a79e719576a724efbbb6
```
I also tried removing all containers made during the deployment process and starting over, but the credentials were still stored somewhere.

## My Environment
Ubuntu v. 18.04 (Fresh install)
Docker v. 18

**Comment by ivanayov** [comment]
Hi @SlopezP 

You can find the credentials following these instructions: [troubleshooting/#i-forgot-my-gateway-password](https://docs.openfaas.com/deployment/troubleshooting/#i-forgot-my-gateway-password)

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by SlopezP** [comment]
I tried resetting the password, and copying the printed string into the password field with "admin" as the username, but could not get in. Where am I going wrong? or what am I not understanding?

**Comment by ivanayov** [comment]
@SlopezP  Password reset is not supported at the moment. Did you try to retrieve the old credentials with the instructions shared above?

**Comment by alexellis** [comment]
@SlopezP run through the steps in the documentation that was shared by Ivana. That will give you your password. Hope this helps.

I'm going to close this issue because if you follow the instructions you'll get what you need. If you want to change the password you can remove the gateway, remove the secret then run the deployment again to generate a new password. 

Alex

**Comment by alexellis** [comment]
(Reset is supported) if you want to reset your password, simply delete the password and run the deployment script again. If your password is not compromised I'd suggest you run the instructions in the docs and then save your password somewhere like 1password for further use.

**Comment by SlopezP** [comment]
I did run through the steps, is what I'm saying, but using "admin" as the username and using the password that the steps give me does not work. 

How do I go about deleting the secrets to start over then? I don't see a guide for that in the troubleshooting page.
