### ISSUE TITLE
Amend Derek users

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#824]
We need to update the Derek user-list in the faas repo. Most repos redirect to this repo for access. 

Remove inactive users

 - ovation22
 - cpitkin
 - jockdarock
 - itscaro

Add new full-time team:

- bartsmykla

Please cross-reference the GitHub org and add anyone who is missing: https://github.com/orgs/openfaas/people

**Comment by stantonxu** [comment]
@alexellis , I've deleted the inactive users and added the individual users per the "People" list. How to add the full-time team? Add as an individual user?

**Comment by bartsmykla** [comment]
As an individual user is fine I think. :-)

**Comment by stantonxu** [comment]
Thank you @bartsmykla , I will add `bartsmykla` as individual user, and remove the duplicated one.

**Comment by alexellis** [comment]
Fixed via Stantonxu's PR
