### ISSUE TITLE
Reset the credentials

### ISSUE THREAD

**Issue by ohld** [openfaas/faas#825]
Hi there! I've just found OpenFASS, created the docker swarm and run the installation bash script. It has generated a login-password pair that I have not saved anywhere. 

Can you please describe the way how to reset the credentials instead of using `--no-auth` every time. Thanks and sorry for such a noob question.

**Comment by ivanayov** [comment]
Hi @ohld 

This should help: [troubleshooting/#i-forgot-my-gateway-password](https://docs.openfaas.com/deployment/troubleshooting/#i-forgot-my-gateway-password)

Ivana

**Comment by ivanayov** [comment]
Derek add label: quiestion

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by ivanayov** [comment]
Derek remove label: quiestion

**Comment by alexellis** [comment]
Hi @ohld did that help?

**Comment by alexellis** [comment]
I've also updated the docs page @ivanayov quoted to mention how to retrieve the credentials from the CLI config file.

**Comment by ohld** [comment]
Yes. That helped. Thanks a lot!
