### ISSUE TITLE
UI: Show info icon for gateway & provider version/data

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#831]
## Expected Behaviour

Using a Glyphicon we can now surface the information provided by `/system/info` which gives relevant versions and the back-end type. See `faas-cli version` as an example of the data or call the endpoint on your own gateway.

## Current Behaviour

Version available via API or `faas-cli version`

## Context

This data is now fully available in the API and stable. The original intention was for it to be surfaced in some way. A model dialog may be suitable.

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

This would work across all versions transparently cc @ewilde

**Comment by alexellis** [comment]
Thank you

**Comment by alexellis** [comment]
@dmcclory it's almost one month on since you volunteered to take this task. Have you made any progress or should we allow someone else in the community or @openfaas/faas-team to pick this up?

**Comment by dmcclory** [comment]
Hi @alexellis - I've been doing some work on it, it's taken me a little longer than I anticipated to get figure out angular. But I think I've turned a corner and I'm pretty close to having something. Right now I have it as a floating action button in the lower right part of the screen:

![screen shot 2018-09-23 at 3 11 55 pm](https://user-images.githubusercontent.com/1952789/45931915-10c72200-bf43-11e8-87a5-99537a0f1029.jpg)

How does that look? Is there a better spot to place it?

**Comment by alexellis** [comment]
Thanks for the update. I was wondering whether it might sit as three dots up by the logo or by the deploy from store button. If you're on Slack you could post this link above into #ui-taskforce to get some other suggestions/help if needed.

Alex

**Comment by alexellis** [comment]
Derek add label: Hacktoberfest

**Comment by phanix5** [comment]
Hi @alexellis It looks like it's been a while since there has been an update on this. Is it okay if I take it up? I'm new here and this doesn't look too complicated.

**Comment by alexellis** [comment]
Please do :+1:

Can you send 2-3 mockups into this issue too?

**Comment by phanix5** [comment]
@alexellis what kind of information are we expecting to display? The endpoint currently just seems to be  providing the last Commit message and SHA along with the orchestration type.

**Comment by alexellis** [comment]
Let's show what we have and hide the commit message.

**Comment by phanix5** [comment]
![faas_mock](https://user-images.githubusercontent.com/25152531/51852984-40e95c00-234d-11e9-9194-662e2c951d93.png)

**Comment by alexellis** [comment]
I think it'd make more sense offset to the right than the left.

Do you have a screenshot of the pop-up?

Alex

**Comment by phanix5** [comment]
And the popup: 
![openfaas-popup](https://user-images.githubusercontent.com/25152531/52228714-119c9700-28d9-11e9-9692-1ab473839154.png)

**Comment by alexellis** [comment]
I'd rather see the ":" on the right of the text, not the left because European readers read left to right. 

<img width="363" alt="screenshot 2019-02-04 at 18 32 27" src="https://user-images.githubusercontent.com/6358735/52228924-6f19ef00-28ab-11e9-86fd-5e7fa4751acc.png">

I'd also like the pop-up to look like the Function Store pop-up.

Perhaps we can also offset the key / value fields as a form so that it has a better layout / padding.

Would you be able to make both those changes please?

**Comment by phanix5** [comment]
This is the issue I was mentioned earlier:
![openfaas-popup2](https://user-images.githubusercontent.com/25152531/52229376-c1263900-28da-11e9-9257-cf6720a96d13.png)

**Comment by phanix5** [comment]
I guess I can 'squash' the 3-dots button to occupy lesser space.

**Comment by alexellis** [comment]
Hey @jagreehal, wdyt?

**Comment by phanix5** [comment]
Something like this? 
![openfaas-popupv2](https://user-images.githubusercontent.com/25152531/52231033-e321ba80-28de-11e9-9ddd-6ff4b106ee0a.png)

**Comment by jagreehal** [comment]
First thoughts are why not just use info-circle as the icon? 

Personally I don't like modals to display information like this. 

Could this information be displayed at the bottom of the left column?

In addition I'd consider making the list of functions scroll separately to the page.

**Comment by alexellis** [comment]
Thanks for your input @jagreehal the Info icon also makes sense for me or some other glyphicon.

The page needs an overhaul when we move to React. Since the re-write is taking some time to get off the ground. Is there a way this can make sense as an info icon/modal or something similar?

**Comment by phanix5** [comment]
@alexellis I guess the requirements/design has to be decided before I get to working on it.

**Comment by phanix5** [comment]
@jagreehal, @alexellis does this look better?
![openfaas-footer](https://user-images.githubusercontent.com/25152531/52519453-7a8d6180-2c81-11e9-998f-52e6e0790865.png)

**Comment by phanix5** [comment]
The text at the bottom is sticky.

**Comment by phanix5** [comment]
@alexellis can I get your decision on this?

**Comment by alexellis** [comment]
How does it look when you have functions with scroll i.e. deploy 20 functions?

**Comment by alexellis** [comment]
@phanix5 agree, generally prefer to see 2-3 mock-ups before actually doing work on it.

Alex

**Comment by phanix5** [comment]
The text stays on top of the functions list - 
![openfaas](https://user-images.githubusercontent.com/25152531/52874999-39151e80-3179-11e9-9dee-be1c1cd158be.png)

**Comment by phanix5** [comment]
@alexellis can I get your call on this? Is this still relevant given the new UI with React?
