### ISSUE TITLE
Pass basic auth upstream to providers

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#836]
## Expected Behaviour

When calling the /system/ or protected routes on the backend providers (upstream) i.e. faas-netes / faas-swarm, we should pass the basic credentials.

## Current Behaviour

This is not being done. For faas-swarm it is essential since faas-swarm is accessible via the network from functions. Related issue: https://github.com/openfaas/faas-swarm/issues/31

## Possible Solution

Add a wrapper for the protected routes which injects the basic auth headers upstream.

**Comment by burtonr** [comment]
This was resolved by #850

**Comment by burtonr** [comment]
Derek close

**Comment by alexellis** [comment]
Thank you @burtonr
