### ISSUE TITLE
Proposal: Make Function Name Available To Function

### ISSUE THREAD

**Issue by s8sg** [openfaas/faas#845]
The idea here is to enable the function name available as a readable form.
Which later can be retrieved from the the handler or in the template. 
    
One friendly way could be from Environment Variable, say `OPENFAAS_FUNCTION `:
```go
nameOfTheFunc = os.Getenv("OPENFAAS_FUNCTION")
```

## Expected Behaviour
Once we build and deployed, it will have the environment variable `OPENFAAS_FUNCTION`, that can be used to retrieve the  function name. 

## Current Behaviour
To achieve such thing now we need to provide it as a environment in `stack.yml`
```yaml
  environment:
          OPENFAAS_FUNCTION: "functionname"
```
or via environment at deploy as 
```
--env OPENFAAS_FUNCTION=functionname
```
Although it's a valid way around, with an inbuilt solution it reduces the work to add a new environment variable in stack or provide it via cli. 

## Possible Solution
One way could be by appending it internally as a env, from `faas-cli deploy`

## Context
This could allow user to do Function Introspection for any operation that needs it, This operation could be : 
>* A call to itself via url.    
>*  A registration of the function from function with a url.
> * Provide a callback url from function
> *  logging with function name 
> * Other use cases that needs Function Introspection

**Comment by alexellis** [comment]
If this is something we want to do then it can be applied through the provider easily in one single place - or injected at the gateway into labels on create/update.

**Comment by alexellis** [comment]
@s8sg thanks for the suggestion. Do you have a practical need for this or is it a "nice to have"?

**Comment by alexellis** [comment]
Derek add label: proposal

**Comment by stefanprodan** [comment]
Injecting this variable from the Gateway will not work if you use the kubectl and the operator since it skips the Gateway API when you create a function this way. We could add this at the provider level.

**Comment by alexellis** [comment]
OK you're right. The Operator is an exception when used via kubectl.

**Comment by stefanprodan** [comment]
In Kubernetes getting the function name can be done by parsing the Hostname env var. The hostname it the pod ID that's prefixed with the function name.

**Comment by LucasRoesler** [comment]
The list of use cases provided are not fully supported by just this change, except for logging.  In each of the other cases it seems like the function would need to know other deployment information about the gateway and ingress configuration.

I am very sympathetic about the logging use case though.  The name could possibly injected using the `fieldRef` https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by s8sg** [comment]
I agree with the point. Theres way to provide it as a build time argument
and add it in some file while building the image. Or simply provide a
secret with function name

**Comment by alexellis** [comment]
For the implementation I'd rather inject an env-var from the provider like the suggestion outlines. This way if we change the name of the function pod in the future to be a GUID etc we can still support the use-case.

I just don't want us to do "busy-work" unless we see real value in this being added. It will touch faas-swarm, faas-nomad, faas-netes, openfaas-operator and faas-fargate, so it's not trivial.

**Comment by s8sg** [comment]
@alexellis I faced similar problem when I was implementing the `faaschain`. In a workflow it a very possible scenario that function need to call `itself`. Passing a `environment` variable with function name externally is a valid way around, only that we need to specify it seperately.  

As per the use case its not only limited to `logging`
For example a set of function might need to register themselves to a 3rd party `monitor system`
@lucasalexander raised a very valid point about the infra structure details might differ, although I was considering that the monitor system already know about the infra and how to reach the gateway. To achieve that another way around can possible be by calling a different system function that takes the function name as an input and return with the `pretty-url` providing the infra details. 
 
To register function to a monitoring system, I can also use gateway to `list`. Although in a deployment I might not want to monitor all functions but a set of them.

There have been similar interest in the docker swarm, although it has a problem, thats the container can be renamed but the env variable cant be. But for `openfaas` it's not the case. A container is always bound to a `function`.

Amazon Lambda provides a way to get the name from `context` as 
```js
console.log('functionName =', context.functionName)
```

and in Google Cloud Function
```js
process.env.FUNCTION_NAME;
```
