### ISSUE TITLE
Istio integration 

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas#851]
This is an overarching issue to keep track of the progress on making OpenFaaS compatible with Istio service mesh.

Goals:

- tracing function calls with Jaeger from Istio Gateway to the function pod and back (https://github.com/openfaas/faas-netes/issues/272)
-  inbound/outbound traffic monitoring for each OpenFaaS service with Prometheus 
-  isolate OpenFaaS core services and functions with Mixer policies 
-  mTLS between OpenFaaS Gateway and functions

Tasks:

- [x] add HTTP named port to Gateway (https://github.com/openfaas/faas-netes/pull/279) and functions (https://github.com/openfaas/faas-netes/pull/280  https://github.com/openfaas-incubator/openfaas-operator/pull/46)
- [x] allow Istio init container root access for Gateway pod (https://github.com/openfaas/faas-netes/pull/279)
- [x] remove absolute domains (ending dot) from the Gateway and  Queue Worker config (https://github.com/openfaas/faas-netes/pull/279)
- [x] mTLS: use wget for health checks (openfaas/faas-netes#279)
- [x] remove http client host overriding from the Gateway (https://github.com/openfaas/faas/issues/847) 
- [x] remove http client host overriding from Queue Worker (https://github.com/openfaas/nats-queue-worker/pull/37)

**Comment by alexellis** [comment]
@stefanprodan please update the tasks above with the current status

**Comment by stefanprodan** [comment]
@alexellis you could merge https://github.com/openfaas/nats-queue-worker/pull/37 first, do a release and I can update the Helm PR to include the new worker release.
