### ISSUE TITLE
Proposal: adopt bash as the preferred scripting shell and improve error handling

### ISSUE THREAD

**Issue by ewilde** [openfaas/faas#860]
## Expected Behaviour
* Scripts used to build, run tests and orchestrate CI should behave the same way when run on either linux or mac. Some developers use a mac and some use linux

* Scripts, in general, should exit if an error occurs and not continue regardless

## Current Behaviour
Most openfaas shell scripts I have come across reference the `#!/bin/sh` shebang. On current versions of mac osx this is a `bash` shell. On ubuntu this is a `dash` shell. This is not a problem if all the commands in the scripts are compliant with the bourne shell.

However since bash has arguably become the defacto standard for shell scripting, many non-compliant sh commands have found their way into openfaas sh scripts.

Consider this small example from: https://github.com/openfaas/certifier/blob/master/create-swarm-secret.sh

```sh
#!/bin/sh

if [[ $(docker secret ls | grep secret-api-test-key | wc -l) -eq 0 ]]
then
    echo $SECRET | docker secret create secret-api-test-key -
    echo "Swarm secret created"
else
    echo "Swarm secret already exists. Removing old secret secret-api-test-key"
    docker secret rm secret-api-test-key
    echo $SECRET | docker secret create secret-api-test-key -
    echo "Swarm secret created"
fi 
```

This works correctly on a `mac` as it runs under the `bash` shell. On Ubuntu if will throw an error because `[[` is not part of the `sh` scripting language. However, because there is no error handling the script continues. If we modify the script to include error handling we can see if fail properly on ubuntu:

```sh
#!/bin/sh

if [[ $(docker secret ls | grep secret-api-test-key | wc -l) -eq 0 ]]
then
    echo $SECRET | docker secret create secret-api-test-key -
    echo "Swarm secret created"
else
    errcode=$?
    if [ "$errcode" != 1 ]; then
      echo "[Error] Status code: $errcode" 
      exit 1
    fi
    echo "Swarm secret already exists. Removing old secret secret-api-test-key"
    docker secret rm secret-api-test-key
    echo $SECRET | docker secret create secret-api-test-key -
    echo "Swarm secret created"
fi
```

## Possible solution 1: Adopt bash
Instead of using the `#!/bin/sh` shebang use `#!/usr/bin/env bash`  <- safest way to locate bash, as some distros don't include bash in the normal location

> Note bash is not included by default on some minimal linux distributions such as alpine. Where minimalism is essential, we could fall back to using sh or add bash to the image (adds an extra 4mb)

**Pros**:  1. quick to implement only need to update shebang. 2. bash is the defacto standard scripting language

## Possible solution 2: Make all existing scripts `sh` compliant
**Pros**: 1. Might be more portable? could use inside alpine without installing bash
**Cons**: 1. Lots of scripts to update 2. Not many scripting examples on the internet use `sh` compared with `bash` 3. Mac developers would need to verify scripts somehow

## Error handling
Put `set -e` Line after shebang

**Comment by ivanayov** [comment]
Derek add label: proposal

**Comment by ivanayov** [comment]
Considering all the testing required after editing all scripts for `sh` and that there are no strong benefits from that, I would suggest going with solution 1.

One more reason, as listed in the pros, is that bash is the standard, so we should better stick to it.

**Comment by alexellis** [comment]
@ewilde I'm fine with option 1. Given the lack of response from the community on GitHub, do you want to socialise the idea on the Slack community before then going ahead and raising a PR?

Alex

**Comment by rdimitrov** [comment]
This is great, I'm also opting for the 1st one. Recently I had some troubles in that context and I believe it would be quite useful.

**Comment by alexellis** [comment]
Derek remove label: design/review

**Comment by alexellis** [comment]
Derek add label: design/approved

**Comment by alexellis** [comment]
Good to see we have consensus. @ewilde please go ahead and note there are quite a few projects to cover here - see the contributing page of the docs site for more. Includes openfaas-incubator org.

**Comment by alexellis** [comment]
@ewilde please can you provide an update?

**Comment by alexellis** [comment]
@ewilde has this work been completed now? Would you like to coordinate any remaining work via the issue?

**Comment by alexellis** [comment]
@ewilde Given that we've had no updates since January I'm closing this issue.

Feel free to open a new one if you need it.
