### ISSUE TITLE
Use distroless image for runtime images

### ISSUE THREAD

**Issue by Cerebus** [openfaas/faas#862]
In the interests of resource usage minimization and security, faas templates should use distroless images where available.

## Expected Behaviour
[Google distroless images](https://github.com/GoogleContainerTools/distroless) provide only necessary files for the contained application to run.  The resulting production image is substantially smaller in most instances.  

Images without even a lightweight distro also offer a smaller attack surface and hence better security.

## Current Behaviour 
Current images deploy using base images that contain things like package managers, but these are not required once the function is deployed.  

## Possible Solution
Templates can instead use [docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) to compose the application into a build container, and then copy the application and dependencies into the deployment container baselined on an appropriate distroless image.

**Comment by ivanayov** [comment]
+1 for this suggestion

I have thought about similar idea for minimising the images by separating the templates on 2 build stages, where the second image contains only a single binary, but didn't know it's already available with a multi-stage build.

My only concern about using [distroless](https://github.com/GoogleContainerTools/distroless) is that it looks like not being supported.

I think this issue should go to [templates](http://github.com/openfaas/templates) and [faas-cli](http://github.com/openfaas/faas-cli) repos.

**Comment by ivanayov** [comment]
Derek add label: proposal

**Comment by Cerebus** [comment]
Google's distroless is mainly just an example.  Docker multi-stage builds might have made it obsolete, but I need to dig into the bazel builds and see what's really happening in there.

**Comment by alexellis** [comment]
Unikernel-style microcontainers have their own maintenance issues and tradeoffs. 

Happy for you to fork the templates repo and do your own experimentation. The CLI will allow you to pull templates from anywhere. This will allow you to test out whether any additional changes are required. 

I don't see this as something we'll be approaching at this stage, but happy to revisit after your initial research. 

Alex

**Comment by alexellis** [comment]
Derek close: revisit
