### ISSUE TITLE
Community: Meet at Open Source Summit Edinburgh

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#863]
## Event

[Open Source Summit Edinburgh - October 22-24](https://osseu18.sched.com/list/descriptions/)

## What's happening?

A number of the community and contributors will be attending and it'd be great too see you there too.

I have a talk on OpenFaaS Cloud on the Monday and would love to set up an afternoon/evening meet-up or get-together.

[Monday, October 22 • 15:05 - 15:45 - Introducing OpenFaaS Cloud, a Developer-Friendly CI/CD Pipeline for Serverless - Alex Ellis, OpenFaaS project / VMware](https://osseu18.sched.com/event/FxXx/introducing-openfaas-cloud-a-developer-friendly-cicd-pipeline-for-serverless-alex-ellis-openfaas-project-vmware)

Let us know if you'll be there.

![](https://pbs.twimg.com/media/DmMeCUfVsAAdBCG.jpg)

Alex

## Confirmed

- @alexellis
- @johnmccabe 
- @ivanayov 

Please also let us know if you're in the area but not attending the main event.

**Comment by johnmccabe** [comment]
Yup

**Comment by ivanayov** [comment]
I'm there. Glad to meet you all :)

**Comment by affix** [comment]
Can't make the conference but the EICC is next to my office can meet up for a beer :)

**Comment by ewilde** [comment]
:+1: yup, I'll be attending

**Comment by alexellis** [comment]
Tagging @amouat who I've been talking to about arranging a small event. Potential talk from myself and @stefanprodan on Istio / OpenFaaS and maybe another topic?

**Comment by amouat** [comment]
Just to be clear, it would be as part of the Docker meetup and I am talking to other speakers as well. But it would be great to have something on OpenFaaS and Istio.

**Comment by alexellis** [comment]
Sure - we haven't found a way to organise a dedicated event or meet-up yet so may look to meet before the meet-up or in a coffee shop at some point around the event.

We'll get an abstract across on OpenFaaS + Istio for the Docker meet up 👍 

Alex

**Comment by amouat** [comment]
I'm sure the summit were offering spaces for meetups e.g. there is a blockchain meetup at the summit itself.

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Great to meet everyone and thanks for a top meet-up @amouat
