### ISSUE TITLE
Investigate: Invocation count 0 for some functions

### ISSUE THREAD

**Issue by ngcdev** [openfaas/faas#868]
Only functions invoked with `curl` have a count

This is more of a question than an issue per se. I have several functions. A couple of those functions are called by our SVN post commit hook. We're using `curl` to make those calls.

The other functions are being consumed by Mattermost (a team collaboration tool that allows integration with HTTP services).

I know all of them are working and responding correctly. However, when I see the invocation count with `faas-cli list` I get this:
```
Function                      	Invocations    	Replicas
bot-revision-notice           	586            	1    
bot-crypto                    	0              	1    
bot-picker                    	0              	1    
bot-appear-in                 	0              	1    
bot-greeter                   	0              	1    
bot-magic-ball                	0              	1    
bot-flip-coin                 	0              	1    
bot-revision-process          	0              	1    
bot-announcement              	0              	1    
bot-jira-comment              	596            	1 
```
The revision notice and jira comment functions are the ones called via curl. The others are called by Mattermost.
The last time I deployed the functions was 5 weeks ago.
I'm using faas-cli version 0.6.10
FaaS Gateway I believe is 0.8.3

Is the invocation count updated when some HTTP header is provided? A header that perhaps `curl` includes but not Mattermost?

P.S. Made a test with Postman and also the count didn't increase. But it does increase if I make an invocation from the OpenFaaS web UI

Thanks

**Comment by alexellis** [comment]
Hi @ngcdev thanks for raising this issue with us. 

What is the best way to reproduce the issue? Can you give a series of steps? What language template are you using? (Is it modified or official?)

I'd also encourage you to fill out the whole template with all the information we ask for so that we can better help you. If in doubt look at the template here -> https://github.com/openfaas/faas/blob/master/.github/ISSUE_TEMPLATE.md

On a related note since you're using OpenFaaS it'd be good to list your company on our end-users page -> https://docs.openfaas.com/#users-of-openfaas via https://github.com/openfaas/faas/issues/776

Alex

**Comment by alexellis** [comment]
Another thing you can do is to look up the gateway's raw metrics by adding:

```
/_metrics
```

To the end of the gateway URL.

Look for `gateway_invocation_count`.

Perhaps the reason we're seeing 0 is due to the results being non-200 results? (not sure)

**Comment by kenfdev** [comment]
Thanks @ngcdev . As Alex says, we would like more context to reproduce this.

An additional question from me is:

> But it does increase if I make an invocation from the OpenFaaS web UI

Are you saying that the functions below get counted if using `curl`?

```
bot-crypto                    	0              	1    
bot-picker                    	0              	1    
bot-appear-in                 	0              	1    
bot-greeter                   	0              	1    
bot-magic-ball                	0              	1    
bot-flip-coin                 	0              	1    
bot-revision-process          	0              	1    
bot-announcement              	0              	1    
```

**Comment by ngcdev** [comment]
Thanks for your responses and sorry about the delay.

I have to adjust the issue, because further investigation showed that curl calls are not being recorded as invocations either. I thought that we were calling `bot-jira-comment` and `bot-revision-notice` from the SVN hooks, but in reality, we're calling (via curl) `bot-revision-process` (which shows 0 invocations). That function internally is calling the prior 2 (following documentation on calling functions locally) So only functions invoked within OpenFaaS interface or internal function calls are getting invocation counts.

I'll start one function from scratch to verify and I'll update the original post to follow the template.

**Comment by ngcdev** [comment]
OK...so it seems to be an issue with OpenFaaS being behind a nginx reverse proxy. The moment that I tried to replicate it calling it locally (localhost) with `curl` it worked. But when I use the URL that is exposed via nginx, it's not working. Also I'm using basic authentication in nginx.

It will be a little hard to replicate for someone else. I'll try to replicate without basic authentication next, to see if that has any bearing on it.

**Comment by ngcdev** [comment]
Regarding the 200 status, this is in the log of nginx for the call:
```
nginx.1    | faas.ngcsoftware.com 40.70.10.1 - ovhYDns6MjaUuPDtxBnEHurTd [18/Sep/2018:10:35:13 -0400] "GET /function/bot-greeter HTTP/1.1" 200 86 "-" "curl/7.47.0"
```
The `ovhYD...` is the user name for basic auth.

**Comment by ngcdev** [comment]
So this environment has 3 variants:
- Running behind an nginx reverse proxy (not an issue, replicated in another machine and works fine)
- Using Basic Authentication (not an issue, replicated in another machine and works fine)
- Using SSL, nginx handles it and the connection to OpenFaaS is over regular HTTP (no yet discarded as the culprit)

I was able to to get a count invocation on every scenario, except the SSL. I'll have to try that with some other URL and certificate. I'll post more info once I can replicate it properly.

**Comment by alexellis** [comment]
OpenFaaS Cloud is running with Nginx as Ingress on Kubernetes with SSL enabled. You can access my dashboard and then one of the public functions for instance `fn1` and then see the invocation count go up.

https://system.o6s.io/dashboard/alexellis

Do you have any specifics on how to reproduce as of now?

Alex

**Comment by ngcdev** [comment]
I have another piece of information... the `faas` DNS  (as opposed to the `faasadmin`) has a rule in nginx to block the UI url (gateway?)... maybe this is causing something not to register properly with the counters, although the functions are being executed. It seems execution is being done directly with the swarm service instead of going via the gateway...

**Comment by ngcdev** [comment]
OK so I'm going to close it, because once I removed the nginx restriction to the getaway go via that URL to execute the functions, the invocation counters update properly. It was the setup of this environment that was going directly to the swarm service instead of the gateway.
Sorry for the disturbance.
