### ISSUE TITLE
Proposal: Edit metadata for functions from UI

### ISSUE THREAD

**Issue by padiazg** [openfaas/faas#870]
It is necessary that the UI handle the same information as the CLI.
It would be interesting to be able to visualize or modify the labels and annotations also from the UI.

Actually you can define labels & annotations throwght the CLI but not from the UI.

**Comment by viveksyngh** [comment]
Derek Add label: proposal

**Comment by viveksyngh** [comment]
Derek add label: area/ux

**Comment by alexellis** [comment]
Derek close
