### ISSUE TITLE
Support question: metrics with Swarm

### ISSUE THREAD

**Issue by poerwiyanto** [openfaas/faas#879]
## Expected Behaviour

Gateway service count returns no. of replicas and auto scaling works.

## Current Behaviour

Gateway service count returns "no data points" error in Prometheus and auto scaling did not work (checked from docker service ps command) even APIHighInvocationRate is firing.

## Steps to Reproduce (for bugs)

1. Deploy stack in Docker Swarm with 2 nodes.
2. Deploy First Python Function tutorial.
3. curl the function using while true to trigger APIHighInvocationRate.
4.

## Context

I am trying to learn OpenFaaS and need the auto scaling.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.06.1-ce, Docker Machine 0.14.0
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi thanks for raising an issue please could you work through the troubleshooting guide and report back to us? We are unaware of any issues with metrics or autoscaling at this time.

**Comment by poerwiyanto** [comment]
Hi, Alex. Thanks for your fast response. I will try the troubleshooting and get back to you.

**Comment by alexellis** [comment]
I'd also advise taking a look at this - https://github.com/openfaas/workshop/blob/master/lab9.md

**Comment by poerwiyanto** [comment]
Actually, I followed the workshop and got stuck in lab9 because prometheus returns "no data points" for gateway_service_count and the no. of replicas for my function is stuck at 1 even after APIHighInvocationRate is triggered. I'm still figuring it out. Thanks a lot.

**Comment by alexellis** [comment]
So you're using a docker-machine VM on top of Ubuntu using the KVM driver right?

Is this all with what's in master? 

What function did you deploy? Maybe try the store too.

**Comment by poerwiyanto** [comment]
![screenshot from 2018-09-19 10-40-53](https://user-images.githubusercontent.com/12395856/45771113-7464fd00-bc6e-11e8-927f-4b2e0dfbef58.png)
![screenshot from 2018-09-19 10-42-25](https://user-images.githubusercontent.com/12395856/45771114-7464fd00-bc6e-11e8-8f68-70ac82e2dd4f.png)
![screenshot from 2018-09-19 10-43-15](https://user-images.githubusercontent.com/12395856/45771115-74fd9380-bc6e-11e8-8e76-0a99b8b3a841.png)
Hi, Alex. Sorry for bothering you. I captured my metrics (I used stefanprodan's faas-grafana). When I used Prometheus, there was no gateway_service_count in metrics options.

Yes, I used 2 docker-machine VMs on top of Ubuntu using VirtualBox driver, but I tried in DigitalOcean (https://github.com/openfaas/faas/blob/master/guide/deployment_digitalocean.md) and faced the same problem. Is there anything I am doing wrong?

**Comment by LucasRoesler** [comment]
I deployed my own 2 node swarm and found this in my gateway logs

```sh
func_gateway.1.jaut08aptbtz@myvm2    | 2018/09/19 18:24:21 Alert received.
func_gateway.1.jaut08aptbtz@myvm2    | 2018/09/19 18:24:21 {"receiver":"scale-up","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"APIHighInvocationRate","function_name":"nodeinfo","monitor":"faas-monitor","service":"gateway","severity":"major","value":"7.4"},"annotations":{"description":"High invocation total on ","summary":"High invocation total on "},"startsAt":"2018-09-19T18:24:16.175098924Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://5356532ccb6a:9090/graph?g0.expr=sum+by%28function_name%29+%28rate%28gateway_function_invocation_total%7Bcode%3D%22200%22%7D%5B10s%5D%29%29+%3E+5\u0026g0.tab=1"}],"groupLabels":{"alertname":"APIHighInvocationRate","service":"gateway"},"commonLabels":{"alertname":"APIHighInvocationRate","function_name":"nodeinfo","monitor":"faas-monitor","service":"gateway","severity":"major","value":"7.4"},"commonAnnotations":{"description":"High invocation total on ","summary":"High invocation total on "},"externalURL":"http://4ba1a6cc8430:9093","version":"4","groupKey":"{}:{alertname=\"APIHighInvocationRate\", service=\"gateway\"}"}
func_gateway.1.jaut08aptbtz@myvm2    |
func_gateway.1.jaut08aptbtz@myvm2    | 2018/09/19 18:24:21 [Scale] function=nodeinfo 0 => 4.
func_gateway.1.jaut08aptbtz@myvm2    | 2018/09/19 18:24:21 error scaling HTTP code 401, http://faas-swarm:8080/system/scale-function/nodeinfo
func_gateway.1.jaut08aptbtz@myvm2    | 2018/09/19 18:24:21 [error scaling HTTP code 401, http://faas-swarm:8080/system/scale-function/nodeinfo]
func_gateway.1.jaut08aptbtz@myvm2    | 2018/09/19 18:24:21 Alert received.
```
Note the 401 errors during the scaling request.  A scaling request is being made

I also noticed that when we try to scrape the service count here https://github.com/openfaas/faas/blob/ddc59f6403331c56aa4167756572f093e2f09875/gateway/metrics/exporter.go#L79-L86

it does not seem to set any authentication headers, so that would explain why `gateway_service_count` is missing

**Comment by LucasRoesler** [comment]
@poerwiyanto can you try disabling auth on the faas-swarm component.  You can do this by modifying the `docker-compose.yaml` file so that `basic_auth: "false"` in the `faas-swarm.environment`

**Comment by alexellis** [comment]
The part of the issue template asks users to provide logs as part of the troubleshooting steps.

Once @LucasRoesler was able to do this I could track down the error to needing additional authentication for the faas-swarm component. I've mentioned the workarounds on the linked PR above.

@poerwiyanto please see the instructions for updating your local environment. This will get you past the issue and thanks for reporting it.

**Comment by poerwiyanto** [comment]
Okay, thanks for your help, Alex and Lucas.

**Comment by alexellis** [comment]
Derek lock: old thread
