### ISSUE TITLE
Scale request via /system/scale-function/ ignores auto-scaling labels

### ISSUE THREAD

**Issue by ivanayov** [openfaas/faas#882]
After deploying a function with scaling limits `com.openfaas.scale.max = 4`, running
```
curl -X POST http://127.0.0.1:8080/system/scale-function/scaling-test -d '{"service": "scaling-test", "replicas": 10}'
```
causes the function to scale up to 10:

```
{  
   "name":"scaling-test",
   "image":"scaling-test:latest",
   "invocationCount":0,
   "replicas":10,
   "envProcess":"python3 index.py",
   "availableReplicas":0,
   "labels":{  
      "com.openfaas.function":"scaling-test",
      "com.openfaas.scale.max":"4",
      "com.openfaas.scale.min":"1",
      "function":"true"
   },
   "annotations":null
}
```
## Expected behaviour
Replicas should be at most 4

## Steps to Reproduce (for bugs)

1. Deploy function `myFn` with 
```
labels:
  com.openfaas.scale.min: 1
  com.openfaas.scale.max: 4
```
2. Run 
```
curl -X POST http://127.0.0.1:8080/system/scale-function/myFn -d '{"service": "myFn", "replicas": 10}'
```
3. Check `http://127.0.0.1:8080/system/function/myFn`

## Context

Reproduced while writing a certifier test [certifier#13](https://github.com/openfaas/certifier/issues/13)

**Comment by alexellis** [comment]
What do we think about this? The scaling limits are for the auto-scaler not for the API endpoint, so should the API endpoint be subjected to the same limits?

**Comment by alexellis** [comment]
@openfaas/core @openfaas/faas-team what do we think?

**Comment by stefanprodan** [comment]
I think the auto-scaling limits should not affect the scaling API.

**Comment by rgee0** [comment]
I think I agree with Stefan. There's a distinction between the two. 

Should the label keys be more indicative of purpose/intuitive?

```
labels:
  com.openfaas.autoscale.min: 1
  com.openfaas.autoscale.max: 4
```

Can appreciate probably not an easy change given they've been here forever, and the body of material detailing the existing. Perhaps something to mull over?

**Comment by alexellis** [comment]
Happy to take a PR to the API swagger documentation for this endpoint stating that it is not subject to autoscaling labels.

**Comment by alexellis** [comment]
Derek close: works as designed

**Comment by alexellis** [comment]
Ivana please raise a PR to the swagger docs if you think it'd be worth documenting this.
