### ISSUE TITLE
Cannot connect to OpenFaaS on URL: http://127.0.0.1:8080

### ISSUE THREAD

**Issue by FlankMiao** [openfaas/faas#898]
https://github.com/openfaas/workshop/blob/master/lab1.md
https://github.com/openfaas/workshop/blob/master/lab2.md
I follow these, but when I  execute [faas-cli list] ，I got this message:"Cannot connect to OpenFaaS on URL: http://127.0.0.1:8080"
![doc](https://user-images.githubusercontent.com/19262116/46652726-82a39a80-cbd6-11e8-8d05-30d9a3d414af.PNG)

the [docker service ls] command can list the services, alsothe port .but I can,t access it on the browser.
windows 10 
docker for windows win73
I lookup the isssues :it says set the env "OPENFAAS_URL=127.0.0.1:8080",but it doesn,t work

**Comment by FlankMiao** [comment]
when I input [docker stack ps func], I got this :"ERROR : "no suitable node (scheduling …""

**Comment by FlankMiao** [comment]
@rgee0 no, I use the default windows containers,ok, I wil  try

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by FlankMiao** [comment]
@rgee0  It worked, thanks a lot :).

**Comment by ivanayov** [comment]
Derek close

**Comment by alexellis** [comment]
@rgee0 / @ivanayov please can you review the pre-reqs for the workshop and see if there is a good place to add a > Note: about using "Linux Containers"?
