### ISSUE TITLE
Suggest: verify args when deploy a  new function  

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [openfaas/faas#901]
I suggest should to verify arguments  when our use `OpenFaas Portal` to deploy a new function

## Expected Behaviour

If args `Docker Image` or `Function name` is empty, `deploy` button should disabeld or show warning message , not send request to backend server 

## Current Behaviour

If arguments `Docker Image` or `Function name` is empty, can also send request get error

## Possible Solution

1. we can verify args when deploy a new function only `frontend`
2. we also verify args in `backend`

some screens as follow:
<img src="https://user-images.githubusercontent.com/3310967/46657044-f7c89d00-cbe1-11e8-92c3-9610ca989842.png" width="600" height="400" />

<img src="https://user-images.githubusercontent.com/3310967/46657084-0d3dc700-cbe2-11e8-853f-ebda4a1b8a83.png" width="600" height="400" />

**Comment by martindekov** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
This sounds good to me. @burtonr @padiazg @kenfdev who can take this?

**Comment by burtonr** [comment]
@alexellis funny, I was working on this as you mentioned me... The PR for this is ready for review #1014
