### ISSUE TITLE
error when I build the go function example

### ISSUE THREAD

**Issue by FlankMiao** [openfaas/faas#902]
**faas-cli build -f gohash.yml:**
**I got this:**
[0] > Building gohash.
Clearing temporary build folder: ./build/gohash/
Preparing ./gohash/ ./build/gohash/function
Building: gohash:latest with go template. Please wait..
Sending build context to Docker daemon  6.656kB
Step 1/20 : FROM golang:1.9.7-alpine3.8 as builder
 ---> b0260be938c6
Step 2/20 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Using cache
 ---> 5e42443212b4
Step 3/20 : WORKDIR /go/src/handler
 ---> Using cache
 ---> b09e269be47c
Step 4/20 : COPY . .
 ---> Using cache
 ---> b027adf140c3
Step 5/20 : RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
 ---> Running in 62842e792955
Run "gofmt -s -w" on your Golang code
The command '/bin/sh -c test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }' returned a non-zero code: 1
2018/10/09 20:06:31 **ERROR - Could not execute command: [docker build -t gohash:latest .]**

**but it,s ok in the https://labs.play-with-docker.com**

**Comment by FlankMiao** [comment]
@martindekov  yeah, I found it in the issues, I didn,t format by the gofmt, I will try.

**Comment by martindekov** [comment]
Try shell command `gofmt -s -w handler.go` into your handler directory and try building again

**Comment by martindekov** [comment]
Derek close: not an issue

**Comment by martindekov** [comment]
@FlankMiao If you still have problems you can still comment them here

**Comment by FlankMiao** [comment]
@martindekov  I solved this in other issue. I set the git config ["core.autocrlf"] to [false] and repull the template , it worked. Thanks a lot :).

**Comment by martindekov** [comment]
You're welcome @FlankMiao 🙂

**Comment by marlexct** [comment]
Hello, Martindekov, the shell command you said worked pretty fine for that step, 9/24, but now I have another error. (By the way, I am a newbie in golang). I am trying to build an updated gohash function following this tutorial https://blog.alexellis.io/serverless-golang-with-openfaas. But I have the following error. I am using openfaas on kubernetes. Although, I can still invoke the gohash function but it returns the previuos one. 

Please, somebody help me.

root@ip-172-31-12-150:~/work/src/functions# faas-cli build -f gohash.yml
[0] > Building gohash.
Clearing temporary build folder: ./build/gohash/
Preparing ./gohash/ ./build/gohash//function
Building: marlexct12/gohash:latest with go template. Please wait..
Sending build context to Docker daemon  26.11kB
Step 1/24 : FROM openfaas/classic-watchdog:0.15.4 as watchdog
 ---> a775beb8ba9f
Step 2/24 : FROM golang:1.11-alpine3.10 as builder
 ---> e116d2efa2ab
Step 3/24 : ARG ADDITIONAL_PACKAGE
 ---> Using cache
 ---> b660738abd32
Step 4/24 : ARG CGO_ENABLED=0
 ---> Using cache
 ---> 7e61fb8a16f0
Step 5/24 : COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
 ---> Using cache
 ---> 0b8967204c00
Step 6/24 : RUN chmod +x /usr/bin/fwatchdog
 ---> Using cache
 ---> d1cfb2cf7dd5
Step 7/24 : WORKDIR /go/src/handler
 ---> Using cache
 ---> c0331d5ee9d4
Step 8/24 : COPY . .
 ---> Using cache
 ---> 531753febb77
Step 9/24 : RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
 ---> Using cache
 ---> 3a849a88a835
Step 10/24 : RUN CGO_ENABLED=${CGO_ENABLED} GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover
 ---> Running in 4445c4a0ea5e
main.go:9:2: import "handler/function" is a program, not an importable package
The command '/bin/sh -c CGO_ENABLED=${CGO_ENABLED} GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover' returned a non-zero code: 1
2019/09/20 18:05:16 ERROR - Could not execute command: [docker build -t marlexct12/gohash:latest .]

**Comment by alexellis** [comment]
Still having the same problem? It can't be.. let's open a new issue please 

Or perhaps ask on Slack?
