### ISSUE TITLE
question about the watchdog and of-watchdog

### ISSUE THREAD

**Issue by FlankMiao** [openfaas/faas#905]
I deploy a go function by this template:

![go](https://user-images.githubusercontent.com/19262116/46779335-e8646380-cd49-11e8-88ee-b19a16d36b11.PNG)

and other go function by this template:
**faas template pull https://github.com/openfaas-incubator/golang-http-template**

My question is:
Is the first go func has the watchdog and the second has the of-watchdog?
If so, it means the two kinds of watchdog can exist together?

**Comment by martindekov** [comment]
Hello there @FlankMiao  I like your curiosity on the project 👍 

The answer to your first question is:
Yes the two templates use different watchdogs as seen here: 
go code in [original templates](https://github.com/openfaas/templates/blob/master/template/go/Dockerfile)
go code in the `golang-http-template` [openfaas-incubator templates]( https://github.com/openfaas-incubator/golang-http-template/blob/60e2a03849667e7bbb087dee9ff3b6e8e49869ed/template/golang-http/Dockerfile#L5)

The answer to the second question:
The watchdog is executed when you try to access the container(send request to the deployed function) so I guess you either use one or the other.

**Comment by martindekov** [comment]
Derek add label: question

**Comment by FlankMiao** [comment]
@martindekov  ok, I got it. Thanks :).
