### ISSUE TITLE
Question about the function with of-watchdog

### ISSUE THREAD

**Issue by FlankMiao** [openfaas/faas#907]
I build a go function demo base on this:
$ faas template pull **https://github.com/openfaas-incubator/golang-http-template**
the doc about the watchdog says:
https://docs.openfaas.com/architecture/watchdog/
"The newer of-watchdog mentioned below is similar, but ideal for streaming use-cases or when an expensive resource needs to be maintained between requests such as a database connection, ML model or other data."
So I write a go demo about db connection and it contails 3rd dependency.
So I execute [dep init], [dep ensure].
When I build the function[faas-cli build -f ./db.yml], I got this:

Step 7/17 : RUN CGO_ENABLED=0 GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover
 ---> Running in 3840629d678a
# handler
**./main.go:36:39: cannot use req (type "handler/vendor/github.com/openfaas-incubator/go-function-sdk".Request) as type "handler/function/vendor/github.com/openfaas-incubator/go-function-sdk".Request in argument to function.Handle**
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover' returned a non-zero code: 2
2018/10/12 15:07:19 ERROR - Could not execute command: [docker build -t db:latest .]

When I delete the github.com/openfaas-incubator/go-function-sdk dependency in the vendor dir, It works.
Is there any better way to solve this?

**Comment by martindekov** [comment]
Hello @FlankMiao

In order to create new function with that template you should
'''
faas-cli new function --lang=golang-http --prefix...
'''
with the template present

This is because go and golang-http are using 'req' as variable name

Hope that helps.

**Comment by martindekov** [comment]
Derek add label: question

**Comment by FlankMiao** [comment]
@marcosnils  When I use the go-middleware template. It.s ok.
