### ISSUE TITLE
Adding metrics about function invocation status to prometheus

### ISSUE THREAD

**Issue by avneesh91** [openfaas/faas#913]
Currently the Prometheus deployment for openfaas allows me to make metric queries about the function invocations ,However there is no way see:
1. Number of requests in a specified time window which resulted in a specified status.
2. Average time take by successful/failing requests.

or any sort of metric related to the HTTP of the request. 

As a user it is extremely important for me to be able see how much time a successful invocation of my function is taking on an average.

This is already logged  here: https://github.com/openfaas/faas/issues/703. 
## Expected Behaviour

Ideally status code/status identifier data along with the  function invocation data should be propagated to Prometheus.

This would enable users to draw out detailed information regarding average response times across different statuses.
## Current Behaviour

Currently there is a get_functions_seconds metric which while gives me an average response time for all the functions, there is however no status code associated with it

## Possible Solution

1. Add the response status code type to the existing get_functions_seconds histogram and push to Prometheus.
2. Create a separate metric with this(and possible more information about the function invocation).

## Context

I have been using openfaas to run a couple of function deployments, however I have been getting complaints about my function taking a more time that usual. Though I have made certain amount of optimizations to my code, I cannot see if the response time for successful invocations have has improved.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by LucasRoesler** [comment]
The gateway currently records a metric for the request status and the histogram that you mentioned for the timing

```
# HELP gateway_function_invocation_total Individual function metrics
# TYPE gateway_function_invocation_total counter
gateway_function_invocation_total{code="200",function_name="nodeinfo"} 4
# HELP gateway_functions_seconds Function time taken
# TYPE gateway_functions_seconds histogram
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.005"} 0
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.01"} 0
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.025"} 0
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.05"} 0
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.1"} 0
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.25"} 4
gateway_functions_seconds_bucket{function_name="nodeinfo",le="0.5"} 4
gateway_functions_seconds_bucket{function_name="nodeinfo",le="1"} 4
gateway_functions_seconds_bucket{function_name="nodeinfo",le="2.5"} 4
gateway_functions_seconds_bucket{function_name="nodeinfo",le="5"} 4
gateway_functions_seconds_bucket{function_name="nodeinfo",le="10"} 4
gateway_functions_seconds_bucket{function_name="nodeinfo",le="+Inf"} 4
gateway_functions_seconds_sum{function_name="nodeinfo"} 0.5221564
gateway_functions_seconds_count{function_name="nodeinfo"} 4
# HELP gateway_service_count Docker service replicas
# TYPE gateway_service_count gauge
gateway_service_count{function_name="nodeinfo"} 1

**Comment by alexellis** [comment]
Related - see how we do this in OpenFaaS Cloud - https://github.com/openfaas/openfaas-cloud/blob/master/system-metrics/handler.go

**Comment by LucasRoesler** [comment]
I think we can generate all of the required values by updating the `PrometheusMetricsNotifier` to tag the histogram with the status code.  We currently do this

```go 
// Notify records metrics in Prometheus
func (p PrometheusFunctionNotifier) Notify(method string, URL string, originalURL string, statusCode int, duration time.Duration) {
	seconds := duration.Seconds()
	serviceName := getServiceName(originalURL)

	p.Metrics.GatewayFunctionsHistogram.
		WithLabelValues(serviceName).
		Observe(seconds)

	code := strconv.Itoa(statusCode)

	p.Metrics.GatewayFunctionInvocation.
		With(prometheus.Labels{"function_name": serviceName, "code": code}).
		Inc()
}
```


it should be a simple change to something like this

```go 
// Notify records metrics in Prometheus
func (p PrometheusFunctionNotifier) Notify(method string, URL string, originalURL string, statusCode int, duration time.Duration) {
	seconds := duration.Seconds()
	serviceName := getServiceName(originalURL)
	code := strconv.Itoa(statusCode)
        labels := prometheus.Labels{"function_name": serviceName, "code": code}

	p.Metrics.GatewayFunctionsHistogram.
		With(labels).
		Observe(seconds)

	p.Metrics.GatewayFunctionInvocation.
		With(labels).
		Inc()
}
```

**Comment by avneesh91** [comment]
@LucasRoesler This is what I thought about doing, but I didn't really want to change any existing metric(I wasn't sure if this would break anything - I am a Prometheus Noob).

So I ended up adding another metric which pretty much does the same thing. I can go ahead and submit a pull request if this is the direction we want to go in(since I pretty much have the whole thing done).

Also does https://github.com/openfaas/faas/issues/703 refer to the same thing we are discussing here or something else?!?!

**Comment by LucasRoesler** [comment]
703 Seems to be the same.  

I think that adding a new tag should be safe, but I will need to do some more reading to verify.  The data in prometheus is immutable once it is stored.  So it will not change any existing data that has already been scrapped.

**Comment by LucasRoesler** [comment]
I don't think adding an additional tag to an existing metric should break anything because all of the previous tags will still exist. Prometheus won't delete the old data, it will just not match queries that use the new tag against the old data. 

It should be simple enough to test by deploying the old gateway, load testing a function, deploy the new gateway, load test again, and then query Prometheus over that time period to see that a query without the status tag sees both sets of data.

**Comment by LucasRoesler** [comment]
As far as design goes, adding the status code seems to be normal or expected. The Prometheus with docs use an example with http requests and clearly use and show you how to query the status code, https://prometheus.io/docs/prometheus/latest/querying/examples/

**Comment by s8sg** [comment]
Can we also change the `code` to `status` providing more similarity to the proposed approach?

**Comment by alexellis** [comment]
We should not make breaking changes to the API @s8sg. 

See the new metrics: https://docs.openfaas.com/architecture/metrics/

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Please see the latest set of standard HTTP metrics
