### ISSUE TITLE
A question about how to run a Dockerfile on Openfaas

### ISSUE THREAD

**Issue by angyauyu** [openfaas/faas#914]
Hi all, I am a beginner of Openfaas, I want to build a Tensorflow application on Openfaas by using a dockerfile based on https://github.com/plutov/packagemain/tree/master/04-tensorflow-image-recognition . I understand that  I need to edit the dockerfile before successfully running it on Openfaas, but I do not know how to rewrite the dockerfile properly.
I'd appreciate it if anyone can tell me what I should do about it. Thank you very much!

**Comment by alexellis** [comment]
Have a look at this as an example of TensorFlow: https://github.com/faas-and-furious/inception-function

Hope it helps

Alex

**Comment by alexellis** [comment]
You may also find this useful but I'd think it's better to run TensorFlow in Python. https://blog.alexellis.io/cli-functions-with-openfaas/

**Comment by alexellis** [comment]
Derek close: question answered, but feel free to keep commenting 👍
