### ISSUE TITLE
Support: General question about openfaas function retries

### ISSUE THREAD

**Issue by tal181** [openfaas/faas#918]
Hi,
Is there a retry mechanism that invokes a function if it fails ?
Thanks,
Tal

**Comment by alexellis** [comment]
Hi @tal181,

Thanks for your interest in the project. I'm going to ask you to fill out the whole issue template and give us all the context and information you have available.

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

If we don't hear from you then I'll close this issue/question as invalid in a few days.

Alex

**Comment by alexellis** [comment]
Update: @tal181 reported over a direct email to me that his functions were being invoked via an asynchronous route and taking longer than the configured asynchronous timeout to finish. This resulted in them being executed again. This behaviour is documented under the following page: https://docs.openfaas.com/deployment/troubleshooting/#timeouts-asynchronous-invocations

I'll close for reference and leave this searchable on Google etc.
