### ISSUE TITLE
Function suggestion: Password generator encrypted via openssl

### ISSUE THREAD

**Issue by pascalandy** [openfaas/faas#92]
I'm simply suggesting to add this function. I use it to store passwords (while ensuring they are never plain-text) in our local documents. I used the container Alpine and installed openssh. 

Just replace the master password 'FancyPasswordHere' with yours.

**1) fct_crypt**

```
#### ENCRYPT
#Generate a 32 characters password
STEP1=$(docker run --rm alpine sh -c \
"cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1")
#Show the password
echo "$STEP1" && echo
#Encrypt the pass
STEP2=$(echo "$STEP1" | openssl enc -aes-256-cbc -a -k "FancyPasswordHere")
STEP1="null"
#Create a variable so it will be quick to copy-paste it later
STEP3="THIS_VAR='$STEP2'"
#Show the final string to copy in your files
echo "$STEP3" && echo
# Copy it in the clipboard (mac)
echo $STEP3 | pbcopy
echo "Just paste your encrypted password into your files."
```

**2) fct_decrypt**

Copy-paste back the output of the previous command. ie:
`THIS_VAR='U2FsdGVkX19YVGj32Z0lb1YlJbD2S3/wa9GQAliwOwPWgvSXHQ1gLnkgNovzMdtd
pk7atELI8iWVAql65rmMQQ=='`, then run

```
#### DECRYPT
echo "Copy-paste back the output of the previous command. Then run:"
echo "$THIS_VAR" | openssl enc -aes-256-cbc -d -a -k "FancyPasswordHere"
```

Cheers!
https://twitter.com/askpascalandy

**Comment by alexellis** [comment]
Hi Pascal - this looks interesting. Did you fancy creating a function for it?

You can start with the base alpine function, you shouldn't need to add anything other than your shell script afterwards.

Here's an example for getting started - https://github.com/alexellis/faas/tree/master/sample-functions/AlpineFunction

Alex

**Comment by pascalandy** [comment]
Hey Alex!

Right now I run this locally only. No functions per say. It would be great to put our master password within a secret as well.

At this point I'm lazy (a.k.a need to manage stuff in my prod first). If you don't want to adapt it leave it there and I'll jump on it on day :)

Cheers!

**Comment by alexellis** [comment]
Adding label - revisit, will come back to this and close for now. Feel free to re-open and add to the discussion.

**Comment by VitorFalcao** [comment]
@alexellis I would like to work on this as well. Do you have any further instructions?

**Comment by alexellis** [comment]
Derek add label: revisit

**Comment by alexellis** [comment]
This was a community suggestion for a utility function. We could use your help with the SNS queue if you'd like to start there?

Marking issue as Revisit for future follow-up
