### ISSUE TITLE
Cannot provide fprocess with args containing an equals sign

### ISSUE THREAD

**Issue by TheWonn** [openfaas/faas#921]
We'd like to be able to pass JVM args to a process run by OpenFaaS using the `java8` template. However when adding JVM args to the `fprocess` env var in the templated Dockerfile, anything after an equals sign is stripped off.

## Expected Behaviour
A Dockerfile containing `ENV fprocess="java com.openfaas.entrypoint.App -Dhttp.proxyHost=http.foo.com -Dhttp.proxyPort=8000"` should result in the following process being invoked: `java com.openfaas.entrypoint.App -Dhttp.proxyHost=http.foo.com -Dhttp.proxyPort=8000`

## Current Behaviour
A Dockerfile containing `ENV fprocess="java com.openfaas.entrypoint.App -Dhttp.proxyHost=http.foo.com -Dhttp.proxyPort=8000"` result in the following process being invoked: `java com.openfaas.entrypoint.App -Dhttp.proxyHost=`

## Possible Solution
Not sure, but we expect it's got something to do with how env vars are being split somewhere. We had a look through the codebase, but couldn't find it before having to move onto something else.

## Steps to Reproduce (for bugs)
1. Scaffold a Java project
2. Amend Dockerfile's `ENV fprocess=` line to include `-Dfoo=bar`
3. Build, push, deploy
4. `kubectl exec` into the resulting pod
4. `ps`
4. Observe `java com.openfaas.entrypoint.App -Dfoo` and not `java com.openfaas.entrypoint.App -Dfoo=bar`

## Context
We can't specify an HTTP proxy for our function, so can't hit stuff in a corporate network when using Java.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
version: 0.7.6

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:21Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS 10.11.6 El Capitan

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by ivanayov** [comment]
Hi @TheWonn 

I reproduced the issue. Looking into it.

**Comment by alexellis** [comment]
You should just set this via environmental variables in the stack.yml file.

**Comment by alexellis** [comment]
Example:

```
JAVA_OPTS="-Dhttp.proxyHost=http://proxy.memorynotfound.com -Dhttp.proxyPort=80"
```

**Comment by alexellis** [comment]
Derek close: resolved. Please feel free to keep commenting.
