### ISSUE TITLE
Support: User config error with "config map"

### ISSUE THREAD

**Issue by KunWangV** [openfaas/faas#923]
I run the command "./deploy_stack.sh" but get a problem. my docker version is "18.06.1-ce-mac73 (26764)"

> ConfigMap "prometheus_config" is invalid: metadata.name: Invalid value: "prometheus_config": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by ivanayov** [comment]
Hi @KunWangV 

I cannot reproduce.
Did you do any changes to your configuration?
Can you please share the exact steps you followed?

Ivana

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by alexellis** [comment]
@KunWangV you need to fill out the whole template to receive support from the community. Please edit your issue and give all of the following: https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

**Comment by alexellis** [comment]
Derek close: invalid

**Comment by alexellis** [comment]
No response from user
