### ISSUE TITLE
Windows deploy_stack.ps1 does not setup basic auth secrets

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas#928]
## Expected Behaviour

Windows `deploy_stack.ps1` should set the `basic-auth-user` and `basic-auth-password` secrets if absent.

## Current Behaviour

The `deploy_stack.ps1` ignores the secrets.

## Possible Solution

Update the Powershell script to prompt for the user/password if not already created.

## Steps to Reproduce (for bugs)

1. Run `deploy_stack.ps1` on a Windows Docker Swarm with/without the http basic auth secrets created.

## Context

Currently using Windows 10.

## Your Environment

- using the script from the latest on master (at the time of raising the issue openfaas/faas@0a5e343c5de4acc697d89542a79d204edaf39c9)

**Comment by alexellis** [comment]
Can you generate a secret so that we have some consistency? Does Powershell offer something similar to bash?

**Comment by johnmccabe** [comment]
Yeah should be feasible.
