### ISSUE TITLE
Suggestion: Powershell HTTP template with of-watchdog

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#956]
Suggestion: Powershell HTTP template with of-watchdog

## Expected Behaviour

There have been several requests from the community to have a Powershell template. I'd like someone to put one together around .NET Core and the HTTP server which is available to enable HTTP headers to be set, state to be kept warm between requests and lower latency than with the classic watchdog sample which I created originally.

This would be housed in the incubator repository along with the other similar templates. 

https://github.com/openfaas-incubator/of-watchdog

https://github.com/openfaas-incubator/powershell-template

**Comment by alexellis** [comment]
This looks like it might be useful for hosting the HTTP server in .NET:

https://4sysops.com/archives/building-a-web-server-with-powershell/

It makes use of the HttpListener class from .NET 2.0 - https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.start?view=netframework-4.7.2

**Comment by alexellis** [comment]
@acornies @burtonr are either of you interested in having a go at this?

**Comment by burtonr** [comment]
If nobody else pops in to look into this, I will give it a try this weekend. Thanks for sharing the links!

**Comment by acornies** [comment]
Thanks @burtonr! Lemme know how far you get since this is really interesting to me. I could provide a second pass if you need it.

**Comment by alexellis** [comment]
Let's get the code up here in a PR when something's ready? https://github.com/openfaas-incubator/powershell-http-template

**Comment by burtonr** [comment]
I've been working on this, and was able to get it working when running as a powershell script. However, when I put it into a function, an error is returned. 

Please check it out here: https://github.com/burtonr/powershell-http-template/tree/burtonr-template

This is the response always:
```
$ docker service logs posh-test
posh-test.1.l68bah1hznjz@pop-os    | 2018/11/18 22:24:23 POST / - 404 Not Found - ContentLength: 30
posh-test.1.l68bah1hznjz@pop-os    | 2018/11/18 22:24:23 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 200 OK\r\nServer: Microsoft-NetCore/2.0\r\nDate: Sun, 18 Nov 2018 22:24:23 GMT\r\nConnection: close\r\n\r\n"; err=<nil>
```

From the OpenFaaS Portal:
![screenshot from 2018-11-18 16-32-28](https://user-images.githubusercontent.com/12687192/48678927-9506e180-eb4f-11e8-9fd4-cb8961859d01.png)

**Comment by burtonr** [comment]
I've done some more work with this in the openfaas-incubator project. A PR is ready, and I'd really appreciate any feedback: https://github.com/openfaas-incubator/powershell-http-template/pull/1

**Comment by burtonr** [comment]
This is complete as the PR has been merged in the openfaas-incubator project: https://github.com/openfaas-incubator/powershell-http-template/pull/1

**Comment by burtonr** [comment]
Derek close:completed
