### ISSUE TITLE
Proposal: Distribute the 'watchdog' binary in a more consistent manner

### ISSUE THREAD

**Issue by rdimitrov** [openfaas/faas#957]
Hello, 

The idea is to distribute the `watchdog/of-watchdog` binaries using the [`licence-check`](https://github.com/alexellis/license-check) approach.

Basically instead of doing - 

```
RUN apk --no-cache add curl \
   && curl -sL https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog > /usr/bin/fwatchdog \
   && chmod +x /usr/bin/fwatchdog
``` 
we can use something more consistent like - 
```
RUN apk --no-cache add curl \
   && curl -sLSf https://raw.githubusercontent.com/openfaas/faas/releases/master/get.sh | sh
```
and handle the architecture differences and the version pinning on-the-go through the [`get.sh`](https://github.com/alexellis/license-check/blob/master/get.sh) script.

Draft example using the `licence-check` get.sh script:
```
#!/bin/sh

uname=$(uname)

suffix=""
case $uname in
"Darwin")
suffix="-darwin"
;;
"Linux")
    arch=$(uname -m)
    echo $arch
    case $arch in
    "aarch64")
    suffix="-arm64"
    ;;
    esac
    case $arch in
    "armv6l" | "armv7l")
    suffix="-armhf"
    ;;
    esac
;;
esac

version=0.9.6

url="https://github.com/openfaas/faas/releases/download/$version/fwatchdog${suffix}"

curl -fsSL $url > /usr/bin/fwatchdog
chmod +x /usr/bin/fwatchdog
```

## Expected Behaviour

1. Pin the desired watchdog release and handle any future updates through a single file.

2. Also handling the architecture differences through the script might reduce maintaining multiple instances of the same sample function for each platform. 

## Current Behaviour

When a new release is available, manually update each related Dockerfile, keeping in mind the architecture differences.

## Possible Solution

Update each Dockerfile applying the suggested changes.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
My primary concern with this approach is that we lose the ability to pin to a specific version. What suggestions do you have?

One alternative I have in mind is to use a published Docker image with the various watchdog versions per platform and to use a multi-stage build to pull in a tagged version - i.e.

```
FROM openfaas/watchdog:0.9.10 watchdog
FROM node:10.0
COPY --from watchdog /fwatchdog /usr/bin/fwatchdog
```

**Comment by rdimitrov** [comment]
@alexellis: Using a Docker image sure seems cleaner than what we use so far. I'm having a couple of thoughts though:
1) This way we'll still have to explicitly specify the platform (for ex. in the image name) 
2) When there's a new release/image, we'll still have to apply the new version in each Dockerfile that is using it, right?

As for using a script, perhaps pinning to a specific version can happen by passing it as an argument to the `get.sh` script (default being the latest watchdog release).

**Comment by 0xdevalias** [comment]
Another alternative to consider is using dockerfile args, and passing it in that way? Then we could have a `build.sh` type script that uses a method similar to above to grab the latest master by default, or uses the specified version otherwise.

Syntax may not be perfect:

```
ARG WATCHDOG_VER

RUN apk --no-cache add curl \
   && curl -sL https://github.com/openfaas/faas/releases/download/${WATCHDOG_VER}/fwatchdog > /usr/bin/fwatchdog \
   && chmod +x /usr/bin/fwatchdog
```

Personally I prefer the docker image and `COPY --from`, but figured i'd mention things here for completeness.

**Comment by alexellis** [comment]
Derek close via #969
