### ISSUE TITLE
Invoking subprocess in ENV fprocess

### ISSUE THREAD

**Issue by josephwinston** [openfaas/faas#967]
I am using my own `Dockerfile` and it is based on `template/python3/Dockerfile`.

I am trying to use `subprocess.run` from `python` since I need to invoke another program.  However, stdout and stderr are set to -1 before invoking `subprocess.run`.  This causes the following traceback:

```
Traceback (most recent call last):
  File "index.py", line 25, in <module>
    ret = handler.handle(st)
  File "/home/app/function/handler.py", line 230, in handle
    verbose)
  File "/home/app/function/handler.py", line 129, in runCommand
    check=False)
  File "/home/app/miniconda3/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/app/miniconda3/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/home/app/miniconda3/lib/python3.7/subprocess.py", line 1447, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int
```

Any suggestions other than, "don't do this"?

**Comment by josephwinston** [comment]
The sample program works <https://github.com/josephwinston/OpenFaaS-Subprocess>.  Now to find out why my example files.

**Comment by alexellis** [comment]
Hi @josephwinston I noticed that you closed the issue? Did you resolve the problem you had and can you tell us more? 

Alex

**Comment by josephwinston** [comment]
Thanks for asking.  The problem was completely on my side.  In the middle of my argument list on of the arguments was an integer and *not* a string.

**Comment by alexellis** [comment]
I would recommend against using `subprocess` since it may be hard to keep track of what processes you're creating - especially if the outer program crashes. What about using the blog post I sent over as an example and running the CLI commands in another image as their own function?

**Comment by josephwinston** [comment]
I started with the resource you sent.  However,  here are the issues that I am trying to solve:

- The data required by the function is a very large binary file.
- The result is also a very large file that more times than not will be binary (parquet is the normal format)
- The function may be written in a language like c# or even Fortran.  
    - Note that <https://github.com/openfaas/templates/blob/master/template/csharp/Program.cs> only works for text
- The existing functions/programs in c# and Fortran don't know how to read/write from stdin/stderr.  
    - More than often, they expect a local file. 
 
By having a driver in Python, it makes it "easier" to parse the input and then handle the I/O by reading the file from a HTTP server, invoking the existing code,  and then writing the file to another HTTP server. 

I'll be happy to help with writing a binary handler for the c# if you think that this is the way forward.
