### ISSUE TITLE
Proposal: Publish Docker image(s) with watchdog binary

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#969]
## Description

We currently need to install curl / wget to fetch the watchdog / of-watchdog binary for templates. What if we published a set of docker images with each watchdog binary per platform - or one larger docker image with all inside and then used that to speed up the build?

```
FROM openfaas/watchdog:0.9.11 as watchdog
FROM go:1.1.1
COPY --from watchdog /fwatchdog /usr/bin/watchdog
```

Our images would be easier to maintain as per above vs:

```
FROM golang:1.10.4-alpine3.8 as builder

RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && apk del curl --no-cache
```

What do we think? Perhaps it might help with #957 via @rdimitrov

**Comment by roncrivera** [comment]
This sounds good to me.

I wanted to pick this up once this proposal is approved.
