### ISSUE TITLE
Proposal: faas-netes should honor com.openfaas.scale.min=0

### ISSUE THREAD

**Issue by cedricvidal** [openfaas/faas#978]
## Expected Behaviour

When setting com.openfaas.scale.min to 0 like in the following example, I would expect my function to be deployed with 0 replicas but is isn't.

## Current Behaviour
Currently, the `com.openfaas.scale.min` is only honored when `> 0` which basically means that the deployment replicas can never be 0 upon deployment.

See https://github.com/openfaas/faas-netes/blob/master/handlers/deploy.go#L405
`if err == nil && minReplicas > 0 {`

## Possible Solution
`if err == nil && minReplicas >= 0 {`

## Steps to Reproduce (for bugs)

`faas deploy -f stack.yml`

stack.yml :
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  java8-echo:
    lang: java8
    handler: ./java8-echo
    image: java8-echo:latest
    labels:
      com.openfaas.scale.min: "0"
```

1 replica will be deployed instead of 0

## Context
For the context, I would like to use OpenFAAS to deploy GPU deep learning models to multiple demo environments. Since they are very heavy and costly to run, I would like them to be only started when actually used.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
[34m  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

[0mCLI:
 commit:  b24c5763d9b61e0c04018a722f8f2f765498f18a
 version: 0.7.8

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.9.10
 sha:     b4c12f824bcea6b3038f5c878001f72e6a57de1e
 commit:  Make use of cache in scaling


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.6.3 
 sha:           62766ad0c4b2ce713df26172faa51f56b1a955ce
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.10.3
  StackAPI:         v1beta2
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
OSX

* Link to your project or a code example to reproduce issue:
Verbatim java8 sample

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Scale to zero is achieved through use of faas-idler and the label: `com.openfaas.scale.zero: true`
