### ISSUE TITLE
UI: Bundle all required JS dependencies

### ISSUE THREAD

**Issue by masarak** [openfaas/faas#982]
## Expected Behaviour
The UI should work, in any environment, on any network.

## Current Behaviour
The UI relies on importing JS dependencies from the internet through `<script>` tags in the `index.html`, which means it does not work anywhere where there is no internet connection.

## Possible Solution
Bundling minified versions of the dependencies and loading them locally providing a self contained application capable of working within the ethos of Docker.

## Context
We are trying to run this in an environment with no internet connection.

Happy to make the simple changes myself and submit a PR.

**Comment by bartsmykla** [comment]
@masarak I think that it's reasonable. Question if we want to add statics manually or implement some building solution (webpack) as a docker build step.

**Comment by SpeedyH30** [comment]
Completely agree defeats the point of using docker else.

**Comment by masarak** [comment]
@bartsmykla Agree with that. Currently it is static in the sense that they're just hardcoded links to defined versions on the `googleapis` site. It is also a rather old version.

In my eyes the best proposal would be to rip out the client completely and build it as its own standalone project with its own image that can be deployed/scaled by itself. For now, if it works, don't change it, and just bundle what it's currently using so that it can be used anywhere.

**Comment by omerzamir** [comment]
We tried running it on an offline environment too and bumped the same issue described... 

Fixing it would be very helpful.

**Comment by alexellis** [comment]
Derek close: duplicate

**Comment by alexellis** [comment]
Hi folks,

Work was started for this in two separate PRs:

https://github.com/openfaas/faas/pull/858

and

https://github.com/openfaas/faas/pull/855

It didn't get completed, but we've had previous requests for this from people who are blocked from using CDNs.

I'd like someone from the core contributor or members group to do this work and we can move quickly to get it packaged in a new point release.

Alex

**Comment by alexellis** [comment]
I can't find the original issue so I'm going to re-open and mark as duplicate with a label for tracking.

**Comment by alexellis** [comment]
Derek reopen
