### ISSUE TITLE
Support: Help needed using private Docker registry with Swarm

### ISSUE THREAD

**Issue by matthewdolman** [openfaas/faas#985]
## Expected Behaviour

I am developing the function locally, I build locally and push the image to my git repository.  Then I deploy to open-faas server.  The open-faas server should pull the image from the git repository and deploy the function.

## Current Behaviour

The image for the function should be pulled by the faas server and the function deployed.

## Steps to Reproduce (for bugs)

1. In stack.yml image for the function is `my.gitlab.com/project/function:latest` 
2 .`faas-cli up -f stack.yml -g http://my-gateway:8080`

## Context

It seems that this should be pretty standard behaviour and I do not know if I am doing something wrong.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
  CLI:
   commit:  70ebebb71f015f4edb0c3e1f03ef3d262b1d84f6
   version: 0.7.7

* Docker version `docker version` (e.g. Docker 17.0.05 ):
  Client: Docker Engine - Community
   Version:           18.09.0
   API version:       1.39
   Go version:        go1.10.4
   Git commit:        4d60db4
   Built:             Wed Nov  7 00:47:51 2018
   OS/Arch:           windows/amd64
   Experimental:      false
  
  Server: Docker Engine - Community
   Engine:
    Version:          18.09.0
    API version:      1.39 (minimum version 1.12)
    Go version:       go1.10.4
    Git commit:       4d60db4
    Built:            Wed Nov  7 00:55:00 2018
    OS/Arch:          linux/amd64
    Experimental:     false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
  Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
  Windows 10 Professional

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi,

Thanks for using OpenFaaS.

This functionality is a core feature of OpenFaaS. I'm not aware of any issues.

Do you use authentication with your registry? If so you'll need to send your registry authentication over the wire on each deployment, see `faas-cli deploy --help`

```
  -a, --send-registry-auth       send registryAuth from Docker credentials manager with the request
```

Alex

**Comment by rgee0** [comment]
Can we clarify some terminology here, please?  The image should be pushed to and pulled from a container registry, rather than a git repo.  Are you using the container registry feature of Gitlab?

What is the output of `faas-cli up -f stack.yml -g http://my-gateway:8080`?

**Comment by matthewdolman** [comment]
Alex's response fixed the issue.

GitLab has a container registry as well as being a git repo.

**Comment by rgee0** [comment]
Derek close: resolved

**Comment by alexellis** [comment]
Thanks for closing Richard.

FYI ` -a, --send-registry-auth` is only required for Swarm. Kubernetes handles registry auth in a more decoupled way. (more in the docs)

You're also welcome to [join Slack](https://docs.openfaas.com/community)
