### ISSUE TITLE
Starting using docker-swarm

### ISSUE THREAD

**Issue by pascalandy** [openfaas/faas#989]
Hello folks,
I'm trying to follow along: https://docs.openfaas.com/deployment/docker-swarm/

### Password

Can't find it ~/.openfaas/config.yaml

![screen shot 2018-12-01 at 7 55 20 pm](https://user-images.githubusercontent.com/6694151/49334397-1c6a4100-f5a3-11e8-8b6c-af9753b7d51d.jpg)

### Sample function

When running:

```
faas deploy -f \
  https://raw.githubusercontent.com/openfaas/faas/master/stack.yml
```

getting errors.

![screen shot 2018-12-01 at 7 52 38 pm](https://user-images.githubusercontent.com/6694151/49334404-3c9a0000-f5a3-11e8-8184-3d0bdc81455d.jpg)

![screen shot 2018-12-01 at 7 52 09 pm](https://user-images.githubusercontent.com/6694151/49334406-40c61d80-f5a3-11e8-97bc-9571c093d9f4.jpg)

![screen shot 2018-12-01 at 7 58 59 pm](https://user-images.githubusercontent.com/6694151/49334417-95699880-f5a3-11e8-962b-0c4d1a5c32dc.jpg)

### Basic stuff

I know it's all basic stuff basic I can't seems to find how to start.
Running Docker for mac. Thanks!

**Comment by rgee0** [comment]
When you ran:
```
$ git clone https://github.com/openfaas/faas && \
  cd faas && \
  ./deploy_stack.sh
```
You will have been provided with some credentials which you would use with the CLI to log in to the gateway: 
```
echo -n <some_hash_secret> | faas-cli login --username=admin --password-stdin
```
Then you should have a `config.yaml`

**Comment by alexellis** [comment]
This might help too -> https://docs.openfaas.com/deployment/troubleshooting/#i-forgot-my-gateway-password

**Comment by alexellis** [comment]
Hi Andy, I assume you may be travelling to Barcelona for Dockercon so I've tried this scenario out with the latest Docker for Mac Edge edition:

https://gist.github.com/alexellis/4a239cb355c9c289f986ec5a2a957c10

Here are my logs ^

The other thing to think about is whether you have "Kubernetes" enabled and are deploying using the Docker Compose Stack file to Kubernetes?

I'l close the issue, but please feel free to keep commenting. 

Alex

**Comment by pascalandy** [comment]
Hello Alex,
My first name is Pascal :-p

No, I won't be part of Dockercon Barcelona. 
I also don't use KB8 at all and stick to Swarm.

Thanks to your password-recovery trick, everything runs normally now!

My end goal is to use (only) the faas-cli. I have dozen and dozen of functions and I would love them to run on faas.

Thanks for this beautiful project!

**Comment by alexellis** [comment]
Thanks, glad you got what you needed and I'll try to unlearn your name as Andy 😄 

If you find our work useful, please consider supporting it work via https://www.openfaas.com/donate
