### ISSUE TITLE
UI: Refresh image tag on periodic basis

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#990]
## Expected Behaviour

The image tag should change when deploying a new version in the UI.

## Current Behaviour

The state has changed in the cluster but is cached on the UI for efficiency and shows the older tag version. This was confusing for one of our users "zeeque" who reported this on Slack.

## Possible Solution

We just need to bust the cache or refresh the objects when we refresh the list of functions.

## Steps to Reproduce (for bugs)

1. Deploy a function
2. Update the tag
3. Deploy it again

<img width="1559" alt="screenshot 2018-12-04 at 09 58 09" src="https://user-images.githubusercontent.com/6358735/49439408-d5559900-f7b8-11e8-8cc9-795e373bdddf.png">

**Comment by LucasRoesler** [comment]
Derek assign: me
