### ISSUE TITLE
Proposal: Make metrics endpoint configurable

### ISSUE THREAD

**Issue by hxalid** [openfaas/faas#998]
Not all Prometheus setups are configured to scrape '/metrics' endpoint and
therefore, it would be nice to have a configurable metrics endpoint in order to have a consistent Prometheus config for different systems.

## Possible Solution

Metrics endpoint could be configurable via 'metrics_endpoint'
environment variable with a default being '/metrics'.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek add label: design/review

**Comment by alexellis** [comment]
This is not approved for PR. Please see my comments on the PR you raised
